import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-01";

const source = (
  label: string,
  url: string,
  kind: Source["kind"],
  supports: string,
): Source => ({ label, url, kind, checkedAt, supports });

const sources = {
  atlasPi: source(
    "VITA Group · Zhangyang ‘Atlas’ Wang",
    "https://www.vita-group.space/pi",
    "profile",
    "Education history, UIUC PhD adviser, and professional timeline",
  ),
  vitaRoster: source(
    "VITA Group · Team and alumni roster",
    "https://www.vita-group.space/team",
    "profile",
    "Named current PhD/postdoctoral roster, alumni dates, co-advising notes and current destinations",
  ),
  uiucDissertation: source(
    "UIUC IDEALS · Task-specific and interpretable feature learning",
    "https://www.ideals.illinois.edu/items/98676",
    "thesis",
    "Zhangyang Wang's 2016 ECE dissertation and Thomas S. Huang as director / adviser",
  ),
  guoliangHome: source(
    "Guoliang Kang · academic homepage",
    "https://kgl-prml.github.io/",
    "profile",
    "UT Austin postdoctoral work with Philipp Krähenbühl and Atlas Wang",
  ),
  guoliangBuaa: source(
    "北京航空航天大学自动化学院 · 康国梁",
    "https://dept3.buaa.edu.cn/szjs/zzjs/znxtykzgcx/js/2.htm",
    "official",
    "Current professor and doctoral-adviser roster",
  ),
  wuyangSfu: source(
    "Simon Fraser University · Wuyang Chen",
    "https://www.sfu.ca/fas/computing/people/faculty/faculty-members/wuyang-chen.html",
    "official",
    "Current assistant professorship, 2023 UT Austin PhD and research areas",
  ),
  wuyangLab: source(
    "DeLTA Lab · Wuyang Chen",
    "https://delta-lab-ai.github.io/",
    "profile",
    "Independent lab leadership and research programme",
  ),
  tianlongHome: source(
    "Tianlong Chen · academic homepage",
    "https://tianlong-chen.github.io/",
    "profile",
    "UNC faculty role, UT Austin PhD and explicit acknowledgement of adviser Atlas Wang",
  ),
  shiweiHome: source(
    "Shiwei Liu · academic homepage",
    "https://shiweiliuiiiiiii.github.io/",
    "profile",
    "ELLIS/MPI independent-PI role and explicit UT Austin postdoctoral work with Atlas Wang",
  ),
  yuningCuhksz: source(
    "CUHK-Shenzhen · Yuning You",
    "https://sse.cuhk.edu.cn/en/faculty/youyuning",
    "official",
    "Current assistant professorship, TAMU PhD and research programme",
  ),
  ziweiHku: source(
    "HKU Scholars Hub · Ziwei Yang",
    "https://repository.hku.hk/cris/rp/rp03531",
    "official",
    "Current HKU research faculty role and explicit postdoctoral work in Atlas Wang's group",
  ),
  junyuanNus: source(
    "NUS ECE · Hong Junyuan",
    "https://cde.nus.edu.sg/ece/staff/hong-junyuan/",
    "official",
    "Current assistant professorship and UT Austin training",
  ),
  junyuanHome: source(
    "Junyuan Hong · academic homepage",
    "https://jyhong.gitlab.io/",
    "profile",
    "Explicit IFML postdoctoral supervision by Atlas Wang and CoSTA Lab leadership",
  ),
  zhiwenTamu: source(
    "Texas A&M ECE · Zhiwen Fan",
    "https://engineering.tamu.edu/electrical/profiles/fan-zhiwen.html",
    "official",
    "Current assistant professorship, 2025 UT Austin PhD and research areas",
  ),
  gregoryHome: source(
    "Gregory Holste · academic homepage",
    "https://www.gholste.me/",
    "profile",
    "Weill Cornell appointment and explicit UT Austin PhD supervision by Atlas Wang",
  ),
  neelHome: source(
    "Neel P. Bhatt · academic homepage",
    "https://neel1302.github.io/",
    "profile",
    "Current UT Dallas assistant professorship and embodied-AI research programme",
  ),
  yangShenTamu: source(
    "Texas A&M ECE · Yang Shen",
    "https://engineering.tamu.edu/electrical/profiles/shen-yang.html",
    "official",
    "Current associate professorship and machine-learning / computational-biology programme",
  ),
  philippUt: source(
    "UT Austin Computer Science · Philipp Krähenbühl",
    "https://www.cs.utexas.edu/people/faculty-researchers/philipp-krahenbuhl",
    "official",
    "Current associate professorship and computer-vision research programme",
  ),
  yuningHome: source(
    "Yuning You · academic homepage",
    "https://yyou1996.github.io/",
    "profile",
    "AI for Life Sciences Lab leadership, current research programme and public recruiting notice",
  ),
  ziweiHkuMicro: source(
    "HKU Department of Microbiology · Ziwei Yang",
    "https://hkumicro.hku.hk/university-staff/dr-yang-ziwei/",
    "official",
    "Yale PhD mentorship, Atlas Wang postdoctoral training, current role and research focus",
  ),
};

type AuditedPersonInput = Omit<Person, "facts" | "lastVerifiedAt" | "x" | "y"> & {
  sources: [Source, Source, ...Source[]];
  atlasConnection: string;
  education: { value: string; source: Source };
  career?: { value: string; source: Source };
  recruiting?: { value: string; source: Source };
};

const auditedPerson = (input: AuditedPersonInput, index: number): Person => {
  const { atlasConnection, education, career, recruiting, ...person } = input;
  return {
    ...person,
    x: 160 + (index % 4) * 180,
    y: 180 + Math.floor(index / 4) * 170,
    lastVerifiedAt: checkedAt,
    introducedAt: checkedAt,
    facts: [
      { label: "当前任职", value: person.role, source: person.sources[0] },
      { label: "Atlas Wang 培养网络", value: atlasConnection, source: person.sources[1] },
      { label: "研究主线", value: person.area, source: person.sources[0] },
      { label: "教育与学术训练", value: education.value, source: education.source },
      ...(career ? [{ label: "职业轨迹", value: career.value, source: career.source }] : []),
      ...(recruiting ? [{ label: "公开招生", value: recruiting.value, source: recruiting.source }] : []),
    ],
  };
};

/**
 * Faculty / independent-PI alumni missing from the current people graph, plus
 * the two explicitly named co-mentors needed to preserve joint supervision.
 * No node below was created from ordinary co-authorship.
 */
export const atlasWangLineageAuditPeople: Person[] = [
  auditedPerson({
    id: "guoliang-kang-buaa-atlas",
    name: "康国梁",
    role: "Professor · PhD Adviser",
    institution: "BUAA",
    region: "Mainland China",
    area: "Computer Vision · Domain Adaptation · Video Understanding",
    tags: ["计算机视觉", "领域适应", "视频理解", "Atlas Wang 博后谱系"],
    summary: "北航教授、博士生导师；曾在 UT Austin 由 Atlas Wang 与 Philipp Krähenbühl 共同指导博士后研究。",
    stage: "senior",
    category: "core",
    primary: true,
    sources: [sources.guoliangBuaa, sources.guoliangHome, sources.vitaRoster],
    atlasConnection: "VITA 名录及本人主页均记录其 2021 年在 UT Austin 与 Atlas Wang、Philipp Krähenbühl 开展博士后研究。",
    education: { value: "2019 年获 University of Technology Sydney 博士，导师为 Yi Yang。", source: sources.guoliangHome },
    career: { value: "先后在 CMU 与 UT Austin 从事博士后研究，现任北航教授、博士生导师。", source: sources.guoliangHome },
  }, 0),
  auditedPerson({
    id: "wuyang-chen-sfu-atlas",
    name: "Wuyang Chen",
    role: "Assistant Professor · School of Computing Science",
    institution: "SFU",
    region: "Canada",
    area: "Deep Learning · Scientific ML · AI for Math · Computer Vision",
    tags: ["深度学习", "科学机器学习", "AI for Math", "计算机视觉", "Atlas Wang 博士谱系"],
    summary: "SFU DeLTA Lab 负责人，2023 年获 UT Austin ECE 博士；研究从深度学习理论延伸到科学推理与可验证代码生成。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.wuyangSfu, sources.vitaRoster, sources.wuyangLab],
    atlasConnection: "VITA 官方校友名录将其列为 Atlas Wang 的 2019–2023 年 PhD 学生。",
    education: { value: "2023 年获 UT Austin ECE 博士；此前获 Rice CS 硕士与中科大生物科学学士。", source: sources.wuyangSfu },
    career: { value: "博士毕业后在 UC Berkeley 与 Michael Mahoney 开展博士后研究，2024 年加入 SFU 并创建 DeLTA Lab。", source: sources.wuyangLab },
  }, 1),
  auditedPerson({
    id: "tianlong-chen-unc-atlas",
    name: "Tianlong Chen",
    role: "Assistant Professor · Computer Science",
    institution: "UNC",
    region: "United States",
    area: "Efficient & Trustworthy AI · Foundation Models · LLMs · Multimodal Learning",
    tags: ["高效 AI", "可信 AI", "基础模型", "LLM", "Atlas Wang 博士谱系"],
    summary: "UNC UNITES Lab 负责人，研究大模型效率、可信性、稀疏化与多模态学习。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.tianlongHome, sources.vitaRoster],
    atlasConnection: "本人主页明确感谢 PhD adviser Atlas Wang；VITA 名录记录其 2019–2023 年博士培养期。",
    education: { value: "中科大应用数学学士与计算机工程学士；2023 年获 UT Austin ECE 博士。", source: sources.tianlongHome },
    career: { value: "2023–2024 年在 MIT CSAIL、Harvard BMI 与 Broad Institute 从事博士后研究，2024 年加入 UNC。", source: sources.tianlongHome },
    recruiting: { value: "UNITES Lab 主页公开招募 PhD、博士后、RA/TA、访问学生与实习生。", source: sources.tianlongHome },
  }, 2),
  auditedPerson({
    id: "shiwei-liu-ellis-atlas",
    name: "Shiwei Liu",
    role: "Principal Investigator, ELLIS Institute Tübingen · Group Leader, MPI-IS",
    institution: "Tübingen/MPI",
    region: "Europe",
    area: "Efficient Foundation Models · Pre-training · Post-training · Model Compression",
    tags: ["基础模型", "预训练", "后训练", "模型压缩", "Atlas Wang 博后谱系"],
    summary: "ELLIS Institute Tübingen PI 与 MPI-IS Group Leader，研究高效基础模型训练、推理和压缩。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.shiweiHome, sources.vitaRoster],
    atlasConnection: "本人主页明确记录其博士后阶段与 Atlas Wang 工作；VITA 名录给出 2022–2023 年培养期。",
    education: { value: "获 Eindhoven University of Technology 博士，导师为 Mykola Pechenizkiy 与 Decebal Constantin Mocanu。", source: sources.shiweiHome },
    career: { value: "UT Austin 博士后之后任 Oxford 博士后与 Somerville College Junior Research Fellow，现领导 ELLIS/MPI-IS 团队。", source: sources.shiweiHome },
    recruiting: { value: "本人主页公开招募位于 ELLIS Institute Tübingen 的博士生与博士后。", source: sources.shiweiHome },
  }, 3),
  auditedPerson({
    id: "yuning-you-cuhksz-atlas",
    name: "Yuning You",
    chinese: "游宇宁",
    role: "Assistant Professor · Presidential Young Fellow",
    institution: "CUHK-Shenzhen",
    region: "Mainland China",
    area: "Graph Machine Learning · Generative Modeling · ML for Cell Biology",
    tags: ["图机器学习", "生成模型", "AI for Biology", "共同指导", "Atlas Wang 博士谱系"],
    summary: "港中大（深圳）助理教授，研究图自监督学习、生成建模与生命科学模拟。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.yuningCuhksz, sources.vitaRoster, sources.yuningHome],
    atlasConnection: "VITA 名录明确记录其 2019–2024 年博士阶段由 Atlas Wang 与 Yang Shen 共同指导。",
    education: { value: "西安交大工学学士；2024 年获 Texas A&M ECE 博士，随后在 Caltech 从事博士后研究。", source: sources.yuningCuhksz },
    career: { value: "2025 年加入港中大（深圳），创建 AI for Life Sciences Laboratory。", source: sources.yuningHome },
    recruiting: { value: "实验室主页明确公开招募 AI 与生命科学方向学生和青年研究人员。", source: sources.yuningHome },
  }, 4),
  auditedPerson({
    id: "ziwei-yang-hku-atlas",
    name: "Ziwei Yang",
    chinese: "楊子維",
    role: "Research Assistant Professor · Department of Microbiology",
    institution: "HKU",
    region: "Hong Kong",
    area: "Structural Virology · AI for Infectious Disease · Single-cell Learning",
    tags: ["AI for Medicine", "结构病毒学", "单细胞学习", "Atlas Wang 博后谱系"],
    summary: "HKU Medicine 研究助理教授，将结构病毒学、单分子成像与 AI 驱动的感染诊断结合。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.ziweiHku, sources.vitaRoster, sources.ziweiHkuMicro],
    atlasConnection: "HKU 官方履历明确写明其在 UT Austin 的 Atlas Wang 研究组从事博士后研究。",
    education: { value: "获 Yale University 博士，导师为 Walther Mothes，研究 HIV 与 SARS-CoV-2 的结构病毒学。", source: sources.ziweiHkuMicro },
    career: { value: "Yale 博士毕业后在 UT Austin 将机器学习用于感染诊断，现于 HKU Medicine 融合结构病毒学、单分子成像与 AI。", source: sources.ziweiHkuMicro },
  }, 5),
  auditedPerson({
    id: "junyuan-hong-nus-atlas",
    name: "Junyuan Hong",
    role: "Assistant Professor · Electrical and Computer Engineering",
    institution: "NUS",
    region: "Singapore",
    area: "Trustworthy AI · LLM Safety & Privacy · Healthcare AI",
    tags: ["可信 AI", "LLM 安全", "隐私", "医疗 AI", "Atlas Wang 博后谱系"],
    summary: "NUS CoSTA Lab 负责人，研究大模型隐私、公平、鲁棒性、安全以及认知健康应用。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.junyuanNus, sources.junyuanHome, sources.vitaRoster],
    atlasConnection: "本人主页明确记录其 IFML 博士后由 Atlas Wang 指导；VITA 名录给出 2023–2025 年培养期。",
    education: { value: "中科大物理学学士；2017 年获 Michigan State CS 硕士、2023 年获 CSE 博士，博士导师为 Jiayu Zhou。", source: sources.junyuanHome },
    career: { value: "先后在 UT Austin IFML 与 Massachusetts General Hospital / Harvard Medical School 开展研究，2026 年加入 NUS。", source: sources.junyuanHome },
  }, 6),
  auditedPerson({
    id: "zhiwen-fan-tamu-atlas",
    name: "Zhiwen Fan",
    role: "Assistant Professor · Electrical and Computer Engineering",
    institution: "Texas A&M",
    region: "United States",
    area: "Multimodal Learning · Generative AI · Robotics · Spatial Computing",
    tags: ["多模态学习", "生成式 AI", "机器人", "空间智能", "Atlas Wang 博士谱系"],
    summary: "Texas A&M ECE 助理教授，研究多模态生成、三维空间智能、机器人与世界模型。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.zhiwenTamu, sources.vitaRoster],
    atlasConnection: "VITA 名录记录其 2021–2025 年在 Atlas Wang 的 VITA Group 完成 PhD；TAMU 官方页确认其 UT Austin ECE 博士背景。",
    education: { value: "2025 年获 UT Austin Electrical and Computer Engineering 博士。", source: sources.zhiwenTamu },
    career: { value: "博士毕业后加入 Texas A&M ECE 任助理教授，研究多模态生成、空间智能与机器人。", source: sources.zhiwenTamu },
  }, 7),
  auditedPerson({
    id: "gregory-holste-cornell-atlas",
    name: "Gregory Holste",
    role: "Assistant Professor · Weill Cornell Medicine (from September 2026)",
    institution: "Cornell",
    region: "United States",
    area: "Medical AI · Computer Vision · Multimodal Learning · Cardiovascular Imaging",
    tags: ["医疗 AI", "计算机视觉", "多模态学习", "心血管影像", "Atlas Wang 博士谱系"],
    summary: "Weill Cornell Medicine 助理教授，研究医疗影像、多模态学习与心血管健康 AI。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.gregoryHome, sources.vitaRoster],
    atlasConnection: "本人主页明确写明 UT Austin ECE PhD 由 Atlas Wang 指导，并记录 2026 年完成答辩。",
    education: { value: "Kenyon College 数学与统计学学士；UT Austin ECE 硕士与博士，博士导师为 Atlas Wang。", source: sources.gregoryHome },
    career: { value: "2026 年完成博士答辩，计划于 2026 年 9 月加入 Weill Cornell Medicine 任助理教授。", source: sources.gregoryHome },
    recruiting: { value: "本人主页公布即将招募 medical AI 博士后。", source: sources.gregoryHome },
  }, 8),
  auditedPerson({
    id: "neel-bhatt-utd-atlas",
    name: "Neel P. Bhatt",
    role: "Assistant Professor · Systems Engineering",
    institution: "UT Dallas",
    region: "United States",
    area: "Neurosymbolic AI · Embodied Autonomy · Formal Verification · Robotics",
    tags: ["神经符号 AI", "具身智能", "形式验证", "机器人", "Atlas Wang 博后谱系"],
    summary: "UT Dallas Systems Engineering 助理教授，研究可验证神经符号 AI、具身自主系统和机器人。",
    stage: "emerging",
    category: "core",
    primary: true,
    sources: [sources.neelHome, sources.vitaRoster],
    atlasConnection: "VITA 名录将其列为 2023–2026 年博士后校友；本人主页确认其 2026 年加入 UT Dallas。",
    education: { value: "University of Toronto 机械工程学士；2023 年获 University of Waterloo 机电一体化工程博士。", source: sources.neelHome },
    career: { value: "2023–2026 年在 UT Austin 从事博士后与 DARPA 项目研究，2026 年加入 UT Dallas。", source: sources.neelHome },
    recruiting: { value: "本人主页公开接洽 2026–2027 年博士、硕士、访问学生与实习生。", source: sources.neelHome },
  }, 9),
  auditedPerson({
    id: "yang-shen-tamu-atlas-audit",
    name: "Yang Shen",
    role: "Associate Professor · Electrical and Computer Engineering",
    institution: "Texas A&M",
    region: "United States",
    area: "Machine Learning · Computational Biology · Generative AI · Protein Design",
    tags: ["机器学习", "计算生物学", "蛋白质设计", "共同指导"],
    summary: "Texas A&M ECE 副教授，Yuning You 博士阶段的共同导师之一。",
    stage: "senior",
    category: "adjacent",
    primary: false,
    sources: [sources.yangShenTamu, sources.vitaRoster],
    atlasConnection: "VITA 名录将 Yang Shen 明确列为 Yuning You 与 Atlas Wang 的共同博士导师。",
    education: { value: "2002 年获中科大自动化学士，2008 年获 Boston University Systems Engineering 博士。", source: sources.yangShenTamu },
    career: { value: "现任 Texas A&M ECE 副教授，并兼任 CSE affiliated faculty。", source: sources.yangShenTamu },
  }, 10),
  auditedPerson({
    id: "philipp-krahenbuhl-ut-atlas-audit",
    name: "Philipp Krähenbühl",
    role: "Associate Professor · Computer Science",
    institution: "UT Austin",
    region: "United States",
    area: "Computer Vision · Machine Learning · Computer Graphics",
    tags: ["计算机视觉", "机器学习", "图形学", "共同博士后指导"],
    summary: "UT Austin CS 副教授，与 Atlas Wang 共同指导 Guoliang Kang 的博士后阶段。",
    stage: "senior",
    category: "adjacent",
    primary: false,
    sources: [sources.philippUt, sources.guoliangHome, sources.vitaRoster],
    atlasConnection: "Guoliang Kang 本人主页与 VITA 名录均记录其博士后由 Philipp Krähenbühl 与 Atlas Wang 共同指导。",
    education: { value: "获 Stanford Computer Science 博士，随后在 UC Berkeley 从事两年博士后研究。", source: sources.philippUt },
    career: { value: "现任 UT Austin Computer Science 副教授，研究计算机视觉、机器学习与图形学。", source: sources.philippUt },
  }, 11),
];

const lineage = (
  id: string,
  from: string,
  to: string,
  subtype: "phd_adviser" | "co_adviser" | "postdoc_mentor",
  label: string,
  evidence: string,
  evidenceSource: Source,
  endYear?: number,
): Relationship => ({
  id,
  from,
  to,
  type: "lineage",
  subtype,
  label,
  evidence,
  evidenceObject: "一手博士论文、学校/本人履历或实验室官方培养名录；不以普通合著推断师承",
  source: evidenceSource,
  verified: true,
  endYear,
});

/** Adviser / postdoctoral mentor points to the trainee. */
export const atlasWangLineageAuditRelationships: Relationship[] = [
  lineage("atlas-audit-atlas-guoliang-postdoc", "atlas-wang-us", "guoliang-kang-buaa-atlas", "postdoc_mentor", "共同博士后指导", "Guoliang Kang 本人主页与 VITA 名录均记录其在 UT Austin 与 Atlas Wang、Philipp Krähenbühl 从事博士后研究。", sources.guoliangHome, 2021),
  lineage("atlas-audit-philipp-guoliang-postdoc", "philipp-krahenbuhl-ut-atlas-audit", "guoliang-kang-buaa-atlas", "postdoc_mentor", "共同博士后指导", "Guoliang Kang 本人主页明确写明其 UT Austin 博士后与 Philipp Krähenbühl、Atlas Wang 共同工作。", sources.guoliangHome, 2021),
  lineage("atlas-audit-atlas-wuyang-phd", "atlas-wang-us", "wuyang-chen-sfu-atlas", "phd_adviser", "博士导师", "VITA 官方校友名录将 Wuyang Chen 列为 2019–2023 年 PhD 学生；SFU 官方页确认其 2023 年 UT Austin ECE 博士。", sources.vitaRoster, 2023),
  lineage("atlas-audit-atlas-tianlong-phd", "atlas-wang-us", "tianlong-chen-unc-atlas", "phd_adviser", "博士导师", "Tianlong Chen 本人主页明确感谢 adviser Atlas Wang，并记录 2023 年获得 UT Austin ECE 博士。", sources.tianlongHome, 2023),
  lineage("atlas-audit-atlas-shiwei-postdoc", "atlas-wang-us", "shiwei-liu-ellis-atlas", "postdoc_mentor", "博士后指导", "Shiwei Liu 本人主页明确写明其曾作为 UT Austin 博士后与 Atlas Wang 工作。", sources.shiweiHome, 2023),
  lineage("atlas-audit-atlas-yuning-coadviser", "atlas-wang-us", "yuning-you-cuhksz-atlas", "co_adviser", "共同博士导师", "VITA 名录明确记录 Yuning You 的 PhD 由 Atlas Wang 与 Yang Shen 共同指导。", sources.vitaRoster, 2024),
  lineage("atlas-audit-yang-shen-yuning-coadviser", "yang-shen-tamu-atlas-audit", "yuning-you-cuhksz-atlas", "co_adviser", "共同博士导师", "VITA 名录明确记录 Yuning You 的 PhD 由 Atlas Wang 与 Yang Shen 共同指导。", sources.vitaRoster, 2024),
  lineage("atlas-audit-atlas-ziwei-postdoc", "atlas-wang-us", "ziwei-yang-hku-atlas", "postdoc_mentor", "博士后指导", "HKU Scholars Hub 的本人履历明确记录 Ziwei Yang 在 UT Austin 的 Atlas Wang 研究组从事博士后研究。", sources.ziweiHku, 2024),
  lineage("atlas-audit-atlas-junyuan-postdoc", "atlas-wang-us", "junyuan-hong-nus-atlas", "postdoc_mentor", "博士后指导", "Junyuan Hong 本人主页明确记录其 IFML 博士后由 Atlas Wang 指导。", sources.junyuanHome, 2025),
  lineage("atlas-audit-atlas-zhiwen-phd", "atlas-wang-us", "zhiwen-fan-tamu-atlas", "phd_adviser", "博士导师", "VITA 名录将 Zhiwen Fan 列为 2021–2025 年 PhD 学生；TAMU 官方页确认其 UT Austin ECE 博士。", sources.vitaRoster, 2025),
  lineage("atlas-audit-atlas-gregory-phd", "atlas-wang-us", "gregory-holste-cornell-atlas", "phd_adviser", "博士导师", "Gregory Holste 本人主页明确写明其 UT Austin ECE PhD 由 Atlas Wang 指导。", sources.gregoryHome, 2026),
  lineage("atlas-audit-atlas-neel-postdoc", "atlas-wang-us", "neel-bhatt-utd-atlas", "postdoc_mentor", "博士后指导", "VITA 官方校友名录将 Neel P. Bhatt 列为 2023–2026 年博士后。", sources.vitaRoster, 2026),
];

/** Current PhD students omitted by the earlier six-person roster sample. */
export const atlasWangLineageAuditGroupMembers: GroupMember[] = [
  { id: "atlas-audit-junbo-li", teacherId: "atlas-wang-us", name: "Junbo Li", role: "PhD Student · Fall 2024–", source: sources.vitaRoster },
  { id: "atlas-audit-yuehao-wang", teacherId: "atlas-wang-us", name: "Yuehao Wang", role: "PhD Student · Fall 2024–", source: sources.vitaRoster },
  { id: "atlas-audit-kevin-wang", teacherId: "atlas-wang-us", name: "Kevin Wang", role: "PhD Student · Fall 2024–", source: sources.vitaRoster },
  { id: "atlas-audit-yeonju-ro", teacherId: "atlas-wang-us", name: "Yeonju Ro", role: "PhD Student · Spring 2025–", source: sources.vitaRoster },
  { id: "atlas-audit-jiajun-zhu", teacherId: "atlas-wang-us", name: "Jiajun Zhu", role: "PhD Student · Fall 2025–", source: sources.vitaRoster },
  { id: "atlas-audit-jinghan-ke", teacherId: "atlas-wang-us", name: "Jinghan Ke", role: "PhD Student · Fall 2025–", source: sources.vitaRoster },
  { id: "atlas-audit-john-robertson", teacherId: "atlas-wang-us", name: "John Robertson", role: "PhD Student · Fall 2025–", source: sources.vitaRoster },
  { id: "atlas-audit-zhizhou-sha", teacherId: "atlas-wang-us", name: "Zhizhou Sha", role: "PhD Student · Fall 2025–", source: sources.vitaRoster },
  { id: "atlas-audit-tushaar-gangavarapu", teacherId: "atlas-wang-us", name: "Tushaar Gangavarapu", role: "PhD Student · Fall 2025–", source: sources.vitaRoster },
  { id: "atlas-audit-jinju-kim", teacherId: "atlas-wang-us", name: "Jinju Kim", role: "PhD Student · Fall 2026–", source: sources.vitaRoster },
  { id: "atlas-audit-cissy-xie", teacherId: "atlas-wang-us", name: "Cissy Xie", role: "PhD Student · Fall 2026–", source: sources.vitaRoster },
  { id: "atlas-audit-kaijing-ma", teacherId: "atlas-wang-us", name: "Kaijing Ma", role: "PhD Student · Fall 2026–", source: sources.vitaRoster },
  { id: "atlas-audit-bei-ouyang", teacherId: "atlas-wang-us", name: "Bei Ouyang", role: "PhD Student · Fall 2026–", source: sources.vitaRoster },
];

const placement = (
  id: string,
  student: string,
  company: string,
  role: string,
  degree: StudentPlacement["degree"],
  graduationYear: number,
  sector: StudentPlacement["sector"],
  highLevel = false,
): StudentPlacement => ({
  id,
  student,
  teacherId: "atlas-wang-us",
  company,
  role,
  degree,
  graduationYear,
  sector,
  kind: "current",
  highLevel,
  verifiedAt: checkedAt,
  source: sources.vitaRoster,
});

/** Alumni destinations omitted by the earlier 15-placement sample. */
export const atlasWangLineageAuditStudentPlacements: StudentPlacement[] = [
  placement("atlas-audit-haotao-wang-qualcomm", "Haotao Wang", "Qualcomm AI Research", "Research Scientist", "PhD", 2023, "industry"),
  placement("atlas-audit-ziyu-jiang-nec", "Ziyu Jiang", "NEC Labs America", "Research Scientist", "PhD", 2023, "industry"),
  placement("atlas-audit-jiayi-shen-amazon", "Jiayi Shen", "Amazon", "Applied Scientist", "PhD", 2023, "industry"),
  placement("atlas-audit-yan-han-microsoft", "Yan Han", "Microsoft AI", "Member of Technical Staff", "PhD", 2023, "industry"),
  placement("atlas-audit-xinyu-gong-adobe", "Xinyu Gong", "Adobe Firefly", "Research Scientist", "PhD", 2023, "industry"),
  placement("atlas-audit-shiwei-liu-ellis", "Shiwei Liu", "ELLIS Institute Tübingen / MPI-IS", "Principal Investigator · Group Leader", "Postdoc", 2023, "academia", true),
  placement("atlas-audit-scott-hoang-apple", "Scott Hoang", "Apple AIML", "Senior Research Scientist · degree frozen per roster", "PhD", 2024, "industry", true),
  placement("atlas-audit-yuning-you-cuhksz", "Yuning You", "CUHK-Shenzhen", "Assistant Professor · Presidential Young Fellow", "PhD", 2024, "academia", true),
  placement("atlas-audit-dejia-xu-luma", "Dejia Xu", "Luma AI", "Research Scientist", "PhD", 2025, "industry"),
  placement("atlas-audit-ziwei-yang-hku", "Ziwei Yang", "The University of Hong Kong", "Research Assistant Professor · Medicine", "Postdoc", 2024, "academia"),
  placement("atlas-audit-junyuan-hong-nus", "Junyuan Hong", "National University of Singapore", "Assistant Professor · ECE", "Postdoc", 2025, "academia", true),
  placement("atlas-audit-zhiwen-fan-tamu", "Zhiwen Fan", "Texas A&M University", "Assistant Professor · ECE", "PhD", 2025, "academia", true),
  placement("atlas-audit-ajay-jaiswal-apple", "Ajay Jaiswal", "Apple AIML", "Research Scientist", "PhD", 2025, "industry"),
  placement("atlas-audit-wes-robbins-clearview", "Wes Robbins", "Clearview AI", "Research Engineer · degree frozen per roster", "PhD", 2025, "industry"),
  placement("atlas-audit-xuxi-chen-xtx", "Xuxi Chen", "XTX Markets", "Quantitative Researcher", "PhD", 2025, "industry"),
  placement("atlas-audit-zhangheng-li-zoom", "Zhangheng Li", "Zoom AI", "Research Scientist", "PhD", 2025, "industry"),
  placement("atlas-audit-yan-zheng-unity", "Yan Zheng", "Unity AI", "Research Scientist", "PhD", 2026, "industry"),
];

/** Existing relation retained rather than duplicated by this module. */
export const atlasWangLineageAuditExistingRelationshipIds = [
  "thomas-huang-atlas-wang-phd",
] as const;

export const atlasWangLineageAuditSummary = {
  subject: "atlas-wang-us",
  verifiedFacultyAlumni: 10,
  verifiedCurrentPostdocs: 3,
  verifiedCurrentPhdStudents: 16,
  verifiedPhdPostdocAlumni: 32,
  addedPeople: atlasWangLineageAuditPeople.length,
  addedRelationships: atlasWangLineageAuditRelationships.length,
  addedGroupMembers: atlasWangLineageAuditGroupMembers.length,
  addedPlacements: atlasWangLineageAuditStudentPlacements.length,
  method: "First-party thesis repository, official university profiles, personal academic pages and the VITA official roster only; no co-authorship inference.",
} as const;
