import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";
const checkedAt="2026-09-03";
const src=(label:string,url:string,kind:Source["kind"],supports:string):Source=>({label,url,kind,supports,checkedAt});
const fact=(label:string,value:string,source:Source)=>({label,value,source});
const s={
 bin:src("Illinois Siebel School · Bin Hu","https://siebelschool.illinois.edu/about/people/all-faculty/binhu7","official","Current faculty appointment and Minnesota doctorate"),binHome:src("Bin Hu · personal academic profile","https://binhu7.github.io/","profile","Education, Peter Seiler supervision, Wisconsin postdoc and AI/control research"),
 kang:src("Illinois Siebel School · Daniel Kang","https://siebelschool.illinois.edu/about/people/all-faculty/ddkang","official","Current assistant professorship and ML analytics research"),kangHome:src("Daniel Kang · personal academic profile","https://ddkang.github.io/","profile","Stanford advisers, Berkeley postdoc and industry consulting"),kangStudents:src("Daniel Kang · students","https://ddkang.github.io/students/","profile","Named students and startup, NVIDIA and graduate-school destinations"),
 lai:src("Illinois Siebel School · Fan Lai","https://siebelschool.illinois.edu/about/people/all-faculty/fanlai","official","Current appointment, Michigan doctorate and AI systems research"),laiHome:src("Fan Lai · personal academic profile","https://www.fanlai.me/","profile","Google and Meta experience, current students and industry destinations"),
 minjia:src("Illinois Siebel School · Minjia Zhang","https://siebelschool.illinois.edu/about/people/all-faculty/minjiaz","official","Current appointment and Ohio State doctorate"),minjiaHome:src("Minjia Zhang · personal academic profile","https://minjiazhang.github.io/","profile","SSAIL leadership, students and efficient AI systems research"),minjiaCv:src("Minjia Zhang · CV","https://minjiazhang.github.io/docs/Minjia_Zhang_Resume_063025.pdf","cv","Education and professional trajectory"),
};
type Seed=Omit<Person,"portrait"|"category"|"status"|"primary"|"introducedAt"|"lastVerifiedAt">;
const p=(x:Seed,file:string,url:string):Person=>({...x,category:"core",status:"current independent PI · official faculty profile verified",primary:true,introducedAt:checkedAt,lastVerifiedAt:checkedAt,portrait:{src:`portraits/candidate-p0-us-canada-ready-batch-11-2026/${file}.jpg`,alt:`${x.name} 官方头像`,source:src(`Illinois portrait · ${x.name}`,url,"official","Official university directory portrait")}});
export const candidatePriorityP0UsCanadaReadyBatch11People2026:Person[]=[
 p({id:"bin-hu-uiuc-p0-b11",name:"Bin Hu",role:"Associate Professor",institution:"UIUC",region:"United States",area:"Control and Machine Learning · Reinforcement Learning · AI Safety",tags:["机器学习","强化学习","控制","AI安全"],summary:"把控制理论用于大模型、强化学习和安全关键 AI 的 UIUC PI。",stage:"senior",x:120,y:120,sources:[s.bin,s.binHome],facts:[fact("当前任职","UIUC ECE 副教授，并与 Siebel School、CSL 交叉任职。",s.binHome),fact("教育与学术训练","USTC 学士、CMU 硕士、University of Minnesota PhD（2016，导师 Peter Seiler）；随后在 Wisconsin 跟随 Laurent Lessard 做博士后。",s.binHome),fact("研究主线","控制与机器学习、强化学习、生成式 AI 和安全稳健 AI。",s.binHome),fact("产业合作","本人主页记录 Amazon Research Award 及 IBM 多智能体 AI 项目支持。",s.binHome)]},"bin-hu","https://ws.engr.illinois.edu/directory/viewphoto/binhu7/1200"),
 p({id:"daniel-kang-uiuc-p0-b11",name:"Daniel Kang",role:"Assistant Professor",institution:"UIUC",region:"United States",area:"ML Systems · Video Analytics · Data Systems",tags:["机器学习系统","视频分析","数据系统","可靠AI"],summary:"研究大规模非结构化数据分析和机器学习部署系统的 UIUC PI。",stage:"emerging",x:300,y:120,sources:[s.kang,s.kangHome,s.kangStudents],facts:[fact("当前任职","UIUC Computer Science 助理教授，并在 ECE 兼任。",s.kangHome),fact("教育与学术训练","Stanford 博士阶段跟随 Peter Bailis 与 Matei Zaharia；随后在 UC Berkeley Sky Lab 跟随 Ion Stoica 做博士后。",s.kangHome),fact("研究主线","视频、图像、文本与音频分析，以及安全可靠的 ML 部署系统。",s.kangStudents),fact("产业连接","本人主页记录曾为 OpenAI、Google 与 Microsoft 等机构提供 ML 部署咨询。",s.kangHome),fact("学生去向","公开学生页记录学生创办 Succinct、Player Zero，并进入 NVIDIA 或 MIT 深造。",s.kangStudents)]},"daniel-kang","https://ws.engr.illinois.edu/directory/viewphoto/ddkang/1200"),
 p({id:"fan-lai-uiuc-p0-b11",name:"Fan Lai",role:"Assistant Professor",institution:"UIUC",region:"United States",area:"AI Systems · Generative AI · Federated Learning",tags:["AI系统","生成式AI","智能体","联邦学习"],summary:"研究生成式 AI、智能体和分布式机器学习系统的 UIUC 新生代 PI。",stage:"emerging",x:480,y:120,sources:[s.lai,s.laiHome],facts:[fact("当前任职","UIUC Computer Science 助理教授。",s.laiHome),fact("教育与学术训练","University of Michigan Computer Science PhD（2023）。",s.lai),fact("研究主线","AI systems and algorithms、生成式 AI、智能体、具身 AI 与 edge-cloud learning。",s.laiHome),fact("产业经历","加入 UIUC 前在 Google Systems Research 与 Meta AI 工作。",s.laiHome),fact("学生体系","本人主页列出博士、硕士学生及去向 Google、NVIDIA、TikTok、MIT 与 CMU。",s.laiHome)]},"fan-lai","https://ws.engr.illinois.edu/directory/viewphoto/fanlai/1200"),
 p({id:"minjia-zhang-uiuc-p0-b11",name:"Minjia Zhang",role:"Assistant Professor · Director, SSAIL",institution:"UIUC",region:"United States",area:"Efficient ML Systems · Agentic AI · Multimodal Models",tags:["机器学习系统","智能体","多模态","模型效率"],summary:"领导 SSAIL、研究大规模模型训练推理与 Agentic AI 系统的 UIUC PI。",stage:"emerging",x:660,y:120,sources:[s.minjia,s.minjiaHome,s.minjiaCv],facts:[fact("当前任职","UIUC Computer Science 助理教授，并任 SSAIL 主任。",s.minjiaHome),fact("教育与学术训练","Ohio State University Computer Science PhD（2016）。",s.minjia),fact("研究主线","高效 ML 训练推理、模型压缩、Agentic AI、多模态及图像视频生成。",s.minjiaHome),fact("团队领导","本人主页明确其为 Supercomputing System and AI Lab 主任并招收博士与硕士生。",s.minjiaHome)]},"minjia-zhang","https://ws.engr.illinois.edu/directory/viewphoto/minjiaz/1200"),
];
export const candidatePriorityP0UsCanadaReadyBatch11SupportingPeople2026:Person[]=[
 {id:"peter-seiler-lineage-p0-b11",name:"Peter Seiler",role:"Professor · doctoral adviser",institution:"University of Minnesota",region:"United States",area:"Control Theory · Robust Systems",tags:["控制理论","博士导师"],summary:"Bin Hu 在 University of Minnesota 博士阶段的导师。",stage:"senior",category:"adjacent",status:"supporting mentor node · relationship evidence only",primary:false,x:120,y:20,sources:[s.binHome],lastVerifiedAt:checkedAt},
 {id:"laurent-lessard-lineage-p0-b11",name:"Laurent Lessard",role:"Professor · postdoctoral mentor",institution:"Northeastern University",region:"United States",area:"Control · Optimization · Machine Learning",tags:["控制","优化","博士后指导"],summary:"Bin Hu 在 Wisconsin 博士后阶段合作的学术导师。",stage:"senior",category:"adjacent",status:"supporting mentor node · relationship evidence only",primary:false,x:220,y:20,sources:[s.binHome],lastVerifiedAt:checkedAt},
];
export const candidatePriorityP0UsCanadaReadyBatch11Relationships2026:Relationship[]=[
 {id:"p0-usca-b11-seiler-hu",from:"peter-seiler-lineage-p0-b11",to:"bin-hu-uiuc-p0-b11",type:"lineage",subtype:"phd_adviser",label:"博士导师",evidence:"Bin Hu 本人主页写明其 University of Minnesota 博士导师为 Peter Seiler。",source:s.binHome,verified:true,endYear:2016},
 {id:"p0-usca-b11-lessard-hu",from:"laurent-lessard-lineage-p0-b11",to:"bin-hu-uiuc-p0-b11",type:"lineage",subtype:"postdoc_mentor",label:"博士后指导",evidence:"Bin Hu 本人主页写明其在 Wisconsin 跟随 Laurent Lessard 从事博士后研究。",source:s.binHome,verified:true},
];
export const candidatePriorityP0UsCanadaReadyBatch11GroupMembers2026:GroupMember[]=[{id:"p0-usca-b11-kang-students",teacherId:"daniel-kang-uiuc-p0-b11",name:"Kang group students",role:"Students and alumni",source:s.kangStudents},{id:"p0-usca-b11-lai-students",teacherId:"fan-lai-uiuc-p0-b11",name:"Lai group students",role:"PhD and master's students",source:s.laiHome},{id:"p0-usca-b11-minjia-students",teacherId:"minjia-zhang-uiuc-p0-b11",name:"SSAIL members",role:"Graduate researchers",source:s.minjiaHome}];
export const candidatePriorityP0UsCanadaReadyBatch11Placements2026:StudentPlacement[]=[{id:"p0-usca-b11-lai-weiyu",student:"Wei-Yu Lin",teacherId:"fan-lai-uiuc-p0-b11",company:"Google",role:"Alumnus",kind:"reported",sector:"industry",note:"本人主页记录其 2024 年硕士生 Wei-Yu Lin 去向 Google。",source:s.laiHome,verifiedAt:checkedAt}];
export const candidatePriorityP0UsCanadaReadyBatch11RosterPromotions2026=candidatePriorityP0UsCanadaReadyBatch11People2026.map(x=>({unitUrl:"https://siebelschool.illinois.edu/about/people/all-faculty",rosterName:x.name,atlasPersonId:x.id}));
export const people=[...candidatePriorityP0UsCanadaReadyBatch11People2026,...candidatePriorityP0UsCanadaReadyBatch11SupportingPeople2026]; export const relationships=candidatePriorityP0UsCanadaReadyBatch11Relationships2026; export const placements=candidatePriorityP0UsCanadaReadyBatch11Placements2026; export const groupMembers=candidatePriorityP0UsCanadaReadyBatch11GroupMembers2026; export const rosterPromotions=candidatePriorityP0UsCanadaReadyBatch11RosterPromotions2026;
