import type {GroupMember,Person,Relationship,Source,StudentPlacement} from "./data";
const checkedAt="2026-09-03"; const src=(label:string,url:string,kind:Source["kind"],supports:string):Source=>({label,url,kind,supports,checkedAt}); const fact=(label:string,value:string,source:Source)=>({label,value,source});
const s={ge:src("Illinois Siebel School · Ge Liu","https://siebelschool.illinois.edu/about/people/all-faculty/geliu","official","Current faculty appointment and education"),geHome:src("Ge Liu · Illinois personal profile","https://geliu.web.illinois.edu/","profile","Gifford and Baker training, Google Brain/AWS experience and recruitment"),jiaqi:src("Illinois Siebel School · Jiaqi Ma","https://siebelschool.illinois.edu/about/people/all-faculty/jiaqima","official","Current faculty appointment and AI/data research"),jiaqiHome:src("Jiaqi Ma · personal academic profile","https://jiaqima.github.io/about/","profile","Michigan doctorate, Harvard postdoc, students and AI research"),haohan:src("Illinois iSchool · Haohan Wang","https://ischool.illinois.edu/people/haohan-wang","official","Current appointment, CMU doctorate and trustworthy ML research"),haohanHome:src("Haohan Wang · Illinois personal profile","https://haohanwang.ischool.illinois.edu/index.html","profile","Eric Xing supervision, agentic AI and student recruitment")};
type Seed=Omit<Person,"portrait"|"category"|"status"|"primary"|"introducedAt"|"lastVerifiedAt">; const p=(x:Seed,file:string,login:string):Person=>({...x,category:"core",status:"current independent PI · official faculty profile verified",primary:true,introducedAt:checkedAt,lastVerifiedAt:checkedAt,portrait:{src:`portraits/candidate-p0-us-canada-ready-batch-12-2026/${file}.jpg`,alt:`${x.name} 官方头像`,source:src(`Illinois portrait · ${x.name}`,`https://ws.engr.illinois.edu/directory/viewphoto/${login}/1200`,"official","Official university portrait")}});
export const candidatePriorityP0UsCanadaReadyBatch12People2026:Person[]=[
p({id:"ge-liu-uiuc-p0-b12",name:"Ge Liu",chinese:"刘謌",role:"Assistant Professor",institution:"UIUC",region:"United States",area:"Generative AI · AI for Science · Geometric Deep Learning",tags:["生成式AI","AI4Science","几何深度学习","科学智能体"],summary:"研究分子设计、多模态生成模型与科学智能体的 UIUC PI。",stage:"emerging",x:120,y:120,sources:[s.ge,s.geHome],facts:[fact("当前任职","UIUC Computer Science 助理教授。",s.ge),fact("教育与学术训练","Tsinghua 学士；MIT Computer Science PhD（导师 David Gifford）；University of Washington Institute for Protein Design 博士后（导师 David Baker）。",s.geHome),fact("研究主线","几何与多模态生成模型、扩散 LLM、RL 后训练和科学智能体。",s.geHome),fact("产业经历","曾任 AWS AI Labs Senior Applied Scientist，并在 Google Brain 实习。",s.geHome),fact("招生信息","本人主页明确招收 AI4Science 与 ML 博士生和实习生。",s.geHome)]},"ge-liu","geliu"),
p({id:"jiaqi-ma-uiuc-p0-b12",name:"Jiaqi Ma",chinese:"马家祺",role:"Assistant Professor",institution:"UIUC",region:"United States",area:"Data-centric AI · Machine Learning · AI Safety",tags:["数据中心AI","机器学习","AI安全","数据归因"],summary:"研究训练数据如何影响模型与社会的 UIUC 数据中心 AI PI。",stage:"emerging",x:300,y:120,sources:[s.jiaqi,s.jiaqiHome],facts:[fact("当前任职","UIUC School of Information Sciences 助理教授，并与 Siebel School 交叉任职。",s.jiaqiHome),fact("教育与学术训练","Tsinghua University B.Eng.；University of Michigan PhD；随后在 Harvard 做博士后。",s.jiaqiHome),fact("研究主线","数据归因、数据策展、合成数据、机器遗忘与 AI 社会影响。",s.jiaqiHome),fact("学生体系","本人主页列出五位博士生与两位 thesis-based 硕士生。",s.jiaqiHome),fact("产业连接","主页记录 Google gift grant 与 Anthropic Safety Fellow 学生。",s.jiaqiHome)]},"jiaqi-ma","jiaqima"),
p({id:"haohan-wang-uiuc-p0-b12",name:"Haohan Wang",chinese:"汪浩瀚",role:"Assistant Professor",institution:"UIUC",region:"United States",area:"Trustworthy Machine Learning · Agentic AI · Computational Biology",tags:["可信机器学习","智能体","计算生物学","医疗AI"],summary:"把可信机器学习与 agentic AI 用于生物医学发现的 UIUC PI。",stage:"emerging",x:480,y:120,sources:[s.haohan,s.haohanHome],facts:[fact("当前任职","UIUC School of Information Sciences 助理教授。",s.haohan),fact("教育与学术训练","Carnegie Mellon University Language Technologies Institute 计算机科学博士，跟随 Eric Xing 工作。",s.haohanHome),fact("研究主线","可信机器学习、agentic AI、安全和计算生物学。",s.haohanHome),fact("团队建设","本人主页公开招收博士、博士后、实习生与访问学生。",s.haohanHome)]},"haohan-wang","haohanw")];
export const candidatePriorityP0UsCanadaReadyBatch12SupportingPeople2026:Person[]=[{id:"eric-xing-lineage-p0-b12",name:"Eric Xing",role:"Professor / President",institution:"CMU",region:"United States",area:"Machine Learning · AI Systems",tags:["博士导师","机器学习"],summary:"Haohan Wang 博士训练阶段的导师。",stage:"senior",category:"historical",status:"supporting mentor node · relationship evidence only",sources:[s.haohanHome],x:480,y:20,primary:false,lastVerifiedAt:checkedAt}];
export const candidatePriorityP0UsCanadaReadyBatch12Relationships2026:Relationship[]=[{id:"p0-usca-b12-gifford-ge",from:"david-gifford-lineage",to:"ge-liu-uiuc-p0-b12",type:"lineage",subtype:"phd_adviser",label:"博士导师",evidence:"Ge Liu 本人主页明确其 MIT EECS 博士由 David Gifford 指导。",source:s.geHome,verified:true},{id:"p0-usca-b12-xing-haohan",from:"eric-xing-lineage-p0-b12",to:"haohan-wang-uiuc-p0-b12",type:"lineage",subtype:"phd_adviser",label:"博士导师",evidence:"Haohan Wang 本人 Illinois 页面说明其在 CMU LTI 博士阶段跟随 Eric Xing。",source:s.haohanHome,verified:true}];
export const candidatePriorityP0UsCanadaReadyBatch12GroupMembers2026:GroupMember[]=[{id:"p0-usca-b12-jiaqi-team",teacherId:"jiaqi-ma-uiuc-p0-b12",name:"Ma group students",role:"PhD and master's students",source:s.jiaqiHome},{id:"p0-usca-b12-ge-team",teacherId:"ge-liu-uiuc-p0-b12",name:"Liu group recruits",role:"PhD students and interns",source:s.geHome}]; export const candidatePriorityP0UsCanadaReadyBatch12Placements2026:StudentPlacement[]=[];
export const candidatePriorityP0UsCanadaReadyBatch12RosterPromotions2026=candidatePriorityP0UsCanadaReadyBatch12People2026.map(x=>({unitUrl:"https://siebelschool.illinois.edu/about/people/all-faculty",rosterName:x.name,atlasPersonId:x.id})); export const people=[...candidatePriorityP0UsCanadaReadyBatch12People2026,...candidatePriorityP0UsCanadaReadyBatch12SupportingPeople2026];export const relationships=candidatePriorityP0UsCanadaReadyBatch12Relationships2026;export const placements=candidatePriorityP0UsCanadaReadyBatch12Placements2026;export const groupMembers=candidatePriorityP0UsCanadaReadyBatch12GroupMembers2026;export const rosterPromotions=candidatePriorityP0UsCanadaReadyBatch12RosterPromotions2026;
