import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";

const source = (
  label: string,
  url: string,
  kind: Source["kind"],
  supports: string,
): Source => ({ label, url, kind, supports, checkedAt });

const sources = {
  cambridgeRoster: source(
    "Cambridge CST · Faculty directory",
    "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en",
    "official",
    "Cambridge CST 现任 faculty 名录与独立 PI 身份",
  ),
  annProfile: source(
    "Cambridge CST · Ann Copestake",
    "https://www.cst.cam.ac.uk/people/aac10",
    "official",
    "计算语言学教授现职、NLP/ML 研究主题与官方头像",
  ),
  annHomepage: source(
    "Ann Copestake · Cambridge academic homepage",
    "https://www.cl.cam.ac.uk/~aac10/",
    "profile",
    "Cambridge 与 Sussex 教育训练、Stanford CSLI 经历、研究方向及博士生名单",
  ),
  carlProfile: source(
    "Cambridge CST · Carl Henrik Ek",
    "https://www.cst.cam.ac.uk/people/che29",
    "official",
    "Cambridge faculty 身份、机器学习主题与官方头像",
  ),
  carlHomepage: source(
    "Carl Henrik Ek · Academic homepage",
    "https://carlhenrik.com/",
    "profile",
    "统计学习教授现职、KTH 与 Oxford Brookes 教育、Neil Lawrence/Phil Torr 博士指导、Berkeley 博士后合作及研究方向",
  ),
  carlStudent: source(
    "Cambridge AI4ER · Mala Virdee",
    "https://ai4er-cdt.esc.cam.ac.uk/StaffDirectory/students-all/2019-students",
    "official",
    "Mala Virdee 的博士项目与 Carl Henrik Ek、Emily Shuckburgh 共同指导记录",
  ),
  damonProfile: source(
    "Cambridge CST · Damon Wischik",
    "https://www.cst.cam.ac.uk/people/djw1005",
    "official",
    "现任 University Lecturer、机器学习研究方向、博士生名单与官方头像",
  ),
  damonCv: source(
    "Damon Wischik · Cambridge curriculum vitae",
    "https://www.cl.cam.ac.uk/~djw1005/AboutMe/cv.html",
    "profile",
    "Cambridge 数学学士与 Frank Kelly 指导的博士训练、学术任职、六位已毕业博士和产业经历",
  ),
  ianProfile: source(
    "Cambridge CST · Ian Wassell",
    "https://www.cst.cam.ac.uk/people/ijw24",
    "official",
    "无线通信教授现职、Southampton 博士与 Loughborough 学位、AI 通信研究和培养规模及官方头像",
  ),
  ianStudent: source(
    "Cambridge Computer Lab Ring · Yan Wu",
    "https://www.cl.cam.ac.uk/downloads/ring/ring-2009-09.pdf",
    "official",
    "Yan Wu 为 Ian Wassell 指导的 Cambridge 博士生及其 2008 年奖项记录",
  ),
  jonProfile: source(
    "Cambridge CST · Jon Crowcroft",
    "https://www.cst.cam.ac.uk/people/jac22",
    "official",
    "Marconi Professor 现职、Cambridge/UCL 教育训练、系统与 AI 研究及官方头像",
  ),
  jonStudents: source(
    "Jon Crowcroft · Cambridge PhD family tree",
    "https://www.cl.cam.ac.uk/~jac22/paststudents.html",
    "profile",
    "Peter Kirstein 博士指导关系、历届博士生及 Paul Francis 等人的公开去向",
  ),
  martinProfile: source(
    "Cambridge CST · Martin Kleppmann",
    "https://www.cst.cam.ac.uk/people/mk428",
    "official",
    "Associate Professor 现职、分布式系统与安全研究及官方头像",
  ),
  martinHomepage: source(
    "Martin Kleppmann · Personal academic website",
    "https://martin.kleppmann.com/",
    "profile",
    "Cambridge 现职、TUM/Cambridge 研究经历、Rapportive 与 Go Test It 创业经历和研究主线",
  ),
  martinEducation: source(
    "Martin Kleppmann · 2019 research update",
    "https://martin.kleppmann.com/2019/10/30/research-update.html",
    "profile",
    "其本人记录 2018 年完成博士以及 2019 年 Cambridge 研究任职",
  ),
  cambridgeSecurityPeople: source(
    "Cambridge CST Security Group · People",
    "https://www.cl.cam.ac.uk/research/security/people/",
    "official",
    "Robert Watson、Martin Kleppmann 等 faculty 与按导师标注的当前博士生名单",
  ),
  paulaProfile: source(
    "Cambridge CST · Paula Buttery",
    "https://www.cst.cam.ac.uk/people/pjb48",
    "official",
    "语言与机器学习教授、Deputy Head、研究主题、团队名单与官方头像",
  ),
  paulaCv: source(
    "Paula Buttery · Cambridge CV",
    "https://www.cl.cam.ac.uk/~pjb48/paula_buttery.pdf",
    "profile",
    "Cambridge 计算机科学博士、MPhil 与本科教育训练及职业履历",
  ),
  mullinsProfile: source(
    "Cambridge CST · Robert Mullins",
    "https://www.cst.cam.ac.uk/people/rdm34",
    "official",
    "计算机体系结构教授现职、AI 加速器研究、CommonAI/lowRISC/Raspberry Pi 创业与官方头像",
  ),
  mullinsCv: source(
    "Robert Mullins · Cambridge curriculum vitae",
    "https://www.cl.cam.ac.uk/~rdm34/cv/",
    "profile",
    "Edinburgh 博士、硕士与本科训练及 Cambridge 学术履历",
  ),
  watsonProfile: source(
    "Cambridge CST · Robert Watson",
    "https://www.cst.cam.ac.uk/people/rnw24",
    "official",
    "系统、安全与体系结构教授现职、CHERI 共同领导、团队规模及官方头像",
  ),
  watsonHomepage: source(
    "Robert Watson · Cambridge academic homepage",
    "https://www.cl.cam.ac.uk/~rnw24/",
    "profile",
    "CMU 本科、Ross Anderson 指导的 Cambridge 博士、产业研究经历、博士生和 CHERI 研究",
  ),
  simonProfile: source(
    "Cambridge CST · Simon Moore",
    "https://www.cst.cam.ac.uk/people/swm11",
    "official",
    "计算机工程教授现职、体系结构与 CHERI 研究、博士生培养及官方头像",
  ),
  simonResume: source(
    "Simon Moore · Cambridge résumé",
    "https://www.cl.cam.ac.uk/~swm11/resume/",
    "profile",
    "Cambridge 博士与研究任职、历届博士生及其产业和学术去向",
  ),
} satisfies Record<string, Source>;

const fact = (label: string, value: string, sourceValue: Source) => ({
  label,
  value,
  source: sourceValue,
});

type PersonSeed = Omit<
  Person,
  "category" | "primary" | "status" | "introducedAt" | "lastVerifiedAt" | "portrait"
> & {
  portraitFile: string;
  portraitSource: Source;
};

const person = (seed: PersonSeed): Person => ({
  ...seed,
  category: "core",
  primary: true,
  status: "current independent PI · official profile verified",
  introducedAt: checkedAt,
  lastVerifiedAt: checkedAt,
  portrait: {
    src: `portraits/candidate-p0-europe-batch-7-2026/${seed.portraitFile}`,
    alt: `${seed.name} 头像`,
    source: seed.portraitSource,
  },
});

export const candidatePriorityP0EuropeBatch7People2026: Person[] = [
  person({
    id: "ann-copestake-cambridge-p0-2026",
    name: "Ann Copestake",
    role: "Professor of Computational Linguistics",
    institution: "Cambridge",
    region: "Europe",
    area: "Natural Language Processing · Computational Semantics · NLG",
    tags: ["NLP", "Computational Semantics", "NLG", "DELPH-IN"],
    summary: "Cambridge 计算语言学资深 PI，长期建设形式语义、语法工程与自然语言生成工具链，也是 LKB 和 DELPH-IN 社群的重要推动者。",
    stage: "senior",
    x: 150,
    y: 220,
    portraitFile: "ann-copestake.jpg",
    portraitSource: sources.annProfile,
    facts: [
      fact("当前任职", "Cambridge Computer Science and Technology 计算语言学教授，研究主题同时归入 NLP 与 Machine Learning and AI。", sources.annProfile),
      fact("教育与学术训练", "Cambridge 自然科学本科、计算机 Diploma 后，于 1990–1992 年在 University of Sussex 完成计算机科学博士。", sources.annHomepage),
      fact("研究主线", "研究形式语义、组合与词汇语义、自然语言生成和语法工程，并长期参与 DELPH-IN、LKB 与 PET 等开放工具。", sources.annHomepage),
      fact("学术经历", "曾访问 Xerox PARC，并于 1994–2000 年在 Stanford CSLI 任 Senior Researcher，之后回到 Cambridge。", sources.annHomepage),
    ],
    sources: [sources.cambridgeRoster, sources.annProfile, sources.annHomepage],
  }),
  person({
    id: "carl-henrik-ek-cambridge-p0-2026",
    name: "Carl Henrik Ek",
    role: "Professor of Statistical Learning · UKRI AI CDT Co-Director",
    institution: "Cambridge",
    region: "Europe",
    area: "Probabilistic Machine Learning · Gaussian Processes · Data-Efficient AI",
    tags: ["Machine Learning", "Bayesian Methods", "Gaussian Processes", "Data-Efficient AI"],
    summary: "Cambridge 统计学习教授，围绕贝叶斯非参数方法、Gaussian processes 和小数据条件下的可解释学习连接 Cambridge、KTH 与 Berkeley 网络。",
    stage: "senior",
    x: 330,
    y: 220,
    portraitFile: "carl-henrik-ek.jpg",
    portraitSource: sources.carlProfile,
    facts: [
      fact("当前任职", "Cambridge Professor of Statistical Learning、ml@cl 成员，并共同领导 Cambridge–Manchester UKRI AI CDT。", sources.carlHomepage),
      fact("教育与学术训练", "KTH Vehicle Engineering MEng；Oxford Brookes 博士阶段由 Neil Lawrence 与 Phil Torr 指导。", sources.carlHomepage),
      fact("博士后网络", "在 UC Berkeley 从事博士后研究，并与 Trevor Darrell、Raquel Urtasun 工作。", sources.carlHomepage),
      fact("研究主线", "研究数据高效且可解释的机器学习假设，重点覆盖 Bayesian non-parametric methods 与 Gaussian processes。", sources.carlHomepage),
    ],
    sources: [sources.cambridgeRoster, sources.carlProfile, sources.carlHomepage, sources.carlStudent],
  }),
  person({
    id: "damon-wischik-cambridge-p0-2026",
    name: "Damon Wischik",
    role: "University Lecturer · Probabilistic Machine Learning",
    institution: "Cambridge",
    region: "Europe",
    area: "Probabilistic Machine Learning · Causal Inference · Data Science",
    tags: ["Probabilistic ML", "Causal ML", "Uncertainty", "Data Science"],
    summary: "Cambridge 概率机器学习与数据科学 PI，把因果、概率和不确定性建模用于网络、交通与气候问题，并持续培养跨数学和计算机科学博士生。",
    stage: "senior",
    x: 510,
    y: 220,
    portraitFile: "damon-wischik.jpg",
    portraitSource: sources.damonProfile,
    facts: [
      fact("当前任职", "Cambridge Computer Science and Technology University Lecturer，研究主题归入 Human-Centred Computing 与 Machine Learning and AI。", sources.damonProfile),
      fact("教育与学术训练", "1992–1996 年在 Cambridge 修读数学学士，1996–1999 年在 Statistical Laboratory 由 Frank Kelly 指导完成博士。", sources.damonCv),
      fact("研究主线", "研究概率机器学习、因果方向识别、不确定性估计，并把方法用于道路交通、计算机网络和气候科学。", sources.damonCv),
      fact("人才与产业", "个人 CV 记录六位已毕业博士；其 AI4ER 学生分别进入风能期货交易和极端天气预测创业。", sources.damonCv),
    ],
    sources: [sources.cambridgeRoster, sources.damonProfile, sources.damonCv],
  }),
  person({
    id: "ian-wassell-cambridge-p0-2026",
    name: "Ian Wassell",
    role: "Professor of Wireless Communication",
    institution: "Cambridge",
    region: "Europe",
    area: "AI for Wireless Systems · Communications · Signal Processing",
    tags: ["AI for Wireless", "Wireless Communications", "Signal Processing", "Deep Learning"],
    summary: "Cambridge 无线通信教授，将 AI 与深度学习引入无线系统、定位和通信建模；官方履历记录已培养 29 位博士与 6 位 MPhil。",
    stage: "senior",
    x: 690,
    y: 220,
    portraitFile: "ian-wassell.jpg",
    portraitSource: sources.ianProfile,
    facts: [
      fact("当前任职", "Cambridge Computer Science and Technology 无线通信教授；此前在 Cambridge Engineering 任职约六年半。", sources.ianProfile),
      fact("教育与学术训练", "1983 年获 Loughborough BSc/BEng，1990 年获 University of Southampton 博士，论文研究无线与移动系统的 Viterbi equalisation。", sources.ianProfile),
      fact("研究主线", "当前研究 AI 在无线通信系统中的应用，长期积累覆盖无线通信仿真、设计、定位与信号处理。", sources.ianProfile),
      fact("人才培养", "官方简介记录成功指导 29 位博士与 6 位 MPhil；Cambridge Ring 明确记录 Yan Wu 为其博士生。", sources.ianProfile),
    ],
    sources: [sources.cambridgeRoster, sources.ianProfile, sources.ianStudent],
  }),
  person({
    id: "jon-crowcroft-cambridge-p0-2026",
    name: "Jon Crowcroft",
    role: "Marconi Professor of Communications Systems",
    institution: "Cambridge",
    region: "Europe",
    area: "Systems and Networking · Trustworthy Infrastructure · Networked AI",
    tags: ["Systems", "Networking", "Trustworthy Infrastructure", "AI"],
    summary: "Cambridge 通信系统资深 PI，以互联网体系结构、网络系统和可信数字基础设施研究形成跨 UCL、Cambridge 与产业研究机构的博士生网络。",
    stage: "senior",
    x: 870,
    y: 220,
    portraitFile: "jon-crowcroft.jpg",
    portraitSource: sources.jonProfile,
    facts: [
      fact("当前任职", "Cambridge Marconi Professor of Communications Systems、Alan Turing Institute Researcher-at-Large，并任 Imperial I-X Visiting Professor。", sources.jonProfile),
      fact("教育与学术训练", "1979 年毕业于 Cambridge Trinity College Physics；1981 年获 UCL Computing MSc，1993 年获 UCL 博士。", sources.jonProfile),
      fact("研究主线", "研究系统与网络、可信数字基础设施、网络体系结构，以及联邦式 IoT 与机器学习的交叉问题。", sources.jonProfile),
      fact("师承与人才网络", "其 Cambridge 博士家族页明确写明 Peter Kirstein 是其博士导师，并逐一记录多位博士生及后续学界、研究院和产业去向。", sources.jonStudents),
    ],
    sources: [sources.cambridgeRoster, sources.jonProfile, sources.jonStudents],
  }),
  person({
    id: "martin-kleppmann-cambridge-p0-2026",
    name: "Martin Kleppmann",
    role: "Associate Professor · Distributed Systems and Security",
    institution: "Cambridge",
    region: "Europe",
    area: "Distributed Systems · Local-First Software · Security Protocols",
    tags: ["Distributed Systems", "Local-First", "CRDT", "Security"],
    summary: "Cambridge 分布式系统与安全 PI，连接 local-first、CRDT、形式验证和真实系统工程，同时具有创业、LinkedIn 与开源项目经历。",
    stage: "emerging",
    x: 1050,
    y: 220,
    portraitFile: "martin-kleppmann.jpg",
    portraitSource: sources.martinProfile,
    facts: [
      fact("当前任职", "自 2024 年起任 Cambridge Associate Professor，研究去中心化系统、local-first 协作软件与安全协议。", sources.martinProfile),
      fact("教育与学术训练", "其本人 2019 年研究总结记录博士学位于 2018 年完成，随后获 Leverhulme 与 Isaac Newton Trust early-career fellowships。", sources.martinEducation),
      fact("研究主线", "研究 distributed systems、databases、CRDT/local-first collaboration 与 cryptographic protocols，并参与 Automerge 开源项目。", sources.martinHomepage),
      fact("产业与创业", "曾联合创办 Rapportive 与 Go Test It，两家公司分别被 LinkedIn 与 Red Gate Software 收购。", sources.martinHomepage),
    ],
    sources: [sources.cambridgeRoster, sources.martinProfile, sources.martinHomepage, sources.martinEducation, sources.cambridgeSecurityPeople],
  }),
  person({
    id: "paula-buttery-cambridge-p0-2026",
    name: "Paula Buttery",
    role: "Professor of Language and Machine Learning · Deputy Head",
    institution: "Cambridge",
    region: "Europe",
    area: "Small Language Models · Explainable AI · Computational Psycholinguistics",
    tags: ["NLP", "Small Language Models", "Explainable AI", "Language Learning"],
    summary: "Cambridge 语言与机器学习教授，围绕小语言模型、可解释 AI、低资源语言和自动语言教学建设跨 NLP、教育与 RegTech 的研究团队。",
    stage: "senior",
    x: 1230,
    y: 220,
    portraitFile: "paula-buttery.jpg",
    portraitSource: sources.paulaProfile,
    facts: [
      fact("当前任职", "Cambridge Professor of Language and Machine Learning、Department Deputy Head，并领导 ALTA Institute。", sources.paulaProfile),
      fact("教育与学术训练", "在 Cambridge 完成计算机科学博士、Computer Speech Text & Internet Technology MPhil 与计算机科学本科。", sources.paulaCv),
      fact("研究主线", "研究小语言模型、主权 AI、可解释性、计算心理语言学、低资源语言与自动语言教学评测。", sources.paulaProfile),
      fact("人才与产业", "官方页面公开团队成员，并记录 RegGenome 合作及其曾任 Cambridge University Press and Assessment Lead Scientific Advisor。", sources.paulaProfile),
    ],
    sources: [sources.cambridgeRoster, sources.paulaProfile, sources.paulaCv],
  }),
  person({
    id: "robert-mullins-cambridge-p0-2026",
    name: "Robert Mullins",
    role: "Professor in Computer Architecture · CommonAI CTO",
    institution: "Cambridge",
    region: "Europe",
    area: "Efficient AI Systems · ML Accelerators · Open-Source Hardware",
    tags: ["AI Systems", "ML Accelerators", "Computer Architecture", "Open Hardware"],
    summary: "Cambridge 计算机体系结构教授，研究高效安全机器学习、AI 加速器与开放芯片，并通过 CommonAI、lowRISC 和 Raspberry Pi 推动技术转化。",
    stage: "senior",
    x: 1410,
    y: 220,
    portraitFile: "robert-mullins.jpg",
    portraitSource: sources.mullinsProfile,
    facts: [
      fact("当前任职", "Cambridge Professor in Computer Architecture，研究高效安全机器学习、加速器、微处理器与开源硬件。", sources.mullinsProfile),
      fact("教育与学术训练", "在 University of Edinburgh 完成 Computer Science and Electronics BEng、Computer Science MSc，并于 1995–2001 年完成计算机科学博士。", sources.mullinsCv),
      fact("研究主线", "面向机器学习的高效与安全计算、AI 加速器、微处理器设计和开放硬件是其当前核心方向。", sources.mullinsProfile),
      fact("产业与创业", "为 CommonAI 创始人兼 CTO、lowRISC 创始人兼董事，并曾参与创办 Raspberry Pi Foundation。", sources.mullinsProfile),
    ],
    sources: [sources.cambridgeRoster, sources.mullinsProfile, sources.mullinsCv, sources.cambridgeSecurityPeople],
  }),
  person({
    id: "robert-watson-cambridge-p0-2026",
    name: "Robert Watson",
    role: "Professor of Systems, Security, and Architecture · CHERI Lead",
    institution: "Cambridge",
    region: "Europe",
    area: "Systems Security · Computer Architecture · Operating Systems",
    tags: ["Systems Security", "CHERI", "Computer Architecture", "Operating Systems"],
    summary: "Cambridge 系统安全与体系结构教授，领导 CHERI 跨层安全体系，把学术研究连接 Arm、Google、Microsoft、Amazon 及开源操作系统生态。",
    stage: "senior",
    x: 1590,
    y: 220,
    portraitFile: "robert-watson.jpg",
    portraitSource: sources.watsonProfile,
    facts: [
      fact("当前任职", "Cambridge Professor of Systems, Security, and Architecture，横跨 Security、Systems and Networking、Computer Architecture 等研究组。", sources.watsonProfile),
      fact("教育与学术训练", "Carnegie Mellon Logic and Computation 本科并双修计算机科学；2011 年获 Cambridge 计算机科学博士，由 Ross Anderson 指导。", sources.watsonHomepage),
      fact("研究主线", "领导跨体系结构、编译器、程序分析、操作系统、网络与安全的 CHERI 研究。", sources.watsonProfile),
      fact("产业网络", "攻读博士前曾在 SPARTA ISSO、McAfee Research、NAI Labs 和 Trusted Information Systems 工作，CHERI 后续获得 Arm、Google、Microsoft、Amazon 等支持。", sources.watsonHomepage),
    ],
    sources: [sources.cambridgeRoster, sources.watsonProfile, sources.watsonHomepage, sources.cambridgeSecurityPeople],
  }),
  person({
    id: "simon-moore-cambridge-p0-2026",
    name: "Simon Moore",
    role: "Professor of Computer Engineering · CHERI Co-Investigator",
    institution: "Cambridge",
    region: "Europe",
    area: "Computer Architecture · Hardware Security · Neuromorphic Computing",
    tags: ["Computer Architecture", "Hardware Security", "CHERI", "Neuromorphic"],
    summary: "Cambridge 计算机工程教授，长期研究安全处理器、异步电路、CHERI 与神经形态计算，并形成连接 Arm、IBM Research、NVIDIA 等机构的博士生网络。",
    stage: "senior",
    x: 1770,
    y: 220,
    portraitFile: "simon-moore.jpg",
    portraitSource: sources.simonProfile,
    facts: [
      fact("当前任职", "Cambridge Professor of Computer Engineering、Computer Architecture Group 资深成员，并参与领导 CHERI。", sources.simonProfile),
      fact("教育与学术训练", "1991–1994 年在 Cambridge 以研究型路径完成博士，随后于 1994–1998 年在同校任 Research Associate。", sources.simonResume),
      fact("研究主线", "研究计算机体系结构、硬件安全、异步逻辑、CHERI capability systems 与神经形态计算。", sources.simonProfile),
      fact("人才流向", "个人履历逐一记录超过 25 位博士生及去向，包括 Arm、IBM Research、NVIDIA、Cadence 和多所高校。", sources.simonResume),
    ],
    sources: [sources.cambridgeRoster, sources.simonProfile, sources.simonResume],
  }),
];

export const candidatePriorityP0EuropeBatch7Relationships2026: Relationship[] = [
  {
    id: "p0-eu7-lawrence-ek-doctoral",
    from: "neil-lawrence-eu",
    to: "carl-henrik-ek-cambridge-p0-2026",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "Carl Henrik Ek 的个人学术主页明确将 Neil Lawrence 与 Phil Torr 列为博士导师。",
    source: sources.carlHomepage,
    verified: true,
  },
  {
    id: "p0-eu7-torr-ek-doctoral",
    from: "philip-torr-eu",
    to: "carl-henrik-ek-cambridge-p0-2026",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "Carl Henrik Ek 的个人学术主页明确将 Phil Torr 与 Neil Lawrence 列为博士导师。",
    source: sources.carlHomepage,
    verified: true,
  },
  {
    id: "p0-eu7-watson-moore-cheri",
    from: "robert-watson-cambridge-p0-2026",
    to: "simon-moore-cambridge-p0-2026",
    type: "collaboration",
    subtype: "joint_project",
    label: "CHERI 共同领导",
    evidence: "Robert Watson 的 Cambridge 官方简介将 Simon Moore 列为共同领导 CHERI architecture project 的核心成员。",
    source: sources.watsonProfile,
    verified: true,
  },
];

export const candidatePriorityP0EuropeBatch7Placements2026: StudentPlacement[] = [
  {
    id: "p0-eu7-crowcroft-francis-mpisws",
    student: "Paul Francis",
    teacherId: "jon-crowcroft-cambridge-p0-2026",
    company: "MPI-SWS",
    role: "Faculty / Research Leader",
    kind: "reported",
    degree: "PhD",
    sector: "academia",
    highLevel: true,
    note: "Jon Crowcroft 的博士家族页将 Paul Francis 列为其博士生，并记录其历经 Bellcore、NTT、Cornell 后到 MPI-SWS。",
    source: sources.jonStudents,
    verifiedAt: checkedAt,
  },
  {
    id: "p0-eu7-moore-barrow-williams-nvidia",
    student: "Nick Barrow-Williams",
    teacherId: "simon-moore-cambridge-p0-2026",
    company: "NVIDIA",
    role: "Engineer / Architect",
    kind: "reported",
    degree: "PhD",
    sector: "industry",
    note: "Simon Moore 的履历将 Nick Barrow-Williams 列为博士生，并记录其去向为 NVIDIA。",
    source: sources.simonResume,
    verifiedAt: checkedAt,
  },
];

export const candidatePriorityP0EuropeBatch7GroupMembers2026: GroupMember[] = [
  { id: "p0-eu7-ann-huiyuan-xie", teacherId: "ann-copestake-cambridge-p0-2026", name: "Huiyuan Xie", role: "PhD student / alumnus", focus: "Natural language generation evaluation", source: sources.annHomepage },
  { id: "p0-eu7-carl-mala-virdee", teacherId: "carl-henrik-ek-cambridge-p0-2026", name: "Mala Virdee", role: "PhD student · co-supervised", focus: "Bayesian learning for climate and environmental risk", source: sources.carlStudent },
  { id: "p0-eu7-damon-james-cruise", teacherId: "damon-wischik-cambridge-p0-2026", name: "James Cruise", role: "Completed PhD student", focus: "Queueing systems and large deviations", source: sources.damonCv },
  { id: "p0-eu7-ian-yan-wu", teacherId: "ian-wassell-cambridge-p0-2026", name: "Yan Wu", role: "PhD student", focus: "Wireless communications and signal processing", source: sources.ianStudent },
  { id: "p0-eu7-jon-paul-francis", teacherId: "jon-crowcroft-cambridge-p0-2026", name: "Paul Francis", role: "Former PhD student", focus: "Internet architecture and networking", source: sources.jonStudents },
  { id: "p0-eu7-martin-vincent-liu", teacherId: "martin-kleppmann-cambridge-p0-2026", name: "Vincent Liu", role: "PhD student", focus: "Conflict-free replicated data types", source: sources.cambridgeSecurityPeople },
  { id: "p0-eu7-paula-marek-rei", teacherId: "paula-buttery-cambridge-p0-2026", name: "Marek Rei", role: "Research student / researcher", focus: "Natural language processing and language modelling", source: sources.paulaProfile },
  { id: "p0-eu7-mullins-david-khachaturov", teacherId: "robert-mullins-cambridge-p0-2026", name: "David Khachaturov", role: "PhD student · co-supervised", focus: "Automated security analysis", source: sources.cambridgeSecurityPeople },
  { id: "p0-eu7-watson-domagoj-stolfa", teacherId: "robert-watson-cambridge-p0-2026", name: "Domagoj Stolfa", role: "PhD student", focus: "Tracing, distributed systems and capability systems", source: sources.cambridgeSecurityPeople },
  { id: "p0-eu7-moore-nick-barrow-williams", teacherId: "simon-moore-cambridge-p0-2026", name: "Nick Barrow-Williams", role: "Former PhD student", focus: "Chip multiprocessor architecture", source: sources.simonResume },
];

export const candidatePriorityP0EuropeBatch7RosterPromotions2026 = [
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Ann Copestake", atlasPersonId: "ann-copestake-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Carl Henrik Ek", atlasPersonId: "carl-henrik-ek-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Damon Wischik", atlasPersonId: "damon-wischik-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Ian Wassell", atlasPersonId: "ian-wassell-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Jon Crowcroft", atlasPersonId: "jon-crowcroft-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Martin Kleppmann", atlasPersonId: "martin-kleppmann-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Paula Buttery", atlasPersonId: "paula-buttery-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Robert Mullins", atlasPersonId: "robert-mullins-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Robert Watson", atlasPersonId: "robert-watson-cambridge-p0-2026" },
  { unitUrl: "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", rosterName: "Simon Moore", atlasPersonId: "simon-moore-cambridge-p0-2026" },
] as const;

export const people = candidatePriorityP0EuropeBatch7People2026;
export const relationships = candidatePriorityP0EuropeBatch7Relationships2026;
export const placements = candidatePriorityP0EuropeBatch7Placements2026;
export const groupMembers = candidatePriorityP0EuropeBatch7GroupMembers2026;
export const rosterPromotions = candidatePriorityP0EuropeBatch7RosterPromotions2026;
