import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const sources = {
  epflRoster: source("EPFL IC · Faculty members", "https://www.epfl.ch/schools/ic/about/faculty-members/", "official", "EPFL IC 现任教授名录"),
  ethRoster: source("ETH Zurich D-INFK · Faculty", "https://inf.ethz.ch/people/faculty.html", "official", "ETH D-INFK 现任教授名录"),
  bourgeatProfile: source("EPFL People · Thomas Bourgeat", "https://people.epfl.ch/thomas.bourgeat?lang=en", "official", "现任 tenure-track Assistant Professor、实验室、课程与具名博士生"),
  bourgeatBio: source("EPFL inaugural lecture · Thomas Bourgeat", "https://mediaspace.epfl.ch/media/Taming%2Bthe%2BComplexity%2Bof%2BFuture%2BComputer%2BDesigns%2C%2Bby%2BProf.%2BThomas%2BBourgeat/0_1xmnx8lt", "official", "MIT 博士、Arvind 与 Adam Chlipala 指导、EPFL 现职和研究主线"),
  bourgeatHome: source("Thomas Bourgeat · academic homepage", "https://people.csail.mit.edu/bthom/", "profile", "MIT 博士导师、研究方向与学术履历"),
  bourgeatPortrait: source("EPFL Media Library · Thomas Bourgeat portrait", "https://mediatheque.epfl.ch/en/media/329a4a48-9604-4589-a810-fd1cad87d33b/", "official", "CC0 EPFL professors portrait of Thomas Bourgeat"),
  gerstnerHome: source("EPFL LCN · Wulfram Gerstner", "https://lcnwww.epfl.ch/gerstner/", "profile", "EPFL full professor、LCN 主任、研究、奖项与本人照片"),
  gerstnerCv: source("Wulfram Gerstner · curriculum vitae", "https://lcnwww.epfl.ch/gerstner/wg_cv.html", "cv", "教育、Leo van Hemmen 博士指导、Berkeley 与 EPFL 任职时间轴"),
  gerstnerBmi: source("EPFL Brain Mind Institute · research groups", "https://www.epfl.ch/schools/sv/bmi/brain-mind-institute/bmi-research/", "official", "Wulfram Gerstner 为 LCN PI 及实验室研究范围"),
  hoeflerHome: source("Torsten Hoefler · ETH academic homepage", "https://htor.inf.ethz.ch/", "profile", "ETH full professor、SPCL 主任、博士与 UIUC/ETH 任职、研究和产业角色"),
  hoeflerCv: source("Torsten Hoefler · curriculum vitae", "https://htor.inf.ethz.ch/hoefler-cv.pdf", "cv", "教育、任职、Microsoft Azure 科学顾问及完整履历"),
  hoeflerLab: source("ETH SPCL · People", "https://spcl.inf.ethz.ch/People/", "official", "Torsten Hoefler 为实验室负责人及当前团队成员"),
  hoeflerAdvisor: source("Torsten Hoefler · commencement note", "https://htor.inf.ethz.ch/blog/index.php/2009/05/", "profile", "本人明确称 Andrew Lumsdaine 为博士导师"),
  hoeflerPortrait: source("Torsten Hoefler · biography and photos", "https://htor.inf.ethz.ch/bio/", "profile", "ETH 托管本人简介与可下载照片"),
  perrigEth: source("ETH Zurich · Adrian Perrig SATW profile", "https://inf.ethz.ch/news-and-events/spotlights/infk-news-channel/2023/03/adrian-perrig-and-olga-sorkine-hornung-elected-members-of-satw.html", "official", "ETH 教授、Network Security Group 负责人、SCION 研究与奖项"),
  perrigCmu: source("Carnegie Mellon Engineering · Adrian Perrig", "https://engineering.cmu.edu/directory/bios/perrig-adrian.html", "official", "EPFL/CMU 教育、CMU 任职、ETH 现职与研究"),
  perrigThesis: source("Carnegie Mellon CSD · Adrian Perrig doctoral degree", "https://csd.cmu.edu/academics/doctoral/degrees-conferred/adrian-perrig", "thesis", "博士论文题目、毕业时间及 Doug Tygar 博士导师"),
  perrigLab: source("ETH Network Security Group · Adrian Perrig", "https://netsec.ethz.ch/people/aperrig/", "official", "SCION 主项目、Anapaya Systems 创业与官方头像"),
  quekProfile: source("EPFL People · Yihui Quek", "https://people.epfl.ch/yihui.quek?lang=en", "official", "现任 tenure-track Assistant Professor、跨院系任职、课程与具名博士生"),
  quekHome: source("Yihui Quek · academic homepage", "https://sites.google.com/view/yihui-quek/", "profile", "EPFL 现职、MIT 本科、Stanford 博士与 Tsachy Weissman 指导、博士后导师和研究方向"),
  quekAppointment: source("EPFL · Yihui Quek appointed tenure-track Assistant Professor", "https://actu.epfl.ch/news/yihui-quek-newly-appointed-tenure-track-assistan-3/", "official", "2025 年联合 IC/SB 任命、此前 MIT 博士后与研究方向"),
  quekPortrait: source("EPFL · Yihui Quek profile interview", "https://actu.epfl.ch/news/i-thrive-in-environments-where-the-rules-aren-t--5", "official", "EPFL 当前职务、教育经历、研究议题和 Alain Herzog 官方照片"),
  cambridgeRoster: source("Cambridge CST · Faculty directory", "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", "official", "Cambridge CST 现任 faculty 名录"),
  muraliProfile: source("Cambridge CST · Prakash Murali", "https://www.cst.cam.ac.uk/people/pm830", "official", "Cambridge 现任职务、Princeton 博士、Microsoft Quantum 经历、研究、教学与奖项"),
  muraliAppointment: source("Cambridge CST · Prakash Murali appointment", "https://www.cst.cam.ac.uk/news/new-associate-professor-computer-architecture", "official", "2024 年 Cambridge Associate Professor 任命、Microsoft Quantum 经历与研究方向"),
  muraliAdvisor: source("Princeton CS · Graduate alumni · Prakash Murali", "https://www.cs.princeton.edu/people/gradalumni?page=15", "official", "2021 年 Princeton Computer Science 博士及 Margaret Martonosi 导师关系"),
  muraliPortrait: source("TartanQEC 2026 · Prakash Murali", "https://qec.codes/tartan2026/speakers/prakash-murali", "profile", "Cambridge affiliation and named speaker portrait"),
  neelProfile: source("Cambridge CST · Neel Krishnaswami", "https://www.cst.cam.ac.uk/people/nk480", "official", "Cambridge faculty 现职、研究主题和本人主页"),
  neelHome: source("Neel Krishnaswami · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~nk480/", "profile", "教授现职、CMU 博士、John Reynolds/Jonathan Aldrich 指导、任职轨迹、研究和逐名学生清单"),
  neelPortrait: source("Cambridge CST · Neel Krishnaswami portrait", "https://www.cst.cam.ac.uk/sites/default/files/images/profile/neel-krishnaswami-theme-image.jpg", "official", "Cambridge faculty profile portrait"),
  sauerwaldHome: source("Thomas Sauerwald · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~tms41/", "profile", "教授现职、研究、项目与逐名博士生/博士后清单"),
  sauerwaldBio: source("Emmanuel College Magazine · Thomas Sauerwald", "https://www.emma.cam.ac.uk/publications/EmmanuelMagazine2017.pdf", "official", "Paderborn 博士、Berkeley/Vancouver 博后、MPI 与 Cambridge 任职轨迹"),
  sauerwaldStudent: source("Dimitrios Los · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~dl516/", "profile", "本人明确 Thomas Sauerwald 为博士导师"),
  sauerwaldPortrait: source("Cambridge CST · Thomas Sauerwald portrait", "https://www.cst.cam.ac.uk/sites/default/files/images/profile/tms41.jpeg", "official", "Cambridge faculty portrait"),
} satisfies Record<string, Source>;

const fact = (label: string, value: string, s: Source) => ({ label, value, source: s });
type Seed = Omit<Person, "category" | "primary" | "status" | "introducedAt" | "lastVerifiedAt" | "portrait"> & { portraitFile: string; portraitSource: Source };
const person = (s: Seed): Person => ({ ...s, category: "core", primary: true, status: "current independent PI · strict third-round verification", introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-europe-third-round-batch-1-2026/${s.portraitFile}`, alt: `${s.name} 头像`, source: s.portraitSource } });

export const candidatePriorityP0EuropeThirdRoundBatch1People2026: Person[] = [
  person({ id: "thomas-bourgeat-epfl-p0-r3", name: "Thomas Bourgeat", role: "Tenure-Track Assistant Professor · VCA Lab", institution: "EPFL", region: "Europe", area: "Computer Architecture · Programming Languages · Formal Verification", tags: ["Computer Architecture", "Programming Languages", "Formal Verification", "Hardware Security"], summary: "EPFL Verification and Computer Architecture Lab 负责人，把高级硬件语言、定理证明与处理器/加速器设计连接起来。", stage: "emerging", x: 180, y: 250, portraitFile: "thomas-bourgeat.jpg", portraitSource: sources.bourgeatPortrait, facts: [fact("当前任职", "EPFL IC tenure-track Assistant Professor，并领导 Verification and Computer Architecture Lab。", sources.bourgeatProfile), fact("教育与学术训练", "2022 年获 MIT 博士学位，由 Arvind 与 Adam Chlipala 共同指导。", sources.bourgeatBio), fact("研究主线", "研究计算机体系结构、编程语言和形式化方法，开发可指定、设计并验证处理器与加速器的技术。", sources.bourgeatBio), fact("学生体系", "EPFL People 页面逐名列出 Martina Camaioni、Guokai Chen、Neelu Shivprakash Kalani、Jiawei Lin 等博士生。", sources.bourgeatProfile)], sources: [sources.epflRoster, sources.bourgeatProfile, sources.bourgeatBio, sources.bourgeatHome, sources.bourgeatPortrait] }),
  person({ id: "wulfram-gerstner-epfl-p0-r3", name: "Wulfram Gerstner", role: "Full Professor · Director, LCN", institution: "EPFL", region: "Europe", area: "Computational Neuroscience · Neural Networks · Learning Theory", tags: ["Computational Neuroscience", "Spiking Neural Networks", "Learning Theory", "Reinforcement Learning"], summary: "EPFL 计算神经科学资深带头人，围绕脉冲神经元、可塑性和多因子学习规则建立连接神经科学与机器学习的研究体系。", stage: "senior", x: 420, y: 250, portraitFile: "wulfram-gerstner.png", portraitSource: sources.gerstnerHome, facts: [fact("当前任职", "EPFL School of Life Sciences 与 School of Computer and Communication Sciences 联合任职 Full Professor，并领导 LCN。", sources.gerstnerHome), fact("教育与学术训练", "在 Tübingen 与 LMU Munich 学习物理，后于 Technical University of Munich 在 Leo van Hemmen 组完成博士研究。", sources.gerstnerCv), fact("研究主线", "研究脉冲神经元模型、脉冲神经网络动力学、STDP、多因子学习规则与 surprise-driven learning。", sources.gerstnerHome), fact("学术履历", "博士前后曾在 William Bialek 的 UC Berkeley 理论生物物理组、Brandeis 与 Munich 开展研究，1996 年加入 EPFL。", sources.gerstnerCv), fact("学术影响", "获 2018 Valentino Braitenberg Award，并当选 Mainz Academy of Sciences and Literature 成员。", sources.gerstnerHome)], sources: [sources.epflRoster, sources.gerstnerHome, sources.gerstnerCv, sources.gerstnerBmi] }),
  person({ id: "torsten-hoefler-eth-p0-r3", name: "Torsten Hoefler", role: "Full Professor · Director, SPCL", institution: "ETH Zurich", region: "Europe", area: "Scalable Computing · Distributed AI · High-Performance Networks", tags: ["High Performance Computing", "Distributed AI", "Parallel Systems", "AI Infrastructure"], summary: "ETH SPCL 负责人，从高性能网络、并行系统和性能建模延伸到大规模 AI 基础设施，并长期连接 Microsoft Azure。", stage: "senior", x: 660, y: 250, portraitFile: "torsten-hoefler.jpg", portraitSource: sources.hoeflerPortrait, facts: [fact("当前任职", "ETH Zurich Computer Science Full Professor，领导 Scalable Parallel Computing Laboratory，并任 Swiss National Supercomputing Centre Chief Architect for Machine Learning。", sources.hoeflerHome), fact("教育与学术训练", "TU Chemnitz Diplom；Indiana University Computer Science PhD，博士导师为 Andrew Lumsdaine。", sources.hoeflerAdvisor), fact("研究主线", "研究可扩展网络、并行编程、性能建模、分布式深度学习，以及面向天气和气候的高性能计算。", sources.hoeflerHome), fact("任职轨迹", "2011 年在 UIUC 开始首个教授职位，2013 年加入 ETH，并曾访问 Argonne、Sandia 与 Microsoft。", sources.hoeflerHome), fact("产业连接", "自 2017 年起任 Microsoft Azure 科学顾问，参与大规模 AI 网络、并行算法、稀疏/量化和 Maia 架构。", sources.hoeflerCv)], sources: [sources.ethRoster, sources.hoeflerHome, sources.hoeflerCv, sources.hoeflerLab, sources.hoeflerAdvisor, sources.hoeflerPortrait] }),
  person({ id: "adrian-perrig-eth-p0-r3", name: "Adrian Perrig", role: "Professor · Head, Network Security Group", institution: "ETH Zurich", region: "Europe", area: "Network Security · Secure Systems · Future Internet Architecture", tags: ["Network Security", "Secure Systems", "SCION", "Cybersecurity"], summary: "ETH Network Security Group 负责人，以 SCION 下一代安全互联网架构为主线，并共同创办 Anapaya Systems 推动产业落地。", stage: "senior", x: 900, y: 250, portraitFile: "adrian-perrig.jpg", portraitSource: sources.perrigLab, facts: [fact("当前任职", "ETH Zurich Computer Science Professor，领导 Institute for Information Security 的 Network Security Group。", sources.perrigEth), fact("教育与学术训练", "EPFL Computer Engineering BSc；Carnegie Mellon Computer Science MS/PhD，博士导师为 Doug Tygar。", sources.perrigThesis), fact("任职经历", "2002–2012 年任教 Carnegie Mellon，2009 年晋升 Full Professor，并曾任 CyLab Technical Director。", sources.perrigCmu), fact("研究主线", "研究安全与稳健网络系统，核心项目为下一代安全互联网架构 SCION。", sources.perrigEth), fact("产业连接", "Network Security Group 页面明确记录其共同创办 Anapaya Systems，将 SCION 技术商业化。", sources.perrigLab)], sources: [sources.ethRoster, sources.perrigEth, sources.perrigCmu, sources.perrigThesis, sources.perrigLab] }),
  person({ id: "yihui-quek-epfl-p0-r3", name: "Yihui Quek", role: "Tenure-Track Assistant Professor · Computer Science and Physics", institution: "EPFL", region: "Europe", area: "Quantum Algorithms · Learning Theory · Quantum Complexity", tags: ["Quantum Computing", "Learning Theory", "Quantum Algorithms", "Complexity Theory"], summary: "EPFL 计算机与物理联合任职的量子信息 PI，研究量子学习、纠错、复杂性和多体物理的计算边界。", stage: "emerging", x: 1140, y: 250, portraitFile: "yihui-quek.jpg", portraitSource: sources.quekPortrait, facts: [fact("当前任职", "自 2025 年起任 EPFL Computer Science and Physics tenure-track Assistant Professor，为 IC 与 SB 联合任命。", sources.quekAppointment), fact("教育与学术训练", "MIT Physics/Mathematics 本科；Stanford PhD（2017–2022），博士导师 Tsachy Weissman。", sources.quekHome), fact("博士后训练", "2022–2024 年先后在 FU Berlin、Harvard 和 MIT 开展博士后研究，合作导师包括 Aram Harrow、Peter Shor、Anurag Anshu、Susanne Yelin 与 Jens Eisert。", sources.quekHome), fact("研究主线", "研究量子算法、量子学习理论、纠错、计算复杂性与多体物理中的信息—计算鸿沟。", sources.quekHome), fact("学生体系", "EPFL People 页面明确列 Helen Olivia Propson 为其博士生。", sources.quekProfile)], sources: [sources.epflRoster, sources.quekProfile, sources.quekHome, sources.quekAppointment, sources.quekPortrait] }),
  person({ id: "prakash-murali-cambridge-p0-r3", name: "Prakash Murali", role: "Associate Professor · Computer Architecture", institution: "Cambridge", region: "Europe", area: "Quantum Architecture · Compilers · Resource Estimation", tags: ["Quantum Computing", "Computer Architecture", "Compilers", "Resource Estimation"], summary: "Cambridge 量子体系结构 PI，从编译与资源估算回答可扩展容错量子计算需要怎样的软硬件栈。", stage: "emerging", x: 1380, y: 250, portraitFile: "prakash-murali.png", portraitSource: sources.muraliPortrait, facts: [fact("当前任职", "University of Cambridge Computer Science and Technology Associate Professor in Computer Architecture。", sources.muraliAppointment), fact("教育与学术训练", "Indian Institute of Science 硕士；2021 年获 Princeton Computer Science PhD，导师 Margaret Martonosi。", sources.muraliAdvisor), fact("研究主线", "研究量子体系结构、资源估算、编译和软硬件协同设计，缩小算法需求与可实现硬件之间的资源鸿沟。", sources.muraliProfile), fact("产业经历", "加入 Cambridge 前任 Microsoft Quantum Senior Quantum Systems Architect，设计 Azure Quantum Resource Estimator。", sources.muraliProfile), fact("学术影响", "获 2022 ACM SIGARCH/IEEE CS TCCA Outstanding Dissertation Award、IBM PhD Fellowship 与 IEEE Micro Top Picks。", sources.muraliProfile)], sources: [sources.cambridgeRoster, sources.muraliProfile, sources.muraliAppointment, sources.muraliAdvisor, sources.muraliPortrait] }),
  person({ id: "neel-krishnaswami-cambridge-p0-r3", name: "Neel Krishnaswami", role: "Professor · Programming Languages and Verification", institution: "Cambridge", region: "Europe", area: "Programming Languages · Program Verification · Type Theory", tags: ["Programming Languages", "Formal Verification", "Type Theory", "Semantics"], summary: "Cambridge 编程语言与验证教授，从高阶分离逻辑、类型系统和语义研究可靠程序构造。", stage: "senior", x: 1620, y: 250, portraitFile: "neel-krishnaswami.jpg", portraitSource: sources.neelPortrait, facts: [fact("当前任职", "University of Cambridge Computer Science Professor，并为 Trinity College Fellow。", sources.neelHome), fact("教育与学术训练", "2011 年获 Carnegie Mellon University PhD，博士由 John C. Reynolds 与 Jonathan Aldrich 共同指导。", sources.neelHome), fact("研究主线", "研究程序验证、编程语言设计、逻辑、语义与类型理论的交叉。", sources.neelHome), fact("任职轨迹", "曾在 Microsoft Research 随 Nick Benton、MPI-SWS 随 Derek Dreyer 从事博士后研究，后任 Birmingham Fellow，再加入 Cambridge。", sources.neelHome), fact("学生体系", "本人主页逐名列出 Michael Arntzenius、Dima Szamozvancev、Faustyna Krawiec、Dhruv Makwana 等博士生。", sources.neelHome)], sources: [sources.cambridgeRoster, sources.neelProfile, sources.neelHome, sources.neelPortrait] }),
  person({ id: "thomas-sauerwald-cambridge-p0-r3", name: "Thomas Sauerwald", role: "Professor · Algorithms and Probability", institution: "Cambridge", region: "Europe", area: "Randomized Algorithms · Distributed Computing · Machine Learning", tags: ["Randomized Algorithms", "Distributed Computing", "Machine Learning", "Markov Chains"], summary: "Cambridge 算法与概率教授，围绕随机算法、负载均衡、随机游走和分布式系统建立研究与学生网络。", stage: "senior", x: 1860, y: 250, portraitFile: "thomas-sauerwald.jpg", portraitSource: sources.sauerwaldPortrait, facts: [fact("当前任职", "自 2020 年起任 Cambridge Professor of Algorithms and Probability，2013 年以 Lecturer 加入，并任 Emmanuel College Director of Studies。", sources.sauerwaldHome), fact("教育与学术训练", "在 University of Paderborn 获计算机博士，研究并行网络高效协议；随后在 Berkeley 与 Vancouver 开展博士后研究。", sources.sauerwaldBio), fact("任职经历", "在加入 Cambridge 前任 Max Planck Institute for Informatics Senior Researcher 和 Group Leader。", sources.sauerwaldBio), fact("研究主线", "研究随机算法、分布式计算、Markov chains、random walks、machine learning 与 data science。", sources.sauerwaldHome), fact("学生体系", "本人主页列出 Leran Cai、Dimitrios Los、Charlotte Out、Hayk Saribekyan 等博士生；Dimitrios Los 本人主页再次确认博士指导。", sources.sauerwaldStudent)], sources: [sources.cambridgeRoster, sources.sauerwaldHome, sources.sauerwaldBio, sources.sauerwaldStudent, sources.sauerwaldPortrait] }),
];

export const candidatePriorityP0EuropeThirdRoundBatch1SupportingPeople2026: Person[] = [
  { id: "arvind-mit-lineage-p0-eu-r3", name: "Arvind", role: "Professor", institution: "MIT", region: "United States", area: "Computer Architecture · Hardware Languages", tags: ["博士导师", "Computer Architecture"], summary: "Thomas Bourgeat 在 MIT 的共同博士导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [sources.bourgeatBio, sources.bourgeatHome], x: 120, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "adam-chlipala-mit-lineage-p0-eu-r3", name: "Adam Chlipala", role: "Professor", institution: "MIT", region: "United States", area: "Programming Languages · Formal Methods", tags: ["共同博士导师", "Formal Verification"], summary: "Thomas Bourgeat 在 MIT 的共同博士导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [sources.bourgeatBio, sources.bourgeatHome], x: 240, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "leo-van-hemmen-tum-lineage-p0-eu-r3", name: "Leo van Hemmen", role: "Professor", institution: "TUM", region: "Europe", area: "Theoretical Biophysics · Neural Networks", tags: ["博士导师", "Theoretical Neuroscience"], summary: "Wulfram Gerstner 在 TUM 博士阶段的导师。", stage: "historical", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [sources.gerstnerCv], x: 420, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "andrew-lumsdaine-lineage-p0-eu-r3", name: "Andrew Lumsdaine", role: "Professor", institution: "External", region: "United States", area: "Parallel Computing · Software Systems", tags: ["博士导师", "Parallel Computing"], summary: "Torsten Hoefler 在 Indiana University 博士阶段的导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [sources.hoeflerAdvisor], x: 660, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "doug-tygar-berkeley-lineage-p0-eu-r3", name: "Doug Tygar", role: "Professor", institution: "Berkeley", region: "United States", area: "Computer Security · Privacy", tags: ["博士导师", "Computer Security"], summary: "Adrian Perrig 在 Carnegie Mellon 博士阶段的导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [sources.perrigThesis], x: 900, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "margaret-martonosi-princeton-lineage-p0-eu-r3", name: "Margaret Martonosi", role: "University Professor", institution: "Princeton", region: "United States", area: "Computer Architecture · Quantum Systems", tags: ["博士导师", "Computer Architecture"], summary: "Prakash Murali 在 Princeton 的博士导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [sources.muraliAdvisor], x: 1380, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "john-reynolds-cmu-lineage-p0-eu-r3", name: "John C. Reynolds", role: "Professor", institution: "CMU", region: "United States", area: "Programming Languages · Separation Logic", tags: ["共同博士导师", "Programming Languages"], summary: "Neel Krishnaswami 在 Carnegie Mellon 的共同博士导师。", stage: "historical", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [sources.neelHome], x: 1560, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "jonathan-aldrich-cmu-lineage-p0-eu-r3", name: "Jonathan Aldrich", role: "Professor", institution: "CMU", region: "United States", area: "Programming Languages · Software Engineering", tags: ["共同博士导师", "Programming Languages"], summary: "Neel Krishnaswami 在 Carnegie Mellon 的共同博士导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [sources.neelHome], x: 1680, y: 20, primary: false, lastVerifiedAt: checkedAt },
];

export const candidatePriorityP0EuropeThirdRoundBatch1Relationships2026: Relationship[] = [
  { id: "p0-eu-r3-arvind-bourgeat", from: "arvind-mit-lineage-p0-eu-r3", to: "thomas-bourgeat-epfl-p0-r3", type: "lineage", subtype: "co_adviser", label: "共同博士导师", evidence: "EPFL inaugural lecture 与 Thomas Bourgeat 本人主页均明确其 MIT 博士由 Arvind 与 Adam Chlipala 指导。", source: sources.bourgeatBio, verified: true, endYear: 2022 },
  { id: "p0-eu-r3-chlipala-bourgeat", from: "adam-chlipala-mit-lineage-p0-eu-r3", to: "thomas-bourgeat-epfl-p0-r3", type: "lineage", subtype: "co_adviser", label: "共同博士导师", evidence: "EPFL inaugural lecture 与 Thomas Bourgeat 本人主页均明确其 MIT 博士由 Arvind 与 Adam Chlipala 指导。", source: sources.bourgeatBio, verified: true, endYear: 2022 },
  { id: "p0-eu-r3-hemmen-gerstner", from: "leo-van-hemmen-tum-lineage-p0-eu-r3", to: "wulfram-gerstner-epfl-p0-r3", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Wulfram Gerstner 本人 CV 记录其 1990–1993 年在 TUM Leo van Hemmen 组开展博士研究。", source: sources.gerstnerCv, verified: true, endYear: 1993 },
  { id: "p0-eu-r3-lumsdaine-hoefler", from: "andrew-lumsdaine-lineage-p0-eu-r3", to: "torsten-hoefler-eth-p0-r3", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Torsten Hoefler 本人博士毕业记录明确称 Andrew Lumsdaine 为其 advisor。", source: sources.hoeflerAdvisor, verified: true, endYear: 2008 },
  { id: "p0-eu-r3-tygar-perrig", from: "doug-tygar-berkeley-lineage-p0-eu-r3", to: "adrian-perrig-eth-p0-r3", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Carnegie Mellon CSD 博士学位记录明确列 Doug Tygar 为 Adrian Perrig 的博士导师。", source: sources.perrigThesis, verified: true, endYear: 2002 },
  { id: "p0-eu-r3-weissman-quek", from: "tsachy-weissman-stanford-p0-b9", to: "yihui-quek-epfl-p0-r3", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Yihui Quek 本人学术主页明确记录其 Stanford 博士导师为 Tsachy Weissman。", source: sources.quekHome, verified: true, endYear: 2022 },
  { id: "p0-eu-r3-martonosi-murali", from: "margaret-martonosi-princeton-lineage-p0-eu-r3", to: "prakash-murali-cambridge-p0-r3", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Princeton CS Graduate Alumni 页面明确列 Margaret Martonosi 为 Prakash Murali 的博士导师。", source: sources.muraliAdvisor, verified: true, endYear: 2021 },
  { id: "p0-eu-r3-reynolds-neel", from: "john-reynolds-cmu-lineage-p0-eu-r3", to: "neel-krishnaswami-cambridge-p0-r3", type: "lineage", subtype: "co_adviser", label: "共同博士导师", evidence: "Neel Krishnaswami 本人 Cambridge 主页明确其博士由 John C. Reynolds 与 Jonathan Aldrich 共同指导。", source: sources.neelHome, verified: true, endYear: 2011 },
  { id: "p0-eu-r3-aldrich-neel", from: "jonathan-aldrich-cmu-lineage-p0-eu-r3", to: "neel-krishnaswami-cambridge-p0-r3", type: "lineage", subtype: "co_adviser", label: "共同博士导师", evidence: "Neel Krishnaswami 本人 Cambridge 主页明确其博士由 John C. Reynolds 与 Jonathan Aldrich 共同指导。", source: sources.neelHome, verified: true, endYear: 2011 },
];

export const candidatePriorityP0EuropeThirdRoundBatch1Placements2026: StudentPlacement[] = [];
export const candidatePriorityP0EuropeThirdRoundBatch1GroupMembers2026: GroupMember[] = [
  { id: "p0-eu-r3-bourgeat-guokai-chen", teacherId: "thomas-bourgeat-epfl-p0-r3", name: "Guokai Chen", role: "Current PhD student", focus: "Verification and computer architecture", source: sources.bourgeatProfile },
  { id: "p0-eu-r3-hoefler-langwen-huang", teacherId: "torsten-hoefler-eth-p0-r3", name: "Langwen Huang", role: "SPCL member", focus: "Scalable parallel computing", source: sources.hoeflerLab },
  { id: "p0-eu-r3-quek-helen-propson", teacherId: "yihui-quek-epfl-p0-r3", name: "Helen Olivia Propson", role: "Current PhD student", focus: "Quantum information and computation", source: sources.quekProfile },
  { id: "p0-eu-r3-neel-faustyna-krawiec", teacherId: "neel-krishnaswami-cambridge-p0-r3", name: "Faustyna Krawiec", role: "PhD student", focus: "Programming languages and verification", source: sources.neelHome },
  { id: "p0-eu-r3-sauerwald-dimitrios-los", teacherId: "thomas-sauerwald-cambridge-p0-r3", name: "Dimitrios Los", role: "Former PhD student", focus: "Randomized load balancing algorithms", source: sources.sauerwaldStudent },
];

export const candidatePriorityP0EuropeThirdRoundBatch1RosterPromotions2026 = [
  { unitUrl: sources.epflRoster.url, rosterName: "Thomas Bourgeat", atlasPersonId: "thomas-bourgeat-epfl-p0-r3" },
  { unitUrl: sources.epflRoster.url, rosterName: "Wulfram Gerstner", atlasPersonId: "wulfram-gerstner-epfl-p0-r3" },
  { unitUrl: sources.ethRoster.url, rosterName: "Torsten Hoefler", atlasPersonId: "torsten-hoefler-eth-p0-r3" },
  { unitUrl: sources.ethRoster.url, rosterName: "Adrian Perrig", atlasPersonId: "adrian-perrig-eth-p0-r3" },
  { unitUrl: sources.epflRoster.url, rosterName: "Yihui Quek", atlasPersonId: "yihui-quek-epfl-p0-r3" },
  { unitUrl: sources.cambridgeRoster.url, rosterName: "Prakash Murali", atlasPersonId: "prakash-murali-cambridge-p0-r3" },
  { unitUrl: sources.cambridgeRoster.url, rosterName: "Neel Krishnaswami", atlasPersonId: "neel-krishnaswami-cambridge-p0-r3" },
  { unitUrl: sources.cambridgeRoster.url, rosterName: "Thomas Sauerwald", atlasPersonId: "thomas-sauerwald-cambridge-p0-r3" },
] as const;

export const people = [...candidatePriorityP0EuropeThirdRoundBatch1People2026, ...candidatePriorityP0EuropeThirdRoundBatch1SupportingPeople2026];
export const relationships = candidatePriorityP0EuropeThirdRoundBatch1Relationships2026;
export const placements = candidatePriorityP0EuropeThirdRoundBatch1Placements2026;
export const groupMembers = candidatePriorityP0EuropeThirdRoundBatch1GroupMembers2026;
export const rosterPromotions = candidatePriorityP0EuropeThirdRoundBatch1RosterPromotions2026;
