import type { Person, Relationship, Source } from "./data";

const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const fact = (label: string, value: string, proof: Source) => ({ label, value, source: proof });

const roster = source("SUTD ISTD · Faculty", "https://www.sutd.edu.sg/istd/people/faculty", "official", "现任 ISTD 教师名录");
const profiles = {
  cao: source("SUTD · Cao Rui", "https://www.sutd.edu.sg/istd/profile/cao-rui/", "official", "现职、教育、研究方向与官方头像"),
  chee: source("SUTD · Chee Yeow Meng", "https://www.sutd.edu.sg/istd/profile/chee-yeow-meng/", "official", "现职、教育、履历、研究与官方头像"),
  chen: source("SUTD · Chen Binbin", "https://www.sutd.edu.sg/istd/profile/chen-binbin/", "official", "现职、教育、履历、研究、论文与官方头像"),
  choo: source("SUTD · Kenny Choo", "https://www.sutd.edu.sg/istd/profile/kenny-choo/", "official", "现职、教育、博士导师、履历与官方头像"),
  herremans: source("SUTD · Dorien Herremans", "https://www.sutd.edu.sg/istd/profile/dorien-herremans/", "official", "现职、教育、履历、研究、论文与官方头像"),
  kassim: source("SUTD · Ashraf Kassim", "https://www.sutd.edu.sg/istd/profile/ashraf-kassim/", "official", "现职、教育、履历、研究、论文与官方头像"),
  li: source("SUTD · Li Xiaoli", "https://www.sutd.edu.sg/istd/profile/li-xiaoli/", "official", "现职、教育、产业履历、研究、论文与官方头像"),
  mashima: source("SUTD · Daisuke Mashima", "https://www.sutd.edu.sg/istd/profile/daisuke-mashima/", "official", "现职、教育、履历、研究、论文与官方头像"),
  meghjani: source("SUTD · Malika Meghjani", "https://www.sutd.edu.sg/istd/profile/malika-meghjani/", "official", "现职、教育、履历、研究、论文与官方头像"),
  park: source("SUTD · Jihong Park", "https://www.sutd.edu.sg/istd/profile/park-jihong/", "official", "现职、教育、履历、研究与官方头像"),
  quek: source("SUTD · Tony Quek", "https://www.sutd.edu.sg/istd/profile/tony-quek/", "official", "现职、教育、领导岗位、研究与官方头像"),
  soremekun: source("SUTD · Ezekiel Soremekun", "https://www.sutd.edu.sg/istd/profile/ezekiel-soremekun/", "official", "现职、教育、履历、研究、论文与官方头像"),
  sun: source("SUTD · Zhu Sun", "https://www.sutd.edu.sg/istd/profile/sun-zhu/", "official", "现职、教育、研究与官方头像"),
  wang: source("SUTD · Angela Bo Wang", "https://www.sutd.edu.sg/istd/profile/angela-wang-bo/", "official", "现职、教育、履历、合作与官方头像"),
  yau: source("SUTD · David Yau", "https://www.sutd.edu.sg/istd/profile/david-yau/", "official", "现职、教育、履历、研究与官方头像"),
  zhou: source("SUTD · Jianying Zhou", "https://www.sutd.edu.sg/istd/profile/zhou-jianying/", "official", "现职、教育、研究与官方头像"),
};

const caoThesis = source("SMU SCIS · Cao Rui dissertation proposal", "https://computing.smu.edu.sg/newsletter/phd-dissertation-proposal-cao-rui-using-pre-trained-models-multimodal-understanding", "thesis", "博士生身份、论文题目与导师 Jing Jiang");
const cheePaper = source("SUTD repository · Quantum channel fidelity", "https://repository.sutd.edu.sg/esploro/outputs/journalArticle/An-Efficient-Parameterized-Algorithm-for-Computing/9911089309846", "publication", "Chee Yeow Meng、Hoang Ta 与 Van Khu Vu 的完整共同署名");
const parkProject = source("Deakin · Cisco quantum research project", "https://www.deakin.edu.au/research/research-news-and-publications/articles/phd-scholarship-boost-for-deakin-and-cisco-quantum-computing-research", "official", "Jihong Park、Jinho Choi 与 Seng Loke 共同领导项目");
const astralis = source("SUTD Temasek Labs · ASTRALIS", "https://www.sutd.edu.sg/temasek-labs/research-project-listing/astralis/", "official", "Tony Quek 为 PI，Ernest Chong 与 Malika Meghjani 为共同 PI");
const sunGroup = source("Zhu Sun · research group", "https://sites.google.com/view/zhusun/home", "profile", "当前研究组成员与研究方向");
const yauProject = source("SUTD iTrust · research project newsletter", "https://www.sutd.edu.sg/itrust/wp-content/uploads/sites/15/2025/10/itrust-newsletter-issue1.pdf", "official", "David Yau 与 Nils Ole Tippenhauer 等共同参与基础设施安全项目");
const zhouProject = source("SUTD iTrust · Research projects", "https://www.sutd.edu.sg/itrust/research/research-projects/itrust-projects/", "official", "Jianying Zhou 与 Gauthama Raman M R 共同负责 AICrit 项目");

type PersonSpec = {
  id: string; name: string; role: string; area: string; tags: string[]; summary: string; stage: "senior" | "emerging";
  portrait: string; profile: Source; x: number; y: number; facts: { label: string; value: string; source: Source }[]; extras?: Source[];
};
const makePerson = (p: PersonSpec): Person => ({
  id: p.id, name: p.name, role: p.role, institution: "SUTD", region: "Singapore", area: p.area, tags: p.tags,
  summary: p.summary, category: "core", primary: true, stage: p.stage, status: "current independent PI · official profile verified",
  x: p.x, y: p.y, introducedAt: checkedAt, lastVerifiedAt: checkedAt,
  portrait: { src: `portraits/candidate-p0-hk-sg-second-round-2026/${p.portrait}.png`, alt: `${p.name} 官方头像`, source: p.profile },
  sources: [p.profile, roster, ...(p.extras ?? [])], facts: p.facts,
});

export const candidatePriorityP0HkSgThirdRoundPeople2026: Person[] = [
  makePerson({ id: "rui-cao-sutd-p0-r3", name: "Rui Cao", role: "Assistant Professor", area: "Multimodal AI · Foundation Models · Trustworthy AI", tags: ["Multimodal AI", "Foundation Models", "Trustworthy AI", "Vision-Language"], summary: "SUTD ISTD tenure-track 助理教授，研究可靠、可解释且安全的多模态基础模型。", stage: "emerging", portrait: "caorui", profile: profiles.cao, extras: [caoThesis], x: 120, y: 130, facts: [fact("当前任职", "SUTD ISTD tenure-track 助理教授。", profiles.cao), fact("教育与学术训练", "在 Singapore Management University 获博士，后在 University of Cambridge 从事博士后研究。", profiles.cao), fact("研究主线", "研究视觉—语言交叉及基础模型的可解释性、组合性、可信性与安全。", profiles.cao), fact("师承关系", "SMU 博士论文提案页明确记录其由 Jing Jiang 指导。", caoThesis)] }),
  makePerson({ id: "yeow-meng-chee-sutd-p0-r3", name: "Yeow Meng Chee", role: "Provost · Chief Academic & Innovation Officer · Chair Professor", area: "Coding Theory · Combinatorics · Theoretical CS", tags: ["Coding Theory", "Combinatorics", "Theoretical CS"], summary: "SUTD 教务长兼首席学术与创新官、讲席教授，研究组合数学与计算机科学交叉。", stage: "senior", portrait: "cheeyeowmeng", profile: profiles.chee, extras: [cheePaper], x: 300, y: 130, facts: [fact("当前任职", "SUTD 教务长兼首席学术与创新官、Cheng Tsang Man Chair Professor。", profiles.chee), fact("教育与学术训练", "在 University of Waterloo 获计算机科学 MMath 与 PhD，并获数学学士。", profiles.chee), fact("任职轨迹", "曾在 NUS、NTU 及新加坡公共部门担任学术、创新与信息安全领导职务。", profiles.chee), fact("研究主线", "研究编码理论、极值集合系统及组合数学与计算机科学的交叉。", profiles.chee), fact("合作关系", "SUTD 机构仓储记录其与 Van Khu Vu 等共同发表量子信道保真度研究。", cheePaper)] }),
  makePerson({ id: "binbin-chen-sutd-p0-r3", name: "Binbin Chen", role: "Associate Professor · FCP Deputy Director", area: "Distributed Systems · Cybersecurity · Wireless Networks", tags: ["Distributed Systems", "Cybersecurity", "Wireless Networks", "Critical Infrastructure"], summary: "SUTD ISTD 副教授、Future Communications Programme 副主任，研究关键基础设施安全与分布式网络。", stage: "senior", portrait: "chenbinbin", profile: profiles.chen, x: 480, y: 130, facts: [fact("当前任职", "SUTD ISTD 副教授，并任 Future Communications R&D Programme 副主任。", profiles.chen), fact("教育与学术训练", "在 Peking University 获计算机科学学士，在 NUS 获计算机科学博士。", profiles.chen), fact("任职轨迹", "加入 SUTD 前在 University of Illinois 的 Advanced Digital Sciences Center 任 Principal Research Scientist。", profiles.chen), fact("研究主线", "研究无线网络、分布式系统与关键基础设施网络安全。", profiles.chen), fact("合作关系", "官方论文列表记录其与 Daisuke Mashima 持续合作工业控制系统与智能电网安全研究。", profiles.chen)] }),
  makePerson({ id: "kenny-choo-sutd-p0-r3", name: "Kenny Choo", role: "Assistant Professor", area: "Human-Computer Interaction · Mobile Sensing · Empathetic Computing", tags: ["HCI", "Mobile Sensing", "Empathetic Computing", "Accessibility"], summary: "SUTD ISTD 助理教授，研究移动感知、无障碍交互与同理计算界面。", stage: "emerging", portrait: "chookenny", profile: profiles.choo, x: 660, y: 130, facts: [fact("当前任职", "2019 年起任 SUTD 助理教授。", profiles.choo), fact("教育与学术训练", "2018 年于 Singapore Management University 获博士学位。", profiles.choo), fact("师承关系", "官方简介明确记录博士阶段由 Youngki Lee、Rajesh Balan 与 Archan Misra 指导。", profiles.choo), fact("产业经历", "攻读博士前曾在 DSO National Laboratories 工作六年。", profiles.choo), fact("研究主线", "研究以移动感知和情境监测支持健康、福祉与无障碍体验的同理计算。", profiles.choo)] }),
  makePerson({ id: "dorien-herremans-sutd-p0-r3", name: "Dorien Herremans", role: "Associate Professor · Game Lab Director", area: "AI for Music · Affective Computing · FinTech", tags: ["AI for Music", "Affective Computing", "Machine Learning", "FinTech"], summary: "SUTD 副教授、Game Lab 主任，研究音乐、音频、情感计算与金融科技中的 AI。", stage: "senior", portrait: "herremansdorien", profile: profiles.herremans, x: 840, y: 130, facts: [fact("当前任职", "SUTD 副教授、Game Lab 主任。", profiles.herremans), fact("教育与学术训练", "在 University of Antwerp 获应用经济学博士与管理信息系统硕士。", profiles.herremans), fact("任职轨迹", "曾任 Queen Mary University of London 玛丽·居里博士后，并曾与 A*STAR 联合任职。", profiles.herremans), fact("研究主线", "研究音乐生成、音乐分类及 AI 在音频、情感计算与 FinTech 的应用。", profiles.herremans), fact("合作关系", "官方代表论文列表记录其与 Elaine Chew 共同发表音乐生成系统分类研究。", profiles.herremans)] }),
  makePerson({ id: "ashraf-kassim-sutd-p0-r3", name: "Ashraf A. Kassim", role: "Associate Provost · Professor", area: "Computer Vision · Medical Imaging · Deep Learning", tags: ["Computer Vision", "Medical Imaging", "Image Processing", "Deep Learning"], summary: "SUTD 教育与创新副教务长、ISTD 教授，研究计算机视觉、医学影像与机器学习。", stage: "senior", portrait: "kassimashrafa", profile: profiles.kassim, x: 120, y: 340, facts: [fact("当前任职", "SUTD 教育与创新副教务长、ISTD 教授。", profiles.kassim), fact("教育与学术训练", "在 NUS 获工程学士与硕士，在 Carnegie Mellon University 获博士。", profiles.kassim), fact("产业经历", "加入学术界前曾在 Texas Instruments 研发用于芯片制造自动化的机器视觉算法。", profiles.kassim), fact("研究主线", "研究计算机视觉、医学影像、图像处理与机器/深度学习。", profiles.kassim), fact("合作关系", "官方出版清单记录其与 B. V. K. Vijaya Kumar 合作神经网络路径规划研究。", profiles.kassim)] }),
  makePerson({ id: "xiaoli-li-sutd-p0-r3", name: "Xiaoli Li", role: "ISTD Head · Chair Professor", area: "Machine Learning · Data Mining · Graph Learning", tags: ["Machine Learning", "Data Mining", "Graph Learning", "Time Series"], summary: "SUTD ISTD 主任、讲席教授，长期在 A*STAR 领导大规模 AI 研究与产业转化。", stage: "senior", portrait: "lixiaoli", profile: profiles.li, x: 300, y: 340, facts: [fact("当前任职", "2025 年起任 SUTD ISTD 主任。", profiles.li), fact("教育与学术训练", "2001 年于 Chinese Academy of Sciences Institute of Computing Technology 获博士。", profiles.li), fact("任职轨迹", "曾任 A*STAR I²R Machine Intellection 部门负责人，领导超过一百名科研人员。", profiles.li), fact("研究主线", "研究机器学习、数据挖掘、图学习与时间序列分析。", profiles.li), fact("合作关系", "官方论文清单记录其与 Aixin Sun 共同发表自然语言视频定位研究。", profiles.li)] }),
  makePerson({ id: "daisuke-mashima-sutd-p0-r3", name: "Daisuke Mashima", role: "Associate Professor", area: "Cyber-Physical Security · Smart Grid · Digital Twins", tags: ["Cybersecurity", "Cyber-Physical Systems", "Smart Grid", "Digital Twins"], summary: "SUTD ISTD 副教授，研究工业控制系统、智能电网与关键基础设施安全。", stage: "senior", portrait: "mashimadaisuke", profile: profiles.mashima, x: 480, y: 340, facts: [fact("当前任职", "SUTD ISTD 副教授。", profiles.mashima), fact("教育与学术训练", "2012 年于 Georgia Institute of Technology 获计算机科学博士。", profiles.mashima), fact("任职轨迹", "曾任 Illinois ARCS Principal Research Scientist、NUS 兼职副教授及 Fujitsu Research of America 研究员。", profiles.mashima), fact("研究主线", "研究工业控制与信息物理系统安全、智能电网、欺骗技术及数字孪生。", profiles.mashima), fact("合作关系", "SUTD 官方论文列表记录其与 Binbin Chen 持续合作工业控制系统安全研究。", profiles.mashima)] }),
  makePerson({ id: "malika-meghjani-sutd-p0-r3", name: "Malika Meghjani", role: "Associate Professor", area: "Robotics · Computer Vision · Reinforcement Learning", tags: ["Robotics", "Computer Vision", "Machine Learning", "Reinforcement Learning"], summary: "SUTD 副教授，研究机器人、计算机视觉、规划与强化学习。", stage: "senior", portrait: "meghjanimalika", profile: profiles.meghjani, extras: [astralis], x: 660, y: 340, facts: [fact("当前任职", "SUTD 副教授，并公开招募机器人、视觉、机器学习与强化学习方向博士生和研究助理。", profiles.meghjani), fact("教育与学术训练", "在 McGill University 获电气与计算机工程硕士及计算机科学博士。", profiles.meghjani), fact("任职轨迹", "加入 SUTD 前任 SMART Autonomous Vehicle Lab Lead Research Scientist。", profiles.meghjani), fact("研究主线", "研究机器人感知、规划、计算机视觉、机器学习与强化学习。", profiles.meghjani), fact("合作关系", "SUTD ASTRALIS 项目页明确列其与 Tony Quek、Ernest Chong 共同负责项目。", astralis)] }),
  makePerson({ id: "jihong-park-sutd-p0-r3", name: "Jihong Park", role: "Associate Professor · FCP Deputy Director", area: "AI-native Communications · Distributed ML · 6G", tags: ["AI-native RAN", "Distributed ML", "Semantic Communications", "6G"], summary: "SUTD 副教授、Future Communications Programme 副主任，研究 6G 的 AI-native 通信与分布式学习。", stage: "senior", portrait: "parkjihong", profile: profiles.park, extras: [parkProject], x: 840, y: 340, facts: [fact("当前任职", "SUTD 副教授，并任 Future Communications R&D Programme 副主任。", profiles.park), fact("教育与学术训练", "在 Yonsei University 获电气与计算机工程学士和博士。", profiles.park), fact("任职轨迹", "曾在 Aalborg、Oulu 从事博士后研究，并任 Deakin University Lecturer。", profiles.park), fact("研究主线", "研究 AI-native 语义通信、面向 6G 的分布式机器学习。", profiles.park), fact("合作关系", "Deakin 官方项目页记录其与 Jinho Choi、Seng Loke 共同领导量子网络研究。", parkProject)] }),
  makePerson({ id: "tony-quek-sutd-p0-r3", name: "Tony Q. S. Quek", role: "Associate Provost (AI) · Chair Professor", area: "AI-RAN · Wireless Networks · 6G", tags: ["AI-RAN", "Wireless Networks", "6G", "Federated Learning"], summary: "SUTD 人工智能与数字创新副教务长、讲席教授，研究 AI-RAN、无线网络与 6G。", stage: "senior", portrait: "quektony", profile: profiles.quek, extras: [astralis], x: 120, y: 550, facts: [fact("当前任职", "SUTD 人工智能与数字创新副教务长、Cheng Tsang Man Chair Professor。", profiles.quek), fact("教育与学术训练", "在 Tokyo Institute of Technology 获学士与硕士，在 MIT 获电气工程与计算机科学博士。", profiles.quek), fact("领导经历", "任 Future Communications R&D Programme 主任及 AI-RAN Alliance 工作组主席。", profiles.quek), fact("研究主线", "研究无线通信、网络智能、AI-RAN、非地面网络与 6G。", profiles.quek), fact("合作关系", "SUTD ASTRALIS 项目页明确列其为 PI，Ernest Chong 与 Malika Meghjani 为共同 PI。", astralis)] }),
  makePerson({ id: "ezekiel-soremekun-sutd-p0-r3", name: "Ezekiel Soremekun", role: "Assistant Professor", area: "AI for Software Engineering · Software Testing · ML Safety", tags: ["Software Engineering", "Software Testing", "AI Safety", "LLM Testing"], summary: "SUTD ISTD 助理教授，研究软件验证、自动调试及 AI/ML 系统的可靠性与公平性。", stage: "emerging", portrait: "soremekunezekiel", profile: profiles.soremekun, x: 300, y: 550, facts: [fact("当前任职", "2024 年起任 SUTD 助理教授。", profiles.soremekun), fact("教育与学术训练", "在 Saarland University/CISPA 完成博士训练，2021 年获博士。", profiles.soremekun), fact("任职轨迹", "曾任 University of Luxembourg 研究科学家/PI 与 Royal Holloway Lecturer。", profiles.soremekun), fact("研究主线", "研究自动调试、软件测试、程序分析、安全及 AI/ML 系统测试。", profiles.soremekun), fact("合作关系", "官方代表论文列表记录其与 Marcel Böhme 合作故障定位和程序切片研究。", profiles.soremekun)] }),
  makePerson({ id: "zhu-sun-sutd-p0-r3", name: "Zhu Sun", role: "Assistant Professor", area: "Trustworthy Recommender Systems · Machine Learning", tags: ["Recommender Systems", "Trustworthy AI", "Machine Learning", "Data Mining"], summary: "SUTD ISTD 助理教授，研究可信推荐系统与人工智能。", stage: "emerging", portrait: "sunzhu", profile: profiles.sun, extras: [sunGroup], x: 480, y: 550, facts: [fact("当前任职", "SUTD ISTD 助理教授。", profiles.sun), fact("教育与学术训练", "在 Nanyang Technological University 获博士学位。", profiles.sun), fact("研究主线", "研究人工智能，重点关注可信推荐系统。", profiles.sun), fact("学术服务", "任 ECRA 与 ACM TORS 副编辑，并长期服务 KDD、SIGIR、IJCAI、AAAI 等会议。", profiles.sun), fact("研究组", "个人研究组主页公开列出 Qingyun Gao 等当前组员。", sunGroup)] }),
  makePerson({ id: "angela-bo-wang-sutd-p0-r3", name: "Angela Bo Wang", role: "Assistant Professor · SUTD AI Centre PI", area: "Edge AI · Neuromorphic Computing · Computer Architecture", tags: ["Edge AI", "Neuromorphic Computing", "Computer Architecture", "Biomedical Wearables"], summary: "SUTD 助理教授、AI Centre PI，研究边缘 AI、神经形态计算与低功耗计算系统。", stage: "emerging", portrait: "wangboangela", profile: profiles.wang, x: 660, y: 550, facts: [fact("当前任职", "2020 年起任 SUTD 助理教授及 SUTD AI Centre PI。", profiles.wang), fact("教育与学术训练", "2015 年于 Nanyang Technological University 获博士。", profiles.wang), fact("任职轨迹", "曾任 MediaTek Singapore 工程师，后在 NUS 任 Research Fellow。", profiles.wang), fact("研究主线", "研究片上 AI、神经形态计算、生物医学可穿戴设备与低电压存储。", profiles.wang), fact("合作关系", "官方简介明确记录其研究组与 NUS 的 Peh Li-Shiuan 教授合作边缘 AI 系统。", profiles.wang)] }),
  makePerson({ id: "david-yau-sutd-p0-r3", name: "David Yau", role: "Professor", area: "Networked Systems · Cybersecurity · Smart Grid", tags: ["Networks", "Cybersecurity", "Smart Grid", "Distributed Systems"], summary: "SUTD ISTD 教授，研究网络系统、信息物理基础设施与安全。", stage: "senior", portrait: "yaudavid", profile: profiles.yau, extras: [yauProject], x: 840, y: 550, facts: [fact("当前任职", "2013 年起任 SUTD ISTD 教授。", profiles.yau), fact("教育与学术训练", "在 CUHK 获计算机科学学士，在 University of Texas at Austin 获计算机科学硕士与博士。", profiles.yau), fact("任职轨迹", "曾任 Illinois ADSC Distinguished Scientist/Cybersecurity Programme Director，并曾任 Purdue 助理教授、副教授。", profiles.yau), fact("研究主线", "研究网络系统、安全与智能电网等信息物理基础设施。", profiles.yau), fact("合作关系", "SUTD iTrust 项目清单记录其与 Nils Ole Tippenhauer 等共同参与公共基础设施安全研究。", yauProject)] }),
  makePerson({ id: "jianying-zhou-sutd-p0-r3", name: "Jianying Zhou", role: "Professor · iTrust Centre Director", area: "Applied Cryptography · Network Security · Cyber-Physical Security", tags: ["Cryptography", "Network Security", "Cyber-Physical Security", "Mobile Security"], summary: "SUTD 教授、iTrust 研究中心主任，研究应用密码学与信息物理系统安全。", stage: "senior", portrait: "zhoujianying", profile: profiles.zhou, extras: [zhouProject], x: 480, y: 760, facts: [fact("当前任职", "SUTD 教授并任 iTrust 研究中心主任。", profiles.zhou), fact("教育与学术训练", "在 Royal Holloway, University of London 获信息安全博士。", profiles.zhou), fact("研究主线", "研究应用密码学、网络安全、信息物理系统安全及移动与无线安全。", profiles.zhou), fact("学术组织", "共同创办并长期参与 ACNS 与 AsiaCCS 等安全会议。", profiles.zhou), fact("合作关系", "SUTD iTrust 项目页记录其与 Gauthama Raman M R 共同负责 AICrit。", zhouProject)] }),
];

export const candidatePriorityP0HkSgThirdRoundSupportingPeople2026: Person[] = [
  { id: "van-khu-vu-p0-r3-support", name: "Van Khu Vu", role: "Research collaborator", institution: "External", area: "Coding Theory", tags: ["Coding Theory"], summary: "Yeow Meng Chee 的论文合作者。", category: "adjacent", primary: false, stage: "adjacent", x: 100, y: 900, sources: [cheePaper], facts: [fact("合作关系", "SUTD 机构仓储记录两人共同论文。", cheePaper)] },
  { id: "youngki-lee-p0-r3-support", name: "Youngki Lee", role: "PhD co-adviser", institution: "External", area: "Mobile Computing · HCI", tags: ["博士导师", "Mobile Computing"], summary: "Kenny Choo 的博士共同导师。", category: "adjacent", primary: false, stage: "adjacent", x: 240, y: 900, sources: [profiles.choo], facts: [fact("师承关系", "SUTD 官方简介明确记录 Youngki Lee 为其博士导师之一。", profiles.choo)] },
  { id: "elaine-chew-p0-r3-support", name: "Elaine Chew", role: "Research collaborator", institution: "External", area: "Music Computing", tags: ["Music Computing"], summary: "Dorien Herremans 的音乐生成论文合作者。", category: "adjacent", primary: false, stage: "adjacent", x: 380, y: 900, sources: [profiles.herremans], facts: [fact("合作关系", "SUTD 官方论文列表记录两人共同论文。", profiles.herremans)] },
  { id: "bvkv-kumar-p0-r3-support", name: "B. V. K. Vijaya Kumar", role: "Research collaborator", institution: "External", region: "United States", area: "Computer Vision · Pattern Recognition", tags: ["Computer Vision", "Pattern Recognition"], summary: "Ashraf Kassim 的神经网络路径规划论文合作者。", category: "adjacent", primary: false, stage: "adjacent", x: 520, y: 900, sources: [profiles.kassim], facts: [fact("合作关系", "SUTD 官方出版清单完整记录两人共同论文。", profiles.kassim)] },
  { id: "jinho-choi-p0-r3-support", name: "Jinho Choi", role: "Research collaborator", institution: "External", area: "Wireless Communications", tags: ["Wireless Communications"], summary: "Jihong Park 的量子网络项目共同负责人。", category: "adjacent", primary: false, stage: "adjacent", x: 660, y: 900, sources: [parkProject], facts: [fact("合作关系", "Deakin 官方项目页记录两人共同领导研究。", parkProject)] },
  { id: "marcel-boehme-p0-r3-support", name: "Marcel Böhme", role: "Research collaborator", institution: "External", region: "Europe", area: "Software Engineering", tags: ["Software Engineering", "Testing"], summary: "Ezekiel Soremekun 的软件测试论文合作者。", category: "adjacent", primary: false, stage: "adjacent", x: 800, y: 900, sources: [profiles.soremekun], facts: [fact("合作关系", "SUTD 官方论文列表记录两人共同论文。", profiles.soremekun)] },
  { id: "qingyun-gao-p0-r3-support", name: "Qingyun Gao", role: "Visiting PhD student · group member", institution: "SUTD", region: "Singapore", area: "Recommender Systems", tags: ["Recommender Systems"], summary: "Zhu Sun 研究组主页列出的访问博士生。", category: "adjacent", primary: false, stage: "adjacent", x: 940, y: 900, sources: [sunGroup], facts: [fact("研究组关系", "研究组主页将其列为访问博士生。", sunGroup)] },
  { id: "peh-li-shiuan-p0-r3-support", name: "Li-Shiuan Peh", role: "Research collaborator", institution: "NUS", region: "Singapore", area: "Computer Architecture", tags: ["Computer Architecture", "Edge AI"], summary: "Angela Bo Wang 官方简介点名的 NUS 合作教授。", category: "adjacent", primary: false, stage: "adjacent", x: 1080, y: 900, sources: [profiles.wang], facts: [fact("合作关系", "SUTD 官方简介明确记录双方合作边缘 AI 系统。", profiles.wang)] },
  { id: "nils-tipppenhauer-p0-r3-support", name: "Nils Ole Tippenhauer", role: "Research collaborator", institution: "External", region: "Europe", area: "Cyber-Physical Security", tags: ["Cybersecurity", "Cyber-Physical Systems"], summary: "David Yau 的 iTrust 项目合作者。", category: "adjacent", primary: false, stage: "adjacent", x: 1220, y: 900, sources: [yauProject], facts: [fact("合作关系", "SUTD iTrust 项目清单记录两人共同参与项目。", yauProject)] },
  { id: "gauthama-raman-p0-r3-support", name: "Gauthama Raman M R", role: "Research collaborator", institution: "SUTD", region: "Singapore", area: "Cybersecurity · AI", tags: ["Cybersecurity", "AI"], summary: "Jianying Zhou 的 AICrit 项目合作者。", category: "adjacent", primary: false, stage: "adjacent", x: 1360, y: 900, sources: [zhouProject], facts: [fact("合作关系", "SUTD iTrust 项目页记录两人共同负责 AICrit。", zhouProject)] },
];

export const candidatePriorityP0HkSgThirdRoundRelationships2026: Relationship[] = [
  { id: "p0-hksg-r3-jiang-cao", from: "jing-jiang", to: "rui-cao-sutd-p0-r3", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "SMU 博士论文提案页明确记录 Cao Rui 由 Jing Jiang 指导。", evidenceObject: "Using Pre-trained Models for Multimodal Understanding · dissertation proposal", source: caoThesis, verified: true },
  { id: "p0-hksg-r3-chee-vu", from: "yeow-meng-chee-sutd-p0-r3", to: "van-khu-vu-p0-r3-support", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "SUTD 机构仓储记录完整共同署名。", evidenceObject: "An Efficient Parameterized Algorithm for Computing Quantum Channel Fidelity via Symmetries Exploitation", source: cheePaper, verified: true, recentYear: 2025 },
  { id: "p0-hksg-r3-chen-mashima", from: "binbin-chen-sutd-p0-r3", to: "daisuke-mashima-sutd-p0-r3", type: "collaboration", subtype: "sustained_collaboration", label: "持续论文合作", evidence: "SUTD 官方出版清单记录两人在工业控制系统安全方向多篇共同论文。", evidenceObject: "Message Authentication and Provenance Verification for Industrial Control Systems · TCPS 2023", source: profiles.chen, verified: true, recentYear: 2023 },
  { id: "p0-hksg-r3-lee-choo", from: "youngki-lee-p0-r3-support", to: "kenny-choo-sutd-p0-r3", type: "lineage", subtype: "co_adviser", label: "博士共同导师", evidence: "SUTD 官方简介明确记录 Youngki Lee 为 Kenny Choo 的博士导师之一。", evidenceObject: "SMU PhD supervision", source: profiles.choo, verified: true },
  { id: "p0-hksg-r3-herremans-chew", from: "dorien-herremans-sutd-p0-r3", to: "elaine-chew-p0-r3-support", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "SUTD 官方论文列表记录两人共同署名。", evidenceObject: "MorpheuS: generating structured music with constrained patterns and tension", source: profiles.herremans, verified: true },
  { id: "p0-hksg-r3-kassim-kumar", from: "ashraf-kassim-sutd-p0-r3", to: "bvkv-kumar-p0-r3-support", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "SUTD 官方出版清单记录两人合作神经网络路径规划研究。", evidenceObject: "Path Planning for Autonomous Robots Using Neural Networks", source: profiles.kassim, verified: true },
  { id: "p0-hksg-r3-li-sun", from: "xiaoli-li-sutd-p0-r3", to: "aixin-sun", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "SUTD 官方论文清单记录 Xiaoli Li 与 Aixin Sun 共同署名 ACL 2023 论文。", evidenceObject: "MS-DETR: Natural Language Video Localization with Sampling Moment-Moment Interaction · ACL 2023", source: profiles.li, verified: true, recentYear: 2023 },
  { id: "p0-hksg-r3-meghjani-hsu", from: "malika-meghjani-sutd-p0-r3", to: "david-hsu-nus", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "SUTD 官方论文列表记录两人共同署名机器人交互规划研究。", evidenceObject: "Interactive Planning for Autonomous Urban Driving in Adversarial Scenarios · ICRA 2021", source: profiles.meghjani, verified: true, recentYear: 2021 },
  { id: "p0-hksg-r3-park-choi", from: "jihong-park-sutd-p0-r3", to: "jinho-choi-p0-r3-support", type: "collaboration", subtype: "joint_project", label: "共同项目", evidence: "Deakin 官方项目页记录双方共同领导量子网络研究。", evidenceObject: "Deakin–Cisco quantum networking research project", source: parkProject, verified: true },
  { id: "p0-hksg-r3-quek-chong", from: "tony-quek-sutd-p0-r3", to: "ernest-chong-sutd-p0-r2", type: "collaboration", subtype: "joint_project", label: "共同项目", evidence: "SUTD 项目页列 Tony Quek 为 PI、Ernest Chong 为共同 PI。", evidenceObject: "ASTRALIS", source: astralis, verified: true },
  { id: "p0-hksg-r3-soremekun-boehme", from: "ezekiel-soremekun-sutd-p0-r3", to: "marcel-boehme-p0-r3-support", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "SUTD 官方论文列表记录两人共同署名软件故障定位研究。", evidenceObject: "Where is the bug and how is it fixed? · FSE 2017", source: profiles.soremekun, verified: true },
  { id: "p0-hksg-r3-sun-gao", from: "zhu-sun-sutd-p0-r3", to: "qingyun-gao-p0-r3-support", type: "talent", subtype: "other", label: "研究组成员", evidence: "Zhu Sun 研究组主页将 Qingyun Gao 列为访问博士生。", evidenceObject: "Zhu Sun research group current members", source: sunGroup, verified: true },
  { id: "p0-hksg-r3-wang-peh", from: "angela-bo-wang-sutd-p0-r3", to: "peh-li-shiuan-p0-r3-support", type: "collaboration", subtype: "sustained_collaboration", label: "研究合作", evidence: "SUTD 官方简介明确写明双方合作设计低功耗边缘 AI 系统。", evidenceObject: "Energy-efficient on-chip AI and ultra-low-power edge AI collaboration", source: profiles.wang, verified: true },
  { id: "p0-hksg-r3-yau-tippenhauer", from: "david-yau-sutd-p0-r3", to: "nils-tipppenhauer-p0-r3-support", type: "collaboration", subtype: "joint_project", label: "共同项目", evidence: "SUTD iTrust 项目清单记录双方共同参与公共基础设施安全研究。", evidenceObject: "Advancing Security of Public Infrastructure using Resilience and Economics", source: yauProject, verified: true },
  { id: "p0-hksg-r3-zhou-raman", from: "jianying-zhou-sutd-p0-r3", to: "gauthama-raman-p0-r3-support", type: "collaboration", subtype: "joint_project", label: "共同项目", evidence: "SUTD iTrust 项目页记录双方共同负责 AICrit。", evidenceObject: "AICrit", source: zhouProject, verified: true },
];

export const candidatePriorityP0HkSgThirdRoundRosterPromotions2026 = [
  ["CAO Rui", "rui-cao-sutd-p0-r3"], ["CHEE Yeow Meng", "yeow-meng-chee-sutd-p0-r3"], ["CHEN Binbin", "binbin-chen-sutd-p0-r3"],
  ["CHOO Kenny", "kenny-choo-sutd-p0-r3"], ["HERREMANS Dorien", "dorien-herremans-sutd-p0-r3"], ["KASSIM Ashraf A.", "ashraf-kassim-sutd-p0-r3"],
  ["LI Xiaoli", "xiaoli-li-sutd-p0-r3"], ["MASHIMA Daisuke", "daisuke-mashima-sutd-p0-r3"], ["MEGHJANI Malika", "malika-meghjani-sutd-p0-r3"],
  ["PARK Jihong", "jihong-park-sutd-p0-r3"], ["QUEK Tony", "tony-quek-sutd-p0-r3"], ["SOREMEKUN Ezekiel", "ezekiel-soremekun-sutd-p0-r3"],
  ["SUN Zhu", "zhu-sun-sutd-p0-r3"], ["WANG Bo Angela", "angela-bo-wang-sutd-p0-r3"], ["YAU David", "david-yau-sutd-p0-r3"], ["ZHOU Jianying", "jianying-zhou-sutd-p0-r3"],
].map(([rosterName, atlasPersonId]) => ({ unitUrl: roster.url, rosterName, atlasPersonId }));

export const People = candidatePriorityP0HkSgThirdRoundPeople2026;
export const SupportingPeople = candidatePriorityP0HkSgThirdRoundSupportingPeople2026;
export const Relationships = candidatePriorityP0HkSgThirdRoundRelationships2026;
export const RosterPromotions = candidatePriorityP0HkSgThirdRoundRosterPromotions2026;
