import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const fact = (label: string, value: string, item: Source) => ({ label, value, source: item });

const s = {
  williams: source("MIT CSAIL · Brian Williams", "https://www.csail.mit.edu/person/brian-williams", "official", "Current MIT professorship, CSAIL PI status and model-based autonomy research"),
  williamsBio: source("Brian Williams · MIT personal profile", "https://people.csail.mit.edu/williams/Web%20site/williams.shtml", "profile", "MIT degrees, Xerox PARC and NASA Ames trajectory, and MERS leadership"),
  williamsGroup: source("MIT MERS Group", "https://mers.csail.mit.edu/", "official", "Current research programme, students and laboratory activity"),
  guttag: source("MIT CSAIL · John Guttag", "https://www.csail.mit.edu/person/john-guttag", "official", "Current MIT appointment, CAML leadership, machine learning research and Health at Scale role"),
  guttagBio: source("John Guttag · MIT personal profile", "https://people.csail.mit.edu/guttag/", "profile", "Brown and Toronto degrees, USC-to-MIT faculty trajectory and EECS leadership"),
  guttagTeam: source("MIT CSAIL · Katherine Matton", "https://www.csail.mit.edu/person/katherine-matton", "official", "CAML group membership under John Guttag"),
  solomon: source("MIT CSAIL · Justin Solomon", "https://www.csail.mit.edu/person/justin-solomon", "official", "Current MIT appointment and geometric data processing research"),
  solomonBio: source("MIT Professional Education · Justin Solomon", "https://professional.mit.edu/programs/faculty-profiles/justin-solomon", "official", "Stanford degrees, Princeton postdoctoral training and Pixar experience"),
  solomonCv: source("Justin Solomon · MIT-hosted CV", "https://people.csail.mit.edu/jsolomon/assets/cv.pdf", "cv", "Leonidas Guibas PhD adviser and Amit Singer postdoctoral mentor"),
  solomonTeam: source("MIT Geometric Data Processing Group", "https://groups.csail.mit.edu/gdpgroup/team.html", "official", "Current students and researchers"),
  mina: source("MIT CSAIL · Mina Konakovic Lukovic", "https://www.csail.mit.edu/person/mina-konakovic-lukovic", "official", "Current MIT appointment and computational design research"),
  minaBio: source("MIT School of Engineering · Mina Konakovic Lukovic", "https://engineering.mit.edu/people/mina-konakovic-lukovic", "official", "Belgrade and EPFL education and MIT postdoctoral mentorship"),
  minaHome: source("Mina Konakovic Lukovic · MIT personal profile", "https://people.csail.mit.edu/mina/", "profile", "Mark Pauly PhD adviser and current advisees"),
  szolovits: source("MIT CSAIL · Peter Szolovits", "https://www.csail.mit.edu/person/peter-szolovits", "official", "Current MIT professorship, Clinical Decision-Making Group and medical AI/NLP research"),
  szolovitsBio: source("Peter Szolovits · MIT-hosted IEEE biography", "https://groups.csail.mit.edu/medg/ftp/psz/IEEE%20transactions%20on%20bio-medical%20engineering%201986%20Potvin-3.pdf", "publication", "Caltech physics bachelor's and information science doctorate"),
  szolovitsStudents: source("Peter Szolovits · MIT student list", "https://people.csail.mit.edu/psz/web/students.html", "profile", "Named doctoral, master's and undergraduate advisees"),
  golland: source("MIT CSAIL · Polina Golland", "https://www.csail.mit.edu/person/polina-golland", "official", "Current MIT professorship and medical vision and machine learning research"),
  gollandBio: source("MIT IMES · Polina Golland", "https://imes.mit.edu/people/golland-polina", "official", "Technion and MIT education and current appointments"),
  gollandCv: source("Polina Golland · MIT-hosted CV", "https://people.csail.mit.edu/polina/old/cv/golland.pdf", "cv", "W. Eric L. Grimson PhD adviser"),
  adelson: source("MIT CSAIL · Ted Adelson", "https://www.csail.mit.edu/person/ted-adelson", "official", "Current MIT professorship and vision science research"),
  adelsonCv: source("Ted Adelson · MIT Perceptual Science Group CV", "https://persci.mit.edu/people/adelson/curriculum_vitae/", "cv", "Yale and Michigan education and complete doctoral-student list"),
  adelsonStudent: source("MIT News · Phillip Isola", "https://news.mit.edu/2025/understanding-nuances-human-intelligence-phillip-isola-1111", "official", "Ted Adelson identified as Phillip Isola's PhD adviser"),
  lozano: source("MIT CSAIL · Tomas Lozano-Perez", "https://www.csail.mit.edu/person/tomas-lozano-perez", "official", "Current MIT professorship, MIT degrees and robotics research"),
  lozanoTeam: source("MIT Learning and Intelligent Systems · People", "https://lis.csail.mit.edu/people/", "official", "Laboratory leadership and current students"),
  matusik: source("MIT CSAIL · Wojciech Matusik", "https://www.csail.mit.edu/person/wojciech-matusik", "official", "Current MIT professorship and AI, vision, graphics and fabrication research"),
  matusikBio: source("MIT Computational Fabrication Group · Wojciech Matusik", "https://cfg.mit.edu/wojciech", "official", "Berkeley and MIT education, MERL/Adobe/Disney experience and group leadership"),
  matusikThesis: source("Wojciech Matusik · MIT doctoral thesis", "https://groups.csail.mit.edu/graphics/pubs/thesis_phd_matusik.pdf", "publication", "Leonard McMillan named as PhD thesis supervisor"),
  matusikTeam: source("MIT Computational Design & Fabrication Group · People", "https://cdfg.mit.edu/people/", "official", "Current students, postdocs and alumni"),
} satisfies Record<string, Source>;

type Seed = Pick<Person, "id" | "name" | "role" | "institution" | "area" | "tags" | "summary" | "facts" | "sources" | "stage"> & { portraitFile: string; portraitSource: Source; x: number };
const person = (p: Seed): Person => ({ ...p, region: "United States", category: "core", status: "current independent PI · official faculty profile verified", primary: true, x: p.x, y: 120, introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-us-canada-mit-tail-2026/${p.portraitFile}`, alt: `${p.name} 官方头像`, source: p.portraitSource } });
const portrait = (name: string, file: string) => source(`MIT CSAIL portrait · ${name}`, `https://www.csail.mit.edu/${file}`, "official", "Official faculty portrait");

export const candidatePriorityP0UsCanadaReadyBatch6People2026: Person[] = [
  person({ id: "brian-williams-mit-p0-b6", name: "Brian Williams", role: "Professor · Director, MERS", institution: "MIT", stage: "senior", x: 120, area: "Model-based Autonomy · Planning · Diagnosis", tags: ["自主系统", "规划", "诊断", "机器人"], summary: "以模型推理、规划与诊断支撑自主系统的 MIT MERS 负责人，研究连接深空任务与智能机器人。", facts: [fact("当前任职", "MIT Professor of Aeronautics and Astronautics、CSAIL PI，并领导 MERS Group。", s.williams), fact("教育与学术训练", "MIT S.B.（1981）、S.M.（1984）与 Ph.D.（1989）。", s.williamsBio), fact("研究主线", "模型化自主、规划、执行、故障诊断与人机协作。", s.williams), fact("科研经历", "曾在 Xerox PARC 与 NASA Ames 工作，并领导 Deep Space One 的 Remote Agent 工作。", s.williamsBio), fact("公开团队", "MERS 官方页面持续列出实验室项目和研究成员。", s.williamsGroup)], sources: [s.williams, s.williamsBio, s.williamsGroup], portraitFile: "brian-williams.jpg", portraitSource: portrait("Brian Williams", "sites/default/files/styles/headshot/public/images/people/card/BrianWilliams.jpg") }),
  person({ id: "john-guttag-mit-p0-b6", name: "John Guttag", role: "Dugald C. Jackson Professor · Lead, CAML", institution: "MIT", stage: "senior", x: 300, area: "Machine Learning · Healthcare AI · Computer Vision", tags: ["机器学习", "医疗 AI", "计算机视觉", "临床决策"], summary: "领导 MIT CAML、把机器学习用于临床与生理数据的资深 PI，并曾长期领导 MIT EECS。", facts: [fact("当前任职", "MIT Dugald C. Jackson Professor，并领导 CSAIL Clinical and Applied Machine Learning Group。", s.guttag), fact("教育与学术训练", "Brown University 英语学士与应用数学硕士；University of Toronto 计算机科学博士（1975）。", s.guttagBio), fact("研究主线", "临床与应用机器学习、计算机视觉和生理信号分析。", s.guttag), fact("学术领导力", "1999–2004 年任 MIT EECS 系主任，此前任计算机方向副系主任。", s.guttagBio), fact("产业连接", "MIT 官方资料记录其为 Health at Scale 联合创始人及 Chief Scientist。", s.guttag)], sources: [s.guttag, s.guttagBio, s.guttagTeam], portraitFile: "john-guttag.jpg", portraitSource: portrait("John Guttag", "sites/default/files/styles/headshot/public/images/people/card/guttag.jpg") }),
  person({ id: "justin-solomon-mit-p0-b6", name: "Justin Solomon", role: "Associate Professor · Associate Dean", institution: "MIT", stage: "emerging", x: 480, area: "Geometric Deep Learning · Computer Vision · Graphics", tags: ["几何深度学习", "计算机视觉", "图形学", "科学机器学习"], summary: "研究几何数据处理和几何深度学习的 MIT PI；博士师承与博士后训练均由公开 CV 直接验证。", facts: [fact("当前任职", "MIT EECS 副教授、CSAIL PI，并任工程教育副院长。", s.solomon), fact("教育与学术训练", "Stanford 数学与计算机科学学士、计算机科学硕士与博士；随后在 Princeton 从事博士后研究。", s.solomonBio), fact("博士师承", "MIT-hosted CV 明确列 Leonidas Guibas 为博士导师。", s.solomonCv), fact("研究主线", "几何数据处理、几何深度学习、计算机视觉与图形学。", s.solomon), fact("产业经历", "2007–2012 年间曾在 Pixar Research 实习或工作。", s.solomonBio)], sources: [s.solomon, s.solomonBio, s.solomonCv, s.solomonTeam], portraitFile: "justin-solomon.jpg", portraitSource: portrait("Justin Solomon", "sites/default/files/styles/headshot/public/images/people/card/J%20Solomon%20Headshot.jpg") }),
  person({ id: "mina-konakovic-lukovic-mit-p0-b6", name: "Mina Konakovic Lukovic", role: "Assistant Professor · PI, Design Intelligence Lab", institution: "MIT", stage: "emerging", x: 660, area: "Computational Design · Graphics · AI for Fabrication", tags: ["计算设计", "图形学", "数字制造", "AI"], summary: "把几何计算、AI 和数字制造结合起来的 MIT 新生代 PI，训练链条连接 EPFL Mark Pauly 与 MIT Wojciech Matusik。", facts: [fact("当前任职", "MIT EECS 助理教授、CSAIL PI。", s.mina), fact("教育与学术训练", "University of Belgrade 学士与硕士；EPFL 计算机科学博士；随后在 MIT 从事博士后研究。", s.minaBio), fact("博士师承", "本人 MIT 页面明确列 Mark Pauly 为 EPFL 博士导师。", s.minaHome), fact("博士后训练", "MIT 工学院官方简介明确其博士后导师为 Wojciech Matusik。", s.minaBio), fact("研究主线", "计算设计、几何算法、图形学与数字制造。", s.mina)], sources: [s.mina, s.minaBio, s.minaHome], portraitFile: "mina-konakovic-lukovic.jpg", portraitSource: portrait("Mina Konakovic Lukovic", "sites/default/files/styles/headshot/public/images/people/card/Mina%20K%20L%20copy.jpg") }),
  person({ id: "peter-szolovits-mit-p0-b6", name: "Peter Szolovits", role: "Professor · Head, Clinical Decision-Making Group", institution: "MIT", stage: "senior", x: 840, area: "Medical AI · Clinical NLP · Decision Support", tags: ["医疗 AI", "临床 NLP", "决策支持", "健康数据"], summary: "MIT 医疗 AI 与临床自然语言处理的奠基型现任 PI，公开学生页记录长期博士与硕士指导体系。", facts: [fact("当前任职", "MIT Professor of Computer Science and Engineering，并领导 Clinical Decision-Making Group。", s.szolovits), fact("教育与学术训练", "Caltech 物理学学士（1970）与信息科学博士（1974）。", s.szolovitsBio), fact("研究主线", "医疗人工智能、临床自然语言处理、健康信息学与决策支持。", s.szolovits), fact("学生体系", "MIT 本人学生页逐名列出博士、硕士和本科指导记录。", s.szolovitsStudents)], sources: [s.szolovits, s.szolovitsBio, s.szolovitsStudents], portraitFile: "peter-szolovits.jpg", portraitSource: portrait("Peter Szolovits", "sites/default/files/styles/headshot/public/images/people/card/szolovits.jpg") }),
  person({ id: "polina-golland-mit-p0-b6", name: "Polina Golland", role: "Sunlin Chou Professor · CSAIL PI", institution: "MIT", stage: "senior", x: 1020, area: "Medical Image Computing · Computer Vision · Machine Learning", tags: ["医学影像", "计算机视觉", "机器学习", "健康 AI"], summary: "以机器学习和视觉方法理解医学影像的 MIT 资深 PI，博士师承可由 MIT-hosted CV 直接验证。", facts: [fact("当前任职", "MIT Sunlin Chou Professor of Electrical Engineering and Computer Science，并任 CSAIL PI。", s.golland), fact("教育与学术训练", "Technion 计算机科学学士与硕士；MIT EECS 博士（2001）。", s.gollandBio), fact("博士师承", "MIT-hosted CV 明确列 W. Eric L. Grimson 为博士导师。", s.gollandCv), fact("研究主线", "医学影像计算、计算机视觉和机器学习。", s.golland), fact("跨学科任职", "MIT IMES 官方页面列其为 Institute for Medical Engineering and Science 核心教师。", s.gollandBio)], sources: [s.golland, s.gollandBio, s.gollandCv], portraitFile: "polina-golland.jpg", portraitSource: portrait("Polina Golland", "sites/default/files/styles/headshot/public/images/people/card/polina.jpg") }),
  person({ id: "ted-adelson-mit-p0-b6", name: "Ted Adelson", role: "John and Dorothy Wilson Professor", institution: "MIT", stage: "senior", x: 1200, area: "Human and Machine Vision · Perception · Robotics", tags: ["计算机视觉", "感知", "机器人", "视觉科学"], summary: "连接人类视觉、机器感知与触觉机器人的 MIT 资深学者，公开 CV 提供完整博士生谱系。", facts: [fact("当前任职", "MIT John and Dorothy Wilson Professor，并任 CSAIL 与 Brain and Cognitive Sciences 成员。", s.adelson), fact("教育与学术训练", "Yale 物理学与哲学学士（1974）；University of Michigan 实验心理学博士（1979）。", s.adelsonCv), fact("研究主线", "人类视觉、计算机视觉、感知与触觉机器人。", s.adelson), fact("学生体系", "MIT CV 逐名列出 William Freeman、Ce Liu、Phillip Isola、Wenzhen Yuan 等博士生。", s.adelsonCv), fact("可核验师承", "MIT News 明确说明 Phillip Isola 的博士导师为 Ted Adelson。", s.adelsonStudent)], sources: [s.adelson, s.adelsonCv, s.adelsonStudent], portraitFile: "ted-adelson.jpg", portraitSource: portrait("Ted Adelson", "sites/default/files/styles/headshot/public/images/people/card/Ted%20Adelson.jpg") }),
  person({ id: "tomas-lozano-perez-mit-p0-b6", name: "Tomas Lozano-Perez", role: "School of Engineering Professor in Teaching Excellence", institution: "MIT", stage: "senior", x: 1380, area: "Robotics · Motion Planning · AI", tags: ["机器人", "运动规划", "人工智能", "操作"], summary: "机器人运动规划和智能操作的 MIT 奠基型现任 PI，也是 Learning and Intelligent Systems Group 联合负责人。", facts: [fact("当前任职", "MIT School of Engineering Professor in Teaching Excellence、CSAIL PI。", s.lozano), fact("教育与学术训练", "MIT S.B.（1973）、S.M.（1976）与 Ph.D.（1980）。", s.lozano), fact("研究主线", "机器人运动规划、操作、人工智能和计算机视觉。", s.lozano), fact("公开团队", "MIT LIS 官方人员页列其为实验室领导，并列出当前博士生与研究人员。", s.lozanoTeam)], sources: [s.lozano, s.lozanoTeam], portraitFile: "tomas-lozano-perez.jpg", portraitSource: portrait("Tomas Lozano-Perez", "sites/default/files/styles/headshot/public/images/people/card/tlp.jpg") }),
  person({ id: "wojciech-matusik-mit-p0-b6", name: "Wojciech Matusik", role: "Professor · Director, Computational Fabrication Group", institution: "MIT", stage: "senior", x: 1560, area: "Computer Graphics · Computer Vision · AI for Design", tags: ["图形学", "计算机视觉", "计算设计", "数字制造"], summary: "把 AI、视觉、图形学与数字制造连接起来的 MIT PI，其博士导师和研究型产业经历均有一手资料。", facts: [fact("当前任职", "MIT EECS 教授、CSAIL PI，并领导 Computational Fabrication Group。", s.matusik), fact("教育与学术训练", "UC Berkeley 电气工程与计算机科学学士；MIT EECS 硕士与博士（2003）。", s.matusikBio), fact("博士师承", "MIT 博士论文明确列 Leonard McMillan 为 thesis supervisor。", s.matusikThesis), fact("研究主线", "计算机图形学、计算机视觉、AI、机器人与数字制造。", s.matusik), fact("产业经历", "加入 MIT 前曾在 Mitsubishi Electric Research Labs，亦曾在 Adobe 与 Disney Research 任访问学者。", s.matusikBio)], sources: [s.matusik, s.matusikBio, s.matusikThesis, s.matusikTeam], portraitFile: "wojciech-matusik.jpg", portraitSource: portrait("Wojciech Matusik", "sites/default/files/styles/headshot/public/images/people/card/wojciech.jpg") }),
];

export const candidatePriorityP0UsCanadaReadyBatch6Relationships2026: Relationship[] = [
  { id: "candidate-p0-usca-b6-guibas-solomon", from: "leonidas-guibas-lineage", to: "justin-solomon-mit-p0-b6", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Justin Solomon 的 MIT-hosted CV 明确列 Leonidas Guibas 为 Stanford 博士导师。", source: s.solomonCv, verified: true },
  { id: "candidate-p0-usca-b6-grimson-golland", from: "eric-grimson-lineage", to: "polina-golland-mit-p0-b6", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Polina Golland 的 MIT-hosted CV 明确列 W. Eric L. Grimson 为 MIT 博士导师。", source: s.gollandCv, verified: true },
  { id: "candidate-p0-usca-b6-adelson-isola", from: "ted-adelson-mit-p0-b6", to: "phillip-isola-us", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "MIT News 明确说明 Phillip Isola 的博士导师是 Ted Adelson。", source: s.adelsonStudent, verified: true },
  { id: "candidate-p0-usca-b6-matusik-mina", from: "wojciech-matusik-mit-p0-b6", to: "mina-konakovic-lukovic-mit-p0-b6", type: "lineage", subtype: "postdoc_mentor", label: "博士后导师", evidence: "MIT School of Engineering 官方简介明确 Mina Konakovic Lukovic 的 MIT 博士后导师为 Wojciech Matusik。", source: s.minaBio, verified: true },
];

export const candidatePriorityP0UsCanadaReadyBatch6GroupMembers2026: GroupMember[] = [
  { id: "candidate-p0-usca-b6-williams-mers", teacherId: "brian-williams-mit-p0-b6", name: "MERS Group members", role: "Graduate students and researchers", source: s.williamsGroup },
  { id: "candidate-p0-usca-b6-guttag-matton", teacherId: "john-guttag-mit-p0-b6", name: "Katherine Matton", role: "CAML graduate researcher", source: s.guttagTeam },
  { id: "candidate-p0-usca-b6-solomon-gdp", teacherId: "justin-solomon-mit-p0-b6", name: "Geometric Data Processing Group members", role: "Graduate students and researchers", source: s.solomonTeam },
  { id: "candidate-p0-usca-b6-mina-team", teacherId: "mina-konakovic-lukovic-mit-p0-b6", name: "Design Intelligence Lab advisees", role: "Graduate researchers", source: s.minaHome },
  { id: "candidate-p0-usca-b6-szolovits-students", teacherId: "peter-szolovits-mit-p0-b6", name: "Clinical Decision-Making Group advisees", role: "Doctoral and master's students", source: s.szolovitsStudents },
  { id: "candidate-p0-usca-b6-lozano-lis", teacherId: "tomas-lozano-perez-mit-p0-b6", name: "Learning and Intelligent Systems members", role: "Graduate students and researchers", source: s.lozanoTeam },
  { id: "candidate-p0-usca-b6-matusik-cdfg", teacherId: "wojciech-matusik-mit-p0-b6", name: "Computational Design & Fabrication Group members", role: "Graduate students and postdocs", source: s.matusikTeam },
];

export const candidatePriorityP0UsCanadaReadyBatch6Placements2026: StudentPlacement[] = [];
export const candidatePriorityP0UsCanadaReadyBatch6RosterPromotions2026 = candidatePriorityP0UsCanadaReadyBatch6People2026.map((p) => ({ unitUrl: "https://www.csail.mit.edu/people?roleFacets=Principal%20Investigators%2CCore%2FDual%2CAssociates%2CEmeritus", rosterName: p.name === "Mina Konakovic Lukovic" ? "Mina  Konakovic Lukovic" : p.name, atlasPersonId: p.id }));
export const people = candidatePriorityP0UsCanadaReadyBatch6People2026;
export const relationships = candidatePriorityP0UsCanadaReadyBatch6Relationships2026;
export const placements = candidatePriorityP0UsCanadaReadyBatch6Placements2026;
export const groupMembers = candidatePriorityP0UsCanadaReadyBatch6GroupMembers2026;
export const rosterPromotions = candidatePriorityP0UsCanadaReadyBatch6RosterPromotions2026;
