import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";
const checkedAt = "2026-09-03";
const src = (label:string,url:string,kind:Source["kind"],supports:string):Source => ({label,url,kind,supports,checkedAt});
const fact=(label:string,value:string,source:Source)=>({label,value,source});
const s={
  katabi:src("MIT CSAIL · Dina Katabi","https://www.csail.mit.edu/person/dina-katabi","official","Current MIT professorship and AI, wireless sensing and health research"),
  katabiBio:src("MIT StartMIT · Dina Katabi","https://startmit-2016.mit.edu/dina-katabi/","official","Damascus and MIT education, Wireless@MIT leadership and startup activity"),
  katabiLab:src("Katabi Lab at MIT","https://groups.csail.mit.edu/netmit/lab/","official","Machine learning and health-AI programme and public team"),
  shenlong:src("Illinois Siebel School · Shenlong Wang","https://siebelschool.illinois.edu/about/people/all-faculty/shenlong","official","Current assistant professorship and computer-vision research"),
  shenlongHome:src("Shenlong Wang · Illinois personal profile","https://shenlong.web.illinois.edu/","profile","Toronto doctorate, Raquel Urtasun supervision, Uber experience and current team"),
  shenlongGroup:src("Shenlong Wang · group alumni","https://shenlong.web.illinois.edu/group.html","profile","Named doctoral students, mentees and industry destinations"),
  lingming:src("Illinois Siebel School · Lingming Zhang","https://siebelschool.illinois.edu/about/people/all-faculty/lingming","official","Current associate professorship and code-LLM research"),
  lingmingHome:src("Lingming Zhang · Illinois personal profile","https://lingming.cs.illinois.edu/","profile","Research programme and academic biography"),
  lingmingStudents:src("Lingming Zhang · students","https://lingming.cs.illinois.edu/student.html","profile","Current and former students with academic and industry destinations"),
};
type Seed=Omit<Person,"category"|"status"|"primary"|"introducedAt"|"lastVerifiedAt"|"portrait">;
const base=(p:Seed,file:string,portraitUrl:string):Person=>({...p,category:"core",status:"current independent PI · official faculty profile verified",primary:true,introducedAt:checkedAt,lastVerifiedAt:checkedAt,portrait:{src:`portraits/candidate-p0-us-canada-ready-batch-10-2026/${file}.jpg`,alt:`${p.name} 官方头像`,source:src(`${p.institution} official portrait · ${p.name}`,portraitUrl,"official","Official university portrait")}});
export const candidatePriorityP0UsCanadaReadyBatch10People2026:Person[]=[
 base({id:"dina-katabi-mit-p0-b10",name:"Dina Katabi",role:"Andrew and Erna Viterbi Professor",institution:"MIT",region:"United States",area:"Machine Learning · Wireless Sensing · Health AI",tags:["机器学习","无线感知","健康AI","自监督学习"],summary:"把无线感知、机器学习和居家健康监测连接起来的 MIT 资深 PI。",stage:"senior",x:120,y:120,sources:[s.katabi,s.katabiBio,s.katabiLab],facts:[fact("当前任职","MIT Andrew and Erna Viterbi Professor，并领导 Wireless@MIT。",s.katabiBio),fact("教育与学术训练","Damascus University 学士（1995）；MIT S.M.（1999）与 Ph.D.（2003）。",s.katabiBio),fact("研究主线","无线感知、机器学习、生理信号与健康 AI。",s.katabiLab),fact("产业连接","MIT 官方简介记录其实验室孵化 PiCharging 与 Emerald。",s.katabiBio),fact("公开团队","Katabi Lab 官方页面公开研究成员与健康 AI 项目。",s.katabiLab)]},"dina-katabi","https://www.csail.mit.edu/sites/default/files/styles/headshot/public/images/migration/katabi.jpg"),
 base({id:"shenlong-wang-uiuc-p0-b10",name:"Shenlong Wang",role:"Assistant Professor",institution:"UIUC",region:"United States",area:"Computer Vision · Robotics · Autonomous Driving",tags:["计算机视觉","机器人","自动驾驶","3D视觉"],summary:"研究 3D 感知、机器人和自主驾驶的 UIUC PI，学术与产业训练连接 Toronto 和 Uber。",stage:"emerging",x:300,y:120,sources:[s.shenlong,s.shenlongHome,s.shenlongGroup],facts:[fact("当前任职","UIUC Siebel School 助理教授。",s.shenlong),fact("教育与学术训练","University of Toronto Computer Science PhD，由 Raquel Urtasun 指导。",s.shenlongHome),fact("研究主线","3D 计算机视觉、机器人、自主驾驶与具身感知。",s.shenlongHome),fact("产业经历","加入 UIUC 前在 Uber 任 Research Scientist。",s.shenlongHome),fact("学生去向","公开团队页记录学生与 mentee 流向 Apple、Meta、Amazon Robotics、Tesla、Waabi 与高校。",s.shenlongGroup)]},"shenlong-wang","https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=111255&s=400&type=portrait"),
 base({id:"lingming-zhang-uiuc-p0-b10",name:"Lingming Zhang",role:"Associate Professor",institution:"UIUC",region:"United States",area:"Code LLMs · AI for Software Engineering · Program Analysis",tags:["代码大模型","软件工程","智能体","程序分析"],summary:"研究代码大模型、软件工程智能体与程序分析的 UIUC PI，公开学生页提供清晰人才去向。",stage:"senior",x:480,y:120,sources:[s.lingming,s.lingmingHome,s.lingmingStudents],facts:[fact("当前任职","UIUC Siebel School 副教授。",s.lingming),fact("教育与学术训练","本人学术主页公开其计算机科学博士训练和历届学术任职。",s.lingmingHome),fact("研究主线","Code LLMs and Agents、AI for Systems and Security、软件工程与程序分析。",s.lingming),fact("学生体系","学生页逐名列出当前博士生、博士后及历届学生。",s.lingmingStudents),fact("产业去向","博士与硕士校友去向包括 OpenAI、Google、Uber、Databricks、Shopify、Amazon 与 Meta。",s.lingmingStudents)]},"lingming-zhang","https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=106752&s=400&type=portrait"),
];
export const candidatePriorityP0UsCanadaReadyBatch10Relationships2026:Relationship[]=[];
export const candidatePriorityP0UsCanadaReadyBatch10GroupMembers2026:GroupMember[]=[{id:"p0-usca-b10-katabi-team",teacherId:"dina-katabi-mit-p0-b10",name:"Katabi Lab members",role:"Graduate researchers",source:s.katabiLab},{id:"p0-usca-b10-shenlong-team",teacherId:"shenlong-wang-uiuc-p0-b10",name:"Wang group members",role:"PhD and master's students",source:s.shenlongGroup},{id:"p0-usca-b10-lingming-team",teacherId:"lingming-zhang-uiuc-p0-b10",name:"Zhang group students",role:"PhD, master's and visiting students",source:s.lingmingStudents}];
export const candidatePriorityP0UsCanadaReadyBatch10Placements2026:StudentPlacement[]=[{id:"p0-usca-b10-lingming-jiawei",student:"Jiawei Liu",teacherId:"lingming-zhang-uiuc-p0-b10",company:"OpenAI",role:"Researcher",kind:"reported",degree:"PhD",sector:"industry",note:"本人学生页记录 Jiawei Liu 于 2025 年博士毕业后进入 OpenAI。",source:s.lingmingStudents,verifiedAt:checkedAt}];
export const candidatePriorityP0UsCanadaReadyBatch10RosterPromotions2026=candidatePriorityP0UsCanadaReadyBatch10People2026.map(person=>({unitUrl:person.institution==="MIT"?"https://www.csail.mit.edu/people?roleFacets=Principal%20Investigators%2CCore%2FDual%2CAssociates%2CEmeritus":"https://siebelschool.illinois.edu/about/people/all-faculty",rosterName:person.name,atlasPersonId:person.id}));
export const people=candidatePriorityP0UsCanadaReadyBatch10People2026;
export const relationships=candidatePriorityP0UsCanadaReadyBatch10Relationships2026;
export const placements=candidatePriorityP0UsCanadaReadyBatch10Placements2026;
export const groupMembers=candidatePriorityP0UsCanadaReadyBatch10GroupMembers2026;
export const rosterPromotions=candidatePriorityP0UsCanadaReadyBatch10RosterPromotions2026;
