import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const s = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const f = (label: string, value: string, source: Source) => ({ label, value, source });

const q = {
  bretl: s("Illinois Center for Autonomy · Timothy Bretl", "https://autonomy.illinois.edu/people/timoty-bretl", "official", "Current appointment, education, adviser and postdoctoral training"),
  bretlCv: s("Timothy Bretl · curriculum vitae", "https://bretl.csl.illinois.edu/s/timothy-bretl-cv.pdf", "cv", "Research, academic training, PhD students and industry role"),
  bretlHome: s("Timothy Bretl · Illinois homepage", "https://bretl.csl.illinois.edu/", "profile", "Current faculty role and robotics research"),
  varun: s("Illinois ECE · Varun Chandrasekaran", "https://ece.illinois.edu/about/directory/faculty/varunc", "official", "Current appointment and AI security research"),
  varunHome: s("Chandrasekaran Research Group", "https://chandrasekaran-group.github.io/", "profile", "Current appointment, research program and group"),
  varunCv: s("Varun Chandrasekaran · curriculum vitae", "https://pages.cs.wisc.edu/~chandrasekaran/CV.pdf", "cv", "Education and Microsoft Research experience"),
  varunTraining: s("Varun Chandrasekaran · Wisconsin homepage", "https://pages.cs.wisc.edu/~chandrasekaran/", "profile", "Doctoral research background and research interests"),
  varunAdvisor: s("Suman Banerjee · curriculum vitae", "https://pages.cs.wisc.edu/~suman/cv-dec2025-banerjee-ext.pdf", "cv", "Varun Chandrasekaran listed among completed PhD students"),
  yunzong: s("Illinois Grainger Engineering · Yunzong Xu", "https://grainger.illinois.edu/about/directory/faculty/xyz", "official", "Current appointment, education and Microsoft Research postdoc"),
  yunzongHome: s("Yunzong Xu · Illinois homepage", "https://yunzongxu.github.io/", "profile", "Research program, current students and alumni outcomes"),
  ron: s("Stanford Computer Science · Ron Fedkiw", "https://www.cs.stanford.edu/people/ron-fedkiw", "official", "Current Stanford professorship"),
  ronBrown: s("Stanford Brown Institute · Ron Fedkiw", "https://brown.stanford.edu/portfolio/ron-fedkiw/", "official", "Education, research, industry consulting and doctoral-student record"),
  ronGroup: s("Ron Fedkiw · PhysBAM group", "https://physbam.stanford.edu/", "profile", "Current and former PhD students"),
  thomas: s("Stanford Philosophy · Thomas Icard", "https://philosophy.stanford.edu/people/thomas-icard", "official", "Current professorship and research areas"),
  thomasHome: s("Thomas Icard · Stanford homepage", "https://stanford.edu/~icard/", "profile", "SAIL affiliation, interpretability work and advisees"),
  thomasTraining: s("University of Amsterdam · Master of Logic alumni reflection", "https://staff.science.uva.nl/u.endriss/admin/MScLogicCriticalReflection2013.pdf", "official", "Amsterdam master's and Stanford doctoral training"),
  thomasProfile: s("Stanford Profiles · Thomas Icard", "https://profiles.stanford.edu/thomas-icard?tab=bio", "official", "Current teaching, advising and publications"),
  gerald: s("MIT CSAIL · Gerald Sussman", "https://www.csail.mit.edu/person/gerald-sussman", "official", "Current PI status, education, AI research and former students"),
  geraldEecs: s("MIT EECS · Gerald Sussman", "https://www.eecs.mit.edu/people/gerald-sussman/", "official", "Current faculty role and AI+ML research area"),
  geraldHome: s("Gerald Jay Sussman · MIT homepage", "https://groups.csail.mit.edu/mac/users/gjs/gjs.html", "profile", "Completed PhD students and current teaching"),
  hart: s("Illinois Grainger Engineering · John C. Hart", "https://grainger.illinois.edu/about/directory/faculty/jch", "official", "Current appointment, education, research and industry collaborations"),
  hartGroup: s("Graphics at Illinois · John C. Hart", "https://graphics.cs.illinois.edu/jch/", "profile", "Graphics research group affiliation"),
  elkebir: s("Illinois Siebel School · Mohammed El-Kebir", "https://siebelschool.illinois.edu/about/people/department-faculty/melkebir", "official", "Current appointment, education, advisers and research"),
  elkebirHome: s("Mohammed El-Kebir · homepage", "https://www.el-kebir.net/", "profile", "Current role, lab research and group news"),
  elkebirCv: s("Mohammed El-Kebir · curriculum vitae", "https://www.el-kebir.net/public/CV.pdf", "cv", "Advisers, current students and alumni destinations"),
  olgica: s("Illinois ECE · Olgica Milenkovic", "https://ece.illinois.edu/about/directory/faculty/milenkov", "official", "Current appointment, education and research"),
  olgicaMembers: s("Olgica Milenkovic group · members", "https://publish.illinois.edu/milenkovic/members/", "profile", "Current students and alumni destinations"),
  olgicaMichigan: s("Michigan ECE · alumni in academia", "https://ece.engin.umich.edu/alumni/alumni-in-academia/", "official", "Doctoral adviser Kevin Compton"),
  rainer: s("Illinois CSL · Rainer Engelken", "https://csl.illinois.edu/directory/faculty/engelken", "official", "Current appointment, education and AI research"),
  rainerHome: s("Rainer Engelken · homepage", "https://rainerengelken.github.io/", "profile", "Research program, recruitment and lab"),
  rainerCv: s("Rainer Engelken · curriculum vitae", "https://rainerengelken.github.io/assets/pdf/Rainer_Engelken_CV_2025c_website.pdf", "cv", "Doctoral and postdoctoral advisers"),
  srikant: s("Illinois CSL · Rayadurgam Srikant", "https://csl.illinois.edu/directory/faculty/rsrikant", "official", "Current appointment, education and research"),
  srikantNews: s("Illinois CSL · Srikant named Nearing Professor", "https://csl.illinois.edu/news-and-media/srikant-named-nearing-professor-electrical-and-computer-engineering", "official", "Doctoral adviser Tamer Başar and career"),
  srikantNcsa: s("Illinois NCSA · Srikant named director", "https://www.ncsa.illinois.edu/2026/02/10/srikant-named-ncsas-new-director/", "official", "Leadership, student network and industry destinations"),
  srikantAlumni: s("Illinois ECE · graduate alumni professors", "https://ece.illinois.edu/academics/grad/alumni-professors", "official", "Verified academic destinations of former students"),
  shuang: s("Illinois Grainger Engineering · Shuang Zhao", "https://grainger.illinois.edu/about/directory/faculty/shzhao", "official", "Current appointment, education and research"),
  shuangHome: s("Shuang Zhao · homepage", "https://shuangz.com/", "profile", "Research, background and publications"),
  shuangPersonal: s("Shuang Zhao · personal background", "https://www.shuangz.com/personal/", "profile", "Doctoral adviser Kavita Bala"),
  shuangLab: s("UCI Graphics · people", "https://graphics.ics.uci.edu/", "official", "Historical graphics lab and graduate researchers"),
};

type Seed = Omit<Person, "portrait" | "category" | "status" | "primary" | "introducedAt" | "lastVerifiedAt">;
const p = (x: Seed, file: string, portraitUrl: string): Person => ({
  ...x,
  category: "core",
  status: "current independent PI · official faculty profile verified",
  primary: true,
  introducedAt: checkedAt,
  lastVerifiedAt: checkedAt,
  portrait: {
    src: `portraits/candidate-p0-us-canada-ready-batch-15-2026/${file}.jpg`,
    alt: `${x.name} 官方头像`,
    source: s(`${x.institution} portrait · ${x.name}`, portraitUrl, "official", "Official university portrait"),
  },
});

export const candidatePriorityP0UsCanadaReadyBatch15People2026: Person[] = [
  p({
    id: "timothy-bretl-uiuc-p0-b15",
    name: "Timothy Bretl",
    role: "Professor · Associate Head",
    institution: "UIUC",
    region: "United States",
    area: "Robotics · Motion Planning · Control",
    tags: ["机器人", "运动规划", "控制", "脑机接口"],
    summary: "研究机器人运动规划、最优控制与康复机器人，并长期连接航空、CS 和神经科学的 UIUC PI。",
    stage: "senior",
    x: 120,
    y: 120,
    sources: [q.bretl, q.bretlCv, q.bretlHome],
    facts: [
      f("当前任职", "UIUC Aerospace Engineering 教授、Severns Faculty Scholar 与 Associate Head，并兼任 CS、ECE、CSL 等单位。", q.bretl),
      f("教育与学术训练", "Swarthmore Engineering/Mathematics 双学士；Stanford Aeronautics and Astronautics MS 与 PhD（2005），博士导师 Stephen M. Rock；随后在 Stanford CS 跟随 Jean-Claude Latombe 从事博士后研究。", q.bretl),
      f("研究主线", "机器人与自动化的理论和算法基础，包括运动规划、控制、优化、康复机器人与脑机接口。", q.bretlCv),
      f("产业经历", "2015–2016 年任 Reconstruct Inc. Chief Innovation Officer and Secretary。", q.bretlCv),
      f("学生体系", "CV 逐名列出 Aadeel Akhtar、Dennis Matthews、Navid Aghasadeghi、Miles Johnson 等已毕业博士生。", q.bretlCv),
    ],
  }, "timothy-bretl", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=5005&s=400&type=portrait"),
  p({
    id: "varun-chandrasekaran-uiuc-p0-b15",
    name: "Varun Chandrasekaran",
    role: "Assistant Professor",
    institution: "UIUC",
    region: "United States",
    area: "Trustworthy Machine Learning · Security · Privacy",
    tags: ["可信机器学习", "安全", "隐私", "机器遗忘"],
    summary: "研究机器学习模型的信息泄露、机器遗忘及安全隐私边界的 UIUC 新锐 PI。",
    stage: "emerging",
    x: 300,
    y: 120,
    sources: [q.varun, q.varunHome, q.varunCv, q.varunTraining],
    facts: [
      f("当前任职", "UIUC Electrical and Computer Engineering 助理教授，并在 Siebel School of Computing and Data Science 兼任。", q.varunHome),
      f("教育与学术训练", "Anna University Computer Science and Engineering BE；NYU Computer Science MS；University of Wisconsin–Madison Computer Science PhD（2022）；Suman Banerjee 的本人 CV 将其列为已毕业博士生。", q.varunAdvisor),
      f("研究主线", "安全隐私与系统、网络、分布式计算和机器学习的交叉，重点研究模型交互暴露的私有信息。", q.varunHome),
      f("产业经历", "博士毕业后在 Microsoft Research Adaptive Systems & Interaction Group 从事博士后研究。", q.varunCv),
      f("团队建设", "Chandrasekaran Research Group 官网公开其可信机器学习与安全方向研究团队。", q.varunHome),
    ],
  }, "varun-chandrasekaran", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=131540&s=400&type=portrait"),
  p({
    id: "yunzong-xu-uiuc-p0-b15",
    name: "Yunzong Xu",
    role: "Assistant Professor",
    institution: "UIUC",
    region: "United States",
    area: "Machine Learning Theory · Sequential Decision Making · Reinforcement Learning",
    tags: ["机器学习理论", "序贯决策", "强化学习", "在线学习"],
    summary: "研究数据与资源受限条件下学习、在线决策和强化学习理论的 UIUC PI。",
    stage: "emerging",
    x: 480,
    y: 120,
    sources: [q.yunzong, q.yunzongHome],
    facts: [
      f("当前任职", "UIUC Industrial and Enterprise Systems Engineering 助理教授，并兼任 CS 与 ECE。", q.yunzongHome),
      f("教育与学术训练", "Tsinghua University 经济管理与数学双学士；MIT Institute for Data, Systems, and Society PhD（2023）；随后任 Microsoft Research 博士后研究员。", q.yunzong),
      f("研究主线", "机器学习与不确定性决策的数学基础，包括在线学习、bandits、强化学习、信息论和博弈论。", q.yunzongHome),
      f("学生体系", "本人主页公开列出 Hao Liang、Boxuan Zhou、Anthony Pineci、Cheng Tang、Shunri Zheng 等博士生。", q.yunzongHome),
      f("学生流向", "本科研究成员 Qiushi Han 进入 MIT 博士项目，Zhangyi Liu 进入 Stanford 博士项目。", q.yunzongHome),
    ],
  }, "yunzong-xu", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=150904&s=400&type=portrait"),
  p({
    id: "ron-fedkiw-stanford-p0-b15",
    name: "Ron Fedkiw",
    role: "Canon Professor in the School of Engineering",
    institution: "Stanford",
    region: "United States",
    area: "Computer Graphics · Physical Simulation · Machine Learning",
    tags: ["计算机图形学", "物理仿真", "机器学习", "计算机视觉"],
    summary: "把计算物理、视觉特效与机器学习连接起来，并培养大规模博士生体系的 Stanford 资深教授。",
    stage: "senior",
    x: 660,
    y: 120,
    sources: [q.ron, q.ronBrown, q.ronGroup],
    facts: [
      f("当前任职", "Stanford School of Engineering Canon Professor、Computer Science 教授，并加入 Stanford AI Lab。", q.ronBrown),
      f("教育与学术训练", "UCLA Mathematics PhD；随后在 Caltech Aeronautics 从事博士后研究。", q.ronBrown),
      f("研究主线", "计算流体力学、物理仿真、计算机图形学、视觉与机器学习交叉。", q.ronBrown),
      f("产业连接", "曾长期为 Industrial Light + Magic 顾问，现为 Epic Games 顾问。", q.ronBrown),
      f("学生体系", "Stanford 官方简介称其已培养 40 名博士；PhysBAM 页面逐名列出当前与历届博士生。", q.ronGroup),
    ],
  }, "ron-fedkiw", "https://www.cs.stanford.edu/sites/g/files/sbiybj28076/files/styles/square_1900/public/media/person/ron-fedkiw1509536111047.jpg?h=e83d06f3&itok=Z3MaA89K"),
  p({
    id: "thomas-icard-stanford-p0-b15",
    name: "Thomas Icard",
    role: "C. I. Lewis Professor of Philosophy · Professor of Computer Science by courtesy",
    institution: "Stanford",
    region: "United States",
    area: "Mechanistic Interpretability · Logic · Causal Reasoning",
    tags: ["机制可解释性", "逻辑", "因果推理", "认知科学"],
    summary: "从逻辑、因果抽象和认知科学研究大模型机制可解释性的 Stanford 跨学科 PI。",
    stage: "senior",
    x: 840,
    y: 120,
    sources: [q.thomas, q.thomasHome, q.thomasTraining, q.thomasProfile],
    facts: [
      f("当前任职", "Stanford C. I. Lewis Professor of Philosophy、Computer Science courtesy professor，并为 SAIL 与 Center for Automated Reasoning affiliate faculty。", q.thomasHome),
      f("教育与学术训练", "Middlebury College 哲学本科背景；University of Amsterdam Logic MS（2008）；随后在 Stanford Philosophy 完成 PhD。", q.thomasTraining),
      f("研究主线", "逻辑、形式哲学、因果抽象、认知科学与机制可解释性。", q.thomasHome),
      f("产业经历", "2026–27 学年在 Goodfire 全职开展 interpretability science。", q.thomasHome),
      f("学生体系", "本人主页与 Stanford Profiles 公开列出多名博士、硕士学生与博士后资助关系。", q.thomasProfile),
    ],
  }, "thomas-icard", "https://ai.stanford.edu/wp-content/uploads/2020/09/thomas-icard.png"),
  p({
    id: "gerald-sussman-mit-p0-b15",
    name: "Gerald Jay Sussman",
    role: "Panasonic Professor of Electrical Engineering",
    institution: "MIT",
    region: "United States",
    area: "Artificial Intelligence · Programming Languages · Scientific Computing",
    tags: ["人工智能", "程序设计语言", "科学计算", "经典AI"],
    summary: "从早期 AI、Scheme 到科学计算和工程教育均有奠基贡献，并培养庞大学术后代的 MIT 资深 PI。",
    stage: "senior",
    x: 1020,
    y: 120,
    sources: [q.gerald, q.geraldEecs, q.geraldHome],
    facts: [
      f("当前任职", "MIT Panasonic Professor of Electrical Engineering、CSAIL Core/Dual PI。", q.gerald),
      f("教育与学术训练", "MIT Mathematics SB（1968）与 PhD（1973）。", q.gerald),
      f("研究主线", "人工智能问题求解、程序设计语言、计算机体系结构、VLSI 和科学计算。", q.gerald),
      f("代表性贡献", "与博士生 Guy L. Steele Jr. 共同发明 Scheme，并与学生发展 AI 驱动的 VLSI 设计工具。", q.gerald),
      f("学生体系", "本人 MIT 主页逐年列出完成博士论文的学生，包括 Drew McDermott、Scott Fahlman、Guy Steele、Jon Doyle 与 Danny Hillis 等。", q.geraldHome),
    ],
  }, "gerald-sussman", "https://www.csail.mit.edu/sites/default/files/styles/headshot/public/images/people/card/Gerald%20Sussman.jpg"),
  p({
    id: "john-hart-uiuc-p0-b15",
    name: "John C. Hart",
    role: "Professor · Executive Associate Dean",
    institution: "UIUC",
    region: "United States",
    area: "Computer Graphics · Data Visualization · Virtual Reality",
    tags: ["计算机图形学", "数据可视化", "虚拟现实", "交互计算"],
    summary: "研究计算机图形、数据可视化和虚拟现实，并推动专业计算教育的 UIUC 资深教授。",
    stage: "senior",
    x: 1200,
    y: 120,
    sources: [q.hart, q.hartGroup],
    facts: [
      f("当前任职", "UIUC Computer Science 教授、Online and Professional Programs 主任及 Graduate College Executive Associate Dean。", q.hart),
      f("教育与学术训练", "University of Illinois Chicago Electronic Visualization Laboratory PhD（1991）。", q.hart),
      f("研究主线", "计算机图形学、数据可视化与虚拟现实。", q.hart),
      f("产业连接", "官方简介记录其研究获 Adobe、IBM、Intel、Microsoft、NVIDIA 等支持，并曾任 Adobe visiting researcher。", q.hart),
      f("团队建设", "Graphics at Illinois 个人页将其研究纳入学校图形学团队。", q.hartGroup),
    ],
  }, "john-hart", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?photo=9962&s=300"),
  p({
    id: "mohammed-el-kebir-uiuc-p0-b15",
    name: "Mohammed El-Kebir",
    role: "Associate Professor",
    institution: "UIUC",
    region: "United States",
    area: "Computational Genomics · Graph Algorithms · Combinatorial Optimization",
    tags: ["计算基因组学", "图算法", "组合优化", "肿瘤系统发育"],
    summary: "用图算法与组合优化重建肿瘤演化和疾病传播过程的 UIUC 计算生物学 PI。",
    stage: "emerging",
    x: 1380,
    y: 120,
    sources: [q.elkebir, q.elkebirHome, q.elkebirCv],
    facts: [
      f("当前任职", "UIUC Siebel School 副教授，并兼任 ECE、NCSA 与 IGB。", q.elkebir),
      f("教育与学术训练", "Eindhoven University of Technology CSE BS/MS、VU Amsterdam Bioinformatics MS；VU Amsterdam 与 CWI Computer Science PhD（2015），导师 Gunnar Klau 与 Jaap Heringa；随后跟随 Ben Raphael 在 Brown/Princeton 从事博士后研究。", q.elkebir),
      f("研究主线", "组合优化、图算法、肿瘤系统发育、癌症与感染基因组学。", q.elkebirHome),
      f("团队建设", "本人 CV 公开当前博士生、访问学生和本科研究成员。", q.elkebirCv),
      f("学生去向", "本人 CV 记录校友进入 Regeneron、D. E. Shaw Research、Google、Meta、Pony.ai 等机构。", q.elkebirCv),
    ],
  }, "mohammed-el-kebir", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?photo=18630&s=300"),
  p({
    id: "olgica-milenkovic-uiuc-p0-b15",
    name: "Olgica Milenkovic",
    role: "Franklin W. Woeltge Professor",
    institution: "UIUC",
    region: "United States",
    area: "Information Theory · Machine Learning · Bioinformatics",
    tags: ["信息论", "机器学习", "生物信息学", "DNA存储"],
    summary: "连接信息论、机器学习、DNA 存储与计算生物学的 UIUC 资深 PI。",
    stage: "senior",
    x: 1560,
    y: 120,
    sources: [q.olgica, q.olgicaMembers, q.olgicaMichigan],
    facts: [
      f("当前任职", "UIUC Franklin W. Woeltge Professor of Electrical and Computer Engineering，并共同创办 CAIM。", q.olgica),
      f("教育与学术训练", "University of Michigan Mathematics MS 与 Electrical and Computer Engineering PhD（2002），博士导师 Kevin Compton。", q.olgicaMichigan),
      f("研究主线", "编码与信息论、DNA 存储、生物信息学、压缩感知、排序聚合和机器学习。", q.olgica),
      f("团队建设", "本人团队页公开当前博士生和博士后成员。", q.olgicaMembers),
      f("学生流向", "团队页记录校友进入 Purdue、UC Irvine、McGill、Imperial、Virginia 等高校及 Jackson Laboratory、Dorna Robotics。", q.olgicaMembers),
    ],
  }, "olgica-milenkovic", "https://publish.illinois.edu/milenkovic/files/2014/03/milenkovic-e1395794806346.jpg"),
  p({
    id: "rainer-engelken-uiuc-p0-b15",
    name: "Rainer Engelken",
    role: "Assistant Professor",
    institution: "UIUC",
    region: "United States",
    area: "NeuroAI · Recurrent Neural Networks · Computational Neuroscience",
    tags: ["神经AI", "循环神经网络", "计算神经科学", "动力系统"],
    summary: "以动力系统研究生物与人工循环神经网络学习、稳定性和高效计算的 UIUC PI。",
    stage: "emerging",
    x: 1740,
    y: 120,
    sources: [q.rainer, q.rainerHome, q.rainerCv],
    facts: [
      f("当前任职", "自 2025 年起任 UIUC ECE 助理教授，并兼任 Siebel CS 与 CSL。", q.rainerCv),
      f("教育与学术训练", "Tübingen Physics diploma、Cambridge Part III；University of Göttingen Physics PhD（2017），研究在 MPI Dynamics and Self-Organization 完成并由 Fred Wolf 指导；随后在 Columbia 跟随 L. F. Abbott 做博士后。", q.rainerCv),
      f("研究主线", "神经数据分析、动力系统、机器学习、理论与计算神经科学。", q.rainer),
      f("代表性方向", "研究循环神经网络混沌、时间信用分配和事件驱动稀疏神经网络算法。", q.rainer),
      f("团队建设", "本人主页公开计算神经科学实验室研究与博士生招募。", q.rainerHome),
    ],
  }, "rainer-engelken", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?photo=20934&s=300"),
  p({
    id: "rayadurgam-srikant-uiuc-p0-b15",
    name: "Rayadurgam Srikant",
    role: "Grainger Distinguished Chair · NCSA Director",
    institution: "UIUC",
    region: "United States",
    area: "Machine Learning · Stochastic Systems · Communication Networks",
    tags: ["机器学习", "随机系统", "通信网络", "博弈论"],
    summary: "连接机器学习、随机控制、网络系统和产业研发，并培养大规模学生体系的 UIUC 资深教授。",
    stage: "senior",
    x: 1920,
    y: 120,
    sources: [q.srikant, q.srikantNews, q.srikantNcsa, q.srikantAlumni],
    facts: [
      f("当前任职", "UIUC Grainger Distinguished Chair、NCSA Director，并共同领导 C3.ai Digital Transformation Institute。", q.srikantNcsa),
      f("教育与学术训练", "IIT Madras BTech；UIUC Electrical Engineering MS 与 PhD（1991），博士导师 Tamer Başar。", q.srikantNews),
      f("研究主线", "机器学习、应用概率、随机控制、通信网络、云计算和博弈论。", q.srikant),
      f("学生体系", "NCSA 官方称其超过 25 名学生与博士后进入高校，其余在 NVIDIA、Amazon、Google、Meta 等担任研发或管理岗位。", q.srikantNcsa),
      f("学术后代", "Illinois 官方校友页记录 Sanjay Shakkottai、Srinivas Shakkottai、Lei Ying、Siva Theja Maguluri、Javad Ghaderi 等成为高校教授。", q.srikantAlumni),
    ],
  }, "rayadurgam-srikant", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?photo=1093&s=300"),
  p({
    id: "shuang-zhao-uiuc-p0-b15",
    name: "Shuang Zhao",
    role: "Associate Professor",
    institution: "UIUC",
    region: "United States",
    area: "Computer Graphics · Differentiable Rendering · Computer Vision",
    tags: ["计算机图形学", "可微渲染", "计算机视觉", "逆渲染"],
    summary: "研究物理光传输、可微与逆渲染，并连接图形学、视觉和科学计算的 UIUC PI。",
    stage: "emerging",
    x: 2100,
    y: 120,
    sources: [q.shuang, q.shuangHome, q.shuangPersonal, q.shuangLab],
    facts: [
      f("当前任职", "自 2025 年起任 UIUC Siebel School 副教授，此前在 UC Irvine 任助理及副教授。", q.shuang),
      f("教育与学术训练", "Cornell Computer Science PhD（2014），博士导师 Kavita Bala；随后在 MIT 从事博士后研究。", q.shuangPersonal),
      f("研究主线", "物理光传输、可微渲染、逆渲染、Monte Carlo PDE 与科学计算。", q.shuangHome),
      f("研究荣誉", "获 NSF CAREER，并凭 warped-area reparameterization 工作获得 SIGGRAPH Asia 2023 Best Papers Award。", q.shuang),
      f("团队体系", "UCI Graphics 官方实验室页记录其历史研究团队与研究生成员。", q.shuangLab),
    ],
  }, "shuang-zhao", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?photo=20816&s=300"),
];

export const candidatePriorityP0UsCanadaReadyBatch15SupportingPeople2026: Person[] = [
  { id: "stephen-rock-lineage-p0-b15", name: "Stephen M. Rock", role: "Professor · doctoral adviser", institution: "Stanford", region: "United States", area: "Robotics · Control", tags: ["机器人", "控制", "博士导师"], summary: "Timothy Bretl 在 Stanford 博士阶段的导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 120, y: 20, sources: [q.bretl], lastVerifiedAt: checkedAt },
  { id: "suman-banerjee-lineage-p0-b15", name: "Suman Banerjee", role: "Professor · doctoral adviser", institution: "Wisconsin", region: "United States", area: "Networks · Systems", tags: ["网络", "系统", "博士导师"], summary: "Varun Chandrasekaran 在 Wisconsin 博士阶段的导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 300, y: 20, sources: [q.varunAdvisor], lastVerifiedAt: checkedAt },
  { id: "gunnar-klau-lineage-p0-b15", name: "Gunnar Klau", role: "Professor · doctoral adviser", institution: "External", actualInstitution: "Heinrich Heine University Düsseldorf", region: "Europe", area: "Bioinformatics · Algorithms", tags: ["生物信息学", "算法", "博士导师"], summary: "Mohammed El-Kebir 博士阶段的共同导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 1380, y: 20, sources: [q.elkebir], lastVerifiedAt: checkedAt },
  { id: "kevin-compton-lineage-p0-b15", name: "Kevin Compton", role: "Professor · doctoral adviser", institution: "External", actualInstitution: "University of Michigan", region: "United States", area: "Theory · Logic", tags: ["理论", "博士导师"], summary: "Olgica Milenkovic 在 Michigan 博士阶段的导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 1560, y: 20, sources: [q.olgicaMichigan], lastVerifiedAt: checkedAt },
  { id: "fred-wolf-lineage-p0-b15", name: "Fred Wolf", role: "Professor · doctoral adviser", institution: "External", actualInstitution: "Max Planck Institute for Dynamics and Self-Organization", region: "Europe", area: "Theoretical Neuroscience", tags: ["理论神经科学", "博士导师"], summary: "Rainer Engelken 博士阶段的导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 1740, y: 20, sources: [q.rainerCv], lastVerifiedAt: checkedAt },
  { id: "tamer-basar-lineage-p0-b15", name: "Tamer Başar", role: "Professor · doctoral adviser", institution: "UIUC", region: "United States", area: "Control · Game Theory", tags: ["控制", "博弈论", "博士导师"], summary: "Rayadurgam Srikant 在 UIUC 博士阶段的导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 1920, y: 20, sources: [q.srikantNews], lastVerifiedAt: checkedAt },
  { id: "kavita-bala-lineage-p0-b15", name: "Kavita Bala", role: "Professor · doctoral adviser", institution: "Cornell", region: "United States", area: "Computer Graphics · Vision", tags: ["计算机图形学", "视觉", "博士导师"], summary: "Shuang Zhao 在 Cornell 博士阶段的导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 2100, y: 20, sources: [q.shuangPersonal], lastVerifiedAt: checkedAt },
];

export const candidatePriorityP0UsCanadaReadyBatch15Relationships2026: Relationship[] = [
  { id: "p0-usca-b15-rock-bretl", from: "stephen-rock-lineage-p0-b15", to: "timothy-bretl-uiuc-p0-b15", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Illinois Center for Autonomy 官方履历明确 Timothy Bretl 的 Stanford 博士导师为 Stephen M. Rock。", source: q.bretl, verified: true, endYear: 2005 },
  { id: "p0-usca-b15-banerjee-varun", from: "suman-banerjee-lineage-p0-b15", to: "varun-chandrasekaran-uiuc-p0-b15", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Suman Banerjee 的本人 CV 将 Varun Chandrasekaran 列入已毕业博士生，并记录其 2022 年完成 Wisconsin CS PhD。", source: q.varunAdvisor, verified: true, endYear: 2022 },
  { id: "p0-usca-b15-klau-elkebir", from: "gunnar-klau-lineage-p0-b15", to: "mohammed-el-kebir-uiuc-p0-b15", type: "lineage", subtype: "co_adviser", label: "共同博士导师", evidence: "UIUC 官方简介明确 Mohammed El-Kebir 的博士研究由 Gunnar Klau 与 Jaap Heringa 指导。", source: q.elkebir, verified: true, endYear: 2015 },
  { id: "p0-usca-b15-compton-olgica", from: "kevin-compton-lineage-p0-b15", to: "olgica-milenkovic-uiuc-p0-b15", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Michigan ECE 官方 alumni-in-academia 页面列出 Olgica Milenkovic 的博士导师为 Kevin Compton。", source: q.olgicaMichigan, verified: true, endYear: 2002 },
  { id: "p0-usca-b15-wolf-engelken", from: "fred-wolf-lineage-p0-b15", to: "rainer-engelken-uiuc-p0-b15", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Rainer Engelken 本人 CV 明确博士研究在 MPI-DS 完成并由 Fred Wolf 指导。", source: q.rainerCv, verified: true, endYear: 2017 },
  { id: "p0-usca-b15-basar-srikant", from: "tamer-basar-lineage-p0-b15", to: "rayadurgam-srikant-uiuc-p0-b15", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Illinois CSL 官方新闻明确 Tamer Başar 是 Rayadurgam Srikant 的博士导师。", source: q.srikantNews, verified: true, endYear: 1991 },
  { id: "p0-usca-b15-bala-zhao", from: "kavita-bala-lineage-p0-b15", to: "shuang-zhao-uiuc-p0-b15", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Shuang Zhao 本人背景页明确 Cornell 博士导师为 Kavita Bala。", source: q.shuangPersonal, verified: true, endYear: 2014 },
];

export const candidatePriorityP0UsCanadaReadyBatch15GroupMembers2026: GroupMember[] = [
  { id: "p0-usca-b15-bretl-students", teacherId: "timothy-bretl-uiuc-p0-b15", name: "Bretl robotics students", role: "PhD students and alumni", source: q.bretlCv },
  { id: "p0-usca-b15-varun-group", teacherId: "varun-chandrasekaran-uiuc-p0-b15", name: "Chandrasekaran Research Group", role: "Trustworthy ML and security researchers", source: q.varunHome },
  { id: "p0-usca-b15-yunzong-students", teacherId: "yunzong-xu-uiuc-p0-b15", name: "Xu research students", role: "Doctoral and undergraduate researchers", source: q.yunzongHome },
  { id: "p0-usca-b15-ron-physbam", teacherId: "ron-fedkiw-stanford-p0-b15", name: "PhysBAM group", role: "Current and former PhD students", source: q.ronGroup },
  { id: "p0-usca-b15-thomas-students", teacherId: "thomas-icard-stanford-p0-b15", name: "Icard advisees", role: "PhD, master's and postdoctoral researchers", source: q.thomasProfile },
  { id: "p0-usca-b15-gerald-students", teacherId: "gerald-sussman-mit-p0-b15", name: "Sussman doctoral lineage", role: "Completed PhD students", source: q.geraldHome },
  { id: "p0-usca-b15-hart-group", teacherId: "john-hart-uiuc-p0-b15", name: "Graphics at Illinois", role: "Computer graphics and visualization researchers", source: q.hartGroup },
  { id: "p0-usca-b15-elkebir-group", teacherId: "mohammed-el-kebir-uiuc-p0-b15", name: "El-Kebir group", role: "Computational genomics students and researchers", source: q.elkebirCv },
  { id: "p0-usca-b15-olgica-group", teacherId: "olgica-milenkovic-uiuc-p0-b15", name: "Milenkovic research group", role: "Graduate students, postdocs and alumni", source: q.olgicaMembers },
  { id: "p0-usca-b15-rainer-group", teacherId: "rainer-engelken-uiuc-p0-b15", name: "Engelken computational neuroscience lab", role: "NeuroAI and dynamical-systems researchers", source: q.rainerHome },
  { id: "p0-usca-b15-srikant-network", teacherId: "rayadurgam-srikant-uiuc-p0-b15", name: "Srikant academic network", role: "Former students and postdoctoral researchers", source: q.srikantNcsa },
  { id: "p0-usca-b15-shuang-group", teacherId: "shuang-zhao-uiuc-p0-b15", name: "UCI Graphics historical team", role: "Graduate students and graphics researchers", source: q.shuangLab },
];

export const candidatePriorityP0UsCanadaReadyBatch15Placements2026: StudentPlacement[] = [
  { id: "p0-usca-b15-yunzong-han", student: "Qiushi Han", teacherId: "yunzong-xu-uiuc-p0-b15", company: "MIT", role: "PhD student", kind: "reported", sector: "academia", note: "Yunzong Xu 本人主页记录本科研究成员 Qiushi Han 进入 MIT 博士项目。", source: q.yunzongHome, verifiedAt: checkedAt },
  { id: "p0-usca-b15-yunzong-liu", student: "Zhangyi Liu", teacherId: "yunzong-xu-uiuc-p0-b15", company: "Stanford", role: "PhD student", kind: "reported", sector: "academia", note: "Yunzong Xu 本人主页记录本科研究成员 Zhangyi Liu 进入 Stanford 博士项目。", source: q.yunzongHome, verifiedAt: checkedAt },
  { id: "p0-usca-b15-elkebir-nuraini", student: "Nuraini Aguse", teacherId: "mohammed-el-kebir-uiuc-p0-b15", company: "Google", role: "Software Engineer", kind: "reported", sector: "industry", note: "Mohammed El-Kebir 本人 CV 记录校友 Nuraini Aguse 去向 Google。", source: q.elkebirCv, verifiedAt: checkedAt },
  { id: "p0-usca-b15-elkebir-jiaqi", student: "Jiaqi Wu", teacherId: "mohammed-el-kebir-uiuc-p0-b15", company: "Meta", role: "Software Engineer", kind: "reported", sector: "industry", note: "Mohammed El-Kebir 本人 CV 记录校友 Jiaqi Wu 去向 Facebook/Meta。", source: q.elkebirCv, verifiedAt: checkedAt },
  { id: "p0-usca-b15-elkebir-chuanyi", student: "Chuanyi Zhang", teacherId: "mohammed-el-kebir-uiuc-p0-b15", company: "Regeneron", role: "Associate Scientist", kind: "reported", sector: "industry", note: "Mohammed El-Kebir 本人 CV 记录校友 Chuanyi Zhang 去向 Regeneron。", source: q.elkebirCv, verifiedAt: checkedAt },
  { id: "p0-usca-b15-elkebir-shunping", student: "Shunping Xie", teacherId: "mohammed-el-kebir-uiuc-p0-b15", company: "Pony.ai", role: "Software Engineer", kind: "reported", sector: "industry", note: "Mohammed El-Kebir 本人 CV 记录校友 Shunping Xie 去向 Pony.ai。", source: q.elkebirCv, verifiedAt: checkedAt },
];

const batch15PromotionOverrides: Record<string, { unitUrl: string; rosterName?: string }> = {
  "ron-fedkiw-stanford-p0-b15": { unitUrl: "https://www.cs.stanford.edu/people/faculty" },
  "thomas-icard-stanford-p0-b15": { unitUrl: "https://ai.stanford.edu/faculty/" },
  "gerald-sussman-mit-p0-b15": {
    unitUrl: "https://www.csail.mit.edu/people?roleFacets=Principal%20Investigators%2CCore%2FDual%2CAssociates%2CEmeritus",
    rosterName: "Gerald Sussman",
  },
};

export const candidatePriorityP0UsCanadaReadyBatch15RosterPromotions2026 = candidatePriorityP0UsCanadaReadyBatch15People2026.map((person) => ({
  unitUrl: batch15PromotionOverrides[person.id]?.unitUrl ?? "https://siebelschool.illinois.edu/about/people/all-faculty",
  rosterName: batch15PromotionOverrides[person.id]?.rosterName ?? person.name,
  atlasPersonId: person.id,
}));

export const people = [...candidatePriorityP0UsCanadaReadyBatch15People2026, ...candidatePriorityP0UsCanadaReadyBatch15SupportingPeople2026];
export const relationships = candidatePriorityP0UsCanadaReadyBatch15Relationships2026;
export const placements = candidatePriorityP0UsCanadaReadyBatch15Placements2026;
export const groupMembers = candidatePriorityP0UsCanadaReadyBatch15GroupMembers2026;
export const rosterPromotions = candidatePriorityP0UsCanadaReadyBatch15RosterPromotions2026;
