import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const sources = {
  cambridgeRoster: source("Cambridge CST · Faculty directory", "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", "official", "Cambridge CST 现任 faculty 名录"),
  cambridgeCurrentPhd: source("Cambridge CST · Current PhD students", "https://www.cl.cam.ac.uk/lists/phd/current.html", "official", "Cambridge 官方当前博士生、主导师、学术导师和课题清单"),
  cambridgePhdBySupervisor: source("Cambridge CST · PhD students by supervisor", "https://www.cl.cam.ac.uk/lists/phd/supervisor.html", "official", "Cambridge 官方按导师汇总的当前与已毕业博士生清单"),
  alanProfile: source("Cambridge CST · Alan Blackwell", "https://www.cst.cam.ac.uk/people/afb21", "official", "现任 faculty 职务、研究主题与教学"),
  alanHome: source("Alan Blackwell · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~afb21/", "profile", "现任教授、研究方向和逐名博士生/校友"),
  alanCv: source("Alan Blackwell · CV", "https://www.cl.cam.ac.uk/~afb21/afb-cv.pdf", "cv", "Auckland、Victoria Wellington 与 Cambridge 教育履历和产业经历"),
  aliceProfile: source("Cambridge CST · Alice Hutchings", "https://www.cst.cam.ac.uk/people/ah793", "official", "现任 faculty 职务与网络犯罪研究"),
  aliceHome: source("Alice Hutchings · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~ah793/", "profile", "Cybercrime Centre 领导、2013 博士、产业和研究经历、当前及毕业博士生"),
  aliceGrant: source("Cambridge CST · Alice Hutchings ERC Starting Grant", "https://www.cst.cam.ac.uk/news/private-eye-turned-researcher-receives-erc-starting-grant-study-cybercrime", "official", "博士训练、Australian Institute of Criminology 与 Cambridge 任职轨迹"),
  andrewProfile: source("Cambridge CST · Andrew Moore", "https://www.cst.cam.ac.uk/people/awm22", "official", "现任 Professor in Networked Systems 与研究主题"),
  andrewCv: source("Andrew Moore · Cambridge CV", "https://www.cl.cam.ac.uk/~awm22/cv-mini-2019-dec.pdf", "cv", "Monash 与 Cambridge 教育、任职、产业合作和研究项目"),
  andrewStudents: source("Andrew Moore · Cambridge research students", "https://www.cl.cam.ac.uk/~awm22/research/students.html", "profile", "逐名当前与过去博士生"),
  dongProfile: source("Cambridge CST · Dong Ma", "https://www.cst.cam.ac.uk/people/dm878", "official", "现任 Associate Professor、研究主题与教育"),
  dongAppointment: source("Cambridge CST · Dong Ma appointment", "https://www.cst.cam.ac.uk/news/new-associate-professor-wearable-computing", "official", "2026 Cambridge 任命、UNSW 博士、SMU/Cambridge/Data61 经历和研究奖项"),
  dongHome: source("Dong Ma · academic homepage", "https://dongma0a.github.io/", "profile", "Cambridge 现职、Mahbub Hassan/Wen Hu 博士指导、任职时间轴和具名学生"),
  ferminProfile: source("Cambridge CST · Fermin Moscoso del Prado Martin", "https://www.cst.cam.ac.uk/people/fm611", "official", "现任 Associate Professor 与语言/AI 研究"),
  ferminAppointment: source("Cambridge University Reporter · Fermin Moscoso appointment", "https://rso.admin.cam.ac.uk/reporter/2023-24/weekly/6711/section2.shtml", "official", "2023 年长期 Associate Professor 任命及 Madrid MEng、Radboud PhD"),
  ferminBio: source("UPM · Fermin Moscoso del Prado interview", "https://www.fi.upm.es/?pagina=679", "official", "UPM 教育、Nijmegen 心理语言学博士、CNRS 研究经历和本人照片"),
  jamieProfile: source("Cambridge CST · Jamie Vicary", "https://www.cst.cam.ac.uk/people/jv258", "official", "现任 Professor of Future Computation"),
  jamieHome: source("Jamie Vicary · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~jv258/", "profile", "Imperial 博士及 Chris Isham 导师、任职轨迹、研究和逐名学生去向"),
  jeremyProfile: source("Cambridge CST · Jeremy Yallop", "https://www.cst.cam.ac.uk/people/jdy22", "official", "现任 Associate Professor 与研究主题"),
  jeremyHome: source("Jeremy Yallop · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~jdy22/", "profile", "现任职务、编程语言项目、招生与 Cambridge MPhil 论文"),
  jeremyDissertation: source("Jeremy Yallop · Cambridge MPhil dissertation", "https://www.cl.cam.ac.uk/~jdy22/papers/dissertation.pdf", "publication", "Cambridge 研究训练及 web programming 研究"),
  jonProfile: source("Cambridge CST · Jon Sterling", "https://www.cst.cam.ac.uk/people/js2878", "official", "现任 Associate Professor 与 programming-languages/semantics 研究"),
  jonAppointment: source("Cambridge CST · Jon Sterling appointment", "https://www.cst.cam.ac.uk/news/new-associate-professor-logical-foundations-and-formal-methods", "official", "2023 Cambridge 任命、Berkeley 本科、CMU 博士和 Aarhus 博士后经历"),
  jonThesis: source("Carnegie Mellon · Jon Sterling PhD thesis", "https://www.cs.cmu.edu/~rwh/students/sterling.pdf", "thesis", "2021 CMU 博士论文及 Robert Harper 指导关系"),
  katieProfile: source("Cambridge CST · Katie Seaborn", "https://www.cst.cam.ac.uk/people/kas214", "official", "现任 Associate Professor、Cambridge/CHIA 任职、教育与招生"),
  katieLab: source("Aspirational Computing Lab · People", "https://aspirelab.io/people/", "profile", "实验室负责人、任职轨迹和逐名团队成员"),
  markusProfile: source("Cambridge CST · Markus Kuhn", "https://www.cst.cam.ac.uk/people/mgk25", "official", "现任 faculty 职务与研究"),
  markusHome: source("Markus Kuhn · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~mgk25/", "profile", "Cambridge/Purdue/Erlangen 教育、研究方向和逐名博士生"),
  richardProfile: source("Cambridge CST · Richard Mortier", "https://www.cst.cam.ac.uk/people/rmm1002", "official", "现任 Professor、Christ's College President、研究和产业角色"),
  richardCouncil: source("University of Cambridge · Richard Mortier", "https://www.governance.cam.ac.uk/committee-members/members/Pages/Richard-Mortier.aspx", "official", "Cambridge 现职、Nottingham、Microsoft Research、Sprint 与创业经历"),
  richardBio: source("Christ's College Magazine · Richard Mortier", "https://www.christs.cam.ac.uk/sites/default/files/2025-02/2016%20Magazine.pdf", "official", "Cambridge 数学本科与计算机博士、产业和任职履历"),
  robertProfile: source("Cambridge CST · Robert Harle", "https://www.cst.cam.ac.uk/people/rkh23", "official", "现任 Professor、研究主题与教学"),
  robertHome: source("Robert Harle · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~rkh23/site/", "profile", "Cambridge 自然科学、物理和工程博士教育及移动感知研究"),
  keshavProfile: source("Cambridge CST · Srinivasan Keshav", "https://www.cst.cam.ac.uk/people/sk818", "official", "现任 Robert Sansom Professor 与研究主题"),
  keshav4c: source("Cambridge Centre for Carbon Credits · Srinivasan Keshav", "https://4c.cst.cam.ac.uk/staff/professor-s-keshav", "official", "现任 PI、博士招生和可持续计算工作"),
  keshavCv: source("Srinivasan Keshav · Cambridge CV", "https://svr-sk818-web.cl.cam.ac.uk/keshav/wiki/images/7/71/Resume-Aug_2020.pdf", "cv", "教育、Bell Labs/Cornell/Ensim/Waterloo 任职、逐名博士生和首份去向"),
  tobiasProfile: source("Cambridge CST · Tobias Grosser", "https://www.cst.cam.ac.uk/people/tcg40", "official", "现任 faculty 职务与研究主题"),
  tobiasHome: source("Tobias Grosser · academic homepage", "https://grosser.science/", "profile", "Cambridge 现职、Edinburgh/ETH/ENS 履历、逐名团队和校友产业去向"),
  epflRoster: source("EPFL IC · Faculty members", "https://www.epfl.ch/schools/ic/about/faculty-members/", "official", "EPFL IC 现任教授名录"),
  emreProfile: source("EPFL People · Emre Telatar", "https://people.epfl.ch/emre.telatar?lang=en", "official", "现任 Full Professor、METU/MIT 教育、Bell Labs 经历、研究和逐名博士生"),
  martinProfile: source("EPFL People · Martin Rohrmeier", "https://people.epfl.ch/martin.rohrmeier/?lang=en", "official", "现任 Associate Professor、博士项目领导、课程和逐名博士生"),
  martinLab: source("EPFL DCML · Martin Rohrmeier", "https://www.epfl.ch/labs/dcml/lab/rohrmeier/", "official", "Bonn/Cambridge 教育、Ian Cross 博士指导、Microsoft Research/MIT/FU Berlin 经历"),
  sarahProfile: source("EPFL People · Sarah Kenderdine", "https://people.epfl.ch/sarah.kenderdine?lang=en", "official", "现任 Full Professor、eM+ 负责人和逐名博士生"),
  sarahBio: source("EPFL · Sarah Kenderdine biography", "https://actu.epfl.ch/news/we-want-to-create-a-narrative-out-of-all-the-heter", "official", "Otago/Curtin/RMIT 教育、UNSW 与 EPFL 任职和研究"),
} satisfies Record<string, Source>;

const fact = (label: string, value: string, s: Source) => ({ label, value, source: s });
type Seed = Omit<Person, "category" | "primary" | "status" | "introducedAt" | "lastVerifiedAt" | "portrait"> & { portraitFile: string; portraitSource: Source };
const person = (s: Seed): Person => ({ ...s, category: "core", primary: true, status: "current independent PI · strict fourth-round verification", introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-europe-fourth-round-batch-1-2026/${s.portraitFile}`, alt: `${s.name} 头像`, source: s.portraitSource } });

export const candidatePriorityP0EuropeFourthRoundBatch1People2026: Person[] = [
  person({ id: "alan-blackwell-cambridge-p0-r4", name: "Alan Blackwell", role: "Professor of Interdisciplinary Design", institution: "Cambridge", region: "Europe", area: "Human-Centred AI · HCI · Interdisciplinary Design", tags: ["HCI", "Human-Centred AI", "Design", "Representation"], summary: "Cambridge 跨学科设计教授，研究技术表征、人机交互与 AI 的社会和创造性替代路径。", stage: "senior", x: 180, y: 260, portraitFile: "alan-blackwell.jpg", portraitSource: sources.alanProfile, facts: [fact("当前任职", "Cambridge Professor of Interdisciplinary Design、Cambridge Global Challenges 联合主任及 Darwin College Fellow。", sources.alanHome), fact("教育与学术训练", "Auckland 电子工程本科、Victoria University of Wellington 计算机硕士、Cambridge 心理学博士。", sources.alanCv), fact("研究主线", "研究表征、人机交互、批判性设计、计算艺术及 human-centred AI。", sources.alanHome), fact("产业经历", "曾在 Progeni、Cambridge Consultants 和 Hitachi Europe 从事工业软件、AI 与工具研发。", sources.alanCv), fact("学生体系", "本人主页与 Cambridge 官方博士名录逐名记录 Joseph Cameron、Rachel Thomas 等博士生。", sources.cambridgeCurrentPhd)], sources: [sources.cambridgeRoster, sources.alanProfile, sources.alanHome, sources.alanCv, sources.cambridgeCurrentPhd] }),
  person({ id: "alice-hutchings-cambridge-p0-r4", name: "Alice Hutchings", role: "Professor · Director, Cambridge Cybercrime Centre", institution: "Cambridge", region: "Europe", area: "Cybercrime · Online Harms · Security", tags: ["Cybercrime", "Security", "Online Harms", "Computational Criminology"], summary: "Cambridge Cybercrime Centre 负责人，以数据驱动方法研究网络犯罪生态、地下市场和干预机制。", stage: "senior", x: 420, y: 260, portraitFile: "alice-hutchings.jpg", portraitSource: sources.aliceProfile, facts: [fact("当前任职", "Cambridge faculty，并任 Cambridge Cybercrime Centre Director。", sources.aliceHome), fact("教育与学术训练", "2013 年获 criminology PhD，研究网络犯罪者进入、维持与退出犯罪的路径。", sources.aliceHome), fact("任职轨迹", "曾任 Australian Institute of Criminology Senior Research Analyst，2014 年加入 Cambridge。", sources.aliceGrant), fact("研究主线", "研究网络犯罪者、地下市场、在线伤害、研究伦理及犯罪预防与干预。", sources.aliceHome), fact("学生体系", "本人主页和官方博士名录列出 Tina Marjanov、Anna Talas、Luna Rae Wang、Hannah Pankow 等当前博士生。", sources.aliceHome)], sources: [sources.cambridgeRoster, sources.aliceProfile, sources.aliceHome, sources.aliceGrant, sources.cambridgeCurrentPhd] }),
  person({ id: "andrew-moore-cambridge-p0-r4", name: "Andrew W. Moore", role: "Professor in Networked Systems", institution: "Cambridge", region: "Europe", area: "Networked Systems · Measurement · Machine Learning", tags: ["Networks", "Systems", "Machine Learning", "Performance"], summary: "Cambridge 网络系统教授，连接网络测量、性能工程、机器学习控制与开放硬件。", stage: "senior", x: 660, y: 260, portraitFile: "andrew-moore.jpg", portraitSource: sources.andrewProfile, facts: [fact("当前任职", "Cambridge Professor in Networked Systems。", sources.andrewCv), fact("教育与学术训练", "Monash Computing 本科与研究硕士；Cambridge Computer Laboratory 博士。", sources.andrewCv), fact("研究主线", "研究网络系统时延测量、建模和缓解，并涉及机器学习驱动网络控制。", sources.andrewCv), fact("产业连接", "CV 记录其与 Intel、AT&T、Google、Facebook、Huawei 等公司的研究联系，并共同创办 NetFPGA C.I.C.。", sources.andrewCv), fact("学生体系", "本人学生页与 Cambridge 官方博士名录列出 Jichun Wu、Wei Li、Charalampos Rotsos 等博士生。", sources.cambridgePhdBySupervisor)], sources: [sources.cambridgeRoster, sources.andrewProfile, sources.andrewCv, sources.andrewStudents, sources.cambridgePhdBySupervisor] }),
  person({ id: "dong-ma-cambridge-p0-r4", name: "Dong Ma", role: "Associate Professor in Wearable Computing", institution: "Cambridge", region: "Europe", area: "Wearable AI · Embedded ML · Human Sensing", tags: ["Wearable Computing", "Embedded ML", "Human Sensing", "Physiological Foundation Models"], summary: "Cambridge 可穿戴计算 PI，研究人类行为与生理信号感知、端侧学习和 physiological foundation models。", stage: "emerging", x: 900, y: 260, portraitFile: "dong-ma.jpg", portraitSource: sources.dongProfile, facts: [fact("当前任职", "2026 年起任 Cambridge Associate Professor in Wearable Computing，并为 Queens' College Fellow。", sources.dongHome), fact("教育与学术训练", "中南大学通信工程本科/硕士阶段；2019 年获 UNSW 博士，由 Mahbub Hassan 与 Wen Hu 指导。", sources.dongHome), fact("任职轨迹", "曾在 Data61-CSIRO 任研究助理、Cambridge 任博士后、SMU 任 Assistant Professor。", sources.dongAppointment), fact("研究主线", "研究可穿戴感知、人机交互、嵌入式机器学习、脉冲网络与生理基础模型。", sources.dongHome), fact("学生体系", "本人主页记录 Xiao Ma 完成由其指导的博士研究。", sources.dongHome)], sources: [sources.cambridgeRoster, sources.dongProfile, sources.dongAppointment, sources.dongHome] }),
  person({ id: "fermin-moscoso-cambridge-p0-r4", name: "Fermin Moscoso del Prado Martin", role: "Associate Professor · AI and Language", institution: "Cambridge", region: "Europe", area: "Computational Linguistics · Cognitive AI · Language", tags: ["NLP", "Cognitive AI", "Psycholinguistics", "Language Models"], summary: "Cambridge AI 与语言方向 PI，将心理语言学、信息论和计算模型用于理解语言学习与大模型。", stage: "senior", x: 1140, y: 260, portraitFile: "fermin-moscoso.jpg", portraitSource: sources.ferminBio, facts: [fact("当前任职", "2023 年获 Cambridge Computer Science University Associate Professor 长期任命。", sources.ferminAppointment), fact("教育与学术训练", "Madrid MEng；Radboud/Nijmegen 心理语言学博士。", sources.ferminAppointment), fact("任职轨迹", "UPM 官方访谈记录其曾任 CNRS 研究员；此后经历产业研究并回到学术界。", sources.ferminBio), fact("研究主线", "研究计算语言学、心理语言学、语言认知和 AI/LLM 的信息论分析。", sources.ferminProfile), fact("学生体系", "Cambridge 官方导师名录列 Paul Siewert、Przemyslaw Kubiak 为其博士生。", sources.cambridgePhdBySupervisor)], sources: [sources.cambridgeRoster, sources.ferminProfile, sources.ferminAppointment, sources.ferminBio, sources.cambridgePhdBySupervisor] }),
  person({ id: "jamie-vicary-cambridge-p0-r4", name: "Jamie Vicary", role: "Professor of Future Computation", institution: "Cambridge", region: "Europe", area: "Quantum Computing · Category Theory · Formal Methods", tags: ["Quantum Computing", "Category Theory", "Formal Methods", "Future Computation"], summary: "Cambridge Future Computation 教授，用范畴论、图形化推理和逻辑结构研究量子与经典计算。", stage: "senior", x: 1380, y: 260, portraitFile: "jamie-vicary.jpg", portraitSource: sources.jamieProfile, facts: [fact("当前任职", "Cambridge Professor of Future Computation、Royal Society University Research Fellow 和 King's College Fellow。", sources.jamieHome), fact("教育与学术训练", "Oxford 物理本科、Cambridge Part III；2009 年获 Imperial Physics PhD，导师 Chris Isham。", sources.jamieHome), fact("任职轨迹", "曾在 Oxford Quantum Group 与 Singapore Centre for Quantum Technologies 任博士后，后任 Birmingham faculty，2020 年加入 Cambridge。", sources.jamieHome), fact("研究主线", "研究范畴论、量子计算、图形化证明与未来计算的逻辑结构。", sources.jamieHome), fact("学生体系", "本人主页与官方博士名录记录 Ioannis Markakis、Wilfred Offord、Neria Baris 等博士生。", sources.cambridgePhdBySupervisor)], sources: [sources.cambridgeRoster, sources.jamieProfile, sources.jamieHome, sources.cambridgeCurrentPhd] }),
  person({ id: "jeremy-yallop-cambridge-p0-r4", name: "Jeremy Yallop", role: "Associate Professor · Programming Languages", institution: "Cambridge", region: "Europe", area: "Programming Languages · Compilers · Type Systems", tags: ["Programming Languages", "Compilers", "Type Systems", "Formal Methods"], summary: "Cambridge 编程语言 PI，研究类型系统、元编程、编译器验证和 OCaml 生态。", stage: "senior", x: 1620, y: 260, portraitFile: "jeremy-yallop.jpg", portraitSource: sources.jeremyProfile, facts: [fact("当前任职", "Cambridge Computer Laboratory Associate Professor，并任 Robinson College Fellow 与 Director of Studies。", sources.jeremyHome), fact("教育与学术训练", "Cambridge MPhil 研究以自动获取形容词次范畴化信息为主题，后持续进入编程语言与 web programming 研究。", sources.jeremyDissertation), fact("研究主线", "研究类型化宏、依赖类型、编译器验证、元编程与 OCaml。", sources.jeremyHome), fact("学生体系", "Cambridge 官方博士名录列 David Sheets、Yulong Huang、Jacob Bennett-Woolf、Alistair O'Brien 等由其指导。", sources.cambridgePhdBySupervisor)], sources: [sources.cambridgeRoster, sources.jeremyProfile, sources.jeremyHome, sources.jeremyDissertation, sources.cambridgePhdBySupervisor] }),
  person({ id: "jon-sterling-cambridge-p0-r4", name: "Jon Sterling", role: "Associate Professor · Logical Foundations and Formal Methods", institution: "Cambridge", region: "Europe", area: "Programming Languages · Type Theory · Semantics", tags: ["Programming Languages", "Type Theory", "Semantics", "Formal Methods"], summary: "Cambridge 逻辑基础与形式化方法 PI，以类型论、范畴论和 domain theory 研究程序语言语义。", stage: "emerging", x: 1740, y: 420, portraitFile: "jon-sterling.jpg", portraitSource: sources.jonProfile, facts: [fact("当前任职", "Cambridge CST Associate Professor in Logical Foundations and Formal Methods。", sources.jonProfile), fact("教育与学术训练", "UC Berkeley Linguistics BA；2021 年获 Carnegie Mellon Computer Science PhD，导师 Robert Harper。", sources.jonThesis), fact("任职轨迹", "加入 Cambridge 前任 Aarhus University Marie Skłodowska-Curie Postdoctoral Fellow。", sources.jonAppointment), fact("研究主线", "利用类型论、范畴论、domain theory 与 topos theory 研究编程语言和语义。", sources.jonProfile), fact("学生体系", "Cambridge 官方博士名录列 Jem Lord、Benno Lossin 等由其指导。", sources.cambridgeCurrentPhd)], sources: [sources.cambridgeRoster, sources.jonProfile, sources.jonAppointment, sources.jonThesis, sources.cambridgeCurrentPhd] }),
  person({ id: "katie-seaborn-cambridge-p0-r4", name: "Katie Seaborn", role: "Associate Professor · Director, Aspirational Computing Lab", institution: "Cambridge", region: "Europe", area: "HCI · Critical Computing · Human-Robot Interaction", tags: ["HCI", "Human-Robot Interaction", "Responsible AI", "Critical Computing"], summary: "Cambridge HCI PI，围绕 human-agent interaction、社会机器人、包容性设计和 critical computing 展开研究。", stage: "emerging", x: 1860, y: 260, portraitFile: "katie-seaborn.jpg", portraitSource: sources.katieProfile, facts: [fact("当前任职", "Cambridge CST Associate Professor、CHIA Associate Fellow，并领导 Aspirational Computing Lab。", sources.katieProfile), fact("教育与学术训练", "Simon Fraser University BA/MSc；2016 年获 University of Toronto Mechanical and Industrial Engineering PhD。", sources.katieProfile), fact("任职轨迹", "曾在 University of Tokyo、RIKEN AIP 与 Institute of Science Tokyo 开展研究和任教。", sources.katieLab), fact("研究主线", "研究 HCI、critical computing、human-agent/robot interaction、性别与包容性设计。", sources.katieProfile), fact("团队体系", "实验室主页逐名列出 Yijia Wang、Xiaodan Gloria Zhang 等博士生。", sources.katieLab)], sources: [sources.cambridgeRoster, sources.katieProfile, sources.katieLab] }),
  person({ id: "markus-kuhn-cambridge-p0-r4", name: "Markus Kuhn", role: "Associate Professor · Security", institution: "Cambridge", region: "Europe", area: "Hardware Security · Signal Security · Cryptography", tags: ["Security", "Hardware Security", "Side Channels", "Cryptography"], summary: "Cambridge 安全方向资深 PI，研究硬件与信号侧信道、RFID、导航系统认证及防篡改技术。", stage: "senior", x: 2100, y: 260, portraitFile: "markus-kuhn.jpg", portraitSource: sources.markusProfile, facts: [fact("当前任职", "Cambridge CST Associate Professor，并为 Wolfson College Fellow。", sources.markusHome), fact("教育与学术训练", "University of Erlangen Diplom、Purdue MSc、2002 年 Cambridge PhD。", sources.markusHome), fact("研究主线", "研究 compromising emanations、硬件安全、RFID、导航信号认证与 signal-processing security。", sources.markusHome), fact("学生体系", "本人主页逐名列出 Eric Chun-Yu Peng 及 Piotr Zieliński、Steven Murdoch、Gerhard Hancke 等毕业博士生。", sources.markusHome)], sources: [sources.cambridgeRoster, sources.markusProfile, sources.markusHome, sources.cambridgePhdBySupervisor] }),
  person({ id: "richard-mortier-cambridge-p0-r4", name: "Richard Mortier", role: "Professor of Computing and Human-Data Interaction", institution: "Cambridge", region: "Europe", area: "Human-Data Interaction · Systems · Edge AI", tags: ["Human-Data Interaction", "Systems", "Edge AI", "Privacy"], summary: "Cambridge Human-Data Interaction 教授，把隐私保护系统、边缘 AI、IoT 和知识管理连接起来。", stage: "senior", x: 2340, y: 260, portraitFile: "richard-mortier.jpg", portraitSource: sources.richardProfile, facts: [fact("当前任职", "Cambridge Professor of Computing and Human-Data Interaction，并任 Christ's College President。", sources.richardProfile), fact("教育与学术训练", "在 Cambridge 完成 Mathematics BA 与 Computer Laboratory PhD。", sources.richardBio), fact("任职轨迹", "曾任 Nottingham faculty、Microsoft Research Cambridge researcher、Sprint ATL researcher，并创办初创公司。", sources.richardCouncil), fact("研究主线", "研究隐私保护个人数据处理、IoT 安全、smart cities、边缘 AI 与知识管理。", sources.richardProfile), fact("学生体系", "Cambridge 官方博士名录列 Stefan Behfar、Rupendra Nath Mitra、Matthew Clayton 等由其指导。", sources.cambridgePhdBySupervisor)], sources: [sources.cambridgeRoster, sources.richardProfile, sources.richardCouncil, sources.richardBio, sources.cambridgeCurrentPhd] }),
  person({ id: "robert-harle-cambridge-p0-r4", name: "Robert Harle", role: "Professor · Mobile and Ubiquitous Systems", institution: "Cambridge", region: "Europe", area: "Mobile Sensing · Ubiquitous Computing · Wearables", tags: ["Mobile Sensing", "Wearables", "Ubiquitous Computing", "Location"], summary: "Cambridge 移动与泛在计算教授，研究可穿戴感知、室内定位、情境感知和 cyberphysical systems。", stage: "senior", x: 2580, y: 260, portraitFile: "robert-harle.jpg", portraitSource: sources.robertProfile, facts: [fact("当前任职", "Cambridge CST Professor，并长期参与 mobile and cyberphysical systems 研究。", sources.robertProfile), fact("教育与学术训练", "Cambridge Natural Sciences BA、Experimental and Theoretical Physics MSci、2004 年 Engineering PhD。", sources.robertHome), fact("研究主线", "研究移动与可穿戴感知、室内定位、情境感知、运动感知和泛在计算。", sources.robertHome), fact("学生体系", "Cambridge 官方导师名录列 Agata Brajdić、Gareth Bailey 等已毕业博士生。", sources.cambridgePhdBySupervisor)], sources: [sources.cambridgeRoster, sources.robertProfile, sources.robertHome, sources.cambridgePhdBySupervisor] }),
  person({ id: "srinivasan-keshav-cambridge-p0-r4", name: "Srinivasan Keshav", role: "Robert Sansom Professor of Computer Science", institution: "Cambridge", region: "Europe", area: "Networks · Sustainable Systems · Carbon Accounting", tags: ["Networks", "Sustainable Computing", "Carbon Credits", "Distributed Systems"], summary: "Cambridge Robert Sansom Professor，从互联网系统扩展到可持续计算、能源系统与碳信用基础设施。", stage: "senior", x: 2820, y: 260, portraitFile: "srinivasan-keshav.jpg", portraitSource: sources.keshavProfile, facts: [fact("当前任职", "Cambridge Robert Sansom Professor of Computer Science，并为 Cambridge Centre for Carbon Credits PI。", sources.keshav4c), fact("教育与学术训练", "IIT Delhi BTech；UC Berkeley Computer Science PhD。", sources.keshavCv), fact("任职轨迹", "曾任 Bell Labs researcher、Cornell faculty、Ensim co-founder 和 Waterloo faculty/Canada Research Chair。", sources.keshavCv), fact("研究主线", "研究网络与分布式系统、可持续能源、碳核算和自然气候解决方案。", sources.keshavProfile), fact("学生体系", "CV 逐名列出 Christian Gorenflo、Fiodar Kazhamiaka、Omid Ardakanian 等博士生及首份去向。", sources.keshavCv)], sources: [sources.cambridgeRoster, sources.keshavProfile, sources.keshav4c, sources.keshavCv] }),
  person({ id: "tobias-grosser-cambridge-p0-r4", name: "Tobias Grosser", role: "Associate Professor · Compilers and Parallelism", institution: "Cambridge", region: "Europe", area: "Compilers · AI Systems · Formal Verification", tags: ["Compilers", "AI Systems", "Formal Verification", "Parallel Computing"], summary: "Cambridge 编译器 PI，以 MLIR/xDSL、验证编译、量子编译和 AI 加速器工具链连接软件与硬件。", stage: "emerging", x: 3060, y: 260, portraitFile: "tobias-grosser.jpg", portraitSource: sources.tobiasProfile, facts: [fact("当前任职", "Cambridge CST Associate Professor，领导 compilers, parallelism and programming-languages team。", sources.tobiasHome), fact("教育与学术训练", "曾获 Google PhD Fellowship，并在 École Normale Supérieure Paris 完成博士阶段研究。", sources.tobiasHome), fact("任职轨迹", "加入 Cambridge 前任 Edinburgh Reader 与 ETH Zurich Ambizione Fellow。", sources.tobiasHome), fact("研究主线", "研究 MLIR/xDSL、验证编译、量子编译、AI/科学计算和硬件工具链。", sources.tobiasHome), fact("团队与去向", "主页逐名列出当前博士生，并记录校友进入 Google、NVIDIA、AMD、Intel 等机构。", sources.tobiasHome)], sources: [sources.cambridgeRoster, sources.tobiasProfile, sources.tobiasHome, sources.cambridgePhdBySupervisor] }),
  person({ id: "emre-telatar-epfl-p0-r4", name: "Emre Telatar", role: "Full Professor · Information Theory Laboratory", institution: "EPFL", region: "Europe", area: "Information Theory · Communications · Coding", tags: ["Information Theory", "Communications", "Coding Theory", "Networks"], summary: "EPFL 信息论资深教授，从通信极限、编码和网络信息论形成长期博士生体系。", stage: "senior", x: 3300, y: 260, portraitFile: "emre-telatar.jpg", portraitSource: sources.emreProfile, facts: [fact("当前任职", "EPFL Full Professor，并领导 Information Theory Laboratory。", sources.emreProfile), fact("教育与学术训练", "METU Electrical Engineering BSc；MIT EECS SM 与 1992 年 PhD。", sources.emreProfile), fact("任职轨迹", "1992 年加入 AT&T Bell Laboratories/Lucent Communications Analysis Research Department，2000 年加入 EPFL。", sources.emreProfile), fact("研究主线", "研究通信与信息论、分布式压缩和无线通信网络。", sources.emreProfile), fact("学生体系", "EPFL 页面列出 Serhat Emre Coban、Adway Girish、Ryan Yuanqing Song 及多位已毕业博士生。", sources.emreProfile)], sources: [sources.epflRoster, sources.emreProfile] }),
  person({ id: "martin-rohrmeier-epfl-p0-r4", name: "Martin Rohrmeier", role: "Associate Professor · Director, DCML", institution: "EPFL", region: "Europe", area: "Computational Musicology · Generative Models · Cognition", tags: ["Computational Musicology", "Generative Models", "Cognition", "Digital Humanities"], summary: "EPFL Digital and Cognitive Musicology Lab 负责人，以计算生成模型研究音乐结构、学习和认知。", stage: "senior", x: 3540, y: 260, portraitFile: "martin-rohrmeier.jpg", portraitSource: sources.martinProfile, facts: [fact("当前任职", "EPFL Associate Professor、DCML Director，并曾任 Digital Humanities doctoral program director。", sources.martinProfile), fact("教育与学术训练", "在 Bonn 学习哲学、数学和音乐学；Cambridge Musicology MPhil 与 PhD，博士导师 Ian Cross。", sources.martinLab), fact("任职轨迹", "曾在 Microsoft Research、FU Berlin 与 MIT Intelligence Initiative 开展博士后研究。", sources.martinLab), fact("研究主线", "研究音乐结构、认知、隐式学习、概率/生成模型与数字音乐学。", sources.martinLab), fact("学生体系", "EPFL 页面列出 Marina Borsodi-Benson、Xinyi Guan、Shuxin Meng、Zeng Ren 等博士生。", sources.martinProfile)], sources: [sources.epflRoster, sources.martinProfile, sources.martinLab] }),
  person({ id: "sarah-kenderdine-epfl-p0-r4", name: "Sarah Kenderdine", role: "Full Professor · Director, eM+", institution: "EPFL", region: "Europe", area: "Digital Heritage · Visualization · Immersive Systems", tags: ["Visualization", "Digital Heritage", "Immersive Systems", "Digital Humanities"], summary: "EPFL Experimental Museology 负责人，用可视化、沉浸系统和数据科学重构文化遗产体验。", stage: "senior", x: 3780, y: 260, portraitFile: "sarah-kenderdine.jpg", portraitSource: sources.sarahProfile, facts: [fact("当前任职", "EPFL Full Professor，并领导 Laboratory for Experimental Museology (eM+)。", sources.sarahProfile), fact("教育与学术训练", "University of Otago BA、Curtin MA、2010 年 RMIT PhD。", sources.sarahBio), fact("任职轨迹", "曾任 UNSW Art & Design Professor 及 EPICentre founding director，2017 年加入 EPFL。", sources.sarahBio), fact("研究主线", "研究文化数据可视化、immersive/interactive systems、digital museology 与文化遗产。", sources.sarahBio), fact("学生体系", "EPFL 页面列 Tsz Kin Chau、Dhruva Gowda Storz 为当前博士生，Yumeng Hou 为已毕业博士生。", sources.sarahProfile)], sources: [sources.epflRoster, sources.sarahProfile, sources.sarahBio] }),
];

export const candidatePriorityP0EuropeFourthRoundBatch1SupportingPeople2026: Person[] = [{
  id: "tina-marjanov-cambridge-p0-r4-support",
  name: "Tina Marjanov",
  role: "PhD Student",
  institution: "Cambridge",
  region: "Europe",
  area: "Cybercrime · Stolen Data Economy",
  tags: ["PhD student", "Cybercrime"],
  summary: "Cambridge 官方博士名录列出的 Alice Hutchings 博士生。",
  category: "adjacent",
  stage: "adjacent",
  primary: false,
  status: "supporting student node · relationship evidence only",
  sources: [sources.cambridgeCurrentPhd],
  x: 420,
  y: 500,
}];

export const candidatePriorityP0EuropeFourthRoundBatch1Relationships2026: Relationship[] = [{
  id: "p0-eu-r4-hutchings-marjanov-lineage",
  from: "alice-hutchings-cambridge-p0-r4",
  to: "tina-marjanov-cambridge-p0-r4-support",
  type: "lineage",
  subtype: "phd_adviser",
  label: "博士导师",
  evidence: "Cambridge 官方博士名录与 Alice Hutchings 本人主页均将 Tina Marjanov 列为其博士生。",
  source: sources.cambridgeCurrentPhd,
  verified: true,
}];
export const candidatePriorityP0EuropeFourthRoundBatch1GroupMembers2026: GroupMember[] = [
  { id: "p0-eu-r4-blackwell-cameron", teacherId: "alan-blackwell-cambridge-p0-r4", name: "Joseph Cameron", role: "Current PhD student", focus: "Generative AI, timbre and HCI", source: sources.cambridgeCurrentPhd },
  { id: "p0-eu-r4-hutchings-marjanov", teacherId: "alice-hutchings-cambridge-p0-r4", name: "Tina Marjanov", role: "Current PhD student", focus: "Stolen data economy", source: sources.cambridgeCurrentPhd },
  { id: "p0-eu-r4-moore-wu", teacherId: "andrew-moore-cambridge-p0-r4", name: "Jichun Wu", role: "Current PhD student", focus: "Low-latency RDMA systems", source: sources.cambridgePhdBySupervisor },
  { id: "p0-eu-r4-ma-xiao", teacherId: "dong-ma-cambridge-p0-r4", name: "Xiao Ma", role: "Former PhD student", focus: "On-demand test-time adaptation", source: sources.dongHome },
  { id: "p0-eu-r4-fermin-siewert", teacherId: "fermin-moscoso-cambridge-p0-r4", name: "Paul Siewert", role: "Current PhD student", focus: "Computational phonology", source: sources.cambridgePhdBySupervisor },
  { id: "p0-eu-r4-vicary-offord", teacherId: "jamie-vicary-cambridge-p0-r4", name: "Wilfred Offord", role: "Current PhD student", focus: "Higher category models", source: sources.cambridgeCurrentPhd },
  { id: "p0-eu-r4-yallop-bennett", teacherId: "jeremy-yallop-cambridge-p0-r4", name: "Jacob Bennett-Woolf", role: "Current PhD student", focus: "Unrolling data types", source: sources.cambridgePhdBySupervisor },
  { id: "p0-eu-r4-sterling-lord", teacherId: "jon-sterling-cambridge-p0-r4", name: "Jem Lord", role: "Current PhD student", focus: "Sheaves and complexity theory", source: sources.cambridgeCurrentPhd },
  { id: "p0-eu-r4-seaborn-zhang", teacherId: "katie-seaborn-cambridge-p0-r4", name: "Xiaodan Gloria Zhang", role: "PhD student", focus: "Human-agent interaction and dark patterns", source: sources.katieLab },
  { id: "p0-eu-r4-kuhn-peng", teacherId: "markus-kuhn-cambridge-p0-r4", name: "Eric Chun-Yu Peng", role: "Current PhD student", focus: "Hardware and signal security", source: sources.markusHome },
  { id: "p0-eu-r4-mortier-behfar", teacherId: "richard-mortier-cambridge-p0-r4", name: "Stefan Behfar", role: "Current PhD student", focus: "Distributed lightweight LLM training", source: sources.cambridgeCurrentPhd },
  { id: "p0-eu-r4-harle-brajdic", teacherId: "robert-harle-cambridge-p0-r4", name: "Agata Brajdić", role: "Former PhD student", focus: "Smartphone pedestrian localisation", source: sources.cambridgePhdBySupervisor },
  { id: "p0-eu-r4-keshav-gorenflo", teacherId: "srinivasan-keshav-cambridge-p0-r4", name: "Christian Gorenflo", role: "Former PhD student", focus: "Permissioned blockchain systems", source: sources.keshavCv },
  { id: "p0-eu-r4-grosser-bhat", teacherId: "tobias-grosser-cambridge-p0-r4", name: "Siddharth Bhat", role: "Current PhD student", focus: "Compiler verification", source: sources.tobiasHome },
  { id: "p0-eu-r4-telatar-coban", teacherId: "emre-telatar-epfl-p0-r4", name: "Serhat Emre Coban", role: "Current PhD student", focus: "Information theory", source: sources.emreProfile },
  { id: "p0-eu-r4-rohrmeier-borsodi", teacherId: "martin-rohrmeier-epfl-p0-r4", name: "Marina Borsodi-Benson", role: "Current PhD student", focus: "Digital and cognitive musicology", source: sources.martinProfile },
  { id: "p0-eu-r4-kenderdine-chau", teacherId: "sarah-kenderdine-epfl-p0-r4", name: "Tsz Kin Chau", role: "Current PhD student", focus: "Experimental museology", source: sources.sarahProfile },
];

export const candidatePriorityP0EuropeFourthRoundBatch1Placements2026: StudentPlacement[] = [
  { id: "p0-eu-r4-keshav-gorenflo-axelar", teacherId: "srinivasan-keshav-cambridge-p0-r4", studentName: "Christian Gorenflo", company: "Axelar", role: "Employee", evidence: "Srinivasan Keshav 的 Cambridge-hosted CV 记录 Christian Gorenflo 博士毕业后的首份去向为 Axelar。", source: sources.keshavCv, verified: true },
  { id: "p0-eu-r4-grosser-gysi-google", teacherId: "tobias-grosser-cambridge-p0-r4", studentName: "Tobias Gysi", company: "Google Zurich", role: "Research Engineer", evidence: "Tobias Grosser 本人团队页记录 Tobias Gysi 从其博士/博士后团队转至 Google Zurich。", source: sources.tobiasHome, verified: true },
  { id: "p0-eu-r4-vicary-verdon-bristol", teacherId: "jamie-vicary-cambridge-p0-r4", studentName: "Dominic Verdon", company: "University of Bristol", role: "Postdoctoral researcher", evidence: "Jamie Vicary 本人主页记录其学生 Dominic Verdon 获 Bristol 量子信息组博士后职位。", source: sources.jamieHome, verified: true },
];

export const candidatePriorityP0EuropeFourthRoundBatch1RosterPromotions2026 = [
  ...candidatePriorityP0EuropeFourthRoundBatch1People2026.filter((person) => person.institution === "Cambridge").map((person) => ({ unitUrl: sources.cambridgeRoster.url, rosterName: person.name, atlasPersonId: person.id })),
  ...candidatePriorityP0EuropeFourthRoundBatch1People2026.filter((person) => person.institution === "EPFL").map((person) => ({ unitUrl: sources.epflRoster.url, rosterName: person.name === "Martin Rohrmeier" ? "Martin Alois Rohrmeier" : person.name, atlasPersonId: person.id })),
] as const;

export const people = candidatePriorityP0EuropeFourthRoundBatch1People2026;
export const supportingPeople = candidatePriorityP0EuropeFourthRoundBatch1SupportingPeople2026;
export const relationships = candidatePriorityP0EuropeFourthRoundBatch1Relationships2026;
export const placements = candidatePriorityP0EuropeFourthRoundBatch1Placements2026;
export const groupMembers = candidatePriorityP0EuropeFourthRoundBatch1GroupMembers2026;
export const rosterPromotions = candidatePriorityP0EuropeFourthRoundBatch1RosterPromotions2026;
