import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const fact = (label: string, value: string, sourceItem: Source) => ({ label, value, source: sourceItem });

const sources = {
  tsinghuaRoster: source("清华大学计算机系 · Full-time Faculty", "https://www.cs.tsinghua.edu.cn/csen/Faculty/Full_time_Faculty.htm", "official", "现任全职教师名录"),
  chunOfficial: source("清华大学计算机系 · Chun Yu", "https://www.cs.tsinghua.edu.cn/csen/info/1307/4341.htm", "official", "现任副教授任职"),
  chunHome: source("Chun Yu · Pervasive Interaction Lab", "https://pi.cs.tsinghua.edu.cn/lab/people/ChunYu/", "profile", "教育、研究、学生名单、校友去向与合作论文"),
  yuanchunOfficial: source("清华大学计算机系 · Yuanchun Shi", "https://www.cs.tsinghua.edu.cn/csen/info/1306/4332.htm", "official", "现任教授、教育、研究与项目"),
  hongningOfficial: source("清华大学计算机系 · Hongning Wang", "https://www.cs.tsinghua.edu.cn/csen/info/1313/4406.htm", "official", "现任副教授、教育与任职经历"),
  hongningHome: source("Hongning Wang · CoAI", "https://coai.cs.tsinghua.edu.cn/hw-ai/", "profile", "研究方向、任职轨迹与科研项目"),
  hongningThesis: source("Illinois IDEALS · Hongning Wang doctoral dissertation", "https://www.ideals.illinois.edu/items/50683/bitstreams/147292/data.pdf", "thesis", "博士论文致谢明确 ChengXiang Zhai 为博士导师"),
  hongningCv: source("Hongning Wang · CV", "https://www.cs.virginia.edu/~hw5x/Data/cv-wang-2021.PDF", "cv", "学生培养与职业去向"),
  hkustRoster: source("HKUST CSE · Faculty", "https://cse.hkust.edu.hk/admin/people/faculty", "official", "现任教师名录"),
  linpingOfficial: source("HKUST CSE · Linping Yuan", "https://cse.hkust.edu.hk/admin/people/faculty/profile/yuanlp", "official", "现任 Research Assistant Professor 任职"),
  linpingCv: source("Linping Yuan · CV", "https://yuanlinping.top/cv/", "cv", "教育、博士导师、研究与论文"),
};

const portrait = (file: string, name: string, src: string, sourceItem: Source) => ({
  src: `portraits/candidate-p0-asia-batch-10-2026/${file}`,
  alt: `${name} 官方头像`,
  source: { ...sourceItem, label: `${sourceItem.label} · portrait`, url: src, supports: "官方人物头像" },
});

export const candidatePriorityP0AsiaBatch10People2026: Person[] = [
  {
    id: "chun-yu-thu-p0-b10",
    name: "Chun Yu",
    chinese: "喻纯",
    role: "Associate Professor",
    institution: "THU",
    region: "Mainland China",
    area: "Human-Computer Interaction · Pervasive Computing · AI Interfaces",
    tags: ["HCI", "智能交互", "普适计算", "AI界面"],
    summary: "把软件、硬件与 AI 结合到自然人机交互，并公开完整学生培养记录的清华 HCI PI。",
    category: "core",
    status: "current independent PI · official faculty profile verified",
    stage: "senior",
    primary: true,
    x: 180,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("chun-yu.png", "Chun Yu", "https://pi.cs.tsinghua.edu.cn/lab/people/ChunYu/img/personal.png", sources.chunHome),
    sources: [sources.chunOfficial, sources.chunHome],
    facts: [
      fact("当前任职", "清华大学计算机系副教授、Pervasive Interaction Lab PI。", sources.chunOfficial),
      fact("教育与学术训练", "2006–2012 年在清华大学计算机系攻读博士，随后留校从事博士后研究。", sources.chunHome),
      fact("研究主线", "研究 HCI、普适计算及融合软件、硬件与 AI 的智能交互。", sources.chunHome),
      fact("学生体系", "个人主页公开列出 7 位已毕业博士生和多位在读博士、硕士研究生。", sources.chunHome),
      fact("人才流动", "主页记录所指导本科生后续进入 Meta Reality Labs、Huawei Canada、MIT、UW 等机构。", sources.chunHome),
    ],
  },
  {
    id: "yuanchun-shi-thu-p0-b10",
    name: "Yuanchun Shi",
    chinese: "史元春",
    role: "Professor · Director, Key Lab of Pervasive Computing",
    institution: "THU",
    region: "Mainland China",
    area: "Human-Computer Interaction · Pervasive Computing · Multimodal Interaction",
    tags: ["HCI", "普适计算", "多模态交互", "VR/AR"],
    summary: "长期建设清华普适计算与自然人机交互方向，并连接移动端、大屏与 VR/AR 交互研究的资深 PI。",
    category: "core",
    status: "current independent PI · official faculty profile verified",
    stage: "senior",
    primary: true,
    x: 360,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("yuanchun-shi.jpg", "Yuanchun Shi", "https://www.cs.tsinghua.edu.cn/__local/9/DF/5F/D88941FAD72DA6BE7FAA1E1A0DF_7DD92A1F_182C9.jpg", sources.yuanchunOfficial),
    sources: [sources.yuanchunOfficial, sources.tsinghuaRoster],
    facts: [
      fact("当前任职", "清华大学计算机系教授、教育部普适计算重点实验室主任。", sources.yuanchunOfficial),
      fact("教育与学术训练", "在清华大学获得计算机学士、硕士与博士学位。", sources.yuanchunOfficial),
      fact("学术轨迹", "1993 年加入清华计算机系，2002 年晋升教授。", sources.yuanchunOfficial),
      fact("研究主线", "研究 HCI、普适计算、移动端与大屏智能交互以及 VR/AR。", sources.yuanchunOfficial),
      fact("产业合作", "官方简介列出阿里—清华与华为—清华联合研究计划的 PI 项目。", sources.yuanchunOfficial),
    ],
  },
  {
    id: "hongning-wang-thu-p0-b10",
    name: "Hongning Wang",
    role: "Tenured Associate Professor",
    institution: "THU",
    region: "Mainland China",
    area: "Machine Learning · Information Retrieval · Sequential Decision Making",
    tags: ["机器学习", "信息检索", "序列决策", "LLM"],
    summary: "从检索与用户建模延伸到序列决策和大模型智能体，并具有 UIUC—UVA—清华跨校学术轨迹的 PI。",
    category: "core",
    status: "current independent PI · official faculty profile verified",
    stage: "senior",
    primary: true,
    x: 540,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("hongning-wang.jpg", "Hongning Wang", "https://coai.cs.tsinghua.edu.cn/hw-ai/figures/2013fall.jpg", sources.hongningHome),
    sources: [sources.hongningOfficial, sources.hongningHome, sources.hongningThesis, sources.hongningCv],
    facts: [
      fact("当前任职", "2023 年起任清华大学计算机系长聘副教授。", sources.hongningOfficial),
      fact("教育与学术训练", "清华计算机本科、硕士；2014 年获 UIUC 计算机博士。", sources.hongningOfficial),
      fact("博士师承", "博士论文致谢明确称 ChengXiang Zhai 为博士导师。", sources.hongningThesis),
      fact("研究主线", "研究机器学习、信息检索与序列决策，近期建设 AI Cosmos 多智能体系统。", sources.hongningHome),
      fact("任职轨迹", "加入清华前在 University of Virginia 任教九年并获得终身教职。", sources.hongningOfficial),
    ],
  },
  {
    id: "linping-yuan-hkust-p0-b10",
    name: "Linping Yuan",
    chinese: "袁林萍",
    role: "Research Assistant Professor",
    institution: "HKUST",
    region: "Hong Kong",
    area: "Human-Computer Interaction · Visualization · Human-AI Collaboration",
    tags: ["HCI", "可视化", "人机协作", "增强现实"],
    summary: "研究可视化、增强现实与生成式 AI 协作界面的 HKUST 青年独立 PI。",
    category: "core",
    status: "current independent PI · official faculty profile verified",
    stage: "emerging",
    primary: true,
    x: 720,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("linping-yuan.jpg", "Linping Yuan", "https://cse.hkust.edu.hk/admin/people/faculty/photos/yuanlp.jpg", sources.linpingOfficial),
    sources: [sources.linpingOfficial, sources.linpingCv, sources.hkustRoster],
    facts: [
      fact("当前任职", "HKUST CSE Research Assistant Professor。", sources.linpingOfficial),
      fact("教育与学术训练", "2019–2024 年在 HKUST CSE 攻读博士，本科毕业于西安交通大学软件工程。", sources.linpingCv),
      fact("博士师承", "个人 CV 明确记录博士阶段由 Huamin Qu 指导。", sources.linpingCv),
      fact("研究主线", "研究 HCI、信息可视化、移动增强现实与人机创意协作。", sources.linpingOfficial),
      fact("代表性方向", "其论文覆盖动画生成中的意图表达、沉浸式可视化和生成式 AI 交互。", sources.linpingCv),
    ],
  },
];

export const candidatePriorityP0AsiaBatch10Relationships2026: Relationship[] = [
  {
    id: "p0-asia-b10-shi-yu-collaboration",
    from: "yuanchun-shi-thu-p0-b10",
    to: "chun-yu-thu-p0-b10",
    type: "collaboration",
    label: "HCI / 普适交互长期合作",
    evidence: "Chun Yu 的研究主页列出两人在智能家居交互、语音编辑和普适界面等多篇论文中的共同署名。",
    source: sources.chunHome,
    evidenceObject: "Chun Yu publication list on the official Tsinghua-hosted lab homepage",
    verified: true,
  },
  {
    id: "p0-asia-b10-zhai-hongning-lineage",
    from: "chengxiang-zhai-lineage",
    to: "hongning-wang-thu-p0-b10",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "Hongning Wang 的 UIUC 博士论文致谢明确称 ChengXiang Zhai 为 PhD adviser。",
    source: sources.hongningThesis,
    evidenceObject: "Hongning Wang doctoral dissertation acknowledgements",
    verified: true,
  },
  {
    id: "p0-asia-b10-qu-yuan-lineage",
    from: "huamin-qu-hkust",
    to: "linping-yuan-hkust-p0-b10",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "Linping Yuan 的个人 CV 明确记录其 HKUST 博士阶段由 Huamin Qu 指导。",
    source: sources.linpingCv,
    evidenceObject: "Linping Yuan CV · Education section",
    verified: true,
  },
];

export const candidatePriorityP0AsiaBatch10GroupMembers2026: GroupMember[] = [
  { id: "p0-asia-b10-yu-yizheng-gu", teacherId: "chun-yu-thu-p0-b10", name: "Yizheng Gu", role: "Graduated PhD student (2022)", source: sources.chunHome },
  { id: "p0-asia-b10-yu-weinan-shi", teacherId: "chun-yu-thu-p0-b10", name: "Weinan Shi", role: "Graduated PhD student (2021)", source: sources.chunHome },
  { id: "p0-asia-b10-wang-huazheng", teacherId: "hongning-wang-thu-p0-b10", name: "Huazheng Wang", role: "PhD student / advisee listed in CV", source: sources.hongningCv },
];

export const candidatePriorityP0AsiaBatch10Placements2026: StudentPlacement[] = [
  { id: "p0-asia-b10-yu-mingrui-meta", student: "Mingrui Ray Zhang", teacherId: "chun-yu-thu-p0-b10", company: "Meta Reality Labs", role: "Research Scientist", kind: "reported", sector: "industry", note: "Chun Yu 主页记录其本科生随后在 UW 获博士并进入 Meta Reality Labs。", source: sources.chunHome, verifiedAt: checkedAt },
  { id: "p0-asia-b10-yu-zhen-huawei", student: "Zhen Li", teacherId: "chun-yu-thu-p0-b10", company: "Huawei Canada", role: "Senior Researcher", kind: "reported", sector: "industry", note: "Chun Yu 主页记录其本科生随后在 Toronto 获博士并进入 Huawei Canada。", source: sources.chunHome, verifiedAt: checkedAt },
  { id: "p0-asia-b10-wang-adam-apple", student: "Adam Jiang", teacherId: "hongning-wang-thu-p0-b10", company: "Apple", role: "Senior Data Scientist", kind: "reported", sector: "industry", note: "Hongning Wang 的 CV 记录该学生去向 Apple。", source: sources.hongningCv, verifiedAt: checkedAt },
  { id: "p0-asia-b10-wang-jason-microsoft", student: "Jason Lewris", teacherId: "hongning-wang-thu-p0-b10", company: "Microsoft", role: "Data Scientist", kind: "reported", sector: "industry", note: "Hongning Wang 的 CV 记录该学生去向 Microsoft。", source: sources.hongningCv, verifiedAt: checkedAt },
];

export const candidatePriorityP0AsiaBatch10RosterPromotions2026 = [
  { unitUrl: "https://www.cs.tsinghua.edu.cn/csen/Faculty/Full_time_Faculty.htm", rosterName: "Chun YU", atlasPersonId: "chun-yu-thu-p0-b10" },
  { unitUrl: "https://www.cs.tsinghua.edu.cn/csen/Faculty/Full_time_Faculty.htm", rosterName: "Yuanchun SHI", atlasPersonId: "yuanchun-shi-thu-p0-b10" },
  { unitUrl: "https://www.cs.tsinghua.edu.cn/csen/Faculty/Full_time_Faculty.htm", rosterName: "Hongning Wang", atlasPersonId: "hongning-wang-thu-p0-b10" },
  { unitUrl: "https://cse.hkust.edu.hk/admin/people/faculty", rosterName: "Linping YUAN", atlasPersonId: "linping-yuan-hkust-p0-b10" },
];
