import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";
const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const sources = {
  roster: source("ETH Zurich D-INFK · Faculty", "https://inf.ethz.ch/people/faculty.html", "official", "ETH D-INFK 现任教授名录、职称和研究范围"),
  steurerBio: source("ETH CSE annual report · David Steurer", "https://ethz.ch/content/dam/ethz/special-interest/study-programme-websites/ms-compsci-and-eng-dam/documents/annual-reports/cse_annual_report_1819.pdf", "official", "Saarland/Princeton 教育、Microsoft Research 博后、Cornell/IAS/ETH 任职与机器学习相关理论研究"),
  steurerAppointment: source("ETH · David Steurer appointed Associate Professor", "https://ethz.ch/en/news-and-events/eth-news/news/2020/07/new-professors-four-women-and-four-men.html", "official", "ETH Associate Professor 现职与复杂性、优化、数据分析研究"),
  steurerStudent: source("Afonso Bandeira · ETH curriculum vitae", "https://people.math.ethz.ch/~abandeira/cvAfonso.pdf", "profile", "博士生联合指导清单明确 Hongjie Chen 的主导师为 David Steurer"),
  jungProfile: source("Ralf Jung · academic homepage", "https://research.ralfj.de/", "profile", "ETH Assistant Professor 与 PLF Lab 负责人、Derek Dreyer 博士指导、MIT 博后及 Rust/Iris 研究"),
  jungCv: source("Ralf Jung · curriculum vitae", "https://research.ralfj.de/cv.pdf", "profile", "Saarland/MPI-SWS 学位、Derek Dreyer 指导、MIT CSAIL 博后与 Mozilla Research 经历"),
  jungTeam: source("ETH Programming Language Foundations Lab · People", "https://plf.inf.ethz.ch/people.html", "official", "Ralf Jung 为 Professor，并逐名列出当前博士生"),
  kyngBio: source("ETH · Rasmus Kyng Latsis Prize", "https://inf.ethz.ch/news-and-events/spotlights/infk-news-channel/2025/12/rasmus-kyng-receives-2025-eth-zurich-latsis-prize-for-groundbreaking-work-in-algorithms.html", "official", "ETH 教授与组长现职、Cambridge 本科、Yale 博士、Harvard/Simons 博后和研究方向"),
  kyngGroup: source("ETH Algorithms and Optimization Group", "https://kyng.inf.ethz.ch/", "official", "Rasmus Kyng 为 Associate Professor，并逐名列出博士生、博士后和校友去向"),
  roscoeProfile: source("Timothy Roscoe · ETH academic homepage", "https://people.inf.ethz.ch/troscoe/", "profile", "ETH Full Professor、Cambridge 博士、创业与 Sprint/Intel Research 经历及系统研究"),
  roscoeCv: source("Timothy Roscoe · curriculum vitae", "https://people.inf.ethz.ch/troscoe/cv-a4.pdf", "profile", "Cambridge BA、Diploma、PhD 与完整任职时间轴"),
  roscoeStudent: source("Roman Meier · ETH academic homepage", "https://people.inf.ethz.ch/romameie/", "profile", "Roman Meier 明确记录 ETH 博士导师为 Timothy Roscoe"),
} satisfies Record<string, Source>;
const fact = (label: string, value: string, s: Source) => ({ label, value, source: s });
type Seed = Omit<Person, "category" | "primary" | "status" | "introducedAt" | "lastVerifiedAt" | "portrait"> & { portraitFile: string; portraitSource: Source };
const person = (s: Seed): Person => ({ ...s, category: "core", primary: true, status: "current independent PI · official profile verified", introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-europe-batch-12-2026/${s.portraitFile}`, alt: `${s.name} 头像`, source: s.portraitSource } });
export const candidatePriorityP0EuropeBatch12People2026: Person[] = [
  person({ id: "david-steurer-eth-p0-2026", name: "David Steurer", role: "Associate Professor · Institute Head", institution: "ETH Zurich", region: "Europe", area: "Complexity Theory · Optimization · Machine Learning Theory", tags: ["Complexity Theory", "Approximation Algorithms", "Optimization", "Machine Learning Theory"], summary: "ETH 理论计算机科学教授，研究优化与高维估计的计算复杂性，连接 Princeton、Microsoft Research、Cornell 与 ETH 理论网络。", stage: "senior", x: 150, y: 240, portraitFile: "david-steurer.jpg", portraitSource: sources.roster, facts: [fact("当前任职", "ETH Zurich Associate Professor of Theoretical Computer Science，并任 Institute of Theoretical Computer Science Head。", sources.steurerAppointment), fact("教育与学术训练", "在 Saarland University 学习计算机科学，2010 年获 Princeton University 博士，后在 Microsoft Research New England 从事博士后研究。", sources.steurerBio), fact("研究主线", "研究复杂性理论、近似算法、凸优化，以及机器学习高维估计问题的计算极限。", sources.steurerBio), fact("任职经历", "曾任 Cornell University Assistant Professor，并访问 Institute for Advanced Study，2017 年加入 ETH。", sources.steurerBio)], sources: [sources.roster, sources.steurerBio, sources.steurerAppointment, sources.steurerStudent] }),
  person({ id: "ralf-jung-eth-p0-2026", name: "Ralf Jung", role: "Assistant Professor · PLF Lab Head", institution: "ETH Zurich", region: "Europe", area: "Programming Languages · Formal Verification · Rust", tags: ["Programming Languages", "Formal Verification", "Rust", "Iris"], summary: "ETH Programming Language Foundations Lab 负责人，以 RustBelt、Miri 和 Iris 推动真实系统软件的形式化基础与验证工具。", stage: "emerging", x: 360, y: 240, portraitFile: "ralf-jung.jpg", portraitSource: sources.roster, facts: [fact("当前任职", "ETH Zurich Assistant Professor，并领导 Programming Language Foundations Lab。", sources.jungProfile), fact("教育与学术训练", "在 Saarland University 与 MPI-SWS 完成计算机科学硕士和博士，导师 Derek Dreyer；随后在 MIT CSAIL PDOS 从事博士后研究。", sources.jungCv), fact("研究主线", "研究 Rust 的形式化基础、并发分离逻辑 Iris，以及真实软件系统的分析与验证。", sources.jungProfile), fact("产业与开源", "曾在 Mozilla Research 实习并任研究助理，长期参与 Rust、Miri 与 Iris 开源生态。", sources.jungCv)], sources: [sources.roster, sources.jungProfile, sources.jungCv, sources.jungTeam] }),
  person({ id: "rasmus-kyng-eth-p0-2026", name: "Rasmus Kyng", role: "Associate Professor · Algorithms and Optimization Group Head", institution: "ETH Zurich", region: "Europe", area: "Fast Algorithms · Graph Optimization · Numerical Linear Algebra", tags: ["Graph Algorithms", "Optimization", "Numerical Linear Algebra", "Machine Learning Theory"], summary: "ETH Algorithms and Optimization Group 负责人，研究近线性时间图算法、凸优化和数值线性代数，并连接机器学习与科学计算。", stage: "emerging", x: 570, y: 240, portraitFile: "rasmus-kyng.jpg", portraitSource: sources.roster, facts: [fact("当前任职", "ETH Zurich Associate Professor，并领导 Algorithms and Optimization Group。", sources.kyngBio), fact("教育与学术训练", "2011 年获 University of Cambridge 计算机科学学士，2017 年获 Yale University 博士，后在 UC Berkeley Simons Institute 与 Harvard Theory of Computation Group 从事博士后研究。", sources.kyngBio), fact("研究主线", "研究图问题的快速算法、凸优化、数值线性代数、fine-grained complexity，以及机器学习和科学计算应用。", sources.kyngBio), fact("团队建设", "官方组页逐名列出当前博士候选人、博士后和历届成员去向。", sources.kyngGroup)], sources: [sources.roster, sources.kyngBio, sources.kyngGroup] }),
  person({ id: "timothy-roscoe-eth-p0-2026", name: "Timothy Roscoe", role: "Full Professor · Systems Group", institution: "ETH Zurich", region: "Europe", area: "Operating Systems · Distributed Systems · Networking", tags: ["Operating Systems", "Distributed Systems", "Networking", "Hardware-Software Co-design"], summary: "ETH Systems Group 资深教授，从操作系统和网络扩展到硬件软件协同设计，履历连接 Cambridge、创业公司、Sprint、Intel Research 与 Berkeley。", stage: "senior", x: 780, y: 240, portraitFile: "timothy-roscoe.jpg", portraitSource: sources.roster, facts: [fact("当前任职", "自 2007 年起任 ETH Zurich Computer Science Full Professor，属于 Systems Group。", sources.roscoeProfile), fact("教育与学术训练", "在 University of Cambridge 完成数学 BA、计算机科学 Diploma，并于 1995 年获计算机科学博士。", sources.roscoeCv), fact("研究主线", "研究操作系统、分布式系统和网络，当前重点包括 Enzian 研究计算机与面向异构硬件的系统接口。", sources.roscoeProfile), fact("产业经历", "曾在 North Carolina 创业公司、Sprint Advanced Technology Lab 与 Intel Research Berkeley 工作，并任 UC Berkeley Adjunct Professor。", sources.roscoeProfile)], sources: [sources.roster, sources.roscoeProfile, sources.roscoeCv, sources.roscoeStudent] }),
];
export const candidatePriorityP0EuropeBatch12Relationships2026: Relationship[] = [];
export const candidatePriorityP0EuropeBatch12Placements2026: StudentPlacement[] = [];
export const candidatePriorityP0EuropeBatch12GroupMembers2026: GroupMember[] = [
  { id: "p0-eu12-steurer-hongjie-chen", teacherId: "david-steurer-eth-p0-2026", name: "Hongjie Chen", role: "PhD student · primary adviser David Steurer", focus: "Algorithms and computational theory", source: sources.steurerStudent },
  { id: "p0-eu12-jung-isaac-van-bakel", teacherId: "ralf-jung-eth-p0-2026", name: "Isaac van Bakel", role: "Current doctoral student", focus: "Formalization of the Rust borrow checker", source: sources.jungTeam },
  { id: "p0-eu12-kyng-aurelio-sulser", teacherId: "rasmus-kyng-eth-p0-2026", name: "Aurelio Sulser", role: "Current PhD candidate", focus: "Algorithms and optimization", source: sources.kyngGroup },
  { id: "p0-eu12-roscoe-roman-meier", teacherId: "timothy-roscoe-eth-p0-2026", name: "Roman Meier", role: "Current doctoral student", focus: "Operating systems and hardware-software co-design", source: sources.roscoeStudent },
];
export const candidatePriorityP0EuropeBatch12RosterPromotions2026 = [
  { unitUrl: "https://inf.ethz.ch/people/faculty.html", rosterName: "David Steurer", atlasPersonId: "david-steurer-eth-p0-2026" },
  { unitUrl: "https://inf.ethz.ch/people/faculty.html", rosterName: "Ralf Jung", atlasPersonId: "ralf-jung-eth-p0-2026" },
  { unitUrl: "https://inf.ethz.ch/people/faculty.html", rosterName: "Rasmus Kyng", atlasPersonId: "rasmus-kyng-eth-p0-2026" },
  { unitUrl: "https://inf.ethz.ch/people/faculty.html", rosterName: "Timothy Roscoe", atlasPersonId: "timothy-roscoe-eth-p0-2026" },
] as const;
export const people = candidatePriorityP0EuropeBatch12People2026;
export const relationships = candidatePriorityP0EuropeBatch12Relationships2026;
export const placements = candidatePriorityP0EuropeBatch12Placements2026;
export const groupMembers = candidatePriorityP0EuropeBatch12GroupMembers2026;
export const rosterPromotions = candidatePriorityP0EuropeBatch12RosterPromotions2026;
