import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";
const checkedAt="2026-09-03"; const source=(label:string,url:string,supports:string):Source=>({label,url,kind:"official",supports,checkedAt});
const roster=source("EPFL IC · Faculty members","https://www.epfl.ch/schools/ic/about/faculty-members/","EPFL IC 现任教师名录");
const haithamProfile=source("EPFL People · Haitham Al Hassanieh","https://people.epfl.ch/haitham.alhassanieh?lang=en","现任职务、博士生、课程与官方头像");
const haithamBio=source("EPFL · Haitham Al Hassanieh inaugural lecture","https://memento.epfl.ch/event/inaugural-lectures-prof-haitham-alhassanieh-prof-/","MIT 博士、UIUC 任职、研究与奖项履历");
const nateProfile=source("EPFL People · Nate Foster","https://people.epfl.ch/nate.foster?lang=en","EPFL 现任职务与官方头像");
const nateLab=source("EPFL LASeR · People","https://laser.epfl.ch/pages/people.html","教育、研究方向、Jane Street/DARPA 职务、团队与历届博士生去向");
const fact=(label:string,value:string,s:Source)=>({label,value,source:s});
const person=(r:Omit<Person,"category"|"primary"|"status"|"introducedAt"|"lastVerifiedAt"|"portrait">&{portraitFile:string;portraitSource:Source}):Person=>({...r,category:"core",primary:true,status:"current independent PI · official profile verified",introducedAt:checkedAt,lastVerifiedAt:checkedAt,portrait:{src:`portraits/candidate-p0-europe-full-batch-4-2026/${r.portraitFile}`,alt:`${r.name} 头像`,source:r.portraitSource}});
export const candidatePriorityP0EuropeFullBatch4People2026:Person[]=[
 person({id:"haitham-al-hassanieh-epfl-p0-full-2026",name:"Haitham Al Hassanieh",role:"Associate Professor · Sensing and Networking Systems",institution:"EPFL",region:"Europe",area:"Wireless Sensing · Signal Processing · Foundation Models",tags:["Wireless Sensing","Signal Processing","Foundation Models","Mobile Systems"],summary:"EPFL SENS 实验室负责人，从稀疏信号处理延伸到无线感知、网络系统与 sensing foundation models。",stage:"senior",x:260,y:210,portraitFile:"haitham-al-hassanieh.jpg",portraitSource:haithamProfile,facts:[fact("当前任职","EPFL Associate Professor，领导 Laboratory of Sensing and Networking Systems，并担任 SSC Director。",haithamProfile),fact("教育与学术训练","2016 年于 MIT 获博士学位，博士论文研究 Sparse Fourier Transform。",haithamBio),fact("任职经历","加入 EPFL 前曾任 University of Illinois Urbana–Champaign 教授。",haithamBio),fact("研究主线","研究信号处理、无线感知与网络系统，并面向 foundation models 和 AI 构建智能系统。",haithamProfile),fact("学生体系","EPFL 页面列出 Raphael Cannatà、Aoyu Gong、Jiachen Lu、Arman Maghsoudnia 等现任博士生。",haithamProfile)],sources:[roster,haithamProfile,haithamBio]}),
 person({id:"nate-foster-epfl-p0-full-2026",name:"Nate Foster",role:"Full Professor · Languages, Systems, and Networks",institution:"EPFL",region:"Europe",area:"Programming Languages · Programmable Networks · Verification",tags:["Programming Languages","Networks","Verification","Systems"],summary:"EPFL LASeR 教授，开发保障可编程网络与系统安全、可靠性的语言、形式化工具和验证方法。",stage:"senior",x:520,y:210,portraitFile:"nate-foster.jpg",portraitSource:nateProfile,facts:[fact("当前任职","EPFL Computer and Communication Sciences Full Professor，并任 Jane Street Visiting Researcher。",nateLab),fact("教育与学术训练","获 Williams College 计算机科学学士、University of Cambridge 科学史与科学哲学 MPhil，以及 University of Pennsylvania Computer and Information Science 博士。",nateLab),fact("研究主线","研究用于构建安全可靠系统的语言与工具，当前重点为可编程网络的语言、实现和验证。",nateLab),fact("学术服务","担任 DARPA Information Science and Technology study group Vice Chair。",nateLab),fact("学生与人才流动","LASeR 页面列出多位历届博士生及去向，包括 Praveen Kumar、Jonathan DiLorenzo 与 Steffen Smolka 进入 Google，Mark Reitblatt 进入 Meta。",nateLab)],sources:[roster,nateProfile,nateLab]}),
];
export const candidatePriorityP0EuropeFullBatch4Relationships2026:Relationship[]=[]; export const candidatePriorityP0EuropeFullBatch4Placements2026:StudentPlacement[]=[{id:"p0-eu-full4-foster-praveen-google",teacherId:"nate-foster-epfl-p0-full-2026",student:"Praveen Kumar",company:"Google",role:"Software Engineer",kind:"reported",degree:"PhD",graduationYear:2021,note:"LASeR alumni list records PhD 2021 and Google destination.",source:nateLab}];
export const candidatePriorityP0EuropeFullBatch4GroupMembers2026:GroupMember[]=[{id:"p0-eu-full4-haitham-aoyu-gong",teacherId:"haitham-al-hassanieh-epfl-p0-full-2026",name:"Aoyu Gong",role:"Current PhD student",focus:"Sensing and networking systems",source:haithamProfile},{id:"p0-eu-full4-foster-mark-barbone",teacherId:"nate-foster-epfl-p0-full-2026",name:"Mark Barbone",role:"PhD Student (Cornell)",focus:"Languages, systems, and networks",source:nateLab}];
export const candidatePriorityP0EuropeFullBatch4RosterPromotions2026=[{unitUrl:roster.url,rosterName:"Haitham Al Hassanieh",atlasPersonId:"haitham-al-hassanieh-epfl-p0-full-2026"},{unitUrl:roster.url,rosterName:"Nate Foster",atlasPersonId:"nate-foster-epfl-p0-full-2026"}] as const;
export const people=candidatePriorityP0EuropeFullBatch4People2026;export const relationships=candidatePriorityP0EuropeFullBatch4Relationships2026;export const placements=candidatePriorityP0EuropeFullBatch4Placements2026;export const groupMembers=candidatePriorityP0EuropeFullBatch4GroupMembers2026;export const rosterPromotions=candidatePriorityP0EuropeFullBatch4RosterPromotions2026;
