import type { Person, Relationship, Source } from "./data";

const checkedAt = "2026-09-03";
const src = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const f = (label: string, value: string, source: Source) => ({ label, value, source });

const rosters = {
  cityu: src("CityU CS · Academic staff", "https://www.cs.cityu.edu.hk/people/academic-staff", "official", "现任计算机系教师名录"),
  polyu: src("PolyU COMP · Academic staff", "https://www.polyu.edu.hk/comp/people/academic-staff/", "official", "现任计算机系教师名录"),
  nus: src("NUS Computing · Faculty", "https://www.comp.nus.edu.sg/about/faculty/", "official", "现任计算学院教师名录"),
  ntu: src("NTU CCDS · Faculty", "https://www.ntu.edu.sg/computing/our-faculty/faculty-at-ccds", "official", "现任计算与数据科学学院教师名录"),
};

const p = {
  guan: src("CityU Scholars · Nan Guan", "https://scholars.cityu.edu.hk/en/persons/nanguan/", "official", "现职、教育、研究方向、学生与头像"),
  hancke: src("CityU Scholars · Gerhard Petrus Hancke", "https://scholars.cityu.edu.hk/en/persons/pghancke/", "official", "现职、教育、履历、研究方向与头像"),
  jia: src("CityU Scholars · Xiaohua Jia", "https://scholars.cityu.edu.hk/en/persons/csjia/", "official", "现职、教育、研究方向、项目与头像"),
  lu: src("CityU Scholars · Zhenliang Lu", "https://scholars.cityu.edu.hk/en/persons/zhenlilu/", "official", "现职、教育、研究方向、学生与头像"),
  wu: src("CityU Scholars · Dapeng Wu", "https://scholars.cityu.edu.hk/en/persons/dapengwu/", "official", "现职、教育、研究方向、学生与头像"),
  zhao: src("CityU Scholars · Qingchuan Zhao", "https://scholars.cityu.edu.hk/en/persons/qizhao/", "official", "现职、教育、研究方向、学生与头像"),
  zhu: src("CityU Scholars · Kening Zhu", "https://scholars.cityu.edu.hk/en/persons/kening-zhu(5a5d8783-8153-4acb-b3a7-7f1a103d0cfc).html", "official", "现职、教育、研究方向、学生与头像"),
  chen: src("PolyU COMP · Changwen Chen", "https://www.polyu.edu.hk/comp/people/academic-staff/prof-chen-changwen/", "official", "现职、教育、任职履历、研究方向与头像"),
  luo: src("PolyU COMP · Xiapu Luo", "https://www.polyu.edu.hk/comp/people/academic-staff/prof-luo-xiapu-daniel/", "official", "现职、教育、博士后导师、研究方向与头像"),
  hahn: src("NUS Computing · Jungpil Hahn", "https://www.comp.nus.edu.sg/disa/people/jungpil", "official", "现职、教育、研究方向、博士生去向与头像"),
  ooi: src("NUS Computing · Ooi Wei Tsang", "https://www.comp.nus.edu.sg/cs/people/ooiwt", "official", "现职、教育、研究方向与头像"),
  dong: src("NUS Computing · Jin Song Dong", "https://www.comp.nus.edu.sg/cs/people/dongjs/", "official", "现职、教育、研究方向与头像"),
  dongHome: src("Jin Song Dong · NUS homepage", "https://www.comp.nus.edu.sg/~dongjs/", "profile", "博士生名单与学术去向"),
  tao: src("NTU Research · Dacheng Tao", "https://dr.ntu.edu.sg/entities/person/Tao-Dacheng", "official", "现职、研究方向、学术荣誉与头像"),
  taoCv: src("University of Sydney · Dacheng Tao CV", "https://www.sydney.edu.au/AcademicProfiles/profile/resource?type=cv&urlid=dacheng.tao", "cv", "教育履历与 MPhil/博士导师"),
  miao: src("NTU Research · Chun Yan Miao", "https://dr.ntu.edu.sg/entities/person/Miao-Chun-Yan", "official", "现职、教育、研究方向与头像"),
};

const r = {
  hanckePaper: src("CityU Scholars · Tangible Security", "https://scholars.cityu.edu.hk/en/publications/tangible-security-survey-of-methods-supporting-secure-ad-hoc-conn/", "publication", "完整作者列表包含 Gerhard Hancke 与 Aikaterini Mitrokotsa"),
  jiaProject: src("CityU Scholars · Trustworthy LLMs project", "https://scholars.cityu.edu.hk/en/projects/trustworthy-large-language-models-a-multifaceted-strategy-for-tru/", "official", "项目页列出 Xiaohua Jia 与 Irwin King 为共同研究者"),
  chenPaper: src("CVF · SD-DiT", "https://openaccess.thecvf.com/content/CVPR2024/html/Zhu_SD-DiT_Unleashing_the_Power_of_Self-supervised_Discrimination_in_Diffusion_Transformer_CVPR_2024_paper.html", "publication", "CVPR 论文页完整列出 Changwen Chen 与 Tao Mei 等作者"),
  ooiStudents: src("Ooi Wei Tsang · NUS students", "https://www.comp.nus.edu.sg/~ooiwt/students.html", "official", "历届学生、论文题目与首份工作去向"),
  miaoPaper: src("NTU DR · MedRAG", "https://dr.ntu.edu.sg/server/api/core/bitstreams/e08ccb7c-4557-4ed4-bec6-48b3a1bec3b2/content", "publication", "WWW 2025 论文完整作者列表包含 Chunyan Miao 与 Xuejiao Zhao"),
};

type Spec = { id: string; name: string; chinese?: string; role: string; institution: Person["institution"]; region: "Hong Kong" | "Singapore"; area: string; tags: string[]; summary: string; stage: "senior" | "emerging"; portrait: string; profile: Source; roster: Source; extra?: Source[]; facts: ReturnType<typeof f>[]; x: number; y: number };
const person = (s: Spec): Person => ({ id: s.id, name: s.name, chinese: s.chinese, role: s.role, institution: s.institution, region: s.region, area: s.area, tags: s.tags, summary: s.summary, stage: s.stage, x: s.x, y: s.y, facts: s.facts, category: "core", primary: true, status: "current independent PI · official profile verified", sources: [s.profile, s.roster, ...(s.extra ?? [])], introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: s.portrait, alt: `${s.name} 官方头像`, source: s.profile } });

export const candidatePriorityP0HkSgFifthRoundPeople2026: Person[] = [
  person({ id: "nan-guan-cityu-p0-r5", name: "Nan Guan", chinese: "关楠", role: "Professor · Associate Head", institution: "CityU", region: "Hong Kong", area: "Real-time Systems · Embedded Systems · Edge AI", tags: ["Real-time Systems", "Embedded Systems", "Edge AI", "Cyber-Physical Systems"], summary: "CityU CS 教授、副系主任，研究实时与嵌入式系统、边缘智能和信息物理系统。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/nan-guan.png", profile: p.guan, roster: rosters.cityu, x: 150, y: 130, facts: [f("当前任职", "CityU CS 教授、副系主任，并公开招收博士生。", p.guan), f("教育与学术训练", "在瑞典 Uppsala University 获博士学位。", p.guan), f("研究主线", "研究实时、嵌入式和信息物理系统，以及面向资源受限设备的边缘智能。", p.guan), f("学生体系", "CityU Scholars 的 supervised researchers 区列出 Yuxin Du 等博士生。", p.guan)] }),
  person({ id: "gerhard-hancke-cityu-p0-r5", name: "Gerhard Petrus Hancke", role: "Professor", institution: "CityU", region: "Hong Kong", area: "Cybersecurity · IoT · Embedded Security", tags: ["Cybersecurity", "IoT", "Embedded Security", "Wireless Security"], summary: "CityU CS 教授，研究物联网、嵌入式与无线系统安全。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/gerhard-hancke.png", profile: p.hancke, roster: rosters.cityu, extra: [r.hanckePaper], x: 360, y: 130, facts: [f("当前任职", "CityU CS 教授。", p.hancke), f("教育与学术训练", "在 University of Pretoria 获 BEng、MEng，在 University of Cambridge 获计算机科学博士。", p.hancke), f("任职轨迹", "加入 CityU 前曾在 Royal Holloway Information Security Group 任研究人员与 Teaching Fellow。", p.hancke), f("研究主线", "研究物联网、嵌入式设备、无线传感与安全协议。", p.hancke), f("合作关系", "CityU 论文页记录其与 Aikaterini Mitrokotsa 共同署名 Tangible Security 综述。", r.hanckePaper)] }),
  person({ id: "xiaohua-jia-cityu-p0-r5", name: "Xiaohua Jia", chinese: "贾小华", role: "Chair Professor · Centre Director", institution: "CityU", region: "Hong Kong", area: "Distributed Systems · Trustworthy AI · Network Security", tags: ["Distributed Systems", "Trustworthy AI", "Network Security", "Privacy"], summary: "CityU CS 讲座教授、去中心化可信计算中心主任，研究分布式系统、网络安全和可信 AI。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/xiaohua-jia.png", profile: p.jia, roster: rosters.cityu, extra: [r.jiaProject], x: 570, y: 130, facts: [f("当前任职", "CityU CS 讲座教授，并任 Centre for Decentralized Trust Computing 主任。", p.jia), f("教育与学术训练", "在 USTC 获学士、硕士，在 University of Tokyo 获 DSc。", p.jia), f("研究主线", "研究云与分布式系统、网络安全、隐私和可信机器学习。", p.jia), f("项目关系", "CityU 项目页将其与 Irwin King 列为 Trustworthy Large Language Models 项目共同研究者。", r.jiaProject)] }),
  person({ id: "zhenliang-lu-cityu-p0-r5", name: "Zhenliang Lu", chinese: "卢振亮", role: "Professor", institution: "CityU", region: "Hong Kong", area: "Distributed Computing · Blockchain · Cryptography", tags: ["Distributed Computing", "Blockchain", "Cryptography", "DeFi"], summary: "CityU CS 教授，研究区块链、分布式计算、密码学和去中心化金融。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/zhenliang-lu.png", profile: p.lu, roster: rosters.cityu, x: 780, y: 130, facts: [f("当前任职", "CityU CS 教授并公开招收博士生。", p.lu), f("教育与学术训练", "在 Hefei University of Technology 获学士、硕士，在 University of Sydney 获博士。", p.lu), f("任职轨迹", "加入 CityU 前曾在 NTU 与 University of Sydney 从事博士后研究。", p.lu), f("研究主线", "研究共识、区块链、分布式计算、密码学与 DeFi。", p.lu), f("学生体系", "CityU Scholars 列出 Liudan Su 等受指导研究者。", p.lu)] }),
  person({ id: "dapeng-wu-cityu-p0-r5", name: "Dapeng Wu", chinese: "吴大鹏", role: "Chair Professor", institution: "CityU", region: "Hong Kong", area: "Network Science · Machine Learning · Multimedia", tags: ["Network Science", "Machine Learning", "NLP", "Computer Vision"], summary: "CityU 讲座教授，研究网络科学、机器学习、NLP、视觉与多媒体系统。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/dapeng-wu.png", profile: p.wu, roster: rosters.cityu, x: 990, y: 130, facts: [f("当前任职", "CityU CS 与数据科学讲座教授。", p.wu), f("教育与学术训练", "在 HUST 获学士、BUPT 获硕士、Carnegie Mellon University 获 ECE 博士。", p.wu), f("研究主线", "研究网络科学、机器学习、自然语言处理、计算机视觉、无线和多媒体。", p.wu), f("学生体系", "CityU Scholars 列出 Guanzhi Deng 等博士生。", p.wu)] }),
  person({ id: "qingchuan-zhao-cityu-p0-r5", name: "Qingchuan Zhao", chinese: "赵晴川", role: "Assistant Professor", institution: "CityU", region: "Hong Kong", area: "AI Security · Systems Security · Privacy", tags: ["AI Security", "Systems Security", "Privacy", "AR/VR Security"], summary: "CityU CS 助理教授，研究 AI/系统安全、隐私和 AR/VR 安全。", stage: "emerging", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/qingchuan-zhao.png", profile: p.zhao, roster: rosters.cityu, x: 1200, y: 130, facts: [f("当前任职", "CityU CS 助理教授。", p.zhao), f("教育与学术训练", "在 SCUT 获工学学士、University of Florida 获硕士、Ohio State University 获博士。", p.zhao), f("研究主线", "研究 AI 与系统安全、隐私、移动和 AR/VR 安全。", p.zhao), f("学生体系", "CityU Scholars 列出 Xiaoyan Yan 等受指导研究者。", p.zhao)] }),
  person({ id: "kening-zhu-cityu-p0-r5", name: "Kening Zhu", chinese: "朱克宁", role: "Associate Professor", institution: "CityU", region: "Hong Kong", area: "Human-Computer Interaction · Multimodal Interaction · XR", tags: ["HCI", "Multimodal Interaction", "XR", "Wearables"], summary: "CityU SCM/CS 副教授，研究多模态交互、移动手势、可穿戴与 XR。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/kening-zhu.png", profile: p.zhu, roster: rosters.cityu, x: 1410, y: 130, facts: [f("当前任职", "CityU School of Creative Media 副教授，并与计算机系联合任职。", p.zhu), f("教育与学术训练", "在 HUST 获学士，在 NUS 获博士。", p.zhu), f("研究主线", "研究多模态人机交互、移动手势、VR/AR/MR 和可穿戴设备。", p.zhu), f("学生体系", "CityU Scholars 列出 Haichen Gao 等博士生。", p.zhu)] }),
  person({ id: "changwen-chen-polyu-p0-r5", name: "Changwen Chen", chinese: "陈长汶", role: "Chair Professor · Interim Dean", institution: "PolyU", region: "Hong Kong", area: "Visual Computing · Multimedia · Artificial Intelligence", tags: ["Computer Vision", "Multimedia", "Visual Computing", "AI"], summary: "PolyU 视觉计算讲座教授，长期研究视觉计算、多媒体通信与人工智能。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/changwen-chen.png", profile: p.chen, roster: rosters.polyu, extra: [r.chenPaper], x: 250, y: 390, facts: [f("当前任职", "PolyU 视觉计算讲座教授并担任学院管理职务。", p.chen), f("教育与学术训练", "在 USTC 获学士、USC 获硕士、University of Illinois Urbana-Champaign 获博士。", p.chen), f("任职轨迹", "曾在 University of Rochester、University at Buffalo 与 CUHK-Shenzhen 等机构任职。", p.chen), f("研究主线", "研究视觉计算、多媒体通信与人工智能。", p.chen), f("合作关系", "CVF 的 CVPR 2024 论文页记录其与 Tao Mei 等共同署名 SD-DiT。", r.chenPaper)] }),
  person({ id: "xiapu-luo-polyu-p0-r5", name: "Xiapu Luo", chinese: "罗霞普", role: "Professor", institution: "PolyU", region: "Hong Kong", area: "Cybersecurity · Blockchain Security · Mobile Security", tags: ["Cybersecurity", "Blockchain Security", "Mobile Security", "Software Security"], summary: "PolyU COMP 教授，研究区块链、智能合约、移动和软件系统安全。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/xiapu-luo.png", profile: p.luo, roster: rosters.polyu, x: 490, y: 390, facts: [f("当前任职", "PolyU COMP 教授。", p.luo), f("教育与学术训练", "在 PolyU 获计算机科学博士。", p.luo), f("博士后训练", "官方简介记录其在 Georgia Tech 由 Wenke Lee 指导博士后研究。", p.luo), f("研究主线", "研究区块链与智能合约安全、移动安全、恶意软件和软件安全。", p.luo)] }),
  person({ id: "jungpil-hahn-nus-p0-r5", name: "Jungpil Hahn", role: "Provost's Chair Professor · FinTech Lab Director", institution: "NUS", region: "Singapore", area: "Information Systems · Human-AI Interaction · FinTech", tags: ["Information Systems", "Human-AI Interaction", "FinTech", "Open Innovation"], summary: "NUS 计算学院 Provost's Chair Professor、FinTech Lab 主任，研究信息系统、开放创新和人机交互。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/jungpil-hahn.png", profile: p.hahn, roster: rosters.nus, x: 730, y: 390, facts: [f("当前任职", "NUS Provost's Chair Professor、FinTech Lab 主任。", p.hahn), f("教育与学术训练", "在 Yonsei University 获 BBA、MBA，在 University of Minnesota 获 Information and Decision Sciences 博士。", p.hahn), f("研究主线", "研究开放创新、组织学习、软件过程与人机交互。", p.hahn), f("学生去向", "NUS 官方个人页列出博士校友 Muhammad Nauman Shahid 及其毕业后 NLP Scientist-II 去向。", p.hahn)] }),
  person({ id: "wei-tsang-ooi-nus-p0-r5", name: "Ooi Wei Tsang", role: "Associate Professor · IPAL Co-Director", institution: "NUS", region: "Singapore", area: "Interactive Multimedia · Intelligent Systems · Edge AI", tags: ["Multimedia", "Intelligent Systems", "Edge AI", "3D Gaussian Splatting"], summary: "NUS Computing 副教授、IPAL 联合主任，研究交互式多媒体、智能系统与人机协同。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/wei-tsang-ooi.png", profile: p.ooi, roster: rosters.nus, extra: [r.ooiStudents], x: 970, y: 390, facts: [f("当前任职", "NUS Computing 副教授，并任 IPAL 联合主任。", p.ooi), f("教育与学术训练", "在 NUS 获计算机科学学士，在 Cornell University 获博士。", p.ooi), f("研究主线", "研究交互式多媒体、智能系统、3D Gaussian Splatting 与 human-AI systems。", p.ooi), f("学生去向", "NUS 学生页记录 Zhenwei Tan 的首份工作为 ByteDance China。", r.ooiStudents)] }),
  person({ id: "jin-song-dong-nus-p0-r5", name: "Jin Song Dong", role: "Professor", institution: "NUS", region: "Singapore", area: "Formal Methods · Trusted AI · Software Engineering", tags: ["Formal Methods", "Trusted AI", "Software Engineering", "LLM Code Synthesis"], summary: "NUS Computing 教授，以形式化方法连接可信机器学习、软件安全与 LLM 代码生成。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/jin-song-dong.png", profile: p.dong, roster: rosters.nus, extra: [p.dongHome], x: 1210, y: 390, facts: [f("当前任职", "NUS Computing 教授。", p.dong), f("教育与学术训练", "在 University of Queensland 获信息技术学士与博士。", p.dong), f("研究主线", "研究形式化方法、系统安全、概率推理、可信机器学习与 verified LLM code synthesis。", p.dong), f("学生体系", "NUS 本人主页逐名列出博士校友，并记录 Jun Sun 为其 2006 年博士毕业生。", p.dongHome)] }),
  person({ id: "dacheng-tao-ntu-p0-r5", name: "Dacheng Tao", chinese: "陶大程", role: "Distinguished University Professor", institution: "NTU", region: "Singapore", area: "Machine Learning · Computer Vision · Data Science", tags: ["Machine Learning", "Computer Vision", "Data Science", "Foundation Models"], summary: "NTU Distinguished University Professor，研究机器学习、计算机视觉与数据科学。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/dacheng-tao.png", profile: p.tao, roster: rosters.ntu, extra: [p.taoCv], x: 1450, y: 390, facts: [f("当前任职", "NTU Distinguished University Professor。", p.tao), f("教育与学术训练", "在 USTC 获工学学士、CUHK 获 MPhil、Birkbeck University of London 获博士。", p.taoCv), f("师承关系", "University of Sydney 官方 CV 列 Xiaoou Tang 为其 MPhil 导师。", p.taoCv), f("研究主线", "研究机器学习、计算机视觉、数据科学及其数学与统计基础。", p.tao)] }),
  person({ id: "chunyan-miao-ntu-p0-r5", name: "Chun Yan Miao", chinese: "苗春燕", role: "President's Chair Professor · School Chair", institution: "NTU", region: "Singapore", area: "Human-Centred AI · Multi-agent Systems · Health AI", tags: ["Human-Centred AI", "Multi-agent Systems", "Health AI", "Education AI"], summary: "NTU President's Chair Professor、CCDS 院长，研究以人为本的 AI、多智能体与健康教育应用。", stage: "senior", portrait: "portraits/candidate-p0-hk-sg-fifth-round-2026/chunyan-miao.png", profile: p.miao, roster: rosters.ntu, extra: [r.miaoPaper], x: 1690, y: 390, facts: [f("当前任职", "NTU President's Chair Professor，并任 College of Computing and Data Science 院长。", p.miao), f("教育与学术训练", "在 NTU 获计算机工程博士，后在 Simon Fraser University 从事博士后研究。", p.miao), f("研究主线", "研究以人为本的 AI、多智能体系统及其在健康、老龄化和教育中的应用。", p.miao), f("合作关系", "NTU 机构仓储的 WWW 2025 MedRAG 论文列出其与 Xuejiao Zhao 等共同署名。", r.miaoPaper)] }),
];

const support = (id: string, name: string, role: string, institution: Person["institution"], region: Person["region"], area: string, proof: Source, summary: string, x: number): Person => ({ id, name, role, institution, region, area, tags: [area], summary, category: "adjacent", primary: false, stage: "adjacent", x, y: 720, sources: [proof], facts: [f("关系证据", summary, proof)] });
export const candidatePriorityP0HkSgFifthRoundSupportingPeople2026: Person[] = [
  support("yuxin-du-cityu-p0-r5-support", "Yuxin Du", "PhD Student", "CityU", "Hong Kong", "Knowledge Graph · RAG", p.guan, "CityU Scholars 将 Yuxin Du 列为 Nan Guan 的受指导博士生。", 250),
  support("aikaterini-mitrokotsa-p0-r5-support", "Aikaterini Mitrokotsa", "Research collaborator", "External", "Europe", "Cybersecurity", r.hanckePaper, "CityU 论文页记录其与 Gerhard Hancke 共同署名。", 390),
  support("liudan-su-cityu-p0-r5-support", "Liudan Su", "Research student", "CityU", "Hong Kong", "Distributed Computing", p.lu, "CityU Scholars 将 Liudan Su 列为 Zhenliang Lu 的受指导研究者。", 530),
  support("guanzhi-deng-cityu-p0-r5-support", "Guanzhi Deng", "PhD Student", "CityU", "Hong Kong", "NLP · Large Language Models", p.wu, "CityU Scholars 将 Guanzhi Deng 列为 Dapeng Wu 的博士生。", 670),
  support("xiaoyan-yan-cityu-p0-r5-support", "Xiaoyan Yan", "Research student", "CityU", "Hong Kong", "AI Security", p.zhao, "CityU Scholars 将 Xiaoyan Yan 列为 Qingchuan Zhao 的受指导研究者。", 810),
  support("haichen-gao-cityu-p0-r5-support", "Haichen Gao", "PhD Student", "CityU", "Hong Kong", "Human-Computer Interaction", p.zhu, "CityU Scholars 将 Haichen Gao 列为 Kening Zhu 的博士生。", 950),
  support("tao-mei-p0-r5-support", "Tao Mei", "Research collaborator", "External", "Mainland China", "Computer Vision", r.chenPaper, "CVF 论文页记录其与 Changwen Chen 共同署名。", 1090),
  support("muhammad-nauman-shahid-p0-r5-support", "Muhammad Nauman Shahid", "PhD alumnus · NLP Scientist-II", "External", "Singapore", "NLP", p.hahn, "NUS 官方个人页记录其为 Jungpil Hahn 博士校友并进入 Supportiv。", 1230),
  support("zhenwei-tan-p0-r5-support", "Zhenwei Tan", "MComp alumnus · ByteDance", "External", "Singapore", "Edge AI", r.ooiStudents, "NUS 学生页记录其由 Ooi Wei Tsang 指导并进入 ByteDance China。", 1370),
  support("xuejiao-zhao-p0-r5-support", "Xuejiao Zhao", "Research collaborator", "NTU", "Singapore", "Medical AI", r.miaoPaper, "NTU 机构仓储论文记录其与 Chun Yan Miao 共同署名 MedRAG。", 1510),
];

export const candidatePriorityP0HkSgFifthRoundRelationships2026: Relationship[] = [
  { id: "p0-hksg-r5-guan-du", from: "nan-guan-cityu-p0-r5", to: "yuxin-du-cityu-p0-r5-support", type: "lineage", subtype: "phd_adviser", label: "博士指导", evidence: "CityU Scholars 的 supervised researchers 区将 Yuxin Du 标为博士生。", evidenceObject: "Yuxin Du · Doctor of Philosophy (Student)", source: p.guan, verified: true },
  { id: "p0-hksg-r5-hancke-mitrokotsa", from: "gerhard-hancke-cityu-p0-r5", to: "aikaterini-mitrokotsa-p0-r5-support", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "CityU 论文页完整作者列表包含双方。", evidenceObject: "Tangible Security: Survey of Methods Supporting Secure Ad-hoc Connects", source: r.hanckePaper, verified: true },
  { id: "p0-hksg-r5-jia-king", from: "xiaohua-jia-cityu-p0-r5", to: "irwin-king", type: "collaboration", subtype: "joint_project", label: "共同项目", evidence: "CityU 项目页列出双方为共同研究者。", evidenceObject: "Trustworthy Large Language Models: A Multifaceted Strategy for Truthfulness, Fairness, and Privacy Preservation", source: r.jiaProject, verified: true, recentYear: 2025 },
  { id: "p0-hksg-r5-lu-su", from: "zhenliang-lu-cityu-p0-r5", to: "liudan-su-cityu-p0-r5-support", type: "lineage", subtype: "phd_adviser", label: "博士指导", evidence: "CityU Scholars 将 Liudan Su 列在 Zhenliang Lu 的 supervised researchers 中。", evidenceObject: "Liudan Su · supervised researcher", source: p.lu, verified: true },
  { id: "p0-hksg-r5-wu-deng", from: "dapeng-wu-cityu-p0-r5", to: "guanzhi-deng-cityu-p0-r5-support", type: "lineage", subtype: "phd_adviser", label: "博士指导", evidence: "CityU Scholars 将 Guanzhi Deng 标为博士生。", evidenceObject: "Guanzhi Deng · Doctor of Philosophy (Student)", source: p.wu, verified: true },
  { id: "p0-hksg-r5-zhao-yan", from: "qingchuan-zhao-cityu-p0-r5", to: "xiaoyan-yan-cityu-p0-r5-support", type: "lineage", subtype: "phd_adviser", label: "研究生指导", evidence: "CityU Scholars 将 Xiaoyan Yan 列在 Qingchuan Zhao 的 supervised researchers 中。", evidenceObject: "Xiaoyan Yan · supervised researcher", source: p.zhao, verified: true },
  { id: "p0-hksg-r5-zhu-gao", from: "kening-zhu-cityu-p0-r5", to: "haichen-gao-cityu-p0-r5-support", type: "lineage", subtype: "phd_adviser", label: "博士指导", evidence: "CityU Scholars 将 Haichen Gao 标为博士生。", evidenceObject: "Haichen Gao · Doctor of Philosophy (Student)", source: p.zhu, verified: true },
  { id: "p0-hksg-r5-chen-mei", from: "changwen-chen-polyu-p0-r5", to: "tao-mei-p0-r5-support", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "CVF 论文页完整作者列表包含双方。", evidenceObject: "SD-DiT: Unleashing the Power of Self-supervised Discrimination in Diffusion Transformer · CVPR 2024", source: r.chenPaper, verified: true, recentYear: 2024 },
  { id: "p0-hksg-r5-lee-luo", from: "wenke-lee-p0-r4-support", to: "xiapu-luo-polyu-p0-r5", type: "talent", subtype: "postdoc_mentor", label: "博士后导师", evidence: "PolyU 官方简介明确记录 Xiapu Luo 在 Georgia Tech 的博士后研究由 Wenke Lee 指导。", evidenceObject: "Xiapu Luo · Georgia Tech postdoctoral research", source: p.luo, verified: true },
  { id: "p0-hksg-r5-hahn-shahid", from: "jungpil-hahn-nus-p0-r5", to: "muhammad-nauman-shahid-p0-r5-support", type: "talent", subtype: "career_movement", label: "博士校友去向", evidence: "NUS 官方个人页逐名列出该博士校友及其毕业后职位。", evidenceObject: "Muhammad Nauman Shahid · PhD 2024 · NLP Scientist-II at Supportiv", source: p.hahn, verified: true, recentYear: 2024 },
  { id: "p0-hksg-r5-ooi-tan", from: "wei-tsang-ooi-nus-p0-r5", to: "zhenwei-tan-p0-r5-support", type: "talent", subtype: "career_movement", label: "学生产业去向", evidence: "NUS 学生页记录 Zhenwei Tan 的论文与首份工作。", evidenceObject: "Zhenwei Tan · Edge AI for Video Surveillance · ByteDance China", source: r.ooiStudents, verified: true, recentYear: 2021 },
  { id: "p0-hksg-r5-dong-sun", from: "jin-song-dong-nus-p0-r5", to: "jun-sun-smu-p0-2026", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Jin Song Dong 的 NUS 本人主页将 Jun Sun 列为 2006 年博士毕业生。", evidenceObject: "Jun Sun · PhD 2006", source: p.dongHome, verified: true, recentYear: 2006 },
  { id: "p0-hksg-r5-tang-tao", from: "xiaoou-tang-cuhk", to: "dacheng-tao-ntu-p0-r5", type: "lineage", subtype: "master_adviser", label: "MPhil 导师", evidence: "University of Sydney 官方 CV 列 Xiaoou Tang 为 Dacheng Tao 的 CUHK MPhil supervisor。", evidenceObject: "MPhil in Computer Science · CUHK · supervisor Xiaoou Tang", source: p.taoCv, verified: true, endYear: 2004 },
  { id: "p0-hksg-r5-miao-zhao", from: "chunyan-miao-ntu-p0-r5", to: "xuejiao-zhao-p0-r5-support", type: "collaboration", subtype: "publication", label: "论文合作", evidence: "NTU 机构仓储的论文完整作者列表包含双方。", evidenceObject: "MedRAG: Enhancing Retrieval-augmented Generation with Knowledge Graph-Elicited Reasoning for Healthcare Copilot · WWW 2025", source: r.miaoPaper, verified: true, recentYear: 2025 },
];

export const candidatePriorityP0HkSgFifthRoundRosterPromotions2026 = [
  [rosters.cityu.url, "Prof GUAN, Nan 關楠", "nan-guan-cityu-p0-r5"], [rosters.cityu.url, "Prof HANCKE, Gerhard Petrus", "gerhard-hancke-cityu-p0-r5"], [rosters.cityu.url, "Prof JIA, Xiaohua 賈小華", "xiaohua-jia-cityu-p0-r5"], [rosters.cityu.url, "Prof LU, Zhenliang 盧振亮", "zhenliang-lu-cityu-p0-r5"], [rosters.cityu.url, "Prof WU, Dapeng 吳大鵬", "dapeng-wu-cityu-p0-r5"], [rosters.cityu.url, "Prof ZHAO, Qingchuan 趙晴川", "qingchuan-zhao-cityu-p0-r5"], [rosters.cityu.url, "Prof ZHU, Kening 朱克宁", "kening-zhu-cityu-p0-r5"], [rosters.polyu.url, "Prof. CHEN Changwen", "changwen-chen-polyu-p0-r5"], [rosters.polyu.url, "Prof. LUO Xiapu Daniel", "xiapu-luo-polyu-p0-r5"], [rosters.nus.url, "Jungpil HAHN", "jungpil-hahn-nus-p0-r5"], [rosters.nus.url, "OOI Wei Tsang", "wei-tsang-ooi-nus-p0-r5"], [rosters.nus.url, "DONG Jin Song", "jin-song-dong-nus-p0-r5"], [rosters.ntu.url, "Prof Tao Dacheng", "dacheng-tao-ntu-p0-r5"], [rosters.ntu.url, "Prof Miao Chun Yan", "chunyan-miao-ntu-p0-r5"],
].map(([unitUrl, rosterName, atlasPersonId]) => ({ unitUrl, rosterName, atlasPersonId }));

export const People = candidatePriorityP0HkSgFifthRoundPeople2026;
export const SupportingPeople = candidatePriorityP0HkSgFifthRoundSupportingPeople2026;
export const Relationships = candidatePriorityP0HkSgFifthRoundRelationships2026;
export const RosterPromotions = candidatePriorityP0HkSgFifthRoundRosterPromotions2026;
