import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const src = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const f = (label: string, value: string, source: Source) => ({ label, value, source });
const s = {
  kundaje: src("Stanford CS · Anshul Kundaje", "https://www.cs.stanford.edu/people/anshul-kundaje", "official", "Current joint Genetics and Computer Science appointment"),
  kundajeProfile: src("Stanford Profiles · Anshul Kundaje", "https://profiles.stanford.edu/anshul-kundaje", "official", "Machine learning for regulatory genomics, lab leadership and trainee destinations"),
  kundajeTraining: src("Stanford CEHG speaker biography · Anshul Kundaje", "https://cehg.stanford.edu/sites/g/files/sbiybj27086/files/media/file/symp14_program_10_jan_2014.pdf", "official", "Columbia doctorate with Christina Leslie and Stanford postdoctoral training with Serafim Batzoglou and Arend Sidow"),
  kundajeStudent: src("Avanti Shrikumar · Stanford-hosted CV", "https://web.stanford.edu/~avanti/resume.html", "cv", "Anshul Kundaje identified as PhD adviser"),
  vanRoy: src("Stanford Profiles · Benjamin Van Roy", "https://profiles.stanford.edu/benjamin-van-roy", "official", "Current Stanford appointment, advisees and professional education"),
  vanRoyHome: src("Benjamin Van Roy · Stanford personal profile", "https://web.stanford.edu/~bvr/", "profile", "MIT degrees, John Tsitsiklis supervision and industry founding roles"),
  vanRoyThesis: src("Benjamin Van Roy · MIT doctoral thesis", "https://web.stanford.edu/~bvr/pubs/thesis.pdf", "publication", "John N. Tsitsiklis named as thesis supervisor"),
  vanRoyStudents: src("Benjamin Van Roy · Stanford student list", "https://web.stanford.edu/~bvr/students.html", "profile", "Current and former doctoral students and destinations"),
  adeli: src("Stanford Medicine · Ehsan Adeli", "https://med.stanford.edu/profiles/ehsan-adeli", "official", "Current research-faculty appointments and translational AI programme"),
  adeliHome: src("Ehsan Adeli · Stanford personal profile", "https://stanford.edu/~eadeli/", "profile", "STAI Lab leadership, computer vision and medical AI research"),
  adeliProfile: src("Stanford Profiles · Ehsan Adeli", "https://profiles.stanford.edu/ehsan-adeli", "official", "Named doctoral and postdoctoral advisees"),
  vitercik: src("Stanford CS · Ellen Vitercik", "https://www.cs.stanford.edu/people/ellen-vitercik", "official", "Current joint Computer Science and MS&E appointment"),
  vitercikBio: src("Stanford HAI · Ellen Vitercik", "https://hai.stanford.edu/people/ellen-vitercik", "official", "CMU co-advisers, Berkeley postdoctoral hosts and machine-learning research"),
  vitercikProfile: src("Stanford Profiles · Ellen Vitercik", "https://profiles.stanford.edu/ellen-vitercik", "official", "Current advisees and appointments"),
};

const portraits: Record<string, Source> = {
  "anshul-kundaje": src("Stanford AI portrait · Anshul Kundaje", "https://ai.stanford.edu/wp-content/uploads/2020/09/Anshul-Kundaje.jpg", "official", "Official university portrait"),
  "benjamin-van-roy": src("Stanford Profiles portrait · Benjamin Van Roy", "https://profiles.stanford.edu/proxy/api/cap/profiles/24760/resources/profilephoto/350x522.1787872051.jpg", "official", "Official university portrait"),
  "ehsan-adeli": src("Stanford AI portrait · Ehsan Adeli", "https://ai.stanford.edu/wp-content/uploads/2026/03/myphoto0011_0.jpg", "official", "Official university portrait"),
  "ellen-vitercik": src("Stanford AI portrait · Ellen Vitercik", "https://ai.stanford.edu/wp-content/uploads/2022/10/vitercik_headshot-scaled-e1665693209223.jpg", "official", "Official university portrait"),
};
type Seed = { id: string; name: string; role: string; area: string; tags: string[]; summary: string; stage: Person["stage"]; facts: Person["facts"]; sources: Source[]; file: string; x: number };
const p = (x: Seed): Person => ({ ...x, institution: "Stanford", region: "United States", category: "core", status: "current independent PI · official faculty profile verified", primary: true, y: 120, introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-us-canada-stanford-tail-2026/${x.file}.jpg`, alt: `${x.name} 官方头像`, source: portraits[x.file] } });

export const candidatePriorityP0UsCanadaReadyBatch8People2026: Person[] = [
  p({ id: "anshul-kundaje-stanford-p0-b8", name: "Anshul Kundaje", role: "Associate Professor of Genetics and Computer Science", area: "Machine Learning for Genomics · Regulatory AI", tags: ["机器学习", "基因组学", "可解释 AI", "生物医学"], summary: "用深度学习解码 DNA、RNA 与蛋白质调控语言的 Stanford Kundaje Lab 负责人。", stage: "senior", x: 120, file: "anshul-kundaje", sources: [s.kundaje, s.kundajeProfile, s.kundajeTraining, s.kundajeStudent], facts: [f("当前任职", "Stanford Genetics 与 Computer Science 副教授。", s.kundajeProfile), f("教育与学术训练", "Columbia Computer Science PhD（2008），在 Christina Leslie 实验室完成；随后在 Stanford 跟随 Serafim Batzoglou 与 Arend Sidow 从事博士后研究。", s.kundajeTraining), f("研究主线", "机器学习驱动的调控基因组学，重点解码 DNA、RNA 和蛋白质序列。", s.kundajeProfile), f("学生体系", "Stanford Profiles 记录其指导超过 35 名研究生和博士后，去向包括 CMU、NVIDIA、Genentech 与 Illumina。", s.kundajeProfile), f("可核验师承", "Avanti Shrikumar 的 Stanford-hosted CV 明确列 Anshul Kundaje 为博士导师。", s.kundajeStudent)] }),
  p({ id: "benjamin-van-roy-stanford-p0-b8", name: "Benjamin Van Roy", role: "Professor of Management Science and Engineering", area: "Reinforcement Learning · AI Alignment · Sequential Decision Making", tags: ["强化学习", "AI 对齐", "序列决策", "智能体"], summary: "研究强化学习、智能体与对齐的 Stanford 教授，并创立 DeepMind 首个美国研究团队。", stage: "senior", x: 300, file: "benjamin-van-roy", sources: [s.vanRoy, s.vanRoyHome, s.vanRoyThesis, s.vanRoyStudents], facts: [f("当前任职", "Stanford Professor of Management Science and Engineering，并兼任 Electrical Engineering、Computer Science 等单位。", s.vanRoyHome), f("教育与学术训练", "MIT Computer Science and Engineering SB、EECS SM 与 PhD（1998）。", s.vanRoy), f("博士师承", "MIT 博士论文明确列 John N. Tsitsiklis 为 thesis supervisor。", s.vanRoyThesis), f("研究主线", "强化学习、AI 对齐和序列决策。", s.vanRoyHome), f("产业连接", "创立 DeepMind 首个美国研究团队 Efficient Agent Team，并创办 Enuvis；公开学生页记录校友流向 Google DeepMind、OpenAI、xAI、Meta 等。", s.vanRoyHome)] }),
  p({ id: "ehsan-adeli-stanford-p0-b8", name: "Ehsan Adeli", role: "Assistant Professor (Research) · Director, STAI Lab", area: "Medical AI · Computer Vision · Computational Neuroscience", tags: ["医疗 AI", "计算机视觉", "计算神经科学", "多模态"], summary: "领导 Stanford Translational AI Lab、把视觉和多模态方法用于医学与心理健康的独立研究 PI。", stage: "emerging", x: 480, file: "ehsan-adeli", sources: [s.adeli, s.adeliHome, s.adeliProfile], facts: [f("当前任职", "Stanford Psychiatry and Behavioral Sciences Assistant Professor (Research)，并兼任 Computer Science 与 Biomedical Data Science。", s.adeli), f("教育与学术训练", "获得人工智能与计算机视觉博士学位，随后接受生物医学影像与计算神经科学的博士后训练。", s.adeli), f("研究主线", "医疗与心理健康中的转化 AI、计算机视觉、神经影像和环境智能。", s.adeliHome), f("团队领导", "任 STAI Lab 主任，并联合领导 Stanford AI for Mental Health Initiative。", s.adeliHome), f("公开指导", "Stanford Profiles 列出 Favour Nerrise、Karan Singh 等博士生以及多位博士后。", s.adeliProfile)] }),
  p({ id: "ellen-vitercik-stanford-p0-b8", name: "Ellen Vitercik", role: "Assistant Professor of MS&E and Computer Science", area: "Machine Learning Theory · Algorithm Design · Economics and Computation", tags: ["机器学习理论", "算法", "计算经济学", "优化"], summary: "研究机器学习理论、算法设计与经济计算交叉的 Stanford 新生代 PI。", stage: "emerging", x: 660, file: "ellen-vitercik", sources: [s.vitercik, s.vitercikBio, s.vitercikProfile], facts: [f("当前任职", "Stanford Management Science and Engineering 与 Computer Science 助理教授。", s.vitercik), f("教育与学术训练", "Carnegie Mellon Computer Science PhD，由 Maria-Florina Balcan 与 Tuomas Sandholm 共同指导；随后在 UC Berkeley 跟随 Michael Jordan 与 Jennifer Chayes 做 Miller Fellow。", s.vitercikBio), f("研究主线", "机器学习理论、算法设计与经济学和计算的交叉。", s.vitercikBio), f("学生体系", "Stanford Profiles 公开列出其博士论文读者与博士后指导记录。", s.vitercikProfile)] }),
];

export const candidatePriorityP0UsCanadaReadyBatch8SupportingPeople2026: Person[] = [
  { id: "avanti-shrikumar-lineage-p0-b8", name: "Avanti Shrikumar", role: "Researcher", institution: "Stanford", region: "United States", area: "Interpretable Machine Learning · Regulatory Genomics", tags: ["博士生", "可解释 AI"], summary: "Anshul Kundaje 的 Stanford 博士生；作为关系证据端点收录。", stage: "adjacent", category: "historical", status: "supporting student node · relationship evidence only", sources: [s.kundajeStudent], x: 120, y: 220, primary: false, lastVerifiedAt: checkedAt },
  { id: "john-tsitsiklis-lineage-p0-b8", name: "John N. Tsitsiklis", role: "Clarence J. Lebel Professor", institution: "MIT", region: "United States", area: "Optimization · Control · Reinforcement Learning", tags: ["博士导师", "优化"], summary: "Benjamin Van Roy 的 MIT 博士导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [s.vanRoyThesis], x: 300, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "nina-balcan-lineage-p0-b8", name: "Maria-Florina Balcan", role: "Professor", institution: "CMU", region: "United States", area: "Machine Learning Theory", tags: ["博士导师", "机器学习理论"], summary: "Ellen Vitercik 的 CMU 博士共同导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [s.vitercikBio], x: 620, y: 20, primary: false, lastVerifiedAt: checkedAt },
  { id: "tuomas-sandholm-lineage-p0-b8", name: "Tuomas Sandholm", role: "Professor", institution: "CMU", region: "United States", area: "AI · Game Theory · Multi-agent Systems", tags: ["博士导师", "人工智能"], summary: "Ellen Vitercik 的 CMU 博士共同导师。", stage: "senior", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [s.vitercikBio], x: 700, y: 20, primary: false, lastVerifiedAt: checkedAt },
];
export const candidatePriorityP0UsCanadaReadyBatch8Relationships2026: Relationship[] = [
  { id: "candidate-p0-usca-b8-kundaje-shrikumar", from: "anshul-kundaje-stanford-p0-b8", to: "avanti-shrikumar-lineage-p0-b8", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Avanti Shrikumar 的 Stanford-hosted CV 明确列 Anshul Kundaje 为博士导师。", source: s.kundajeStudent, verified: true },
  { id: "candidate-p0-usca-b8-tsitsiklis-vanroy", from: "john-tsitsiklis-lineage-p0-b8", to: "benjamin-van-roy-stanford-p0-b8", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Benjamin Van Roy 的 MIT 博士论文明确列 John N. Tsitsiklis 为 thesis supervisor。", source: s.vanRoyThesis, verified: true },
  { id: "candidate-p0-usca-b8-balcan-vitercik", from: "nina-balcan-lineage-p0-b8", to: "ellen-vitercik-stanford-p0-b8", type: "lineage", subtype: "co_adviser", label: "共同博士导师", evidence: "Stanford HAI 官方简介明确 Ellen Vitercik 的 CMU 博士由 Maria-Florina Balcan 与 Tuomas Sandholm 共同指导。", source: s.vitercikBio, verified: true },
  { id: "candidate-p0-usca-b8-sandholm-vitercik", from: "tuomas-sandholm-lineage-p0-b8", to: "ellen-vitercik-stanford-p0-b8", type: "lineage", subtype: "co_adviser", label: "共同博士导师", evidence: "Stanford HAI 官方简介明确 Ellen Vitercik 的 CMU 博士由 Maria-Florina Balcan 与 Tuomas Sandholm 共同指导。", source: s.vitercikBio, verified: true },
];
export const candidatePriorityP0UsCanadaReadyBatch8GroupMembers2026: GroupMember[] = [
  { id: "candidate-p0-usca-b8-kundaje-avanti", teacherId: "anshul-kundaje-stanford-p0-b8", name: "Avanti Shrikumar", role: "Former PhD student", source: s.kundajeStudent },
  { id: "candidate-p0-usca-b8-vanroy-henrik", teacherId: "benjamin-van-roy-stanford-p0-b8", name: "Henrik Marklund", role: "Current PhD student", source: s.vanRoyStudents },
  { id: "candidate-p0-usca-b8-adeli-favour", teacherId: "ehsan-adeli-stanford-p0-b8", name: "Favour Nerrise", role: "Doctoral advisee", source: s.adeliProfile },
  { id: "candidate-p0-usca-b8-vitercik-postdocs", teacherId: "ellen-vitercik-stanford-p0-b8", name: "Vitercik group advisees", role: "Doctoral and postdoctoral researchers", source: s.vitercikProfile },
];
export const candidatePriorityP0UsCanadaReadyBatch8Placements2026: StudentPlacement[] = [{ id: "candidate-p0-usca-b8-vanroy-zhengwen", student: "Zheng Wen", teacherId: "benjamin-van-roy-stanford-p0-b8", company: "OpenAI", role: "Researcher", kind: "reported", degree: "PhD", sector: "industry", note: "Benjamin Van Roy 的 Stanford 学生页将 Zheng Wen 列为 2014 博士校友，并记录其去向 OpenAI。", source: s.vanRoyStudents, verifiedAt: checkedAt }];
export const candidatePriorityP0UsCanadaReadyBatch8RosterPromotions2026 = candidatePriorityP0UsCanadaReadyBatch8People2026.map((person) => ({ unitUrl: "https://www.cs.stanford.edu/people/faculty", rosterName: person.name, atlasPersonId: person.id }));
export const people = [...candidatePriorityP0UsCanadaReadyBatch8People2026, ...candidatePriorityP0UsCanadaReadyBatch8SupportingPeople2026];
export const relationships = candidatePriorityP0UsCanadaReadyBatch8Relationships2026;
export const placements = candidatePriorityP0UsCanadaReadyBatch8Placements2026;
export const groupMembers = candidatePriorityP0UsCanadaReadyBatch8GroupMembers2026;
export const rosterPromotions = candidatePriorityP0UsCanadaReadyBatch8RosterPromotions2026;
