import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const src = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const f = (label: string, value: string, source: Source) => ({ label, value, source });
const roster = "https://siebelschool.illinois.edu/about/people/all-faculty/";

const profiles = {
  girish: src("Illinois Siebel School · Girish Chowdhary", `${roster}girishc`, "official", "Current appointment, Georgia Tech education, MIT postdoctoral training and autonomous-systems research"),
  girishLab: src("Illinois DASLAB", "http://daslab.illinois.edu", "official", "Laboratory leadership, current students and field-robotics programme"),
  katie: src("Illinois Siebel School · Katie Driggs-Campbell", `${roster}krdc`, "official", "Current appointment, Berkeley doctorate and human-centred autonomy research"),
  katieLab: src("Illinois Human-Centered Autonomy Lab", "https://thehcalab.web.illinois.edu/", "official", "PI leadership and current graduate research team"),
  hauser: src("Illinois Siebel School · Kris Hauser", `${roster}kkhauser`, "official", "Current professorship, Stanford doctorate, robotics research and Waymo consulting"),
  hauserLab: src("Illinois Intelligent Motion Lab", "http://motion.cs.illinois.edu/", "official", "Laboratory leadership, current members and alumni"),
  lavalle: src("Illinois Siebel School · Steven M. LaValle", `${roster}lavalle`, "official", "Current professorship, Illinois doctorate and robotics and planning research"),
  lavalleLab: src("Illinois Motion Strategy Lab", "http://msl.cs.uiuc.edu/~lavalle/", "official", "Research programme, publications and student network"),
  liu: src("Illinois Siebel School · Yaoyao Liu", `${roster}lyy`, "official", "Current appointment, MPII doctorate and continual computer-vision research"),
  liuLab: src("Illinois Vision and Learning Group", "https://vision.ischool.illinois.edu/", "official", "Group leadership and current research members"),
  do: src("Illinois Siebel School · Minh N. Do", `${roster}minhdo`, "official", "Current endowed professorship, EPFL doctorate, computational imaging and industrial roles"),
  doHome: src("Minh N. Do · Illinois personal profile", "https://minhdo.ece.illinois.edu", "profile", "Research programme, lab activity and publications"),
  doStudents: src("Minh N. Do · collaborations and students", "https://minhdo.ece.illinois.edu/collaborations/", "profile", "Current graduate students, doctoral alumni, thesis years and public career destinations"),
  zhang: src("Illinois Siebel School · Tong Zhang", `${roster}tozhang`, "official", "Current professorship and machine-learning teaching and research"),
  zhangHome: src("Tong Zhang · personal academic profile", "https://tongzhang-ml.org", "profile", "Cornell and Stanford education, prior HKUST and Rutgers appointments and research programme"),
  zhangGroup: src("Tong Zhang · research group", "https://www.tongzhang-ml.org/group", "profile", "Current doctoral and master students, former group members and public career destinations"),
  warnow: src("Illinois Siebel School · Tandy Warnow", `${roster}warnow`, "official", "Current distinguished chair, Berkeley adviser, USC postdoctoral mentors and computational biology leadership"),
  warnowHome: src("Tandy Warnow · Illinois personal profile", "http://tandy.cs.illinois.edu", "profile", "Publications, students, projects and research programme"),
  yuan: src("Illinois Siebel School · Wenzhen Yuan", `${roster}yuanwz`, "official", "Current faculty listing, MIT doctorate and tactile robotics research"),
  yuanLab: src("Illinois RoboTouch Lab", "https://robotouchlab.com", "official", "Research group, students and tactile-robotics projects"),
  adelsonCv: src("Ted Adelson · MIT Perceptual Science Group CV", "https://persci.mit.edu/people/adelson/curriculum_vitae/", "cv", "Wenzhen Yuan listed among Ted Adelson's doctoral students"),
};

type Seed = { id: string; name: string; role: string; area: string; tags: string[]; summary: string; facts: Person["facts"]; sources: Source[]; stage: Person["stage"]; file: string; profile: Source; x: number };
const p = (x: Seed): Person => ({ id: x.id, name: x.name, role: x.role, institution: "UIUC", region: "United States", area: x.area, tags: x.tags, summary: x.summary, facts: x.facts, sources: x.sources, stage: x.stage, category: "core", status: "current independent PI · official faculty profile verified", primary: true, x: x.x, y: 120, introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-us-canada-uiuc-tail-2026/${x.file}`, alt: `${x.name} 官方头像`, source: src(`Illinois Engineering portrait · ${x.name}`, `https://ws.engr.illinois.edu/directory/viewphoto/${x.profile.url.split("/").pop()}/1200`, "official", "Official university directory portrait") } });

export const candidatePriorityP0UsCanadaReadyBatch7People2026: Person[] = [
  p({ id: "girish-chowdhary-uiuc-p0-b7", name: "Girish Chowdhary", role: "Associate Professor · Director, DASLAB", area: "Autonomous Systems · Field Robotics · Machine Learning", tags: ["自主系统", "机器人", "机器学习", "农业 AI"], summary: "把自主学习和机器人带入农田等真实环境的 UIUC DASLAB 负责人。", stage: "senior", x: 120, file: "girish-chowdhary.jpg", profile: profiles.girish, sources: [profiles.girish, profiles.girishLab], facts: [f("当前任职", "UIUC Agricultural and Biological Engineering 与 Computer Science 副教授。", profiles.girish), f("教育与学术训练", "Georgia Tech M.S.（2008）与 Ph.D.（2010）；MIT LIDS 博士后（2011–2013）。", profiles.girish), f("研究主线", "自主系统、适应控制、机器人学习与田野机器人。", profiles.girishLab), f("公开团队", "DASLAB 官方站列出当前学生与研究项目。", profiles.girishLab)] }),
  p({ id: "katie-driggs-campbell-uiuc-p0-b7", name: "Katie Driggs-Campbell", role: "Assistant Professor · Director, HCAL", area: "Human-Centered Autonomy · Robotics · Safe AI", tags: ["人本自主", "机器人", "安全 AI", "人机交互"], summary: "研究安全、可解释人机协作自主系统的 UIUC Human-Centered Autonomy Lab 负责人。", stage: "emerging", x: 300, file: "katie-driggs-campbell.jpg", profile: profiles.katie, sources: [profiles.katie, profiles.katieLab], facts: [f("当前任职", "UIUC ECE 助理教授，并在 Siebel School 任教师。", profiles.katie), f("教育与学术训练", "Arizona State 电气工程 BSE；UC Berkeley EECS MS（2015）与 PhD（2017）。", profiles.katie), f("研究主线", "人本自主、机器人、安全决策与人机系统。", profiles.katieLab), f("公开团队", "HCAL 官方页公开实验室 PI、学生与研究方向。", profiles.katieLab)] }),
  p({ id: "kris-hauser-uiuc-p0-b7", name: "Kris Hauser", role: "Professor · Director, Intelligent Motion Lab", area: "Robot Planning · Control · Learning", tags: ["机器人", "规划", "控制", "具身智能"], summary: "聚焦复杂真实环境中机器人规划、控制与学习的 UIUC Intelligent Motion Lab 负责人。", stage: "senior", x: 480, file: "kris-hauser.jpg", profile: profiles.hauser, sources: [profiles.hauser, profiles.hauserLab], facts: [f("当前任职", "UIUC Computer Science 教授，并兼任 ECE 与 Mechanical Science and Engineering。", profiles.hauser), f("教育与学术训练", "UC Berkeley 数学与计算机科学双学士；Stanford Computer Science PhD（2008）；UC Berkeley 博士后。", profiles.hauser), f("研究主线", "机器人规划与控制、感知学习、医疗机器人和智能车辆。", profiles.hauser), f("产业连接", "Illinois 官方简介记录其担任 Waymo 顾问。", profiles.hauser), f("公开团队", "Intelligent Motion Lab 页面列出当前成员与校友。", profiles.hauserLab)] }),
  p({ id: "steven-lavalle-uiuc-p0-b7", name: "Steven M. LaValle", role: "Professor · Motion Strategy Lab", area: "Robot Motion Planning · Virtual Reality · Sensing", tags: ["机器人", "运动规划", "虚拟现实", "感知"], summary: "以机器人运动规划与虚拟现实基础方法著称的 UIUC 资深 PI。", stage: "senior", x: 660, file: "steven-lavalle.jpg", profile: profiles.lavalle, sources: [profiles.lavalle, profiles.lavalleLab], facts: [f("当前任职", "UIUC Computer Science 教授。", profiles.lavalle), f("教育与学术训练", "University of Illinois Electrical Engineering PhD（1995）。", profiles.lavalle), f("研究主线", "机器人运动规划、感知、虚拟现实与计算几何。", profiles.lavalleLab), f("公开团队", "Motion Strategy Lab 官方站持续记录研究、论文与学生工作。", profiles.lavalleLab)] }),
  p({ id: "yaoyao-liu-uiuc-p0-b7", name: "Yaoyao Liu", role: "Assistant Professor · Vision and Learning Group", area: "Continual Learning · Computer Vision · Generative Models", tags: ["持续学习", "计算机视觉", "生成模型", "3D 视觉"], summary: "聚焦持续学习、数据高效视觉和生成模型的 UIUC 新生代 PI。", stage: "emerging", x: 840, file: "yaoyao-liu.jpg", profile: profiles.liu, sources: [profiles.liu, profiles.liuLab], facts: [f("当前任职", "UIUC School of Information Sciences 与 CSL 助理教授，并与 Siebel School、ECE 交叉任职。", profiles.liu), f("教育与学术训练", "Tianjin University 学士；Max Planck Institute for Informatics Computer Science PhD。", profiles.liu), f("研究主线", "持续学习、小样本学习、生成模型、3D 几何与医学影像。", profiles.liu), f("公开团队", "Illinois Vision and Learning Group 页面公开当前团队与项目。", profiles.liuLab)] }),
  p({ id: "minh-do-uiuc-p0-b7", name: "Minh N. Do", role: "Thomas and Margaret Huang Endowed Professor", area: "Computational Imaging · Computer Vision · Signal Processing", tags: ["计算成像", "计算机视觉", "信号处理", "数据科学"], summary: "连接计算成像、视觉和信号处理的 UIUC 资深教授，并有创业与产业技术转化经历。", stage: "senior", x: 1020, file: "minh-do.jpg", profile: profiles.do, sources: [profiles.do, profiles.doHome, profiles.doStudents], facts: [f("当前任职", "UIUC ECE Thomas and Margaret Huang Endowed Professor，并兼任 Computer Science 等单位。", profiles.do), f("教育与学术训练", "University of Canberra Computer Engineering BEng（1997）；EPFL Communication Systems Dr.Sci.（2001）。", profiles.do), f("研究主线", "计算成像、图像表示、计算机视觉与数据科学。", profiles.do), f("产业连接", "Illinois 官方简介记录其为 Personify 联合创始人兼 CTO、Misfit Chief Scientist。", profiles.do), f("学生网络", "本人合作页逐名公开当前研究生、博士校友、论文年份与公开职业去向。", profiles.doStudents)] }),
  p({ id: "tong-zhang-uiuc-p0-b7", name: "Tong Zhang", role: "Professor", area: "Machine Learning Theory · Optimization · Reinforcement Learning", tags: ["机器学习", "优化", "强化学习", "生成式 AI"], summary: "研究机器学习理论、优化与强化学习的 UIUC 教授，任职轨迹跨 Rutgers、HKUST 与 UIUC。", stage: "senior", x: 1200, file: "tong-zhang.jpg", profile: profiles.zhang, sources: [profiles.zhang, profiles.zhangHome, profiles.zhangGroup], facts: [f("当前任职", "UIUC Computer Science 教授。", profiles.zhang), f("教育与学术训练", "Cornell 数学与计算机科学 BA；Stanford Computer Science PhD。", profiles.zhangHome), f("研究主线", "机器学习理论、算法、优化、强化学习与生成式 AI。", profiles.zhangHome), f("任职轨迹", "加入 UIUC 前曾任 HKUST 与 Rutgers 教授。", profiles.zhangHome), f("学生网络", "本人团队页公开当前博士与硕士生，并逐名记录校友的学术界与工业界去向。", profiles.zhangGroup)] }),
  p({ id: "tandy-warnow-uiuc-p0-b7", name: "Tandy Warnow", role: "Grainger Distinguished Chair in Engineering", area: "Machine Learning · Computational Biology · Network Science", tags: ["计算生物学", "机器学习", "网络科学", "算法"], summary: "在计算生物学、网络科学与历史语言学交叉处建立大规模算法体系的 UIUC 资深学者。", stage: "senior", x: 1380, file: "tandy-warnow.jpg", profile: profiles.warnow, sources: [profiles.warnow, profiles.warnowHome], facts: [f("当前任职", "UIUC Grainger Distinguished Chair in Engineering，并任 Siebel School 副主任。", profiles.warnow), f("教育与学术训练", "UC Berkeley Mathematics PhD（1991），导师 Gene Lawler；随后在 USC 跟随 Simon Tavaré 与 Michael Waterman 做博士后。", profiles.warnow), f("研究主线", "计算生物学、网络科学、历史语言学与大规模算法。", profiles.warnow), f("学术领导力", "曾领导 CIPRES 项目，Illinois 官方简介记录该项目训练超过 50 名博士生。", profiles.warnow), f("公开网络", "本人 Illinois 页面公开学生、项目与研究成果。", profiles.warnowHome)] }),
  p({ id: "wenzhen-yuan-uiuc-p0-b7", name: "Wenzhen Yuan", role: "Courtesy Faculty · Assistant Professor", area: "Tactile Sensing · Robotics · Computer Vision", tags: ["触觉感知", "机器人", "计算机视觉", "具身智能"], summary: "研究高分辨率触觉感知与机器人操作的 RoboTouch Lab 负责人，博士谱系连接 MIT Ted Adelson。", stage: "emerging", x: 1560, file: "wenzhen-yuan.jpg", profile: profiles.yuan, sources: [profiles.yuan, profiles.yuanLab, profiles.adelsonCv], facts: [f("当前任职", "Illinois 名录列为 Courtesy Faculty 与 Assistant Professor。", profiles.yuan), f("教育与学术训练", "Tsinghua University 机械工程学士；MIT Mechanical Engineering MS（2014）与 PhD（2018）。", profiles.yuan), f("博士师承", "Ted Adelson 的 MIT 官方 CV 将 Wenzhen Yuan 列为博士生。", profiles.adelsonCv), f("研究主线", "高分辨率触觉传感、机器人操作与视觉触觉学习。", profiles.yuanLab), f("公开团队", "RoboTouch Lab 官方页面公开研究团队与项目。", profiles.yuanLab)] }),
];

export const candidatePriorityP0UsCanadaReadyBatch7SupportingPeople2026: Person[] = [{ id: "gene-lawler-lineage-p0-b7", name: "Eugene L. Lawler", role: "Professor (historical)", institution: "Berkeley", region: "United States", area: "Algorithms · Combinatorial Optimization", tags: ["博士导师", "算法"], summary: "Tandy Warnow 在 UC Berkeley 的博士导师。", stage: "historical", category: "historical", status: "supporting mentor node · relationship evidence only", sources: [profiles.warnow], x: 1380, y: 20, primary: false, lastVerifiedAt: checkedAt }];
export const candidatePriorityP0UsCanadaReadyBatch7Relationships2026: Relationship[] = [
  { id: "candidate-p0-usca-b7-lawler-warnow", from: "gene-lawler-lineage-p0-b7", to: "tandy-warnow-uiuc-p0-b7", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Illinois 官方简介明确 Tandy Warnow 的 Berkeley 数学博士由 Gene Lawler 指导。", source: profiles.warnow, verified: true },
  { id: "candidate-p0-usca-b7-adelson-yuan", from: "ted-adelson-mit-p0-b6", to: "wenzhen-yuan-uiuc-p0-b7", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Ted Adelson 的 MIT CV 将 Wenzhen Yuan 列为博士生。", source: profiles.adelsonCv, verified: true },
];
export const candidatePriorityP0UsCanadaReadyBatch7GroupMembers2026: GroupMember[] = [
  ["girish-chowdhary-uiuc-p0-b7", "DASLAB members", profiles.girishLab], ["katie-driggs-campbell-uiuc-p0-b7", "HCAL members", profiles.katieLab], ["kris-hauser-uiuc-p0-b7", "Intelligent Motion Lab members", profiles.hauserLab], ["steven-lavalle-uiuc-p0-b7", "Motion Strategy Lab members", profiles.lavalleLab], ["yaoyao-liu-uiuc-p0-b7", "Vision and Learning Group members", profiles.liuLab], ["wenzhen-yuan-uiuc-p0-b7", "RoboTouch Lab members", profiles.yuanLab],
  ["minh-do-uiuc-p0-b7", "Nick Bampton", profiles.doStudents], ["tong-zhang-uiuc-p0-b7", "Rui Yang", profiles.zhangGroup],
].map(([teacherId, name, source], i) => ({ id: `candidate-p0-usca-b7-group-${i}`, teacherId: teacherId as string, name: name as string, role: "Graduate students and researchers", source: source as Source }));
export const candidatePriorityP0UsCanadaReadyBatch7Placements2026: StudentPlacement[] = [
  { id: "candidate-p0-usca-b7-do-qian-jiang", student: "Qian Jiang", teacherId: "minh-do-uiuc-p0-b7", company: "Amazon AWS AI Labs", role: "Researcher", kind: "reported", degree: "PhD", sector: "industry", note: "Minh N. Do 的合作页记录 Qian Jiang 于 2024 年完成博士学位，公开去向为 Amazon AWS AI Labs。", source: profiles.doStudents, verifiedAt: checkedAt },
  { id: "candidate-p0-usca-b7-zhang-wei-xiong", student: "Wei Xiong", teacherId: "tong-zhang-uiuc-p0-b7", company: "OpenAI", role: "Research Scientist", kind: "current", degree: "Research group alumnus", sector: "industry", note: "Tong Zhang 的团队页将 Wei Xiong 列为 former group member，并记录其现任 OpenAI Research Scientist。", source: profiles.zhangGroup, verifiedAt: checkedAt },
];
export const candidatePriorityP0UsCanadaReadyBatch7RosterPromotions2026 = candidatePriorityP0UsCanadaReadyBatch7People2026.map((person) => ({ unitUrl: "https://siebelschool.illinois.edu/about/people/all-faculty", rosterName: person.name === "Katie Driggs-Campbell" ? person.name : person.name, atlasPersonId: person.id }));
export const people = [...candidatePriorityP0UsCanadaReadyBatch7People2026, ...candidatePriorityP0UsCanadaReadyBatch7SupportingPeople2026];
export const relationships = candidatePriorityP0UsCanadaReadyBatch7Relationships2026;
export const placements = candidatePriorityP0UsCanadaReadyBatch7Placements2026;
export const groupMembers = candidatePriorityP0UsCanadaReadyBatch7GroupMembers2026;
export const rosterPromotions = candidatePriorityP0UsCanadaReadyBatch7RosterPromotions2026;
