import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const fact = (label: string, value: string, sourceItem: Source) => ({ label, value, source: sourceItem });

const sources = {
  thuCsRoster: source("清华大学计算机系 · 在职教师名录", "https://www.cs.tsinghua.edu.cn/csen/Faculty/Full_time_Faculty.htm", "official", "现任教授名录与所属研究所"),
  jiaOfficial: source("清华大学计算机系 · Jia JIA", "https://www.cs.tsinghua.edu.cn/csen/info/1154/3920.htm", "official", "现任教职与个人主页入口"),
  jiaHome: source("贾珈 · HCSI 个人主页", "https://hcsi.cs.tsinghua.edu.cn/", "profile", "现任任职、教育、研究、代表论文与合作作者"),
  jiaAbout: source("贾珈 · About", "https://hcsi.cs.tsinghua.edu.cn/jiajiaabout", "profile", "教育经历、研究方向、学术服务与产业合作"),

  pkuIntelligenceRoster: source("北京大学智能学院 · 专职教师", "https://www.cis.pku.edu.cn/szdw/zzjs.htm", "official", "现任专职教师名录"),
  yisenOfficial: source("北京大学智能学院 · 王奕森", "https://www.cis.pku.edu.cn/info/1362/2264.htm", "official", "现任职称、博士教育与研究方向"),
  yisenLab: source("北京大学 ZERO Lab · 王奕森", "https://zero-lab-pku.github.io/authors/wangyisen/", "profile", "研究组身份、研究主题与论文"),
  yifeiLab: source("北京大学 ZERO Lab · 王逸飞", "https://zero-lab-pku.github.io/personwise/wangyifei/", "profile", "王奕森共同指导关系、教育与产业实习"),

  pkuCsRoster: source("北京大学计算机学院 · 教研系列名录", "https://cs.pku.edu.cn/szdw/jyxl/amz/ALL.htm", "official", "现任教师名录"),
  zongqingOfficial: source("北京大学视频与视觉技术国家工程研究中心 · 卢宗青", "https://idm.pku.edu.cn/info/1017/1032.htm", "official", "长聘副教授、博士生导师与研究方向"),
  zongqingHome: source("卢宗青 · 个人主页", "https://z0ngqing.github.io/", "profile", "现任任职、教育履历、研究、创业与招生"),
  zongqingLab: source("北京大学强化学习实验室 · Students and Alumni", "https://z0ngqing.github.io/project/", "profile", "在读博士生、毕业生与公开职业去向"),

  fuchunOfficial: source("清华大学计算机系 · Fuchun SUN", "https://www.cs.tsinghua.edu.cn/csen/info/1312/4393.htm", "official", "现任教授、教育、研究、学生培养与代表成果"),
  fuchunNews: source("清华大学 · Youth2Real at ICRA 2026", "https://www.tsinghua.edu.cn/en/info/1245/14991.htm", "official", "孙富春现任团队负责人及具身机器人研究活动"),
  huapingOfficial: source("清华大学计算机系 · Huaping LIU", "https://www.cs.tsinghua.edu.cn/csen/info/1312/4389.htm", "official", "现任教授、教育、研究与孙富春论文合作"),
  advancedComputing: source("清华大学 Advanced Computing · Faculty", "https://ac.cs.tsinghua.edu.cn/faculty.html", "official", "现任教授与机器人智能控制、视觉目标跟踪方向"),
};

const portrait = (file: string, name: string, url: string, sourceItem: Source) => ({
  src: `portraits/candidate-p0-mainland-tail-batch-2-2026/${file}`,
  alt: `${name} 官方头像`,
  source: { ...sourceItem, label: `${sourceItem.label} · portrait`, url, supports: "人物头像" },
});

export const candidatePriorityP0MainlandTailBatch2People2026: Person[] = [
  {
    id: "jia-jia-thu-p0-tail-b2",
    name: "贾珈",
    role: "Professor · PhD Advisor",
    institution: "THU",
    region: "Mainland China",
    area: "Affective Computing · Digital Humans · Multimodal Interaction",
    tags: ["情感计算", "数字人", "多模态交互", "语音交互"],
    summary: "围绕情感计算、数字人生成和人机语音交互持续建设跨多媒体与生成式 AI 研究体系的清华教授。",
    category: "core",
    status: "current independent PI · official faculty and personal profiles verified",
    stage: "senior",
    primary: true,
    x: 150,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("jia-jia.jpg", "贾珈", "https://www.cs.tsinghua.edu.cn/__local/9/A0/80/3BCAD70379BFAFCC49DB22A3F02_76112C11_195AB.jpg", sources.jiaOfficial),
    sources: [sources.jiaOfficial, sources.jiaHome, sources.jiaAbout, sources.thuCsRoster],
    facts: [
      fact("当前任职", "清华大学计算机科学与技术系长聘教授、博士生导师。", sources.jiaAbout),
      fact("教育与学术训练", "2003 年和 2008 年分别获清华大学计算机系学士与博士学位。", sources.jiaAbout),
      fact("研究主线", "研究数字人生成、情感计算与人机语音交互。", sources.jiaAbout),
      fact("学术合作", "个人主页论文清单记录与唐杰共同发表 IJCAI 2018 与 TKDE 2017 等成果。", sources.jiaHome),
      fact("产业连接", "个人简介记录与华为、腾讯、博世和西门子等企业的科研合作。", sources.jiaAbout),
    ],
  },
  {
    id: "yisen-wang-pku-p0-tail-b2",
    name: "王奕森",
    role: "Assistant Professor · Researcher · PhD Advisor",
    institution: "PKU",
    region: "Mainland China",
    area: "Machine Learning · Robust Learning · Graph Learning",
    tags: ["机器学习", "对抗学习", "图学习", "弱监督学习"],
    summary: "聚焦鲁棒机器学习、图学习与弱监督学习，并在 ZERO Lab 开展研究和人才培养的北大青年独立 PI。",
    category: "core",
    status: "current independent PI · official faculty and lab profiles verified",
    stage: "emerging",
    primary: true,
    x: 320,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("yisen-wang.jpg", "王奕森", "https://www.cis.pku.edu.cn/virtual_attach_file.vsb?afc=5M8CCYUl7bLm6RMQ462LmQ2L8LPUzMq7Uz6fMm7Doz9YMNC0gihFp2hmCIa0LYyYMYybLYyYoR-anz9snlQkLmQfoz7Zn7lDM4r7UzG8LRTFLNV2UNr7LzWFLlUYMRUJqjfjo4OeosXJ_dTJQ5v0qIbtpYyxLYyxLYbw62p8c&oid=1887772040&e=.jpg", sources.yisenOfficial),
    sources: [sources.yisenOfficial, sources.yisenLab, sources.pkuIntelligenceRoster, sources.yifeiLab],
    facts: [
      fact("当前任职", "北京大学智能学院研究员、助理教授、博士生导师。", sources.yisenOfficial),
      fact("教育与学术训练", "2018 年博士毕业于清华大学计算机系。", sources.yisenOfficial),
      fact("研究主线", "研究机器学习、深度学习、对抗学习、图学习与弱监督学习。", sources.yisenOfficial),
      fact("人才培养", "ZERO Lab 的王逸飞页面明确记录由王奕森与杨剑生共同指导。", sources.yifeiLab),
    ],
  },
  {
    id: "zongqing-lu-pku-p0-tail-b2",
    name: "卢宗青",
    role: "Tenured Associate Professor · PhD Advisor · Lab Founder",
    institution: "PKU",
    region: "Mainland China",
    area: "Reinforcement Learning · Multimodal Models · General Agents",
    tags: ["强化学习", "多模态大模型", "通用智能体", "具身智能"],
    summary: "从强化学习和多智能体学习延伸到多模态基础模型与具身通用智能体，并公开完整学生去向的北大长聘副教授。",
    category: "core",
    status: "current independent PI · official faculty, personal and lab profiles verified",
    stage: "senior",
    primary: true,
    x: 490,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("zongqing-lu.jpg", "卢宗青", "https://cs.pku.edu.cn/virtual_attach_file.vsb?afc=5Ll-CaozLPnNn7oQ7LbUmffolUZnzLqDU87boRC8nNLsoRN0gihFp2hmCIa0MSh2UYyYLky4MNrRolrfU4n2LmUZMzAfo7nkUmlPnm-bLlnFMzMVMRNaMlrFMmlZMzvJqjfjo4OeoDX4qjAb_khXptQ0gY84gY84gtA8pUpcc&oid=1934453449&e=.jpg", sources.zongqingOfficial),
    sources: [sources.zongqingOfficial, sources.zongqingHome, sources.zongqingLab, sources.pkuCsRoster],
    facts: [
      fact("当前任职", "北京大学计算机学院长聘副教授、博士生导师，并于 2017 年加入北大。", sources.zongqingHome),
      fact("教育与学术训练", "获东南大学学士和硕士学位，2014 年获南洋理工大学计算机博士，后在宾州州立大学从事博士后研究。", sources.zongqingHome),
      fact("研究主线", "研究强化学习、多模态大模型、通用智能体与具身智能。", sources.zongqingOfficial),
      fact("学生体系", "实验室页面公开列出 12 位博士生，以及多位已毕业博士、硕士和共同指导学生。", sources.zongqingLab),
      fact("创业与产业", "创办具身智能基础模型公司 BeingBeyond；实验室毕业生公开去向包括字节跳动、腾讯与阿里巴巴。", sources.zongqingHome),
    ],
  },
  {
    id: "fuchun-sun-thu-p0-tail-b2",
    name: "孙富春",
    role: "Professor · Robotics Group Leader",
    institution: "THU",
    region: "Mainland China",
    area: "Intelligent Control · Robotics · Embodied AI",
    tags: ["智能控制", "机器人", "具身智能", "多模态感知"],
    summary: "长期研究智能控制和机器人，并将团队推进到真实环境具身感知、抓取与操作的清华资深教授。",
    category: "core",
    status: "current independent PI · official faculty and current team activity verified",
    stage: "senior",
    primary: true,
    x: 660,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("fuchun-sun.jpg", "孙富春", "https://www.cs.tsinghua.edu.cn/__local/E/B7/49/932B898264F6883AA0352E9C2B0_6B27DF97_1CD6C.jpg", sources.fuchunOfficial),
    sources: [sources.fuchunOfficial, sources.fuchunNews, sources.thuCsRoster],
    facts: [
      fact("当前任职", "清华大学计算机科学与技术系教授；清华官方 2026 年新闻称其领导 Youth2Real 团队。", sources.fuchunNews),
      fact("教育与学术训练", "1986 年、1989 年获海军航空工程学院学士和硕士，1997 年获清华大学计算机博士。", sources.fuchunOfficial),
      fact("研究主线", "研究智能控制与机器人、移动机器人和航天器制导控制、人工认知系统信息感知处理。", sources.fuchunOfficial),
      fact("人才培养", "官方简介记录已指导 20 名硕士生和 15 名博士生。", sources.fuchunOfficial),
      fact("近期团队", "Youth2Real 团队在 ICRA 2026 机器人抓取与操作赛事获得两个单项第一和总赛铜牌。", sources.fuchunNews),
    ],
  },
  {
    id: "huaping-liu-thu-p0-tail-b2",
    name: "刘华平",
    role: "Professor",
    institution: "THU",
    region: "Mainland China",
    area: "Robot Intelligent Control · Visual Object Tracking",
    tags: ["机器人控制", "视觉跟踪", "多传感器融合", "机器学习"],
    summary: "把鲁棒控制、多传感器信息融合和机器学习用于机器人智能控制与视觉跟踪的清华教授。",
    category: "core",
    status: "current independent PI · official faculty profiles verified",
    stage: "senior",
    primary: true,
    x: 830,
    y: 160,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: portrait("huaping-liu.jpg", "刘华平", "https://www.cs.tsinghua.edu.cn/__local/F/74/C5/0E2D9793535DE0947942874AF56_2BAF5BA3_1EC96.jpg", sources.huapingOfficial),
    sources: [sources.huapingOfficial, sources.advancedComputing, sources.thuCsRoster],
    facts: [
      fact("当前任职", "清华大学计算机科学与技术系人工智能研究所教授，2006 年加入该系。", sources.huapingOfficial),
      fact("教育与学术训练", "1997 年获上海理工大学机械工程学士，2000 年获同济大学电气工程硕士，2004 年获清华大学计算机博士。", sources.huapingOfficial),
      fact("研究主线", "研究机器人智能控制与视觉目标跟踪，并将机器学习用于粒子滤波和视觉跟踪。", sources.huapingOfficial),
      fact("学术合作", "官方成果清单记录与孙富春持续合作控制、滤波与视觉跟踪论文。", sources.huapingOfficial),
    ],
  },
];

export const candidatePriorityP0MainlandTailBatch2SupportingPeople2026: Person[] = [
  {
    id: "yifei-wang-pku-p0-tail-b2-support",
    name: "王逸飞",
    role: "PhD Student · Co-advised",
    institution: "PKU",
    region: "Mainland China",
    area: "Self-supervised Learning · Robustness",
    tags: ["博士生", "共同指导", "鲁棒学习"],
    summary: "ZERO Lab 主页明确记录由杨剑生与王奕森共同指导的北京大学博士生。",
    category: "adjacent",
    stage: "adjacent",
    primary: false,
    x: 320,
    y: 290,
    sources: [sources.yifeiLab],
  },
  {
    id: "haobin-jiang-pku-p0-tail-b2-support",
    name: "姜浩斌",
    role: "PhD Student",
    institution: "PKU",
    region: "Mainland China",
    area: "Reinforcement Learning · General Agents",
    tags: ["博士生", "强化学习", "智能体"],
    summary: "北京大学强化学习实验室公开列出的 2020 级博士生。",
    category: "adjacent",
    stage: "adjacent",
    primary: false,
    x: 490,
    y: 290,
    sources: [sources.zongqingLab],
  },
];

export const candidatePriorityP0MainlandTailBatch2Relationships2026: Relationship[] = [
  {
    id: "p0-mainland-tail-b2-jia-tang-publication",
    from: "jia-jia-thu-p0-tail-b2",
    to: "jie-tang-thu",
    type: "collaboration",
    subtype: "publication",
    label: "论文合作",
    evidence: "贾珈个人主页列出与唐杰共同署名的 IJCAI 2018 Cross-Domain Depression Detection 和 TKDE 2017 Detecting Stress 等论文。",
    evidenceObject: "Cross-Domain Depression Detection via Harvesting Social Media · IJCAI 2018",
    source: sources.jiaHome,
    verified: true,
    recentYear: 2018,
  },
  {
    id: "p0-mainland-tail-b2-yisen-yifei-lineage",
    from: "yisen-wang-pku-p0-tail-b2",
    to: "yifei-wang-pku-p0-tail-b2-support",
    type: "lineage",
    subtype: "co_adviser",
    label: "共同博士导师",
    evidence: "王逸飞的 ZERO Lab 页面明确写明其由杨剑生与王奕森共同指导。",
    evidenceObject: "Yifei Wang · ZERO Lab biography",
    source: sources.yifeiLab,
    verified: true,
  },
  {
    id: "p0-mainland-tail-b2-lu-jiang-lineage",
    from: "zongqing-lu-pku-p0-tail-b2",
    to: "haobin-jiang-pku-p0-tail-b2-support",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "卢宗青实验室 Students 页面将 Haobin Jiang 列为 2020 年入学的博士生。",
    evidenceObject: "Peking University Reinforcement Learning Lab · PhD Students",
    source: sources.zongqingLab,
    verified: true,
  },
  {
    id: "p0-mainland-tail-b2-sun-liu-publication",
    from: "fuchun-sun-thu-p0-tail-b2",
    to: "huaping-liu-thu-p0-tail-b2",
    type: "collaboration",
    subtype: "sustained_collaboration",
    label: "智能控制与视觉跟踪合作",
    evidence: "刘华平清华官方成果页列出多篇与孙富春共同发表的 Automatica、IEEE TAC、IEEE TFS、ICRA 和 ICASSP 论文。",
    evidenceObject: "Huaping Liu official profile · Academic Achievement",
    source: sources.huapingOfficial,
    verified: true,
    recentYear: 2009,
  },
  {
    id: "p0-mainland-tail-b2-sun-zhang-monograph",
    from: "fuchun-sun-thu-p0-tail-b2",
    to: "bo-zhang-thu-historical",
    type: "collaboration",
    subtype: "publication",
    label: "专著合作",
    evidence: "孙富春清华官方成果页列出其与孙增圻、张钹共同撰写《机械手自适应控制神经网络理论与方法》。",
    evidenceObject: "Manipulator adaptive control neural network theory and method · 2005",
    source: sources.fuchunOfficial,
    verified: true,
    recentYear: 2005,
  },
];

export const candidatePriorityP0MainlandTailBatch2GroupMembers2026: GroupMember[] = [
  { id: "p0-mainland-tail-b2-lu-yicheng-feng", teacherId: "zongqing-lu-pku-p0-tail-b2", name: "冯奕澄", role: "PhD student · Fall 2021", focus: "Reinforcement learning and agents", source: sources.zongqingLab },
  { id: "p0-mainland-tail-b2-lu-hao-luo", teacherId: "zongqing-lu-pku-p0-tail-b2", name: "罗浩", role: "PhD student · Fall 2022", focus: "Embodied intelligence", source: sources.zongqingLab },
];

export const candidatePriorityP0MainlandTailBatch2Placements2026: StudentPlacement[] = [
  { id: "p0-mainland-tail-b2-lu-kefan-su-bytedance", student: "苏克凡", teacherId: "zongqing-lu-pku-p0-tail-b2", company: "ByteDance", role: "PhD alumnus · destination reported by lab", kind: "reported", sector: "industry", note: "实验室 Alumni 页面记录 Kefan Su（PhD, 2025）去向 ByteDance。", source: sources.zongqingLab, verifiedAt: checkedAt },
  { id: "p0-mainland-tail-b2-yisen-yifei-huawei", student: "王逸飞", teacherId: "yisen-wang-pku-p0-tail-b2", company: "Huawei Noah's Ark Lab", role: "Research intern · Sep 2019–Jul 2020", kind: "reported", sector: "industry", note: "王逸飞的 ZERO Lab 页面公开记录其在华为诺亚方舟实验室的研究实习。", source: sources.yifeiLab, verifiedAt: checkedAt },
];

export const candidatePriorityP0MainlandTailBatch2RosterPromotions2026 = [
  { unitUrl: "https://www.cs.tsinghua.edu.cn/csen/Faculty/Full_time_Faculty.htm", rosterName: "Jia JIA", atlasPersonId: "jia-jia-thu-p0-tail-b2" },
  { unitUrl: "https://www.cis.pku.edu.cn/szdw/zzjs.htm", rosterName: "王奕森", atlasPersonId: "yisen-wang-pku-p0-tail-b2" },
  { unitUrl: "https://cs.pku.edu.cn/szdw/jyxl/amz/ALL.htm", rosterName: "卢宗青", atlasPersonId: "zongqing-lu-pku-p0-tail-b2" },
  { unitUrl: "https://www.cs.tsinghua.edu.cn/csen/Faculty/Full_time_Faculty.htm", rosterName: "Fuchun SUN", atlasPersonId: "fuchun-sun-thu-p0-tail-b2" },
  { unitUrl: "https://www.cs.tsinghua.edu.cn/csen/Faculty/Full_time_Faculty.htm", rosterName: "Huaping LIU", atlasPersonId: "huaping-liu-thu-p0-tail-b2" },
];
