import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const s = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const f = (label: string, value: string, source: Source) => ({ label, value, source });

const q = {
  deepak: s("Illinois Siebel School · Deepak Vasisht", "https://siebelschool.illinois.edu/about/people/all-faculty/deepakv", "official", "Current faculty appointment"),
  deepakHome: s("Deepak Vasisht · Illinois homepage", "https://deepakv.web.illinois.edu/index.html", "profile", "Education, Dina Katabi supervision, research, students and Microsoft work"),
  kevin: s("Illinois Siebel School · Kevin Chenchuan Chang", "https://siebelschool.illinois.edu/about/people/all-faculty/kcchang", "official", "Current faculty appointment"),
  kevinEce: s("Illinois ECE · Kevin Chenchuan Chang", "https://ece.illinois.edu/about/directory/faculty/kcchang", "official", "Education, information-access research and student-founded startup"),
  maxim: s("Illinois Siebel School · Maxim Raginsky", "https://siebelschool.illinois.edu/about/people/all-faculty/maxim", "official", "Current affiliated faculty appointment"),
  maximCsl: s("Illinois CSL · Maxim Raginsky", "https://csl.illinois.edu/directory/faculty/maxim", "official", "Education and machine-learning research"),
  maximHome: s("Maxim Raginsky · Illinois homepage", "https://maxim.web.engr.illinois.edu/", "profile", "Current students and alumni destinations"),
  romit: s("Illinois Siebel School · Romit Roy Choudhury", "https://siebelschool.illinois.edu/about/people/all-faculty/croy", "official", "Current affiliated faculty appointment"),
  romitHome: s("Romit Roy Choudhury · Illinois homepage", "https://croy.ece.illinois.edu/", "profile", "Research, current students and alumni destinations"),
  romitBio: s("Romit Roy Choudhury · Illinois bio", "https://croy.web.engr.illinois.edu/bio.html", "profile", "Doctoral education and faculty trajectory"),
  gill: s("Stanford Computer Science · Gill Bejerano", "https://www.cs.stanford.edu/people/gill-bejerano", "official", "Current Stanford faculty appointment"),
  gillProfile: s("Stanford Medicine · Gill Bejerano", "https://med.stanford.edu/profiles/gill-bejerano", "official", "Education and current computational genomics research"),
  gillBioX: s("Stanford Bio-X · Gill Bejerano", "https://biox.stanford.edu/people/gill-bejerano", "official", "Bejerano Lab research program"),
  genesereth: s("Stanford Computer Science · Michael Genesereth", "https://www.cs.stanford.edu/people/michael-genesereth", "official", "Current faculty appointment"),
  geneserethProfile: s("Stanford Profiles · Michael Genesereth", "https://profiles.stanford.edu/michael-genesereth", "official", "Education, Logic Group leadership and startup activity"),
  geneserethNews: s("Stanford Report · Michael Genesereth", "https://news.stanford.edu/stories/2024/04/professor-michael-genesereth-mission-bring-logic-education-high-schools", "official", "Current logic education program and work with graduate students"),
  vasilis: s("Stanford MS&E · Vasilis Syrgkanis", "https://msande.stanford.edu/people/vasilis-syrgkanis", "official", "Current Stanford appointment and AI research recognition"),
  vasilisHome: s("Vasilis Syrgkanis · Stanford homepage", "https://www.vsyrgkanis.com/", "profile", "Education, Eva Tardos supervision, Microsoft Research and Causal AI Lab"),
  randall: s("MIT CSAIL · Randall Davis", "https://www.csail.mit.edu/person/randall-davis", "official", "Current PI status, education and AI/HCI research"),
  randallHome: s("Randall Davis · MIT homepage", "https://people.csail.mit.edu/davis/davis.htm", "profile", "Current MIT role and research projects"),
  randallGroup: s("MIT Multimodal Understanding Group · People", "https://groups.csail.mit.edu/mug/people.shtml", "official", "Current students and PhD alumni"),
  rob: s("MIT CSAIL · Rob Miller", "https://www.csail.mit.edu/person/rob-miller", "official", "Current MIT faculty roster entry"),
  robHome: s("Rob Miller · MIT homepage", "https://people.csail.mit.edu/rcm/", "profile", "Education, current role and HCI research"),
  robGroup: s("MIT User Interface Design Group · People", "https://up.csail.mit.edu/uid.html", "official", "Students, alumni and career destinations"),
  stefanie: s("MIT CSAIL · Stefanie Mueller", "https://www.csail.mit.edu/person/stefanie-mueller", "official", "Current associate professorship and HCI research"),
  stefanieEecs: s("MIT EECS · 2024 faculty promotions", "https://www.eecs.mit.edu/department-of-eecs-announces-2024-promotions-2/", "official", "Tenure promotion and education"),
  stefanieLab: s("Stefanie Mueller · MIT HCI Engineering", "https://hcie.csail.mit.edu/stefanie-mueller", "profile", "Research, current students and alumni outcomes"),
  stefanieMentor: s("MIT News · HPI–MIT collaboration", "https://news.mit.edu/2024/hpi-mit-design-research-collaboration-creates-powerful-teams-0503", "official", "Patrick Baudisch was Mueller's PhD adviser"),
  dong: s("Illinois iSchool · Dong Wang", "https://ischool.illinois.edu/people/dong-wang", "official", "Current appointment, education, research, projects and students"),
  dongAimpact: s("Illinois AImpact · Dong Wang", "https://aimpact.illinois.edu/faculty-pages/wang.html", "official", "Human-centered AI and social sensing research program"),
  francis: s("Illinois Siebel School · Francis Y. Yan", "https://siebelschool.illinois.edu/about/people/all-faculty/fyy", "official", "Current faculty appointment"),
  francisHome: s("Francis Y. Yan · Illinois homepage", "https://fyy.web.illinois.edu/", "profile", "Research, education and current role"),
  francisCv: s("Francis Y. Yan · curriculum vitae", "https://fyy.web.illinois.edu/documents/fyy-cv.pdf", "cv", "Doctoral training, advisers and industry career"),
  francisStudents: s("Francis Y. Yan · students and alumni", "https://mail.fyy.web.illinois.edu/students/", "profile", "Current students, co-advising and alumni destinations"),
  melkior: s("Illinois Siebel School · Melkior Ornik", "https://siebelschool.illinois.edu/about/people/all-faculty/mornik", "official", "Current affiliated faculty appointment"),
  melkiorGrainger: s("Illinois Grainger Engineering · Melkior Ornik", "https://grainger.illinois.edu/about/directory/faculty/mornik", "official", "Education, academic training and autonomous-systems research"),
  melkiorHome: s("Melkior Ornik · Illinois research", "https://mornik.web.illinois.edu/research/", "profile", "Safety-critical autonomy and sponsored research program"),
  kaiyu: s("Illinois Siebel School · Kaiyu Guan", "https://siebelschool.illinois.edu/about/people/all-faculty/kaiyug", "official", "Current Computer Science affiliate appointment"),
  kaiyuHome: s("Kaiyu Guan · Illinois homepage", "https://kaiyuguan.nres.illinois.edu/", "profile", "Current appointment, education, advisers, research and lab leadership"),
  kaiyuExperts: s("Illinois Experts · Kaiyu Guan", "https://experts.illinois.edu/en/persons/kaiyu-guan/", "official", "Education and current university appointments"),
  kaiyuStartup: s("Illinois Research Park · HabiTerre founder Kaiyu Guan", "https://researchpark.illinois.edu/habiterre-founder-kaiyu-guan-honored-for-excellence-in-agricultural-research-innovation/", "official", "University-reported startup founding and technology translation"),
};

type Seed = Omit<Person, "portrait" | "category" | "status" | "primary" | "introducedAt" | "lastVerifiedAt">;
const p = (x: Seed, file: string, portraitUrl: string): Person => ({ ...x, category: "core", status: "current independent PI · official faculty profile verified", primary: true, introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-us-canada-ready-batch-14-2026/${file}.jpg`, alt: `${x.name} 官方头像`, source: s(`${x.institution} portrait · ${x.name}`, portraitUrl, "official", "Official university portrait") } });

export const candidatePriorityP0UsCanadaReadyBatch14People2026: Person[] = [
  p({ id: "deepak-vasisht-uiuc-p0-b14", name: "Deepak Vasisht", role: "Assistant Professor", institution: "UIUC", region: "United States", area: "AI-driven Networks · Wireless Sensing · Robotics", tags: ["AI网络", "无线感知", "机器人", "数字农业"], summary: "把机器学习、无线网络与感知用于卫星、农业和医疗场景的 UIUC PI。", stage: "emerging", x: 120, y: 120, sources: [q.deepak, q.deepakHome], facts: [f("当前任职", "UIUC Computer Science 助理教授，并交叉 ECE 与 CSL。", q.deepakHome), f("教育与学术训练", "IIT Delhi B.Tech；MIT CSE S.M. 与 PhD（2019），博士导师 Dina Katabi。", q.deepakHome), f("研究主线", "AI 驱动网络、卫星连接、无线感知、机器人和数据驱动农业。", q.deepakHome), f("产业经历", "博士期间及毕业后参与 Microsoft Research FarmBeats 农业 AI/IoT 平台。", q.deepakHome), f("学生体系", "本人主页公开列出 Jay Shenoy、Zikun Liu、Emerson Sie 等在读博士生。", q.deepakHome)] }, "deepak-vasisht", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=99471&s=400&type=portrait"),
  p({ id: "kevin-chang-uiuc-p0-b14", name: "Kevin Chenchuan Chang", role: "Professor of Computer Science", institution: "UIUC", region: "United States", area: "Information Retrieval · Knowledge Acquisition · Data Mining", tags: ["信息检索", "知识获取", "数据挖掘", "搜索"], summary: "研究大规模信息访问、搜索与知识获取并推动成果创业转化的 UIUC 资深教授。", stage: "senior", x: 300, y: 120, sources: [q.kevin, q.kevinEce], facts: [f("当前任职", "UIUC Computer Science 教授。", q.kevinEce), f("教育与学术训练", "National Taiwan University BS；Stanford Electrical Engineering PhD（2001）。", q.kevinEce), f("研究主线", "结构化与非结构化大数据的搜索、挖掘、集成和知识获取。", q.kevinEce), f("产业连接", "与学生共同创办校内创业公司 Cazoodle，并开发 GrantForward 服务。", q.kevinEce)] }, "kevin-chang", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=4960&s=400&type=portrait"),
  p({ id: "maxim-raginsky-uiuc-p0-b14", name: "Maxim Raginsky", role: "Professor · William L. Everitt Fellow", institution: "UIUC", region: "United States", area: "Machine Learning Theory · Control · Information Theory", tags: ["机器学习理论", "控制", "信息论", "优化"], summary: "连接学习理论、控制与信息论，研究智能系统基本极限的 UIUC PI。", stage: "senior", x: 480, y: 120, sources: [q.maxim, q.maximCsl, q.maximHome], facts: [f("当前任职", "UIUC ECE 教授、William L. Everitt Fellow，并在 CS 兼任。", q.maximHome), f("教育与学术训练", "Northwestern University Electrical Engineering BS、MS（2000）与 PhD（2002）；曾任 UIUC Beckman Foundation Fellow。", q.maximHome), f("研究主线", "概率、随机控制、机器学习、优化和信息论。", q.maximHome), f("学生体系", "本人主页列出 Tatiana Grigorovich、June Hou、Anson Li 等研究生。", q.maximHome), f("学生去向", "博士校友 Tanya Veeravalli 进入新加坡 A*STAR，Joshua Hanson 进入 Sandia National Laboratories。", q.maximHome)] }, "maxim-raginsky", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=73612&s=400&type=portrait"),
  p({ id: "romit-roy-choudhury-uiuc-p0-b14", name: "Romit Roy Choudhury", role: "Gilmore Family Endowed Professor · Amazon Scholar", institution: "UIUC", region: "United States", area: "Generative Models · Audio AI · Sensing", tags: ["生成模型", "音频AI", "感知", "逆问题"], summary: "从无线感知拓展到生成模型、音频分离与逆问题的 UIUC 资深 PI。", stage: "senior", x: 660, y: 120, sources: [q.romit, q.romitHome, q.romitBio], facts: [f("当前任职", "UIUC ECE/CS Gilmore Family Endowed Professor，并任 Amazon Scholar。", q.romitHome), f("教育与学术训练", "UIUC Computer Science PhD（2006）；加入 UIUC 前曾任 Duke 副教授。", q.romitBio), f("研究主线", "生成模型、黑盒优化、逆问题、NeRF、音频去噪与源分离。", q.romitHome), f("学生体系", "本人主页公开当前博士、硕士学生及历届博士生。", q.romitHome), f("学生去向", "公开记录校友进入 Apple、Meta Reality Labs、Google、LinkedIn，以及 Georgia Tech、UMD、Penn State 等高校。", q.romitHome)] }, "romit-roy-choudhury", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=43501&s=400&type=portrait"),
  p({ id: "gill-bejerano-stanford-p0-b14", name: "Gill Bejerano", role: "Professor", institution: "Stanford", region: "United States", area: "Machine Learning for Genomics · Biomedical Data Science", tags: ["计算基因组学", "机器学习", "生物医学数据", "医疗AI"], summary: "用机器学习与大规模基因组数据研究疾病诊断和调控机制的 Stanford PI。", stage: "senior", x: 840, y: 120, sources: [q.gill, q.gillProfile, q.gillBioX], facts: [f("当前任职", "Stanford Developmental Biology、Computer Science 与 Pediatrics 教授。", q.gillProfile), f("教育与学术训练", "Hebrew University 数学、物理与计算机科学本科及 Computer Science PhD；随后在 UC Santa Cruz 做计算与功能基因组学博士后。", q.gillProfile), f("研究主线", "计算基因组学、机器学习、电子健康记录与罕见病诊断。", q.gillProfile), f("团队方向", "Bejerano Lab 结合计算与实验方法，把基因组变异映射到表型。", q.gillBioX)] }, "gill-bejerano", "https://www.cs.stanford.edu/sites/g/files/sbiybj28076/files/styles/square_1900/public/media/person/gill-bejerano1628984517681.jpg?h=1641edec&itok=twT-mB9b"),
  p({ id: "michael-genesereth-stanford-p0-b14", name: "Michael Genesereth", role: "Associate Professor of Computer Science", institution: "Stanford", region: "United States", area: "Computational Logic · General Game Playing · AI", tags: ["计算逻辑", "通用博弈", "符号AI", "计算法学"], summary: "推动计算逻辑、通用博弈与计算法学落地的 Stanford 资深 AI 教授。", stage: "senior", x: 1020, y: 120, sources: [q.genesereth, q.geneserethProfile, q.geneserethNews], facts: [f("当前任职", "Stanford Computer Science 副教授、Logic Group 主任与 CodeX 研究主任。", q.geneserethProfile), f("教育与学术训练", "Harvard University PhD（1978）。", q.geneserethProfile), f("研究主线", "计算逻辑及其在企业管理、计算法学与通用博弈中的应用。", q.geneserethProfile), f("创业经历", "Stanford Profiles 记录其参与创办 Teknowledge、CommerceNet、Mergent Systems 与 Symbium。", q.geneserethProfile), f("教育与团队", "Stanford Report 记录其与研究生开发逻辑课程工具，并发起 Logic For All。", q.geneserethNews)] }, "michael-genesereth", "https://www.cs.stanford.edu/sites/g/files/sbiybj28076/files/styles/square_1900/public/media/person/michael-genesereth1219536232000.jpg?h=df2f6dbc&itok=7ZApUeUH"),
  p({ id: "vasilis-syrgkanis-stanford-p0-b14", name: "Vasilis Syrgkanis", role: "Assistant Professor", institution: "Stanford", region: "United States", area: "Causal Machine Learning · Reinforcement Learning · Econometrics", tags: ["因果机器学习", "强化学习", "计量经济学", "博弈论"], summary: "连接因果推断、机器学习、强化学习与算法经济学的 Stanford PI。", stage: "emerging", x: 1200, y: 120, sources: [q.vasilis, q.vasilisHome], facts: [f("当前任职", "Stanford MS&E 助理教授，并在 CS、EE 兼任。", q.vasilisHome), f("教育与学术训练", "National Technical University of Athens EECS diploma；Cornell Computer Science PhD，导师 Eva Tardos；随后在 Microsoft Research NYC 博士后。", q.vasilisHome), f("研究主线", "机器学习、因果推断、计量经济学、在线与强化学习及机制设计。", q.vasilisHome), f("产业经历", "2022 年前任 Microsoft Research New England Principal Researcher，并共同领导 ALICE 项目。", q.vasilisHome), f("团队建设", "领导 Stanford Causal AI Lab，并公开邀请博士生开展因果机器学习研究。", q.vasilisHome)] }, "vasilis-syrgkanis", "https://www.cs.stanford.edu/sites/g/files/sbiybj28076/files/styles/square_1900/public/media/image/vasilis-syrgkanis_profilephoto_0.jpg?h=9446d18b&itok=b99xv2eo"),
  p({ id: "randall-davis-mit-p0-b14", name: "Randall Davis", role: "Professor", institution: "MIT", region: "United States", area: "Knowledge-based AI · Multimodal HCI", tags: ["知识系统", "多模态交互", "人机交互", "经典AI"], summary: "知识系统与自然多模态交互领域的 MIT 奠基型 AI 教授。", stage: "senior", x: 1380, y: 120, sources: [q.randall, q.randallHome, q.randallGroup], facts: [f("当前任职", "MIT EECS 教授、CSAIL PI。", q.randall), f("教育与学术训练", "Dartmouth 本科（1970）；Stanford 人工智能 PhD（1976）。", q.randall), f("研究主线", "知识系统、草图理解、手势与语音结合的自然多模态交互。", q.randall), f("学术领导", "曾任 MIT AI Laboratory 副主任及 CSAIL Research Director/Associate Director。", q.randall), f("学生体系", "Multimodal Understanding Group 页面列出当前学生与 Jacob Eisenstein、Tracy Hammond 等博士校友。", q.randallGroup)] }, "randall-davis", "https://www.csail.mit.edu/sites/default/files/styles/headshot/public/images/people/card/Jun%2030%202016%20-%20Digital%20Cognition%20Technologies%20-%20Randy%20Davis%20-%200001%20-%20social.jpg"),
  p({ id: "rob-miller-mit-p0-b14", name: "Rob Miller", role: "Distinguished Professor of Computer Science", institution: "MIT", region: "United States", area: "Human-Computer Interaction · Programming Tools · AI Education", tags: ["人机交互", "编程工具", "AI教育", "众包"], summary: "研究可用编程、学习工具与人机协作的 MIT HCI 资深 PI。", stage: "senior", x: 1560, y: 120, sources: [q.rob, q.robHome, q.robGroup], facts: [f("当前任职", "MIT EECS Distinguished Professor、CSAIL 成员。", q.robHome), f("教育与学术训练", "MIT Computer Science 学士与硕士（1995）；Carnegie Mellon Computer Science PhD（2002）。", q.robHome), f("研究主线", "编程与 HCI，包括在线教育、软件开发工具和终端用户编程。", q.robHome), f("学生体系", "User Interface Design Group 页面逐名列出博士、硕士、本科研究者与校友。", q.robGroup), f("学生去向", "公开记录 Elena Glassman 去 Berkeley 博士后、Juho Kim 任 KAIST 教授，以及校友进入 Cisco、Google、Microsoft、Dropbox 等。", q.robGroup)] }, "rob-miller", "https://www.csail.mit.edu/sites/default/files/styles/headshot/public/images/migration/miller.jpg"),
  p({ id: "stefanie-mueller-mit-p0-b14", name: "Stefanie Mueller", role: "Associate Professor", institution: "MIT", region: "United States", area: "Human-Computer Interaction · Generative Design · Robotics", tags: ["人机交互", "生成式设计", "计算制造", "机器人"], summary: "把生成式 AI、计算制造与交互硬件结合的 MIT HCI Engineering 负责人。", stage: "emerging", x: 1740, y: 120, sources: [q.stefanie, q.stefanieEecs, q.stefanieLab, q.stefanieMentor], facts: [f("当前任职", "MIT EECS 与 Mechanical Engineering 联合副教授、CSAIL HCI Engineering Group 负责人。", q.stefanie), f("教育与学术训练", "University of Applied Science Harz BS（2010）；Hasso Plattner Institute MS（2013）与 PhD（2016）。", q.stefanieEecs), f("研究主线", "HCI、个人制造、生成式 3D 设计、交互材料与机器人。", q.stefanieLab), f("师承关系", "MIT News 明确记录 Patrick Baudisch 是其 HPI 博士导师。", q.stefanieMentor), f("学生去向", "本人页面记录其博士及博士后校友进入 UW、Michigan、NYU 等高校，以及 Adobe、Google Research。", q.stefanieLab)] }, "stefanie-mueller", "https://www.csail.mit.edu/sites/default/files/styles/headshot/public/images/people/card/stefanie-mueller-profile-picture_0.jpg"),
  p({ id: "dong-wang-uiuc-p0-b14", name: "Dong Wang", role: "Professor · Associate Dean for Research", institution: "UIUC", region: "United States", area: "Human-centered AI · Social Sensing · Responsible AI", tags: ["人本AI", "社会感知", "可信AI", "人机协作"], summary: "以社会感知与人本 AI 连接群体智能、可信决策和现实公共场景的 Illinois iSchool 教授。", stage: "senior", x: 1920, y: 120, sources: [q.dong, q.dongAimpact], facts: [f("当前任职", "University of Illinois iSchool 教授、分管科研的副院长，并兼任 Computer Science。", q.dong), f("教育与学术训练", "University of Illinois Urbana-Champaign Computer Science PhD；此前在 Peking University 获学位。", q.dong), f("研究主线", "社会感知、人本 AI、人机协作与负责任 AI，关注由人类和机器共同产生的大规模数据。", q.dongAimpact), f("产业与应用", "官方简介记录其团队与 Snap Research 合作，并把方法用于公共安全、灾害响应和智能城市。", q.dong), f("团队建设", "官方个人页列出 Wang group 的学生、研究项目与招募信息。", q.dong)] }, "dong-wang", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=152073&s=400&type=portrait"),
  p({ id: "francis-yan-uiuc-p0-b14", name: "Francis Y. Yan", role: "Assistant Professor", institution: "UIUC", region: "United States", area: "Networked Systems · Video Systems · ML for Systems", tags: ["网络系统", "视频系统", "系统机器学习", "资源管理"], summary: "研究视频传输、网络资源管理和机器学习系统交叉问题的 UIUC 新锐 PI。", stage: "emerging", x: 2100, y: 120, sources: [q.francis, q.francisHome, q.francisCv, q.francisStudents], facts: [f("当前任职", "自 2025 年起任 UIUC Computer Science 助理教授。", q.francisCv), f("教育与学术训练", "Tsinghua University Computer Science 学士；Stanford Computer Science PhD（2020），导师 Keith Winstein 与 Philip Levis。", q.francisCv), f("研究主线", "网络化系统、视频系统、资源管理，以及机器学习在网络与系统中的应用。", q.francisHome), f("产业经历", "加入 UIUC 前在 Microsoft Research 任 Senior Researcher，并有 Google、Baidu、Microsoft Research 等实习经历。", q.francisCv), f("学生去向", "本人学生页记录校友进入 CoreWeave、Meta、Amazon、Google、ByteDance 与 Tencent。", q.francisStudents)] }, "francis-yan", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=153261&s=400&type=portrait"),
  p({ id: "melkior-ornik-uiuc-p0-b14", name: "Melkior Ornik", role: "Associate Professor", institution: "UIUC", region: "United States", area: "Autonomous Systems · Safe Control · Robotics", tags: ["自主系统", "安全控制", "机器人", "规划"], summary: "研究未知环境下安全关键自主系统、规划与控制学习的 UIUC PI。", stage: "emerging", x: 2280, y: 120, sources: [q.melkior, q.melkiorGrainger, q.melkiorHome], facts: [f("当前任职", "UIUC Aerospace Engineering 副教授，并在 Computer Science 等单位兼任。", q.melkiorGrainger), f("教育与学术训练", "University of Zagreb 数学学士、Queen's University 数学硕士、University of Toronto ECE PhD（2017）；随后在 UT Austin 从事博士后研究。", q.melkiorGrainger), f("研究主线", "安全关键控制、自主系统、未知环境规划及控制中的学习方法。", q.melkiorGrainger), f("项目体系", "本人研究页列出面向复杂环境规划、群体系统和 foundation models 的 ONR、DARPA 与 AFWERX 项目。", q.melkiorHome)] }, "melkior-ornik", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=163790&s=400&type=portrait"),
  p({ id: "kaiyu-guan-uiuc-p0-b14", name: "Kaiyu Guan", role: "Levenick Endowed Professor", institution: "UIUC", region: "United States", area: "AI for Agriculture · Remote Sensing · Earth Data Science", tags: ["农业AI", "遥感", "地球数据科学", "机器学习"], summary: "用 AI、卫星观测与超级计算推进农业和气候可持续性的 UIUC 跨学科 PI。", stage: "senior", x: 2460, y: 120, sources: [q.kaiyu, q.kaiyuHome, q.kaiyuExperts, q.kaiyuStartup], facts: [f("当前任职", "UIUC Levenick Endowed Professor、NRES 教授并兼任 Computer Science。", q.kaiyuHome), f("教育与学术训练", "Nanjing University Geography/Geoinformatics 学士；Princeton Environmental Engineering MA 与 PhD（2013），导师 Eric F. Wood；随后在 Stanford 与 David Lobell、Joe Berry 从事博士后研究。", q.kaiyuHome), f("研究主线", "融合卫星与田间观测、机器学习和超级计算，研究农业生产与气候可持续性。", q.kaiyuHome), f("团队建设", "创办并领导 Agroecosystem Sustainability Center，官网公开研究团队与招募信息。", q.kaiyuHome), f("创业转化", "Illinois Research Park 记录其为农业科技公司 HabiTerre 创始人。", q.kaiyuStartup)] }, "kaiyu-guan", "https://ws.engr.illinois.edu/directory/viewphoto.aspx?id=121731&s=400&type=portrait"),
];

export const candidatePriorityP0UsCanadaReadyBatch14SupportingPeople2026: Person[] = [
  { id: "eva-tardos-lineage-p0-b14", name: "Eva Tardos", role: "Professor · doctoral adviser", institution: "Cornell", region: "United States", area: "Algorithms · Algorithmic Game Theory", tags: ["算法", "博弈论", "博士导师"], summary: "Vasilis Syrgkanis 在 Cornell 博士阶段的导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 1200, y: 20, sources: [q.vasilisHome], lastVerifiedAt: checkedAt },
  { id: "patrick-baudisch-lineage-p0-b14", name: "Patrick Baudisch", role: "Professor · doctoral adviser", institution: "External", actualInstitution: "Hasso Plattner Institute", region: "Europe", area: "Human-Computer Interaction", tags: ["人机交互", "博士导师"], summary: "Stefanie Mueller 在 Hasso Plattner Institute 博士阶段的导师。", stage: "senior", category: "adjacent", status: "supporting mentor node · relationship evidence only", primary: false, x: 1740, y: 20, sources: [q.stefanieMentor], lastVerifiedAt: checkedAt },
];

export const candidatePriorityP0UsCanadaReadyBatch14Relationships2026: Relationship[] = [
  { id: "p0-usca-b14-katabi-vasisht", from: "dina-katabi-mit-p0-b10", to: "deepak-vasisht-uiuc-p0-b14", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Deepak Vasisht 本人主页明确其 MIT 博士导师为 Dina Katabi。", source: q.deepakHome, verified: true, endYear: 2019 },
  { id: "p0-usca-b14-tardos-syrgkanis", from: "eva-tardos-lineage-p0-b14", to: "vasilis-syrgkanis-stanford-p0-b14", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Vasilis Syrgkanis 本人主页明确其 Cornell 博士导师为 Eva Tardos。", source: q.vasilisHome, verified: true },
  { id: "p0-usca-b14-baudisch-mueller", from: "patrick-baudisch-lineage-p0-b14", to: "stefanie-mueller-mit-p0-b14", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "MIT News 明确称 Patrick Baudisch 为 Stefanie Mueller 的 HPI 博士导师。", source: q.stefanieMentor, verified: true, endYear: 2016 },
  { id: "p0-usca-b14-francis-deepak", from: "francis-yan-uiuc-p0-b14", to: "deepak-vasisht-uiuc-p0-b14", type: "collaboration", subtype: "co_adviser", label: "共同指导", evidence: "Francis Yan 的学生页明确记录 Seoyul Oh 由 Francis Yan 与 Deepak Vasisht 共同指导。", source: q.francisStudents, verified: true },
];

export const candidatePriorityP0UsCanadaReadyBatch14GroupMembers2026: GroupMember[] = [
  { id: "p0-usca-b14-deepak-students", teacherId: "deepak-vasisht-uiuc-p0-b14", name: "Vasisht group students", role: "PhD students", source: q.deepakHome },
  { id: "p0-usca-b14-kevin-student-founders", teacherId: "kevin-chang-uiuc-p0-b14", name: "Cazoodle student co-founders", role: "Student collaborators and startup co-founders", source: q.kevinEce },
  { id: "p0-usca-b14-maxim-students", teacherId: "maxim-raginsky-uiuc-p0-b14", name: "Raginsky graduate students", role: "Graduate students and postdocs", source: q.maximHome },
  { id: "p0-usca-b14-romit-students", teacherId: "romit-roy-choudhury-uiuc-p0-b14", name: "SiNRG students", role: "PhD and master's students", source: q.romitHome },
  { id: "p0-usca-b14-gill-lab", teacherId: "gill-bejerano-stanford-p0-b14", name: "Bejerano Lab", role: "Computational and experimental genomics researchers", source: q.gillBioX },
  { id: "p0-usca-b14-genesereth-logic", teacherId: "michael-genesereth-stanford-p0-b14", name: "Stanford Logic Group", role: "Faculty and graduate researchers", source: q.geneserethProfile },
  { id: "p0-usca-b14-randall-group", teacherId: "randall-davis-mit-p0-b14", name: "MIT Multimodal Understanding Group", role: "Students and alumni", source: q.randallGroup },
  { id: "p0-usca-b14-rob-group", teacherId: "rob-miller-mit-p0-b14", name: "MIT User Interface Design Group", role: "Students and alumni", source: q.robGroup },
  { id: "p0-usca-b14-stefanie-group", teacherId: "stefanie-mueller-mit-p0-b14", name: "MIT HCI Engineering Group", role: "PhD students and postdocs", source: q.stefanieLab },
  { id: "p0-usca-b14-dong-group", teacherId: "dong-wang-uiuc-p0-b14", name: "Wang Group", role: "Students and research collaborators", source: q.dong },
  { id: "p0-usca-b14-francis-group", teacherId: "francis-yan-uiuc-p0-b14", name: "Yan research group", role: "Students and alumni", source: q.francisStudents },
  { id: "p0-usca-b14-melkior-group", teacherId: "melkior-ornik-uiuc-p0-b14", name: "Ornik autonomy research team", role: "Autonomous-systems researchers", source: q.melkiorHome },
  { id: "p0-usca-b14-kaiyu-group", teacherId: "kaiyu-guan-uiuc-p0-b14", name: "Agroecosystem Sustainability Center", role: "Director and interdisciplinary research team", source: q.kaiyuHome },
];

export const candidatePriorityP0UsCanadaReadyBatch14Placements2026: StudentPlacement[] = [
  { id: "p0-usca-b14-maxim-tanya", student: "Tanya Veeravalli", teacherId: "maxim-raginsky-uiuc-p0-b14", company: "A*STAR", role: "PhD alumna", kind: "reported", sector: "industry", note: "Raginsky 本人主页记录其 2025 PhD 校友进入新加坡 A*STAR。", source: q.maximHome, verifiedAt: checkedAt },
  { id: "p0-usca-b14-romit-seo", student: "Hyungjoo Seo", teacherId: "romit-roy-choudhury-uiuc-p0-b14", company: "Apple", role: "PhD alumnus", kind: "reported", sector: "industry", note: "Romit 本人主页记录其博士校友 Hyungjoo Seo 去向 Apple。", source: q.romitHome, verifiedAt: checkedAt },
  { id: "p0-usca-b14-romit-shen", student: "Sheng Shen", teacherId: "romit-roy-choudhury-uiuc-p0-b14", company: "Meta", role: "Researcher", kind: "reported", sector: "industry", note: "Romit 本人主页记录其博士校友 Sheng Shen 去向 Meta Reality Labs。", source: q.romitHome, verifiedAt: checkedAt },
  { id: "p0-usca-b14-francis-neil", student: "Neil Agarwal", teacherId: "francis-yan-uiuc-p0-b14", company: "Meta", role: "Alumnus", kind: "reported", sector: "industry", note: "Francis Yan 本人学生页记录 Neil Agarwal 去向 Meta。", source: q.francisStudents, verifiedAt: checkedAt },
  { id: "p0-usca-b14-francis-zhengxu", student: "Zhengxu Xia", teacherId: "francis-yan-uiuc-p0-b14", company: "Google", role: "Alumnus", kind: "reported", sector: "industry", note: "Francis Yan 本人学生页记录 Zhengxu Xia 去向 Google。", source: q.francisStudents, verifiedAt: checkedAt },
  { id: "p0-usca-b14-francis-hang", student: "Hang Zhu", teacherId: "francis-yan-uiuc-p0-b14", company: "ByteDance", role: "Alumnus", kind: "reported", sector: "industry", note: "Francis Yan 本人学生页记录 Hang Zhu 去向 ByteDance。", source: q.francisStudents, verifiedAt: checkedAt },
];

const batch14RosterUrlByInstitution: Record<string, string> = {
  UIUC: "https://siebelschool.illinois.edu/about/people/all-faculty",
  Stanford: "https://www.cs.stanford.edu/people/faculty",
  MIT: "https://www.csail.mit.edu/people?roleFacets=Principal%20Investigators%2CCore%2FDual%2CAssociates%2CEmeritus",
};

export const candidatePriorityP0UsCanadaReadyBatch14RosterPromotions2026 = candidatePriorityP0UsCanadaReadyBatch14People2026.map((person) => ({
  unitUrl: batch14RosterUrlByInstitution[person.institution],
  rosterName: person.id === "francis-yan-uiuc-p0-b14" ? "Francis Yan" : person.name,
  atlasPersonId: person.id,
}));
export const people = [...candidatePriorityP0UsCanadaReadyBatch14People2026, ...candidatePriorityP0UsCanadaReadyBatch14SupportingPeople2026];
export const relationships = candidatePriorityP0UsCanadaReadyBatch14Relationships2026;
export const placements = candidatePriorityP0UsCanadaReadyBatch14Placements2026;
export const groupMembers = candidatePriorityP0UsCanadaReadyBatch14GroupMembers2026;
export const rosterPromotions = candidatePriorityP0UsCanadaReadyBatch14RosterPromotions2026;
