import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";
const checkedAt="2026-09-03";const source=(label:string,url:string,kind:Source["kind"],supports:string):Source=>({label,url,kind,supports,checkedAt});
const roster=source("Edinburgh Informatics · Academic staff","https://informatics.ed.ac.uk/people/academic-staff","official","University of Edinburgh School of Informatics 现任 academic staff 名录");
const oisinHome=source("Oisin Mac Aodha · Personal homepage","https://homepages.inf.ed.ac.uk/omacaod/","lab","Edinburgh 托管个人主页：现任职务、教育、导师、研究与官方个人照片");
const oisinTeam=source("Oisin Mac Aodha · Team","https://homepages.inf.ed.ac.uk/omacaod/team.html","lab","当前博士生及共同指导关系、历届成员");
const henryHome=source("Henry Gouk · Personal homepage","https://www.henrygouk.com/","lab","现任职务、教育与博士导师、研究方向、当前博士生和本人照片");
const fact=(label:string,value:string,s:Source)=>({label,value,source:s});
const person=(r:Omit<Person,"category"|"primary"|"status"|"introducedAt"|"lastVerifiedAt"|"portrait">&{portraitFile:string;portraitSource:Source}):Person=>({...r,category:"core",primary:true,status:"current independent PI · profile and official roster verified",introducedAt:checkedAt,lastVerifiedAt:checkedAt,portrait:{src:`portraits/candidate-p0-europe-second-round-batch-1-2026/${r.portraitFile}`,alt:`${r.name} 头像`,source:r.portraitSource}});
export const candidatePriorityP0EuropeSecondRoundBatch1People2026:Person[]=[
 person({id:"oisin-mac-aodha-edinburgh-p0-2026",name:"Oisin Mac Aodha",role:"Reader · Machine Learning",institution:"University of Edinburgh",region:"Europe",area:"Computer Vision · Machine Learning · AI for Conservation",tags:["Computer Vision","Machine Learning","3D Vision","AI for Conservation"],summary:"Edinburgh 机器学习 Reader，研究 3D 视觉、人机协同学习，以及面向生态与生物多样性监测的 AI。",stage:"senior",x:240,y:210,portraitFile:"oisin-mac-aodha.jpg",portraitSource:oisinHome,facts:[fact("当前任职","University of Edinburgh School of Informatics Reader（Associate Professor）in Machine Learning，并为 ELLIS Scholar。",oisinHome),fact("教育与学术训练","在 UCL 完成 MSc 与 PhD，导师为 Gabriel Brostow；本科毕业于 University of Galway。",oisinHome),fact("任职经历","曾在 UCL 随 Gabriel Brostow 与 Kate Jones 从事博士后研究，随后在 Caltech Computational Vision Lab 随 Pietro Perona 开展博士后工作。",oisinHome),fact("研究主线","研究计算机视觉和机器学习，重点包括 3D understanding、human-in-the-loop methods 与 conservation AI。",oisinHome),fact("学生体系","团队页列出 Ruchira Ray、Leonie Bossemeyer、Sebastian Day、Chris Lange、Bingchen Zhao 等 Edinburgh 博士生。",oisinTeam)],sources:[roster,oisinHome,oisinTeam]}),
 person({id:"henry-gouk-edinburgh-p0-2026",name:"Henry Gouk",role:"Lecturer · Machine Learning",institution:"University of Edinburgh",region:"Europe",area:"Reliable AI · Foundation Models · Autonomous Agents",tags:["Reliable AI","Foundation Models","AI Agents","Machine Learning"],summary:"Edinburgh 机器学习 Lecturer，研究如何在资源约束和分布变化下构建可靠的生成模型与自主智能体。",stage:"emerging",x:500,y:210,portraitFile:"henry-gouk.png",portraitSource:henryHome,facts:[fact("当前任职","University of Edinburgh School of Informatics Lecturer（Assistant Professor）in Machine Learning，并共同领导 Bayesian and Neural Systems group。",henryHome),fact("教育与学术训练","在 University of Waikato 完成博士学位，导师为 Bernhard Pfahringer 与 Eibe Frank。",henryHome),fact("任职经历","加入教职前在 University of Edinburgh 随 Timothy Hospedales 从事博士后研究。",henryHome),fact("研究主线","研究 AI engineering，关注生成模型和自主智能体的可靠构建、部署、维护与资源效率。",henryHome),fact("学生体系","个人主页列出 Cameron Barker、Taehoon Kim、Sanghyeok Choi 与 Sahel Torkamani 等共同指导博士生。",henryHome)],sources:[roster,henryHome]}),
];
export const candidatePriorityP0EuropeSecondRoundBatch1Relationships2026:Relationship[]=[];export const candidatePriorityP0EuropeSecondRoundBatch1Placements2026:StudentPlacement[]=[];export const candidatePriorityP0EuropeSecondRoundBatch1GroupMembers2026:GroupMember[]=[{id:"p0-eu-r2b1-oisin-ruchira-ray",teacherId:"oisin-mac-aodha-edinburgh-p0-2026",name:"Ruchira Ray",role:"Current PhD student",focus:"Computer vision and machine learning",source:oisinTeam},{id:"p0-eu-r2b1-henry-cameron-barker",teacherId:"henry-gouk-edinburgh-p0-2026",name:"Cameron Barker",role:"PhD student · co-advised with Elliot Crowley",focus:"Hardware-aware foundation models",source:henryHome}];
export const candidatePriorityP0EuropeSecondRoundBatch1RosterPromotions2026=[{unitUrl:roster.url,rosterName:"Oisin Mac Aodha",atlasPersonId:"oisin-mac-aodha-edinburgh-p0-2026"},{unitUrl:roster.url,rosterName:"Henry Gouk",atlasPersonId:"henry-gouk-edinburgh-p0-2026"}]as const;
export const people=candidatePriorityP0EuropeSecondRoundBatch1People2026;export const relationships=candidatePriorityP0EuropeSecondRoundBatch1Relationships2026;export const placements=candidatePriorityP0EuropeSecondRoundBatch1Placements2026;export const groupMembers=candidatePriorityP0EuropeSecondRoundBatch1GroupMembers2026;export const rosterPromotions=candidatePriorityP0EuropeSecondRoundBatch1RosterPromotions2026;
