import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const sources = {
  epflRoster: source("EPFL IC · Faculty members", "https://www.epfl.ch/schools/ic/about/faculty-members/", "official", "EPFL School of Computer and Communication Sciences 现任 faculty 名录"),
  mondada: source("EPFL People · Francesco Mondada", "https://people.epfl.ch/francesco.mondada?lang=en", "official", "EPFL Adjunct Professor 现职、教育、机器人研究、创业、博士生与官方头像"),
  argyraki: source("EPFL People · Katerina Argyraki", "https://people.epfl.ch/katerina.argyraki?lang=en", "official", "EPFL Associate Professor 现职、Stanford 博士、Arista 经历、网络研究、博士生与官方头像"),
  vaudenay: source("EPFL People · Serge Vaudenay", "https://people.epfl.ch/serge.vaudenay?lang=en", "official", "EPFL Full Professor 现职、ENS/Paris 7 教育、密码学研究、博士生与官方头像"),
  gastpar: source("EPFL People · Michael Gastpar", "https://people.epfl.ch/michael.gastpar?lang=en", "official", "EPFL Full Professor 现职、ETH/UIUC/EPFL 教育、信息论研究、博士生与官方头像"),
  macris: source("EPFL People · Nicolas Macris", "https://people.epfl.ch/nicolas.macris?lang=en", "official", "EPFL Adjunct Professor 现职、EPFL 博士、统计推断研究、博士生与官方头像"),
} satisfies Record<string, Source>;
const fact = (label: string, value: string, s: Source) => ({ label, value, source: s });
type Seed = Omit<Person, "category" | "primary" | "status" | "introducedAt" | "lastVerifiedAt" | "portrait"> & { portraitFile: string; portraitSource: Source };
const person = (s: Seed): Person => ({ ...s, category: "core", primary: true, status: "current independent PI · official profile verified", introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-europe-batch-18-2026/${s.portraitFile}`, alt: `${s.name} 头像`, source: s.portraitSource } });

export const candidatePriorityP0EuropeBatch18People2026: Person[] = [
  person({ id: "francesco-mondada-epfl-p0-2026", name: "Francesco Mondada", role: "Adjunct Professor · Miniature and Swarm Robotics", institution: "EPFL", region: "Europe", area: "Swarm Robotics · Educational Robotics · Mechatronics", tags: ["Robotics", "Swarm Robotics", "Bio-inspired Robotics", "Educational Technology"], summary: "EPFL 微型与群体机器人资深 PI，连接机器人平台、仿生群体智能、教育与科研工具产业化。", stage: "senior", x: 150, y: 210, portraitFile: "francesco-mondada.jpg", portraitSource: sources.mondada, facts: [fact("当前任职", "EPFL Adjunct Professor，围绕微型移动机器人、群体机器人和教育机器人主持研究与博士培养。", sources.mondada), fact("教育与学术训练", "1991 年获 EPFL 微工程硕士，1997 年获 EPFL 博士学位。", sources.mondada), fact("研究主线", "研究移动和模块化机器人的机电设计、仿生群体系统、动物—机器人交互与教育平台。", sources.mondada), fact("产业与创业", "博士期间联合创办 K-Team 并担任约五年 CEO 和董事长，参与开发 Khepera 机器人。", sources.mondada), fact("学生体系", "EPFL 官方页面列出 Manuel Bernal Lecina、Jérôme Brender、Valentina Ferraioli 等当前博士生。", sources.mondada)], sources: [sources.epflRoster, sources.mondada] }),
  person({ id: "katerina-argyraki-epfl-p0-2026", name: "Katerina Argyraki", role: "Associate Professor · Network Architecture Lab", institution: "EPFL", region: "Europe", area: "Network Architecture · Network Verification · Systems", tags: ["Computer Networks", "Network Verification", "Systems", "Internet Architecture"], summary: "EPFL Network Architecture Lab 负责人，研究可预测、可验证和透明的网络系统。", stage: "senior", x: 360, y: 210, portraitFile: "katerina-argyraki.jpg", portraitSource: sources.argyraki, facts: [fact("当前任职", "EPFL Computer Science Associate Professor，领导 Network Architecture Lab。", sources.argyraki), fact("教育与学术训练", "2007 年于 Stanford University 获博士学位。", sources.argyraki), fact("研究主线", "研究网络透明性与可预测性，覆盖网络架构、验证和可靠系统。", sources.argyraki), fact("产业经历", "加入 EPFL 前为 Arista Networks 早期员工。", sources.argyraki), fact("学生体系", "EPFL 页面列出 Muhammad Abdullah、Catalina Alvarez Inostroza、Mahdi Hosseini 等当前博士生。", sources.argyraki)], sources: [sources.epflRoster, sources.argyraki] }),
  person({ id: "serge-vaudenay-epfl-p0-2026", name: "Serge Vaudenay", role: "Full Professor · Security and Cryptography Laboratory", institution: "EPFL", region: "Europe", area: "Cryptography · Security · Privacy", tags: ["Cryptography", "Security", "Privacy", "Applied Cryptography"], summary: "EPFL Security and Cryptography Laboratory 创建者，长期研究现代密码协议、安全与隐私。", stage: "senior", x: 570, y: 210, portraitFile: "serge-vaudenay.jpg", portraitSource: sources.vaudenay, facts: [fact("当前任职", "1999 年起任 EPFL Professor，并创建 Security and Cryptography Laboratory。", sources.vaudenay), fact("教育与学术训练", "1989 年进入 École Normale Supérieure 主修数学，1992 年获数学 agrégation，1995 年在 University of Paris 7 获计算机科学博士。", sources.vaudenay), fact("研究主线", "研究密码学、安全和隐私，覆盖密码分析、协议设计与应用密码学。", sources.vaudenay), fact("任职经历", "博士后曾任 CNRS senior research fellow，并取得 habilitation à diriger des recherches。", sources.vaudenay), fact("学生体系", "EPFL 页面列出 Keng-Yu Chen、Max Duparc 与 Lewis Glabush 等当前博士生及历届博士生。", sources.vaudenay)], sources: [sources.epflRoster, sources.vaudenay] }),
  person({ id: "michael-gastpar-epfl-p0-2026", name: "Michael C. Gastpar", role: "Full Professor · Information in Networked Systems", institution: "EPFL", region: "Europe", area: "Information Theory · Signal Processing · Machine Learning", tags: ["Information Theory", "Signal Processing", "Communications", "Systems Neuroscience"], summary: "EPFL 网络信息系统教授，从网络信息论与编码延伸到信号处理、传感网络和系统神经科学。", stage: "senior", x: 780, y: 210, portraitFile: "michael-gastpar.jpg", portraitSource: sources.gastpar, facts: [fact("当前任职", "EPFL Full Professor，领导 Laboratory for Information in Networked Systems。", sources.gastpar), fact("教育与学术训练", "1997 年获 ETH Zurich 工程学位，1999 年获 UIUC 硕士，2002 年在 EPFL 完成博士论文。", sources.gastpar), fact("研究主线", "研究网络信息论、编码与信号处理，并应用于传感网络和系统神经科学。", sources.gastpar), fact("任职经历", "2003–2011 年在 UC Berkeley 任教并于 2008 年获 tenure，也曾任 Delft University of Technology Full Professor。", sources.gastpar), fact("学生体系", "EPFL 页面列出 Cemre Çadir、Millen Kanabar、Adrien Vandenbroucque 等当前博士生。", sources.gastpar)], sources: [sources.epflRoster, sources.gastpar] }),
  person({ id: "nicolas-macris-epfl-p0-2026", name: "Nicolas Macris", role: "Adjunct Professor · Statistical Mechanics of Inference", institution: "EPFL", region: "Europe", area: "Inference Theory · Statistical Learning · Information Theory", tags: ["Inference", "Learning Theory", "Information Theory", "Statistical Physics"], summary: "EPFL 推断统计力学实验室负责人，用统计物理与概率方法研究高维推断、学习理论和纠错码。", stage: "senior", x: 990, y: 210, portraitFile: "nicolas-macris.jpg", portraitSource: sources.macris, facts: [fact("当前任职", "EPFL Adjunct Professor，领导 Statistical Mechanics of Inference in Large Systems 实验室。", sources.macris), fact("教育与学术训练", "在 EPFL 获理论物理博士，随后在 Rutgers University 数学系开展研究。", sources.macris), fact("研究主线", "研究高维推断与学习理论、纠错与图模型，以及它们和无序系统统计力学的联系。", sources.macris), fact("任职时间线", "2005 年起进入 EPFL Communication Theories Laboratory 与 Information Processing Group，并长期开展跨校访问合作。", sources.macris), fact("学生体系", "EPFL 页面列出 Anand Jerry George、Anastasia Remizova、Perrine Vantalon 等当前博士生。", sources.macris)], sources: [sources.epflRoster, sources.macris] }),
];

export const candidatePriorityP0EuropeBatch18Relationships2026: Relationship[] = [];
export const candidatePriorityP0EuropeBatch18Placements2026: StudentPlacement[] = [];
export const candidatePriorityP0EuropeBatch18GroupMembers2026: GroupMember[] = [
  { id: "p0-eu18-mondada-manuel-bernal", teacherId: "francesco-mondada-epfl-p0-2026", name: "Manuel Bernal Lecina", role: "Current PhD student", focus: "Robotics", source: sources.mondada },
  { id: "p0-eu18-argyraki-muhammad-abdullah", teacherId: "katerina-argyraki-epfl-p0-2026", name: "Muhammad Abdullah", role: "Current PhD student", focus: "Network architecture", source: sources.argyraki },
  { id: "p0-eu18-vaudenay-keng-yu-chen", teacherId: "serge-vaudenay-epfl-p0-2026", name: "Keng-Yu Chen", role: "Current PhD student", focus: "Security and cryptography", source: sources.vaudenay },
  { id: "p0-eu18-gastpar-cemre-cadir", teacherId: "michael-gastpar-epfl-p0-2026", name: "Cemre Çadir", role: "Current PhD student", focus: "Information in networked systems", source: sources.gastpar },
  { id: "p0-eu18-macris-anand-george", teacherId: "nicolas-macris-epfl-p0-2026", name: "Anand Jerry George", role: "Current PhD student", focus: "Inference and learning theory", source: sources.macris },
];
export const candidatePriorityP0EuropeBatch18RosterPromotions2026 = [
  { unitUrl: "https://www.epfl.ch/schools/ic/about/faculty-members/", rosterName: "Francesco Mondada", atlasPersonId: "francesco-mondada-epfl-p0-2026" },
  { unitUrl: "https://www.epfl.ch/schools/ic/about/faculty-members/", rosterName: "Katerina Argyraki", atlasPersonId: "katerina-argyraki-epfl-p0-2026" },
  { unitUrl: "https://www.epfl.ch/schools/ic/about/faculty-members/", rosterName: "Serge Vaudenay", atlasPersonId: "serge-vaudenay-epfl-p0-2026" },
  { unitUrl: "https://www.epfl.ch/schools/ic/about/faculty-members/", rosterName: "Michael C. Gastpar", atlasPersonId: "michael-gastpar-epfl-p0-2026" },
  { unitUrl: "https://www.epfl.ch/schools/ic/about/faculty-members/", rosterName: "Nicolas Macris", atlasPersonId: "nicolas-macris-epfl-p0-2026" },
] as const;
export const people = candidatePriorityP0EuropeBatch18People2026;
export const relationships = candidatePriorityP0EuropeBatch18Relationships2026;
export const placements = candidatePriorityP0EuropeBatch18Placements2026;
export const groupMembers = candidatePriorityP0EuropeBatch18GroupMembers2026;
export const rosterPromotions = candidatePriorityP0EuropeBatch18RosterPromotions2026;
