import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const src = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const f = (label: string, value: string, source: Source) => ({ label, value, source });
const s = {
  pilanci: src("Stanford Profiles · Mert Pilanci", "https://profiles.stanford.edu/mert-pilanci", "official", "Current appointment, Berkeley doctorate, Stanford postdoctoral training and machine-learning research"),
  pilanciStudent: src("Aaron Mishkin · Stanford personal profile", "https://cs.stanford.edu/~amishkin/", "profile", "Mert Pilanci identified as doctoral supervisor"),
  boyd: src("Stanford Engineering · Stephen Boyd", "https://engineering.stanford.edu/people/stephen-boyd", "official", "Current professorship, Harvard and Berkeley education and optimization research"),
  boydHome: src("Stephen Boyd · Stanford personal profile", "https://web.stanford.edu/~boyd/", "profile", "Research programme, publications and teaching"),
  boydPeople: src("Stephen Boyd · Stanford student list", "https://web.stanford.edu/~boyd/people.html", "profile", "Current and former doctoral students and destinations"),
  weissman: src("Stanford Engineering · Tsachy Weissman", "https://engineering.stanford.edu/people/tsachy-weissman", "official", "Current endowed professorship, Technion education and ML and information-theory research"),
  weissmanHome: src("Tsachy Weissman · Stanford research group", "https://web.stanford.edu/~tsachy/research", "profile", "Current and former doctoral students and collaborators"),
};
const portrait = (name: string, file: string, url: string) => ({ src: `portraits/candidate-p0-us-canada-stanford-tail-2026/${file}.jpg`, alt: `${name} 官方头像`, source: src(`Stanford portrait · ${name}`, url, "official", "Official university portrait") });

export const candidatePriorityP0UsCanadaReadyBatch9People2026: Person[] = [
  { id: "mert-pilanci-stanford-p0-b9", name: "Mert Pilanci", role: "Assistant Professor of Electrical Engineering", institution: "Stanford", region: "United States", area: "Machine Learning · Convex Optimization · Neural Networks", tags: ["机器学习", "优化", "神经网络", "信号处理"], summary: "研究机器学习与神经网络全局优化理论的 Stanford PI。", stage: "emerging", category: "core", status: "current independent PI · official faculty profile verified", primary: true, x: 120, y: 120, introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: portrait("Mert Pilanci", "mert-pilanci", "https://profiles.stanford.edu/proxy/api/cap/profiles/84036/resources/profilephoto/350x522.1787872051.jpg"), sources: [s.pilanci, s.pilanciStudent], facts: [f("当前任职", "Stanford Electrical Engineering 助理教授。", s.pilanci), f("教育与学术训练", "UC Berkeley EECS PhD（2016）；Stanford 博士后（2017）。", s.pilanci), f("研究主线", "神经网络、机器学习、数学优化、信息论和信号处理。", s.pilanci), f("公开指导", "Aaron Mishkin 的 Stanford 个人页明确写明由 Mert Pilanci 指导博士研究。", s.pilanciStudent)] },
  { id: "stephen-boyd-stanford-p0-b9", name: "Stephen P. Boyd", role: "Samsung Professor in the School of Engineering", institution: "Stanford", region: "United States", area: "Convex Optimization · Machine Learning · Control", tags: ["凸优化", "机器学习", "控制", "信号处理"], summary: "以凸优化基础方法深刻影响机器学习、控制与信号处理的 Stanford 资深教授。", stage: "senior", category: "core", status: "current independent PI · official faculty profile verified", primary: true, x: 300, y: 120, introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: portrait("Stephen P. Boyd", "stephen-boyd", "https://profiles.stanford.edu/proxy/api/cap/profiles/18537/resources/profilephoto/350x522.1787872051.jpg"), sources: [s.boyd, s.boydHome, s.boydPeople], facts: [f("当前任职", "Stanford Samsung Professor in the School of Engineering、Electrical Engineering 教授。", s.boyd), f("教育与学术训练", "Harvard Mathematics AB（1980）；UC Berkeley EECS PhD（1985）。", s.boyd), f("研究主线", "凸优化及其在控制、信号处理、机器学习和金融中的应用。", s.boyd), f("学生体系", "本人 Stanford 学生页逐名记录当前及历届博士生与去向。", s.boydPeople)] },
  { id: "tsachy-weissman-stanford-p0-b9", name: "Tsachy Weissman", role: "Robert and Barbara Kleist Professor", institution: "Stanford", region: "United States", area: "Information Theory · Machine Learning · Statistical Signal Processing", tags: ["信息论", "机器学习", "压缩", "统计信号处理"], summary: "连接信息论、压缩、统计信号处理与机器学习的 Stanford 资深 PI。", stage: "senior", category: "core", status: "current independent PI · official faculty profile verified", primary: true, x: 480, y: 120, introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: portrait("Tsachy Weissman", "tsachy-weissman", "https://profiles.stanford.edu/proxy/api/cap/profiles/41890/resources/profilephoto/350x522.1787872051.jpg"), sources: [s.weissman, s.weissmanHome], facts: [f("当前任职", "Stanford Robert and Barbara Kleist Professor in the School of Engineering。", s.weissman), f("教育与学术训练", "Technion Electrical Engineering B.Sc.（1997）与 PhD（2001）。", s.weissman), f("研究主线", "信息论、数据压缩、统计信号处理与机器学习。", s.weissman), f("公开团队", "本人 Stanford 研究页列出当前与历届博士生以及合作研究者。", s.weissmanHome)] },
];
export const candidatePriorityP0UsCanadaReadyBatch9SupportingPeople2026: Person[] = [{ id: "aaron-mishkin-student-p0-b9", name: "Aaron Mishkin", role: "PhD Student", institution: "Stanford", region: "United States", area: "Optimization for Machine Learning", tags: ["博士生", "优化"], summary: "Mert Pilanci 的 Stanford 博士生。", stage: "adjacent", category: "historical", status: "supporting student node · relationship evidence only", sources: [s.pilanciStudent], x: 120, y: 220, primary: false, lastVerifiedAt: checkedAt }];
export const candidatePriorityP0UsCanadaReadyBatch9Relationships2026: Relationship[] = [{ id: "candidate-p0-usca-b9-pilanci-mishkin", from: "mert-pilanci-stanford-p0-b9", to: "aaron-mishkin-student-p0-b9", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Aaron Mishkin 的 Stanford 个人页明确写明由 Mert Pilanci 指导博士研究。", source: s.pilanciStudent, verified: true }];
export const candidatePriorityP0UsCanadaReadyBatch9GroupMembers2026: GroupMember[] = [{ id: "candidate-p0-usca-b9-boyd-group", teacherId: "stephen-boyd-stanford-p0-b9", name: "Boyd group students", role: "Current and former PhD students", source: s.boydPeople }, { id: "candidate-p0-usca-b9-weissman-group", teacherId: "tsachy-weissman-stanford-p0-b9", name: "Weissman group students", role: "Current and former doctoral students", source: s.weissmanHome }];
export const candidatePriorityP0UsCanadaReadyBatch9Placements2026: StudentPlacement[] = [];
export const candidatePriorityP0UsCanadaReadyBatch9RosterPromotions2026 = candidatePriorityP0UsCanadaReadyBatch9People2026.map((person) => ({ unitUrl: "https://ee.stanford.edu/people/faculty", rosterName: person.name, atlasPersonId: person.id }));
export const people = [...candidatePriorityP0UsCanadaReadyBatch9People2026, ...candidatePriorityP0UsCanadaReadyBatch9SupportingPeople2026];
export const relationships = candidatePriorityP0UsCanadaReadyBatch9Relationships2026;
export const placements = candidatePriorityP0UsCanadaReadyBatch9Placements2026;
export const groupMembers = candidatePriorityP0UsCanadaReadyBatch9GroupMembers2026;
export const rosterPromotions = candidatePriorityP0UsCanadaReadyBatch9RosterPromotions2026;
