import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";
const checkedAt = "2026-09-03";
const source = (label: string, url: string, supports: string): Source => ({ label, url, kind: "official", supports, checkedAt });
const roster = source("EPFL IC · Faculty members", "https://www.epfl.ch/schools/ic/about/faculty-members/", "EPFL IC 现任教师名录");
const goosProfile = source("EPFL People · Mika Göös", "https://people.epfl.ch/mika.goos?lang=en", "EPFL 现任职务、课程与官方头像");
const goosLab = source("EPFL Theory · Mika Göös", "https://ic-people.epfl.ch/~goos/", "教育、博士导师、研究主题、博士后经历与当前团队");
const shkelProfile = source("EPFL People · Yanina Shkel", "https://people.epfl.ch/yanina.shkel?lang=en", "现任职务、课程、博士生与官方头像");
const shkelLab = source("EPFL Theory · Yanina Shkel", "https://theory.epfl.ch/yanina/", "教育、Princeton/UIUC/EPFL 履历、产业经历与研究主题");
const kashyapProfile = source("EPFL People · Sanidhya Kashyap", "https://people.epfl.ch/sanidhya.kashyap?lang=en", "现任职务、研究主题、课程、博士生与官方头像");
const kashyapBio = source("EPFL · Sanidhya Kashyap inaugural lecture", "https://memento.epfl.ch/event/inaugural-lectures-prof-sanidhya-kashyap-and-prof-/", "Georgia Tech 博士、导师与系统研究履历");
const kaeserProfile = source("EPFL People · Tanja Käser", "https://people.epfl.ch/tanja.kaeser?lang=en", "EPFL 现任职务与官方头像");
const kaeserTeam = source("EPFL ML4ED · Team", "https://www.epfl.ch/labs/ml4ed/team/", "实验室负责人、现任博士生和研究团队");
const kaeserBio = source("EPFL · Three questions for Tanja Käser", "https://actu.epfl.ch/news/three-questions-for-ic-professor-tanja-kaser-2", "ETH Zurich 硕博教育、SDSC 任职、AI 教育研究与加入 EPFL 履历");
const fact = (label: string, value: string, evidence: Source) => ({ label, value, source: evidence });
const person = (row: Omit<Person, "category" | "primary" | "status" | "introducedAt" | "lastVerifiedAt" | "portrait"> & { portraitFile: string; portraitSource: Source }): Person => ({ ...row, category: "core", primary: true, status: "current independent PI · official profile verified", introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-europe-full-batch-3-2026/${row.portraitFile}`, alt: `${row.name} 头像`, source: row.portraitSource } });
export const candidatePriorityP0EuropeFullBatch3People2026: Person[] = [
  person({ id: "mika-goos-epfl-p0-full-2026", name: "Mika Göös", role: "Assistant Professor · Theory Group", institution: "EPFL", region: "Europe", area: "Computational Complexity · Communication Complexity", tags: ["Complexity Theory", "Communication Complexity", "Lower Bounds", "Theoretical Computer Science"], summary: "EPFL Theory Group 助理教授，研究计算下界、通信复杂度与查询复杂度。", stage: "emerging", x: 210, y: 210, portraitFile: "mika-goos.jpg", portraitSource: goosProfile, facts: [fact("当前任职", "EPFL Theory Group Assistant Professor。", goosLab), fact("教育与学术训练", "获 Aalto University 学士、University of Oxford 硕士，并在 University of Toronto 完成博士，导师为 Toniann Pitassi。", goosLab), fact("任职经历", "加入 EPFL 前先后在 Stanford、Princeton IAS 与 Harvard 从事博士后研究。", goosLab), fact("研究主线", "以通信复杂度和查询复杂度研究理论计算机科学中的不可能性与计算下界。", goosLab), fact("学生体系", "个人主页列出 Weiqiang Yuan、Ziyi Guan、Anastasia Sofronova、Artur Riazanov、Valentin Imbach 与 Polina Stankevich 等当前博士生。", goosLab)], sources: [roster, goosProfile, goosLab] }),
  person({ id: "yanina-shkel-epfl-p0-full-2026", name: "Yanina Shkel", role: "Assistant Professor · Information Processing Group", institution: "EPFL", region: "Europe", area: "Information Theory · Privacy · Learning Theory", tags: ["Information Theory", "Privacy", "Learning Theory", "Cryptography"], summary: "EPFL 信息处理方向助理教授，以信息论、学习论和密码学研究隐私、保密与数据效用边界。", stage: "emerging", x: 430, y: 210, portraitFile: "yanina-shkel.jpg", portraitSource: shkelProfile, facts: [fact("当前任职", "EPFL Assistant Professor，隶属 Information Processing Group 并主持信息数学研究。", shkelProfile), fact("教育与学术训练", "2014 年于 University of Wisconsin–Madison 获博士学位。", shkelLab), fact("任职经历", "曾任 UIUC 博士后、Princeton research scholar，并于 2019–2023 年在 EPFL 任 Scientist。", shkelLab), fact("研究主线", "研究信息论、学习论、编码与密码学，重点包括差分隐私、最大泄漏和隐私—效用权衡。", shkelLab), fact("学生体系", "EPFL 官方页面列出 Cemre Çadir、Serhat Emre Coban、Salim Najib 与 Anuj Yadav 为现任博士生。", shkelProfile)], sources: [roster, shkelProfile, shkelLab] }),
  person({ id: "sanidhya-kashyap-epfl-p0-full-2026", name: "Sanidhya Kashyap", role: "Tenure Track Assistant Professor · RS3Lab", institution: "EPFL", region: "Europe", area: "Systems · Operating Systems · Data-intensive Systems", tags: ["Systems", "Operating Systems", "Databases", "Software Testing"], summary: "EPFL Robust Scalable Systems Software Lab 负责人，研究异构硬件上的高性能、可靠系统软件。", stage: "emerging", x: 650, y: 210, portraitFile: "sanidhya-kashyap.jpg", portraitSource: kashyapProfile, facts: [fact("当前任职", "EPFL Tenure Track Assistant Professor，领导 Robust Scalable Systems Software Lab。", kashyapProfile), fact("教育与学术训练", "2020 年于 Georgia Tech 获博士学位，导师为 Taesoo Kim 与 Changwoo Min。", kashyapBio), fact("研究主线", "研究面向异构硬件的高性能、可靠系统软件，覆盖操作系统、数据库、并发、调度、网络与 fuzzing。", kashyapProfile), fact("教学范围", "在 EPFL 开设 Advanced Operating Systems、Computer Systems 与 Data-intensive Systems。", kashyapProfile), fact("学生体系", "EPFL 页面列出 Musa Ünal、Lucas Lopes Cendes、Vishal Gupta、Yueyang Pan、Tao Lyu 等博士生。", kashyapProfile)], sources: [roster, kashyapProfile, kashyapBio] }),
  person({ id: "tanja-kaeser-epfl-p0-full-2026", name: "Tanja Käser", role: "Tenure Track Assistant Professor · ML4ED", institution: "EPFL", region: "Europe", area: "AI in Education · Machine Learning · Human-Centered AI", tags: ["AI in Education", "Machine Learning", "Human-Centered AI", "Learning Analytics"], summary: "EPFL ML4ED 实验室负责人，用机器学习建模学习过程并设计可解释、个性化的教育系统。", stage: "emerging", x: 870, y: 210, portraitFile: "tanja-kaeser.jpg", portraitSource: kaeserProfile, facts: [fact("当前任职", "EPFL Tenure Track Assistant Professor，领导 ML4ED 实验室。", kaeserTeam), fact("教育与学术训练", "在 ETH Zurich 完成计算机科学硕士和博士学位。", kaeserBio), fact("任职经历", "加入 EPFL 前任 Swiss Data Science Center senior data scientist，并曾在 Stanford 与 ETH Zurich 开展博士后研究。", kaeserBio), fact("研究主线", "以 AI、机器学习、算法和数据挖掘建模人类学习与行为，服务个性化教育。", kaeserBio), fact("学生体系", "ML4ED 官方团队页设有 PhD students 名录，并记录实验室现任博士培养体系。", kaeserTeam)], sources: [roster, kaeserProfile, kaeserTeam, kaeserBio] }),
];
export const candidatePriorityP0EuropeFullBatch3Relationships2026: Relationship[] = [];
export const candidatePriorityP0EuropeFullBatch3Placements2026: StudentPlacement[] = [];
export const candidatePriorityP0EuropeFullBatch3GroupMembers2026: GroupMember[] = [
  { id: "p0-eu-full3-goos-anastasia-sofronova", teacherId: "mika-goos-epfl-p0-full-2026", name: "Anastasia Sofronova", role: "Current PhD student", focus: "Computational complexity", source: goosLab },
  { id: "p0-eu-full3-shkel-salim-najib", teacherId: "yanina-shkel-epfl-p0-full-2026", name: "Salim Najib", role: "Current PhD student", focus: "Information theory and privacy", source: shkelProfile },
  { id: "p0-eu-full3-kashyap-musa-unal", teacherId: "sanidhya-kashyap-epfl-p0-full-2026", name: "Musa Ünal", role: "Current PhD student", focus: "Systems", source: kashyapProfile },
  { id: "p0-eu-full3-kaeser-fares-fawzi", teacherId: "tanja-kaeser-epfl-p0-full-2026", name: "Fares Fawzi", role: "Doctoral Assistant", focus: "AI in education", source: kaeserTeam },
];
export const candidatePriorityP0EuropeFullBatch3RosterPromotions2026 = [
  { unitUrl: roster.url, rosterName: "Mika Göös", atlasPersonId: "mika-goos-epfl-p0-full-2026" },
  { unitUrl: roster.url, rosterName: "Yanina Shkel", atlasPersonId: "yanina-shkel-epfl-p0-full-2026" },
  { unitUrl: roster.url, rosterName: "Sanidhya Kashyap", atlasPersonId: "sanidhya-kashyap-epfl-p0-full-2026" },
  { unitUrl: roster.url, rosterName: "Tanja Kaeser", atlasPersonId: "tanja-kaeser-epfl-p0-full-2026" },
] as const;
export const people = candidatePriorityP0EuropeFullBatch3People2026; export const relationships = candidatePriorityP0EuropeFullBatch3Relationships2026; export const placements = candidatePriorityP0EuropeFullBatch3Placements2026; export const groupMembers = candidatePriorityP0EuropeFullBatch3GroupMembers2026; export const rosterPromotions = candidatePriorityP0EuropeFullBatch3RosterPromotions2026;
