import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, supports, checkedAt });
const sources = {
  epflRoster: source("EPFL IC · Faculty members", "https://www.epfl.ch/schools/ic/about/faculty-members/", "official", "EPFL IC 现任教授名录"),
  cambridgeRoster: source("Cambridge CST · Faculty directory", "https://www.cst.cam.ac.uk/people/directory/faculty?lang=en", "official", "Cambridge CST 现任 faculty 名录"),
  cambridgePhd: source("Cambridge CST · PhD students by supervisor", "https://www.cl.cam.ac.uk/lists/phd/supervisor.html", "official", "Cambridge 官方逐名博士生、论文和导师记录"),
  edinburghRoster: source("Edinburgh Informatics · Academic staff", "https://informatics.ed.ac.uk/people/academic-staff", "official", "Edinburgh Informatics 现任 academic staff 名录"),

  koch: source("EPFL People · Christoph Koch", "https://people.epfl.ch/christoph.koch?lang=en", "official", "现任职务、TU Vienna/CERN 博士训练、任职履历、研究与逐名博士生/校友"),
  moraud: source("EPFL People · Eduardo Moraud", "https://people.epfl.ch/eduardo.moraud?lang=en", "official", "现任 tenure-track PI、UPM/École des Mines/Edinburgh/ETH 教育训练、履历、研究与逐名博士生"),
  kaplan: source("EPFL People · Frédéric Kaplan", "https://people.epfl.ch/frederic.kaplan?lang=en", "official", "现任教授和博士项目负责人、AI/数字人文研究及逐名博士生"),
  kaplanEducation: source("EPFL Infoscience · Frédéric Kaplan author biography", "https://infoscience.epfl.ch/bitstreams/b760213d-a8b0-465e-b435-5f07809add55/download", "publication", "Télécom Paris 工程教育、Paris VI 人工智能博士和 Sony CSL 研究履历"),
  huang: source("EPFL People · Jeffrey Huang", "https://people.epfl.ch/jeffrey.huang?lang=en", "official", "现任教授、ETH/Harvard 教育、MIT/Harvard/SUTD/EPFL 履历、研究和逐名博士生"),
  hartley: source("EPFL People · Mary-Anne Hartley", "https://people.epfl.ch/mary-anne.hartley", "official", "现任 Adjunct Professor、LiGHT Laboratory 与逐名博士生"),
  hartleyBio: source("Carnegie Mellon University Africa · Mary-Anne Hartley seminar biography", "https://www.africa.engineering.cmu.edu/events/2024/02/28-upanzi.html", "official", "Pretoria/Cape Town/Lausanne/LSHTM 教育与 EPFL/Yale/CMU 研究履历"),
  hartleyProject: source("EPFL · Enhancing Maternal Health in Zanzibar", "https://www.epfl.ch/innovation/domains/tech4dev/health-challenges/enhancing-maternal-health-in-zanzibar/", "official", "Mary-Anne Hartley 团队、Trevor Brokowski 博士生和跨机构合作"),
  greaves: source("Cambridge CST · David Greaves", "https://www.cst.cam.ac.uk/people/djg11", "official", "现任 faculty 职务、研究和教学"),
  greavesBio: source("David Greaves · Cambridge-hosted short biography", "https://www.cl.cam.ac.uk/~djg11/shortbiog.html", "profile", "Cambridge 博士、Martin Richards/Andy Hopper 指导、Olivetti/IBM/Plessey 履历与产业活动"),
  fiore: source("Cambridge CST · Marcelo Fiore", "https://www.cst.cam.ac.uk/people/mpf23", "official", "现任 Professor in Mathematical Foundations of Computer Science 与研究主题"),
  fioreHome: source("Marcelo Fiore · Cambridge academic homepage", "https://www.cl.cam.ac.uk/~mpf23/", "profile", "现任教授、研究主线、博士论文专著与教学"),
  fioreTraining: source("Cambridge · Domain Theory for Concurrency", "https://www.cl.cam.ac.uk/~gw104/EPSRCProp04.pdf", "official", "博士论文、Gordon Plotkin 组研究训练、Sussex 与 Cambridge 任职轨迹"),

  keller: source("Edinburgh Research Explorer · Frank Keller", "https://www.research.ed.ac.uk/en/persons/frank-keller/", "official", "现任教授、Stuttgart/Edinburgh 教育、任职和语言视觉研究"),
  kellerPeople: source("Frank Keller · Edinburgh people page", "https://homepages.inf.ed.ac.uk/keller/people/", "profile", "逐名博士生、校友及其学术/产业去向"),
  shay: source("Edinburgh Research Explorer · Shay Cohen", "https://www.research.ed.ac.uk/en/persons/shay-cohen/", "official", "现任 Reader、Tel Aviv/CMU 教育、Columbia 博后与 NLP/ML 研究"),
  shayPeople: source("Shay Cohen · Edinburgh academic homepage", "https://homepages.inf.ed.ac.uk/scohen/", "profile", "逐名当前博士生、博士校友、博士后及 Google/Amazon/NRC 等去向"),
  simon: source("Edinburgh Research Explorer · Simon King", "https://www.research.ed.ac.uk/en/persons/simon-king/", "official", "现任教授与 CSTR 主任、Cambridge/Edinburgh 教育、履历和逐名博士生"),
  wenfei: source("Edinburgh Research Explorer · Wenfei Fan", "https://www.research.ed.ac.uk/en/persons/wenfei-fan/", "official", "现任 Chair、PKU/UPenn 教育、数据库研究、院士荣誉与产业项目"),
  wenfeiStudents: source("Edinburgh LFCS · Current students", "https://informatics.ed.ac.uk/lfcs/study-with-us/current-students", "official", "LFCS 官方逐名博士生及 Wenfei Fan 指导关系"),
  rovatsos: source("Edinburgh Research Explorer · Michael Rovatsos", "https://www.research.ed.ac.uk/en/persons/michael-rovatsos/", "official", "现任 Personal Chair、Bayes Centre 主任、Saarbrücken/TUM 教育、AI 研究与项目合作"),
  rovatsosStudents: source("Edinburgh profile · Michael Rovatsos", "https://edwebprofiles.ed.ac.uk/node/95826", "official", "逐名毕业博士生与指导关系"),
  webb: source("Edinburgh Research Explorer · Barbara Webb", "https://www.research.ed.ac.uk/en/persons/barbara-webb/", "official", "现任 Personal Chair in Biorobotics、PI 项目和研究主题"),
  webbHome: source("Barbara Webb · Edinburgh academic homepage", "https://homepages.inf.ed.ac.uk/bwebb/", "profile", "Sydney/Edinburgh 教育、Stirling/Nottingham/Edinburgh 任职与研究"),
  webbStudent: source("Edinburgh IPAB archive · Mark Payne", "https://www.ipab.inf.ed.ac.uk/archive/news04.html", "official", "Mark Payne 博士由 Barbara Webb 指导"),
  fisher: source("Edinburgh Research Explorer · Bob Fisher", "https://www.research.ed.ac.uk/en/persons/bob-fisher/", "official", "现任 Chair in Computer Vision、Caltech/Stanford/Edinburgh 教育、研究、创业与项目"),
  fisherHome: source("Bob Fisher · Edinburgh academic homepage", "https://homepages.inf.ed.ac.uk/rbf/", "profile", "任职时间轴、研究、逐名当前博士生/研究人员和博士校友"),
  minervini: source("Edinburgh Research Explorer · Pasquale Minervini", "https://www.research.ed.ac.uk/en/persons/pasquale-minervini/", "official", "现任 NLP Lecturer、研究产出和 Huawei/EPSRC 项目"),
  minerviniPeople: source("Edinburgh Informatics · Pasquale Minervini", "https://people.inf.ed.ac.uk/Pasquale_Minervini.html", "official", "Edinburgh 托管个人主页与本人照片"),
  minerviniBio: source("UCL Engineering · Pasquale Minervini biography", "https://www.ucl.ac.uk/engineering/events/2021/jan/logical-journeys-webinar-world-logic-day-event", "official", "Bari 博士、UCL 博后、Fujitsu 与 INSIGHT 产业研究履历"),
  minerviniProject: source("Edinburgh · EIDF GPU service", "https://digitalresearchservices.ed.ac.uk/new-eidf-gpu-service", "official", "Pasquale Minervini 指导 Aryo Gema 和 Piotr Nawrot 的具名研究项目"),
} satisfies Record<string, Source>;

const fact = (label: string, value: string, s: Source) => ({ label, value, source: s });
type Seed = Omit<Person, "category" | "primary" | "status" | "introducedAt" | "lastVerifiedAt" | "portrait"> & { portraitFile: string; portraitSource: Source };
const person = (s: Seed): Person => ({ ...s, category: "core", primary: true, status: "current independent PI · strict fifth-round verification", introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/candidate-p0-europe-fifth-round-batch-1-2026/${s.portraitFile}`, alt: `${s.name} 头像`, source: s.portraitSource } });

export const candidatePriorityP0EuropeFifthRoundBatch1People2026: Person[] = [
  person({ id: "christoph-koch-epfl-p0-r5", name: "Christoph Koch", role: "Full Professor · Director, DATA Lab", institution: "EPFL", region: "Europe", area: "Data Management · Database Systems · Query Languages", tags: ["Data Management", "Databases", "Query Processing", "Programming Languages"], summary: "EPFL DATA Lab 负责人，研究数据库理论、查询语言与高性能数据系统。", stage: "senior", x: 180, y: 260, portraitFile: "christoph-koch.jpg", portraitSource: sources.koch, facts: [fact("当前任职", "EPFL Computer Science Full Professor，并领导 Data Analysis Theory and Applications Laboratory。", sources.koch), fact("教育与学术训练", "2001 年在 TU Vienna 与 CERN 完成人工智能博士训练，2004 年取得 Habilitation。", sources.koch), fact("研究主线", "研究数据库理论、查询语言、查询处理和高性能数据管理系统。", sources.koch), fact("学生体系", "EPFL People 页面列出 Christian Fattebert、Zhekai Jiang、Hanbit Lee、Kseniya Shastakova 等当前博士生及多位校友。", sources.koch)], sources: [sources.epflRoster, sources.koch] }),
  person({ id: "eduardo-moraud-epfl-p0-r5", name: "Eduardo Moraud", role: "Tenure-Track Assistant Professor · SPARK", institution: "EPFL", region: "Europe", area: "Adaptive Neuromodulation · Neural Engineering · AI", tags: ["Neural Engineering", "Adaptive Neuromodulation", "Multimodal AI", "Parkinson's Disease"], summary: "EPFL SPARK 负责人，将多模态神经/运动信号解码用于闭环神经调控。", stage: "emerging", x: 420, y: 260, portraitFile: "eduardo-moraud.jpg", portraitSource: sources.moraud, facts: [fact("当前任职", "2026 年加入 EPFL Neuro-X，任 tenure-track Assistant Professor 并领导 Systems for Adaptive neuRomodulation。", sources.moraud), fact("教育与学术训练", "在 UPM Madrid 与 École des Mines de Paris 学习电气与控制工程，获 Edinburgh AI 硕士和 ETH Zurich Neural Engineering 博士。", sources.moraud), fact("研究主线", "研究多模态神经和运动信号解码、闭环神经调控与神经工程 AI。", sources.moraud), fact("学生体系", "EPFL 页面逐名列出 Flore Munier-Jolain、Olivia Ruggaber、Paula Sanchez Lopez 和 Ruijia Wang 为博士生。", sources.moraud)], sources: [sources.epflRoster, sources.moraud] }),
  person({ id: "frederic-kaplan-epfl-p0-r5", name: "Frédéric Kaplan", role: "Associate Professor · Director, Digital Humanities", institution: "EPFL", region: "Europe", area: "Digital Humanities · AI · Language Evolution", tags: ["Digital Humanities", "Artificial Intelligence", "Language Evolution", "Multi-Agent Systems"], summary: "EPFL 数字人文带头人，把 AI、语言演化与大规模文化数据基础设施连接起来。", stage: "senior", x: 660, y: 260, portraitFile: "frederic-kaplan.jpg", portraitSource: sources.kaplan, facts: [fact("当前任职", "EPFL Associate Professor、Digital Humanities Laboratory 主任及 Digital Humanities 博士项目主任。", sources.kaplan), fact("教育与学术训练", "毕业于 Télécom Paris 工程师项目，并在 Université Paris VI 获人工智能博士学位。", sources.kaplanEducation), fact("研究主线", "研究数字人文、人工智能、语言演化、多智能体系统与大规模文化数据。", sources.kaplanEducation), fact("学生体系", "EPFL People 页面列出 Tommy Bruzzese、Ziyi Liu、Alexander Rusnak 等当前博士生及十余位毕业博士生。", sources.kaplan)], sources: [sources.epflRoster, sources.kaplan, sources.kaplanEducation] }),
  person({ id: "jeffrey-huang-epfl-p0-r5", name: "Jeffrey Huang", role: "Full Professor · Director, Media x Design Lab", institution: "EPFL", region: "Europe", area: "Generative Design · Urban Digital Twins · AI in Architecture", tags: ["Generative AI", "Digital Twins", "Design", "Computational Urbanism"], summary: "EPFL Media x Design Lab 负责人，研究生成式空间 AI、城市数字孪生与人机协同设计。", stage: "senior", x: 900, y: 260, portraitFile: "jeffrey-huang.jpg", portraitSource: sources.huang, facts: [fact("当前任职", "EPFL IC 与 ENAC 联合 Full Professor，并领导 Media x Design Laboratory。", sources.huang), fact("教育与学术训练", "获 ETH Zurich DiplArch，以及 Harvard University 硕士与博士学位。", sources.huang), fact("研究主线", "研究生成式空间 AI、城市数字孪生、计算城市学和人机协同设计。", sources.huang), fact("学生体系", "EPFL People 页面列 Gianna Ledermann、Ga In Sim 为其当前博士生，并记录多位毕业博士生。", sources.huang)], sources: [sources.epflRoster, sources.huang] }),
  person({ id: "mary-anne-hartley-epfl-p0-r5", name: "Mary-Anne Hartley", role: "Adjunct Professor · Director, LiGHT Laboratory", institution: "EPFL", region: "Europe", area: "AI for Global Health · Foundation Models · Clinical AI", tags: ["Global Health", "Clinical AI", "Foundation Models", "Humanitarian AI"], summary: "EPFL LiGHT Laboratory 负责人，推动面向全球健康与人道响应的开放、可实施 AI。", stage: "emerging", x: 1140, y: 260, portraitFile: "mary-anne-hartley.jpg", portraitSource: sources.hartley, facts: [fact("当前任职", "EPFL Adjunct Professor，并领导 Laboratory for Intelligent Global Health and Humanitarian Response Technologies。", sources.hartley), fact("教育与学术训练", "在 Pretoria/Cape Town 接受医学训练，后在 Lausanne 完成博士训练，并获 LSHTM 公共卫生硕士。", sources.hartleyBio), fact("研究主线", "研究面向低资源医疗与人道响应的可信、代表性和可部署 AI，包括 Meditron 等开放模型。", sources.hartley), fact("学生体系", "EPFL People 页面列 Yusuf Kesmen 为博士生；EPFL 项目页另列 Trevor Brokowski 为团队博士生。", sources.hartleyProject)], sources: [sources.epflRoster, sources.hartley, sources.hartleyBio, sources.hartleyProject] }),

  person({ id: "david-greaves-cambridge-p0-r5", name: "David Greaves", role: "Senior Lecturer · Computer Systems", institution: "Cambridge", region: "Europe", area: "Computer Systems · SoC Design · Networking", tags: ["Computer Systems", "System-on-Chip", "Networking", "Hardware/Software Co-design"], summary: "Cambridge 计算系统学者，长期研究片上系统、网络与软硬件协同设计。", stage: "senior", x: 1380, y: 260, portraitFile: "david-greaves.jpg", portraitSource: sources.greaves, facts: [fact("当前任职", "Cambridge Department of Computer Science and Technology 现任 faculty。", sources.cambridgeRoster), fact("教育与学术训练", "1989 年获 Cambridge 博士；本科研究导师 Martin Richards，博士导师 Andy Hopper。", sources.greavesBio), fact("研究主线", "研究片上系统、计算机网络与软硬件协同设计。", sources.greaves), fact("学生体系", "Cambridge 官方博士名录记录 Umar Saif、Anil Madhavapeddy、Stephen Kell 等由 David Greaves 指导的博士生。", sources.cambridgePhd)], sources: [sources.cambridgeRoster, sources.greaves, sources.greavesBio, sources.cambridgePhd] }),
  person({ id: "marcelo-fiore-cambridge-p0-r5", name: "Marcelo Fiore", role: "Professor in Mathematical Foundations of Computer Science", institution: "Cambridge", region: "Europe", area: "Programming Languages · Semantics · Category Theory", tags: ["Programming Languages", "Semantics", "Category Theory", "Type Systems"], summary: "Cambridge 计算机数学基础教授，以范畴论、语义和类型系统研究计算与交互。", stage: "senior", x: 1620, y: 260, portraitFile: "marcelo-fiore.jpg", portraitSource: sources.fiore, facts: [fact("当前任职", "Cambridge Professor in Mathematical Foundations of Computer Science，并为 Christ's College Fellow。", sources.fiore), fact("教育与学术训练", "博士论文《Axiomatic Domain Theory in Categories of Partial Maps》后收入 Cambridge Distinguished Dissertations 系列；曾在 Gordon Plotkin 组任研究员。", sources.fioreTraining), fact("研究主线", "研究计算数学模型、程序语言的指称/操作语义、类型系统、程序逻辑及范畴论应用。", sources.fioreHome), fact("学生体系", "Cambridge 官方博士名录逐名列出 Samuel Staton、Chung Kil Hur、Philip Saville、Nathanael Arkor 等博士生。", sources.cambridgePhd)], sources: [sources.cambridgeRoster, sources.fiore, sources.fioreHome, sources.fioreTraining, sources.cambridgePhd] }),

  person({ id: "frank-keller-edinburgh-p0-r5", name: "Frank Keller", role: "Personal Chair in Computational Cognitive Science", institution: "Edinburgh", region: "Europe", area: "NLP · Language and Vision · Computational Narrative", tags: ["NLP", "Vision-Language", "Computational Narrative", "Multimodal AI"], summary: "Edinburgh 计算认知科学教授，研究语言—视觉、多模态理解与长文本叙事建模。", stage: "senior", x: 180, y: 520, portraitFile: "frank-keller.jpg", portraitSource: sources.keller, facts: [fact("当前任职", "Edinburgh School of Informatics Personal Chair in Computational Cognitive Science，并参与 UKRI NLP CDT 领导。", sources.keller), fact("教育与学术训练", "1996 年获 Stuttgart Diplom，2000 年获 Edinburgh PhD。", sources.keller), fact("研究主线", "研究 NLP、视觉语言、图像描述/视觉定位、视频摘要及计算叙事。", sources.keller), fact("学生体系", "本人 Edinburgh 页面列出 Harvey Donnelly、Gautier Dagan 等当前博士生，并记录 Roger Levy、Pinelopi Papalampidi 等校友去向。", sources.kellerPeople)], sources: [sources.edinburghRoster, sources.keller, sources.kellerPeople] }),
  person({ id: "shay-cohen-edinburgh-p0-r5", name: "Shay Cohen", role: "Reader · Natural Language Processing", institution: "Edinburgh", region: "Europe", area: "NLP · Structured Prediction · Language Models", tags: ["NLP", "Structured Prediction", "Text Generation", "Language Models"], summary: "Edinburgh NLP Reader，研究结构预测、概率语法、文本生成和大模型推理。", stage: "senior", x: 420, y: 520, portraitFile: "shay-cohen.jpg", portraitSource: sources.shay, facts: [fact("当前任职", "Edinburgh School of Informatics Reader，隶属 ILCC。", sources.shay), fact("教育与学术训练", "Tel Aviv University 数学与计算机本科、计算机硕士；2011 年获 CMU Language and Information Technologies 博士。", sources.shay), fact("研究主线", "研究自然语言处理、结构预测、概率语法、文本生成和语言模型。", sources.shay), fact("学生体系", "本人主页列出 Zheng Zhao、Yifu Qiu、Ke Wang 等博士生，并记录 Javad Hosseini 去 Google、Marco Damonte 去 Amazon。", sources.shayPeople)], sources: [sources.edinburghRoster, sources.shay, sources.shayPeople] }),
  person({ id: "simon-king-edinburgh-p0-r5", name: "Simon King", role: "Personal Chair of Speech Processing · Director, CSTR", institution: "Edinburgh", region: "Europe", area: "Speech Synthesis · Speech Recognition · Neural Speech", tags: ["Speech", "Text-to-Speech", "Speech Recognition", "Neural Audio"], summary: "Edinburgh CSTR 主任，研究从传统语音合成/识别到神经语音模型的完整技术谱系。", stage: "senior", x: 660, y: 520, portraitFile: "simon-king.jpg", portraitSource: sources.simon, facts: [fact("当前任职", "Edinburgh Personal Chair of Speech Processing，并自 2011 年起任 Centre for Speech Technology Research 主任。", sources.simon), fact("教育与学术训练", "1992/1993 年获 Cambridge MA/MPhil，1998 年获 Edinburgh PhD。", sources.simon), fact("研究主线", "研究语音合成、语音识别、说话人适配和神经语音建模。", sources.simon), fact("学生体系", "官方主页逐名记录 Joe Frankel、Peter Bell、Oliver Watts 等毕业博士生及 Adaeze Adigwe、Ariadna Sanchez 等当前博士生。", sources.simon)], sources: [sources.edinburghRoster, sources.simon] }),
  person({ id: "wenfei-fan-edinburgh-p0-r5", name: "Wenfei Fan", role: "Personal Chair in Web Data Management", institution: "Edinburgh", region: "Europe", area: "Data Management · Data Quality · Distributed Query Processing", tags: ["Databases", "Data Quality", "Distributed Systems", "Recommender Systems"], summary: "Edinburgh Web Data Management Chair，研究数据质量、数据共享与分布式查询，并长期连接 Huawei 数据研究。", stage: "senior", x: 900, y: 520, portraitFile: "wenfei-fan.jpg", portraitSource: sources.wenfei, facts: [fact("当前任职", "Edinburgh School of Informatics Personal Chair in Web Data Management，隶属 LFCS。", sources.wenfei), fact("教育与学术训练", "1985/1988 年获 Peking University CS 学士/硕士，1999 年获 University of Pennsylvania Computer and Information Science 博士。", sources.wenfei), fact("研究主线", "研究数据库理论与系统、数据质量、数据共享、分布式查询、推荐系统和社交媒体营销。", sources.wenfei), fact("产业连接", "Edinburgh Research Explorer 记录其参与 Huawei 资助的数据共享与图计算研究合作。", sources.wenfei)], sources: [sources.edinburghRoster, sources.wenfei, sources.wenfeiStudents] }),
  person({ id: "michael-rovatsos-edinburgh-p0-r5", name: "Michael Rovatsos", role: "Professor of Artificial Intelligence · Dean of Research and Innovation", institution: "Edinburgh", region: "Europe", area: "Multi-Agent Systems · Responsible AI · Social Computation", tags: ["Multi-Agent Systems", "Responsible AI", "Social Computation", "Collective Intelligence"], summary: "Edinburgh AI 教授，研究多智能体系统、社会计算和以人类价值为中心的 AI；曾于 2018–2023 年领导 Bayes Centre。", stage: "senior", x: 1140, y: 520, portraitFile: "michael-rovatsos.jpg", portraitSource: sources.rovatsos, facts: [fact("当前任职", "Edinburgh Professor of Artificial Intelligence，并任 College of Science and Engineering Dean of Research and Innovation。", sources.rovatsosStudents), fact("教育与学术训练", "1999 年获 Saarbrücken 计算机 Diploma，2004 年获 Technical University of Munich 计算机博士。", sources.rovatsos), fact("研究主线", "研究多智能体协作/竞争、社会计算、集体智能、透明公平与 human-friendly AI。", sources.rovatsos), fact("学生体系", "Edinburgh 个人档案逐名记录 Claire Barale、Savina Kim、Matthew Crosby 等毕业博士生及指导关系。", sources.rovatsosStudents)], sources: [sources.edinburghRoster, sources.rovatsos, sources.rovatsosStudents] }),
  person({ id: "barbara-webb-edinburgh-p0-r5", name: "Barbara Webb", role: "Personal Chair in Biorobotics", institution: "Edinburgh", region: "Europe", area: "Biorobotics · Computational Neuroscience · Insect Navigation", tags: ["Biorobotics", "Computational Neuroscience", "Robotics", "Animal Navigation"], summary: "Edinburgh 仿生机器人教授，以昆虫神经与行为模型研究感知、导航和自主控制。", stage: "senior", x: 1380, y: 520, portraitFile: "barbara-webb.jpg", portraitSource: sources.webbHome, facts: [fact("当前任职", "Edinburgh School of Informatics Personal Chair in Biorobotics，并领导多项 insect-inspired robotics PI 项目。", sources.webb), fact("教育与学术训练", "1988 年获 University of Sydney Psychology BSc，1993 年获 Edinburgh Artificial Intelligence PhD。", sources.webbHome), fact("研究主线", "研究仿生机器人、计算神经科学、昆虫导航和自主控制。", sources.webbHome), fact("学生体系", "Edinburgh IPAB 档案明确记录 Mark Payne 的博士研究由 Barbara Webb 指导。", sources.webbStudent)], sources: [sources.edinburghRoster, sources.webb, sources.webbHome, sources.webbStudent] }),
  person({ id: "bob-fisher-edinburgh-p0-r5", name: "Bob Fisher", role: "Chair in Computer Vision", institution: "Edinburgh", region: "Europe", area: "Computer Vision · 3D Scene Understanding · Robotics", tags: ["Computer Vision", "3D Vision", "Scene Understanding", "Robotics"], summary: "Edinburgh 计算机视觉资深教授，研究 3D 场景理解、物体建模、行为视频分析与机器人视觉。", stage: "senior", x: 1620, y: 520, portraitFile: "bob-fisher.jpg", portraitSource: sources.fisher, facts: [fact("当前任职", "Edinburgh School of Informatics Chair in Computer Vision，并参与创建 Institute of Perception, Action and Behaviour。", sources.fisher), fact("教育与学术训练", "1974 年获 Caltech 数学学士、1978 年获 Stanford CS 硕士、1987 年获 Edinburgh CS 博士。", sources.fisher), fact("研究主线", "研究 3D 场景理解、模型驱动物体识别、range data、认知视觉和视频行为理解。", sources.fisher), fact("学生体系", "本人主页列出 Longfei Chen、Fiona Smith、Yucheng Xu 等当前成员及 Andrew Fitzgibbon、Toby Breckon 等博士校友。", sources.fisherHome)], sources: [sources.edinburghRoster, sources.fisher, sources.fisherHome] }),
  person({ id: "pasquale-minervini-edinburgh-p0-r5", name: "Pasquale Minervini", role: "Lecturer in Natural Language Processing", institution: "Edinburgh", region: "Europe", area: "NLP · Knowledge Representation · Foundation Models", tags: ["NLP", "Knowledge Graphs", "Foundation Models", "Reasoning"], summary: "Edinburgh NLP PI，研究知识表示、神经符号推理、基础模型可靠性与高效训练。", stage: "emerging", x: 1860, y: 520, portraitFile: "pasquale-minervini.jpg", portraitSource: sources.minerviniPeople, facts: [fact("当前任职", "Edinburgh School of Informatics Lecturer in Natural Language Processing，并主持 Huawei 资助的复杂问答项目。", sources.minervini), fact("教育与学术训练", "获 University of Bari 博士，后在 UCL 开展博士后研究。", sources.minerviniBio), fact("研究主线", "研究知识图谱、神经符号推理、基础模型可靠性与高效训练。", sources.minerviniBio), fact("研究与指导", "Edinburgh 官方项目页记录其指导 Aryo Gema 和 Piotr Nawrot 的项目。", sources.minerviniProject)], sources: [sources.edinburghRoster, sources.minervini, sources.minerviniPeople, sources.minerviniBio, sources.minerviniProject] }),
];

export const candidatePriorityP0EuropeFifthRoundBatch1SupportingPeople2026: Person[] = [{
  id: "claire-barale-edinburgh-p0-r5-support",
  name: "Claire Barale",
  role: "Former PhD Student",
  institution: "Edinburgh",
  region: "Europe",
  area: "Legal Text · Responsible AI",
  tags: ["PhD student", "Responsible AI"],
  summary: "Edinburgh 官方人物档案列出的 Michael Rovatsos 博士毕业生。",
  category: "adjacent",
  stage: "adjacent",
  primary: false,
  status: "supporting former student node · relationship evidence only",
  sources: [sources.rovatsosStudents],
  x: 1140,
  y: 700,
}];
export const candidatePriorityP0EuropeFifthRoundBatch1Relationships2026: Relationship[] = [{
  id: "p0-eu-r5-rovatsos-barale-lineage",
  from: "michael-rovatsos-edinburgh-p0-r5",
  to: "claire-barale-edinburgh-p0-r5-support",
  type: "lineage",
  subtype: "phd_adviser",
  label: "博士导师",
  evidence: "Edinburgh 官方人物档案将 Claire Barale 列为 Michael Rovatsos 指导的博士毕业生。",
  source: sources.rovatsosStudents,
  verified: true,
}];
export const candidatePriorityP0EuropeFifthRoundBatch1Placements2026: StudentPlacement[] = [
  { id: "p0-eu-r5-keller-papalampidi-deepmind", teacherId: "frank-keller-edinburgh-p0-r5", studentName: "Pinelopi Papalampidi", company: "Google DeepMind", role: "Researcher", evidence: "Frank Keller 的 Edinburgh-hosted people page 将 Pinelopi Papalampidi 列为校友，并记录当前去向为 Google DeepMind。", source: sources.kellerPeople, verified: true },
  { id: "p0-eu-r5-shay-hosseini-google", teacherId: "shay-cohen-edinburgh-p0-r5", studentName: "Javad Hosseini", company: "Google", role: "Researcher", evidence: "Shay Cohen 本人主页记录 Javad Hosseini 为博士校友，当前任 Google Researcher。", source: sources.shayPeople, verified: true },
];

export const candidatePriorityP0EuropeFifthRoundBatch1GroupMembers2026: GroupMember[] = [
  { id: "p0-eu-r5-koch-fattebert", teacherId: "christoph-koch-epfl-p0-r5", name: "Christian Luc Fattebert", role: "Current PhD student", focus: "Data management", source: sources.koch },
  { id: "p0-eu-r5-moraud-munier", teacherId: "eduardo-moraud-epfl-p0-r5", name: "Flore Marie Munier-Jolain", role: "Current PhD student", focus: "Adaptive neuromodulation", source: sources.moraud },
  { id: "p0-eu-r5-kaplan-bruzzese", teacherId: "frederic-kaplan-epfl-p0-r5", name: "Tommy Bruzzese", role: "Current PhD student", focus: "Digital humanities", source: sources.kaplan },
  { id: "p0-eu-r5-huang-ledermann", teacherId: "jeffrey-huang-epfl-p0-r5", name: "Gianna Morgane Ledermann", role: "Current PhD student", focus: "Media and design", source: sources.huang },
  { id: "p0-eu-r5-hartley-kesmen", teacherId: "mary-anne-hartley-epfl-p0-r5", name: "Yusuf Kesmen", role: "Current PhD student", focus: "AI for global health", source: sources.hartley },
  { id: "p0-eu-r5-greaves-madhavapeddy", teacherId: "david-greaves-cambridge-p0-r5", name: "Anil Madhavapeddy", role: "Former PhD student", focus: "Type-safe network applications", source: sources.cambridgePhd },
  { id: "p0-eu-r5-fiore-staton", teacherId: "marcelo-fiore-cambridge-p0-r5", name: "Samuel Staton", role: "Former PhD student", focus: "Process calculi and semantics", source: sources.cambridgePhd },
  { id: "p0-eu-r5-keller-dagan", teacherId: "frank-keller-edinburgh-p0-r5", name: "Gautier Dagan", role: "Current PhD student", focus: "Natural language processing", source: sources.kellerPeople },
  { id: "p0-eu-r5-shay-qiu", teacherId: "shay-cohen-edinburgh-p0-r5", name: "Yifu Qiu", role: "Current PhD student", focus: "Language and vision", source: sources.shayPeople },
  { id: "p0-eu-r5-simon-bell", teacherId: "simon-king-edinburgh-p0-r5", name: "Peter Bell", role: "Former PhD student", focus: "Speech processing", source: sources.simon },
  { id: "p0-eu-r5-wenfei-yang-cao", teacherId: "wenfei-fan-edinburgh-p0-r5", name: "Yang Cao", role: "Long-term data-management collaborator", focus: "Distributed and graph data management", source: sources.wenfei },
  { id: "p0-eu-r5-rovatsos-barale", teacherId: "michael-rovatsos-edinburgh-p0-r5", name: "Claire Barale", role: "Former PhD student", focus: "Legal text and responsible AI", source: sources.rovatsosStudents },
  { id: "p0-eu-r5-webb-payne", teacherId: "barbara-webb-edinburgh-p0-r5", name: "Mark Payne", role: "Former PhD student", focus: "Biorobotics", source: sources.webbStudent },
  { id: "p0-eu-r5-fisher-chen", teacherId: "bob-fisher-edinburgh-p0-r5", name: "Longfei Chen", role: "Current PhD student / research staff", focus: "Computer vision", source: sources.fisherHome },
  { id: "p0-eu-r5-minervini-gema", teacherId: "pasquale-minervini-edinburgh-p0-r5", name: "Aryo Gema", role: "Supervised project researcher", focus: "Foundation model evaluation", source: sources.minerviniProject },
];

export const candidatePriorityP0EuropeFifthRoundBatch1RosterPromotions2026 = [
  ...candidatePriorityP0EuropeFifthRoundBatch1People2026.filter((p) => p.institution === "EPFL").map((p) => ({ unitUrl: sources.epflRoster.url, rosterName: p.name, atlasPersonId: p.id })),
  ...candidatePriorityP0EuropeFifthRoundBatch1People2026.filter((p) => p.institution === "Cambridge").map((p) => ({ unitUrl: sources.cambridgeRoster.url, rosterName: p.name, atlasPersonId: p.id })),
  ...candidatePriorityP0EuropeFifthRoundBatch1People2026.filter((p) => p.institution === "Edinburgh").map((p) => ({ unitUrl: sources.edinburghRoster.url, rosterName: p.name, atlasPersonId: p.id })),
] as const;

export const people = candidatePriorityP0EuropeFifthRoundBatch1People2026;
export const supportingPeople = candidatePriorityP0EuropeFifthRoundBatch1SupportingPeople2026;
export const relationships = candidatePriorityP0EuropeFifthRoundBatch1Relationships2026;
export const placements = candidatePriorityP0EuropeFifthRoundBatch1Placements2026;
export const groupMembers = candidatePriorityP0EuropeFifthRoundBatch1GroupMembers2026;
export const rosterPromotions = candidatePriorityP0EuropeFifthRoundBatch1RosterPromotions2026;
