import type { Person, Relationship, Source } from "./data";

const checkedAt = "2026-08-30";

const official = (label: string, url: string, supports: string): Source => ({
  label,
  url,
  kind: "official",
  checkedAt,
  supports,
});

const profile = (label: string, url: string, supports: string): Source => ({
  label,
  url,
  kind: "profile",
  checkedAt,
  supports,
});

const sources = {
  kaimingMit: official(
    "MIT CSAIL · Kaiming He",
    "https://www.csail.mit.edu/person/kaiming-he",
    "Current MIT appointment and computer-vision research profile",
  ),
  kaimingHome: profile(
    "Kaiming He · MIT homepage",
    "https://people.csail.mit.edu/kaiming/",
    "Current MIT and Google DeepMind roles, education and research history",
  ),
  kaimingCuhk: official(
    "CUHK IE · Kaiming He and Xiaoou Tang",
    "https://www.ie.cuhk.edu.hk/prof-sean-xiaoou-tang-recognised-by-inclusion-in-ai-2000-most-influential-scholar-annual-list-2/",
    "Kaiming He as Xiaoou Tang's PhD student and 2011 CUHK IE PhD graduate",
  ),
  tangMemorial: official(
    "CUHK IE · In memory of Prof. Xiaoou Tang",
    "https://www.ie.cuhk.edu.hk/in-memory-of-prof-xiaoou-tang-1968-2023/",
    "CUHK appointment, MMLab founding, MIT PhD and SenseTime co-founding role",
  ),
  mmlabAbout: official(
    "MMLab · About us",
    "https://mmlab.hk/about-us",
    "Xiaoou Tang's founding role and MMLab history since 2001",
  ),
  mmlabNews: official(
    "CUHK MMLab · News and alumni milestones",
    "https://mmlab.ie.cuhk.edu.hk/read_all_news.html",
    "Kaiming He and Bolei Zhou alumni records and supervision details",
  ),
  pingHku: official(
    "HKU IDS · Ping Luo",
    "https://datascience.hku.hk/people/ping-luo/",
    "Ping Luo's CUHK PhD co-advisers Xiaoou Tang and Xiaogang Wang",
  ),
  malikBerkeley: official(
    "Berkeley EECS · Jitendra Malik",
    "https://www2.eecs.berkeley.edu/Faculty/Homepages/malik.html",
    "Current Berkeley title, BAIR affiliation and computer-vision research",
  ),
  malikHome: profile(
    "Jitendra Malik · Berkeley homepage",
    "https://people.eecs.berkeley.edu/~malik/",
    "Research programme, students and academic family tree",
  ),
  guptaCmu: official(
    "CMU Computer Vision faculty · Abhinav Gupta",
    "https://vision.cs.cmu.edu/people.html",
    "Current CMU vision faculty role and research areas",
  ),
  guptaHome: profile(
    "Abhinav Gupta · CMU homepage",
    "https://www.cs.cmu.edu/~abhinavg/",
    "Current appointment, laboratory, students and alumni",
  ),
  shuranStanford: official(
    "Stanford Profiles · Shuran Song",
    "https://profiles.stanford.edu/shuran-song?tab=bio",
    "Current Stanford appointment and computer vision and robotics research",
  ),
  shuranHome: profile(
    "Shuran Song · REAL@Stanford",
    "https://shurans.github.io/",
    "Research group, embodied AI programme and current members",
  ),
  sainingNyu: official(
    "NYU Courant · Machine Learning faculty",
    "https://cs.nyu.edu/dynamic/people/faculty/type/21/?area=Machine+Learning",
    "Current NYU faculty listing and computer-vision research areas",
  ),
  sainingHome: profile(
    "Saining Xie · homepage",
    "https://www.sainingxie.com/",
    "NYU role, AMI Labs co-founding role, leave status and research history",
  ),
  kanazawaBerkeley: official(
    "Berkeley EECS · Angjoo Kanazawa",
    "https://www2.eecs.berkeley.edu/Faculty/Homepages/kanazawa.html",
    "Current appointment, research and BAIR postdoctoral advisers",
  ),
  kanazawaHome: profile(
    "Angjoo Kanazawa · KAIR homepage",
    "https://people.eecs.berkeley.edu/~kanazawa/",
    "KAIR laboratory, research programme and current members",
  ),
  jiayaHkust: official(
    "HKUST Engineering · Jiaya Jia",
    "https://seng.hkust.edu.hk/about/people/faculty/jiaya-jia",
    "Current HKUST appointment and AI, computer-vision and machine-learning research",
  ),
  jiayaHome: profile(
    "Jiaya Jia · homepage",
    "https://www.cse.cuhk.edu.hk/~leojia/",
    "Current HKUST chair professorship, research programme and alumni network",
  ),
};

type CurrentPerson = Omit<Person, "category" | "primary" | "lastVerifiedAt" | "facts" | "status"> & {
  node: string;
  sources: [Source, Source, ...Source[]];
  status?: string;
};

const current = ({ node, ...person }: CurrentPerson): Person => ({
  ...person,
  category: "core",
  primary: true,
  status: person.status ?? "current PI",
  lastVerifiedAt: checkedAt,
  facts: [
    { label: "当前任职", value: person.role, source: person.sources[0] },
    { label: "研究主线", value: person.area, source: person.sources[0] },
    { label: "公开研究节点", value: node, source: person.sources[1] },
  ],
});

export const cvRosterAuditPeople: Person[] = [
  current({
    id: "kaiming-he-us",
    name: "Kaiming He",
    chinese: "何恺明",
    role: "Associate Professor, EECS · Distinguished Scientist, Google DeepMind",
    institution: "MIT",
    region: "United States",
    area: "Computer Vision · Deep Learning · Visual Representation Learning",
    tags: ["计算机视觉", "深度学习", "ResNet", "Mask R-CNN", "MAE", "汤晓鸥学生"],
    summary: "MIT 计算机视觉与深度学习核心 PI，博士师从汤晓鸥；代表工作横跨 ResNet、Faster/Mask R-CNN、MoCo 与 MAE，并兼任 Google DeepMind Distinguished Scientist。",
    node: "MIT CSAIL · Google DeepMind",
    stage: "senior",
    sources: [sources.kaimingMit, sources.kaimingHome, sources.kaimingCuhk],
    x: 350,
    y: 995,
  }),
  current({
    id: "jitendra-malik-us",
    name: "Jitendra Malik",
    role: "Arthur J. Chick Professor of EECS",
    institution: "Berkeley",
    region: "United States",
    area: "Computer Vision · Machine Learning · Robotics",
    tags: ["计算机视觉", "机器学习", "机器人", "BAIR", "导师谱系"],
    summary: "Berkeley 计算机视觉与机器学习资深带头人，长期研究视觉识别、分割、三维理解与机器人感知，并形成覆盖多所高校的重要学生与博士后网络。",
    node: "Berkeley AI Research · Computer Vision Group",
    stage: "senior",
    sources: [sources.malikBerkeley, sources.malikHome],
    x: 640,
    y: 490,
  }),
  current({
    id: "angjoo-kanazawa-us",
    name: "Angjoo Kanazawa",
    role: "Associate Professor of EECS",
    institution: "Berkeley",
    region: "United States",
    area: "Computer Vision · 3D Reconstruction · Dynamic Scene Understanding",
    tags: ["计算机视觉", "3D 视觉", "人体重建", "动态场景", "BAIR"],
    summary: "Berkeley KAIR 负责人，研究从单目图像与视频理解可运动的三维世界；其 BAIR 博士后阶段由 Jitendra Malik、Alexei Efros 与 Trevor Darrell 共同指导。",
    node: "Kanazawa AI Research Lab · BAIR",
    stage: "emerging",
    sources: [sources.kanazawaBerkeley, sources.kanazawaHome],
    x: 770,
    y: 490,
  }),
  current({
    id: "abhinav-gupta-us",
    name: "Abhinav Gupta",
    role: "Professor, Robotics Institute",
    institution: "CMU",
    region: "United States",
    area: "Computer Vision · Self-Supervised Learning · Robot Learning",
    tags: ["计算机视觉", "自监督学习", "机器人学习", "视觉推理", "CMU RI"],
    summary: "CMU Robotics Institute 视觉方向资深 PI，研究自监督视觉学习、机器人学习与视觉推理，并培养了跨学术界和产业研究机构的学生与博士后。",
    node: "CMU Robotics Institute · Visual Learning",
    stage: "senior",
    sources: [sources.guptaCmu, sources.guptaHome],
    x: 930,
    y: 490,
  }),
  current({
    id: "shuran-song-us",
    name: "Shuran Song",
    role: "Assistant Professor of Electrical Engineering",
    institution: "Stanford",
    region: "United States",
    area: "Embodied AI · Computer Vision · Robotics",
    tags: ["具身智能", "计算机视觉", "机器人", "3D 感知", "操作"],
    summary: "Stanford REAL 实验室负责人，研究让机器人从视觉与交互中理解三维世界并完成操作任务，是计算机视觉通向具身智能的重要新生代 PI。",
    node: "REAL@Stanford",
    stage: "emerging",
    sources: [sources.shuranStanford, sources.shuranHome],
    x: 350,
    y: 550,
  }),
  current({
    id: "saining-xie-us",
    name: "Saining Xie",
    role: "Assistant Professor of Computer Science · Co-Founder and CSO, AMI Labs",
    institution: "NYU",
    region: "United States",
    area: "Computer Vision · Generative Models · World Models",
    tags: ["计算机视觉", "生成模型", "世界模型", "ConvNeXt", "DiT", "创业"],
    summary: "NYU 视觉与生成模型 PI，曾任 Meta FAIR 与 Google DeepMind 研究科学家；当前联合创办 AMI Labs，研究从视觉架构、扩散模型延伸到世界模型。",
    node: "NYU Vision · AMI Labs",
    stage: "emerging",
    status: "current PI · on leave Spring/Summer 2026",
    sources: [sources.sainingNyu, sources.sainingHome],
    x: 1220,
    y: 995,
  }),
  current({
    id: "jiaya-jia-hkust",
    name: "Jiaya Jia",
    chinese: "贾佳亚",
    role: "Chair Professor · Director, Von Neumann Institute",
    institution: "HKUST",
    region: "Hong Kong",
    area: "Computer Vision · Multimodal AI · Deep Learning",
    tags: ["计算机视觉", "多模态", "深度学习", "视觉语言", "产业连接"],
    summary: "HKUST 计算机视觉资深 PI，研究视觉理解、生成、语言与深度学习；公开主页记录其长期培养的学生网络及 Tencent YouTu、SmartMore 等产业经历。",
    node: "HKUST · Von Neumann Institute",
    stage: "senior",
    sources: [sources.jiayaHkust, sources.jiayaHome],
    x: 1350,
    y: 350,
  }),
  {
    id: "xiaoou-tang-cuhk",
    name: "Xiaoou Tang",
    chinese: "汤晓鸥",
    role: "Professor · MMLab Founding Director (1968–2023)",
    institution: "CUHK",
    region: "Hong Kong",
    area: "Computer Vision · Pattern Recognition · AI Industry",
    tags: ["计算机视觉", "MMLab", "SenseTime", "导师谱系", "历史根节点"],
    summary: "CUHK MMLab 创始人、SenseTime 联合创始人。其学术谱系连接何恺明、罗平、周博磊等视觉学者，是理解中国视觉研究跨校与产业扩散的重要历史根节点。",
    facts: [
      { label: "学术任职", value: "1998 年加入 CUHK，2001 年创立 MMLab", source: sources.tangMemorial },
      { label: "产业连接", value: "SenseTime 联合创始人及执行董事", source: sources.tangMemorial },
      { label: "学术影响", value: "MMLab 官方资料记录其培养并影响多代计算机视觉研究者", source: sources.mmlabAbout },
    ],
    stage: "historical",
    category: "historical",
    primary: false,
    sources: [sources.tangMemorial, sources.mmlabAbout],
    lastVerifiedAt: checkedAt,
    x: 0,
    y: 0,
  },
];

export const cvRosterAuditRelationships: Relationship[] = [
  {
    id: "tang-kaiming-phd-lineage",
    from: "xiaoou-tang-cuhk",
    to: "kaiming-he-us",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "CUHK IE 官方页面明确称何恺明为汤晓鸥的博士生，并记录其于 2011 年取得 CUHK IE 博士学位。",
    evidenceObject: "Kaiming He · CUHK PhD 2011",
    source: sources.kaimingCuhk,
    verified: true,
    endYear: 2011,
  },
  {
    id: "tang-ping-co-adviser",
    from: "xiaoou-tang-cuhk",
    to: "ping-luo-hku",
    type: "lineage",
    subtype: "co_adviser",
    label: "共同博士导师",
    evidence: "HKU IDS 官方简介明确记录罗平的 CUHK 博士由汤晓鸥与王晓刚共同指导。",
    evidenceObject: "Ping Luo · CUHK PhD",
    source: sources.pingHku,
    verified: true,
  },
  {
    id: "tang-bolei-mphil-lineage",
    from: "xiaoou-tang-cuhk",
    to: "bolei-zhou-us",
    type: "lineage",
    subtype: "other",
    label: "MPhil 导师",
    evidence: "CUHK MMLab 官方新闻记录周博磊于 2012 年取得 CUHK MPhil，并由汤晓鸥指导。",
    evidenceObject: "Bolei Zhou · CUHK MPhil 2012",
    source: sources.mmlabNews,
    verified: true,
    endYear: 2012,
  },
  ...["jitendra-malik-us", "alexei-efros-us", "trevor-darrell-us"].map((mentorId, index): Relationship => ({
    id: `kanazawa-bair-postdoc-${index + 1}`,
    from: mentorId,
    to: "angjoo-kanazawa-us",
    type: "lineage",
    subtype: "postdoc_mentor",
    label: "博士后导师",
    evidence: "Berkeley EECS 官方简介记录 Angjoo Kanazawa 在 BAIR 的博士后阶段由 Jitendra Malik、Alexei Efros 与 Trevor Darrell 共同指导。",
    evidenceObject: "Angjoo Kanazawa · BAIR postdoc",
    source: sources.kanazawaBerkeley,
    verified: true,
  })),
];
