import type { GroupMember, IndustryPathway, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-08-30";
const official = (label: string, url: string, supports: string): Source => ({ label, url, kind: "official", checkedAt, supports });
const profile = (label: string, url: string, supports: string): Source => ({ label, url, kind: "profile", checkedAt, supports });

type EuropePersonInput = Pick<Person, "id" | "name" | "role" | "institution" | "area" | "tags" | "summary" | "stage"> & {
  node: string;
  sources: [Source, Source, ...Source[]];
};

type EuropeProfileDetail = { trajectory: string; contribution: string };

const europeProfileDetails: Record<string, EuropeProfileDetail> = {
  "yarin-gal-eu": { trajectory: "在 Oxford 领导 OATML，将贝叶斯深度学习、不确定性估计与可靠机器学习组织为一条连续研究主线。", contribution: "其工作把模型不确定性从理论问题推进到深度学习系统的可解释置信度与风险判断。" },
  "michael-bronstein-eu": { trajectory: "现任 Oxford DeepMind Professor of AI，研究经历横跨几何深度学习、图机器学习、生命科学与技术创业。", contribution: "是 geometric deep learning 研究范式的代表人物之一，关注非欧数据与 AI for Science。" },
  "philip-torr-eu": { trajectory: "长期领导 Oxford Torr Vision Group / CVML，并把视觉研究延伸到多项技术转化与创业活动。", contribution: "研究覆盖多视图几何、识别、分割与现代机器学习，是英国计算机视觉的重要资深节点。" },
  "christian-rupprecht-eu": { trajectory: "Oxford 发展期独立 PI，依托 Visual Geometry Group 推进大规模视觉学习与生成式视觉研究。", contribution: "重点连接视频理解、生成模型与视觉表征，是欧洲新一代视觉团队扩张值得持续观察的节点。" },
  "michael-wooldridge-eu": { trajectory: "现任 Oxford Ashall Professor of Foundations of AI，长期研究自主智能体、博弈与多智能体系统。", contribution: "其研究为今天的 agentic AI 提供形式化决策、协调与社会交互基础。" },
  "neil-lawrence-eu": { trajectory: "加入 Cambridge 前曾任 Amazon Director of Machine Learning，现任 DeepMind Professor of Machine Learning。", contribution: "把概率机器学习、数据中心 AI、人本 AI 与公共治理议题连接在同一研究框架中。" },
  "andreas-vlachos-eu": { trajectory: "从 UCL Machine Reading Group 博士后阶段发展为 Cambridge NLP 与机器学习教授，并持续公开产业资助连接。", contribution: "研究集中于事实核查、对话、生成与模仿学习，兼具方法研究和信息可信度应用。" },
  "anna-korhonen-eu": { trajectory: "兼任 Cambridge Language Technology Lab 联合主任与 Centre for Human-Inspired AI 主任。", contribution: "以多语言、低资源、健康与 human-centric NLP 为核心，强调语言技术的社会与跨学科价值。" },
  "roberto-cipolla-eu": { trajectory: "在 Cambridge 任信息工程教授，同时领导 Toshiba Cambridge Research Laboratory。", contribution: "长期连接三维视觉、机器人感知与产业实验室，是典型的学术—企业双重领导节点。" },
  "ferenc-huszar-eu": { trajectory: "现任 Cambridge 机器学习教授，是该校生成模型与概率学习方向的新一代独立 PI。", contribution: "研究把概率建模、生成学习与基础模型方法连接起来。" },
  "sebastian-riedel-eu": { trajectory: "在 UCL 领导机器阅读与 NLP 研究网络，并形成从博士培养到产业研究的外溢关系。", contribution: "研究覆盖知识表示、信息抽取、机器阅读与语言模型，是欧洲 NLP 的关键导师节点。" },
  "tim-rocktaschel-eu": { trajectory: "由 UCL 博士阶段发展为该校 AI 教授，并与 Google DeepMind 前沿研究保持公开连接。", contribution: "重点研究强化学习、开放式学习与语言模型智能体，连接 LLM 和 sequential decision making。" },
  "marc-deisenroth-eu": { trajectory: "现任 UCL Google DeepMind Chair，并担任 Google DeepMind Research Director、共同领导 Sustainability and ML Group。", contribution: "以数据高效机器学习、概率建模和自主决策为核心，应用延伸到气候、核聚变与机器人。" },
  "lourdes-agapito-eu": { trajectory: "领导 UCL Vision and Imaging Science 研究方向，长期专注动态世界的三维视觉建模。", contribution: "代表性主线包括非刚性重建、动态场景理解与从视频恢复三维结构。" },
  "david-silver-eu": { trajectory: "在 UCL 保留教授节点，其强化学习研究与 DeepMind 的 AlphaGo / AlphaZero 路线紧密相连。", contribution: "把强化学习、规划与自博弈推进到可在复杂决策问题中验证的系统规模。" },
  "mirella-lapata-eu": { trajectory: "Edinburgh NLP 核心带头人并参与领导学校 Generative AI Laboratory。", contribution: "研究从语言理解与生成延伸到多模态学习和长上下文推理，是欧洲生成式 NLP 的关键导师节点。" },
  "ivan-titov-eu": { trajectory: "现任 Edinburgh 计算语言学教授，围绕语义表示、多语言学习与推理组织研究团队。", contribution: "重点探索神经表示与结构化、符号化推理之间的连接。" },
  "hakan-bilen-eu": { trajectory: "由 KU Leuven 博士谱系成长为 Edinburgh 计算机视觉教授。", contribution: "研究覆盖弱监督学习、视频理解与生成式视觉，兼具视觉识别和时序建模。" },
  "amos-storkey-eu": { trajectory: "长期任职 Edinburgh Institute for Machine Learning，研究横跨概率、贝叶斯与生成式机器学习。", contribution: "关注数据效率、可靠学习和科学应用，是该校机器学习基础方向的资深节点。" },
  "andreas-krause-eu": { trajectory: "在 ETH 领导 Learning & Adaptive Systems，并参与建设 ETH AI Center 与 Swiss Data Science 生态。", contribution: "以不确定环境中的可靠决策、主动学习与自适应系统为核心。" },
  "marc-pollefeys-eu": { trajectory: "同时任 ETH 教授和 Microsoft Mixed Reality & AI Lab Zurich 负责人。", contribution: "三维重建、机器人感知与 mixed reality 的研究长期在学界和产业系统之间双向流动。" },
  "siyu-tang-eu": { trajectory: "ETH 发展期视觉 PI，围绕三维人体、场景理解与具身感知建设独立团队。", contribution: "将生成式视觉、人体建模和 embodied AI 放在统一的空间智能问题中。" },
  "thomas-hofmann-eu": { trajectory: "ETH 数据分析与机器学习资深教授，长期研究统计学习、表征与语言模型基础。", contribution: "其节点连接传统统计机器学习与当代大规模语言建模。" },
  "antoine-bosselut-eu": { trajectory: "在 EPFL 建设 Natural Language Processing Lab，是知识增强语言模型方向的发展期 PI。", contribution: "聚焦常识知识、语言模型与推理，强调模型如何获得和使用外部知识。" },
  "martin-jaggi-eu": { trajectory: "领导 EPFL Machine Learning and Optimization Lab，研究覆盖大规模与分布式学习。", contribution: "把优化方法直接连接到现代深度网络和语言模型训练效率。" },
  "pascal-fua-eu": { trajectory: "长期领导 EPFL Computer Vision Laboratory，是该校三维视觉研究的资深核心。", contribution: "研究从三维重建、人体建模延伸到医学视觉和科学成像。" },
  "volkan-cevher-eu": { trajectory: "在 EPFL 领导 LIONS，围绕机器学习基础、优化与可扩展算法组织研究。", contribution: "连接学习理论、计算效率和产业合作项目，强调可扩展且可证明的方法。" },
  "bernhard-schoelkopf-eu": { trajectory: "长期担任 Max Planck Institute for Intelligent Systems 研究主任，是 Tübingen 机器学习生态核心。", contribution: "从核方法、统计学习推进到因果学习，持续影响欧洲机器学习基础研究。" },
  "andreas-geiger-eu": { trajectory: "领导 Tübingen Autonomous Vision Group，并共同创建 KITTI 自动驾驶视觉基准。", contribution: "研究连接三维场景理解、自动驾驶感知与生成式世界模型。" },
  "michael-black-eu": { trajectory: "长期领导 MPI-IS Perceiving Systems 部门，研究聚焦人体形状、运动与视觉感知。", contribution: "其工作推动了可学习人体模型与运动估计在视觉和生成式人体建模中的使用。" },
  "zeynep-akata-eu": { trajectory: "现任 TUM Liesel Beckmann Distinguished Professor，并领导 Helmholtz Munich 可解释机器学习研究。", contribution: "研究把视觉—语言、多模态学习和可解释性结合起来，强调可靠的人机知识交互。" },
  "iryna-gurevych-eu": { trajectory: "领导 TU Darmstadt Ubiquitous Knowledge Processing Lab，是德国 NLP 研究的重要组织者。", contribution: "研究集中于跨文档理解、信息质量、文本推理与可信语言技术。" },
  "stefan-roth-eu": { trajectory: "在 TU Darmstadt 领导 Visual Inference Lab，研究统计视觉和深度视觉模型。", contribution: "重点处理鲁棒性、可解释性与场景理解，连接经典视觉推断和现代深度网络。" },
  "max-welling-eu": { trajectory: "长期任职 UvA 机器学习团队，并以 CuspAI 联合创办人身份连接 AI for Science 创业。", contribution: "代表性研究覆盖生成模型、对称性与科学机器学习。" },
  "cees-snoek-eu": { trajectory: "在 UvA 领导 Video and Image Sense Lab，是 Amsterdam 视觉与视频理解核心 PI。", contribution: "研究覆盖视觉检索、视频表征和多模态感知，重视大规模真实数据。" },
  "maarten-de-rijke-eu": { trajectory: "现任 UvA University Professor of AI and Information Retrieval，并通过 ICAI 等机制连接联合产业实验室。", contribution: "把信息检索、推荐、NLP 与 responsible AI 组织成连续的人才培养和产业合作网络。" },
  "luc-de-raedt-eu": { trajectory: "KU Leuven DTAI 资深教授，长期建设统计关系学习与神经符号 AI 导师谱系。", contribution: "代表性方向包括概率编程、知识表示与从符号规则到机器学习的统一。" },
  "tinne-tuytelaars-eu": { trajectory: "在 KU Leuven 领导视觉识别研究，并培养了流向 Edinburgh、Google、DeepMind、Huawei 等节点的公开校友。", contribution: "研究从视觉表征延伸到持续学习，是欧洲视觉导师网络的重要节点。" },
  "jesse-davis-eu": { trajectory: "任 KU Leuven DTAI 教授，研究复杂结构数据、关系学习与数据挖掘。", contribution: "将通用机器学习方法延伸到 sports analytics 等真实决策场景。" },
  "cordelia-schmid-eu": { trajectory: "任 Inria Research Director，并保持与 Google Research 的公开联合任职。", contribution: "长期推动图像和视频表征、识别与大规模视觉学习，是欧洲视觉谱系关键节点。" },
  "gael-varoquaux-eu": { trajectory: "领导 Inria SODA 团队，并长期参与 scikit-learn 开放机器学习基础设施。", contribution: "把方法、软件工程、可复现数据科学和医疗应用连接在同一开放生态中。" },
  "benoit-sagot-eu": { trajectory: "任 Inria Research Director，围绕多语言 NLP、语言资源与数字人文组织研究。", contribution: "重点建设覆盖多语言和低资源语言的模型、词典与可复用语言基础设施。" },
  "roberto-navigli-eu": { trajectory: "任 Sapienza 教授，并以 Babelscape 联合创办人身份推动多语言语义技术转化。", contribution: "以词义消歧、BabelNet、多语言语义和语言模型为连续主线。" },
};

const person = ({ node, ...entry }: EuropePersonInput): Person => ({
  ...entry,
  region: "Europe",
  category: "core",
  primary: true,
  status: "current PI",
  lastVerifiedAt: checkedAt,
  x: 0,
  y: 0,
  facts: [
    { label: "现职", value: entry.role, source: entry.sources[0] },
    { label: "研究主题", value: entry.area, source: entry.sources[0] },
    { label: "研究节点", value: node, source: entry.sources[1] },
    { label: "职业与学术轨迹", value: europeProfileDetails[entry.id].trajectory, source: entry.sources[0] },
    { label: "代表性贡献", value: europeProfileDetails[entry.id].contribution, source: entry.sources[1] },
  ],
});

export const europePeople: Person[] = [
  person({ id: "yarin-gal-eu", name: "Yarin Gal", role: "Professor of Computer Science", institution: "Oxford", area: "Machine Learning · Uncertainty · Deep Learning", tags: ["机器学习", "不确定性", "深度学习", "OATML"], stage: "senior", node: "Oxford Applied and Theoretical Machine Learning", summary: "Oxford OATML 负责人，研究贝叶斯深度学习、不确定性和可靠机器学习，也是欧洲生成式 AI 人才网络的重要节点。", sources: [official("Oxford CS profile", "https://www.cs.ox.ac.uk/people/yarin.gal/index.html", "Current appointment and research"), profile("OATML profile", "https://oatml.cs.ox.ac.uk/members/yarin/", "Lab leadership and group")]}),
  person({ id: "michael-bronstein-eu", name: "Michael Bronstein", role: "DeepMind Professor of AI", institution: "Oxford", area: "Geometric Deep Learning · AI for Science", tags: ["几何深度学习", "图机器学习", "AI for Science", "创业"], stage: "senior", node: "Oxford AI / Geometric Deep Learning", summary: "几何深度学习代表性学者，研究图与非欧空间上的学习，并连接学术研究、生命科学和技术创业。", sources: [official("Oxford CS profile", "https://www.cs.ox.ac.uk/people/michael.bronstein/", "Current title, research and industry links"), official("Oxford AI/ML people", "https://www.cs.ox.ac.uk/research/ai_ml/people.html", "Current AI/ML faculty roster")]}),
  person({ id: "philip-torr-eu", name: "Philip Torr", role: "Professor of Engineering Science", institution: "Oxford", area: "Computer Vision · Machine Learning", tags: ["计算机视觉", "机器学习", "视觉几何", "创业"], stage: "senior", node: "Torr Vision Group / CVML", summary: "Oxford 计算机视觉资深 PI，研究视觉几何、识别与机器学习，并有多项视觉技术产业转化与创业记录。", sources: [official("Oxford Engineering profile", "https://eng.ox.ac.uk/people/philip-torr", "Current appointment, research and companies"), official("Oxford CVML", "https://eng.ox.ac.uk/about/computer-vision-and-machine-learning", "Research group and programme")]}),
  person({ id: "christian-rupprecht-eu", name: "Christian Rupprecht", role: "Associate Professor of Computer Science", institution: "Oxford", area: "Computer Vision · Generative Models", tags: ["计算机视觉", "生成模型", "视频", "发展期 PI"], stage: "emerging", node: "Visual Geometry Group", summary: "Oxford 新生代视觉 PI，聚焦大规模视觉学习、生成式视觉与视频理解。", sources: [official("Oxford AI/ML people", "https://www.cs.ox.ac.uk/research/ai_ml/people.html", "Current faculty status"), official("Oxford ERC profile", "https://www.cs.ox.ac.uk/news/2482-full.html", "Research programme and professorial title")]}),
  person({ id: "michael-wooldridge-eu", name: "Michael Wooldridge", role: "Ashall Professor of Foundations of AI", institution: "Oxford", area: "Multi-agent Systems · AI Foundations", tags: ["多智能体", "AI 基础", "博弈", "Agent"], stage: "senior", node: "Oxford AI / Agent Systems", summary: "多智能体系统与 AI 基础研究的资深节点，连接形式化方法、博弈与当代智能体研究。", sources: [official("Oxford CS profile", "https://www.cs.ox.ac.uk/people/michael.wooldridge/", "Current title and research"), official("Oxford AI/ML people", "https://www.cs.ox.ac.uk/research/ai_ml/people.html", "Current AI/ML roster")]}),

  person({ id: "neil-lawrence-eu", name: "Neil Lawrence", role: "DeepMind Professor of Machine Learning", institution: "Cambridge", area: "Machine Learning · Data-Centric AI", tags: ["机器学习", "数据中心 AI", "AI 治理", "Amazon"], stage: "senior", node: "Cambridge ML and AI", summary: "Cambridge 机器学习资深 PI，研究数据、概率学习与人本 AI；此前曾任 Amazon 机器学习总监。", sources: [official("Cambridge profile", "https://www.cst.cam.ac.uk/people/ndl21", "Current title, research and career"), official("Cambridge ML/AI theme", "https://www.cst.cam.ac.uk/research/themes/machine-learning-and-artificial-intelligence", "Research theme membership")]}),
  person({ id: "andreas-vlachos-eu", name: "Andreas Vlachos", role: "Professor of NLP and Machine Learning", institution: "Cambridge", area: "NLP · Fact Checking · Dialogue", tags: ["NLP", "事实核查", "对话", "模仿学习"], stage: "senior", node: "Cambridge Language and Intelligence", summary: "研究事实核查、对话、生成与模仿学习，公开主页记录与 Meta、Amazon、Google、Huawei 等产业研究资助的连接。", sources: [official("Cambridge CS profile", "https://www.cst.cam.ac.uk/people/av308", "Current appointment and research"), profile("Andreas Vlachos homepage", "https://andreasvlachos.github.io/", "Projects, group and career history")]}),
  person({ id: "anna-korhonen-eu", name: "Anna Korhonen", role: "Professor of Natural Language Processing", institution: "Cambridge", area: "Human-Centric · Multilingual · Biomedical NLP", tags: ["NLP", "多语言", "医疗 NLP", "Human-Centric AI"], stage: "senior", node: "Language Technology Lab / CHIA", summary: "Cambridge Language Technology Lab 联合主任和 CHIA 主任，推动多语言、低资源、健康与人本 NLP。", sources: [official("Cambridge MMLL profile", "https://www.mmll.cam.ac.uk/people/anna-korhonen", "Current roles, supervision and research"), official("Cambridge CHIA profile", "https://www.chia.cam.ac.uk/team/anna-korhonen", "CHIA leadership and research themes")]}),
  person({ id: "roberto-cipolla-eu", name: "Roberto Cipolla", role: "Professor of Information Engineering", institution: "Cambridge", area: "Computer Vision · Robotics", tags: ["计算机视觉", "机器人", "三维视觉", "Toshiba"], stage: "senior", node: "Machine Intelligence Laboratory", summary: "Cambridge 计算机视觉与机器人资深 PI，同时担任 Toshiba Cambridge Research Laboratory 主任，体现长期产学连接。", sources: [official("Cambridge Engineering profile", "https://www.eng.cam.ac.uk/profiles/rc10001", "Current title, research and Toshiba role"), official("Jesus College profile", "https://www.jesus.cam.ac.uk/people/roberto-cipolla", "Biography and current university role")]}),
  person({ id: "ferenc-huszar-eu", name: "Ferenc Huszár", role: "Professor of Machine Learning", institution: "Cambridge", area: "Machine Learning · Generative Models", tags: ["机器学习", "生成模型", "概率学习", "发展期 PI"], stage: "emerging", node: "Cambridge ML and AI", summary: "研究生成模型、概率机器学习与基础模型，是 Cambridge 机器学习的新一代独立 PI。", sources: [official("Cambridge CS profile", "https://www.cst.cam.ac.uk/people/fh277", "Current appointment and research"), official("Cambridge ML/AI theme", "https://www.cst.cam.ac.uk/research/themes/machine-learning-and-artificial-intelligence", "Research theme roster")]}),

  person({ id: "sebastian-riedel-eu", name: "Sebastian Riedel", role: "Professor of Artificial Intelligence", institution: "UCL", area: "NLP · Machine Reading · LLM", tags: ["NLP", "机器阅读", "知识表示", "LLM"], stage: "senior", node: "UCL NLP / Machine Reading", summary: "UCL 机器阅读与 NLP 资深 PI，研究知识表示、信息抽取和语言模型，并形成跨学界与产业研究网络。", sources: [official("UCL Intelligent Systems", "https://www.ucl.ac.uk/engineering/computer-science/research/research-groups-and-centres/intelligent-systems-group", "Current faculty roster and PhD supervision"), profile("UCL NLP", "https://nlp.cs.ucl.ac.uk/", "Lab leadership and research programme")]}),
  person({ id: "tim-rocktaschel-eu", name: "Tim Rocktäschel", role: "Professor of Artificial Intelligence", institution: "UCL", area: "Reinforcement Learning · LLM Agents", tags: ["强化学习", "LLM Agents", "开放式学习", "Google DeepMind"], stage: "senior", node: "UCL Centre for AI", summary: "研究强化学习、开放式学习和语言模型智能体，横跨 UCL 学术岗位与前沿产业研究。", sources: [official("UCL AI people", "https://www.ucl.ac.uk/engineering/research/centres-institutes-and-labs/ucl-centre-artificial-intelligence/people", "Current AI faculty roster"), official("UCL Intelligent Systems", "https://www.ucl.ac.uk/engineering/computer-science/research/research-groups-and-centres/intelligent-systems-group", "Current group membership")]}),
  person({ id: "marc-deisenroth-eu", name: "Marc Deisenroth", role: "Google DeepMind Chair of Machine Learning and Artificial Intelligence", institution: "UCL", area: "Machine Learning · Robotics · Decision Making", tags: ["机器学习", "机器人", "概率学习", "决策", "Google DeepMind", "AI for Sustainability"], stage: "senior", node: "UCL Centre for AI / Sustainability and ML Group", summary: "UCL Google DeepMind Chair 与 Google DeepMind Research Director，研究数据高效学习、概率建模、机器人和自主决策，并将方法用于气候、天气与核聚变。", sources: [profile("Marc Deisenroth homepage", "https://www.deisenroth.cc/", "Current UCL and Google DeepMind roles, biography and research"), official("UCL AI people", "https://www.ucl.ac.uk/engineering/research/centres-institutes-and-labs/ucl-centre-artificial-intelligence/people", "Current chair and centre membership"), profile("Sustainability and ML Group", "https://www.sml-group.cc/", "Current group leadership and research programme")]}),
  person({ id: "lourdes-agapito-eu", name: "Lourdes Agapito", role: "Professor of 3D Vision", institution: "UCL", area: "Computer Vision · 3D Reconstruction", tags: ["计算机视觉", "三维视觉", "动态重建", "视觉几何"], stage: "senior", node: "UCL Vision and Imaging Science", summary: "UCL 三维视觉资深 PI，研究非刚性重建、动态场景理解和视觉几何。", sources: [official("UCL AI people", "https://www.ucl.ac.uk/engineering/research/centres-institutes-and-labs/ucl-centre-artificial-intelligence/people", "Current professorial appointment"), official("UCL CS key contacts", "https://www.ucl.ac.uk/engineering/computer-science/people/computer-science-key-contacts?isMobile=0", "Vision research leadership")]}),
  person({ id: "david-silver-eu", name: "David Silver", role: "Professor of Computer Science", institution: "UCL", area: "Reinforcement Learning · Planning", tags: ["强化学习", "规划", "AlphaGo", "Google DeepMind"], stage: "senior", node: "UCL Reinforcement Learning", summary: "强化学习与规划领域的重要学术—产业双栖节点，研究谱系与 DeepMind 的 AlphaGo/AlphaZero 路线高度相关。", sources: [official("UCL Intelligent Systems", "https://www.ucl.ac.uk/engineering/computer-science/research/research-groups-and-centres/intelligent-systems-group", "Current UCL faculty membership"), profile("David Silver homepage", "https://www.davidsilver.uk/", "Research and public biography")]}),

  person({ id: "mirella-lapata-eu", name: "Mirella Lapata", role: "Professor of Natural Language Processing", institution: "Edinburgh", area: "NLP · Language Generation · Multimodal AI", tags: ["NLP", "语言生成", "多模态", "Generative AI"], stage: "senior", node: "Edinburgh NLP / GAIL", summary: "Edinburgh NLP 核心带头人之一，研究语言生成、理解和多模态学习，并领导学校生成式 AI 实验室。", sources: [official("Edinburgh GAIL leadership", "https://gail.ed.ac.uk/about-gail/meet-gail-leadership-team/professor-mirella-lapata", "Current leadership and research"), profile("Mirella Lapata homepage", "https://homepages.inf.ed.ac.uk/mlap/", "Group, students and publications")]}),
  person({ id: "ivan-titov-eu", name: "Ivan Titov", role: "Professor of Computational Linguistics", institution: "Edinburgh", area: "NLP · Representation Learning · Reasoning", tags: ["NLP", "表征学习", "推理", "多语言"], stage: "senior", node: "Edinburgh NLP", summary: "Edinburgh 计算语言学资深 PI，研究语义表示、多语言学习和神经符号推理。", sources: [official("Edinburgh NLP supervisors", "https://informatics.ed.ac.uk/cdt-in-machine-learning-systems/people/supervisors/natural-language-processing-and-speech-systems", "Current supervisor status and research"), profile("Ivan Titov homepage", "https://www.ivan-titov.org/", "Research group and publications")]}),
  person({ id: "hakan-bilen-eu", name: "Hakan Bilen", role: "Professor of Computer Vision", institution: "Edinburgh", area: "Computer Vision · Video Understanding", tags: ["计算机视觉", "视频理解", "弱监督学习", "生成视觉"], stage: "senior", node: "Visual Computing Group", summary: "Edinburgh 视觉 PI，研究弱监督视觉学习、视频理解和生成式视觉；博士谱系连接 KU Leuven。", sources: [official("Edinburgh profile", "https://people.inf.ed.ac.uk/Hakan_Bilen.html", "Current appointment and research"), profile("Hakan Bilen homepage", "https://homepages.inf.ed.ac.uk/hbilen/", "Biography, group and publications")]}),
  person({ id: "amos-storkey-eu", name: "Amos Storkey", role: "Professor of Machine Learning", institution: "Edinburgh", area: "Machine Learning · Generative Models", tags: ["机器学习", "生成模型", "贝叶斯学习", "AI for Science"], stage: "senior", node: "Institute for Machine Learning", summary: "Edinburgh 机器学习资深 PI，研究概率与生成式机器学习、科学智能和可靠学习。", sources: [official("Edinburgh IML academics", "https://people.inf.ed.ac.uk/iml/academic.html", "Current institute faculty roster"), profile("Amos Storkey homepage", "https://homepages.inf.ed.ac.uk/amos/", "Research programme and group")]}),

  person({ id: "andreas-krause-eu", name: "Andreas Krause", role: "Professor of Computer Science", institution: "ETH Zurich", area: "Machine Learning · Decision Making · Trustworthy AI", tags: ["机器学习", "决策", "可信 AI", "主动学习"], stage: "senior", node: "Learning & Adaptive Systems / ETH AI Center", summary: "ETH 机器学习资深 PI，研究可靠决策、主动学习与自适应系统，并参与 ETH AI Center 建设。", sources: [official("ETH AI Center faculty", "https://ai.ethz.ch/about-us/people/faculty.html", "Current faculty membership and topics"), profile("LAS group", "https://las.inf.ethz.ch/", "Lab leadership and research")]}),
  person({ id: "marc-pollefeys-eu", name: "Marc Pollefeys", role: "Professor of Computer Science", institution: "ETH Zurich", area: "Computer Vision · 3D Reconstruction · Robotics", tags: ["计算机视觉", "三维重建", "机器人", "Microsoft"], stage: "senior", node: "Computer Vision and Geometry Group", summary: "三维视觉与机器人感知资深 PI，同时领导 Microsoft Mixed Reality & AI Lab Zurich，具备清晰的产学双向连接。", sources: [official("ETH AI Center faculty", "https://ai.ethz.ch/about-us/people/faculty.html", "Current faculty and research"), profile("Marc Pollefeys homepage", "https://people.inf.ethz.ch/pomarc/index.html", "Group and Microsoft role")]}),
  person({ id: "siyu-tang-eu", name: "Siyu Tang", role: "Associate Professor of Computer Science", institution: "ETH Zurich", area: "Computer Vision · 3D Humans · Embodied AI", tags: ["计算机视觉", "三维人体", "具身 AI", "生成模型"], stage: "emerging", node: "Computer Vision and Learning Group", summary: "ETH 新生代视觉 PI，聚焦三维人体、场景理解、生成式视觉与具身感知。", sources: [official("ETH AI Center faculty", "https://ai.ethz.ch/about-us/people/faculty.html", "Current title and research"), official("ETH D-INFK ML", "https://inf.ethz.ch/research/data-management-machine-learning.html", "Department research roster")]}),
  person({ id: "thomas-hofmann-eu", name: "Thomas Hofmann", role: "Professor of Data Analytics", institution: "ETH Zurich", area: "Machine Learning · Language Models", tags: ["机器学习", "语言模型", "数据分析", "学习理论"], stage: "senior", node: "ETH Data Analytics", summary: "ETH 机器学习与数据分析资深 PI，研究统计学习、表征与语言模型基础。", sources: [official("ETH AI Center faculty", "https://ai.ethz.ch/about-us/people/faculty.html", "Current faculty roster"), official("ETH D-INFK ML", "https://inf.ethz.ch/research/data-management-machine-learning.html", "Research area and faculty")]}),

  person({ id: "antoine-bosselut-eu", name: "Antoine Bosselut", role: "Assistant Professor", institution: "EPFL", area: "NLP · LLM · Knowledge and Reasoning", tags: ["NLP", "LLM", "知识推理", "发展期 PI"], stage: "emerging", node: "EPFL Natural Language Processing Lab", summary: "EPFL 新生代 NLP PI，研究知识增强语言模型、常识推理和生成式 AI。", sources: [official("EPFL profile", "https://people.epfl.ch/antoine.bosselut?lang=en", "Current appointment and research"), official("EPFL NLP faculty", "https://www.epfl.ch/schools/ic/fr/recherche/traitement-automatique-langage/", "NLP faculty roster")]}),
  person({ id: "martin-jaggi-eu", name: "Martin Jaggi", role: "Professor of Machine Learning", institution: "EPFL", area: "Machine Learning · Optimization · LLM", tags: ["机器学习", "优化", "LLM", "分布式训练"], stage: "senior", node: "Machine Learning and Optimization Lab", summary: "EPFL 机器学习与优化资深 PI，研究大规模优化、分布式学习与语言模型训练。", sources: [official("EPFL profile", "https://people.epfl.ch/martin.jaggi?lang=en", "Current appointment and research"), profile("MLO Lab", "https://www.epfl.ch/labs/mlo/", "Lab leadership and research")]}),
  person({ id: "pascal-fua-eu", name: "Pascal Fua", role: "Professor of Computer Science", institution: "EPFL", area: "Computer Vision · 3D Vision", tags: ["计算机视觉", "三维视觉", "人体建模", "医学影像"], stage: "senior", node: "Computer Vision Laboratory", summary: "EPFL 计算机视觉资深 PI，研究三维重建、人体建模和医学视觉。", sources: [official("EPFL CVLab people", "https://www.epfl.ch/labs/cvlab/people/", "Current lab leadership and people"), profile("EPFL CVLab", "https://www.epfl.ch/labs/cvlab/", "Research programme")]}),
  person({ id: "volkan-cevher-eu", name: "Volkan Cevher", role: "Professor of Electrical Engineering", institution: "EPFL", area: "Machine Learning · Optimization · Foundations", tags: ["机器学习", "优化", "学习理论", "Amazon"], stage: "senior", node: "LIONS", summary: "EPFL 机器学习基础与优化资深 PI，研究可扩展学习算法，并与产业研究项目保持公开连接。", sources: [official("EPFL LIONS profile", "https://www.epfl.ch/labs/lions/people/volkan-cevher/", "Current title, research and affiliations"), profile("EPFL LIONS", "https://www.epfl.ch/labs/lions/", "Lab leadership and research")]}),

  person({ id: "bernhard-schoelkopf-eu", name: "Bernhard Schölkopf", role: "Director, Max Planck Institute for Intelligent Systems", institution: "Tübingen/MPI", area: "Machine Learning · Causality", tags: ["机器学习", "因果学习", "核方法", "AI 基础"], stage: "senior", node: "Empirical Inference Department", summary: "统计机器学习、核方法与因果学习的代表性资深学者，是 Tübingen–Max Planck 机器学习生态的核心节点。", sources: [official("Tübingen CS research", "https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/forschung/", "Current professor affiliation and ML area"), official("IMPRS-IS faculty news", "https://imprs.is.tue.mpg.de/news/bernhard-scholkopf-receives-frontiers-of-knowledge-award", "Institute leadership and research recognition")]}),
  person({ id: "andreas-geiger-eu", name: "Andreas Geiger", role: "Professor of Autonomous Machine Vision", institution: "Tübingen/MPI", area: "Computer Vision · Autonomous Systems · 3D", tags: ["计算机视觉", "自动驾驶", "三维视觉", "KITTI"], stage: "senior", node: "Autonomous Vision Group", summary: "自主视觉与三维场景建模代表性 PI，KITTI 基准共同创建者，连接感知、自动系统和生成式三维世界模型。", sources: [official("Tübingen CS research", "https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/forschung/", "Current chair and research"), official("IMPRS-IS news", "https://imprs.is.tue.mpg.de/news", "Current faculty activity and AI research")]}),
  person({ id: "michael-black-eu", name: "Michael J. Black", role: "Director, Max Planck Institute for Intelligent Systems", institution: "Tübingen/MPI", area: "Computer Vision · Human Motion", tags: ["计算机视觉", "人体建模", "运动估计", "MPI-IS"], stage: "senior", node: "Perceiving Systems", summary: "人体运动、形状与视觉感知的资深学者，长期领导 MPI-IS Perceiving Systems 部门。", sources: [official("Tübingen CS research", "https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/forschung/", "Current honorary professorship and research"), profile("Perceiving Systems", "https://ps.is.mpg.de/", "Department leadership and research")]}),
  person({ id: "zeynep-akata-eu", name: "Zeynep Akata", role: "Liesel Beckmann Distinguished Professor", institution: "TUM", area: "Explainable · Multimodal Machine Learning", tags: ["可解释 AI", "多模态", "视觉语言", "可靠学习"], stage: "senior", node: "Explainable Machine Learning", summary: "多模态与可解释机器学习代表性学者，现任 TUM 特聘教授并领导 Helmholtz Munich 可解释机器学习研究。", sources: [official("Helmholtz Munich profile", "https://www.eml-munich.de/people/zeynep-akata", "Current professorship and institute leadership"), profile("Zeynep Akata homepage", "https://www.eml-munich.de/", "Research group and programme")]}),

  person({ id: "iryna-gurevych-eu", name: "Iryna Gurevych", role: "Professor of Computer Science", institution: "TU Darmstadt", area: "NLP · LLM · Information Quality", tags: ["NLP", "LLM", "信息质量", "可信 AI"], stage: "senior", node: "Ubiquitous Knowledge Processing Lab", summary: "德国 NLP 资深 PI，研究跨文档理解、信息质量、文本推理与可信语言技术。", sources: [official("TU Darmstadt UKP head", "https://www.informatik.tu-darmstadt.de/ukp/ukp_home/head_ukp/index.en.jsp", "Current title and research"), official("TU Darmstadt excellence", "https://www.informatik.tu-darmstadt.de/forschung_fb20/forschungsprogramme/exzellenzprogramme/index.en.jsp", "ERC programme and current research")]}),
  person({ id: "stefan-roth-eu", name: "Stefan Roth", role: "Professor of Computer Science", institution: "TU Darmstadt", area: "Computer Vision · Robust and Explainable AI", tags: ["计算机视觉", "鲁棒 AI", "可解释 AI", "场景理解"], stage: "senior", node: "Visual Inference Lab", summary: "TU Darmstadt 视觉 PI，研究统计视觉、场景理解以及鲁棒、可解释的深度网络。", sources: [official("TU Darmstadt profile", "https://www.visinf.tu-darmstadt.de/visual_inference/people_vi/stefan_roth.en.jsp", "Current title, biography and research"), official("Visual Inference Lab", "https://www.visinf.tu-darmstadt.de/", "Lab leadership and research")]}),

  person({ id: "max-welling-eu", name: "Max Welling", role: "Professor of Machine Learning", institution: "UvA", area: "Machine Learning · Generative Models · AI for Science", tags: ["机器学习", "生成模型", "AI for Science", "创业"], stage: "senior", node: "Amsterdam Machine Learning Lab", summary: "Amsterdam 机器学习资深 PI，研究生成模型和科学智能；公开资料记录其 CuspAI 创业连接。", sources: [official("UvA profile", "https://www.uva.nl/en/profile/w/e/m.welling/m.welling.html", "Current appointment and research"), official("UvA AI award profile", "https://www.uva.nl/shared-content/uva/en/news/news/2026/03/dutch-ai-award-for-max-welling.html", "Current research and CuspAI role")]}),
  person({ id: "cees-snoek-eu", name: "Cees Snoek", role: "Professor of Intelligent Sensory Information Systems", institution: "UvA", area: "Computer Vision · Video Understanding", tags: ["计算机视觉", "视频理解", "多模态", "检索"], stage: "senior", node: "Video and Image Sense Lab", summary: "Amsterdam 视觉与视频理解资深 PI，研究视觉检索、视频表征和多模态感知。", sources: [official("UvA profile", "https://www.uva.nl/profiel/s/n/c.g.m.snoek/c.g.m.snoek.html", "Current title and research"), profile("VIS Lab", "https://ivi.fnwi.uva.nl/vislab/", "Lab leadership and programme")]}),
  person({ id: "maarten-de-rijke-eu", name: "Maarten de Rijke", role: "University Professor of AI and Information Retrieval", institution: "UvA", area: "Information Retrieval · NLP · Responsible AI", tags: ["信息检索", "NLP", "推荐系统", "产业实验室"], stage: "senior", node: "Information and Language Processing Systems", summary: "信息检索与语言技术资深 PI，通过 ICAI 等机制连接大学团队与企业联合实验室。", sources: [official("UvA university professor profile", "https://www.uva.nl/en/about-the-uva/organisation/professors/university-professors/maarten-de-rijke.html", "Current title and research"), profile("ILPS", "https://ilps.science.uva.nl/", "Research group and industry-facing programme")]}),

  person({ id: "luc-de-raedt-eu", name: "Luc De Raedt", role: "Full Professor of Computer Science", institution: "KU Leuven", area: "Machine Learning · Neuro-Symbolic AI", tags: ["机器学习", "神经符号 AI", "概率编程", "知识表示"], stage: "senior", node: "DTAI Machine Learning", summary: "统计关系学习、概率编程与神经符号 AI 代表性资深 PI，形成广泛欧洲导师谱系。", sources: [official("KU Leuven profile", "https://www.kuleuven.be/wieiswie/en/person/00010316", "Current title and unit"), profile("Luc De Raedt homepage", "https://wms.cs.kuleuven.be/people/lucderaedt/", "Research, group and students")]}),
  person({ id: "tinne-tuytelaars-eu", name: "Tinne Tuytelaars", role: "Full Professor", institution: "KU Leuven", area: "Computer Vision · Continual Learning", tags: ["计算机视觉", "持续学习", "表征学习", "导师谱系"], stage: "senior", node: "PSI Visual Recognition", summary: "KU Leuven 视觉资深 PI，研究表征、持续学习和视觉识别；公开履历记录多位校友进入高校与 Google、DeepMind、Huawei 等公司。", sources: [official("KU Leuven profile", "https://www.kuleuven.be/wieiswie/EN/person/00018289", "Current title and unit"), profile("Tinne Tuytelaars homepage", "https://www.esat.kuleuven.be/psi/TT/", "Research group and supervision")]}),
  person({ id: "jesse-davis-eu", name: "Jesse Davis", role: "Professor of Computer Science", institution: "KU Leuven", area: "Machine Learning · Data Mining", tags: ["机器学习", "数据挖掘", "关系学习", "Sports Analytics"], stage: "senior", node: "DTAI Machine Learning", summary: "KU Leuven DTAI 教授，研究机器学习、数据挖掘、复杂结构数据和体育分析。", sources: [official("KU Leuven profile", "https://www.kuleuven.be/wieiswie/en/person/00071880", "Current title and research"), profile("Jesse Davis homepage", "https://people.cs.kuleuven.be/~jesse.davis/", "Biography, teaching and research")]}),

  person({ id: "cordelia-schmid-eu", name: "Cordelia Schmid", role: "Inria Research Director", institution: "Inria", area: "Computer Vision · Video Understanding", tags: ["计算机视觉", "视频理解", "视觉表征", "Google Research"], stage: "senior", node: "THOTH / WILLOW", summary: "法国计算机视觉资深研究主任，研究图像与视频表征、识别和视觉学习，并有公开 Google Research 联合任职。", sources: [official("Inria award profile", "https://www.inria.fr/en/cordelia-schmid-inria-french-academie-des-sciences-grand-prize", "Research director status and research"), profile("Cordelia Schmid homepage", "https://thoth.inrialpes.fr/~schmid/", "Current role, research and Google affiliation")]}),
  person({ id: "gael-varoquaux-eu", name: "Gaël Varoquaux", role: "Inria Research Director · SODA Team Lead", institution: "Inria", area: "Machine Learning · Data Science · Health", tags: ["机器学习", "数据科学", "医疗 AI", "scikit-learn"], stage: "senior", node: "SODA / scikit-learn", summary: "开放机器学习基础设施的重要学术节点，领导 Inria SODA 团队并长期参与 scikit-learn。", sources: [official("Inria profile", "https://www.inria.fr/fr/gael-varoquaux-0", "Research and scikit-learn role"), official("Inria SODA", "https://www.inria.fr/fr/soda", "Current team leadership and research")]}),
  person({ id: "benoit-sagot-eu", name: "Benoît Sagot", role: "Inria Research Director", institution: "Inria", area: "NLP · Language Resources · Multilingual AI", tags: ["NLP", "多语言", "语言资源", "数字人文"], stage: "senior", node: "ALMAnaCH", summary: "法国 NLP 与语言资源资深研究者，研究多语言建模、语言资源和数字人文。", sources: [official("Inria ALMAnaCH", "https://cristal.inria.fr/", "Current team and research programme"), profile("Benoît Sagot homepage", "https://pauillac.inria.fr/~sagot/", "Biography and research")]}),

  person({ id: "roberto-navigli-eu", name: "Roberto Navigli", role: "Professor of Computer Science", institution: "Sapienza", area: "NLP · Word Sense · Multilingual LLM", tags: ["NLP", "多语言", "词义消歧", "Babelscape"], stage: "senior", node: "Sapienza NLP / Babelscape", summary: "词义消歧、多语言语义和语言模型资深 PI，也是 Babelscape 联合创办人，连接欧洲 NLP 与产业转化。", sources: [official("Sapienza profile", "https://www.diag.uniroma1.it/users/roberto_navigli", "Current appointment and research"), official("Sapienza research profile", "https://research.uniroma1.it/researcher/d32105ad5bf72bddaaba4f07d3da93a7d7af490fc37349ebc79d7c21", "Research programme and projects")]}),
];

const relation = (id: string, from: string, to: string, type: Relationship["type"], label: string, evidence: string, source: Source, subtype: Relationship["subtype"]): Relationship => ({ id, from, to, type, label, evidence, source, subtype, verified: true });

export const europeRelationships: Relationship[] = [
  relation("eu-riedel-vlachos", "sebastian-riedel-eu", "andreas-vlachos-eu", "talent", "博士后合作 / UCL", "Andreas Vlachos 的公开履历记录其曾在 UCL Machine Reading Group 与 Sebastian Riedel 从事博士后研究。", profile("Andreas Vlachos homepage", "https://andreasvlachos.github.io/", "Postdoctoral collaboration at UCL"), "postdoc_mentor"),
  relation("eu-riedel-rocktaschel", "sebastian-riedel-eu", "tim-rocktaschel-eu", "lineage", "博士导师", "UCL 博士论文致谢明确称 Sebastian Riedel 为 Tim Rocktäschel 的博士导师。", official("UCL doctoral thesis", "https://discovery.ucl.ac.uk/10040845/1/Rocktaeschel_ID_thesis.pdf", "Doctoral supervision"), "phd_adviser"),
  relation("eu-tuytelaars-bilen", "tinne-tuytelaars-eu", "hakan-bilen-eu", "lineage", "博士导师", "Tinne Tuytelaars 的公开履历将 Hakan Bilen 列为已毕业博士生，后任 Edinburgh 教授。", profile("Tinne Tuytelaars CV", "https://doctorat.unibuc.ro/wp-content/uploads/2022/01/cv_TinneTuytelaars.pdf", "Doctoral alumni and destination"), "phd_adviser"),
  relation("eu-schmid-akata", "cordelia-schmid-eu", "zeynep-akata-eu", "lineage", "博士导师", "Max Planck 官方简介记录 Zeynep Akata 在 Inria Rhône-Alpes 由 Cordelia Schmid 指导完成博士。", official("MPI-IS profile", "https://is.mpg.de/de/person/zakata", "Doctoral supervision and career path"), "phd_adviser"),
  relation("eu-welling-akata", "max-welling-eu", "zeynep-akata-eu", "talent", "UvA 独立 PI 阶段", "Max Planck 官方履历记录 Zeynep Akata 在 2017–2019 年于 UvA 与 Max Welling 工作。", official("MPI-IS profile", "https://is.mpg.de/de/person/zakata", "UvA career stage"), "career_movement"),
];

export const europeGroupMembers: GroupMember[] = [
  { id: "eu-korhonen-li", teacherId: "anna-korhonen-eu", name: "Yaoyiran Li", role: "PhD student", focus: "Natural Language Processing", source: official("Cambridge MMLL profile", "https://www.mmll.cam.ac.uk/people/anna-korhonen", "Current supervised students") },
  { id: "eu-korhonen-liu", teacherId: "anna-korhonen-eu", name: "Qianchu (Flora) Liu", role: "PhD student", focus: "Natural Language Processing", source: official("Cambridge MMLL profile", "https://www.mmll.cam.ac.uk/people/anna-korhonen", "Current supervised students") },
];

export const europeStudentPlacements: StudentPlacement[] = [
  { id: "eu-tuytelaars-bilen-placement", student: "Hakan Bilen", teacherId: "tinne-tuytelaars-eu", company: "University of Edinburgh", role: "Professor of Computer Vision", kind: "current", degree: "PhD", sector: "academia", highLevel: true, source: profile("Tinne Tuytelaars CV", "https://doctorat.unibuc.ro/wp-content/uploads/2022/01/cv_TinneTuytelaars.pdf", "PhD alumnus and current institution") },
  { id: "eu-tuytelaars-industry", student: "公开校友群体", teacherId: "tinne-tuytelaars-eu", company: "Google / DeepMind / Huawei / Ford / Toyota", role: "Research positions", kind: "reported", sector: "industry", note: "来源以群体方式列出产业去向，尚未逐人拆分。", source: profile("Tinne Tuytelaars CV", "https://doctorat.unibuc.ro/wp-content/uploads/2022/01/cv_TinneTuytelaars.pdf", "Reported industry destinations") },
];

export const europeCoverage = [
  { region: "Europe" as const, institution: "Oxford" as const, core: 5, adjacent: 0, note: "AI/ML、视觉、智能体与科学智能代表性 PI" },
  { region: "Europe" as const, institution: "Cambridge" as const, core: 5, adjacent: 0, note: "NLP、机器学习、人本 AI 与视觉" },
  { region: "Europe" as const, institution: "UCL" as const, core: 5, adjacent: 0, note: "机器阅读、强化学习、统计 ML 与三维视觉" },
  { region: "Europe" as const, institution: "Edinburgh" as const, core: 4, adjacent: 0, note: "NLP、生成式 AI、视觉与机器学习" },
  { region: "Europe" as const, institution: "ETH Zurich" as const, core: 4, adjacent: 0, note: "学习基础、三维视觉、具身与可靠 AI" },
  { region: "Europe" as const, institution: "EPFL" as const, core: 4, adjacent: 0, note: "NLP、优化、视觉与机器学习基础" },
  { region: "Europe" as const, institution: "Tübingen/MPI" as const, core: 3, adjacent: 0, note: "因果 ML、自主视觉与人体感知" },
  { region: "Europe" as const, institution: "TUM" as const, core: 1, adjacent: 0, note: "可解释与多模态机器学习" },
  { region: "Europe" as const, institution: "TU Darmstadt" as const, core: 2, adjacent: 0, note: "NLP、鲁棒和可解释视觉" },
  { region: "Europe" as const, institution: "UvA" as const, core: 3, adjacent: 0, note: "机器学习、视觉与信息检索" },
  { region: "Europe" as const, institution: "KU Leuven" as const, core: 3, adjacent: 0, note: "神经符号学习、视觉与数据挖掘" },
  { region: "Europe" as const, institution: "Inria" as const, core: 3, adjacent: 0, note: "视觉、开放机器学习基础设施与多语言 NLP" },
  { region: "Europe" as const, institution: "Sapienza" as const, core: 1, adjacent: 0, note: "多语言语义与 NLP" },
];

export const europeCommunities = [
  { region: "Europe" as const, kicker: "语言与知识", name: "European NLP, LLM & Knowledge Network", anchor: "Mirella Lapata · Sebastian Riedel · Anna Korhonen · Iryna Gurevych · Antoine Bosselut · Roberto Navigli · Benoît Sagot", description: "从多语言 NLP、机器阅读和知识推理，延伸到生成式语言模型、信息质量与人本 AI。", color: "cobalt" },
  { region: "Europe" as const, kicker: "视觉与空间智能", name: "European Vision, 3D & Embodied AI", anchor: "Philip Torr · Roberto Cipolla · Marc Pollefeys · Pascal Fua · Andreas Geiger · Michael Black · Cordelia Schmid · Tinne Tuytelaars", description: "覆盖三维视觉、人体与场景建模、视频理解、机器人感知和具身智能。", color: "lime" },
  { region: "Europe" as const, kicker: "学习基础", name: "Machine Learning Foundations & Reliable AI", anchor: "Yarin Gal · Michael Bronstein · Bernhard Schölkopf · Andreas Krause · Max Welling · Luc De Raedt · Volkan Cevher", description: "连接不确定性、几何学习、因果、神经符号、优化和科学智能。", color: "coral" },
  { region: "Europe" as const, kicker: "学界—产业双向流动", name: "European Academic–Industry Bridges", anchor: "David Silver · Marc Pollefeys · Neil Lawrence · Roberto Cipolla · Max Welling · Roberto Navigli", description: "以 DeepMind、Microsoft、Amazon、Toshiba、CuspAI 与 Babelscape 等公开任职或创业记录呈现产学连接。", color: "violet" },
];

export const europeIndustryPathways: IndustryPathway[] = [
  { id: "eu-pollefeys-microsoft", region: "Europe", kind: "JOINT ACADEMIC–INDUSTRY LEADERSHIP", title: "Marc Pollefeys ↔ Microsoft", description: "个人主页记录其领导 Microsoft Mixed Reality & AI Lab Zurich，同时任 ETH Zurich 教授。", source: profile("Marc Pollefeys homepage", "https://people.inf.ethz.ch/pomarc/index.html", "Microsoft and ETH roles") },
  { id: "eu-lawrence-amazon", region: "Europe", kind: "INDUSTRY-TO-ACADEMIA", title: "Neil Lawrence ↔ Amazon", description: "Cambridge 官方简介记录其出任 DeepMind Professor 前曾任 Amazon Director of Machine Learning。", source: official("Cambridge profile", "https://www.cst.cam.ac.uk/people/ndl21", "Amazon career history") },
  { id: "eu-cipolla-toshiba", region: "Europe", kind: "RESEARCH LAB LEADERSHIP", title: "Roberto Cipolla ↔ Toshiba", description: "Cambridge Engineering 官方页列其为 Toshiba Cambridge Research Laboratory 主任。", source: official("Cambridge Engineering profile", "https://www.eng.cam.ac.uk/profiles/rc10001", "Toshiba laboratory role") },
  { id: "eu-welling-cuspai", region: "Europe", kind: "STARTUP", title: "Max Welling ↔ CuspAI", description: "UvA 2026 官方报道记录 Max Welling 的 CuspAI 联合创办人身份。", source: official("UvA AI award profile", "https://www.uva.nl/shared-content/uva/en/news/news/2026/03/dutch-ai-award-for-max-welling.html", "CuspAI co-founder role") },
  { id: "eu-navigli-babelscape", region: "Europe", kind: "STARTUP", title: "Roberto Navigli ↔ Babelscape", description: "Sapienza 公开研究履历与实验室资料记录其将多语言语义技术延伸到 Babelscape。", source: official("Sapienza profile", "https://www.diag.uniroma1.it/users/roberto_navigli", "Academic and technology-transfer profile") },
  { id: "eu-schmid-google", region: "Europe", kind: "JOINT AFFILIATION", title: "Cordelia Schmid ↔ Google Research", description: "公开主页记录其自 2018 年起与 Google Research 联合任职。", source: profile("Cordelia Schmid homepage", "https://thoth.inrialpes.fr/~schmid/", "Google Research joint appointment") },
];
