import type { Person, Relationship, Source } from "./data";

const checkedAt = "2026-09-02";

const official = (label: string, url: string, supports: string): Source => ({
  label,
  url,
  kind: "official",
  checkedAt,
  supports,
});

const rosterSource = official(
  "华中科技大学人工智能与自动化学院师资名录",
  "https://aia.hust.edu.cn/szdw/xysz/axlb.htm",
  "自主智能与智能控制系教师名录、职称分组与官方个人页入口",
);

type Seed = {
  id: string;
  name: string;
  role: string;
  area: string;
  tags: string[];
  summary: string;
  stage: Person["stage"];
  profileUrl: string;
  facts: { label: string; value: string }[];
  x: number;
  y: number;
};

function person(seed: Seed): Person {
  const profileSource = official(
    `华中科技大学官方教师主页 — ${seed.name}`,
    seed.profileUrl,
    "当前任职、研究方向、教育或学术训练，以及该页面发布的单人头像",
  );

  return {
    id: seed.id,
    name: seed.name,
    role: seed.role,
    institution: "HUST",
    region: "Mainland China",
    area: seed.area,
    tags: seed.tags,
    summary: seed.summary,
    facts: seed.facts.map((fact) => ({ ...fact, source: profileSource })),
    stage: seed.stage,
    category: "core",
    status: "current PI · HUST AIA official roster verified",
    sources: [profileSource, rosterSource],
    x: seed.x,
    y: seed.y,
    primary: true,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: {
      src: `portraits/hust-aia-roster-2026/${seed.id}.jpg`,
      alt: `${seed.name} 华中科技大学官方教师头像`,
      source: profileSource,
    },
  };
}

export const hustAiaRosterPiExpansion1People: Person[] = [
  person({
    id: "chi-ming-hust",
    name: "池明",
    role: "教授 · 博士生导师 · 硕士生导师",
    area: "Networked Control · Multi-Robot Systems · Smart Grid",
    tags: ["网络化控制", "多机器人协同", "智能电网", "系统优化"],
    summary: "华中科技大学人工智能与自动化学院教授，围绕网络控制、多机器人协同与智能电网优化形成交叉研究主线。",
    stage: "senior",
    profileUrl: "http://faculty.hust.edu.cn/chiming/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页标注其为人工智能与自动化学院在职教授、博士生导师和硕士生导师。" },
      { label: "研究主线", value: "网络控制系统性能优化、多机器人协同控制、智能电网控制与优化。" },
      { label: "教育与学术训练", value: "2008 年获华中科技大学学士学位，2013 年在该校控制科学与工程专业获工学博士学位。" },
      { label: "为什么值得关注", value: "把控制理论、群体机器人与能源系统连接起来，并主持国家自然科学基金优青等国家级项目。" },
    ],
    x: 120,
    y: 120,
  }),
  person({
    id: "deng-zhonghua-hust",
    name: "邓忠华",
    role: "教授 · 博士生导师",
    area: "Intelligent Control · Digital Motion Control · Industrial Automation",
    tags: ["智能控制", "数字运动控制", "多轴装备", "工业自动化"],
    summary: "华中科技大学人工智能与自动化学院教授，长期推动套印与多轴联动装备的智能控制及成果转化。",
    stage: "senior",
    profileUrl: "https://aia.hust.edu.cn/info/1691/10467.htm",
    facts: [
      { label: "当前任职", value: "学院官方页面列其为教授、博士生导师。" },
      { label: "研究主线", value: "套印智能控制、电气传动系统数字化控制和多轴联动智能装备控制。" },
      { label: "教育与学术训练", value: "1985 年获华中理工大学工业自动化专业硕士学位，1994 年获该校控制理论与控制工程博士学位。" },
      { label: "为什么值得关注", value: "其多轴联动控制成果已在套色印刷与包装行业完成产品化和批量应用。" },
    ],
    x: 260,
    y: 120,
  }),
  person({
    id: "yin-quan-hust",
    name: "尹泉",
    role: "教授",
    area: "Servo Control · Embedded Control · Intelligent Motion Systems",
    tags: ["伺服控制", "嵌入式控制", "智能运动系统", "变频电源"],
    summary: "华中科技大学人工智能与自动化学院教授，研究数字伺服、嵌入式控制及智能控制在运动系统中的应用。",
    stage: "senior",
    profileUrl: "https://aia.hust.edu.cn/info/1691/10478.htm",
    facts: [
      { label: "当前任职", value: "学院官方页面列其为教授。" },
      { label: "研究主线", value: "全数字交流伺服、广义变频电源数字化控制、嵌入式控制，以及智能控制的运动系统应用。" },
      { label: "教育与学术训练", value: "先后在华中理工大学获学士、硕士学位，2001 年在华中科技大学获控制理论与控制工程博士学位。" },
      { label: "为什么值得关注", value: "长期参与电动汽车、电机驱动、舰炮控制及网络化伺服等工程研究。" },
    ],
    x: 400,
    y: 120,
  }),
  person({
    id: "zhang-haitao-hust",
    name: "张海涛",
    role: "副院长 · 二级教授 · 博士生导师",
    area: "Swarm Intelligence · Autonomous Systems · Multi-Robot Coordination",
    tags: ["群体智能", "自主无人系统", "多机器人", "协同制造"],
    summary: "华中科技大学人工智能与自动化学院副院长，研究群体智能、无人艇集群与多机器人协同制造。",
    stage: "institute",
    profileUrl: "https://aia.hust.edu.cn/info/1691/10480.htm",
    facts: [
      { label: "当前任职", value: "学院官方页面列其为副院长、二级教授、博士生导师，并任自主智能无人系统教育部工程研究中心主任。" },
      { label: "研究主线", value: "人工智能、群体智能、群体机器人协同制造和全自主无人艇集群协同控制。" },
      { label: "教育与学术训练", value: "2005 年在中国科学技术大学获博士学位，2007 年在剑桥大学从事博士后研究。" },
      { label: "为什么值得关注", value: "其理论研究与大型海洋设施检测、海上风电和油气勘测等真实场景相连接。" },
    ],
    x: 540,
    y: 120,
  }),
  person({
    id: "zhao-jin-hust",
    name: "赵金",
    role: "教授 · 博士生导师",
    area: "Fault-Tolerant Control · Medical AI · Autonomous Navigation",
    tags: ["故障预测", "容错控制", "医疗 AI", "无人航行"],
    summary: "华中科技大学人工智能与自动化学院教授，连接复杂系统容错、医学人工智能和无人船自主航行。",
    stage: "senior",
    profileUrl: "http://faculty.hust.edu.cn/zhaojin1/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页标注其为人工智能与自动化学院在职教授、博士生导师和硕士生导师。" },
      { label: "研究主线", value: "电力电子与运动控制、复杂工程系统故障预测与容错、医学人工智能和无人船舶智能航行。" },
      { label: "教育与学术训练", value: "1994 年在华中理工大学工业自动化专业获工学博士学位；2001 年赴美国田纳西大学访问研究。" },
      { label: "为什么值得关注", value: "研究横跨可靠控制与医疗、海洋无人系统两类 AI 应用场景。" },
    ],
    x: 680,
    y: 120,
  }),
  person({
    id: "zhou-chunjie-hust",
    name: "周纯杰",
    role: "二级教授 · 博士生导师",
    area: "Industrial Internet · Cyber-Physical Security · Industrial AI",
    tags: ["工业互联网", "信息物理安全", "工业 AI", "数字孪生"],
    summary: "华中科技大学二级教授，研究工业互联网、工业信息物理系统安全与工业人工智能。",
    stage: "institute",
    profileUrl: "http://faculty.hust.edu.cn/zhouchunjie/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页列其为华中科技大学二级教授、博士生导师。" },
      { label: "研究主线", value: "工业通信网络、工业互联网、工控系统安全、工业人工智能和安全防护数字孪生。" },
      { label: "教育与学术训练", value: "在华中理工大学获学士、硕士学位，2001 年在华中科技大学获工学博士学位。" },
      { label: "为什么值得关注", value: "处在工业互联网基础设施、网络安全和 AI 工程应用的交汇处。" },
    ],
    x: 820,
    y: 120,
  }),
  person({
    id: "zhu-lijun-hust",
    name: "朱力军",
    role: "教授 · 博士生导师",
    area: "Biomimetic Robotics · Reinforcement Learning · Multi-Robot Systems",
    tags: ["仿生机器人", "强化学习", "机器人集群", "智能控制"],
    summary: "华中科技大学人工智能与自动化学院教授，研究仿生机器人智能控制、强化学习与机器人集群协同。",
    stage: "senior",
    profileUrl: "http://faculty.hust.edu.cn/ZHULIJUN/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页列其为人工智能与自动化学院教授、博士生导师。" },
      { label: "研究主线", value: "人形与四足等仿生机器人智能控制、强化学习的机器人应用和机器人集群协同。" },
      { label: "教育与学术训练", value: "2013 年获澳大利亚纽卡斯尔大学博士学位，后在纽卡斯尔大学和香港大学从事博士后研究。" },
      { label: "为什么值得关注", value: "把网络化控制基础与具身机器人和群体协同问题结合起来。" },
    ],
    x: 120,
    y: 280,
  }),
  person({
    id: "yuan-ye-hust",
    name: "袁烨",
    role: "教授 · 博士生导师",
    area: "Physical AI · System Identification · Robotic Manufacturing",
    tags: ["物理 AI", "系统辨识", "灵巧智能", "智能制造"],
    summary: "华中科技大学人工智能与自动化学院教授，聚焦物理 AI 系统的演化、辨识优化与机器人化智能制造。",
    stage: "senior",
    profileUrl: "http://faculty.hust.edu.cn/yeyuan/zh_CN/index/752531/list/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页列其为人工智能与自动化学院教授、博士生导师。" },
      { label: "研究主线", value: "物理 AI 系统演化机理、系统辨识优化理论与算法，以及机器人化智能制造。" },
      { label: "教育与学术训练", value: "2008 年获上海交通大学学士学位，2009 年和 2012 年分别获剑桥大学硕士、博士学位，期间赴加州理工联合培养。" },
      { label: "为什么值得关注", value: "其工作连接机器学习、控制理论和航空工业等高复杂度工程系统，并培养学生赴清华、剑桥、伯克利及产业界。" },
    ],
    x: 260,
    y: 280,
  }),
  person({
    id: "wang-yanwu-hust",
    name: "王燕舞",
    role: "二级教授 · 博士生导师",
    area: "Deep Learning · Reinforcement Learning · Distributed Control",
    tags: ["深度学习", "强化学习", "数据挖掘", "分布式控制"],
    summary: "华中科技大学二级教授，研究深度学习数据分析、强化学习优化调度和群体智能协同控制。",
    stage: "senior",
    profileUrl: "http://faculty.hust.edu.cn/wangyanwu/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页列其为华中科技大学二级教授、博士生导师。" },
      { label: "研究主线", value: "基于深度学习的混杂数据挖掘与预测、强化学习分布式调度和群体智能协同控制。" },
      { label: "教育与学术训练", value: "在华中理工大学获学士学位，并于 2000 年、2003 年在华中科技大学获硕士和博士学位。" },
      { label: "为什么值得关注", value: "长期把机器学习方法嵌入复杂网络、电网和多尺度群体系统的优化控制。" },
    ],
    x: 400,
    y: 280,
  }),
  person({
    id: "tai-ruochen-hust",
    name: "邰若晨",
    role: "教授 · 博士生导师",
    area: "Embodied AI · Swarm Robotics · AI Safety",
    tags: ["具身智能", "群体机器人", "AI 安全", "灵巧操作"],
    summary: "华中科技大学人工智能与自动化学院教授，研究大模型驱动的具身智能、群体机器人和安全自主系统。",
    stage: "emerging",
    profileUrl: "http://faculty.hust.edu.cn/tairuochen/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页列其为教授、博士生导师及国家级青年人才计划入选者。" },
      { label: "研究主线", value: "大模型驱动具身智能、多机器人协作、灵巧操作、无人机感知规划及无人系统 AI 安全。" },
      { label: "教育与学术训练", value: "2016 年获南京理工大学学士学位，2019 年获上海交通大学硕士学位，2023 年获南洋理工大学博士学位并继续从事博士后研究。" },
      { label: "为什么值得关注", value: "把控制系统安全与新一代具身、群体智能平台结合，是学院快速发展的年轻 PI 节点。" },
    ],
    x: 540,
    y: 280,
  }),
  person({
    id: "shen-anwen-hust",
    name: "沈安文",
    role: "教授 · 博士生导师",
    area: "Motion Control · Robotics · Process Control",
    tags: ["运动控制", "机器人", "新能源", "过程控制"],
    summary: "华中科技大学人工智能与自动化学院教授，长期研究运动控制、电力电子、机器人与生产过程控制。",
    stage: "senior",
    profileUrl: "https://aia.hust.edu.cn/info/1691/10474.htm",
    facts: [
      { label: "当前任职", value: "学院官方页面列其为教授、博士生导师。" },
      { label: "研究主线", value: "先进运动控制、电力电子、新能源、电动汽车控制、机器人和生产过程控制。" },
      { label: "教育与学术训练", value: "在浙江大学获学士、硕士学位，1997 年在华中理工大学获博士学位，随后完成控制科学与工程博士后训练。" },
      { label: "为什么值得关注", value: "官方简介记录其已指导博士 8 名、硕士 30 余名，并推动多项控制成果产业化。" },
    ],
    x: 680,
    y: 280,
  }),
  person({
    id: "liu-yang-aia-hust",
    name: "刘洋",
    role: "教授 · 博士生导师",
    area: "Machine Learning for Control · Health Management · Autonomous Systems",
    tags: ["机器学习控制", "健康管理", "无人系统", "人形机器人"],
    summary: "华中科技大学人工智能与自动化学院教授，研究机器学习驱动的关键器件控制、系统健康管理与无人平台执行机构。",
    stage: "senior",
    profileUrl: "http://faculty.hust.edu.cn/liuyang18/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页列其为人工智能与自动化学院教授、学术型和专业型博士生导师。" },
      { label: "研究主线", value: "无人系统执行机构、机器学习智能控制、数据驱动健康管理、人形机器人和自动驾驶相关控制。" },
      { label: "教育与学术训练", value: "2005 年和 2009 年分别在华中科技大学获硕士、博士学位。" },
      { label: "为什么值得关注", value: "把机器学习应用于关键器件、功率电子和无人系统，覆盖从算法到硬件执行链路。" },
    ],
    x: 820,
    y: 280,
  }),
  person({
    id: "liu-zhiwei-hust",
    name: "刘智伟",
    role: "教授 · 博士生导师",
    area: "Multi-Agent Systems · Smart Grid · Safe Reinforcement Learning",
    tags: ["多智能体", "智能电网", "安全强化学习", "分布式优化"],
    summary: "华中科技大学人工智能与自动化学院教授，研究多智能体协同、智能电网优化与安全强化学习。",
    stage: "senior",
    profileUrl: "http://faculty.hust.edu.cn/zwliu",
    facts: [
      { label: "当前任职", value: "官方主页列其为教授、博士生导师。" },
      { label: "研究主线", value: "AI 电力数据分析与预测、智能电网控制、无人集群协同、多智能体分布式优化和安全强化学习。" },
      { label: "教育与学术训练", value: "2011 年在华中科技大学获工学博士学位，之后在武汉大学任职并开展博士后研究。" },
      { label: "为什么值得关注", value: "公开研究横跨多智能体理论、电网需求响应和无人集群系统，并明确持续招收博士后及研究生。" },
    ],
    x: 120,
    y: 440,
  }),
  person({
    id: "he-dingxin-hust",
    name: "何顶新",
    role: "教授 · 教学实验中心主任",
    area: "Robot Control · Multi-Robot Navigation · Swarm Optimization",
    tags: ["机器人控制", "多机器人导航", "智能地图", "群体优化"],
    summary: "华中科技大学人工智能与自动化学院教授，研究机器人控制、智能地图建模与多机器人群体协同。",
    stage: "senior",
    profileUrl: "https://aia.hust.edu.cn/info/1691/10468.htm",
    facts: [
      { label: "当前任职", value: "学院官方页面列其为教授、教学实验中心主任。" },
      { label: "研究主线", value: "机器人控制、嵌入式控制、智能地图建模、多机器人定位导航和智能群体网络协同优化。" },
      { label: "教育与学术训练", value: "1987 年本科毕业于华中理工大学计算机系，1995 年获该校工业自动化硕士学位。" },
      { label: "为什么值得关注", value: "兼具机器人科研与长期创新训练经验，官方页面记录其已指导硕士 30 余人。" },
    ],
    x: 260,
    y: 440,
  }),
  person({
    id: "hu-xiaoya-hust",
    name: "胡晓娅",
    role: "教授",
    area: "AI Safety · Data Security · Industrial Internet Security",
    tags: ["AI 安全", "数据安全", "工业互联网", "系统安全"],
    summary: "华中科技大学人工智能与自动化学院教授，长期研究人工智能安全、数据安全和工业互联网系统安全。",
    stage: "senior",
    profileUrl: "http://faculty.hust.edu.cn/huxiaoya/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页列其为人工智能与自动化学院教授。" },
      { label: "研究主线", value: "人工智能、人工智能安全、数据安全、工业互联网及系统信息安全。" },
      { label: "教育与学术训练", value: "在华中理工大学获学士、硕士学位，2006 年在华中科技大学获工学博士学位。" },
      { label: "为什么值得关注", value: "研究覆盖模型与数据安全到工业互联网基础设施，并承担多项国家级安全相关项目。" },
    ],
    x: 400,
    y: 440,
  }),
  person({
    id: "cheng-cheng-aia-hust",
    name: "程骋",
    role: "副教授 · 博士生导师 · 硕士生导师",
    area: "Cyber-Physical Systems · Intelligent Manufacturing · Medical AI",
    tags: ["信息物理系统", "智能制造", "医疗 AI", "灵巧操作"],
    summary: "华中科技大学人工智能与自动化学院副教授，研究信息物理系统优化、智能制造与医疗人工智能。",
    stage: "emerging",
    profileUrl: "http://faculty.hust.edu.cn/~uQb2Mf/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页标注其为在职副教授、博士生导师和硕士生导师。" },
      { label: "研究主线", value: "信息物理系统建模与优化、机器人化智能制造灵巧操作、智能制造大数据和医疗人工智能。" },
      { label: "教育与学术训练", value: "2013 年和 2018 年获帝国理工学院硕士、博士学位，博士阶段由 Simos Evangelou 与 Daniele Dini 指导；回国后在华中科技大学从事博士后研究。" },
      { label: "为什么值得关注", value: "把控制与制造方法延伸到灵巧操作和医疗 AI，形成清晰的跨领域年轻 PI 轨迹。" },
    ],
    x: 540,
    y: 440,
  }),
  person({
    id: "luo-hui-hust",
    name: "罗慧",
    role: "副教授",
    area: "Intelligent Control · Signal Processing · Digital Drive Systems",
    tags: ["智能控制", "信号处理", "数字驱动", "交流传动"],
    summary: "华中科技大学人工智能与自动化学院副教授，研究数字交流驱动、信号处理与智能控制。",
    stage: "senior",
    profileUrl: "https://aia.hust.edu.cn/info/1692/10488.htm",
    facts: [
      { label: "当前任职", value: "学院官方页面列其为副教授。" },
      { label: "研究主线", value: "全数字交流驱动、新型交流传动、信号处理和智能控制。" },
      { label: "教育与学术训练", value: "1998 年获武汉理工大学学士学位，2001 年和 2009 年分别获华中科技大学硕士、博士学位。" },
      { label: "为什么值得关注", value: "长期围绕驱动系统控制与信号处理开展应用研究，并有研究生培养记录。" },
    ],
    x: 680,
    y: 440,
  }),
  person({
    id: "luo-xin-hust",
    name: "罗欣",
    role: "副研究员 · 博士生导师 · 硕士生导师",
    area: "Robot Control · Motion Control · Intelligent Manufacturing",
    tags: ["机器人", "运动控制", "智能制造", "新能源"],
    summary: "华中科技大学人工智能与自动化学院副研究员，研究机器人、运动控制与生产过程控制。",
    stage: "emerging",
    profileUrl: "http://faculty.hust.edu.cn/luoxin6/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页标注其为在职副研究员、博士生导师和硕士生导师。" },
      { label: "研究主线", value: "先进运动控制、机器人、生产过程控制、电力电子与新能源系统。" },
      { label: "教育与学术训练", value: "在华中科技大学获学士、硕士和博士学位，2015 至 2017 年在浙江大学电气学院从事博士后研究。" },
      { label: "为什么值得关注", value: "其工作处在机器人控制、制造装备和新能源执行系统的工程交叉地带。" },
    ],
    x: 820,
    y: 440,
  }),
  person({
    id: "ye-lintao-hust",
    name: "叶林涛",
    role: "副教授 · 硕士生导师",
    area: "Reinforcement Learning · Online Optimization · Control Theory",
    tags: ["强化学习", "在线优化", "控制理论", "分布式系统"],
    summary: "华中科技大学人工智能与自动化学院副教授，研究具有可解释性与性能保障的强化学习和优化算法。",
    stage: "emerging",
    profileUrl: "http://faculty.hust.edu.cn/yelintao/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页标注其自 2025 年起任人工智能与自动化学院副教授、硕士生导师。" },
      { label: "研究主线", value: "强化学习最优控制、在线与组合优化、大规模分布式强化学习及无人集群应用。" },
      { label: "教育与学术训练", value: "2015 年获华中科技大学学士学位，2017 年和 2020 年获普渡大学硕士、博士学位，之后在圣母大学从事博士后研究。" },
      { label: "为什么值得关注", value: "强调可解释、可验证的学习与控制算法，并公开招收本科生、研究生和博士后。" },
    ],
    x: 120,
    y: 600,
  }),
  person({
    id: "yu-yaowen-hust",
    name: "俞耀文",
    role: "副教授 · 硕士生导师",
    area: "AI for Power Systems · Energy Optimization · Electricity Markets",
    tags: ["电网大数据", "能源优化", "电力市场", "工业经历"],
    summary: "华中科技大学人工智能与自动化学院副教授，研究 AI 与电网大数据、能源系统优化和电力市场机制。",
    stage: "emerging",
    profileUrl: "http://faculty.hust.edu.cn/YuYaowen/zh_CN/index.htm",
    facts: [
      { label: "当前任职", value: "官方主页标注其自 2019 年起任人工智能与自动化学院副教授、硕士生导师。" },
      { label: "研究主线", value: "电力能源系统优化调度、人工智能与电网大数据、电力市场竞价和机制设计。" },
      { label: "教育与学术训练", value: "2011 年获华中科技大学学士学位，2016 年获康涅狄格大学电子工程博士学位。" },
      { label: "产业经历与关注点", value: "2016 至 2019 年在 ABB 美国硅谷办公室任高级应用工程师，形成学术方法与电力产业实践之间的直接连接。" },
    ],
    x: 260,
    y: 600,
  }),
];

export const hustAiaRosterPiExpansion1Relationships: Relationship[] = [];

export const hustAiaRosterPiExpansion1DeferredLeaderIds = new Set([
  "zhang-haitao-hust",
  "he-dingxin-hust",
]);

export const hustAiaRosterPiExpansion1PublishedPeople = hustAiaRosterPiExpansion1People.filter(
  (person) => !hustAiaRosterPiExpansion1DeferredLeaderIds.has(person.id),
);

export const hustAiaRosterPiExpansion1Portraits: Record<string, Person["portrait"]> =
  Object.fromEntries(
    hustAiaRosterPiExpansion1People.map((entry) => [entry.id, entry.portrait]),
  );
