import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-01";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({
  label,
  url,
  kind,
  checkedAt,
  supports,
});

const sources = {
  pkuNlp: source("PKU CS · Natural Language Processing advisers", "https://cs.pku.edu.cn/internationalization/Advisor/Natural_Language_Processing.htm", "official", "PKU NLP research-area faculty roster, including Baobao Chang, Houfeng Wang, Xu Sun, Zhifang Sui, Yansong Feng and named colleagues"),
  defuZhaoyi: source("Zhaoyi Li · homepage", "https://zhaoyi-li21.github.io/", "profile", "Current USTC PhD study co-supervised by Defu Lian"),
  defuZhihao: source("Zhihao Zhu · homepage", "https://zzh9568.github.io/", "profile", "USTC doctoral training under Defu Lian"),
  defuChenwang: source("Chenwang Wu · homepage", "https://daftstone.github.io/", "profile", "USTC doctoral training under Defu Lian"),
  bitCs: source("BIT School of Computer Science · faculty", "https://cs.bit.edu.cn/szdw/jsml/index.htm", "official", "School faculty roster containing Huaping Zhang and the named current unit colleagues"),
  ipalLim: source("IPAL · Joo Hwee Lim personal page", "https://ipal.cnrs.fr/joo-hwee-lim-personal-page/", "profile", "IPAL role and explicitly named collaborators at IPAL"),
  njuNlp: source("Nanjing University NLP Group · people", "https://nlp.nju.edu.cn/people.html", "official", "Current NJU NLP faculty and student roster"),
  thuAutomation: source("Tsinghua Automation · doctoral adviser roster", "https://yzbm.tsinghua.edu.cn/publish/s03/s0303/detail/15ea7b31-0aa5-4819-a38d-238dccac4fc0?yxsdm=025", "official", "Industrial Intelligence and Systems adviser team including Shiji Song and Biqing Huang"),
  boxinThesis: source("University of Tokyo repository · Boxin Shi dissertation record", "https://repository.dl.itc.u-tokyo.ac.jp/records/6455", "thesis", "Doctoral dissertation record and review identifying Katsushi Ikeuchi as supervisor"),
  ikeuchiTokyo: source("University of Tokyo IIS · emeritus faculty", "https://www.iis.u-tokyo.ac.jp/en/research/emeritus/", "official", "Katsushi Ikeuchi emeritus appointment"),
  ikeuchiHome: source("Katsushi Ikeuchi · University of Tokyo homepage", "https://www.cvl.iis.u-tokyo.ac.jp/~ki/", "profile", "Academic career, research fields, laboratory leadership and doctoral supervision record"),
  openFiesta: source("Tsinghua Open FIESTA · faculty", "https://openfiesta.sigs.tsinghua.edu.cn/cn/faculty/3", "official", "Open FIESTA faculty team including Yujiu Yang and named program colleagues"),
  openFiestaStudent: source("Tsinghua Open FIESTA · student news", "https://openfiesta.sigs.tsinghua.edu.cn/cn/news/detail/41", "official", "Yang Cheng identified as a student under Yujiu Yang"),
  hitAi: source("HIT School of Artificial Intelligence · faculty and leadership", "https://sai.hit.edu.cn/zrjs/list.htm", "official", "Current AI-school faculty team containing Junjun Jiang and named colleagues"),
  yizhouStudents: source("PKU CFCS · graduate students", "https://cfcs.pku.edu.cn/people/graduate_students/", "official", "Graduate-student roster explicitly mapping named students to Yizhou Wang"),
  mediaBrain: source("SJTU MediaBrain · members", "https://mediabrain.sjtu.edu.cn/members/", "official", "Current doctoral-student roster in Yanfeng Wang's MediaBrain group"),
  thuGgc: source("Tsinghua Graphics and Geometric Computing · people", "https://cg.cs.tsinghua.edu.cn/people_main.htm", "official", "Current faculty, postdoctoral and doctoral-member roster in the research group led by Shimin Hu"),
  tongLu: source("Nanjing University · Tong Lu profile", "https://cs.nju.edu.cn/58/01/c2639a153601/page.htm", "official", "Named doctoral students and research-group information for Tong Lu"),
  thuPi: source("Tsinghua PI Lab · people", "https://pi.cs.tsinghua.edu.cn/lab/people/", "official", "Current PI Lab research team containing Junliang Xing and named members"),
  yiwuPku: source("PKU School of Intelligence Science and Technology · Yiwu Zhong", "https://www.cis.pku.edu.cn/info/1362/3348.htm", "official", "Current appointment, UW–Madison PhD, CUHK postdoc and research directions"),
  yiwuThesis: source("UW–Madison dissertation · Learning Visual Knowledge from Natural Language Supervision", "https://asset.library.wisc.edu/1711.dl/NDW2GRIYP7CZ68Y/R/file-e1c7b.pdf", "thesis", "2023 dissertation explicitly identifying Yin Li as adviser"),
  leap: source("Tsinghua LEAP Lab · members", "https://www.leaplab.ai/members", "profile", "Current doctoral-student roster for Gao Huang's laboratory"),
  dmal: source("NTU Data Management and Analytics Lab · people", "https://www.ntu.edu.sg/dmal/about-us/our-people", "official", "DMAL research leads and faculty team including Aixin Sun"),
  ssi: source("NUS Smart Systems Institute", "https://ssi.nus.edu.sg/", "official", "David Hsu's director role and the institute principal-investigator team"),
  debinCv: source("Debin Gao · SMU CV", "https://computing.smu.edu.sg/sites/scis.smu.edu.sg/files/2025-02/dbgao-CV.pdf", "cv", "Completed doctoral dissertations supervised by Debin Gao"),
  cityuMerc: source("CityU Multimedia Software Engineering Research Centre · people", "https://www.cityu.edu.hk/merc/people.aspx", "official", "MERC membership and student roster including Shiqi Wang"),
  thunlp: source("Tsinghua NLP Lab · team", "https://nlp.csai.tsinghua.edu.cn/", "official", "THUNLP faculty and student team including Maosong Sun, Zhiyuan Liu and Yang Liu"),
  zhiyuanHome: source("Zhiyuan Liu · Tsinghua homepage", "https://lzy.thunlp.org/", "profile", "Current and former student roster, with co-supervision annotations"),
  xiangnanKexin: source("Kexin Huang · homepage", "https://kexinhuang02.github.io/", "profile", "Current doctoral study supervised by Xiangnan He and Xiang Wang"),
  xiangnanJiaju: source("Jiaju Chen · homepage", "https://jiaju-chen.github.io/", "profile", "Current doctoral study under Xiangnan He"),
  xiangnanYang: source("Yang Zhang · homepage", "https://zyang1580.github.io/", "profile", "USTC PhD training supervised by Xiangnan He"),
  sjtuAiLeadership: source("SJTU School of Artificial Intelligence · leadership", "https://soai.sjtu.edu.cn/cn/article/xyld", "official", "Current school leadership team including Cewu Lu and named colleagues"),
  pkuMipl: source("PKU Machine Intelligence and Perception Lab · people", "https://www.mipl.pku.edu.cn/people/", "official", "Current MIPL faculty and researcher team including Chao Zhang"),
  liweiPku: source("Peking University Education Foundation · Liwei Wang group", "https://www.pkuef.org/pdf/cbzl/2018/20180309090354798.pdf", "official", "Named students in Liwei Wang's research group"),
  fudanIipl: source("Fudan IIPL · people", "https://iipl.fudan.edu.cn/", "official", "Current IIPL faculty and student team including Xiangyang Xue and Zuxuan Wu"),
  sysuBdl: source("SYSU Big Data and Distributed Computing Lab · team", "https://bdl.sysu.edu.cn/people", "official", "Current research-group roster for Zibin Zheng"),
  chaoQian: source("Chao Qian · LAMDA homepage", "https://www.lamda.nju.edu.cn/qianc/", "profile", "Current postdoctoral researchers and doctoral students supervised by Chao Qian"),
  xlance: source("SJTU X-LANCE Lab · members", "https://x-lance.sjtu.edu.cn/members.html", "profile", "Current X-LANCE faculty and research-member roster led by Kai Yu"),
  hitScir: source("HIT SCIR · team", "https://ir.hit.edu.cn/19590/list.htm", "official", "Current institute leadership and faculty team including Ting Liu"),
  thuIr: source("Tsinghua Information Retrieval Group", "http://www.thuir.org/", "profile", "Current information-retrieval research team led by Shaoping Ma"),
  gaoWenStudents: source("Peng Cheng Laboratory JDL · alumni", "https://www.jdl.ac.cn/rencai/taolitianxia", "official", "Named doctoral students trained by Gao Wen, with graduation years and destinations"),
  boAnCv: source("Bo An · NTU CV", "https://personal.ntu.edu.sg/boan/CV-BOAN.pdf", "cv", "Current and former doctoral students supervised by Bo An"),
  aiminEcnu: source("ECNU faculty profile · Aimin Zhou", "https://faculty.ecnu.edu.cn/_s16/zam/main.psp", "official", "Current role, research program and named students in the official teaching-and-awards record"),
  minyenResearch: source("Min-Yen Kan · NUS research group", "https://www.comp.nus.edu.sg/~kanmy/research/", "profile", "Current doctoral-student roster"),
  coai: source("Tsinghua CoAI · team", "https://coai.cs.tsinghua.edu.cn/team", "official", "Current doctoral-student and research-team roster led by Minlie Huang"),
};

type RosterRow = readonly [teacherId: string, slug: string, name: string, role: string, rosterSource: Source];
const rosterRows: RosterRow[] = [
  ["baobao-chang", "sujian-li", "Sujian Li", "PKU NLP research-area faculty", sources.pkuNlp],
  ["baobao-chang", "yunfang-wu", "Yunfang Wu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["baobao-chang", "yang-liu", "Yang Liu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["defu-lian-ustc", "zhaoyi-li", "Zhaoyi Li", "PhD student · co-supervised", sources.defuZhaoyi],
  ["defu-lian-ustc", "zhihao-zhu", "Zhihao Zhu", "Former PhD student", sources.defuZhihao],
  ["defu-lian-ustc", "chenwang-wu", "Chenwang Wu", "Former PhD student", sources.defuChenwang],
  ["houfeng-wang", "sujian-li", "Sujian Li", "PKU NLP research-area faculty", sources.pkuNlp],
  ["houfeng-wang", "yunfang-wu", "Yunfang Wu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["houfeng-wang", "yang-liu", "Yang Liu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["huaping-zhang-bit", "huang-hua", "Hua Huang", "BIT Computer Science faculty colleague", sources.bitCs],
  ["huaping-zhang-bit", "wang-guoren", "Guoren Wang", "BIT Computer Science faculty colleague", sources.bitCs],
  ["huaping-zhang-bit", "li-dongni", "Dongni Li", "BIT Computer Science faculty colleague", sources.bitCs],
  ["joo-hwee-lim", "christophe-jouffrais", "Christophe Jouffrais", "IPAL collaborator", sources.ipalLim],
  ["joo-hwee-lim", "wei-tsang-ooi", "Wei Tsang Ooi", "IPAL collaborator", sources.ipalLim],
  ["xinyu-dai", "jiajun-chen", "Jiajun Chen", "NJU NLP faculty", sources.njuNlp],
  ["xinyu-dai", "shujian-huang", "Shujian Huang", "NJU NLP faculty", sources.njuNlp],
  ["xinyu-dai", "jianbing-zhang", "Jianbing Zhang", "NJU NLP faculty", sources.njuNlp],
  ["xu-sun-pku", "sujian-li", "Sujian Li", "PKU NLP research-area faculty", sources.pkuNlp],
  ["xu-sun-pku", "yunfang-wu", "Yunfang Wu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["xu-sun-pku", "yang-liu", "Yang Liu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["zhifang-sui", "sujian-li", "Sujian Li", "PKU NLP research-area faculty", sources.pkuNlp],
  ["zhifang-sui", "yunfang-wu", "Yunfang Wu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["zhifang-sui", "yang-liu", "Yang Liu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["shiji-song-award", "min-liu", "Min Liu", "Industrial Intelligence and Systems adviser team", sources.thuAutomation],
  ["shiji-song-award", "wenhui-fan", "Wenhui Fan", "Industrial Intelligence and Systems adviser team", sources.thuAutomation],
  ["shiji-song-award", "heming-zhang", "Heming Zhang", "Industrial Intelligence and Systems adviser team", sources.thuAutomation],
  ["yujiu-yang-tsinghua-award", "yang-cheng", "Yang Cheng", "Student under Yujiu Yang", sources.openFiestaStudent],
  ["yujiu-yang-tsinghua-award", "weijian-chen", "Weijian Chen", "Open FIESTA faculty team", sources.openFiesta],
  ["yujiu-yang-tsinghua-award", "xiu-li", "Xiu Li", "Open FIESTA faculty team", sources.openFiesta],
  ["junjun-jiang-hit", "weinan-zhang", "Weinan Zhang", "HIT AI-school faculty team", sources.hitAi],
  ["junjun-jiang-hit", "xiaocheng-feng", "Xiaocheng Feng", "HIT AI-school faculty team", sources.hitAi],
  ["junjun-jiang-hit", "shaohui-liu", "Shaohui Liu", "HIT AI-school faculty team", sources.hitAi],
  ["yizhou-wang-pku", "jinlu-zhang", "Jinlu Zhang", "PhD student", sources.yizhouStudents],
  ["yizhou-wang-pku", "zijian-wang", "Zijian Wang", "PhD student", sources.yizhouStudents],
  ["yizhou-wang-pku", "rujie-wu", "Rujie Wu", "PhD student", sources.yizhouStudents],
  ["yanfeng-wang-sjtu", "fei-ye", "Fei Ye", "PhD student · MediaBrain", sources.mediaBrain],
  ["yanfeng-wang-sjtu", "peisen-zhao", "Peisen Zhao", "PhD student · MediaBrain", sources.mediaBrain],
  ["yanfeng-wang-sjtu", "maosen-li", "Maosen Li", "PhD student · MediaBrain", sources.mediaBrain],
  ["hu-shimin-thu", "haoxiang-chen", "Haoxiang Chen", "PhD student · GGC", sources.thuGgc],
  ["hu-shimin-thu", "menghao-guo", "Menghao Guo", "PhD student · GGC", sources.thuGgc],
  ["hu-shimin-thu", "hanchao-liu", "Hanchao Liu", "PhD student · GGC", sources.thuGgc],
  ["tong-lu-nju", "zhiqi-li", "Zhiqi Li", "Doctoral student", sources.tongLu],
  ["junliang-xing-thu", "jue-wang", "Jue Wang", "PI Lab research-team member", sources.thuPi],
  ["junliang-xing-thu", "yonggang-peng", "Yonggang Peng", "PI Lab research-team member", sources.thuPi],
  ["junliang-xing-thu", "qi-xie", "Qi Xie", "PI Lab research-team member", sources.thuPi],
  ["gao-huang-tsinghua-award", "haojun-jiang", "Haojun Jiang", "PhD student · LEAP", sources.leap],
  ["gao-huang-tsinghua-award", "rui-lu", "Rui Lu", "PhD student · LEAP", sources.leap],
  ["gao-huang-tsinghua-award", "zanlin-ni", "Zanlin Ni", "PhD student · LEAP", sources.leap],
  ["aixin-sun", "sourav-bhowmick", "Sourav S. Bhowmick", "DMAL research lead", sources.dmal],
  ["aixin-sun", "hui-siu-cheung", "Hui Siu Cheung", "DMAL faculty", sources.dmal],
  ["aixin-sun", "cong-gao", "Cong Gao", "DMAL faculty", sources.dmal],
  ["david-hsu-nus", "harold-soh", "Harold Soh", "SSI principal investigator", sources.ssi],
  ["david-hsu-nus", "suranga-nanayakkara", "Suranga Nanayakkara", "SSI principal investigator", sources.ssi],
  ["david-hsu-nus", "clement-zheng", "Clement Zheng", "SSI principal investigator", sources.ssi],
  ["debin-gao-smu", "yan-lin", "Yan Lin", "Former PhD student", sources.debinCv],
  ["debin-gao-smu", "xiaoxiao-tang", "Xiaoxiao Tang", "Former PhD student", sources.debinCv],
  ["debin-gao-smu", "daoyuan-wu", "Daoyuan Wu", "Former PhD student", sources.debinCv],
  ["shiqi-wang-cityu", "jianping-wang", "Jianping Wang", "MERC director", sources.cityuMerc],
  ["shiqi-wang-cityu", "antoni-chan", "Antoni Chan", "MERC deputy director", sources.cityuMerc],
  ["shiqi-wang-cityu", "junhui-hou", "Junhui Hou", "MERC member", sources.cityuMerc],
  ["yang-liu-thu", "zhiyuan-liu", "Zhiyuan Liu", "THUNLP faculty team", sources.thunlp],
  ["yang-liu-thu", "maosong-sun", "Maosong Sun", "THUNLP faculty team", sources.thunlp],
  ["yang-liu-thu", "minlie-huang", "Minlie Huang", "THUNLP faculty team", sources.thunlp],
  ["yansong-feng", "sujian-li", "Sujian Li", "PKU NLP research-area faculty", sources.pkuNlp],
  ["yansong-feng", "yunfang-wu", "Yunfang Wu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["yansong-feng", "yang-liu", "Yang Liu", "PKU NLP research-area faculty", sources.pkuNlp],
  ["xiangnan-he-ustc-award", "kexin-huang", "Kexin Huang", "PhD student · co-supervised", sources.xiangnanKexin],
  ["xiangnan-he-ustc-award", "jiaju-chen", "Jiaju Chen", "PhD student", sources.xiangnanJiaju],
  ["xiangnan-he-ustc-award", "yang-zhang", "Yang Zhang", "Former PhD student", sources.xiangnanYang],
  ["cewu-lu-sjtu", "yanfeng-wang", "Yanfeng Wang", "SJTU AI-school leadership team", sources.sjtuAiLeadership],
  ["cewu-lu-sjtu", "ya-zhang", "Ya Zhang", "SJTU AI-school leadership team", sources.sjtuAiLeadership],
  ["cewu-lu-sjtu", "junchi-yan", "Junchi Yan", "SJTU AI-school leadership team", sources.sjtuAiLeadership],
  ["chao-zhang-pku-lineage", "song-chun-zhu", "Song-Chun Zhu", "MIPL research-unit faculty", sources.pkuMipl],
  ["chao-zhang-pku-lineage", "yizhou-wang", "Yizhou Wang", "MIPL research-unit faculty", sources.pkuMipl],
  ["liwei-wang-pku-award", "dong-wang", "Dong Wang", "Research-group student", sources.liweiPku],
  ["liwei-wang-pku-award", "zhiqiang-hu", "Zhiqiang Hu", "Research-group student", sources.liweiPku],
  ["liwei-wang-pku-award", "tiange-luo", "Tiange Luo", "Research-group student", sources.liweiPku],
  ["xiangyang-xue-fdu", "zuxuan-wu", "Zuxuan Wu", "IIPL faculty member", sources.fudanIipl],
  ["zibin-zheng-sysu", "xiao-xi", "Xiao Xi", "BDL research-group member", sources.sysuBdl],
  ["zibin-zheng-sysu", "hongning-li", "Hongning Li", "BDL research-group member", sources.sysuBdl],
  ["zibin-zheng-sysu", "huan-zhou", "Huan Zhou", "BDL research-group member", sources.sysuBdl],
  ["chao-qian-lamda", "zeqiong-lv", "Zeqiong Lv", "Postdoctoral researcher", sources.chaoQian],
  ["chao-qian-lamda", "ke-xue", "Ke Xue", "Postdoctoral researcher", sources.chaoQian],
  ["chao-qian-lamda", "chengrui-gao", "Cheng-Rui Gao", "PhD student", sources.chaoQian],
  ["biqing-huang-thu", "shiji-song", "Shiji Song", "Industrial Intelligence and Systems adviser team", sources.thuAutomation],
  ["biqing-huang-thu", "min-liu", "Min Liu", "Industrial Intelligence and Systems adviser team", sources.thuAutomation],
  ["biqing-huang-thu", "wenhui-fan", "Wenhui Fan", "Industrial Intelligence and Systems adviser team", sources.thuAutomation],
  ["kai-yu-sjtu", "lu-chen", "Lu Chen", "X-LANCE research-team member", sources.xlance],
  ["kai-yu-sjtu", "su-zhu", "Su Zhu", "X-LANCE research-team member", sources.xlance],
  ["kai-yu-sjtu", "yanmin-qian", "Yanmin Qian", "X-LANCE faculty member", sources.xlance],
  ["ting-liu-hit", "qin-bing", "Qin Bing", "SCIR faculty team", sources.hitScir],
  ["ting-liu-hit", "wanxiang-che", "Wanxiang Che", "SCIR faculty team", sources.hitScir],
  ["zuxuan-wu-fdu", "xiangyang-xue", "Xiangyang Xue", "IIPL faculty team", sources.fudanIipl],
  ["zuxuan-wu-fdu", "yi-yang", "Yi Yang", "IIPL research-team member", sources.fudanIipl],
  ["zuxuan-wu-fdu", "yu-gang-jiang", "Yu-Gang Jiang", "IIPL faculty team", sources.fudanIipl],
  ["shaoping-ma-thu", "yiqun-liu", "Yiqun Liu", "THUIR faculty team", sources.thuIr],
  ["shaoping-ma-thu", "min-zhang", "Min Zhang", "THUIR faculty team", sources.thuIr],
  ["gao-wen-pku", "falei-luo", "Falei Luo", "Former PhD student", sources.gaoWenStudents],
  ["bo-an", "jianing-ju", "Jianing Ju", "PhD student", sources.boAnCv],
  ["bo-an", "shengming-wang", "Shengming Wang", "PhD student", sources.boAnCv],
  ["bo-an", "fuxiang-zhang", "Fuxiang Zhang", "PhD student", sources.boAnCv],
  ["aimin-zhou-ecnu", "yupeng-wu", "Yupeng Wu", "Student named in official supervision record", sources.aiminEcnu],
  ["aimin-zhou-ecnu", "siyu-gao", "Siyu Gao", "Student named in official supervision record", sources.aiminEcnu],
  ["aimin-zhou-ecnu", "xiangfeng-wang", "Xiangfeng Wang", "Shanghai Institute of AI for Education team", sources.aiminEcnu],
  ["maosong-sun", "zhiyuan-liu", "Zhiyuan Liu", "THUNLP faculty team", sources.thunlp],
  ["maosong-sun", "yang-liu", "Yang Liu", "THUNLP faculty team", sources.thunlp],
  ["min-yen-kan", "yajing-yang", "Yajing Yang", "PhD student", sources.minyenResearch],
  ["min-yen-kan", "yisong-miao", "Yisong Miao", "PhD student", sources.minyenResearch],
  ["zhiyuan-liu", "xu-han", "Xu Han", "PhD student", sources.zhiyuanHome],
  ["zhiyuan-liu", "yuan-yao", "Yuan Yao", "PhD student", sources.zhiyuanHome],
  ["minlie-huang", "daoyi-li", "Daoyi Li", "PhD student · CoAI", sources.coai],
];

export const influenceQueueAsiaGroupMembers: GroupMember[] = rosterRows.map(([teacherId, slug, name, role, rosterSource]) => ({
  id: `influence-asia-${teacherId}-${slug}`,
  teacherId,
  name,
  role,
  source: rosterSource,
}));

const enhancementSourcesByPerson: Record<string, Source[]> = {};
for (const member of influenceQueueAsiaGroupMembers) {
  const existing = enhancementSourcesByPerson[member.teacherId] ?? [];
  if (!existing.some((item) => item.url === member.source.url)) existing.push(member.source);
  enhancementSourcesByPerson[member.teacherId] = existing;
}

export const influenceQueueAsiaPersonEnhancements: Record<string, Partial<Person>> = Object.fromEntries(
  Object.entries(enhancementSourcesByPerson).map(([id, rosterSources]) => [id, {
    sources: rosterSources,
    facts: [{
      label: "团队与培养体系",
      value: "一手页面公开列出该人物所在研究组、研究单元、具名学生或团队成员；关系按页面明示角色记录，不从普通论文合著推断。",
      source: rosterSources[0],
    }],
    lastVerifiedAt: checkedAt,
  }]),
);

export const influenceQueueAsiaPeople: Person[] = [
  {
    id: "katsushi-ikeuchi-historical",
    name: "Katsushi Ikeuchi",
    chinese: "池内克史",
    role: "Professor Emeritus · University of Tokyo",
    institution: "External",
    actualInstitution: "University of Tokyo",
    region: "Mainland China",
    area: "Computer Vision · Robotics · 3D Sensing",
    tags: ["计算机视觉", "机器人", "三维感知", "博士导师谱系"],
    summary: "东京大学计算机视觉与机器人资深学者；东京大学博士论文记录明确连接其与施柏鑫的博士指导关系。",
    facts: [
      { label: "当前任职", value: "University of Tokyo Institute of Industrial Science Professor Emeritus。", source: sources.ikeuchiTokyo },
      { label: "研究主线", value: "计算机视觉、机器人、三维感知与文化遗产数字化。", source: sources.ikeuchiHome },
      { label: "教育与学术训练", value: "本人一手主页公开其学术经历、研究方向与长期实验室领导记录。", source: sources.ikeuchiHome },
      { label: "图谱关系", value: "施柏鑫东京大学博士论文材料将 Katsushi Ikeuchi 列为指导教师。", source: sources.boxinThesis },
    ],
    stage: "historical",
    category: "historical",
    status: "师承上游 · Tokyo computer vision",
    sources: [sources.ikeuchiTokyo, sources.ikeuchiHome, sources.boxinThesis],
    x: 1840,
    y: 340,
    lastVerifiedAt: checkedAt,
    introducedAt: checkedAt,
  },
];

export const influenceQueueAsiaRelationships: Relationship[] = [
  {
    id: "influence-asia-ikeuchi-boxin-shi",
    from: "katsushi-ikeuchi-historical",
    to: "boxin-shi-pku",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "东京大学博士论文记录及审查材料明确将 Katsushi Ikeuchi 列为施柏鑫的博士指导教师。",
    evidenceObject: "University of Tokyo doctoral dissertation record",
    source: sources.boxinThesis,
    verified: true,
  },
];

export const influenceQueueAsiaPlacements: StudentPlacement[] = [];
export const influenceQueueAsiaPortraits: Record<string, NonNullable<Person["portrait"]>> = {};

export const influenceQueueAsiaDeferred = [
  {
    id: "yiwu-zhong-pku",
    reason: "UW–Madison 博士论文已明确 Yin Li 为导师；待 Yin Li 的完整当前 PI 节点与可核验头像资产完成后再接入，避免悬空边。",
    sources: [sources.yiwuPku, sources.yiwuThesis],
  },
] as const;

export const enhancements = influenceQueueAsiaPersonEnhancements;
export const people = influenceQueueAsiaPeople;
export const relationships = influenceQueueAsiaRelationships;
export const groupMembers = influenceQueueAsiaGroupMembers;
export const placements = influenceQueueAsiaPlacements;
export const portraitMap = influenceQueueAsiaPortraits;
