import type { Person } from "./data";

/** Verified portraits for the Hong Kong and Singapore AI/CV expansion roster. */
export const hkSgMissingPortraits: Record<string, NonNullable<Person["portrait"]>> = {
  "mohan-kankanhalli": { src: "portraits/hk-sg-missing/mohan-kankanhalli.jpg", alt: "Portrait of Mohan Kankanhalli", source: { label: "Portrait source · NUS faculty profile", url: "https://www.comp.nus.edu.sg/cs/people/mohan/", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Mohan Kankanhalli" } },
  "mike-zheng-shou": { src: "portraits/hk-sg-missing/mike-zheng-shou.jpg", alt: "Portrait of Mike Zheng Shou", source: { label: "Portrait source · NUS faculty profile", url: "https://www.comp.nus.edu.sg/cs/people/mikeshou/", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Mike Zheng Shou" } },
  "chen-change-loy": { src: "portraits/hk-sg-missing/chen-change-loy.jpg", alt: "Portrait of Chen Change Loy", source: { label: "Portrait source · NTU S-Lab people", url: "https://www.ntu.edu.sg/s-lab/our-people", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Chen Change Loy" } },
  "ziwei-liu-ntu": { src: "portraits/hk-sg-missing/ziwei-liu-ntu.jpg", alt: "Portrait of Ziwei Liu", source: { label: "Portrait source · NTU S-Lab people", url: "https://www.ntu.edu.sg/s-lab/our-people", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Ziwei Liu" } },
  "ngai-man-cheung": { src: "portraits/hk-sg-missing/ngai-man-cheung.jpg", alt: "Portrait of Ngai-Man Cheung", source: { label: "Portrait source · SUTD faculty profile", url: "https://www.sutd.edu.sg/profile/cheung-ngai-man", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Ngai-Man Cheung" } },
  "guansong-pang": { src: "portraits/hk-sg-missing/guansong-pang.jpg", alt: "Portrait of Guansong Pang", source: { label: "Portrait source · SMU faculty profile", url: "https://computing.smu.edu.sg/faculty/profile/6271/guansong-pang", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Guansong Pang" } },
  "joo-hwee-lim": { src: "portraits/hk-sg-missing/joo-hwee-lim.jpg", alt: "Portrait of Joo-Hwee Lim", source: { label: "Portrait source · A*STAR researcher profile", url: "https://research.a-star.edu.sg/researcher/joo-hwee-lim/", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Joo-Hwee Lim" } },
  "ping-luo-hku": { src: "portraits/hk-sg-missing/ping-luo-hku.jpg", alt: "Portrait of Ping Luo", source: { label: "Portrait source · HKU IDS faculty profile", url: "https://datascience.hku.hk/people/ping-luo/", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Ping Luo" } },
  "yizhou-yu-hku": { src: "portraits/hk-sg-missing/yizhou-yu-hku.jpg", alt: "Portrait of Yizhou Yu", source: { label: "Portrait source · Yizhou Yu HKU homepage", url: "https://i.cs.hku.hk/~yzyu/index.html", kind: "profile", checkedAt: "2026-08-29", supports: "Portrait identity for Yizhou Yu" } },
  "qifeng-chen-hkust": { src: "portraits/hk-sg-missing/qifeng-chen-hkust.jpg", alt: "Portrait of Qifeng Chen", source: { label: "Portrait source · HKUST CSE profile", url: "https://cse.hkust.edu.hk/admin/people/faculty/profile/cqf", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Qifeng Chen" } },
  "xiaogang-wang-cuhk": { src: "portraits/hk-sg-missing/xiaogang-wang-cuhk.jpg", alt: "Portrait of Xiaogang Wang", source: { label: "Portrait source · CUHK research portal", url: "https://research.cuhk.edu.hk/en/persons/xiaogang-wang/", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Xiaogang Wang" } },
  "dahua-lin-cuhk": { src: "portraits/hk-sg-missing/dahua-lin-cuhk.jpg", alt: "Portrait of Dahua Lin", source: { label: "Portrait source · CUHK IE faculty profile", url: "https://www.ie.cuhk.edu.hk/faculty/lin-dahua/", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Dahua Lin" } },
  "shiqi-wang-cityu": { src: "portraits/hk-sg-missing/shiqi-wang-cityu.jpg", alt: "Portrait of Shiqi Wang", source: { label: "Portrait source · Shiqi Wang CityU homepage", url: "https://www.cs.cityu.edu.hk/~shiqwang/", kind: "profile", checkedAt: "2026-08-29", supports: "Portrait identity for Shiqi Wang" } },
  "lei-zhang-polyu": { src: "portraits/hk-sg-missing/lei-zhang-polyu.jpg", alt: "Portrait of Lei Zhang", source: { label: "Portrait source · Lei Zhang PolyU homepage", url: "https://web.comp.polyu.edu.hk/cslzhang/", kind: "profile", checkedAt: "2026-08-29", supports: "Portrait identity for Lei Zhang" } },
  "jie-chen-hkbu": { src: "portraits/hk-sg-missing/jie-chen-hkbu.jpg", alt: "Portrait of Jie Chen", source: { label: "Portrait source · HKBU faculty profile", url: "https://www.comp.hkbu.edu.hk/v1/?id=chenjie&page=profile", kind: "official", checkedAt: "2026-08-29", supports: "Portrait identity for Jie Chen" } },
};
