import type { Person } from "./data";

type Portrait = NonNullable<Person["portrait"]>;

const checkedAt = "2026-09-02";

function portrait(id: string, name: string, url: string): Portrait {
  return {
    src: "portraits/current-pi-backfill-2026/" + id + ".jpg",
    alt: "Portrait of " + name,
    source: {
      label: "Official or personal profile portrait for " + name,
      url,
      kind: "profile",
      checkedAt,
      supports: "Portrait identity for " + name,
    },
  };
}

/**
 * Manually reviewed portrait backfill for every current PI that lacked a
 * reliable local portrait on 2026-09-02. Source pages were checked one by one;
 * unrelated sidebar images, logos, group photos, and placeholders were rejected.
 */
export const currentPiBackfill2026Portraits: Record<string, Portrait> = {
  "abhinav-gupta-us": portrait("abhinav-gupta-us", "Abhinav Gupta", "https://vision.cs.cmu.edu/people.html"),
  "achuta-kadambi-us": portrait("achuta-kadambi-us", "Achuta Kadambi", "https://www.ee.ucla.edu/achuta-kadambi/"),
  "alan-yuille-us": portrait("alan-yuille-us", "Alan Yuille", "https://www.cs.jhu.edu/faculty/alan-yuille/"),
  "alex-aiken-lineage": portrait("alex-aiken-lineage", "Alex Aiken", "https://profiles.stanford.edu/alex-aiken"),
  "alexei-efros-us": portrait("alexei-efros-us", "Alexei A. Efros", "https://vcresearch.berkeley.edu/faculty/alexei-efros"),
  "ali-farhadi-us": portrait("ali-farhadi-us", "Ali Farhadi", "https://www.cs.washington.edu/people/faculty/ali-farhadi/"),
  "andreas-geiger-eu": portrait("andreas-geiger-eu", "Andreas Geiger", "https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/forschung/"),
  "andrew-zisserman-eu": portrait("andrew-zisserman-eu", "Andrew Zisserman", "https://eng.ox.ac.uk/people/andrew-zisserman"),
  "angjoo-kanazawa-us": portrait("angjoo-kanazawa-us", "Angjoo Kanazawa", "https://news.berkeley.edu/2020/11/30/meet-our-new-faculty-angjoo-kanazawa-engineering/"),
  "anna-choromanska-foundational": portrait("anna-choromanska-foundational", "Anna Choromanska", "https://engineering.nyu.edu/faculty/anna-choromanska?page=1"),
  "antoine-bosselut-eu": portrait("antoine-bosselut-eu", "Antoine Bosselut", "https://people.epfl.ch/antoine.bosselut?lang=en"),
  "armando-solar-lezama-lineage": portrait("armando-solar-lezama-lineage", "Armando Solar-Lezama", "https://www.csail.mit.edu/person/armando-solar-lezama"),
  "atlas-wang-us": portrait("atlas-wang-us", "Atlas Wang", "https://www.cs.utexas.edu/people/faculty-researchers/atlas-wang"),
  "bharath-hariharan-us": portrait("bharath-hariharan-us", "Bharath Hariharan", "https://www.cs.cornell.edu/people/bharath-hariharan"),
  "bo-zhang-thu-historical": portrait("bo-zhang-thu-historical", "张钹", "https://www.cs.tsinghua.edu.cn/info/1121/3552.htm"),
  "bolei-zhou-us": portrait("bolei-zhou-us", "Bolei Zhou", "https://samueli.ucla.edu/people/bolei-zhou/"),
  "carl-rasmussen-lineage": portrait("carl-rasmussen-lineage", "Carl Edward Rasmussen", "https://www.eng.cam.ac.uk/profiles/cer54"),
  "carl-vondrick-us": portrait("carl-vondrick-us", "Carl Vondrick", "https://www.cs.columbia.edu/~vondrick/"),
  "chang-xu-lineage": portrait("chang-xu-lineage", "Chang Xu", "https://dsi.sydney.edu.au/wps-members/dr-chang-xu/"),
  "chao-zhang-pku-lineage": portrait("chao-zhang-pku-lineage", "张超", "https://eecs.pku.edu.cn/xxkxjsxy/szdw1/zzjs1/Z/2.htm"),
  "christos-papadimitriou-lineage": portrait("christos-papadimitriou-lineage", "Christos Papadimitriou", "https://simons.berkeley.edu/people/christos-papadimitriou"),
  "daniel-cremers-eu": portrait("daniel-cremers-eu", "Daniel Cremers", "https://www.professoren.tum.de/cremers-daniel"),
  "david-blei-foundational": portrait("david-blei-foundational", "David Blei", "https://www.cs.columbia.edu/~blei/"),
  "david-gifford-lineage": portrait("david-gifford-lineage", "David Gifford", "https://www.eecs.mit.edu/people/david-gifford/"),
  "david-krueger-foundational": portrait("david-krueger-foundational", "David Krueger", "https://mila.quebec/en/directory/david-scott-krueger?page=0%2C1"),
  "derek-hoiem-us": portrait("derek-hoiem-us", "Derek Hoiem", "https://dhoiem.cs.illinois.edu/main.html"),
  "dieter-fox-us": portrait("dieter-fox-us", "Dieter Fox", "https://www.cs.washington.edu/people/faculty/dieter-fox/"),
  "dylan-hadfield-menell-foundational": portrait("dylan-hadfield-menell-foundational", "Dylan Hadfield-Menell", "https://www.csail.mit.edu/person/dylan-hadfield-menell"),
  "emine-yilmaz-lineage": portrait("emine-yilmaz-lineage", "Emine Yilmaz", "https://ucl-ellis.github.io/"),
  "emma-brunskill-foundational": portrait("emma-brunskill-foundational", "Emma Brunskill", "https://profiles.stanford.edu/emma-brunskill"),
  "fei-sha-lineage": portrait("fei-sha-lineage", "Fei Sha", "https://shalab.usc.edu/people/"),
  "fuli-feng-ustc": portrait("fuli-feng-ustc", "冯福利", "https://fulifeng.github.io/"),
  "gao-xiaoshan-amss": portrait("gao-xiaoshan-amss", "高小山", "https://people.ucas.edu.cn/~xgao"),
  "gerald-penn-lineage": portrait("gerald-penn-lineage", "Gerald Penn", "https://media.utoronto.ca/bluebook/gerald-penn/"),
  "graham-taylor-foundational": portrait("graham-taylor-foundational", "Graham W. Taylor", "https://www.uoguelph.ca/engineering/people/graham-w-taylor-phd-peng"),
  "helen-meng-lineage": portrait("helen-meng-lineage", "Helen Meng", "https://research.cuhk.edu.hk/en/persons/mei-ling-helen-meng/"),
  "james-hays-us": portrait("james-hays-us", "James Hays", "https://www.cc.gatech.edu/people/james-hays"),
  "jeff-schneider-lineage": portrait("jeff-schneider-lineage", "Jeff Schneider", "https://www.ri.cmu.edu/ri-faculty/jeff-schneider/"),
  "jesse-davis-eu": portrait("jesse-davis-eu", "Jesse Davis", "https://www.kuleuven.be/wieiswie/en/person/00071880"),
  "jia-deng-us": portrait("jia-deng-us", "Jia Deng", "https://www.cs.princeton.edu/people/profile/jiadeng"),
  "jim-glass-lineage": portrait("jim-glass-lineage", "Jim Glass", "https://www.csail.mit.edu/person/jim-glass"),
  "jitendra-malik-us": portrait("jitendra-malik-us", "Jitendra Malik", "https://vision.berkeley.edu/people/jitendra-malik-phd/"),
  "joshua-tenenbaum-lineage": portrait("joshua-tenenbaum-lineage", "Joshua B. Tenenbaum", "https://bcs.mit.edu/directory/joshua-b-tenenbaum"),
  "judith-degen-lineage": portrait("judith-degen-lineage", "Judith Degen", "https://profiles.stanford.edu/judith-degen"),
  "julian-mcauley-us": portrait("julian-mcauley-us", "Julian McAuley", "https://jacobs.ucsd.edu/people/profile/julian-mcauley"),
  "junbin-xiao-ustc": portrait("junbin-xiao-ustc", "肖俊斌", "https://doc-doc.github.io/cv/"),
  "karen-livescu-lineage": portrait("karen-livescu-lineage", "Karen Livescu", "https://www.ttic.edu/faculty/livescu/"),
  "kyros-kutulakos-lineage": portrait("kyros-kutulakos-lineage", "Kyros Kutulakos", "https://www.cs.utoronto.ca/~kyros/"),
  "leonidas-guibas-lineage": portrait("leonidas-guibas-lineage", "Leonidas Guibas", "https://engineering.stanford.edu/people/leonidas-guibas"),
  "lillian-lee-us": portrait("lillian-lee-us", "Lillian Lee", "https://nlp.cornell.edu/people/"),
  "louis-philippe-morency-us": portrait("louis-philippe-morency-us", "Louis-Philippe Morency", "https://www.lti.cs.cmu.edu/people/faculty/morency-louis-philippe.html"),
  "matei-zaharia-lineage": portrait("matei-zaharia-lineage", "Matei Zaharia", "https://dawn.cs.stanford.edu/people/matei-zaharia"),
  "meng-jiang-lineage": portrait("meng-jiang-lineage", "Meng Jiang", "https://liugangcode.github.io/"),
  "michael-jordan-eu": portrait("michael-jordan-eu", "Michael I. Jordan", "https://eecs.berkeley.edu/news/michael-jordan-explains-why-todays-ai-systems-arent-actually-intelligent/"),
  "noah-snavely-us": portrait("noah-snavely-us", "Noah Snavely", "https://www.cs.cornell.edu/people/noah-snavely"),
  "pascal-fua-eu": portrait("pascal-fua-eu", "Pascal Fua", "https://www.epfl.ch/labs/cvlab/people/"),
  "peter-dayan-eu": portrait("peter-dayan-eu", "Peter Dayan", "https://www.kyb.tuebingen.mpg.de/person/95844"),
  "pietro-perona-lineage": portrait("pietro-perona-lineage", "Pietro Perona", "https://www.eas.caltech.edu/people/perona"),
  "qingfu-zhang-lineage": portrait("qingfu-zhang-lineage", "Qingfu Zhang", "https://www.cs.cityu.edu.hk/en/people/academic-staff"),
  "rama-chellappa-us": portrait("rama-chellappa-us", "Rama Chellappa", "https://www.cs.jhu.edu/people/cs-affiliates/joint-and-secondary-faculty/"),
  "rob-fergus-us": portrait("rob-fergus-us", "Rob Fergus", "https://cs.nyu.edu/dynamic/people/faculty/area/Graphics%2C%20Vision%2C%20User%20Interfaces%2C%20and%20Games/?type=1"),
  "roger-levy-us": portrait("roger-levy-us", "Roger Levy", "https://www.mit.edu/~rplevy/"),
  "ryan-adams-us": portrait("ryan-adams-us", "Ryan P. Adams", "https://www.cs.princeton.edu/people/profile/rpa"),
  "saining-xie-us": portrait("saining-xie-us", "Saining Xie", "https://cs.nyu.edu/dynamic/people/faculty/type/21/?area=Machine+Learning"),
  "satinder-singh-us": portrait("satinder-singh-us", "Satinder Singh Baveja", "https://midas.umich.edu/directory/satinder-singh-baveja/"),
  "shih-fu-chang-lineage": portrait("shih-fu-chang-lineage", "Shih-Fu Chang", "https://cnec.columbia.edu/people/shih-fu-chang"),
  "shree-nayar-us": portrait("shree-nayar-us", "Shree K. Nayar", "https://www.cs.columbia.edu/cg/backup/people.html"),
  "siyu-tang-eu": portrait("siyu-tang-eu", "Siyu Tang", "https://ai.ethz.ch/about-us/people/faculty.html"),
  "stefano-soatto-lineage": portrait("stefano-soatto-lineage", "Stefano Soatto", "https://samueli.ucla.edu/people/stefano-soatto/"),
  "stuart-shieber-lineage": portrait("stuart-shieber-lineage", "Stuart Shieber", "https://seas.harvard.edu/person/stuart-shieber"),
  "svetlana-lazebnik-us": portrait("svetlana-lazebnik-us", "Svetlana Lazebnik", "https://slazebni.cs.illinois.edu/"),
  "takeo-kanade-historical": portrait("takeo-kanade-historical", "Takeo Kanade", "https://www.ri.cmu.edu/ri-faculty/takeo-kanade/"),
  "tao-xiang-lineage": portrait("tao-xiang-lineage", "Tao Xiang", "https://www.surrey.ac.uk/people/tao-xiang"),
  "tinne-tuytelaars-eu": portrait("tinne-tuytelaars-eu", "Tinne Tuytelaars", "https://www.esat.kuleuven.be/psi/TT/"),
  "tom-rainforth-lineage": portrait("tom-rainforth-lineage", "Tom Rainforth", "https://www.stats.ox.ac.uk/people/tom-rainforth"),
  "tommi-jaakkola-lineage": portrait("tommi-jaakkola-lineage", "Tommi Jaakkola", "https://stat.mit.edu/people/tommi-s-jaakkola/"),
  "trevor-darrell-us": portrait("trevor-darrell-us", "Trevor Darrell", "https://vcresearch.berkeley.edu/faculty/trevor-darrell"),
  "wenjie-wang-ustc": portrait("wenjie-wang-ustc", "王文杰", "https://faculty.ustc.edu.cn/wangwenjie/zh_CN/index.htm"),
  "william-freeman-lineage": portrait("william-freeman-lineage", "William T. Freeman", "https://billf.mit.edu/"),
  "william-wang-lineage": portrait("william-wang-lineage", "William Wang", "https://www.cs.ucsb.edu/people/faculty/william-wang"),
  "xiang-wang-ustc": portrait("xiang-wang-ustc", "王翔", "https://saids.ustc.edu.cn/2022/0321/c36362a549612/page.htm"),
  "xuezhe-ma-lineage": portrait("xuezhe-ma-lineage", "Xuezhe Ma", "https://www.isi.edu/directory/xuezhe-ma/"),
  "xun-yang-ustc": portrait("xun-yang-ustc", "杨勋", "https://sites.google.com/site/xunyangprofile/"),
  "yaochu-jin-lineage": portrait("yaochu-jin-lineage", "金耀初", "https://faculty.ecnu.edu.cn/_s16/zam/main.psp"),
  "yee-whye-teh-lineage": portrait("yee-whye-teh-lineage", "Yee Whye Teh", "https://www.stats.ox.ac.uk/people/yee-whye-teh"),
  "yi-wu-foundational": portrait("yi-wu-foundational", "吴翼", "https://iiis.tsinghua.edu.cn/rydw1/qzjs/wuyi.htm"),
  "zhi-quan-luo-lineage": portrait("zhi-quan-luo-lineage", "Zhi-Quan Tom Luo", "https://www.se.cuhk.edu.hk/people/honorary-appointments/prof-luo-zhi-quan-tom/"),
  "zhongzhi-shi-historical": portrait("zhongzhi-shi-historical", "史忠植", "https://people.ucas.ac.cn/~0012883"),
  "zoubin-ghahramani-eu": portrait("zoubin-ghahramani-eu", "Zoubin Ghahramani", "https://www.eng.cam.ac.uk/node/755"),
  "zsolt-kira-us": portrait("zsolt-kira-us", "Zsolt Kira", "https://www.cc.gatech.edu/people/zsolt-kira"),
};
