import type { Person } from "./data";

type Portrait = NonNullable<Person["portrait"]>;

const checkedAt = "2026-08-29";

function portrait(id: string, name: string, label: string, url: string): Portrait {
  return {
    src: `portraits/us/${id}.jpg`,
    alt: `${name} portrait`,
    source: {
      label,
      url,
      kind: label.includes("homepage") ? "profile" : "official",
      checkedAt,
      supports: `${name} portrait`,
    },
  };
}

export const usPortraits: Record<string, Portrait> = {
  "christopher-manning-us": portrait("christopher-manning-us", "Christopher Manning", "Stanford Bio-X faculty profile", "https://biox.stanford.edu/people/christopher-manning"),
  "dan-jurafsky-us": portrait("dan-jurafsky-us", "Dan Jurafsky", "Dan Jurafsky homepage", "https://web.stanford.edu/~jurafsky/"),
  "percy-liang-us": portrait("percy-liang-us", "Percy Liang", "Percy Liang homepage", "https://cs.stanford.edu/people/pliang/"),
  "christopher-potts-us": portrait("christopher-potts-us", "Christopher Potts", "Stanford Bio-X faculty profile", "https://biox.stanford.edu/people/chris-potts"),
  "tatsunori-hashimoto-us": portrait("tatsunori-hashimoto-us", "Tatsunori Hashimoto", "Tatsunori Hashimoto homepage", "https://thashim.github.io/"),
  "diyi-yang-us": portrait("diyi-yang-us", "Diyi Yang", "Diyi Yang homepage", "https://cs.stanford.edu/people/diyiy/index.html"),
  "yejin-choi-us": portrait("yejin-choi-us", "Yejin Choi", "Stanford HAI faculty profile", "https://hai.stanford.edu/people/yejin-choi"),
  "dora-demszky-us": portrait("dora-demszky-us", "Dora Demszky", "Stanford Graduate School of Education faculty profile", "https://ed.stanford.edu/faculty/ddemszky"),
  "dan-klein-us": portrait("dan-klein-us", "Dan Klein", "Berkeley NLP faculty roster", "https://nlp.berkeley.edu/people/"),
  "sewon-min-us": portrait("sewon-min-us", "Sewon Min", "Sewon Min homepage", "https://www.sewonmin.com/"),
  "alane-suhr-us": portrait("alane-suhr-us", "Alane Suhr", "Alane Suhr homepage", "https://www.alanesuhr.com/"),
  "david-bamman-us": portrait("david-bamman-us", "David Bamman", "Berkeley NLP faculty roster", "https://nlp.berkeley.edu/people/"),
  "john-denero-us": portrait("john-denero-us", "John DeNero", "Berkeley NLP faculty roster", "https://nlp.berkeley.edu/people/"),
  "steven-bird-us": portrait("steven-bird-us", "Steven Bird", "Berkeley NLP faculty roster", "https://nlp.berkeley.edu/people/"),
  "akari-asai-us": portrait("akari-asai-us", "Akari Asai", "CMU LTI faculty roster", "https://www.lti.cs.cmu.edu/people/faculty/index.html"),
  "graham-neubig-us": portrait("graham-neubig-us", "Graham Neubig", "Graham Neubig homepage", "https://www.phontron.com/"),
  "yonatan-bisk-us": portrait("yonatan-bisk-us", "Yonatan Bisk", "CMU LTI faculty roster", "https://www.lti.cs.cmu.edu/people/faculty/index.html"),
  "daniel-fried-us": portrait("daniel-fried-us", "Daniel Fried", "Daniel Fried homepage", "https://dpfried.github.io/"),
  "mona-diab-us": portrait("mona-diab-us", "Mona Diab", "CMU LTI faculty roster", "https://www.lti.cs.cmu.edu/people/faculty/index.html"),
  "carolyn-rose-us": portrait("carolyn-rose-us", "Carolyn Rosé", "CMU Human-Computer Interaction Institute profile", "https://hcii.cmu.edu/people/carolyn-rose"),
  "noah-smith-us": portrait("noah-smith-us", "Noah A. Smith", "Noah A. Smith homepage", "https://homes.cs.washington.edu/~nasmith/"),
  "luke-zettlemoyer-us": portrait("luke-zettlemoyer-us", "Luke Zettlemoyer", "Luke Zettlemoyer homepage", "https://homes.cs.washington.edu/~lsz/"),
  "hannaneh-hajishirzi-us": portrait("hannaneh-hajishirzi-us", "Hanna Hajishirzi", "Hanna Hajishirzi homepage", "https://homes.cs.washington.edu/~hannaneh/index.html"),
  "yulia-tsvetkov-us": portrait("yulia-tsvetkov-us", "Yulia Tsvetkov", "Yulia Tsvetkov homepage", "https://homes.cs.washington.edu/~yuliats/"),
  "lucy-lu-wang-us": portrait("lucy-lu-wang-us", "Lucy Lu Wang", "UW iSchool faculty profile", "https://ischool.uw.edu/people/faculty/profile/lucylw"),
  "tim-althoff-us": portrait("tim-althoff-us", "Tim Althoff", "UW Allen School faculty profile", "https://www.cs.washington.edu/people/faculty/tim-althoff/"),
  "regina-barzilay-us": portrait("regina-barzilay-us", "Regina Barzilay", "Regina Barzilay homepage", "https://www.regina.csail.mit.edu/"),
  "danqi-chen-us": portrait("danqi-chen-us", "Danqi Chen", "Danqi Chen homepage", "https://www.cs.princeton.edu/~danqic/"),
  "karthik-narasimhan-us": portrait("karthik-narasimhan-us", "Karthik Narasimhan", "Karthik Narasimhan homepage", "https://www.cs.princeton.edu/~karthikn/"),
  "claire-cardie-us": portrait("claire-cardie-us", "Claire Cardie", "Cornell Bowers faculty profile", "https://www.cs.cornell.edu/people/claire-cardie"),
  "yoav-artzi-us": portrait("yoav-artzi-us", "Yoav Artzi", "Cornell Bowers faculty profile", "https://www.cs.cornell.edu/people/yoav-artzi"),
  "cristian-danescu-us": portrait("cristian-danescu-us", "Cristian Danescu-Niculescu-Mizil", "Cornell Bowers faculty profile", "https://www.cs.cornell.edu/people/cristian-danescu-niculescu-mizil"),
  "tanya-goyal-us": portrait("tanya-goyal-us", "Tanya Goyal", "Cornell Bowers faculty profile", "https://www.cs.cornell.edu/people/tanya-goyal"),
  "sasha-rush-us": portrait("sasha-rush-us", "Alexander Rush", "Alexander Rush homepage", "https://rush-nlp.com/"),
  "samuel-bowman-us": portrait("samuel-bowman-us", "Samuel Bowman", "NYU Computer Science faculty roster", "https://cs.nyu.edu/dynamic/people/faculty/area/Natural%20Language%2C%20Speech%20Processing%2C%20and%20Knowledge%20Representation/?type=22"),
  "kyunghyun-cho-us": portrait("kyunghyun-cho-us", "Kyunghyun Cho", "NYU Computer Science faculty roster", "https://cs.nyu.edu/dynamic/people/faculty/area/Natural%20Language%2C%20Speech%20Processing%2C%20and%20Knowledge%20Representation/?type=22"),
  "eunsol-choi-us": portrait("eunsol-choi-us", "Eunsol Choi", "NYU Computer Science faculty roster", "https://cs.nyu.edu/dynamic/people/faculty/area/Natural%20Language%2C%20Speech%20Processing%2C%20and%20Knowledge%20Representation/?type=22"),
  "he-he-us": portrait("he-he-us", "He He", "NYU Computer Science faculty roster", "https://cs.nyu.edu/dynamic/people/faculty/area/Natural%20Language%2C%20Speech%20Processing%2C%20and%20Knowledge%20Representation/?type=22"),
  "julia-hirschberg-us": portrait("julia-hirschberg-us", "Julia Hirschberg", "Julia Hirschberg homepage", "https://www.cs.columbia.edu/~julia/index.html"),
  "kathleen-mckeown-us": portrait("kathleen-mckeown-us", "Kathleen McKeown", "Kathleen McKeown homepage", "https://www.cs.columbia.edu/~kathy/"),
  "katrin-erk-us": portrait("katrin-erk-us", "Katrin Erk", "UMass NLP members", "https://nlp.cs.umass.edu/members/"),
  "mohit-iyyer-us": portrait("mohit-iyyer-us", "Mohit Iyyer", "UMass NLP members", "https://nlp.cs.umass.edu/members/"),
  "andrew-mccallum-us": portrait("andrew-mccallum-us", "Andrew McCallum", "UMass NLP members", "https://nlp.cs.umass.edu/members/"),
  "brendan-oconnor-us": portrait("brendan-oconnor-us", "Brendan O'Connor", "UMass NLP members", "https://nlp.cs.umass.edu/members/"),
  "jacob-andreas-us": portrait("jacob-andreas-us", "Jacob Andreas", "MIT CSAIL NLP Group", "https://www.csail.mit.edu/research/natural-language-processing-group"),
  "yoon-kim-us": portrait("yoon-kim-us", "Yoon Kim", "MIT CSAIL NLP Group", "https://www.csail.mit.edu/research/natural-language-processing-group"),
  "smaranda-muresan-us": portrait("smaranda-muresan-us", "Smaranda Muresan", "Smaranda Muresan homepage", "https://www.cs.columbia.edu/~smara/"),
  "zhou-yu-us": portrait("zhou-yu-us", "Zhou Yu", "Columbia Engineering faculty profile", "https://www.engineering.columbia.edu/faculty-staff/directory/zhou-yu"),
  "john-hewitt-us": portrait("john-hewitt-us", "John Hewitt", "John Hewitt homepage", "https://www.cs.columbia.edu/~johnhew/"),
  "benjamin-van-durme-us": portrait("benjamin-van-durme-us", "Benjamin Van Durme", "Johns Hopkins CLSP faculty profile", "https://www.clsp.jhu.edu/faculty/benjamin-van-durme/"),
  "jason-eisner-us": portrait("jason-eisner-us", "Jason Eisner", "Johns Hopkins Whiting School faculty profile", "https://engineering.jhu.edu/faculty/jason-eisner/"),
  "philipp-koehn-us": portrait("philipp-koehn-us", "Philipp Koehn", "Philipp Koehn homepage", "https://www.cs.jhu.edu/~phi/"),
  "mark-dredze-us": portrait("mark-dredze-us", "Mark Dredze", "Mark Dredze homepage", "https://www.cs.jhu.edu/~mdredze/"),
  "greg-durrett-us": portrait("greg-durrett-us", "Greg Durrett", "UT Austin Computer Science faculty profile", "https://www.cs.utexas.edu/people/faculty-researchers/greg-durrett"),
  "raymond-mooney-us": portrait("raymond-mooney-us", "Raymond Mooney", "UT Austin Computer Science faculty profile", "https://www.cs.utexas.edu/people/faculty-researchers/raymond-mooney"),
  "peter-stone-us": portrait("peter-stone-us", "Peter Stone", "UT Austin Computer Science faculty profile", "https://www.cs.utexas.edu/people/faculty-researchers/peter-stone"),
  "qiang-liu-us": portrait("qiang-liu-us", "Qiang Liu", "UT Austin Computer Science faculty profile", "https://www.cs.utexas.edu/people/faculty-researchers/qiang-liu"),
};
