import type { Person, Source } from "./data";

const checkedAt = "2026-08-31";

const portrait = (
  src: string,
  alt: string,
  label: string,
  url: string,
): NonNullable<Person["portrait"]> => ({
  src,
  alt,
  source: {
    label,
    url,
    kind: "official",
    checkedAt,
    supports: `Official or university-hosted portrait of ${alt}`,
  } satisfies Source,
});

/**
 * Portraits for faculty discovered through the 2023–2026 conference-award audit.
 *
 * These are deliberately conservative: every image is hosted by the person's
 * university, institute, lab, or personal academic site and was checked against
 * the matching faculty/profile page. The current 91-person award-audit cohort is
 * fully mapped; future ambiguous additions should remain initials until verified.
 */
export const awardAuditPortraits: Record<string, NonNullable<Person["portrait"]>> = {
  "alexandra-birch-award": portrait("https://people.inf.ed.ac.uk/images/fc655afc-6670-4375-afe6-55dc0c802559", "Alexandra Birch", "University of Edinburgh portrait", "https://people.inf.ed.ac.uk/Alexandra_Birch-Mayne.html"),
  "bing-liu-award": portrait("https://cs.uic.edu/wp-content/uploads/sites/110/2018/06/Bing-Liu-157x180.jpg", "Bing Liu", "University of Illinois Chicago portrait", "https://cs.uic.edu/profiles/bing-liu/"),
  "guillaume-lajoie-award": portrait("https://mila.quebec/sites/default/files/styles/member_full/public/member/5187/portrait-of-guillaume-lajoie.jpeg.webp?itok=6ReZnxvR", "Guillaume Lajoie", "Mila portrait", "https://mila.quebec/fr/annuaire/guillaume-lajoie"),
  "kyle-mahowald-award": portrait("https://texasconnect.utexas.edu/wp-content/uploads/2026/03/20251119_Mahowald_CK_1_1-600x600-c-default.jpg", "Kyle Mahowald", "University of Texas portrait", "https://texasconnect.utexas.edu/2026/03/23/thinking-inside-the-boxes-linguistics-professor-has-a-passion-for-crossword-puzzles/"),
  "ludwig-schmidt-uw-award": portrait("https://www.engr.washington.edu/sites/engr/files/faculty/new%20faculty%202021/new-faculty-2021_Ludwig%20Schmidt.png", "Ludwig Schmidt", "University of Washington portrait", "https://www.engr.washington.edu/facresearch/newfaculty/2021/schmidt"),
  "mark-yatskar-upenn-award": portrait("https://dbei.med.upenn.edu/wp-content/uploads/2025/07/Yatskar-Mark-directory-e1752875471355.jpg", "Mark Yatskar", "University of Pennsylvania portrait", "https://dbei.med.upenn.edu/news-events/big-data-conference-2025/speakers-2/mark-yatskar-phd/"),
  "ming-hsuan-yang-award": portrait("https://engineering.ucmerced.edu/sites/g/files/ufvvjh831/f/people/photos/150yang_ming-hsuan_120118.jpg", "Ming-Hsuan Yang", "University of California, Merced portrait", "https://engineering.ucmerced.edu/content/ming-hsuan-yang"),
  "ranjay-krishna-uw-award": portrait("https://www.cs.washington.edu/wp-content/uploads/elementor/thumbs/portrait-ranjay-krishna-rsiyasn41bgnxsjjqjmofmc89xpqgcqfmjp7moz44g.jpg", "Ranjay Krishna", "University of Washington portrait", "https://www.cs.washington.edu/people/faculty/ranjay-krishna/"),
  "tomasz-trzcinski-award": portrait("https://cvlab.ii.pw.edu.pl/ttrzcins/photo2.jpg", "Tomasz Trzciński", "Warsaw University of Technology CVLab portrait", "https://cvlab.ii.pw.edu.pl/ttrzcins/"),
  "wei-lun-chao-osu-award": portrait("https://opic.osu.edu/chao.209?aspect=p&width=300", "Wei-Lun Chao", "Ohio State University portrait", "https://tdai.osu.edu/people/chao.209"),
  "xiangnan-he-ustc-award": portrait("https://iat.ustc.edu.cn/Uploads/Editor/2020-03-22/5e765af80bd3f.png", "何向南", "University of Science and Technology of China portrait", "https://iat.ustc.edu.cn/iat/x223/20200321/2368.html"),
  "yanghua-xiao-award": portrait("https://datascience.fudan.edu.cn/_upload/article/images/65/94/1e26b6864c459eead3056a5953ae/6069ce15-6c41-4ef3-af18-5f07c63140f3.png", "肖仰华", "Fudan University portrait", "https://datascience.fudan.edu.cn/74/93/c13433a488595/page.psp"),
  "ying-wei-cityu-award": portrait("https://person.zju.edu.cn/person//attachments/2024-10/1017042309-72928548.jpg", "魏颖", "Zhejiang University portrait", "https://person.zju.edu.cn/0024167"),
  "yisong-yue-caltech-award": portrait("https://divisions-prod-assets.resources.caltech.edu/bbe20/images/Yue.2e16d0ba.fill-310x412-c100.jpg", "Yisong Yue", "Caltech portrait", "https://www.bbe.caltech.edu/people/yisong-yue"),
  "yu-su-osu-award": portrait("https://ysu1989.github.io/images/YuSu.jpeg", "Yu Su", "Ohio State academic portrait", "https://ysu1989.github.io/"),
  "richard-futrell-award": portrait("https://www.socsci.uci.edu/files/news_events/2022/richardfutrell_880.jpg", "Richard Futrell", "UC Irvine portrait", "https://sites.socsci.uci.edu/~rfutrell/index.html"),
  "david-jurgens-award": portrait("https://si.umich.edu/sites/default/files/styles/profile_image/public/2019-12/david_jurgens.jpeg?itok=4D6iAdvc", "David Jurgens", "University of Michigan portrait", "https://si.umich.edu/people/david-jurgens"),
  "colin-raffel-award": portrait("https://vanguardlab.cs.utoronto.ca/wp-content/uploads/2026/01/Colin-headshot-scaled-e1694032052288-1600x0-c-default.jpeg", "Colin Raffel", "University of Toronto Vanguard Lab portrait", "https://vanguardlab.cs.utoronto.ca/projects/"),
  "david-lindell-ca-award": portrait("https://davidlindell.com/assets/img/prof_pic.jpg", "David B. Lindell", "Academic homepage portrait", "https://davidlindell.com/"),
  "deyu-meng-xjtu-award": portrait("https://gr.xjtu.edu.cn/_resource/fileshow/7260d3f5-be9f-4932-bb85-797f99023dbe.jpg", "孟德宇", "Xi'an Jiaotong University portrait", "https://gr.xjtu.edu.cn/mengdeyu/zh_CN/zdylm/1068401/list/index.htm"),
  "gao-huang-tsinghua-award": portrait("https://www.au.tsinghua.edu.cn/__local/D/72/0F/B0BBEA1B3B7CB37877E02D7B13A_660E158E_67419.jpg", "高煌", "Tsinghua University portrait", "https://www.au.tsinghua.edu.cn/en/info/1075/3328.htm"),
  "he-wang-pku-award": portrait("https://cs.pku.edu.cn/virtual_attach_file.vsb?afc=5U4-CbLRLPLll8LQ4UsnNrVLNlYnzNqPLRLYU8laU4VfU4L0gihFp2hmCIa0LYybLYhVnSy4LzCsUl-DolL8ozG8MmQ7LNVkozC8MmMfUlMFLmfVUm7DnRWFnmLinmCJqjfjo4OeoDX4qjAb_khXptQ0gY84gY84gtA8pUpcc&e=.jpg&oid=1934453449", "王鹤", "Peking University portrait", "https://cs.pku.edu.cn/info/1083/1707.htm"),
  "liwei-wang-pku-award": portrait("https://www.ai.pku.edu.cn/virtual_attach_file.vsb?afc=5nz-CDLRlinlL4MQ7lPnR-PMN78UlWq7olVVLzlZL7V7M8L0gihFp2hmCIa0LSh2n1y8MYy4L49DoRCYU47DnNr7n7CYM4lsLNUZUzW7L7MFnzr7LzGaMzQFLlMfU1b%2Fv2veo4Oevt6EpjT%2FQIZ0qIbtpYyxLYyxLYbw62p8c&e=.jpg&oid=1583923523", "王立威", "Peking University portrait", "https://www.ai.pku.edu.cn/en/info/1409/1831.htm"),
  "liang-lin-award": portrait("https://www.sysu-hcp.net/userfiles/images/2020/8af48bdf0a369e6e.jpg", "林倞", "Sun Yat-sen University HCP Lab portrait", "https://www.sysu-hcp.net/faculty/lianglin.html"),
  "shiji-song-award": portrait("https://www.au.tsinghua.edu.cn/__local/D/94/37/44852E95738A70089A067560C7E_B537C6E0_4575.jpg", "宋士吉", "Tsinghua University portrait", "https://www.au.tsinghua.edu.cn/info/1075/3206.htm"),
  "yujiu-yang-tsinghua-award": portrait("https://www.sigs.tsinghua.edu.cn/_upload/article/images/d3/f9/c040f5714c29a9e7437fee48fd71/01bb8f34-e53c-4034-9aa9-954788a1150e_s.jpg", "杨余久", "Tsinghua SIGS portrait", "https://www.sigs.tsinghua.edu.cn/yyj_en/main.htm"),
  "elisabeth-andre-award": portrait("https://assets.uni-augsburg.de/media/filer_public_thumbnails/filer_public/0b/b0/0bb095e9-8149-437b-a942-780582967d5c/elisabeth-andre-mit-roboter_klein.jpg__800x800_q85_optimize_subject_location-85%2C119_subsampling-2.jpg", "Elisabeth André", "University of Augsburg portrait", "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/prof/hcm/team/andre/"),
  "florian-bernard-bonn-award": portrait("https://www.informatik.uni-bonn.de/px/team-members/bernard_profile.png/%40%40images/image", "Florian Bernard", "University of Bonn portrait", "https://www.informatik.uni-bonn.de/en/research/visual-computing/visual-computing"),
  "ruoxi-jia-award": portrait("https://ece.vt.edu/content/dam/ece_vt_edu/people/portraits/rouxi-jia.jpg.transform/xl-medium/image.jpg", "Ruoxi Jia", "Virginia Tech ECE portrait", "https://ece.vt.edu/people/faculty.html"),
  "weiyan-shi-award": portrait("https://coe.northeastern.edu/wp-content/uploads/profiles/ece/shi-w-768x1024.jpg", "Weiyan Shi", "Northeastern College of Engineering portrait", "https://coe.northeastern.edu/people/shi-weiyan/"),
  "david-chiang-award": portrait("https://cse.nd.edu/wp-content/uploads/2020/06/Chiang-David-HS-800x800.jpg", "David Chiang", "Notre Dame CSE portrait", "https://cse.nd.edu/faculty/"),
  "tal-linzen-award": portrait("https://linguistics.umd.edu/sites/default/files/2024-01/tal-linzen-web.jpeg", "Tal Linzen", "University of Maryland invited-speaker portrait", "https://linguistics.umd.edu/events/csc-tal-linzen/role-language-models-linguistics"),
  "michael-hahn-award": portrait("https://www.uni-saarland.de/fileadmin/upload/aktuell/fotos/pm/2024/Hahn_Michael.jpg", "Michael Hahn", "Saarland University portrait", "https://www.uni-saarland.de/fachrichtung/lst/news/michael-hahn-nimmt-ruf-auf-die-tenure-track-professur-in-unserer-fachrichtung-an-23976.html"),
  "antonios-anastasopoulos-award": portrait("https://www.gmu.edu/sites/g/files/yyqcgq291/files/2023-09/Antonios-Anastasopoulos-1x1.jpg", "Antonios Anastasopoulos", "George Mason University portrait", "https://cs.gmu.edu/people/faculty"),
  "alan-ritter-award": portrait("https://research.gatech.edu/sites/default/files/photos/picRitter.png", "Alan Ritter", "Georgia Tech portrait", "https://www.cc.gatech.edu/people/alan-ritter"),
  "wei-xu-award": portrait("https://research.gatech.edu/sites/default/files/photos/weixu_profile.png", "Wei Xu", "Georgia Tech portrait", "https://www.cc.gatech.edu/people/wei-xu"),
  "zhihao-jia-award": portrait("https://csd.cmu.edu/sites/default/files/2023-01/photo.jpg", "Zhihao Jia", "Carnegie Mellon portrait", "https://csd.cs.cmu.edu/people/faculty/zhihao-jia"),
  "sanmi-koyejo-award": portrait("https://www.cs.stanford.edu/sites/g/files/sbiybj28076/files/styles/large_square/public/media/person/sanmi-koyejo1751174063680.jpg?h=1641edec&itok=7EuqOedR", "Sanmi Koyejo", "Stanford Computer Science portrait", "https://profiles.stanford.edu/sanmi-koyejo"),
  "robert-west-award": portrait("https://actu.epfl.ch/image/141877/1440x810.jpg", "Robert West", "EPFL portrait", "https://people.epfl.ch/robert.west?lang=en"),
  "walid-magdy-award": portrait("https://www.turing.ac.uk/sites/default/files/styles/people/public/2018-10/92891832_6947789_669253.jpg?itok=WNfVczPI", "Walid Magdy", "Alan Turing Institute portrait", "https://www.research.ed.ac.uk/en/persons/walid-magdy/"),
  "junchi-yan-award": portrait("https://cs.sjtu.edu.cn/cse/Management/Upload/%5BUser%5Da456db24997c44e786968b30e712fc9c/20235415517948ZYxVm.jpg", "严骏驰", "Shanghai Jiao Tong University portrait", "https://speit.sjtu.edu.cn/en/faculty/42920"),
  "ndapa-nakashole-award": portrait("https://cse.ucsd.edu/sites/default/files/news/NdapaNakashole_400x400.jpg", "Ndapa Nakashole", "UC San Diego portrait", "https://cse.ucsd.edu/people/faculty-profiles/ndapa-nakashole"),
  "anna-rohrbach-award": portrait("https://www.informatik.tu-darmstadt.de/media/informatik/fb20_allgemeines/fb20_profilfotos/fb20_proferssors/rohrbach_a_DSC8458_415x415.jpg", "Anna Rohrbach", "TU Darmstadt portrait", "https://www.informatik.tu-darmstadt.de/mai/multimodal_ai/people_mai/teamdetails_136832.en.jsp"),
  "marcus-rohrbach-award": portrait("https://www.informatik.tu-darmstadt.de/media/mai/mai_images_people/marcus_rohrbach_1180x0.jpg", "Marcus Rohrbach", "TU Darmstadt portrait", "https://www.informatik.tu-darmstadt.de/mai/multimodal_ai/index.en.jsp"),
  "mubarak-shah-award": portrait("https://graduate.ucf.edu/wp-content/uploads/sites/8/2021/09/Website-Image.jpg", "Mubarak Shah", "University of Central Florida portrait", "https://www.cs.ucf.edu/person/mubarakshah/"),
  "boaz-barak-award": portrait("https://lowell.harvard.edu/sites/g/files/omnuum5006/files/styles/hwp_1_1__800x800/public/2025-02/author_bbarak.png?itok=CrmBIhys", "Boaz Barak", "Harvard Lowell House portrait", "https://lowell.harvard.edu/people/boaz-barak"),
  "stephan-mandt-award": portrait("https://cml.ics.uci.edu/wp-content/uploads/Mandt_191126__SRZ7172-1-768x517.jpg", "Stephan Mandt", "UC Irvine Center for Machine Learning portrait", "https://cml.ics.uci.edu/2020/02/uci-and-disney-research-scientists-develop-ai-enhanced-video-compression-model/"),
  "animashree-anandkumar-award": portrait("https://caltech-prod.resources.caltech.edu/main/images/Anandkumar_Anima-FACULTY-EAS-4455-NW.original.jpg?download=true", "Animashree Anandkumar", "Caltech portrait", "https://www.caltech.edu/about/news/anima-anandkumar-appointed-to-un-scientific-advisory-board"),
  "dan-hendrycks-award": portrait("https://cdn.prod.website-files.com/63fe96aeda6bea77ac7d3000/6888621bb1cce773927f37a5_Dan_NYT_2024_cropped.webp", "Dan Hendrycks", "Center for AI Safety portrait", "https://safe.ai/"),
  "dawn-song-award": portrait("https://www2.eecs.berkeley.edu/Faculty/Photos/Fullsize/song.jpg", "Dawn Song", "UC Berkeley EECS portrait", "https://www2.eecs.berkeley.edu/Faculty/Homepages/song.html"),
  "bo-li-uiuc-award": portrait("https://ws.engr.illinois.edu/directory/viewphoto/lbo/1200", "Bo Li", "University of Illinois portrait", "https://ece.illinois.edu/about/directory/faculty/lbo"),
  "jaakko-lehtinen-award": portrait("https://images.squarespace-cdn.com/content/v1/5d429cc990aa3d000191d3e3/1613130231232-3WZT4X5MAY9N5OZOQKHA/Lehtinen.png", "Jaakko Lehtinen", "Academic homepage portrait", "https://www.aalto.fi/en/people/jaakko-lehtinen"),
  "scott-hale-award": portrait("https://www.oii.ox.ac.uk/wp-content/uploads/2016/06/scott-hale-2025-700x395.jpg", "Scott A. Hale", "Oxford Internet Institute portrait", "https://www.oii.ox.ac.uk/people/profiles/scott-hale/"),
  "maarten-sap-award": portrait("https://lti.cmu.edu/people/faculty/faculty-bio-images/armscrossed_square_sm.jpg", "Maarten Sap", "Carnegie Mellon portrait", "https://www.lti.cs.cmu.edu/people/faculty/sap-maarten.html"),
  "benjamin-eysenbach-award": portrait("https://faculty.princeton.edu/sites/g/files/toruqf3496/files/styles/16x9_2880w_1620h/public/2026-06/20260514_eysenbachb_dja_021.jpg?itok=Ey9XfNhl", "Benjamin Eysenbach", "Princeton faculty portrait", "https://faculty.princeton.edu/news/2026/meet-benjamin-eysenbach-exploring-ai-decisionmaking-through-reinforcement-learning"),
  "steve-hanneke-award": portrait("https://www.cs.purdue.edu/people/images-landscape/faculty/hanneke.jpg", "Steve Hanneke", "Purdue Computer Science portrait", "https://www.cs.purdue.edu/people/faculty/hanneke.html"),
  "marc-mezard-award": portrait("https://cs.unibocconi.eu/sites/default/files/media/images/M%C3%A9zard850_0.png?VersionId=4wHYOw_PdIGB88abYxBU2fDTNpoPuGiD", "Marc Mézard", "Bocconi University portrait", "https://cs.unibocconi.eu/faculty/marc-mezard"),
  "giulio-biroli-award": portrait("https://www.paris-centre.cnrs.fr/sites/delegation_dr2/files/styles/person/public/image/BIROLI-web.jpg?itok=3Jm8M2dZ", "Giulio Biroli", "CNRS portrait", "https://www.paris-centre.cnrs.fr/fr/personne/giulio-biroli"),
  "pierre-baldi-award": portrait("https://caltechsites-prod-assets.resources.caltech.edu/heritageproject/images/BaldiPhoto-766x1024.original.jpg?download=true", "Pierre Baldi", "Caltech Heritage Project portrait", "https://heritageproject.caltech.edu/interviews-updates/pierre-baldi"),
  "andrea-tagliasacchi-ca-award": portrait("https://www.sfu.ca/content/sfu/fas/computing/people/faculty/faculty-members/taiya.img.1071222064.png", "Andrea Tagliasacchi", "Simon Fraser University portrait", "https://www.sfu.ca/fas/computing/people/faculty/faculty-members/taiya.html"),
  "vincent-sitzmann-mit-award": portrait("https://www.eecs.mit.edu/wp-content/uploads/2022/03/Sitzmann_Vincent-preferred-as-of-2025-scaled-e1761059560657.jpeg", "Vincent Sitzmann", "MIT EECS portrait", "https://www.csail.mit.edu/person/vincent-sitzmann"),
  "tanya-berger-wolf-osu-award": portrait("https://people.engineering.osu.edu/sites/default/files/styles/coe_3_4_medium_large/public/2020-08/TanyaBW19%20-1.jpeg", "Tanya Berger-Wolf", "Ohio State University portrait", "https://cse.osu.edu/people/berger-wolf.1"),
  "ioannis-gkioulekas-cmu-award": portrait("https://www.csd.cmu.edu/sites/default/files/2023-10/GKIOULEKAS-Ioannis-2023.jpg", "Ioannis Gkioulekas", "Carnegie Mellon portrait", "https://scsdean.cs.cmu.edu/new-faculty/2017.html"),
  "fuxin-li-oregon-award": portrait("https://engineering.oregonstate.edu/sites/engineering.oregonstate.edu/files/styles/facebook_1200x/public/2023-04/profile-fuxin-li.jpg?itok=7FtWZ_5L", "Fuxin Li", "Oregon State University portrait", "https://engineering.oregonstate.edu/people/fuxin-li"),
  "andrea-vedaldi-oxford-award": portrait("https://robots.ox.ac.uk/~vedaldi/images/vedaldi.jpg", "Andrea Vedaldi", "Oxford academic portrait", "https://robots.ox.ac.uk/~vedaldi/index.html"),
  "matthew-otoole-cmu-award": portrait("https://www.ri.cmu.edu/app/uploads/2018/05/matthew-otoole-csd-ri-crop.jpg", "Matthew O'Toole", "CMU Robotics Institute portrait", "https://www.ri.cmu.edu/ri-faculty/matthew-otoole/"),
  "chris-callison-burch-upenn-award": portrait("https://directory.seas.upenn.edu/wp-content/uploads/2020/03/callison-burch-chris.jpg", "Chris Callison-Burch", "Penn Engineering portrait", "https://directory.seas.upenn.edu/"),
  "andrew-head-upenn-award": portrait("https://andrewhead.info/assets/img/andrew4.jpg", "Andrew Head", "Academic homepage portrait", "https://andrewhead.info/"),
  "georgia-gkioxari-caltech-award": portrait("https://caltech-prod.resources.caltech.edu/main/images/Gkioxari_Georgia-Faculty-0236-WEB.original.jpg?download=true", "Georgia Gkioxari", "Caltech portrait", "https://www.eas.caltech.edu/people/georgia-gkioxari"),
  "yuke-zhu-utaustin-award": portrait("https://www.cs.utexas.edu/~yukez/images/yukezhu.jpg", "Yuke Zhu", "UT Austin academic portrait", "https://experts.utexas.edu/yuke_zhu"),
  "eero-simoncelli-award": portrait("https://www.cns.nyu.edu/csh/csh06/Lecturers/Simoncelli/Eero2.JPG", "Eero P. Simoncelli", "NYU CNS portrait", "https://cds.nyu.edu/team/eero-simoncelli/"),
  "stephane-mallat-award": portrait("https://www.college-de-france.fr/sites/default/files/media/portrait/2022-04/Stephane-Mallat_2.jpg", "Stéphane Mallat", "Collège de France portrait", "https://www.college-de-france.fr/en/chair/stephane-mallat-data-science-statutory-chair"),
  "leslie-kaelbling-award": portrait("https://www.eecs.mit.edu/wp-content/uploads/2021/07/Kaelbling_Leslie-preferred-as-of-2023-2048x2048.jpg", "Leslie Pack Kaelbling", "MIT EECS portrait", "https://www.eecs.mit.edu/role/faculty/?fwp_research=artificial-intelligence-machine-learning"),
  "julien-mairal-award": portrait("https://www.inria.fr/sites/default/files/2019-12/A_Mairal_Inria-0262-021_707x530.jpg", "Julien Mairal", "Inria portrait", "https://www.inria.fr/fr/julien-mairal-recoit-le-prix-international-pami"),
  "di-he-pku-award": portrait("https://sai.pku.edu.cn/__local/B/B9/F9/98B7EE034B9BB846BBE8D03A5AE_65A49F78_7778.jpg", "贺笛", "Peking University portrait", "https://sai.pku.edu.cn/znxyenglish/info/1362/2643.htm"),
  "andrea-montanari-award": portrait("https://events.seas.upenn.edu/wp-content/uploads/2019/08/KkQ9YkvP.jpg", "Andrea Montanari", "Penn Engineering invited-speaker portrait", "https://events.seas.upenn.edu/event/ese-seminar-andrea-montanari/"),
  "prateek-mittal-award": portrait("https://engineering.princeton.edu/wp-content/uploads/2021/08/mittal._16x9jpg-scaled.jpg", "Prateek Mittal", "Princeton Engineering portrait", "https://www.princeton.edu/~pmittal/"),
  "peter-henderson-award": portrait("https://plaw.law.princeton.edu/sites/g/files/toruqf6301/files/styles/16x9_750w_422h/public/2024-12/peter_henderson.jpg?itok=qnWwaFtL", "Peter Henderson", "Princeton University portrait", "https://www.cs.princeton.edu/people/profile/ph4162"),
  "danica-sutherland-award": portrait("https://www.cs.ubc.ca/sites/default/files/styles/profile_page/public/people/md1-4221.JPG?h=d30407f1&itok=8mb9XjPY", "Danica J. Sutherland", "University of British Columbia portrait", "https://www.cs.ubc.ca/people/danica-sutherland"),
  "dale-schuurmans-award": portrait("https://a-ca.storyblok.com/f/2000323/800x800/ef4455a44e/dale-schuurmans.webp/m/3840x5120", "Dale Schuurmans", "Amii portrait", "https://www.amii.ca/people/dale-schuurmans"),
  "tengyu-ma-award": portrait("https://ai.stanford.edu/~tengyuma/image/square_3594.jpg", "Tengyu Ma", "Stanford academic portrait", "https://ai.stanford.edu/~tengyuma/"),
  "ryan-cotterell-award": portrait("https://inf.ethz.ch/news-and-events/spotlights/infk-news-channel/2020/02/welcome-professor-ryan-cotterell/_jcr_content/pageimages/imageSmall.imageformat.contentteaser.876084193.jpg", "Ryan Cotterell", "ETH Zürich portrait", "https://inf.ethz.ch/news-and-events/spotlights/infk-news-channel/2020/02/welcome-professor-ryan-cotterell.html"),
  "jennifer-neville-award": portrait("https://www.cs.purdue.edu/people/images-landscape/faculty/neville.jpg", "Jennifer Neville", "Purdue Computer Science portrait", "https://www.cs.purdue.edu/people/faculty/neville.html"),
  "christopher-musco-award": portrait("https://engineering.nyu.edu/sites/default/files/styles/square_large_default_2x/public/2023-10/Chris%20Musco.jpeg?h=7d66a0c3&itok=YPD-JYS0", "Christopher Musco", "NYU Tandon portrait", "https://engineering.nyu.edu/faculty/christopher-musco"),
  "daniel-roy-award": portrait("https://www.statistics.utoronto.ca/sites/www.statistics.utoronto.ca/files/danroy-portrait.jpg", "Daniel M. Roy", "University of Toronto portrait", "https://www.statistics.utoronto.ca/people/directories/all-faculty/daniel-roy"),
  "aditi-raghunathan-award": portrait("https://www.csd.cs.cmu.edu/sites/default/files/2025-08/RAGHUNATHAN-Aditi.jpg", "Aditi Raghunathan", "Carnegie Mellon portrait", "https://csd.cs.cmu.edu/people/faculty/aditi-raghunathan"),
  "thomas-griffiths-award": portrait("https://engineering.princeton.edu/wp-content/uploads/2021/08/griffiths_portrait_1-1.jpg", "Thomas L. Griffiths", "Princeton Engineering portrait", "https://engineering.princeton.edu/faculty/tom-griffiths"),
  "james-zou-award": portrait("https://btp.stanford.edu/sites/g/files/sbiybj19201/files/styles/card_1192x596/public/media/image/jameszou_0.jpg?h=748c68d3&itok=-cCLaQjy", "James Zou", "Stanford portrait", "https://profiles.stanford.edu/james-zou"),
  "richard-bonneau-award": portrait("https://csmapnyu.org/img/asset/YXNzZXRzL3Blb3BsZS9yaWNoYXJkLWJvbm5lYXUuanBn?fm=webp&h=400&s=02f364ea622321cf371e1e4a62dba524&w=400", "Richard Bonneau", "NYU CSMap portrait", "https://csmapnyu.org/people/richard-bonneau"),
  "sham-kakade-award": portrait("https://kempnerinstitute.harvard.edu/app/uploads/2024/01/t7HhVpBi5wv3mFKz-5-sham_scaled.jpeg", "Sham M. Kakade", "Harvard Kempner Institute portrait", "https://kempnerinstitute.harvard.edu/people/our-people/sham-kakade/"),
  "constantinos-daskalakis-award": portrait("https://news.mit.edu/sites/default/files/images/201602/MIT-Constantinos-Daskalakis-A1-press.jpg", "Constantinos Daskalakis", "MIT portrait", "https://people.csail.mit.edu/costis/"),
};
