import type { Person } from "./data";

/** Locally cached portraits from first-party faculty, department, laboratory, or personal pages. */
export const finalMainlandPortraits: Record<string, NonNullable<Person["portrait"]>> = {
  "hongzheng-li-bit": {"src":"portraits/final-mainland/hongzheng-li-bit.jpg","alt":"Portrait of Hongzheng Li","source":{"label":"Portrait source · BIT School of Foreign Languages news","url":"https://sfl.bit.edu.cn/xyxw/c8262fe15eb545269244222aa9d03642.htm","kind":"official","checkedAt":"2026-08-30","supports":"Portrait identity for Hongzheng Li"}},
  "peilin-jiang-xjtu": {"src":"portraits/final-mainland/peilin-jiang-xjtu.jpg","alt":"Portrait of Peilin Jiang","source":{"label":"Portrait source · Xi'an Jiaotong University teacher profile","url":"https://mob.xjtu.edu.cn/teacher_content.jsp?urltype=tree.TreeTempUrl&wbtreeid=1170&wbwbxjtuteacherid=3013","kind":"official","checkedAt":"2026-08-30","supports":"Portrait identity for Peilin Jiang"}},
  "yizhou-wang-pku": {"src":"portraits/final-mainland/yizhou-wang-pku.jpg","alt":"王亦洲肖像","source":{"label":"肖像来源 · 北京大学前沿计算研究中心","url":"https://cfcs.pku.edu.cn/people/faculty/yizhouwang/","kind":"official","checkedAt":"2026-08-30","supports":"王亦洲人物身份与肖像"}},
  "yiwu-zhong-pku": {"src":"portraits/final-mainland/yiwu-zhong-pku.jpg","alt":"钟亦武肖像","source":{"label":"肖像来源 · 北京大学智能学院教师主页","url":"https://www.cis.pku.edu.cn/info/1362/3348.htm","kind":"official","checkedAt":"2026-08-30","supports":"钟亦武人物身份与肖像"}},
  "cewu-lu-sjtu": {"src":"portraits/final-mainland/cewu-lu-sjtu.jpg","alt":"卢策吾肖像","source":{"label":"肖像来源 · 上海交通大学人工智能学院","url":"https://sai.sjtu.edu.cn/cn/facultydetails/zzjs/lucewu","kind":"official","checkedAt":"2026-08-30","supports":"卢策吾人物身份与肖像"}},
  "yanfeng-wang-sjtu": {"src":"portraits/final-mainland/yanfeng-wang-sjtu.jpg","alt":"王延峰肖像","source":{"label":"肖像来源 · 上海交通大学人工智能学院","url":"https://sai.sjtu.edu.cn/cn/facultydetails/zzjs/wangyanfeng","kind":"official","checkedAt":"2026-08-30","supports":"王延峰人物身份与肖像"}},
  "guangtao-zhai-sjtu": {"src":"portraits/final-mainland/guangtao-zhai-sjtu.jpg","alt":"翟广涛肖像","source":{"label":"肖像来源 · 上海交通大学教师个人主页","url":"https://faculty.sjtu.edu.cn/zhaiguangtao/zh_CN/index.htm","kind":"official","checkedAt":"2026-08-30","supports":"翟广涛人物身份与肖像"}},
  "fei-wu-zju": {"src":"portraits/final-mainland/fei-wu-zju.jpg","alt":"吴飞肖像","source":{"label":"肖像来源 · 浙江大学教师个人主页","url":"https://mypage.zju.edu.cn/wufei/","kind":"official","checkedAt":"2026-08-30","supports":"吴飞人物身份与肖像"}},
  "deng-cai-zju": {"src":"portraits/final-mainland/deng-cai-zju.jpg","alt":"蔡登肖像","source":{"label":"肖像来源 · 浙江大学教师个人主页","url":"https://person.zju.edu.cn/0009217","kind":"official","checkedAt":"2026-08-30","supports":"蔡登人物身份与肖像"}},
  "jiajun-bu-zju": {"src":"portraits/final-mainland/jiajun-bu-zju.jpg","alt":"卜佳俊肖像","source":{"label":"肖像来源 · 浙江大学教师个人主页","url":"https://person.zju.edu.cn/bjj/0.html","kind":"official","checkedAt":"2026-08-30","supports":"卜佳俊人物身份与肖像"}},
  "xiangyang-xue-fdu": {"src":"portraits/final-mainland/xiangyang-xue-fdu.jpg","alt":"薛向阳肖像","source":{"label":"肖像来源 · 复旦大学智能图像与集成学习实验室","url":"https://iipl.fudan.edu.cn/70/cc/c45863a684236/page.htm","kind":"official","checkedAt":"2026-08-30","supports":"薛向阳人物身份与肖像"}},
  "zuxuan-wu-fdu": {"src":"portraits/final-mainland/zuxuan-wu-fdu.jpg","alt":"吴祖煊肖像","source":{"label":"肖像来源 · 复旦大学智能图像与集成学习实验室","url":"https://iipl.fudan.edu.cn/7f/c1/c45855a688065/page.htm","kind":"official","checkedAt":"2026-08-30","supports":"吴祖煊人物身份与肖像"}},
  "zhihua-zhou-nju": {"src":"portraits/final-mainland/zhihua-zhou-nju.jpg","alt":"周志华肖像","source":{"label":"肖像来源 · 南京大学教师主页","url":"https://www.nju.edu.cn/info/1040/372961.htm","kind":"official","checkedAt":"2026-08-30","supports":"周志华人物身份与肖像"}},
  "jianxin-wu-nju": {"src":"portraits/final-mainland/jianxin-wu-nju.jpg","alt":"吴建鑫肖像","source":{"label":"肖像来源 · 南京大学软件新技术全国重点实验室","url":"https://keysoftlab.nju.edu.cn/1599/list.htm","kind":"official","checkedAt":"2026-08-30","supports":"吴建鑫人物身份与肖像"}},
  "tong-lu-nju": {"src":"portraits/final-mainland/tong-lu-nju.jpg","alt":"路通肖像","source":{"label":"肖像来源 · 南京大学计算机学院教师主页","url":"https://cs.nju.edu.cn/58/01/c2639a153601/pagem.htm","kind":"official","checkedAt":"2026-08-30","supports":"路通人物身份与肖像"}},
  "houqiang-li-ustc": {"src":"portraits/final-mainland/houqiang-li-ustc.jpg","alt":"李厚强肖像","source":{"label":"肖像来源 · 中国科学技术大学教师个人主页","url":"https://faculty.ustc.edu.cn/lihouqiang/zh_CN/index.htm","kind":"official","checkedAt":"2026-08-30","supports":"李厚强人物身份与肖像"}},
  "enhong-chen-ustc": {"src":"portraits/final-mainland/enhong-chen-ustc.jpg","alt":"陈恩红肖像","source":{"label":"肖像来源 · 中国科学技术大学计算机学院","url":"https://cs.ustc.edu.cn/2020/0806/c23235a460077/page.htm","kind":"official","checkedAt":"2026-08-30","supports":"陈恩红人物身份与肖像"}},
  "junjun-jiang-hit": {"src":"portraits/final-mainland/junjun-jiang-hit.jpg","alt":"江俊君肖像","source":{"label":"肖像来源 · 哈尔滨工业大学人工智能研究院","url":"https://sai.hit.edu.cn/2024/1024/c19933a357239/page.htm","kind":"official","checkedAt":"2026-08-30","supports":"江俊君人物身份与肖像"}},
  "chen-zhao-hit": {"src":"portraits/final-mainland/chen-zhao-hit.jpg","alt":"赵琛肖像","source":{"label":"肖像来源 · 赵琛个人学术主页","url":"https://zhao-chen.com/","kind":"profile","checkedAt":"2026-08-30","supports":"赵琛人物身份与肖像"}},
  "zenglin-xu-fdu": {"src":"portraits/final-mainland/zenglin-xu-fdu.jpg","alt":"徐增林肖像","source":{"label":"肖像来源 · 复旦大学人工智能创新与产业研究院","url":"https://ai3.fudan.edu.cn/info/1075/1744.htm","kind":"official","checkedAt":"2026-08-30","supports":"徐增林人物身份与肖像"}},
  "jianke-zhu-zju": {"src":"portraits/final-mainland/jianke-zhu-zju.jpg","alt":"朱建科肖像","source":{"label":"肖像来源 · 浙江大学教师个人主页","url":"https://person.zju.edu.cn/jkzhu","kind":"official","checkedAt":"2026-08-30","supports":"朱建科人物身份与肖像"}},
};
