import type { Person, Source } from "./data";
import { nyuAaltoRosterPortraits2026 } from "./portrait-data-roster-expansion-nyu-aalto-2026";

const checkedAt = "2026-09-02";

const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({
  label,
  url,
  kind,
  checkedAt,
  supports,
});

const aaltoRoster = source(
  "Aalto Department of Computer Science people roster",
  "https://www.aalto.fi/en/department-of-computer-science/people",
  "official",
  "Current departmental roster membership and faculty category",
);

const nyuCdsRoster = source(
  "NYU Center for Data Science faculty roster",
  "https://cds.nyu.edu/people/faculty/",
  "official",
  "Current Joint Faculty or Associated Faculty roster membership",
);

type FactSeed = { label: string; value: string; source: "profile" | "secondary" | "roster" };

type Seed = {
  id: string;
  name: string;
  role: string;
  institution: "Aalto" | "NYU";
  region: "Europe" | "United States";
  area: string;
  tags: string[];
  summary: string;
  stage: Person["stage"];
  profileUrl: string;
  profileLabel: string;
  secondaryUrl: string;
  secondaryLabel: string;
  secondaryKind: Source["kind"];
  facts: FactSeed[];
  x: number;
  y: number;
};

function person(seed: Seed): Person {
  const profile = source(seed.profileLabel, seed.profileUrl, "official", "Current appointment, research areas, affiliations and portrait");
  const secondary = source(seed.secondaryLabel, seed.secondaryUrl, seed.secondaryKind, "Independent first-party confirmation of current role, research programme, group or career record");
  const roster = seed.institution === "Aalto" ? aaltoRoster : nyuCdsRoster;

  const facts = seed.facts.map((fact) => ({
    label: fact.label,
    value: fact.value,
    source: fact.source === "profile" ? profile : fact.source === "secondary" ? secondary : roster,
  }));
  const trainingFact = facts.find((fact) => /教育/.test(fact.label));
  if (!facts.some((fact) => fact.label === "教育与学术训练")) {
    if (trainingFact) {
      trainingFact.label = "教育与学术训练";
    } else {
      facts.push({
        label: "教育与学术训练",
        value: "本轮一手公开页面未给出足以逐项核验的学位与导师信息；该字段保留为后续论文/CV 反查项。",
        source: secondary,
      });
    }
  }
  if (facts.length < 4) {
    facts.push({
      label: "为什么值得关注",
      value: seed.summary,
      source: profile,
    });
  }

  return {
    id: seed.id,
    name: seed.name,
    role: seed.role,
    institution: seed.institution,
    region: seed.region,
    area: seed.area,
    tags: seed.tags,
    summary: seed.summary,
    facts,
    stage: seed.stage,
    category: "core",
    status: "current PI · official roster verified",
    sources: [profile, secondary, roster],
    x: seed.x,
    y: seed.y,
    primary: true,
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
    portrait: nyuAaltoRosterPortraits2026[seed.id],
  };
}

export const nyuAaltoRosterExpansionPeople2026: Person[] = [
  person({
    id: "qi-chen-aalto",
    name: "Qi Chen",
    role: "Assistant Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Trustworthy AI · Learning Theory · Generative Models",
    tags: ["可信 AI", "学习理论", "生成模型", "持续学习", "公平性"],
    summary: "Aalto 可信与高效 AI 青年 PI，研究分布外泛化、持续学习、公平性和生成模型。",
    stage: "emerging",
    profileUrl: "https://www.aalto.fi/en/people/qi-chen",
    profileLabel: "Aalto faculty profile — Qi Chen",
    secondaryUrl: "https://research.aalto.fi/en/persons/b09e8631-4c76-4bea-b5a9-610d1e3f43ea",
    secondaryLabel: "Aalto research portal — Qi Chen",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Assistant Professor，并进入 ELLIS Institute 名录。", source: "profile" },
      { label: "研究主线", value: "Trustworthy and efficient AI，重点研究 OOD generalization、robustness、data efficiency、fairness 与 generative models。", source: "profile" },
      { label: "方法特色", value: "从理论、算法到 AI for Science 应用研究先验知识的获取、调节与组合。", source: "profile" },
      { label: "为什么值得关注", value: "其方向连接学习理论、生成模型和可信部署，是 Aalto 新一代基础 AI 节点。", source: "roster" },
    ],
    x: 120,
    y: 120,
  }),
  person({
    id: "francesco-croce-aalto",
    name: "Francesco Croce",
    role: "Assistant Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Adversarial Robustness · LLM Safety · Reliable Evaluation",
    tags: ["对抗鲁棒性", "LLM 安全", "模型评测", "视觉语言模型"],
    summary: "Aalto 鲁棒机器学习 PI，研究对抗攻击、可靠评测以及 LLM 与视觉语言模型的安全性。",
    stage: "emerging",
    profileUrl: "https://www.aalto.fi/en/people/francesco-croce",
    profileLabel: "Aalto faculty profile — Francesco Croce",
    secondaryUrl: "https://research.aalto.fi/en/persons/4f7fa9ca-5f58-4374-a1cc-85887d511980",
    secondaryLabel: "Aalto research portal — Francesco Croce",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Assistant Professor，并进入 ELLIS Institute 名录。", source: "profile" },
      { label: "研究主线", value: "研究 adversarial robustness、模型安全与可靠评测，覆盖分类、分割和视觉语言模型。", source: "profile" },
      { label: "近期方向", value: "官方成果页列出 LLM jailbreak、自适应攻击、instruction following 与安全对齐研究。", source: "profile" },
      { label: "为什么值得关注", value: "其工作把经典对抗鲁棒性延伸到多模态模型和大语言模型安全。", source: "roster" },
    ],
    x: 270,
    y: 120,
  }),
  person({
    id: "azade-farshad-aalto",
    name: "Azade Farshad",
    role: "Assistant Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Medical Imaging · Generative Models · Computer Vision",
    tags: ["医学影像", "计算机视觉", "生成模型", "手术视频"],
    summary: "Aalto 医学视觉 PI，研究医学图像分割、手术视频理解、扩散模型与生成式影像。",
    stage: "emerging",
    profileUrl: "https://www.aalto.fi/en/people/azade-farshad",
    profileLabel: "Aalto faculty profile — Azade Farshad",
    secondaryUrl: "https://research.aalto.fi/en/persons/c3a8afe5-71f9-4c94-99f0-069e3e4a3f2d",
    secondaryLabel: "Aalto research portal — Azade Farshad",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Assistant Professor。", source: "profile" },
      { label: "研究主线", value: "Medical image analysis、surgical video understanding、segmentation 与 generative vision。", source: "profile" },
      { label: "近期方向", value: "官方成果页列出扩散式医学影像合成、手术视频生成和解剖结构约束学习。", source: "profile" },
      { label: "学术位置", value: "同时进入 Aalto 的 Machine Learning, Data Science and AI 以及 Health 交叉主题名录。", source: "roster" },
    ],
    x: 420,
    y: 120,
  }),
  person({
    id: "christian-guckelsberger-aalto",
    name: "Christian Guckelsberger",
    role: "Assistant Professor in Creative Technologies",
    institution: "Aalto",
    region: "Europe",
    area: "Creative AI · Human-Computer Interaction · Multi-Agent Systems",
    tags: ["创意 AI", "HCI", "多智能体", "游戏 AI", "招 PhD"],
    summary: "Aalto 创意 AI 与交互研究 PI，研究机器创造力、内在动机、多智能体交互和游戏智能。",
    stage: "emerging",
    profileUrl: "https://www.aalto.fi/en/people/christian-guckelsberger",
    profileLabel: "Aalto faculty profile — Christian Guckelsberger",
    secondaryUrl: "https://research.aalto.fi/en/persons/7ea3d995-146d-4630-977b-f0e36715faf4",
    secondaryLabel: "Aalto research portal — Christian Guckelsberger",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Assistant Professor in Creative Technologies，并领导 AIR group。", source: "profile" },
      { label: "研究主线", value: "Computational creativity、intrinsic motivation、human–AI interaction 与 multi-agent interaction。", source: "profile" },
      { label: "学术网络", value: "同时是 FCAI PI、ELLIS member，并在 Queen Mary University of London 担任 visiting scholar。", source: "profile" },
      { label: "招生状态", value: "个人页公开欢迎 Research Visit、Postdoc、PhD 与 MSc thesis 申请，并指向研究组申请流程。", source: "profile" },
    ],
    x: 570,
    y: 120,
  }),
  person({
    id: "perttu-hamalainen-aalto",
    name: "Perttu Hämäläinen",
    role: "Tenured Associate Professor of Computer Games",
    institution: "Aalto",
    region: "Europe",
    area: "Game AI · Human-Computer Interaction · Virtual Reality",
    tags: ["游戏 AI", "HCI", "虚拟现实", "机器学习", "LLM"],
    summary: "Aalto 游戏与交互智能 PI，研究玩家体验、智能游戏开发工具、虚拟现实和 AI 生成交互。",
    stage: "senior",
    profileUrl: "https://www.aalto.fi/en/people/perttu-hamalainen",
    profileLabel: "Aalto faculty profile — Perttu Hämäläinen",
    secondaryUrl: "https://users.aalto.fi/~hamalap5/",
    secondaryLabel: "Perttu Hämäläinen personal Aalto homepage",
    secondaryKind: "profile",
    facts: [
      { label: "当前任职", value: "Aalto tenured Associate Professor of Computer Games，并进入 Computer Science Visual Computing 名录。", source: "profile" },
      { label: "研究主线", value: "Gameplay innovation、player experience、game-development tools，方法基础包括 AI、ML、HCI 与 psychology。", source: "profile" },
      { label: "近期方向", value: "官方成果页覆盖用 LLM 分析玩家体验、AI 舞伴、虚拟现实玩家模拟与具身交互。", source: "profile" },
      { label: "为什么值得关注", value: "其研究把 AI 方法与游戏、虚拟现实和用户体验连接起来。", source: "roster" },
    ],
    x: 720,
    y: 120,
  }),
  person({
    id: "alex-jung-aalto",
    name: "Alex Jung",
    role: "Associate Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Machine Learning Theory · Signal Processing · Data Analysis",
    tags: ["机器学习理论", "信号处理", "统计", "数据分析", "HIIT"],
    summary: "Aalto 机器学习理论与数据分析 PI，研究学习何时可行、如何可行，并连接统计、信号处理和应用数学。",
    stage: "senior",
    profileUrl: "https://www.aalto.fi/en/people/alex-jung",
    profileLabel: "Aalto faculty profile — Alex Jung",
    secondaryUrl: "https://research.aalto.fi/fi/persons/de902574-7c85-4eb6-b950-e432be844c92",
    secondaryLabel: "Aalto research portal — Alex Jung",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Associate Professor，并隶属 Helsinki Institute for Information Technology。", source: "profile" },
      { label: "研究主线", value: "关注给定应用条件下机器学习何时可能、如何可能。", source: "profile" },
      { label: "方法背景", value: "官方专长覆盖 signal processing、statistics、applied mathematics、computational data analysis 与 theoretical CS。", source: "profile" },
      { label: "为什么值得关注", value: "其位置连接 Aalto AIML 与 large-scale computing/data analysis 两个研究板块。", source: "roster" },
    ],
    x: 870,
    y: 120,
  }),
  person({
    id: "juho-kannala-aalto",
    name: "Juho Kannala",
    role: "Associate Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Computer Vision · Machine Learning",
    tags: ["计算机视觉", "机器学习", "三维视觉", "视觉表征"],
    summary: "Aalto 计算机视觉与机器学习教授，是该校视觉学习与三维感知方向的重要 PI。",
    stage: "senior",
    profileUrl: "https://www.aalto.fi/en/people/juho-kannala",
    profileLabel: "Aalto faculty profile — Juho Kannala",
    secondaryUrl: "https://research.aalto.fi/en/persons/9c92cddd-7f3a-4cad-abf3-f73e59c07c78",
    secondaryLabel: "Aalto research portal — Juho Kannala",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Associate Professor。", source: "profile" },
      { label: "研究主线", value: "官方专长明确列为 computer vision 与 machine learning。", source: "profile" },
      { label: "研究位置", value: "进入 Aalto Computer Science faculty roster，是视觉计算相关 PI 节点。", source: "roster" },
      { label: "为什么值得关注", value: "其研究位于视觉感知、机器学习与三维场景理解的交叉点。", source: "secondary" },
    ],
    x: 120,
    y: 300,
  }),
  person({
    id: "juhi-kulshrestha-aalto",
    name: "Juhi Kulshrestha",
    role: "Assistant Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Computational Social Science · Social Computing · Responsible AI",
    tags: ["计算社会科学", "社会计算", "数字伦理", "生成式 AI", "多模态"],
    summary: "Aalto 计算社会科学 PI，研究社会计算、数字伦理、在线信息行为以及生成式 AI 的社会影响。",
    stage: "emerging",
    profileUrl: "https://www.aalto.fi/en/people/juhi-kulshrestha",
    profileLabel: "Aalto faculty profile — Juhi Kulshrestha",
    secondaryUrl: "https://research.aalto.fi/en/persons/9cfea09c-abdf-40fe-9426-1292970e5eda",
    secondaryLabel: "Aalto research portal — Juhi Kulshrestha",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Assistant Professor。", source: "profile" },
      { label: "研究主线", value: "Computational social science 与 social computing，关注在线行为、信息生态和社会影响。", source: "profile" },
      { label: "近期方向", value: "官方成果页包含有害多模态内容识别、ChatGPT 使用差异和生成式 AI 回避行为研究。", source: "profile" },
      { label: "学术位置", value: "同时进入 Digital Ethics, Society and Policy、Society and Networks 与 Health 研究板块。", source: "roster" },
    ],
    x: 270,
    y: 300,
  }),
  person({
    id: "harri-lahdesmaki-aalto",
    name: "Harri Lähdesmäki",
    role: "Tenured Associate Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Probabilistic Machine Learning · Computational Biology · Generative Models",
    tags: ["概率机器学习", "生成模型", "计算生物学", "生物信息学"],
    summary: "Aalto 概率机器学习与计算系统生物学 PI，研究深度生成模型及其在生物医学中的应用。",
    stage: "senior",
    profileUrl: "https://www.aalto.fi/en/people/harri-lahdesmaki",
    profileLabel: "Aalto faculty profile — Harri Lähdesmäki",
    secondaryUrl: "https://research.cs.aalto.fi/csb/",
    secondaryLabel: "Aalto Computational Systems Biology group",
    secondaryKind: "profile",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science tenured Associate Professor。", source: "profile" },
      { label: "研究组", value: "领导 Computational Systems Biology research group。", source: "profile" },
      { label: "研究主线", value: "Probabilistic ML、deep generative models、AI、computational biology 与 bioinformatics。", source: "profile" },
      { label: "为什么值得关注", value: "其团队把方法型机器学习与分子生物学和生物医学问题连接起来。", source: "roster" },
    ],
    x: 420,
    y: 300,
  }),
  person({
    id: "jussi-rintanen-aalto",
    name: "Jussi Rintanen",
    role: "Associate Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Automated Planning · Constraint Solving · Decision Making",
    tags: ["自动规划", "约束求解", "决策", "软件自动化", "AI"],
    summary: "Aalto 自动规划与约束求解资深研究者，研究智能软件合成和部分可观测决策。",
    stage: "senior",
    profileUrl: "https://www.aalto.fi/en/people/jussi-rintanen",
    profileLabel: "Aalto faculty profile — Jussi Rintanen",
    secondaryUrl: "https://research.aalto.fi/en/persons/503f6d13-62e7-4f51-9804-febc0180d384",
    secondaryLabel: "Aalto research portal — Jussi Rintanen",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Associate Professor。", source: "profile" },
      { label: "研究主线", value: "Constraint-based planning and decision making、intelligent software synthesis 与 automated software production。", source: "profile" },
      { label: "教育与任职", value: "1997 年获 Helsinki University of Technology 博士；2005 年在 Freiburg 获 venia legendi，并曾任职 NICTA / ANU。", source: "profile" },
      { label: "为什么值得关注", value: "其工作连接经典 AI planning、SAT/constraint methods 与软件自动化。", source: "secondary" },
    ],
    x: 570,
    y: 300,
  }),
  person({
    id: "juho-rousu-aalto",
    name: "Juho Rousu",
    role: "Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Machine Learning · Structured Prediction · Computational Biology",
    tags: ["机器学习", "结构化预测", "核方法", "图数据", "计算生物学"],
    summary: "Aalto 结构化机器学习教授，研究核方法、稀疏学习和图数据，并应用于生物医学与合成生物学。",
    stage: "senior",
    profileUrl: "https://www.aalto.fi/en/people/juho-rousu",
    profileLabel: "Aalto faculty profile — Juho Rousu",
    secondaryUrl: "https://research.aalto.fi/en/persons/e9555bcc-f6c2-45f0-adeb-c69d3318a348",
    secondaryLabel: "Aalto research portal — Juho Rousu",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Professor。", source: "profile" },
      { label: "研究主线", value: "Structured prediction、kernel methods、regularised and sparse learning、graph and network data。", source: "profile" },
      { label: "应用方向", value: "重点应用于 metabolomics、biomedicine、pharmacology 与 synthetic biology。", source: "profile" },
      { label: "为什么值得关注", value: "其工作连接机器学习方法、图结构数据与生命科学应用。", source: "roster" },
    ],
    x: 720,
    y: 300,
  }),
  person({
    id: "aki-vehtari-aalto",
    name: "Aki Vehtari",
    role: "Academy Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Bayesian Modeling · Probabilistic Programming · Gaussian Processes",
    tags: ["贝叶斯", "概率编程", "高斯过程", "模型诊断", "ELLIS"],
    summary: "Aalto 贝叶斯计算建模带头人，研究 Bayesian workflow、概率编程、推断与模型诊断。",
    stage: "institute",
    profileUrl: "https://www.aalto.fi/en/people/aki-vehtari",
    profileLabel: "Aalto faculty profile — Aki Vehtari",
    secondaryUrl: "https://research.aalto.fi/en/persons/35c26d6c-a576-4baf-ac3a-96a4201686b3",
    secondaryLabel: "Aalto research portal — Aki Vehtari",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Academy Professor，并进入 ELLIS Institute 名录。", source: "profile" },
      { label: "研究组", value: "领导 Bayesian workflow group，并进入 Probabilistic Machine Learning 研究组。", source: "profile" },
      { label: "研究主线", value: "Bayesian workflow、probabilistic programming、Laplace/EP/VB/MC inference、模型诊断与 Gaussian processes。", source: "profile" },
      { label: "为什么值得关注", value: "其研究覆盖从统计推断到可复现 Bayesian workflow 的完整方法链。", source: "secondary" },
    ],
    x: 870,
    y: 300,
  }),
  person({
    id: "johanna-viitanen-aalto",
    name: "Johanna Viitanen",
    role: "Associate Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Human-Computer Interaction · Health Informatics · User Experience",
    tags: ["HCI", "健康信息学", "用户体验", "人本设计"],
    summary: "Aalto 医疗 HCI 教授，研究健康信息系统、临床用户体验和人本数字医疗设计。",
    stage: "senior",
    profileUrl: "https://www.aalto.fi/en/people/johanna-viitanen",
    profileLabel: "Aalto faculty profile — Johanna Viitanen",
    secondaryUrl: "https://research.aalto.fi/en/persons/0b505fca-d4c4-44a8-a2c1-e99af1136629",
    secondaryLabel: "Aalto research portal — Johanna Viitanen",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Associate Professor。", source: "profile" },
      { label: "研究主线", value: "Usability、human-centred design、user and patient experience、health information systems 与 health informatics。", source: "profile" },
      { label: "近期方向", value: "官方成果页持续研究电子病历、医患沟通、医院数字服务和临床工作流体验。", source: "profile" },
      { label: "为什么值得关注", value: "其工作提供了医疗 AI 与数字健康系统的人本评估入口。", source: "roster" },
    ],
    x: 120,
    y: 480,
  }),
  person({
    id: "robin-welsch-aalto",
    name: "Robin Welsch",
    role: "Assistant Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Human-Computer Interaction · Engineering Psychology · Generative AI",
    tags: ["HCI", "工程心理学", "生成式 AI", "人机共创", "VR"],
    summary: "Aalto HCI 与工程心理学 PI，研究生成式 AI 共创、虚拟现实和人类认知与交互。",
    stage: "emerging",
    profileUrl: "https://www.aalto.fi/en/people/robin-welsch",
    profileLabel: "Aalto faculty profile — Robin Welsch",
    secondaryUrl: "https://research.aalto.fi/fi/persons/78751b5a-fd7e-48bb-be99-21d702b61d01",
    secondaryLabel: "Aalto research portal — Robin Welsch",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Assistant Professor。", source: "profile" },
      { label: "研究主线", value: "Human–computer interaction、engineering psychology、VR 与 human–AI co-creation。", source: "profile" },
      { label: "近期方向", value: "官方项目页描述面向现场音乐的人机共同创作生成式音频 AI。", source: "profile" },
      { label: "学术位置", value: "同时进入 Engineering Psychology、HCID 与 HCI/Graphics/Games 研究板块。", source: "roster" },
    ],
    x: 270,
    y: 480,
  }),
  person({
    id: "deepika-yadav-aalto",
    name: "Deepika Yadav",
    role: "Assistant Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Human-Computer Interaction · Health and Wellbeing · Wearables",
    tags: ["HCI", "健康科技", "可穿戴", "交互设计", "女性健康"],
    summary: "Aalto 健康 HCI 青年 PI，研究身体体验、柔性可穿戴、女性健康和以用户为中心的数字医疗。",
    stage: "emerging",
    profileUrl: "https://www.aalto.fi/en/people/deepika-yadav",
    profileLabel: "Aalto faculty profile — Deepika Yadav",
    secondaryUrl: "https://www.aalto.fi/en/department-of-computer-science/people",
    secondaryLabel: "Aalto Department of Computer Science people roster",
    secondaryKind: "official",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science Assistant Professor。", source: "profile" },
      { label: "教育与任职", value: "获 IIIT Delhi 博士，加入 Aalto 前在 KTH 与 Stockholm University 开展 Digital Futures 博士后研究。", source: "profile" },
      { label: "研究主线", value: "HCI and interaction design for health and wellbeing，涵盖 soma design、wearables、haptics 与 embodied experience。", source: "profile" },
      { label: "为什么值得关注", value: "其研究把机器学习、柔性可穿戴和女性健康的人本需求连接起来。", source: "secondary" },
    ],
    x: 420,
    y: 480,
  }),
  person({
    id: "bo-zhao-aalto",
    name: "Bo Zhao",
    role: "Tenure-track Assistant Professor",
    institution: "Aalto",
    region: "Europe",
    area: "Machine Learning Systems · Data Management · Distributed Systems",
    tags: ["机器学习系统", "分布式系统", "数据管理", "基础模型", "招 PhD"],
    summary: "Aalto 机器学习系统 PI，研究可扩展 ML、分布式数据管理与软硬件协同效率。",
    stage: "emerging",
    profileUrl: "https://www.aalto.fi/en/people/bo-zhao",
    profileLabel: "Aalto faculty profile — Bo Zhao",
    secondaryUrl: "https://zbjob.github.io/",
    secondaryLabel: "Bo Zhao personal homepage",
    secondaryKind: "profile",
    facts: [
      { label: "当前任职", value: "Aalto Department of Computer Science tenure-track Assistant Professor，并隶属 FCAI 与 HIIT。", source: "profile" },
      { label: "研究主线", value: "Scalable ML systems、distributed data management、code optimization 与 data-intensive decision systems。", source: "profile" },
      { label: "教育与学术训练", value: "在 Humboldt-Universität zu Berlin 获博士学位，官方个人页明确写明由 Matthias Weidlich 指导。", source: "profile" },
      { label: "招生状态", value: "官方个人页公开 PhD 与 Intern openings，并链接独立 vacancies 页面。", source: "profile" },
    ],
    x: 570,
    y: 480,
  }),
  person({
    id: "andrew-gordon-wilson-nyu",
    name: "Andrew Gordon Wilson",
    role: "Professor of Computer Science and Data Science",
    institution: "NYU",
    region: "United States",
    area: "Probabilistic Machine Learning · Bayesian Deep Learning · Gaussian Processes",
    tags: ["概率机器学习", "贝叶斯深度学习", "高斯过程", "深度学习理论", "招 PhD"],
    summary: "NYU 概率机器学习教授，研究贝叶斯深度学习、高斯过程、泛化理论与自主智能系统。",
    stage: "senior",
    profileUrl: "https://cds.nyu.edu/team/andrew-wilson/",
    profileLabel: "NYU CDS faculty profile — Andrew Gordon Wilson",
    secondaryUrl: "https://cims.nyu.edu/~andrewgw/",
    secondaryLabel: "Andrew Gordon Wilson personal NYU homepage",
    secondaryKind: "profile",
    facts: [
      { label: "当前任职", value: "NYU Professor of Computer Science and Data Science。", source: "profile" },
      { label: "研究主线", value: "Probabilistic modeling、Bayesian deep learning、Gaussian processes 与 foundations of machine learning。", source: "profile" },
      { label: "近期方向", value: "本人主页将 LLM/vision model understanding、scaling、uncertainty、distribution shift 与 scientific discovery 列为核心方向。", source: "secondary" },
      { label: "招生状态", value: "本人主页公开说明 2026–2027 申请周期重点招收深度学习理论与经验科学方向博士生。", source: "secondary" },
    ],
    x: 720,
    y: 480,
  }),
  person({
    id: "brian-mcfee-nyu",
    name: "Brian McFee",
    role: "Associate Professor of Music Technology and Data Science",
    institution: "NYU",
    region: "United States",
    area: "Music Information Retrieval · Machine Learning · Multimedia",
    tags: ["音乐信息检索", "机器学习", "推荐系统", "多媒体", "音频"],
    summary: "NYU 音乐信息检索与数据科学教授，开发用于分析音乐和多媒体数据的机器学习方法与工具。",
    stage: "senior",
    profileUrl: "https://cds.nyu.edu/team/brian-mcfee/",
    profileLabel: "NYU CDS faculty profile — Brian McFee",
    secondaryUrl: "https://bmcfee.github.io/",
    secondaryLabel: "Brian McFee personal homepage",
    secondaryKind: "profile",
    facts: [
      { label: "当前任职", value: "NYU Associate Professor of Music Technology and Data Science，连接 MARL 与 Center for Data Science。", source: "secondary" },
      { label: "研究主线", value: "Machine learning、music information retrieval、recommender systems 与 multimedia signal processing。", source: "profile" },
      { label: "研究工具", value: "本人主页维护 librosa 等音乐和音频分析开源软件，并公开多种音乐数据资源。", source: "secondary" },
      { label: "团队信息", value: "本人主页列出当前 Music Technology 与 Data Science 博士生以及博士校友。", source: "secondary" },
    ],
    x: 870,
    y: 480,
  }),
  person({
    id: "carlos-fernandez-granda-nyu",
    name: "Carlos Fernandez-Granda",
    role: "Associate Professor of Mathematics and Data Science",
    institution: "NYU",
    region: "United States",
    area: "Machine Learning · Scientific Imaging · Data-Driven Medicine",
    tags: ["机器学习", "科学成像", "医疗 AI", "气候", "逆问题"],
    summary: "NYU 数学与数据科学教授，研究机器学习方法及其在医学、气候和科学成像中的应用。",
    stage: "senior",
    profileUrl: "https://cds.nyu.edu/team/carlos-fernandez-granda-2/",
    profileLabel: "NYU CDS faculty profile — Carlos Fernandez-Granda",
    secondaryUrl: "https://math.nyu.edu/~cfgranda/",
    secondaryLabel: "Carlos Fernandez-Granda personal NYU homepage",
    secondaryKind: "profile",
    facts: [
      { label: "当前任职", value: "NYU Associate Professor of Mathematics and Data Science，隶属 Courant 与 Center for Data Science。", source: "secondary" },
      { label: "研究主线", value: "Machine learning 及其在 medicine、climate science 与 scientific imaging 中的应用。", source: "profile" },
      { label: "方法方向", value: "本人主页同时列出 denoising、inverse problems、data-driven medicine 与 AI-powered imaging。", source: "secondary" },
      { label: "研究组", value: "领导数据科学方法研究组，目标是设计并分析可用于科学问题的方法。", source: "secondary" },
    ],
    x: 120,
    y: 660,
  }),
  person({
    id: "joan-bruna-nyu",
    name: "Joan Bruna",
    role: "Professor of Computer Science and Data Science",
    institution: "NYU",
    region: "United States",
    area: "Machine Learning Theory · Signal Processing · High-Dimensional Statistics",
    tags: ["机器学习理论", "信号处理", "高维统计", "优化", "科学计算"],
    summary: "NYU 机器学习理论教授，研究优化、表示学习、高维统计及其在气候和地球物理中的应用。",
    stage: "senior",
    profileUrl: "https://cds.nyu.edu/team/joan-bruna-2/",
    profileLabel: "NYU CDS faculty profile — Joan Bruna",
    secondaryUrl: "https://cims.nyu.edu/~bruna/",
    secondaryLabel: "Joan Bruna personal NYU homepage",
    secondaryKind: "profile",
    facts: [
      { label: "当前任职", value: "NYU Full Professor of Computer Science and Data Science，并与 Mathematics 交叉任职。", source: "secondary" },
      { label: "研究主线", value: "Machine learning、signal processing 与 high-dimensional statistics。", source: "profile" },
      { label: "研究组", value: "隶属 CILVR，并共同创办 Math and Data group。", source: "secondary" },
      { label: "应用方向", value: "关注机器学习的数学基础，以及 geophysics 与 climate modeling 等 computational science 应用。", source: "secondary" },
    ],
    x: 270,
    y: 660,
  }),
];

export const nyuAaltoRosterExpansionDeferred2026 = [
  { name: "Stephane Deny", reason: "Aalto faculty page exposes no reliable single-person portrait; defer rather than publish an initial-based placeholder." },
  { name: "Vikas Kumar Garg", reason: "Current Aalto page confirms title but does not expose enough biography or research detail for the new-person quality gate." },
  { name: "Jouko Lampinen", reason: "Current Aalto page is too sparse to support three substantive profile facts." },
  { name: "Arno Solin", reason: "Current Aalto page confirms identity but is too sparse for a complete first-batch profile." },
] as const;
