import type { Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-01";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({
  label,
  url,
  kind,
  checkedAt,
  supports,
});

const sources = {
  sunOfficial: source(
    "清华大学计算机系 · 孙茂松",
    "https://www.cs.tsinghua.edu.cn/info/1121/3554.htm",
    "official",
    "教育经历、研究方向、标准制定、科研平台与学术服务",
  ),
  foundationCenter: source(
    "清华大学计算机系 · 基础模型研究中心",
    "https://www.cs.tsinghua.edu.cn/info/1088/5512.htm",
    "official",
    "中心组织结构及孙茂松、唐杰、刘知远、黄民烈的职责",
  ),
  liuOfficial: source(
    "清华大学计算机系 · 刘知远",
    "https://www.cs.tsinghua.edu.cn/info/1121/7037.htm",
    "official",
    "教育经历、研究方向、代表性成果与人才培养",
  ),
  liuThesis: source(
    "刘知远博士学位论文",
    "https://lzy.thunlp.org/publications/phd_thesis.pdf",
    "thesis",
    "论文致谢明确记录孙茂松的博士指导关系",
  ),
  tangOfficial: source(
    "清华大学计算机系 · 唐杰",
    "https://www.cs.tsinghua.edu.cn/info/1111/3486.htm",
    "official",
    "现职、教育经历、学术服务与研究方向",
  ),
  tangProfile: source(
    "唐杰 · KEG 个人主页",
    "https://keg.cs.tsinghua.edu.cn/persons/jietang/index.html",
    "profile",
    "研究项目、博士生与博士后名单及主页记录的后续去向",
  ),
  qiuThesis: source(
    "清华大学学位论文系统 · 裘捷中",
    "https://newetds.lib.tsinghua.edu.cn/qh/paper/summary?dbCode=ETDQH&sysId=273307",
    "thesis",
    "博士论文页面列唐杰为导师",
  ),
  zhuOfficial: source(
    "清华大学计算机系 · 朱军",
    "https://www.cs.tsinghua.edu.cn/info/1121/3551.htm",
    "official",
    "现职、教育经历、研究方向及学术服务",
  ),
  zhuBiography: source(
    "朱军 · Biography",
    "http://ml.cs.tsinghua.edu.cn/~jun/biography.shtml",
    "profile",
    "博士经历及张钹指导关系",
  ),
  zhuPeople: source(
    "清华大学机器学习组 · People",
    "http://ml.cs.tsinghua.edu.cn/~jun/people.shtml",
    "profile",
    "朱军研究组当前成员及历届博士、博士后校友名单",
  ),
  jianfeiHome: source(
    "陈键飞 · 清华大学个人主页",
    "http://ml.cs.tsinghua.edu.cn/~jianfei/",
    "profile",
    "现职、研究方向、教育经历与头像",
  ),
  chongxuanHome: source(
    "李崇轩 · 个人主页",
    "https://zhenxuan00.github.io/",
    "profile",
    "中国人民大学现职、研究方向及张钹、朱军共同指导关系",
  ),
  zhijieHome: source(
    "邓志杰 · 上海交通大学个人主页",
    "https://thudzj.github.io/",
    "profile",
    "上海交通大学现职、研究方向及张钹、朱军共同指导关系",
  ),
  fudanHistory: source(
    "复旦大学 · 自然语言处理实验室师生校友聚会",
    "https://news.fudan.edu.cn/2023/0527/c2610a135077/page.htm",
    "official",
    "吴立德对黄萱菁、邱锡鹏、林峰的学术指导及林峰的产业任职",
  ),
  fudanLab: source(
    "复旦大学自然语言处理实验室",
    "https://nlp.fudan.edu.cn/",
    "official",
    "吴立德创建实验室、实验室发展历史及 FudanNLP 平台",
  ),
};

const portrait = (id: string, alt: string, portraitSource: Source): NonNullable<Person["portrait"]> => ({
  src: `portraits/senior-core-network/${id}.jpg`,
  alt,
  source: portraitSource,
});

export const seniorCoreNetworkPortraits: Record<string, NonNullable<Person["portrait"]>> = {
  "jianfei-chen-thu": portrait("jianfei-chen-thu", "陈键飞公开学术头像", sources.jianfeiHome),
  "chongxuan-li-ruc": portrait("chongxuan-li-ruc", "李崇轩公开学术头像", sources.chongxuanHome),
  "zhijie-deng-sjtu": portrait("zhijie-deng-sjtu", "邓志杰公开学术头像", sources.zhijieHome),
};

export const seniorCoreNetworkPeople: Person[] = [
  {
    id: "jianfei-chen-thu",
    name: "陈键飞",
    role: "副教授 · 博士生导师",
    institution: "THU",
    region: "Mainland China",
    area: "高效机器学习 · 模型压缩 · 概率推断",
    tags: ["高效机器学习", "模型量化", "概率推断", "朱军博士谱系"],
    summary: "清华大学机器学习组独立 PI，研究高效机器学习、模型压缩和概率推断；清华机器学习组校友名录将其列为朱军培养的博士校友。",
    facts: [
      { label: "当前任职", value: "清华大学计算机系副教授、博士生导师。", source: sources.jianfeiHome },
      { label: "教育与学术训练", value: "2019 年获清华大学博士学位，2021 年加入清华大学任教。", source: sources.jianfeiHome },
      { label: "研究主线", value: "高效机器学习、量化神经网络、随机优化与概率推断。", source: sources.jianfeiHome },
      { label: "学术谱系", value: "清华机器学习组校友名录列其为朱军研究组博士校友。", source: sources.zhuPeople },
      { label: "为什么值得关注", value: "把朱军团队的概率机器学习积累延伸到基础模型高效训练与部署。", source: sources.jianfeiHome },
    ],
    stage: "emerging",
    category: "core",
    status: "current PI",
    sources: [sources.jianfeiHome, sources.zhuPeople],
    x: 850,
    y: 805,
    primary: true,
    lastVerifiedAt: checkedAt,
    introducedAt: checkedAt,
    portrait: seniorCoreNetworkPortraits["jianfei-chen-thu"],
  },
  {
    id: "chongxuan-li-ruc",
    name: "李崇轩",
    role: "长聘副教授 · 博士生导师",
    institution: "RUC",
    region: "Mainland China",
    area: "生成模型 · 扩散模型 · 基础模型",
    tags: ["生成模型", "扩散模型", "基础模型", "张钹—朱军共同谱系"],
    summary: "中国人民大学高瓴人工智能学院独立 PI，研究深度生成模型与基础模型；个人主页明确记录清华博士阶段由张钹与朱军共同指导。",
    facts: [
      { label: "当前任职", value: "中国人民大学高瓴人工智能学院长聘副教授、博士生导师。", source: sources.chongxuanHome },
      { label: "教育与学术训练", value: "清华大学博士，张钹与朱军共同指导。", source: sources.chongxuanHome },
      { label: "研究主线", value: "深度生成模型、扩散模型、概率建模与基础模型。", source: sources.chongxuanHome },
      { label: "团队来源", value: "清华机器学习组校友名录记录其 2019 年博士毕业后的学术去向。", source: sources.zhuPeople },
      { label: "为什么值得关注", value: "是张钹—朱军概率机器学习谱系在中国人民大学形成独立研究组的代表节点。", source: sources.chongxuanHome },
    ],
    stage: "emerging",
    category: "core",
    status: "current PI",
    sources: [sources.chongxuanHome, sources.zhuPeople],
    x: 830,
    y: 690,
    primary: true,
    lastVerifiedAt: checkedAt,
    introducedAt: checkedAt,
    portrait: seniorCoreNetworkPortraits["chongxuan-li-ruc"],
  },
  {
    id: "zhijie-deng-sjtu",
    name: "邓志杰",
    role: "副教授 · 博士生导师",
    institution: "SJTU",
    region: "Mainland China",
    area: "生成模型 · 贝叶斯方法 · 具身智能 · 可信机器学习",
    tags: ["生成模型", "贝叶斯学习", "具身智能", "可信机器学习", "张钹—朱军共同谱系"],
    summary: "上海交通大学独立 PI，研究生成模型、统计与贝叶斯方法、具身智能和可信机器学习；个人主页明确记录清华博士阶段由张钹与朱军共同指导。",
    facts: [
      { label: "当前任职", value: "上海交通大学副教授、博士生导师。", source: sources.zhijieHome },
      { label: "教育与学术训练", value: "2022 年获清华大学博士学位，张钹与朱军共同指导。", source: sources.zhijieHome },
      { label: "研究主线", value: "生成模型、谱方法与贝叶斯方法，并延伸到具身智能和可信机器学习。", source: sources.zhijieHome },
      { label: "团队来源", value: "清华机器学习组校友名录列其为 2022 届博士校友。", source: sources.zhuPeople },
      { label: "为什么值得关注", value: "把清华概率机器学习谱系拓展到上海交通大学，并连接生成式 AI、具身智能与可靠性研究。", source: sources.zhijieHome },
    ],
    stage: "emerging",
    category: "core",
    status: "current PI",
    sources: [sources.zhijieHome, sources.zhuPeople],
    x: 1040,
    y: 800,
    primary: true,
    lastVerifiedAt: checkedAt,
    introducedAt: checkedAt,
    portrait: seniorCoreNetworkPortraits["zhijie-deng-sjtu"],
  },
  {
    id: "yang-yang-tang-alumnus",
    name: "杨洋",
    role: "浙江大学 Assistant Professor（唐杰主页记录）",
    institution: "ZJU",
    region: "Mainland China",
    area: "Artificial Intelligence · Data Mining",
    tags: ["唐杰博士谱系", "学术去向待更新核验"],
    summary: "唐杰个人主页列出的博士生，并记录其后续进入浙江大学任教；本节点保留导师主页所载状态，不据此推断最新职称。",
    facts: [
      { label: "师承证据", value: "唐杰主页将 Yang Yang 列入 Ph.D. Students。", source: sources.tangProfile },
      { label: "主页所载去向", value: "Zhejiang University · Assistant Professor。", source: sources.tangProfile },
      { label: "数据边界", value: "当前未用第二个一手页面确认最新职称，因此不计入当前 PI 名录。", source: sources.tangProfile },
    ],
    stage: "adjacent",
    category: "adjacent",
    status: "导师主页记录的学术校友",
    sources: [sources.tangProfile],
    x: 965,
    y: 660,
    primary: false,
    lastVerifiedAt: checkedAt,
  },
  {
    id: "jing-zhang-tang-alumnus",
    name: "张静",
    role: "中国人民大学 Assistant Professor（唐杰主页记录）",
    institution: "RUC",
    region: "Mainland China",
    area: "Artificial Intelligence · Data Mining",
    tags: ["唐杰博士谱系", "学术去向待更新核验"],
    summary: "唐杰个人主页列出的博士生，并记录其后续进入中国人民大学任教；本节点保留导师主页所载状态，不据此推断最新职称。",
    facts: [
      { label: "师承证据", value: "唐杰主页将 Jing Zhang 列入 Ph.D. Students。", source: sources.tangProfile },
      { label: "主页所载去向", value: "Renmin University of China · Assistant Professor。", source: sources.tangProfile },
      { label: "数据边界", value: "当前未用第二个一手页面确认最新职称，因此不计入当前 PI 名录。", source: sources.tangProfile },
    ],
    stage: "adjacent",
    category: "adjacent",
    status: "导师主页记录的学术校友",
    sources: [sources.tangProfile],
    x: 930,
    y: 730,
    primary: false,
    lastVerifiedAt: checkedAt,
  },
  {
    id: "jiezhong-qiu-tang-student",
    name: "裘捷中",
    role: "清华大学博士校友",
    institution: "THU",
    region: "Mainland China",
    area: "Graph Neural Networks · Representation Learning",
    tags: ["图神经网络", "唐杰博士谱系"],
    summary: "清华学位论文系统明确列唐杰为其博士导师；作为具名学生节点进入图谱，避免把学生关系错误画成导师自环。",
    facts: [
      { label: "博士导师", value: "唐杰。", source: sources.qiuThesis },
      { label: "研究主题", value: "图表示学习与图神经网络。", source: sources.qiuThesis },
      { label: "导师名录", value: "唐杰主页将其列入 Ph.D. Students。", source: sources.tangProfile },
    ],
    stage: "adjacent",
    category: "adjacent",
    status: "博士校友",
    sources: [sources.qiuThesis, sources.tangProfile],
    x: 905,
    y: 610,
    primary: false,
    lastVerifiedAt: checkedAt,
  },
  {
    id: "haoxi-zhong-liu-student",
    name: "钟浩熙",
    role: "清华大学硕士校友",
    institution: "THU",
    region: "Mainland China",
    area: "Natural Language Processing · Knowledge Representation",
    tags: ["刘知远硕士谱系", "清华优秀硕士论文"],
    summary: "清华官方教师履历记录刘知远指导钟浩熙获得 2021 年清华大学优秀硕士学位论文；作为具名学生节点呈现培养关系。",
    facts: [
      { label: "硕士导师", value: "刘知远。", source: sources.liuOfficial },
      { label: "培养记录", value: "论文获 2021 年清华大学优秀硕士学位论文。", source: sources.liuOfficial },
      { label: "数据边界", value: "当前没有足够的一手资料确认其最新任职，因此不推断职业去向。", source: sources.liuOfficial },
    ],
    stage: "adjacent",
    category: "adjacent",
    status: "硕士校友",
    sources: [sources.liuOfficial],
    x: 945,
    y: 575,
    primary: false,
    lastVerifiedAt: checkedAt,
  },
  {
    id: "lin-feng-fudan-alumnus",
    name: "林峰",
    role: "钉钉副总裁 · 智能搜索负责人（复旦 2023 报道）",
    institution: "External",
    actualInstitution: "DingTalk",
    region: "Mainland China",
    area: "Natural Language Processing · Search",
    tags: ["吴立德学术指导", "搜索", "产业去向"],
    summary: "复旦官方报道记录其 2004 年加入复旦 NLP 实验室并在吴立德指导下学习，后进入产业界负责智能搜索。",
    facts: [
      { label: "学术训练", value: "2004 年加入复旦自然语言处理实验室，跟随吴立德学习。", source: sources.fudanHistory },
      { label: "报道所载去向", value: "钉钉副总裁、钉钉智能搜索负责人。", source: sources.fudanHistory },
      { label: "数据边界", value: "官方报道未明确其学位类别，因此关系保守标为“学术指导”，不升级为博士师承。", source: sources.fudanHistory },
    ],
    stage: "adjacent",
    category: "adjacent",
    status: "产业校友节点",
    sources: [sources.fudanHistory, sources.fudanLab],
    x: 850,
    y: 880,
    primary: false,
    lastVerifiedAt: checkedAt,
  },
];

export const seniorCoreNetworkPersonEnhancements: Record<string, Partial<Person>> = {
  "maosong-sun": {
    role: "教授 · 清华大学基础模型研究中心首席科学家",
    summary: "清华自然语言处理与基础模型研究的重要组织者：研究从中文分词、句法与语义分析延伸到知识图谱、预训练语言模型、大模型和计算人文，并通过 THUNLP、学堂在线与九歌等平台形成持续的人才和技术影响。",
    tags: ["中文信息处理", "NLP", "知识图谱", "预训练语言模型", "大模型", "计算人文", "THUNLP", "学术领导"],
    facts: [
      { label: "当前角色", value: "清华大学计算机系教授、基础模型研究中心首席科学家。", source: sources.foundationCenter },
      { label: "教育经历", value: "1986 年清华本科、1988 年清华硕士，2004 年获香港城市大学计算语言学博士。", source: sources.sunOfficial },
      { label: "研究演化", value: "从中文分词、句法语义分析发展到知识表示、预训练语言模型、大模型与计算人文。", source: sources.sunOfficial },
      { label: "标准与领域建设", value: "主持或参与两项 ISO 国际标准，长期推动中文信息处理与计算语言学共同体建设。", source: sources.sunOfficial },
      { label: "平台与公共产品", value: "公开履历列出学堂在线、诗歌生成系统“九歌”以及 THUNLP 开源工具与知识图谱项目。", source: sources.sunOfficial },
      { label: "可核验师承", value: "刘知远博士论文致谢明确记录孙茂松的指导。", source: sources.liuThesis },
      { label: "为什么值得关注", value: "他的影响不仅来自论文，也来自中文 NLP 的平台建设、标准制定和跨代人才培养。", source: sources.sunOfficial },
    ],
    sources: [sources.sunOfficial, sources.foundationCenter, sources.liuThesis],
    lastVerifiedAt: checkedAt,
  },
  "jie-tang-thu": {
    role: "教授 · 清华大学基础模型研究中心主任",
    summary: "清华 KEG 与基础模型研究中心核心负责人，研究横跨学术知识图谱、图学习、社会计算与大模型；其公开学生名录显示人才流向高校、基础研究机构和多家 AI 公司。",
    tags: ["知识图谱", "图机器学习", "社会计算", "AMiner", "GLM", "ChatGLM", "基础模型中心", "人才培养"],
    facts: [
      { label: "当前角色", value: "清华大学计算机系教授、基础模型研究中心主任。", source: sources.foundationCenter },
      { label: "教育经历", value: "2006 年获清华大学计算机科学与技术博士学位。", source: sources.tangOfficial },
      { label: "研究主线", value: "从学术社会网络与知识图谱、图表示学习，延伸到基础模型与大模型技术。", source: sources.tangProfile },
      { label: "代表性平台", value: "长期建设 AMiner/科技情报与知识图谱系统，并参与 GLM、ChatGLM 等基础模型工作。", source: sources.tangProfile },
      { label: "人才网络", value: "公开主页列出博士后、博士生和硕士生，并记录部分校友进入浙江大学、中国人民大学、BAAI、Google、Alibaba 与创业公司。", source: sources.tangProfile },
      { label: "为什么值得关注", value: "同时连接学术知识网络、国产基础模型、产业转化与跨机构人才流动，是理解中国大模型生态的重要枢纽。", source: sources.tangProfile },
    ],
    sources: [sources.tangOfficial, sources.tangProfile, sources.foundationCenter],
    lastVerifiedAt: checkedAt,
  },
  "zhiyuan-liu": {
    role: "教授 · 清华大学基础模型研究中心副主任",
    summary: "清华 THUNLP 的核心学术带头人之一，研究从知识图谱与关系抽取推进到预训练语言模型、开放知识表示和大模型；博士师承孙茂松，并持续参与基础模型研究中心建设。",
    tags: ["NLP", "知识图谱", "关系抽取", "OpenKE", "OpenNRE", "预训练语言模型", "大模型", "孙茂松博士谱系"],
    facts: [
      { label: "当前角色", value: "清华大学计算机系教授、基础模型研究中心副主任。", source: sources.foundationCenter },
      { label: "教育经历", value: "2006 年清华本科，2011 年获清华大学博士学位。", source: sources.liuOfficial },
      { label: "博士师承", value: "博士论文致谢明确记录孙茂松的指导。", source: sources.liuThesis },
      { label: "研究演化", value: "从知识图谱、语义计算和关系抽取，发展到预训练语言模型、开放知识表示与大模型。", source: sources.liuOfficial },
      { label: "开源影响", value: "围绕 OpenKE、OpenNRE 等开放平台形成知识表示与关系抽取工具链。", source: sources.liuOfficial },
      { label: "人才培养", value: "官方履历记录指导钟浩熙获得 2021 年清华大学优秀硕士学位论文。", source: sources.liuOfficial },
      { label: "为什么值得关注", value: "连接孙茂松的中文 NLP 谱系、清华知识工程传统与当前基础模型研究。", source: sources.liuOfficial },
    ],
    sources: [sources.liuOfficial, sources.liuThesis, sources.foundationCenter],
    lastVerifiedAt: checkedAt,
  },
  "jun-zhu-thu": {
    role: "博世人工智能冠名教授 · 清华大学人工智能研究院副院长",
    summary: "清华概率机器学习与生成式 AI 的关键带头人：博士阶段由张钹指导，研究从贝叶斯机器学习与概率编程扩展到深度生成模型、强化学习和 AI 安全，并培养出分布在清华、人大、上交等高校的独立 PI。",
    tags: ["概率机器学习", "贝叶斯学习", "生成模型", "强化学习", "AI 安全", "朱算", "天授", "张钹博士谱系", "人才培养"],
    facts: [
      { label: "当前角色", value: "清华大学博世人工智能冠名教授、人工智能研究院副院长。", source: sources.zhuOfficial },
      { label: "教育经历", value: "2005 年清华本科、2009 年清华博士。", source: sources.zhuOfficial },
      { label: "博士师承", value: "个人 Biography 明确记录博士论文导师为张钹。", source: sources.zhuBiography },
      { label: "研究演化", value: "从贝叶斯机器学习、概率图模型与概率编程，拓展到深度生成模型、强化学习和人工智能安全。", source: sources.zhuOfficial },
      { label: "开源与系统", value: "团队长期建设 ZhuSuan（朱算）概率编程与 Tianshou（天授）强化学习工具。", source: sources.zhuPeople },
      { label: "学术后继", value: "公开组页列出陈键飞、李崇轩、邓志杰等进入高校任教的博士校友。", source: sources.zhuPeople },
      { label: "为什么值得关注", value: "他把张钹的 AI 学术谱系推进到概率机器学习和生成式 AI，并形成可见的跨校独立 PI 网络。", source: sources.zhuPeople },
    ],
    sources: [sources.zhuOfficial, sources.zhuBiography, sources.zhuPeople],
    lastVerifiedAt: checkedAt,
  },
  "wulide-lineage": {
    role: "复旦大学自然语言处理实验室创始人",
    summary: "复旦自然语言处理与信息检索方向的奠基者：创建复旦 NLP 实验室并持续指导黄萱菁、邱锡鹏、林峰等后继者，其学术影响经 FudanNLP、院系教师和产业校友延续。",
    tags: ["复旦 NLP 实验室", "NLP", "信息检索", "中文信息处理", "FudanNLP", "人才培养", "奠基者"],
    facts: [
      { label: "领域建设", value: "创建复旦大学自然语言处理实验室；实验室是中国较早开展 NLP 与信息检索研究的团队之一。", source: sources.fudanLab },
      { label: "长期影响", value: "实验室发展跨越四十余年，并形成 FudanNLP 等公开研究与工具平台。", source: sources.fudanLab },
      { label: "学术后继", value: "复旦官方校庆报道明确提及其指导黄萱菁、邱锡鹏与林峰成长。", source: sources.fudanHistory },
      { label: "跨界流动", value: "林峰后来进入产业界负责智能搜索，显示该谱系从学术研究到搜索产品的延伸。", source: sources.fudanHistory },
      { label: "为什么值得关注", value: "理解复旦 NLP 并不能只从现任教师开始；吴立德是连接早期中文信息处理、当前实验室与产业校友的上游节点。", source: sources.fudanHistory },
    ],
    sources: [sources.fudanLab, sources.fudanHistory],
    lastVerifiedAt: checkedAt,
  },
};

const relation = (
  id: string,
  from: string,
  to: string,
  type: Relationship["type"],
  subtype: NonNullable<Relationship["subtype"]>,
  label: string,
  evidence: string,
  relationSource: Source,
): Relationship => ({ id, from, to, type, subtype, label, evidence, source: relationSource, verified: true });

export const seniorCoreNetworkRelationships: Relationship[] = [
  relation("senior-core-sun-tang-center", "maosong-sun", "jie-tang-thu", "collaboration", "sustained_collaboration", "基础模型中心：首席科学家 / 主任", "清华官方中心介绍列孙茂松为首席科学家、唐杰为主任；这是持续组织协作，不由单篇合著推断。", sources.foundationCenter),
  relation("senior-core-sun-huang-center", "maosong-sun", "minlie-huang", "collaboration", "sustained_collaboration", "基础模型中心：首席科学家 / 副主任", "清华官方中心介绍列孙茂松为首席科学家、黄民烈为副主任。", sources.foundationCenter),
  relation("senior-core-liu-huang-center", "zhiyuan-liu", "minlie-huang", "collaboration", "sustained_collaboration", "基础模型中心共同副主任", "清华官方中心介绍列刘知远、黄民烈共同担任副主任。", sources.foundationCenter),
  relation("senior-core-tang-yangyang", "jie-tang-thu", "yang-yang-tang-alumnus", "lineage", "phd_adviser", "博士导师", "唐杰主页将 Yang Yang 列为其博士生，并记录其后续浙江大学任教去向。", sources.tangProfile),
  relation("senior-core-tang-jingzhang", "jie-tang-thu", "jing-zhang-tang-alumnus", "lineage", "phd_adviser", "博士导师", "唐杰主页将 Jing Zhang 列为其博士生，并记录其后续中国人民大学任教去向。", sources.tangProfile),
  relation("senior-core-tang-jiezhongqiu", "jie-tang-thu", "jiezhong-qiu-tang-student", "lineage", "phd_adviser", "博士导师", "清华学位论文系统明确列唐杰为裘捷中的博士论文导师。", sources.qiuThesis),
  relation("senior-core-liu-haoxizhong", "zhiyuan-liu", "haoxi-zhong-liu-student", "lineage", "master_adviser", "硕士导师", "清华大学官方教师履历记录刘知远指导钟浩熙获得 2021 年清华大学优秀硕士学位论文。", sources.liuOfficial),
  relation("senior-core-zhu-jianfei", "jun-zhu-thu", "jianfei-chen-thu", "lineage", "phd_adviser", "博士导师", "清华机器学习组的博士校友名录将陈键飞列入朱军研究组，并记录其 2019 年博士毕业。", sources.zhuPeople),
  relation("senior-core-zhu-chongxuan", "jun-zhu-thu", "chongxuan-li-ruc", "lineage", "co_adviser", "共同博士导师", "李崇轩个人主页明确记录清华博士阶段由张钹和朱军共同指导。", sources.chongxuanHome),
  relation("senior-core-zhu-zhijie", "jun-zhu-thu", "zhijie-deng-sjtu", "lineage", "co_adviser", "共同博士导师", "邓志杰个人主页明确记录清华博士阶段由张钹和朱军共同指导。", sources.zhijieHome),
  relation("senior-core-wulide-linfeng", "wulide-lineage", "lin-feng-fudan-alumnus", "lineage", "other", "学术指导", "复旦官方报道记载林峰 2004 年加入复旦 NLP 实验室并跟随吴立德学习；报道没有注明具体学位类别，因此不升级为博士关系。", sources.fudanHistory),
];

export const seniorCoreNetworkPlacements: StudentPlacement[] = [
  { id: "senior-core-zhu-jianfei-academia", student: "陈键飞", teacherId: "jun-zhu-thu", company: "Tsinghua University", role: "Associate Professor", kind: "current", sector: "academia", degree: "PhD", graduationYear: 2019, source: sources.jianfeiHome, verifiedAt: checkedAt },
  { id: "senior-core-zhu-chongxuan-academia", student: "李崇轩", teacherId: "jun-zhu-thu", company: "Renmin University of China", role: "Tenured Associate Professor", kind: "current", sector: "academia", degree: "PhD", graduationYear: 2019, coAdvisers: ["张钹"], source: sources.chongxuanHome, verifiedAt: checkedAt },
  { id: "senior-core-zhu-zhijie-academia", student: "邓志杰", teacherId: "jun-zhu-thu", company: "Shanghai Jiao Tong University", role: "Associate Professor", kind: "current", sector: "academia", degree: "PhD", graduationYear: 2022, coAdvisers: ["张钹"], source: sources.zhijieHome, verifiedAt: checkedAt },
  { id: "senior-core-wulide-linfeng-industry", student: "林峰", teacherId: "wulide-lineage", company: "DingTalk", department: "Intelligent Search", role: "Vice President · Search Lead（复旦 2023 报道）", kind: "reported", sector: "industry", source: sources.fudanHistory, verifiedAt: checkedAt },
];
