import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

type PersonEnhancement = Partial<Pick<Person, "summary" | "tags" | "facts" | "sources" | "lastVerifiedAt" | "status" | "knownAlumniCount">>;

const checkedAt = "2026-08-28";
const official = (label: string, url: string, supports: string, asOf?: string): Source => ({ label, url, kind: "official", checkedAt, supports, asOf });
const profile = (label: string, url: string, supports: string, asOf?: string): Source => ({ label, url, kind: "profile", checkedAt, supports, asOf });
const cv = (label: string, url: string, supports: string, asOf?: string): Source => ({ label, url, kind: "cv", checkedAt, supports, asOf });
const fact = (label: string, value: string, source: Source) => ({ label, value, source });

const s = {
  ng: official("NUS personal page", "https://www.comp.nus.edu.sg/~nght/", "education, research, editorial service and recruiting status"),
  ngPeople: official("NUS NLP people and alumni", "https://www.comp.nus.edu.sg/~nlp/people.html", "named students, alumni years and public destinations"),
  kan: official("Min-Yen Kan personal page", "https://www.comp.nus.edu.sg/~kanmy/index.html", "roles, research agenda and recent work", "2026-08-23"),
  kanCv: cv("Min-Yen Kan one-page CV", "https://www.comp.nus.edu.sg/~kanmy/cv.1page.html", "education and PhD advisers"),
  chua: profile("Tat-Seng Chua personal page", "https://www.chuatatseng.com/", "career, projects, supervision and entrepreneurship"),
  chuaNus: official("NUS faculty profile", "https://www.comp.nus.edu.sg/cs/people/chuats/", "current appointment and research"),
  shieh: official("NUS faculty profile", "https://www.comp.nus.edu.sg/cs/people/mshieh/", "education, Google research career and research themes"),
  shiehPersonal: profile("Michael Qizhe Shieh homepage", "https://michaelshieh.com/", "publications, team and research updates"),
  kenji: official("NUS faculty profile", "https://www.comp.nus.edu.sg/cs/people/kenji/", "education, Harvard postdoc and current appointment"),
  kenjiLab: profile("NUS Machine Learning Lab", "https://ml.comp.nus.edu.sg/", "research group and recruiting status"),
  xiao: official("NUS faculty profile", "https://www.comp.nus.edu.sg/cs/people/xiaojc/", "2026 start date, education, mentors and research"),
  xiaoNews: official("NUS new faculty 2026", "https://www.comp.nus.edu.sg/news/nus-school-of-computing-welcomes-17-new-faculty-members/", "2026 appointment and research overview", "2026"),
  you: official("NUS faculty profile", "https://www.comp.nus.edu.sg/cs/people/youy/", "education and large-scale training research"),
  youNews: official("NUS new faculty profile", "https://www.comp.nus.edu.sg/news/2020-new-faculty2/", "2020 NUS start and research record", "2020"),
  hooi: profile("Bryan Hooi homepage", "https://bhooi.github.io/", "education, adviser and language-model research"),
  hooiNus: official("NUS faculty profile", "https://www.comp.nus.edu.sg/cs/people/bhooi/", "current appointment and official research areas"),
  joty: profile("Shafiq Joty homepage", "https://raihanjoty.github.io/index.html", "education, dated career history and research"),
  jotyStudents: profile("Shafiq Joty students", "https://raihanjoty.github.io/students.html", "named students, graduation years and destinations", "2026"),
  sun: profile("Aixin Sun biography", "https://personal.ntu.edu.sg/axsun/bio.html", "education, appointments and research"),
  sunDmal: official("NTU DMAL people", "https://www.ntu.edu.sg/dmal/about-us/our-people", "NTU appointment and UNSW postdoc"),
  luu: profile("Anh Tuan Luu homepage", "https://tuanluu.github.io/index.html", "education, MIT mentor, research and recruiting"),
  luuNtu: official("NTU GrAIL people", "https://www.ntu.edu.sg/computing/research/institutes-centres/grail/our-people", "current appointment and research"),
  wang: profile("Wenya Wang homepage", "https://personal.ntu.edu.sg/wangwy/", "PhD adviser, UW postdoc mentors, research and recruiting"),
  wangNtu: official("NTU faculty profile", "https://www.ntu.edu.sg/computing/about-us/faculty-directory/detail/wenya-wang", "current appointment and research"),
  cambria: official("NTU Multi-Net Lab profile", "https://blogs.ntu.edu.sg/multi-net-lab/erik-cambria-5/", "education, industry history, startups and research"),
  cambriaNtu: official("NTU scholar session", "https://www.ntu.edu.sg/computing/news-events/news/detail/ccds-connect-2025---scholar-session--deep-thinking--big-questions--and-the-future-of-ai", "2025 chair role and research outlook", "2025"),
  an: official("Bo An homepage", "https://personal.ntu.edu.sg/boan/", "education, career, deployment and research"),
  anCv: cv("Bo An CV", "https://personal.ntu.edu.sg/boan/CV-BOAN.pdf", "dated education and employment history"),
  weiLu: official("NTU new faculty 2025", "https://www.ntu.edu.sg/computing/our-faculty/new-faculty-at-ccds-%282025%29", "September 2025 NTU start and prior SUTD tenure", "2025"),
  weiLuNus: official("NUS NLP alumni", "https://www.comp.nus.edu.sg/~nlp/people.html", "2009 PhD under Hwee Tou Ng and alumni destinations"),
  poria: profile("DeCLaRe Lab", "https://declare-lab.net/", "lab, people and multimodal conversational AI"),
  poriaNtu: official("NTU ROSE people", "https://www.ntu.edu.sg/rose/about-us/our-people", "current NTU appointment"),
  zhang: official("SUTD faculty profile", "https://www.sutd.edu.sg/profile/zhang-wenxuan", "PhD adviser, Alibaba career, appointment and research"),
  zhangPersonal: profile("Wenxuan Zhang homepage", "https://isakzhang.github.io/", "projects, lab and research updates"),
  deng: official("SMU faculty profile", "https://faculty.smu.edu.sg/profile/deng-yang-7801", "current appointment, education and research"),
  dengPersonal: profile("CHAT NLP Group", "https://dengyang17.github.io/", "PhD adviser, NUS postdoc mentors, team and projects"),
  maYunshan: official("SMU faculty profile", "https://faculty.smu.edu.sg/profile/ma-yunshan-7956", "current appointment and research"),
  maYunshanCv: cv("Yunshan Ma CV", "https://computing.smu.edu.sg/sites/scis.smu.edu.sg/files/2026-02/ysma-CV.pdf", "dated education and employment", "2026-02"),
  jiang: official("SMU faculty profile", "https://faculty.smu.edu.sg/profile/jing-jiang-636", "SMU leave status and research"),
  jiangCv: cv("Jing Jiang CV", "https://computing.smu.edu.sg/sites/scis.smu.edu.sg/files/2023-08/jingjiang-2023-cv.pdf", "education and dated SMU promotion history", "2023-08"),
  chen: official("A*STAR I2R profile", "https://www.a-star.edu.sg/i2r/i2r-profiles/nancychen", "education, leadership, projects and supervision"),
  chenEdu: official("A*STAR AI for Education", "https://www.a-star.edu.sg/i2r/centres-programmes/ai-for-education", "AI4Edu programme and 2022 spin-offs"),
  aw: official("A*STAR researcher profile", "https://research.a-star.edu.sg/researcher/aiti-aw/", "leadership, MERaLiON and Southeast Asian language research"),
  meralion: official("AI Singapore MERaLiON", "https://aisingapore.org/aiproducts/meralion/", "national multimodal language-model programme and public model family"),
  su: official("A*STAR researcher profile", "https://research.a-star.edu.sg/researcher/jian-su/", "leadership roles, projects and deployments"),
  suResearch: official("A*STAR Research feature", "https://research.a-star.edu.sg/articles/highlights/artificial-intelligence-that-knows-how-you-feel/", "Jian Su-led NLP group and conversation emotion work", "2022"),

  kong: official("HKU faculty profile", "https://ai.hku.hk/people/academic-staff/lpk", "current appointment and research"),
  kongLaw: official("HKU LawTech profile", "https://www.lawtech.hku.hk/people/lingpeng-kong/", "PhD co-advisers and DeepMind career"),
  tao: official("HKU IDS profile", "https://datascience.hku.hk/people/tao-yu/", "appointment, XLANG and research"),
  taoPersonal: profile("Tao Yu homepage", "https://taoyds.github.io/", "education, advisers and research projects"),
  qi: official("HKU AI profile", "https://www.ai.hku.hk/people/academic-staff/liuqi", "education, industry career, Reka and research"),
  qiPdf: official("HKU faculty introduction", "https://www.hku.hk/f/upload/26258/Dr%20Qi%20Liu.pdf", "Oxford PhD, NUS MSc and industry background"),
  chao: official("HKU IDS profile", "https://datascience.hku.hk/people/chao-huang/", "education, Data Intelligence Lab and research"),
  chaoAi: official("HKU AI profile", "https://www.ai.hku.hk/people/academic-staff/chuang", "appointment and open-source agent/RAG work"),
  fung: official("HKUST ECE profile", "https://ece.hkust.edu.hk/pascale", "current role and research"),
  fungBio: official("HKUST Rising Stars biography", "https://risingstarsasia2018.hkust.edu.hk/speaker_detail.php?id=27", "Columbia PhD and dated industrial research career", "2018"),
  dekai: official("HKUST faculty profile", "https://facultyprofiles.hkust.edu.hk/profiles.php?profile=dekai-wu-dekai", "education, 1992 appointment and research"),
  dekaiPersonal: profile("De Kai homepage", "https://cse.hkust.edu.hk/faculty/dekai/", "career and early statistical machine translation work"),
  song: profile("Yangqiu Song homepage", "https://cse.hkust.edu.hk/~yqsong/", "education, dated career, industry visits and projects"),
  songHkust: official("HKUST faculty profile", "https://cse.hkust.edu.hk/admin/people/faculty/profile/yqsong", "current appointment and research"),
  he: official("HKUST faculty profile", "https://cse.hkust.edu.hk/admin/people/faculty/profile/junxianh", "education, current students and research", "2026-08-25"),
  heCmu: official("CMU LTI alumni", "https://www.lti.cs.cmu.edu/people/alumni/alumni-2022/he-junxian.html", "2022 PhD and academic adviser", "2022"),
  guo: profile("Song Guo homepage", "https://cse.hkust.edu.hk/~songguo/index.html", "education, career, lab and recruiting"),
  guoPortal: official("HKUST research portal", "https://researchportal.hkust.edu.hk/en/persons/song-guo/", "current appointment and research"),
  wong: official("CUHK SEEM brochure 2025", "https://www.se.cuhk.edu.hk/wp-content/uploads/2025/09/2025-SEEM-Brochure_final.pdf", "education, appointment and research", "2025"),
  wongCuhk: official("CUHK faculty profile", "https://www.se.cuhk.edu.hk/people/academic-staff/", "current appointment and research"),
  king: profile("Irwin King homepage", "https://www.cse.cuhk.edu.hk/irwin.king/", "education, career, leadership and research"),
  kingLab: profile("CUHK MISC Lab people", "https://misc-lab.cse.cuhk.edu.hk/people/", "current team and alumni"),
  cheng: official("CUHK CSE profile", "https://www.cse.cuhk.edu.hk/people/faculty/yu-cheng/", "education, 2024 appointment and dated industry career"),
  chengPersonal: profile("Yu Cheng homepage", "https://yucheng.research.googlepages.com/", "publications and research"),
  maWeiying: official("CityU HKIAS lecture", "https://www.hkias.cityu.edu.hk/en/news-and-media/e-newsletter/issue-16/ais-transformative-power-scientific-exploration-0", "2024 Tsinghua role, ByteDance history and AI-for-science work", "2024-06-11"),
  maWeiyingCityu: official("CityU College recognitions", "https://www.cityu.edu.hk/cc/about-us/recognitions", "CityU affiliation record"),
  maChen: profile("Chen Ma homepage", "https://allenjack.github.io/", "education, 2021/2026 appointments, research and recruiting"),
  maChenCityu: official("CityU CS academic staff", "https://www.cs.cityu.edu.hk/en/people/academic-staff", "current Associate Professor title"),
  dengXiaotie: official("CityU CS academic staff", "https://www.cs.cityu.edu.hk/en/people/academic-staff", "education, chair title and LLM multi-agent research"),
  dengXiaotieProfile: official("CityU faculty profile", "https://www.cityu.edu.hk/stfprofile/xiaotie.htm", "career and algorithmic game theory research"),
  liZhenjiang: profile("Zhenjiang Li homepage", "https://www.cs.cityu.edu.hk/~zhenjili/", "education, lab, LLM systems and named alumni destinations"),
  liZhenjiangCityu: official("CityU faculty profile", "https://www.cityu.edu.hk/stfprofile/zhenjiangli.htm", "current appointment and research"),
  liWenjie: official("PolyU Cognitive Computing Lab", "https://coglab.comp.polyu.edu.hk/person10.html", "1997 PhD and research"),
  liWenjieGroup: profile("PolyU NLP Group", "https://www4.comp.polyu.edu.hk/~cswjli/Group.html", "team and named alumni destinations"),
  liJing: official("PolyU faculty profile", "https://www.polyu.edu.hk/comp/people/academic-staff/prof-li-jing-amelia/", "education, 2017-2019 Tencent career and 2019 PolyU start"),
  liJingPersonal: profile("Jing Li homepage", "https://www4.comp.polyu.edu.hk/~jing1li/", "2025 promotion, Embodied AI Lab and research projects"),
  yangHongxia: official("PolyU scholars CV", "https://research.polyu.edu.hk/ws/portalfiles/portal/cv/587d5524-6d74-4888-8712-633e50c26412?locale=en_GB", "education and 2024 PolyU appointment", "2026"),
  yangHongxiaNews: official("PolyU named professorship", "https://www.polyu.edu.hk/comp/news-and-events/news/2026/0512_prof-yang-hongxia-vobile-group-professor/", "2026 named chair, industry leadership and Co-GenAI project", "2026-05-12"),
  cao: official("PolyU DSAI profile", "https://www.polyu.edu.hk/dsai/people/academic-staff/cao-liangliang/?sc_lang=en", "education, startup and Google/Apple/DeepMind career"),
  caoNews: official("PolyU appointment news", "https://www.polyu.edu.hk/dsai/news-and-events/news/2026/20260630-welcome-cao-liangliang/", "2026 arrival", "2026-06-29"),
  fan: official("PolyU faculty profile", "https://www.polyu.edu.hk/comp/people/academic-staff/prof-fan-wenqi/?sc_lang=en", "education, 2020 PhD, postdoc and appointment"),
  fanMm: official("PolyU Management profile", "https://www.polyu.edu.hk/mm/people/academic-staff/dr-wenqi-fan/", "2020-2023 postdoc/RAP history and current LLM research"),
  huang: profile("Xiao Huang homepage", "https://www4.comp.polyu.edu.hk/~xiaohuang/", "education, career, research, recruiting and 2026 update", "2026-08"),
  huangLab: profile("PolyU X AI Lab", "https://web.comp.polyu.edu.hk/xiaohuang/lab.html", "current students and named alumni destinations"),
  yangQiang: official("PolyU profile", "https://www.polyu.edu.hk/dsai/docdrive/personal/yangqiang.html", "education, career, FATE and research"),
  yangQiangHub: official("PolyU Scholars Hub", "https://research.polyu.edu.hk/en/persons/qiang-yang/", "1 April 2025 appointment and current leadership", "2025-04-01"),
  maJing: official("HKBU faculty profile", "https://www.comp.hkbu.edu.hk/v1/?id=majing&page=profile", "education, visits and research"),
  maJingTheses: official("HKBU thesis archive", "https://www.comp.hkbu.edu.hk/v1/?pid=47", "named 2025 PhD graduates and thesis topics", "2025"),
  bai: official("HKBU faculty profile", "https://www.comp.hkbu.edu.hk/v1/?id=baijiaxin&page=profile", "education, PhD adviser, career, internships and 2026 start"),
  baiFaculty: official("HKBU faculty directory", "https://www.comp.hkbu.edu.hk/v1/?page=faculty&sort=n", "current Assistant Professor status"),
  zhou: official("HKBU faculty profile", "https://www.comp.hkbu.edu.hk/v1/?id=kyzhou&page=profile", "current appointment, research and software"),
  zhouSchool: official("HKBU Winter School biography", "https://www.comp.hkbu.edu.hk/wsb2025/lecturer_details.php?lect_id=16", "PhD adviser and NTU postdoc mentors", "2025"),
  han: official("HKBU faculty profile", "https://www.comp.hkbu.edu.hk/v1/index.php?id=bhanml&lang=sc&page=profile", "education, adviser, dated visits, group and research"),
  hanNews: official("HKBU research spotlight", "https://www.comp.hkbu.edu.hk/v1/?id=4&page=research_spotlights", "late-2019 HKBU start and research trajectory", "2020"),
  lam: profile("CUHK Text Mining Group", "https://www1.se.cuhk.edu.hk/~textmine/", "education, post-PhD career, team and research"),
  lamPortal: official("CUHK research portal", "https://research.cuhk.edu.hk/en/persons/wai-lam/", "current appointment and research"),
};

export const sgHkFullProfileEnhancements: Record<string, PersonEnhancement> = {
  "hwee-tou-ng": { facts: [fact("教育", "University of Toronto BSc（1985）、Stanford MS（1987）、UT Austin PhD（1992）", s.ng), fact("学术服务", "Computational Linguistics 主编（2018-07 至 2024-01）", s.ng), fact("招生状态", "个人主页在核验日公开招募博士后与研究助理", s.ng)], sources: [s.ng, s.ngPeople], lastVerifiedAt: checkedAt },
  "min-yen-kan": { facts: [fact("博士师承", "Columbia 博士阶段由 Kathleen McKeown 与 Judith Klavans 共同指导", s.kanCv), fact("研究主线", "科学文献理解、数字图书馆、IR/NLP，并延伸至 RAG 与 LLM 安全伦理", s.kan), fact("页面时效", "个人主页标注最近构建于 2026-08-23", s.kan)], sources: [s.kan, s.kanCv], lastVerifiedAt: checkedAt },
  "tat-seng-chua": { facts: [fact("任职轨迹", "1983 年起在 NUS 任职，2003 年晋升教授，2009 年起任 KITHCT Chair Professor", s.chua), fact("研究平台", "2010 年起共同领导 NExT/NExT++；2021–2023 年推进 Sea–NExT Joint Lab", s.chua), fact("创业", "共同创办 ViSenze 与 6Estates", s.chua), fact("博士培养", "个人主页记录自 2004 年以来指导 37 名博士", s.chua)], sources: [s.chuaNus, s.chua], lastVerifiedAt: checkedAt, knownAlumniCount: 37 },
  "qizhe-shieh": { facts: [fact("教育", "SJTU ACM 本科（2016）、CMU LTI 硕士（2018）、CMU Machine Learning PhD（2020）", s.shieh), fact("产业研究", "加入 NUS 前在 Google Brain / Google DeepMind 从事两年研究", s.shieh), fact("研究主线", "大语言模型、深度学习、NLP 与训练/推理方法", s.shieh)], sources: [s.shieh, s.shiehPersonal], lastVerifiedAt: checkedAt },
  "kenji-kawaguchi": { facts: [fact("教育", "MIT CS PhD（2020），博士导师 Leslie Kaelbling", s.kenji), fact("任职轨迹", "Harvard 博士后（2020–2021）后加入 NUS", s.kenji), fact("团队", "NUS Machine Learning Lab 研究深度学习与 LLM 的理论和实践，并在核验日公开招生", s.kenjiLab)], sources: [s.kenji, s.kenjiLab], lastVerifiedAt: checkedAt },
  "jiancong-xiao": { facts: [fact("到任", "2026-07-01 加入 NUS 任 tenure-track Assistant Professor", s.xiao), fact("教育", "CUHK-Shenzhen PhD（2023），导师 Zhi-Quan Tom Luo", s.xiao), fact("博士后", "UPenn 博士后，合作导师 Qi Long 与 Weijie Su", s.xiao)], sources: [s.xiao, s.xiaoNews], lastVerifiedAt: checkedAt },
  "yang-you": { facts: [fact("教育", "Tsinghua 硕士（2015）、UC Berkeley CS PhD（2020），导师 James Demmel", s.you), fact("到任", "2020-08-14 加入 NUS", s.youNews), fact("研究主线", "大规模基础模型训练、HPC、分布式优化；代表性方法包括 LARS 与 LAMB", s.you)], sources: [s.you, s.youNews], lastVerifiedAt: checkedAt },
  "bryan-hooi": { facts: [fact("教育与师承", "CMU Machine Learning PhD，导师 Christos Faloutsos", s.hooi), fact("研究边界", "图机器学习与异常检测为基础，近年覆盖 LLM/VLM 事实性、幻觉、安全和智能体", s.hooi), fact("机构交叉", "同时隶属 NUS School of Computing 与 Institute of Data Science", s.hooiNus)], sources: [s.hooi, s.hooiNus], lastVerifiedAt: checkedAt },
  "shafiq-joty": { facts: [fact("教育", "UBC Computer Science PhD（2008-09 至 2014-02）", s.joty), fact("任职轨迹", "QCRI Research Scientist（2014–2017）→ NTU Assistant/Associate Professor（2017–2022）→ Salesforce Research Director（2022–）", s.joty), fact("团队状态", "个人主页说明全职任 Salesforce 期间不再招收新的 NTU 学生", s.joty), fact("学生去向", "公开学生页记录 Li Xingxuan 2025 PhD 后赴 MiroMind 任 Research Scientist，Ruochen Zhao 赴 Apple 任 Research Engineer", s.jotyStudents)], sources: [s.joty, s.jotyStudents], lastVerifiedAt: checkedAt },
  "aixin-sun": { facts: [fact("教育", "NTU B.A.Sc.（2001）、PhD（2004）", s.sun), fact("任职轨迹", "UNSW 博士后后于 2005 年加入 NTU", s.sunDmal), fact("研究主线", "信息检索、推荐系统、NLP；近期延伸至 LLM 归因、信息抽取与科学推理", s.sun)], sources: [s.sun, s.sunDmal], lastVerifiedAt: checkedAt },
  "anh-tuan-luu": { facts: [fact("教育", "NTU PhD（2017）", s.luu), fact("博士后", "MIT CSAIL Research Fellow（2018–2020），合作导师 Regina Barzilay", s.luu), fact("研究与招生", "LLM、可信 AI、图学习与 NLP 应用；个人主页在核验日公开招募学生", s.luu)], sources: [s.luu, s.luuNtu], lastVerifiedAt: checkedAt },
  "wenya-wang": { facts: [fact("博士师承", "NTU PhD，导师 Sinno Jialin Pan", s.wang), fact("博士后", "University of Washington 博士后，与 Noah Smith、Hanna Hajishirzi 合作", s.wang), fact("研究与招生", "生成模型推理、可解释/可信与高效学习；核验日公开招募 PhD、RA 与实习生", s.wang)], sources: [s.wang, s.wangNtu], lastVerifiedAt: checkedAt },
  "erik-cambria": { facts: [fact("教育", "Stirling / MIT Media Lab 联合研究经历下完成博士", s.cambria), fact("产业与创业", "曾在 MSRA 北京与 HP Labs India 研究，并创办 SenticNet 与 finaXai", s.cambria), fact("研究主线", "神经符号、可解释与可信的情感计算/NLP", s.cambria)], sources: [s.cambria, s.cambriaNtu], lastVerifiedAt: checkedAt },
  "bo-an": { facts: [fact("教育与师承", "UMass Amherst CS PhD，导师 Victor Lesser", s.anCv), fact("任职轨迹", "USC 博士后（2010–2012，与 Milind Tambe）后于 2013 年加入 NTU", s.anCv), fact("产业化部署", "安全博弈系统曾部署于美国联邦空警、海岸警卫队与野生动物保护场景", s.an)], sources: [s.an, s.anCv], lastVerifiedAt: checkedAt },
  "wei-lu": { facts: [fact("师承", "NUS PhD（2009），导师 Hwee Tou Ng", s.weiLuNus), fact("任职轨迹", "在 SUTD 任职 12 年后于 2025-09 加入 NTU", s.weiLu), fact("团队", "在 NTU 领导 BREATHE AI Lab，研究 NLP 与现代语言模型", s.weiLu)], sources: [s.weiLu, s.weiLuNus], lastVerifiedAt: checkedAt },
  "soujanya-poria": { facts: [fact("教育", "University of Stirling 博士", s.poria), fact("任职轨迹", "曾任 A*STAR 科学家、NTU Presidential Postdoctoral Fellow 与 SUTD 教员，后转任 NTU EEE", s.poriaNtu), fact("团队", "DeCLaRe Lab 聚焦多模态对话、情感与常识推理", s.poria)], sources: [s.poria, s.poriaNtu], lastVerifiedAt: checkedAt },
  "wenxuan-zhang": { facts: [fact("博士师承", "CUHK PhD，导师 Wai Lam", s.zhang), fact("产业经历", "加入 SUTD 前任 Alibaba Group Singapore Research Scientist，并获 Ali Star", s.zhang), fact("研究平台", "建立 iNLP Lab，公开项目包括 SeaLLMs、Babel、Auto-Arena 与 Myna", s.zhangPersonal)], sources: [s.zhang, s.zhangPersonal], lastVerifiedAt: checkedAt },
  "yang-deng": { facts: [fact("博士师承", "CUHK PhD，导师 Wai Lam", s.dengPersonal), fact("博士后", "在 NUS NExT++ 与 Tat-Seng Chua、See-Kiong Ng 合作", s.dengPersonal), fact("研究主线", "对话、人本、智能体与可信 NLP", s.deng)], sources: [s.deng, s.dengPersonal], lastVerifiedAt: checkedAt },
  "yunshan-ma": { facts: [fact("教育", "BUPT BEng（2015）、NUS PhD（2022）", s.maYunshanCv), fact("到任", "2025-01 加入 SMU 任 Assistant Professor", s.maYunshanCv), fact("研究主线", "推荐、数据挖掘、多模态事件预测与 LLM 增强优化", s.maYunshan)], sources: [s.maYunshan, s.maYunshanCv], lastVerifiedAt: checkedAt },
  "jing-jiang": { facts: [fact("教育", "Stanford BS（2002）/MComp（2003）、UIUC PhD（2008）", s.jiangCv), fact("SMU 轨迹", "2008 年入职，2016 年晋升副教授，2021-07 晋升教授", s.jiangCv), fact("状态", "SMU 主页在核验日标注 on leave；当前公开任职为 ANU", s.jiang)], sources: [s.jiang, s.jiangCv], lastVerifiedAt: checkedAt, status: "历史 / 跨地区节点；SMU 官方页标注 on leave" },
  "nancy-chen": { facts: [fact("教育", "MIT 与 Harvard 联合培养博士；博士阶段曾在 MIT Lincoln Laboratory 工作", s.chen), fact("团队与项目", "I2R Senior Principal Scientist / Lead PI，领导多模态生成式 AI 与 AI for Education", s.chen), fact("技术转化", "A*STAR AI4Edu 页面记录项目在 2022 年孵化 nomopai 与 KiteSense", s.chenEdu)], sources: [s.chen, s.chenEdu], lastVerifiedAt: checkedAt },
  "ai-ti-aw": { facts: [fact("研究主线", "自 1990 年代末持续研究机器翻译与本地/东南亚语言 NLP", s.aw), fact("领导角色", "A*STAR I2R Aural and Language Intelligence 负责人、国家多模态 LLM 计划共同 PI", s.aw), fact("模型平台", "领导 MERaLiON 多模态语言模型系列", s.meralion)], sources: [s.aw, s.meralion], lastVerifiedAt: checkedAt },
  "jian-su": { facts: [fact("机构领导", "I2R Principal Scientist、NLP Group Leader", s.su), fact("联合平台", "A*STAR Co-Director of DesCartes、I2R Co-Director of Baidu-I2R Research Centre", s.su), fact("研究与部署", "负责国际协作与大规模 NLP 部署；团队公开研究含对话情感识别", s.suResearch)], sources: [s.su, s.suResearch], lastVerifiedAt: checkedAt },

  "lingpeng-kong": { facts: [fact("博士师承", "CMU PhD，由 Noah Smith 与 Chris Dyer 共同指导", s.kongLaw), fact("产业研究", "Google DeepMind Research Scientist / Senior Research Scientist（2017–2020）", s.kongLaw), fact("研究主线", "结构化预测、语言模型与表示学习", s.kong)], sources: [s.kong, s.kongLaw], lastVerifiedAt: checkedAt },
  "tao-yu": { facts: [fact("教育与师承", "Yale PhD，导师 Dragomir Radev；Columbia 硕士阶段与 Owen Rambow、Kathleen McKeown 合作", s.taoPersonal), fact("研究平台", "创办 XLANG Lab，研究长程推理、智能体与自然语言数据接口", s.tao), fact("代表资源", "主导 Spider / Text-to-SQL 方向的公开研究", s.taoPersonal)], sources: [s.tao, s.taoPersonal], lastVerifiedAt: checkedAt },
  "qi-liu-hku": { facts: [fact("教育", "NUS MSc、Oxford Computer Science PhD", s.qiPdf), fact("产业轨迹", "曾在 Google DeepMind、Facebook AI Research 与 Microsoft Research 任职", s.qi), fact("创业", "共同创办 Reka AI", s.qi)], sources: [s.qi, s.qiPdf], lastVerifiedAt: checkedAt },
  "chao-huang-hku": { facts: [fact("教育", "University of Notre Dame PhD", s.chao), fact("研究平台", "领导 Data Intelligence Lab，覆盖推荐、图学习、LLM 与智能体", s.chao), fact("开放项目", "公开项目包括 LightRAG、RAG-Anything、DeepCode 与 AutoAgent", s.chaoAi)], sources: [s.chao, s.chaoAi], lastVerifiedAt: checkedAt },
  "pascale-fung": { facts: [fact("教育", "Columbia Computer Science PhD（1997）", s.fungBio), fact("早期产业研究", "AT&T Bell Labs（1993–1997）；此前经历包括 BBN、LIMSI 与 ATR/Kyoto", s.fungBio), fact("研究主线", "人本/同理心 AI、NLP、语音与情感计算", s.fung)], sources: [s.fung, s.fungBio], lastVerifiedAt: checkedAt },
  "de-kai": { facts: [fact("教育", "UC San Diego BS（1984）、UC Berkeley CS PhD（1992）", s.dekai), fact("任职轨迹", "Toronto 博士后后于 1992 年加入创校初期 HKUST", s.dekai), fact("技术史", "1993–1994 年开展早期英汉统计机器翻译研究", s.dekaiPersonal)], sources: [s.dekai, s.dekaiPersonal], lastVerifiedAt: checkedAt },
  "yangqiu-song": { facts: [fact("教育", "Tsinghua BE（2003）、PhD（2009）", s.song), fact("任职轨迹", "IBM Research China（2009–2010）、MSRA（2010–2012）、HKUST/Huawei 与 UIUC 博后（2012–2015）、WVU（2015–2016）", s.song), fact("产业连接", "Amazon A9/Rufus visiting appointment（2022–2026），并共同领导 HKUST–WeBank Lab", s.song)], sources: [s.song, s.songHkust], lastVerifiedAt: checkedAt },
  "junxian-he": { facts: [fact("教育与师承", "SJTU 本科、CMU LTI PhD（2022），导师 Taylor Berg-Kirkpatrick", s.heCmu), fact("研究主线", "复杂推理与规划、强化学习和 LLM agents", s.he), fact("团队", "HKUST 页面于 2026-08-25 列出 12 名 PhD、2 名 MPhil，并记录 Bryan Wilie 2026 年毕业", s.he)], sources: [s.he, s.heCmu], lastVerifiedAt: checkedAt },
  "yi-fung": { sources: [official("HKUST faculty profile", "https://cse.hkust.edu.hk/admin/people/faculty/profile/yrfung", "education, research and awards"), official("HKUST faculty projects", "https://facultyprofiles.hkust.edu.hk/profiles.php?profile=may-fung-yrfung", "current students and projects", "2026")], lastVerifiedAt: checkedAt },
  "song-guo-hkust": { facts: [fact("教育", "HUST BE（1995）、BUPT ME（1998）、University of Ottawa PhD（2006）", s.guo), fact("任职轨迹", "UBC 博士后（2006）后历任 UNBC、Aizu、PolyU；2023 年加入 HKUST", s.guo), fact("创业", "2021 年共同创办 Zero Dynamic Medical Technology 并任 Chief Scientist", s.guo)], sources: [s.guo, s.guoPortal], lastVerifiedAt: checkedAt },
  "kam-fai-wong": { facts: [fact("教育", "University of Edinburgh BSc 与 PhD", s.wong), fact("研究主线", "NLP、信息检索、文本挖掘与中文语言技术", s.wong), fact("当前节点", "CUHK SEEM 教授，属于香港中文 NLP 资深培养节点", s.wongCuhk)], sources: [s.wong, s.wongCuhk], lastVerifiedAt: checkedAt },
  "xixin-wu": { sources: [official("CUHK research portal", "https://research.cuhk.edu.hk/en/persons/xixin-wu/", "education, career and research"), profile("Xixin Wu homepage", "https://www1.se.cuhk.edu.hk/~wuxx/", "PhD/Master advisers and Cambridge mentors")], lastVerifiedAt: checkedAt },
  "irwin-king": { facts: [fact("教育", "Caltech BS、USC MSc 与 PhD", s.king), fact("机构建设", "领导 CUHK MISC Lab / ELITE，并承担大学教育管理职务", s.king), fact("外部经历", "曾在 AT&T Labs Research 休假研究，并访问 UC Berkeley", s.king)], sources: [s.king, s.kingLab], lastVerifiedAt: checkedAt },
  "yu-cheng-cuhk": { facts: [fact("教育", "Tsinghua BSc、Northwestern PhD", s.cheng), fact("任职轨迹", "Microsoft Research Redmond Principal Researcher（2018–2023）；2024 年加入 CUHK", s.cheng), fact("产业领导", "2023–2025 任 MiniMax Chief Scientist，并参与 abab、M1、Hailuo Video 等模型；现与 Kunlun/Skywork 保持 Chief Scientist 角色", s.cheng)], sources: [s.cheng, s.chengPersonal], lastVerifiedAt: checkedAt },
  "wei-ying-ma": { facts: [fact("当前地区状态", "2024 年 CityU 讲座资料明确其当前任 Tsinghua AIR Huiyan Chair Professor / Chief Scientist", s.maWeiying), fact("产业轨迹", "曾任 ByteDance Vice President / Head of AI Lab，相关技术进入 Douyin、TikTok、Toutiao、CapCut 与 Lark", s.maWeiying), fact("研究转向", "当前重点为生成式 AI for Science，覆盖药物、蛋白与材料发现", s.maWeiying)], sources: [s.maWeiying, s.maWeiyingCityu], lastVerifiedAt: checkedAt, status: "历史 / 跨地区节点；当前公开任职在清华 AIR" },
  "chen-ma-cityu": { facts: [fact("教育", "BIT BS（2013）/MS（2015）、McGill CS PhD", s.maChen), fact("任职轨迹", "2021-08 加入 CityU 任 Assistant Professor，2026-07 晋升 Associate Professor", s.maChen), fact("研究与招生", "推荐系统、知识图谱、数据驱动 AI 与 NLP；个人主页在核验日公开招募 PhD/博后", s.maChen)], sources: [s.maChen, s.maChenCityu], lastVerifiedAt: checkedAt },
  "zhisong-zhang": { lastVerifiedAt: checkedAt },
  "gang-liu-cityu": { lastVerifiedAt: checkedAt },
  "ning-miao": { lastVerifiedAt: checkedAt },
  "jianyuan-guo": { lastVerifiedAt: checkedAt },
  "xiaotie-deng": { facts: [fact("教育", "Tsinghua BSc、Academia Sinica MSc、Stanford PhD", s.dengXiaotie), fact("研究主线", "算法博弈、机制设计与数字市场", s.dengXiaotieProfile), fact("近期延伸", "官方师资页将 LLM-based multi-agent systems 列为研究方向", s.dengXiaotie)], sources: [s.dengXiaotie, s.dengXiaotieProfile], lastVerifiedAt: checkedAt },
  "zhenjiang-li": { facts: [fact("教育", "XJTU BE（2007）、HKUST MPhil（2009）/PhD（2012）", s.liZhenjiang), fact("研究平台", "DamsonSys 研究边缘 AI、AIoT 与资源高效 LLM agents", s.liZhenjiang), fact("公开校友去向", "组页列出 Yang Liu→Florida State faculty、Tao Chen→Samsung Research America、Lixiang Han→Tencent AI Lab", s.liZhenjiang)], sources: [s.liZhenjiang, s.liZhenjiangCityu], lastVerifiedAt: checkedAt },
  "wenjie-li": { facts: [fact("教育", "CUHK Systems Engineering and Engineering Management PhD（1997）", s.liWenjie), fact("研究主线", "NLP、文本挖掘、自动摘要、问答与对话", s.liWenjie), fact("校友网络", "公开组页列出多名成员进入 Microsoft、Alibaba、Tencent 与 Baidu", s.liWenjieGroup)], sources: [s.liWenjie, s.liWenjieGroup], lastVerifiedAt: checkedAt },
  "jing-li-polyu": { facts: [fact("教育", "Peking University BS（2013）、CUHK PhD（2017）", s.liJing), fact("任职轨迹", "Tencent AI Lab NLP Center Senior Researcher（2017–2019）；2019 年加入 PolyU，2025 年晋升 Associate Professor", s.liJingPersonal), fact("研究平台", "创办 PolyU Embodied Artificial Intelligence Lab，研究人本 NLP 与具身智能体 LLM", s.liJingPersonal)], sources: [s.liJing, s.liJingPersonal], lastVerifiedAt: checkedAt },
  "hongxia-yang": { facts: [fact("教育", "Nankai BS、Duke PhD", s.yangHongxia), fact("到任", "2024-07-15 加入 PolyU 任 Chair Professor", s.yangHongxia), fact("产业领导", "曾任 IBM Research Staff、Yahoo Principal Data Scientist、Alibaba AI Scientist/Director、ByteDance US LLM Head", s.yangHongxiaNews), fact("近期平台", "2026 年获 Vobile Group Professorship，并领导 Co-GenAI / Model-over-Models 路线", s.yangHongxiaNews)], sources: [s.yangHongxia, s.yangHongxiaNews], lastVerifiedAt: checkedAt },
  "liangliang-cao": { facts: [fact("教育", "USTC BS（2003）、CUHK MPhil（2005）、UIUC PhD（2011）", s.cao), fact("产业轨迹", "Switi co-founder（2016；2018 被 Google 收购）→ Google Cloud Speech（2018–2021）→ Apple（2022）→ Google DeepMind Gemini/Astra（2024–）", s.cao), fact("到任", "2026-06-29 出任 PolyU Chair Professor of AI Systems", s.caoNews)], sources: [s.cao, s.caoNews], lastVerifiedAt: checkedAt },
  "wenqi-fan": { facts: [fact("教育", "GDMU BM、SYSU MEng、CityU CS PhD（2020）", s.fan), fact("任职轨迹", "PolyU Postdoctoral Fellow / Research Assistant Professor（2020–2023）后任 Assistant Professor", s.fanMm), fact("研究主线", "推荐系统、图学习、可信 AI，并延伸至 LLM/RAG", s.fanMm)], sources: [s.fan, s.fanMm], lastVerifiedAt: checkedAt },
  "xiao-huang-polyu": { facts: [fact("教育", "SJTU BS（2012）、Illinois Tech MS（2015）、Texas A&M PhD（2020）", s.huang), fact("产业研究", "Baidu USA intern（2018）、Microsoft Research Redmond intern（2019）", s.huang), fact("研究与招生", "Graph RAG、Text-to-SQL、LLM reasoning 与 agentic AI；核验日公开招募 PhD", s.huang)], sources: [s.huang, s.huangLab], lastVerifiedAt: checkedAt },
  "qiang-yang-polyu": { facts: [fact("教育", "Peking University BS（1982）、University of Maryland MSc（1987）/CS PhD（1989）", s.yangQiangHub), fact("任职轨迹", "Waterloo/SFU（1989–2001）→ HKUST（2001–2023）→ PolyU（2025-04-01 起）", s.yangQiang), fact("产业与开源", "曾领导 Huawei Noah’s Ark、WeBank AI；共同建设联邦学习平台 FATE", s.yangQiang)], sources: [s.yangQiang, s.yangQiangHub], lastVerifiedAt: checkedAt },
  "jing-ma-hkbu": { facts: [fact("教育", "BUPT BE（2013）/ME（2016）、CUHK PhD（2020）", s.maJing), fact("访问经历", "NTU visiting scholar（2018-12 至 2019-08）、IBS visiting scholar（2019-12 至 2020-02）", s.maJing), fact("公开博士培养", "HKBU thesis archive 列出 2025 年博士毕业生 Luo Ziyang 与 Niu Shuai", s.maJingTheses)], sources: [s.maJing, s.maJingTheses], lastVerifiedAt: checkedAt },
  "jiaxin-bai": { facts: [fact("教育与师承", "HKUST BEng/BBA 与 CS PhD，博士导师 Yangqiu Song", s.bai), fact("研究经历", "HKUST 博士后、Edinburgh 访问；曾在 Amazon Search A9 Palo Alto 实习", s.bai), fact("到任", "2026 年加入 HKBU 任 Assistant Professor", s.bai)], sources: [s.bai, s.baiFaculty], lastVerifiedAt: checkedAt },
  "kaiyang-zhou": { facts: [fact("博士师承", "University of Surrey CS PhD，导师 Tao Xiang", s.zhouSchool), fact("博士后", "NTU 博士后，与 Ziwei Liu、Chen Change Loy 合作", s.zhouSchool), fact("研究与工具", "视觉语言模型、域泛化/适配；创建 Torchreid、Dassl 与 CoOp", s.zhou)], sources: [s.zhou, s.zhouSchool], lastVerifiedAt: checkedAt },
  "bo-han-hkbu": { facts: [fact("教育与师承", "UTS CS PhD（2015–2019），主要导师 Ivor W. Tsang", s.han), fact("任职轨迹", "RIKEN AIP 博士后（2019–2020）；2019 年末加入 HKBU", s.hanNews), fact("外部研究", "Alibaba DAMO visiting（2021）、Microsoft Research visiting（2022）、MBZUAI visiting（2024）", s.han), fact("团队", "领导 Trustworthy Machine Learning and Reasoning Group，核验日公开招募 PhD/RA/访问生/博后", s.han)], sources: [s.han, s.hanNews], lastVerifiedAt: checkedAt },
  "wai-lam": { facts: [fact("教育", "CUHK BSc/MPhil、University of Waterloo CS PhD", s.lam), fact("任职轨迹", "博士毕业后曾在 IUPUI 与 University of Iowa 研究，随后加入 CUHK", s.lam), fact("研究与团队", "Text Mining Group 研究 IR、文本挖掘、机器学习与不确定性推理，并公开列出现任研究生", s.lam)], sources: [s.lam, s.lamPortal], lastVerifiedAt: checkedAt },
};

export const sgHkFullProfileRelationships: Relationship[] = [
  { id: "sg-hk-song-bai", from: "yangqiu-song", to: "jiaxin-bai", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "HKBU 官方简介明确写明 Jiaxin Bai 的 HKUST 博士由 Yangqiu Song 指导。", evidenceObject: "HKUST PhD supervision", source: s.bai, verified: true },
];

export const sgHkFullProfileGroupMembers: GroupMember[] = [
  { id: "sg-hk-hongxia-zhen", teacherId: "hongxia-yang", name: "Zhen Li", role: "PhD Student · joined 2024", focus: "Low-bit training / foundation models", source: profile("Hongxia Yang team", "https://www4.comp.polyu.edu.hk/~hongxyang/people/", "current team roles and start years", "2026") },
  { id: "sg-hk-xiao-chuang", teacherId: "xiao-huang-polyu", name: "Chuang Zhou", role: "PhD Student · Fall 2022–", focus: "Graph RAG and agentic AI", source: s.huangLab },
];

export const sgHkFullProfileStudentPlacements: StudentPlacement[] = [
  { id: "sg-hk-zhenjiang-yang-liu", student: "Yang Liu", teacherId: "zhenjiang-li", company: "Florida State University", role: "Assistant Professor", kind: "reported", degree: "PhD", currentRole: "Assistant Professor", verifiedAt: checkedAt, sector: "academia", source: s.liZhenjiang },
  { id: "sg-hk-zhenjiang-tao-chen", student: "Tao Chen", teacherId: "zhenjiang-li", company: "Samsung Research America", role: "Senior Researcher", kind: "reported", degree: "PhD", currentRole: "Senior Researcher", verifiedAt: checkedAt, sector: "industry", source: s.liZhenjiang },
  { id: "sg-hk-zhenjiang-lixiang-han", student: "Lixiang Han", teacherId: "zhenjiang-li", company: "Tencent AI Lab", role: "Researcher", kind: "reported", degree: "PhD", currentRole: "Researcher", verifiedAt: checkedAt, sector: "industry", source: s.liZhenjiang },
];
