import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-03";
const src = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({ label, url, kind, checkedAt, supports });
const fact = (label: string, value: string, source: Source) => ({ label, value, source });

const s = {
  manocha: src("UMD Engineering · Dinesh Manocha", "https://eng.umd.edu/clark/faculty/901/Dinesh-Manocha", "official", "Current chairs, IIT Delhi B.Tech, Berkeley PhD, research, software licensing and Impulsonic acquisition"),
  manochaImpact: src("UMD CS · Dinesh Manocha receives Jimmy Lin Award", "https://www.cs.umd.edu/node/25980", "official", "52 graduated PhD students and technology transfer to more than 60 companies"),
  goldstein: src("UMD CS · Tom Goldstein", "https://www.cs.umd.edu/people/tomg", "official", "Current UMD appointment, Washington University BA, UCLA PhD, Rice/Stanford research training and AI/vision/machine-learning research areas"),
  goldsteinGroup: src("Tom Goldstein · group", "https://www.cs.umd.edu/~tomg/group/", "profile", "First-party student roster, thesis topics and destinations"),
  goldsteinRecruiting: src("Tom Goldstein · prospective students", "https://www.cs.umd.edu/~tomg/contact/", "profile", "Current prospective-PhD instructions and research fit"),
  aloimonos: src("UMD NACS · Yiannis Aloimonos", "https://nacs.umd.edu/facultyprofile/aloimonos/yiannis", "official", "Current professorship, Computer Vision Laboratory leadership, education and current student link"),
  aloimonosImpact: src("UMIACS · Yiannis Aloimonos named IEEE Fellow", "https://www.umiacs.umd.edu/news-events/news/aloimonos-named-ieee-fellow", "official", "Active-perception research, Perception & Robotics Group and 40+ advised PhDs"),
  vidal: src("Penn GRASP · René Vidal", "https://www.grasp.upenn.edu/people/rene-vidal/", "official", "Current Penn role, research programme and official portrait"),
  vidalEducation: src("Penn Medicine · René Vidal", "https://www.med.upenn.edu/apps/faculty/index.php/g275/p9684356", "official", "Berkeley doctorate and Penn academic appointment"),
  chang: src("UCLA Samueli · Kai-Wei Chang", "https://samueli.ucla.edu/people/kai-wei-chang/", "official", "Current professorship, education, NLP/ML research and industry internships"),
  changThesis: src("UIUC IDEALS · Kai-Wei Chang dissertation", "https://www.ideals.illinois.edu/items/79678/bitstreams/208946/data.pdf", "thesis", "Dissertation acknowledgements explicitly name Dan Roth as PhD adviser"),
  changGroup: src("Kai-Wei Chang · UCLA NLP group", "https://web.cs.ucla.edu/~kwchang/members/", "profile", "Current group and public PhD/postdoc alumni destinations"),
  li: src("UW–Madison CS · Sharon Li", "https://www.cs.wisc.edu/staff/li-sharon/", "official", "Current faculty appointment and official portrait"),
  liHome: src("Sharon Li · homepage", "https://pages.cs.wisc.edu/~sharonli/", "profile", "Reliable AI/LLM research, education, advisers, Stanford postdoc and recruiting status"),
  liCv: src("Sharon Li · CV", "https://pages.cs.wisc.edu/~sharonli/CV_SharonLi.pdf", "cv", "Cornell PhD adviser John Hopcroft and Stanford postdoctoral adviser Christopher Ré"),
  liu: src("USC Viterbi · Yan Liu", "https://stevens-computing-ai.usc.edu/directory/faculty/profile/?fname=Yan&lname=Liu", "official", "Current chairs, education, research and IBM trajectory"),
  liuCv: src("Yan Liu · USC CV", "https://viterbi.usc.edu/directory/cv/liu_yan_cv.pdf", "cv", "CMU PhD adviser Jaime Carbonell and Didi AI Labs chief-scientist role"),
  dilkina: src("USC CAIS · Bistra Dilkina", "https://cais.usc.edu/our-people/", "official", "Current USC chair, CAIS leadership, research and Cornell doctorate"),
  dilkinaCv: src("Bistra Dilkina · Cornell-hosted CV", "https://www.cs.cornell.edu/~bistra/images/dilkina-CV.pdf", "cv", "Cornell PhD adviser Carla Gomes"),
  qi: src("UVA Engineering · Yanjun Qi", "https://engineering.virginia.edu/faculty/yanjun-qi", "official", "Current appointment, CMU doctorate, NEC Labs career and ML/bioinformatics research"),
  qiMedicine: src("UVA School of Medicine · Yanjun Qi", "https://med.virginia.edu/faculty/faculty-listing/yq2h/", "official", "Education, group identity and machine learning for biomedicine programme"),
  qiStudent: src("UVA Libra · Zhe Wang dissertation", "https://libraetd.lib.virginia.edu/public_view/3j333376d", "thesis", "Official dissertation metadata names Yanjun Qi as adviser"),
  nikolaidis: src("USC Viterbi · Stefanos Nikolaidis", "https://viterbi.usc.edu/directory/faculty/Nikolaidis/Stefanos", "official", "Current professorship, ICAROS leadership, education and robotics research"),
  nikolaidisCv: src("Stefanos Nikolaidis · CV", "https://stefanosnikolaidis.net/cv/cv.pdf", "cv", "CMU PhD adviser Siddhartha Srinivasa, MIT master's adviser Julie Shah and industry history"),
  gomes: src("Cornell CS · Carla Gomes", "https://www.cs.cornell.edu/people/carla-gomes", "official", "Current Cornell professorship, University of Edinburgh PhD, AI/computational-sustainability research and official portrait"),
  gomesGroup: src("Carla Gomes · research agenda", "https://www.cs.cornell.edu/gomes/research.php", "profile", "First-party PhD/postdoc roster and academic/industry destinations"),
  srinivasa: src("UW Allen School · Siddhartha Srinivasa", "https://www.cs.washington.edu/people/faculty/siddhartha-sidd-srinivasa/", "official", "Current professorship, Personal Robotics Lab, education, research and official portrait"),
  srinivasaThesis: src("Siddhartha Srinivasa · CMU PhD thesis", "https://personalrobotics.cs.washington.edu/publications/srinivasa2005phd.pdf", "thesis", "CMU thesis committee lists Michael Erdmann and Matthew Mason as co-chairs"),
  srinivasaGroup: src("UW Personal Robotics Lab · people", "https://personalrobotics.cs.washington.edu/people/", "profile", "Current lab members, advisers and public alumni destinations"),
};

type Seed = Omit<Person, "region" | "category" | "status" | "primary" | "introducedAt" | "lastVerifiedAt" | "portrait"> & { portraitFile: string; portraitSource: Source };
const person = (p: Seed): Person => {
  const normalizedFacts = (p.facts ?? []).map((item) => item.label === "当前角色" ? { ...item, label: "当前任职" } : item);
  if (!normalizedFacts.some((item) => item.label === "研究主线")) {
    normalizedFacts.push(fact("研究主线", p.area, p.sources[0]));
  }
  return { ...p, facts: normalizedFacts, region: "United States", category: "core", status: "current independent PI · official faculty roster verified", primary: true, introducedAt: checkedAt, lastVerifiedAt: checkedAt, portrait: { src: `portraits/us-canada-remaining-priority-2026/${p.portraitFile}`, alt: `${p.name} 官方头像`, source: p.portraitSource } };
};

export const usCanadaRemainingPriorityPeople2026: Person[] = [
  person({ id: "dinesh-manocha-umd-2026", name: "Dinesh Manocha", role: "Distinguished University Professor · Paul Chrisman Iribe Chair", institution: "UMD", area: "Robotics · Multi-Agent Simulation · Computer Graphics", tags: ["UMD GAMMA", "Robotics", "Simulation", "Impulsonic", "Valve"], stage: "senior", x: 110, y: 120, portraitFile: "dinesh-manocha.jpg", portraitSource: s.manocha, summary: "UMD 机器人、图形学与多智能体仿真的资深带头人；公开履历记录其已指导 52 名博士，软件被大量产业用户采用，并联合创办被 Valve 收购的 Impulsonic。", facts: [fact("当前角色", "UMD Distinguished University Professor，兼任 CS/ECE 的 Paul Chrisman Iribe Chair。", s.manocha), fact("教育与学术训练", "1987 年获 IIT Delhi 计算机科学与工程 B.Tech，1992 年获 UC Berkeley 计算机科学博士。", s.manocha), fact("培养规模", "UMD 官方报道记录其已指导 52 名博士。", s.manochaImpact), fact("产业连接", "联合创办声学仿真公司 Impulsonic，2016 年被 Valve 收购；团队软件授权给 60 多家商业机构。", s.manocha)], sources: [s.manocha, s.manochaImpact] }),
  person({ id: "tom-goldstein-umd-2026", name: "Tom Goldstein", role: "Professor", institution: "UMD", area: "Machine Learning · Computer Vision · Optimization", tags: ["UMD CML", "Optimization", "Machine Learning", "Generative AI"], stage: "senior", x: 250, y: 120, portraitFile: "tom-goldstein.jpg", portraitSource: s.goldstein, summary: "UMD 机器学习、视觉与大规模优化 PI；公开组员页把博士课题和 Google、Google DeepMind、Amazon、Intel 等去向直接对应起来。", facts: [fact("当前角色", "Professor, University of Maryland Computer Science。", s.goldstein), fact("教育与学术训练", "2006 年获 Washington University in St. Louis 学士、2010 年获 UCLA 博士；加入 UMD 前在 Rice 与 Stanford 从事研究工作。", s.goldstein), fact("研究主线", "数值优化、机器学习、计算机视觉与大规模模型训练。", s.goldstein), fact("人才流向", "公开组员页记录 Zheng Xu 去 Google、Soham De 去 Google DeepMind、Hao Li 去 Amazon Research、Sohil Shah 去 Intel Research。", s.goldsteinGroup), fact("招生信息", "面向具备扎实数学背景的 prospective PhD applicants 给出公开申请说明。", s.goldsteinRecruiting)], sources: [s.goldstein, s.goldsteinGroup, s.goldsteinRecruiting] }),
  person({ id: "yiannis-aloimonos-umd-2026", name: "Yiannis Aloimonos", role: "Professor · Computer Vision Laboratory Director", institution: "UMD", area: "Computer Vision · Active Perception · Robot Learning", tags: ["UMD Vision Lab", "Active Vision", "Robotics", "IEEE Fellow"], stage: "senior", x: 390, y: 120, portraitFile: "yiannis-aloimonos.jpg", portraitSource: s.aloimonos, summary: "UMD 主动视觉与机器人感知资深学者，领导 Computer Vision Laboratory；官方资料记录其指导超过 40 篇博士论文。", facts: [fact("当前角色", "UMD CS Professor、Computer Vision Laboratory Director，并参与 UMIACS 与 Maryland Robotics Center。", s.aloimonos), fact("教育与学术训练", "在 University of Rochester 获计算机科学硕士与博士学位。", s.aloimonos), fact("培养规模", "UMIACS 官方报道记录其在 UMD 已指导超过 40 篇博士论文。", s.aloimonosImpact)], sources: [s.aloimonos, s.aloimonosImpact] }),
  person({ id: "rene-vidal-upenn-2026", name: "René Vidal", role: "Rachleff University Professor", institution: "Penn", area: "Computer Vision · Machine Learning · Biomedical Data Science", tags: ["Penn GRASP", "Trustworthy AI", "Computer Vision", "THEORINET"], stage: "senior", x: 530, y: 120, portraitFile: "rene-vidal.jpg", portraitSource: s.vidal, summary: "Penn 视觉、深度学习基础与生物医学数据科学资深 PI，连接 GRASP、IDEAS 与 THEORINET 等跨院系研究共同体。", facts: [fact("当前角色", "Penn Rachleff University Professor，并参与 GRASP。", s.vidal), fact("教育与学术训练", "1995 年获 Pontificia Universidad Católica de Chile 工业工程学士，1997 年获工程硕士；2000 年与 2003 年分别获 UC Berkeley EECS 硕士、博士。", s.vidalEducation), fact("研究主线", "深度学习基础、可信 AI、计算机视觉和生物医学数据科学。", s.vidal), fact("跨院系连接", "在 Penn 的 Electrical and Systems Engineering 与 Radiology 两个院系任职，并参与 GRASP Laboratory。", s.vidal)], sources: [s.vidal, s.vidalEducation] }),
  person({ id: "kai-wei-chang-ucla-2026", name: "Kai-Wei Chang", role: "Professor", institution: "UCLA", area: "Natural Language Processing · Machine Learning · Responsible AI", tags: ["UCLA NLP", "Dan Roth", "Amazon AGI", "Structured Prediction"], stage: "senior", x: 670, y: 120, portraitFile: "kai-wei-chang.jpg", portraitSource: s.chang, summary: "UCLA NLP 与结构化机器学习 PI，博士师承 Dan Roth；公开组员页持续记录学生进入 Anthropic、OpenAI、Meta、Google 与学术界的流动。", facts: [fact("当前角色", "Professor, UCLA Computer Science。", s.chang), fact("教育与学术训练", "National Taiwan University 计算机与电机双学士、计算机硕士；2015 年获 UIUC 计算机博士，随后在 Microsoft Research New England 从事博士后研究。", s.chang), fact("博士师承", "UIUC Computer Science PhD；博士论文致谢明确称 Dan Roth 为导师。", s.changThesis), fact("产业轨迹", "公开履历记录 Microsoft Research、Microsoft CISL 与 Google 的实习经历。", s.chang), fact("人才流向", "组员页公开列出校友进入 Anthropic、OpenAI、Meta、Google、Amazon 与 Stanford 等机构。", s.changGroup)], sources: [s.chang, s.changThesis, s.changGroup] }),
  person({ id: "sharon-li-wisc-2026", name: "Sharon Li", role: "Associate Professor", institution: "Wisconsin", area: "Reliable AI · LLM Safety · Out-of-Distribution Learning", tags: ["Reliable AI", "Agentic LLM", "John Hopcroft", "Christopher Ré"], stage: "emerging", x: 810, y: 120, portraitFile: "sharon-li.jpg", portraitSource: s.li, summary: "UW–Madison 可靠智能与 LLM 安全 PI，研究 OOD、推理时可靠性和 agentic systems；训练轨迹连接 John Hopcroft、Kilian Weinberger 与 Stanford Christopher Ré。", facts: [fact("当前角色", "Associate Professor, UW–Madison Computer Sciences。", s.li), fact("教育与学术训练", "2013 年获 Shanghai Jiao Tong University 工学学士；2017 年获 Cornell 博士，导师 John Hopcroft；2019–2020 年在 Stanford 跟随 Christopher Ré 从事博士后研究。", s.liCv), fact("博士师承", "Cornell PhD；CV 列 John Hopcroft 为 adviser，并与 Kilian Weinberger 紧密合作。", s.liCv), fact("博士后训练", "Stanford Computer Science postdoc，advisor Christopher Ré。", s.liCv), fact("招生状态", "主页明确写明当前组已满，暂无 Fall 2027 PhD/MS/本科/博士后研究名额。", s.liHome)], sources: [s.li, s.liHome, s.liCv] }),
  person({ id: "yan-liu-usc-2026", name: "Yan Liu", role: "Professor · Fletcher Jones Foundation Chair", institution: "USC", area: "Machine Learning · Time Series · AI for Health and Climate", tags: ["USC Machine Learning Center", "Jaime Carbonell", "Didi AI Labs", "IBM Research"], stage: "senior", x: 950, y: 120, portraitFile: "yan-liu.jpg", portraitSource: s.liu, summary: "USC 时间序列与可信机器学习资深 PI，博士师承 Jaime Carbonell，职业轨迹连接 IBM Research、Didi AI Labs 与 USC 的机器学习中心。", facts: [fact("当前角色", "USC Professor，兼 Fletcher Jones Foundation Chair 与 CS-centric Machine Learning Center Director。", s.liu), fact("教育与学术训练", "2001 年获 Peking University 计算机学士，2004 年与 2007 年分别获 CMU 计算机硕士、博士；博士导师为 Jaime Carbonell。", s.liuCv), fact("博士师承", "CMU Computer Science PhD；CV 列 Jaime Carbonell 为导师。", s.liuCv), fact("产业轨迹", "IBM T.J. Watson Research Staff Member；2018–2019 任 Didi AI Labs Chief Scientist。", s.liuCv)], sources: [s.liu, s.liuCv] }),
  person({ id: "bistra-dilkina-usc-2026", name: "Bistra Dilkina", role: "Associate Professor · Ginsburg Early Career Chair", institution: "USC", area: "AI for Social Good · Computational Sustainability · Optimization", tags: ["USC CAIS", "Carla Gomes", "Computational Sustainability", "AI for Social Good"], stage: "senior", x: 1090, y: 120, portraitFile: "bistra-dilkina.jpg", portraitSource: s.dilkina, summary: "USC Center for AI in Society 负责人之一，把组合优化、机器学习与环境保护、城市和灾害响应问题结合；博士师承 Carla Gomes。", facts: [fact("当前角色", "USC Dr. Allen and Charlotte Ginsburg Early Career Chair、Associate Professor，并领导 CAIS。", s.dilkina), fact("教育与学术训练", "2004 年获 Simon Fraser University 计算机学士；2009 年与 2012 年分别获 Cornell 计算机硕士、博士，导师 Carla Gomes；2012–2013 年在 Cornell Institute for Computational Sustainability 从事博士后研究。", s.dilkinaCv), fact("博士师承", "Cornell Computer Science PhD；CV 明确列 Carla Gomes 为 thesis adviser。", s.dilkinaCv), fact("研究主线", "计算可持续性、AI for Social Good、组合优化、保护规划与城市系统。", s.dilkina)], sources: [s.dilkina, s.dilkinaCv] }),
  person({ id: "yanjun-qi-uva-2026", name: "Yanjun Qi", role: "Associate Professor", institution: "UVA", area: "Machine Learning · Bioinformatics · Trustworthy AI", tags: ["UVA ML & Bioinformatics", "CMU PhD", "NEC Labs", "Deep Learning"], stage: "senior", x: 1230, y: 120, portraitFile: "yanjun-qi.jpg", portraitSource: s.qi, summary: "UVA 机器学习、生物信息与可信 AI PI，清华本科、CMU 博士，加入学术界前在 NEC Labs Machine Learning Department 任高级研究员。", facts: [fact("当前角色", "Tenured Associate Professor, UVA Computer Science。", s.qi), fact("教育与学术训练", "获 Tsinghua University 计算机学士学位；2008 年获 CMU School of Computer Science 博士学位。", s.qi), fact("产业轨迹", "2008–2013 任 NEC Labs America Machine Learning Department Senior Researcher。", s.qi), fact("培养关系", "UVA 学位论文库将 Yanjun Qi 列为 Zhe Wang 2024 博士论文导师。", s.qiStudent)], sources: [s.qi, s.qiMedicine, s.qiStudent] }),
  person({ id: "stefanos-nikolaidis-usc-2026", name: "Stefanos Nikolaidis", role: "Associate Professor · Fluor Early Career Chair", institution: "USC", area: "Human-Robot Interaction · Robust Robotics · Quality-Diversity", tags: ["USC ICAROS", "Siddhartha Srinivasa", "Julie Shah", "Human-Robot Interaction"], stage: "emerging", x: 1370, y: 120, portraitFile: "stefanos-nikolaidis.jpg", portraitSource: s.nikolaidis, summary: "USC ICAROS Lab 负责人，研究面向真实场景的鲁棒人机协作；训练轨迹连接 CMU Siddhartha Srinivasa 与 MIT Julie Shah，并有 Square Enix 产业经历。", facts: [fact("当前角色", "USC Associate Professor、Fluor Early Career Chair，领导 ICAROS Lab。", s.nikolaidis), fact("教育与学术训练", "2006 年获 National Technical University of Athens 电气与计算机工程学士，2009 年获 University of Tokyo 工程硕士，2014 年获 MIT 航空航天硕士，2018 年获 CMU Robotics 博士。", s.nikolaidis), fact("博士师承", "CMU Robotics PhD；CV 列 Siddhartha Srinivasa 为 adviser。", s.nikolaidisCv), fact("硕士师承", "MIT AeroAstro MSc；CV 列 Julie Shah 为 adviser。", s.nikolaidisCv), fact("产业轨迹", "曾任 Square Enix Research and Development 研究员。", s.nikolaidisCv)], sources: [s.nikolaidis, s.nikolaidisCv] }),
  person({ id: "carla-gomes-cornell-2026", name: "Carla Gomes", role: "Ronald C. and Antonia V. Nielsen Professor", institution: "Cornell", area: "Artificial Intelligence · Computational Sustainability · AI for Science", tags: ["Cornell AI", "Computational Sustainability", "AI for Science", "AAAI Fellow"], stage: "senior", x: 1510, y: 120, portraitFile: "carla-gomes.jpg", portraitSource: s.gomes, summary: "Cornell 计算可持续性与 AI for Science 资深带头人；公开研究页完整列出博士、博士后及其 Meta、Google、Microsoft、AI2、学术界等去向。", facts: [fact("当前角色", "Cornell Ronald C. and Antonia V. Nielsen Professor of Computing and Information Science。", s.gomes), fact("教育与学术训练", "1993 年获 University of Edinburgh 计算机博士，博士研究方向为人工智能与运筹学。", s.gomes), fact("研究主线", "人工智能、计算可持续性、计算生物学和科学计算。", s.gomes), fact("人才流向", "公开研究页列出校友进入 Stanford、Purdue、Meta、Google、Microsoft Turing、AI2 与 Deep Reasoning AI 等。", s.gomesGroup)], sources: [s.gomes, s.gomesGroup] }),
  person({ id: "siddhartha-srinivasa-uw-2026", name: "Siddhartha Srinivasa", role: "Professor · Personal Robotics Lab Director", institution: "UW", area: "Robot Manipulation · Human-Robot Interaction · Assistive Robotics", tags: ["UW Personal Robotics Lab", "Robotics", "Manipulation", "Amazon Robotics AI"], stage: "senior", x: 1650, y: 120, portraitFile: "siddhartha-srinivasa.jpg", portraitSource: s.srinivasa, summary: "UW Personal Robotics Lab 创始人，研究复杂环境中的机器人操作、人机交互和辅助机器人；博士论文由 Michael Erdmann 与 Matthew Mason 共同担任委员会主席。", facts: [fact("当前角色", "Professor, UW Paul G. Allen School，并领导 Personal Robotics Lab。", s.srinivasa), fact("教育与学术训练", "1999 年获 IIT Madras 机械工程 B.Tech；2005 年获 CMU Robotics 博士。", s.srinivasa), fact("博士师承", "CMU Robotics PhD；论文委员会列 Michael Erdmann 与 Matthew Mason 为 co-chairs。", s.srinivasaThesis), fact("研究共同体", "Personal Robotics Lab 研究 perception、manipulation、learning 与 human-robot interaction。", s.srinivasaGroup), fact("当前团队", "实验室公开列出 Helen Wang、Sidharth Talia、Yunchu Zhang 与 Ethan Pronovost 等博士生及共同导师。", s.srinivasaGroup)], sources: [s.srinivasa, s.srinivasaThesis, s.srinivasaGroup] }),
];

export const usCanadaRemainingPriorityRelationships2026: Relationship[] = [
  { id: "us-remain-roth-chang", from: "dan-roth-top", to: "kai-wei-chang-ucla-2026", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Kai-Wei Chang 的 UIUC 博士论文致谢明确称 Dan Roth 为导师。", source: s.changThesis, verified: true },
  { id: "us-remain-gomes-dilkina", from: "carla-gomes-cornell-2026", to: "bistra-dilkina-usc-2026", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Bistra Dilkina 的 Cornell-hosted CV 明确列 Carla Gomes 为 thesis adviser。", source: s.dilkinaCv, verified: true },
  { id: "us-remain-srinivasa-nikolaidis", from: "siddhartha-srinivasa-uw-2026", to: "stefanos-nikolaidis-usc-2026", type: "lineage", subtype: "phd_adviser", label: "博士导师", evidence: "Stefanos Nikolaidis 的 CV 明确列 Siddhartha Srinivasa 为 CMU Robotics PhD adviser。", source: s.nikolaidisCv, verified: true },
];

export const usCanadaRemainingPriorityGroupMembers2026: GroupMember[] = [
  { id: "us-remain-aloimonos-eadom", teacherId: "yiannis-aloimonos-umd-2026", name: "Eadom Dessalene", role: "PhD Candidate", focus: "Human manipulation and robot imitation", source: src("Eadom Dessalene · homepage", "https://www.cs.umd.edu/~edessale/index.html", "profile", "Current UMD PhD status and Yiannis Aloimonos advisership") },
  { id: "us-remain-sidd-helen", teacherId: "siddhartha-srinivasa-uw-2026", name: "Helen Wang", role: "PhD Student", focus: "Robot learning, vision and planning", source: s.srinivasaGroup },
  { id: "us-remain-sidd-talia", teacherId: "siddhartha-srinivasa-uw-2026", name: "Sidharth Talia", role: "PhD Student", focus: "Mobile robotics and agile autonomy", source: s.srinivasaGroup },
];

const placement = (id: string, student: string, teacherId: string, company: string, role: string, source: Source): StudentPlacement => ({ id, student, teacherId, company, role, kind: "first_job", degree: "PhD", source, verifiedAt: checkedAt });
export const usCanadaRemainingPriorityPlacements2026: StudentPlacement[] = [
  placement("us-remain-goldstein-xu-google", "Zheng Xu", "tom-goldstein-umd-2026", "Google", "Researcher", s.goldsteinGroup),
  placement("us-remain-goldstein-de-deepmind", "Soham De", "tom-goldstein-umd-2026", "Google DeepMind", "Researcher", s.goldsteinGroup),
  placement("us-remain-goldstein-li-amazon", "Hao Li", "tom-goldstein-umd-2026", "Amazon Research", "Researcher", s.goldsteinGroup),
  placement("us-remain-chang-bansal-anthropic", "Hritik Bansal", "kai-wei-chang-ucla-2026", "Anthropic", "Researcher", s.changGroup),
  placement("us-remain-chang-li-openai", "Harold (Liunian) Li", "kai-wei-chang-ucla-2026", "OpenAI", "Researcher", s.changGroup),
  placement("us-remain-chang-yin-google", "Fan Yin", "kai-wei-chang-ucla-2026", "Google", "Researcher", s.changGroup),
  placement("us-remain-gomes-ament-meta", "Sebastian Ament", "carla-gomes-cornell-2026", "Meta", "Research Scientist", s.gomesGroup),
  placement("us-remain-gomes-bai-google", "Junwen Bai", "carla-gomes-cornell-2026", "Google", "Research Scientist", s.gomesGroup),
  placement("us-remain-gomes-bjorck-ms", "Johan Bjorck", "carla-gomes-cornell-2026", "Microsoft Turing", "Researcher", s.gomesGroup),
];

export const people = usCanadaRemainingPriorityPeople2026;
export const relationships = usCanadaRemainingPriorityRelationships2026;
export const groupMembers = usCanadaRemainingPriorityGroupMembers2026;
export const placements = usCanadaRemainingPriorityPlacements2026;
