import type { GroupMember, Person, Relationship, Source, StudentPlacement } from "./data";

const checkedAt = "2026-09-02";
const source = (label: string, url: string, kind: Source["kind"], supports: string): Source => ({
  label,
  url,
  kind,
  checkedAt,
  supports,
});

const sources = {
  ustcProfile: source(
    "中国科学技术大学 · 吴枫",
    "https://faculty.ustc.edu.cn/wufeng1/zh_CN/index.htm",
    "official",
    "中国科大教授、博士生导师、科技成果转化院院长（兼任），以及教育、微软亚洲研究院经历和研究方向",
  ),
  caeProfile: source(
    "中国工程院 · 吴枫院士",
    "https://www.cae.cn/cae/html/main/colys/95871425.html",
    "official",
    "多媒体压缩与网络传输专家身份，以及 2025 年当选中国工程院院士",
  ),
  ustcAward: source(
    "中国科大报 · 吴枫获 IEEE CAS Mac Van Valkenburg 奖",
    "https://zgkdb.ustc.edu.cn/ndetail/6874",
    "official",
    "网络流媒体、国际视频编码标准、IEEE 数据压缩标准及产业转化贡献",
  ),
  ustcLab: source(
    "中国科学技术大学 · 类脑智能技术及应用国家工程实验室",
    "https://leinao.ustc.edu.cn/2021/0430/c25923a483642/page.htm",
    "official",
    "稳定的教育与职业经历、实验室建设和研究方向",
  ),
  wuFirstPerson: source(
    "吴枫自述 · 我乐意给学生打工（微软亚洲研究院员工故事存档）",
    "https://blog.sina.com.cn/s/blog_4caedc7a01000awz.html",
    "profile",
    "吴枫第一人称称高文为导师，并写明 1999 年跟随高文完成博士阶段学习",
  ),
  haichuanThesis: source(
    "中国科学技术大学 · 2023 年中国科学院优秀博士学位论文材料（马海川）",
    "https://gradschool.ustc.edu.cn/static/upload/article/file/1695020709977/2ea167888edc4588a83b78a254a38407.pdf",
    "official",
    "马海川 2022 年博士毕业、博士导师吴枫、论文主题与代表性成果",
  ),
  haichuanHuawei: source(
    "华为云媒体创新 Lab · 马海川",
    "https://www.huaweicloud.com/lab/multimedia/about.html",
    "company",
    "马海川在华为云媒体创新 Lab 的公开成员记录、研究背景及 iWave / AVS3 经历",
  ),
  yindaHome: source(
    "Yinda Chen（陈胤达）· Academic Homepage",
    "https://ydchen0806.github.io/",
    "profile",
    "中国科大—上海人工智能实验室联合培养博士生身份、吴枫与熊志伟指导关系及研究方向",
  ),
  ustcMsraProgramme: source(
    "中国科学技术大学 · 微软亚洲研究院联合培养博士生项目",
    "https://sist.ustc.edu.cn/2021/0317/c5142a476799/page.htm",
    "official",
    "联合培养项目机制，以及刘东（2009）和熊志伟（2011）作为联培博士毕业后回到中国科大的记录",
  ),
  wuBook: source(
    "吴枫 · Advances in Visual Data Compression and Communication（致谢）",
    "https://api.pageplace.de/preview/DT0400.9781482234152_A25895503/preview-9781482234152_A25895503.pdf",
    "publication",
    "吴枫以第一人称明确称刘东为其在中国科大指导的博士生，并记录孙晓艳负责 MSRA 视觉编码研究、熊志伟在 MSRA 完成博士阶段研究",
  ),
  xiongUstc: source(
    "中国科学技术大学 · 熊志伟",
    "https://leinao.ustc.edu.cn/2021/0430/c25925a483538/page.htm",
    "official",
    "熊志伟的中国科大教授现职、教育经历、微软亚洲研究院任职经历和研究方向",
  ),
  xiongMicrosoftPaper: source(
    "Microsoft Research · Robust Web Image/Video Super-Resolution",
    "https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/superresolution_tip_10.pdf",
    "publication",
    "熊志伟在中国科大攻读博士且自 2007 年在微软亚洲研究院实习，并与孙晓艳、吴枫共同开展图像超分辨率研究",
  ),
  dongUstc: source(
    "中国科学技术大学 · 刘东",
    "https://faculty.ustc.edu.cn/dongeliu/zh_CN/index.htm",
    "official",
    "刘东现任教授、博士生导师、电子工程与信息科学系副主任，以及教育、任职、研究和奖励信息",
  ),
  dongMicrosoftPaper: source(
    "Microsoft Research · Manipulating Image Patches for Compression",
    "https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/inpainting_icme_08.pdf",
    "publication",
    "刘东以中国科大教育部—微软重点实验室博士生身份与孙晓艳、吴枫开展图像压缩研究",
  ),
  sunUstc: source(
    "中国科学技术大学 · 孙晓艳",
    "https://eeis.ustc.edu.cn/2022/0926/c2648a571218/page.htm",
    "official",
    "孙晓艳现任讲席教授、博士生导师、国家工程实验室副主任，以及微软亚洲研究院经历、研究和人才培养信息",
  ),
  gaoAlumni: source(
    "先进人机通信技术联合实验室 · 高文博士生名录",
    "https://www.jdl.ac.cn/rencai/taolitianxia",
    "official",
    "孙晓艳于 2003 年完成视频压缩方向博士学位、导师为高文，毕业后进入微软亚洲研究院",
  ),
  ustcHuaweiAlumni: source(
    "中国科学技术大学 · 三名毕业生入选华为“天才少年”计划",
    "https://eeis.ustc.edu.cn/2021/0812/c2706a519602/page.htm",
    "official",
    "陈畅由吴枫、熊志伟共同指导后进入华为诺亚方舟实验室；林建平由李厚强、刘东共同指导后进入华为数据存储与机器视觉部门",
  ),
};

export const wuFengNetworkPortraits: Record<string, NonNullable<Person["portrait"]>> = {
  "feng-wu-ustc": {
    src: "portraits/wu-feng-network/feng-wu-ustc.jpg",
    alt: "吴枫中国科学技术大学官方头像",
    source: sources.ustcProfile,
  },
  "haichuan-ma-huawei": {
    src: "portraits/wu-feng-network/haichuan-ma-huawei.jpg",
    alt: "马海川华为云媒体创新 Lab 官方头像",
    source: sources.haichuanHuawei,
  },
  "zhiwei-xiong-ustc": {
    src: "portraits/wu-feng-network/zhiwei-xiong-ustc.jpg",
    alt: "熊志伟中国科学技术大学官方头像",
    source: sources.xiongUstc,
  },
  "dong-liu-ustc": {
    src: "portraits/wu-feng-network/dong-liu-ustc.jpg",
    alt: "刘东中国科学技术大学官方头像",
    source: sources.dongUstc,
  },
  "xiaoyan-sun-ustc": {
    src: "portraits/wu-feng-network/xiaoyan-sun-ustc.jpg",
    alt: "孙晓艳中国科学技术大学官方头像",
    source: sources.sunUstc,
  },
};

export const wuFengNetworkPeople: Person[] = [
  {
    id: "feng-wu-ustc",
    name: "吴枫",
    role: "中国工程院院士 · 教授 · 博士生导师 · 科技成果转化院院长（兼任）",
    institution: "USTC",
    region: "Mainland China",
    area: "多媒体压缩 · 视频编码与通信 · 计算机视觉 · 智能媒体",
    tags: ["中国工程院院士", "视频编码", "多媒体通信", "计算机视觉", "智能媒体", "IEEE Fellow", "微软亚洲研究院", "高文博士谱系", "人才培养"],
    summary: "中国多媒体压缩与网络传输领域的代表性学者，长期贯通基础理论、国际标准和大规模产业应用；博士阶段由高文指导，后在微软亚洲研究院和中国科大持续建设视频编码、智能媒体与人才培养体系。",
    facts: [
      { label: "当前任职", value: "中国科学技术大学教授、博士生导师，兼任科技成果转化院院长；2025 年当选中国工程院院士。", source: sources.ustcProfile },
      { label: "研究主线", value: "视频编码与通信、多媒体内容分析、计算机视觉，以及面向智能媒体的图像和视频高效表示。", source: sources.ustcProfile },
      { label: "教育与学术训练", value: "1996 年、1999 年分别获哈尔滨工业大学计算机科学与技术硕士、博士学位；其第一人称经历明确称高文为导师。", source: sources.wuFirstPerson },
      { label: "院士与学术荣誉", value: "2025 年当选中国工程院院士；2013 年当选 IEEE Fellow；2021 年获 IEEE CAS Mac Van Valkenburg Award。", source: sources.caeProfile },
      { label: "产业研究经历", value: "1999–2014 年在微软亚洲研究院历任研究员、主任研究员和首席研究员，此后全职任教中国科大。", source: sources.ustcProfile },
      { label: "标准与产业影响", value: "多项技术被 MPEG-4、H.264、H.265 等国际标准采纳，并牵头 IEEE 数据压缩系列标准；相关编解码技术进入 Windows、华为麒麟芯片和腾讯会议等产业系统。", source: sources.ustcAward },
      { label: "已核验学生", value: "马海川的中科大优秀博士材料明确写明指导老师为吴枫；陈胤达的公开履历写明博士阶段由吴枫、熊志伟等共同指导。", source: sources.haichuanThesis },
      { label: "为什么值得关注", value: "他连接了高文的多媒体学术谱系、微软亚洲研究院的工业研究体系、中国科大的智能媒体研究，以及从博士培养到华为技术团队的人才流动。", source: sources.ustcAward },
    ],
    stage: "senior",
    category: "core",
    status: "current PI",
    primary: true,
    x: 785,
    y: 935,
    sources: [sources.ustcProfile, sources.caeProfile, sources.ustcAward, sources.ustcLab, sources.wuFirstPerson, sources.haichuanThesis, sources.yindaHome],
    portrait: wuFengNetworkPortraits["feng-wu-ustc"],
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
  },
  {
    id: "haichuan-ma-huawei",
    name: "马海川",
    role: "华为云媒体创新 Lab 研究成员（“天才少年”）",
    institution: "External",
    actualInstitution: "Huawei Cloud Media Innovation Lab",
    region: "Mainland China",
    area: "学习式图像压缩 · 视频编码 · 深度学习",
    tags: ["图像压缩", "视频编码", "深度学习", "iWave", "AVS3", "华为", "吴枫博士谱系"],
    summary: "吴枫培养的图像编码方向博士，提出学习式类小波图像压缩方法 iWave；博士毕业后进入华为云媒体创新 Lab，将学术成果延伸到标准软件与产业研发。",
    facts: [
      { label: "当前任职", value: "华为云媒体创新 Lab 公开成员，官方页面列入“天才少年”板块。", source: sources.haichuanHuawei },
      { label: "研究主线", value: "基于深度学习的图像／视频编码与处理，重点包括可学习类小波变换与端到端压缩。", source: sources.haichuanThesis },
      { label: "教育与学术训练", value: "2017 年获西安电子科技大学学士；2022 年获中国科学技术大学信息与通信工程博士，指导老师为吴枫。", source: sources.haichuanThesis },
      { label: "代表性成果", value: "iWave 被确定为 IEEE 1857.11 标准制定参考软件，并参与 AVS3 参考软件开发。", source: sources.haichuanHuawei },
      { label: "为什么值得关注", value: "他是“高文—吴枫”视频编码谱系向华为智能媒体研发流动的可核验案例。", source: sources.haichuanHuawei },
    ],
    stage: "adjacent",
    category: "adjacent",
    status: "industry researcher",
    primary: false,
    x: 865,
    y: 1000,
    sources: [sources.haichuanThesis, sources.haichuanHuawei],
    portrait: wuFengNetworkPortraits["haichuan-ma-huawei"],
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
  },
  {
    id: "zhiwei-xiong-ustc",
    name: "熊志伟",
    role: "教授 · 博士生导师",
    institution: "USTC",
    region: "Mainland China",
    area: "计算机视觉 · 计算摄影 · 低层视觉 · 生物医学图像分析",
    tags: ["计算机视觉", "计算摄影", "低层视觉", "生物医学图像", "微软亚洲研究院", "联合培养", "VIDAR"],
    summary: "中国科大—微软亚洲研究院联合培养体系中回流高校的代表学者：博士阶段在 MSRA 开展图像与视频研究，毕业后留任微软五年，2016 年回到中国科大建立计算摄影、低层视觉和脑成像分析方向。",
    facts: [
      { label: "当前任职", value: "中国科学技术大学信息科学技术学院教授、博士生导师。", source: sources.xiongUstc },
      { label: "研究主线", value: "图像处理、计算机视觉和计算摄像学，并延伸到生物医学图像分析与大规模脑成像数据处理。", source: sources.xiongUstc },
      { label: "教育与学术训练", value: "2006 年获中国科大学士学位，2011 年获中国科大电路与系统博士学位；校方将其列为中国科大—微软亚洲研究院联合培养博士。", source: sources.ustcMsraProgramme },
      { label: "微软联培经历", value: "微软论文作者简介记录其自 2007 年起在 MSRA 实习；吴枫专著进一步记录其在 MSRA 完成博士阶段研究。", source: sources.xiongMicrosoftPaper },
      { label: "职业轨迹", value: "2011–2016 年在微软亚洲研究院历任副研究员、研究员，2016 年回到中国科大任教授。", source: sources.xiongUstc },
      { label: "人才培养", value: "中国科大官方报道明确记录陈畅在研究生阶段由吴枫、熊志伟共同指导，毕业后进入华为中央研究院诺亚方舟实验室。", source: sources.ustcHuaweiAlumni },
      { label: "为什么值得关注", value: "他把 MSRA 的视觉编码与图像恢复研究传统带回中国科大，并进一步发展出计算摄影和脑成像分析方向，是这条联合培养—产业研究—高校回流链的关键节点。", source: sources.ustcMsraProgramme },
    ],
    stage: "senior",
    category: "core",
    status: "current PI",
    primary: true,
    x: 735,
    y: 995,
    sources: [sources.xiongUstc, sources.ustcMsraProgramme, sources.xiongMicrosoftPaper, sources.wuBook, sources.ustcHuaweiAlumni],
    portrait: wuFengNetworkPortraits["zhiwei-xiong-ustc"],
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
  },
  {
    id: "dong-liu-ustc",
    name: "刘东",
    role: "教授 · 博士生导师 · 电子工程与信息科学系副主任",
    institution: "USTC",
    region: "Mainland China",
    area: "图像视频压缩编码 · 视觉智能 · 学习式压缩",
    tags: ["视频编码", "图像压缩", "视觉智能", "学习式压缩", "微软联合培养", "吴枫博士谱系", "IEEE 1857.11", "VIDAR"],
    summary: "吴枫明确记录的博士生，也是中国科大—微软亚洲研究院 2009 届联合培养博士；先进入诺基亚研究院，2012 年回到中国科大，持续推动传统与学习式图像视频编码、标准化和人才培养。",
    facts: [
      { label: "当前任职", value: "中国科学技术大学教授、博士生导师、电子工程与信息科学系副主任。", source: sources.dongUstc },
      { label: "研究主线", value: "图像和视频压缩编码、视觉智能，以及端到端学习式图像／视频编码。", source: sources.dongUstc },
      { label: "教育与学术训练", value: "2004 年、2009 年分别获中国科大学士和博士学位；吴枫在专著中明确称刘东为其在中国科大指导的博士生。", source: sources.wuBook },
      { label: "微软联培经历", value: "中国科大官方将刘东列为 2009 届中科大—微软亚洲研究院联合培养博士；2008 年微软论文记录其所属中国科大教育部—微软重点实验室，并与孙晓艳、吴枫合作。", source: sources.ustcMsraProgramme },
      { label: "职业轨迹", value: "2009–2012 年任诺基亚北京研究院研究员，2012 年回到中国科大，历任副教授、特任教授和教授。", source: sources.dongUstc },
      { label: "研究与标准影响", value: "公开履历记录其发表论文 300 余篇，并任 IEEE 1857.11 标准工作小组主席；该标准获 2025 IEEE SA Emerging Technology Award。", source: sources.dongUstc },
      { label: "人才培养", value: "林建平在李厚强、刘东指导下从事深度学习视频编码，博士毕业后进入华为数据存储与机器视觉部门。", source: sources.ustcHuaweiAlumni },
      { label: "为什么值得关注", value: "他是吴枫学术培养、微软联合训练、产业研究院经历和高校回流四个环节都可被一手资料串联起来的代表节点。", source: sources.wuBook },
    ],
    stage: "senior",
    category: "core",
    status: "current PI",
    primary: true,
    x: 820,
    y: 1030,
    sources: [sources.dongUstc, sources.ustcMsraProgramme, sources.wuBook, sources.dongMicrosoftPaper, sources.ustcHuaweiAlumni],
    portrait: wuFengNetworkPortraits["dong-liu-ustc"],
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
  },
  {
    id: "xiaoyan-sun-ustc",
    name: "孙晓艳",
    role: "讲席教授 · 博士生导师 · 国家工程实验室副主任",
    institution: "USTC",
    region: "Mainland China",
    area: "视频图像处理 · 计算机视觉 · 人工智能 · 类脑计算",
    tags: ["视频编码", "图像处理", "计算机视觉", "类脑计算", "微软亚洲研究院", "高文博士谱系", "联合培养"],
    summary: "高文培养的视频压缩博士，曾在微软亚洲研究院工作近十六年并负责视觉编码研究，2019 年回到中国科大任讲席教授；她是吴枫—联合培养博士团队之间不可忽略的研究指导与协作枢纽。",
    facts: [
      { label: "当前任职", value: "中国科学技术大学信息学院讲席教授、博士生导师、类脑智能技术及应用国家工程实验室副主任。", source: sources.sunUstc },
      { label: "研究主线", value: "视频图像处理、计算机视觉、人工智能与类脑计算。", source: sources.sunUstc },
      { label: "教育与学术训练", value: "1997、1999、2003 年分别获哈尔滨工业大学学士、硕士、博士学位；JDL 官方博士生名录明确列高文为其博士导师。", source: sources.gaoAlumni },
      { label: "微软研究经历", value: "2003–2019 年在微软亚洲研究院历任研究员、主管研究员和资深研究员；吴枫专著记录其负责团队的视觉编码研究。", source: sources.sunUstc },
      { label: "研究协作角色", value: "微软官方论文记录她与博士阶段的熊志伟、刘东及吴枫共同开展图像恢复和图像编码研究。", source: sources.xiongMicrosoftPaper },
      { label: "人才培养与流动", value: "中国科大公开招募信息说明其团队可推荐学生赴微软、字节跳动、腾讯等研究机构访问或联合培养。", source: sources.sunUstc },
      { label: "为什么值得关注", value: "她既连接高文博士谱系与 MSRA Internet Media Group，也连接 2019 年后的中国科大视觉、视频编码和类脑计算团队。", source: sources.gaoAlumni },
    ],
    stage: "senior",
    category: "core",
    status: "current PI",
    primary: true,
    x: 875,
    y: 930,
    sources: [sources.sunUstc, sources.gaoAlumni, sources.wuBook, sources.xiongMicrosoftPaper, sources.dongMicrosoftPaper],
    portrait: wuFengNetworkPortraits["xiaoyan-sun-ustc"],
    introducedAt: checkedAt,
    lastVerifiedAt: checkedAt,
  },
];

export const wuFengNetworkRelationships: Relationship[] = [
  {
    id: "gao-wen-feng-wu-phd",
    from: "gao-wen-pku",
    to: "feng-wu-ustc",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "吴枫在第一人称经历中称高文为导师，并写明 1999 年跟随高文完成博士阶段学习。",
    evidenceObject: "吴枫第一人称学术经历",
    source: sources.wuFirstPerson,
    verified: true,
    endYear: 1999,
  },
  {
    id: "feng-wu-haichuan-ma-phd",
    from: "feng-wu-ustc",
    to: "haichuan-ma-huawei",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "中国科大 2023 年中国科学院优秀博士学位论文材料明确写明马海川在中国科大攻读博士、指导老师为吴枫教授。",
    evidenceObject: "中国科学院优秀博士学位论文材料",
    source: sources.haichuanThesis,
    verified: true,
    endYear: 2022,
  },
  {
    id: "gao-wen-xiaoyan-sun-phd",
    from: "gao-wen-pku",
    to: "xiaoyan-sun-ustc",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "JDL 先进人机通信技术联合实验室博士生名录明确列孙晓艳于 2003 年完成视频压缩方向博士学位、导师为高文。",
    evidenceObject: "JDL 博士生名录",
    source: sources.gaoAlumni,
    verified: true,
    endYear: 2003,
  },
  {
    id: "feng-wu-dong-liu-phd",
    from: "feng-wu-ustc",
    to: "dong-liu-ustc",
    type: "lineage",
    subtype: "phd_adviser",
    label: "博士导师",
    evidence: "吴枫在专著致谢中以第一人称明确写明刘东是其在中国科大指导的博士生；校方同时将刘东列为 2009 届中科大—微软亚洲研究院联合培养博士。",
    evidenceObject: "导师第一人称专著记录 + 联培项目校方记录",
    source: sources.wuBook,
    verified: true,
    endYear: 2009,
  },
  {
    id: "feng-wu-zhiwei-xiong-msra-training",
    from: "feng-wu-ustc",
    to: "zhiwei-xiong-ustc",
    type: "lineage",
    subtype: "other",
    label: "MSRA 联合培养研究指导",
    evidence: "中国科大将熊志伟列为 2011 届 MSRA 联培博士；微软论文记录其 2007 年起在 MSRA 实习并与吴枫、孙晓艳开展博士阶段研究，吴枫专著记录其在 MSRA 完成博士研究。现有一手材料未将此边升级为正式学位导师。",
    evidenceObject: "联合培养项目记录 + 博士阶段微软论文 + 吴枫专著",
    source: sources.ustcMsraProgramme,
    verified: true,
    startYear: 2007,
    endYear: 2011,
  },
  {
    id: "feng-wu-xiaoyan-sun-msra-collaboration",
    from: "feng-wu-ustc",
    to: "xiaoyan-sun-ustc",
    type: "collaboration",
    subtype: "sustained_collaboration",
    label: "MSRA 视觉编码长期合作",
    evidence: "吴枫专著记录孙晓艳负责 MSRA 团队的视觉编码研究；微软公开论文保留二人在视频／图像编码方向多年的共同成果。",
    evidenceObject: "MSRA 团队记录与连续论文",
    source: sources.wuBook,
    verified: true,
    startYear: 2003,
    endYear: 2014,
  },
  {
    id: "xiaoyan-sun-zhiwei-xiong-msra-collaboration",
    from: "xiaoyan-sun-ustc",
    to: "zhiwei-xiong-ustc",
    type: "collaboration",
    subtype: "sustained_collaboration",
    label: "MSRA 联培阶段视觉研究合作",
    evidence: "微软论文记录熊志伟在博士阶段进入 MSRA 实习，并与孙晓艳、吴枫连续开展图像超分辨率、图像编码与恢复研究。",
    evidenceObject: "微软官方论文与作者履历",
    source: sources.xiongMicrosoftPaper,
    verified: true,
    startYear: 2007,
    endYear: 2016,
  },
  {
    id: "xiaoyan-sun-dong-liu-msra-collaboration",
    from: "xiaoyan-sun-ustc",
    to: "dong-liu-ustc",
    type: "collaboration",
    subtype: "sustained_collaboration",
    label: "MSRA 联培阶段视觉编码合作",
    evidence: "微软公开论文记录中国科大博士生刘东与 MSRA 的孙晓艳、吴枫共同开展图像编码研究；吴枫专著将三人列入同一视觉编码研究线。",
    evidenceObject: "微软官方论文 + 吴枫专著",
    source: sources.dongMicrosoftPaper,
    verified: true,
    startYear: 2005,
    endYear: 2009,
  },
];

export const wuFengNetworkGroupMembers: GroupMember[] = [
  {
    id: "wu-feng-yinda-chen-current-phd",
    teacherId: "feng-wu-ustc",
    name: "陈胤达（Yinda Chen）",
    role: "联合培养博士生 · 预计 2027",
    focus: "自监督预训练 · 多模态大模型 · 世界模型 · 图像编码；与上海人工智能实验室联合培养，吴枫、熊志伟等指导",
    source: sources.yindaHome,
  },
  {
    id: "wu-feng-haichuan-ma-alumnus",
    teacherId: "feng-wu-ustc",
    name: "马海川",
    role: "博士校友 · 2022",
    focus: "学习式图像压缩 · iWave；现进入华为云媒体创新 Lab",
    source: sources.haichuanThesis,
  },
  {
    id: "zhiwei-xiong-yinda-chen-current-phd",
    teacherId: "zhiwei-xiong-ustc",
    name: "陈胤达（Yinda Chen）",
    role: "联合培养博士生 · 预计 2027",
    focus: "自监督预训练 · 多模态大模型 · 世界模型 · 图像编码；公开履历列吴枫、熊志伟等共同指导",
    source: sources.yindaHome,
  },
  {
    id: "zhiwei-xiong-chang-chen-alumnus",
    teacherId: "zhiwei-xiong-ustc",
    name: "陈畅",
    role: "博士校友 · 吴枫 / 熊志伟共同指导",
    focus: "低层视觉 · 计算摄影；毕业后进入华为诺亚方舟实验室",
    source: sources.ustcHuaweiAlumni,
  },
  {
    id: "dong-liu-jianping-lin-alumnus",
    teacherId: "dong-liu-ustc",
    name: "林建平",
    role: "博士校友 · 李厚强 / 刘东共同指导",
    focus: "深度学习视频编码；毕业后进入华为数据存储与机器视觉部门",
    source: sources.ustcHuaweiAlumni,
  },
];

export const wuFengNetworkPlacements: StudentPlacement[] = [
  {
    id: "wu-feng-haichuan-ma-huawei",
    student: "马海川",
    teacherId: "feng-wu-ustc",
    company: "Huawei",
    department: "华为云媒体创新 Lab",
    role: "研究成员（官方页面列入“天才少年”板块）",
    kind: "current",
    sector: "industry",
    degree: "PhD",
    graduationYear: 2022,
    currentRole: "华为云媒体创新 Lab 研究成员",
    note: "中科大优秀博士材料留有 @huawei.com 邮箱；华为云官方成员页记录其博士背景与 iWave / AVS3 工作。",
    source: sources.haichuanHuawei,
    verifiedAt: checkedAt,
  },
  {
    id: "wu-feng-dong-liu-nokia",
    student: "刘东",
    teacherId: "feng-wu-ustc",
    company: "Nokia Research Center",
    department: "Nokia Research Center Beijing",
    role: "Member of Research Staff（博士毕业后首份工作）",
    kind: "first_job",
    degree: "PhD",
    graduationYear: 2009,
    firstJob: "Nokia Research Center Beijing · Member of Research Staff",
    currentRole: "中国科学技术大学教授、电子工程与信息科学系副主任",
    sector: "industry",
    note: "吴枫专著与刘东官方履历共同闭合“博士培养—诺基亚研究院—中国科大回流”的路径。",
    source: sources.dongUstc,
    verifiedAt: checkedAt,
  },
  {
    id: "gao-wen-xiaoyan-sun-msra",
    student: "孙晓艳",
    teacherId: "gao-wen-pku",
    company: "Microsoft Research Asia",
    department: "Internet Media / Vision-based Coding",
    role: "Researcher → Lead / Senior Researcher（2003–2019）",
    kind: "first_job",
    highLevel: true,
    degree: "PhD",
    graduationYear: 2003,
    firstJob: "Microsoft Research Asia · Researcher",
    currentRole: "中国科学技术大学讲席教授、国家工程实验室副主任",
    sector: "industry",
    note: "JDL 名录记录博士导师与毕业去向；中国科大官方履历记录其 2019 年从微软回到高校。",
    source: sources.sunUstc,
    verifiedAt: checkedAt,
  },
  {
    id: "zhiwei-xiong-chang-chen-huawei",
    student: "陈畅",
    teacherId: "zhiwei-xiong-ustc",
    company: "Huawei",
    department: "中央研究院 · 诺亚方舟实验室",
    role: "计算机视觉研究工程师",
    kind: "current",
    degree: "PhD",
    currentRole: "华为中央研究院诺亚方舟实验室计算机视觉研究工程师",
    coAdvisers: ["吴枫"],
    sector: "industry",
    source: sources.ustcHuaweiAlumni,
    verifiedAt: checkedAt,
  },
  {
    id: "dong-liu-jianping-lin-huawei",
    student: "林建平",
    teacherId: "dong-liu-ustc",
    company: "Huawei",
    department: "数据存储与机器视觉部门",
    role: "视频压缩算法研究",
    kind: "current",
    degree: "PhD",
    graduationYear: 2021,
    currentRole: "华为数据存储与机器视觉部门视频压缩算法研究",
    coAdvisers: ["李厚强"],
    sector: "industry",
    source: sources.ustcHuaweiAlumni,
    verifiedAt: checkedAt,
  },
];
